FastLED: fl::Callback< Args > Class Template Reference
fl::Callback< Args > Class Template Reference
Detailed Description
template<typename ... Args>
class fl::Callback< Args >
Definition at line 13 of file callback.h.
#include <callback.h>
Public Member Functions
Callback ()=default
Callback (const Callback &)=default
Callback (void *(*callback)(Args... args))
Callback (void *self, void(*callback)(void *self, Args... args))
void clear ()
operator bool () const
bool operator!= (const Callback &other) const
void operator() (Args... args) const
bool operator< (const Callback &other) const
Callback & operator= (const Callback &other)
Callback & operator= (void *(*other)(Args... args))
Callback & operator= (void(*other)(void *self, Args... args))
bool operator== (const Callback &other) const
Private Attributes
void(* callback)(void *self, Args... args) = nullptr
void * self = nullptr
Constructor & Destructor Documentation
Callback() [1/4]
template<typename ... Args> fl::Callback< Args >::Callback () default
Callback() [2/4]
template<typename ... Args> fl::Callback< Args >::Callback (void * self, void(* callback)(void *self, Args... args)) inline
Definition at line 17 of file callback.h.
: self(self), callback(callback) {}
Callback() [3/4]
template<typename ... Args> fl::Callback< Args >::Callback (void *(* callback)(Args... args)) inline explicit
Definition at line 19 of file callback.h.
: self(nullptr), callback((void (*)(void*, Args...))callback) {}
Callback() [4/4]
template<typename ... Args> fl::Callback< Args >::Callback (const Callback< Args > &) default
Member Function Documentation
clear()
template<typename ... Args> void fl::Callback< Args >::clear () inline
Definition at line 23 of file callback.h.
{ callback = nullptr; self = nullptr; }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator bool()
template<typename ... Args> fl::Callback< Args >::operator bool () const inline
Definition at line 21 of file callback.h.
{ return callback != nullptr; }
References fl::Callback< Args >::callback.
operator!=()
template<typename ... Args> bool fl::Callback< Args >::operator!= (const Callback< Args > & other) const inline
Definition at line 25 of file callback.h.
{ return !(*this == other); }
operator()()
template<typename ... Args> void fl::Callback< Args >::operator() (Args... args) const inline
Definition at line 22 of file callback.h.
{ if (callback) callback(self, args...); }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator<()
template<typename ... Args> bool fl::Callback< Args >::operator< (const Callback< Args > & other) const inline
Definition at line 30 of file callback.h.
{ return self < other.self || (self == other.self && callback < other.callback); }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator=() [1/3]
template<typename ... Args> Callback & fl::Callback< Args >::operator= (const Callback< Args > & other) inline
Definition at line 26 of file callback.h.
{ self = other.self; callback = other.callback; return *this; }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator=() [2/3]
template<typename ... Args> Callback & fl::Callback< Args >::operator= (void *(* other)(Args... args)) inline
Definition at line 27 of file callback.h.
{ self = nullptr; callback = (void (*)(void*, Args...))other; return *this; }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator=() [3/3]
template<typename ... Args> Callback & fl::Callback< Args >::operator= (void(* other)(void *self, Args... args)) inline
Definition at line 28 of file callback.h.
{ self = nullptr; callback = other; return *this; }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
operator==()
template<typename ... Args> bool fl::Callback< Args >::operator== (const Callback< Args > & other) const inline
Definition at line 24 of file callback.h.
{ return self == other.self && callback == other.callback; }
References fl::Callback< Args >::callback, and fl::Callback< Args >::self.
Member Data Documentation
callback
template<typename ... Args> void(* fl::Callback< Args >::callback) (void *self, Args... args) = nullptr private
Definition at line 33 of file callback.h.
Referenced by fl::Callback< Args >::clear(), fl::Callback< Args >::operator bool(), fl::Callback< Args >::operator()(), fl::Callback< Args >::operator<(), fl::Callback< Args >::operator=(), fl::Callback< Args >::operator=(), fl::Callback< Args >::operator=(), and fl::Callback< Args >::operator==().
self
template<typename ... Args> void* fl::Callback< Args >::self = nullptr private
Definition at line 32 of file callback.h.
Referenced by fl::Callback< Args >::clear(), fl::Callback< Args >::operator()(), fl::Callback< Args >::operator<(), fl::Callback< Args >::operator=(), fl::Callback< Args >::operator=(), fl::Callback< Args >::operator=(), and fl::Callback< Args >::operator==().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/callback.h