FastLED: /home/runner/work/FastLED/FastLED/examples/NoisePlusPalette/NoisePlusPalette.ino File Reference
NoisePlusPalette.ino File Reference
Detailed Description
Demonstrates how to mix noise generation with color palettes on a 2D LED matrix.
Definition in file NoisePlusPalette.ino.
#include <FastLED.h>
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define HOLD_PALETTES_X_TIMES_AS_LONG 1
#define LED_PIN 3
#define LED_TYPE WS2811
#define MAX_DIMENSION ((kMatrixWidth>kMatrixHeight) ? kMatrixWidth : kMatrixHeight)
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Functions
void ChangePaletteAndSettingsPeriodically ()
void fillnoise8 ()
void loop ()
void mapNoiseToLEDsUsingPalette ()
void setup ()
void SetupBlackAndWhiteStripedPalette ()
void SetupPurpleAndGreenPalette ()
void SetupRandomPalette ()
uint16_t XY (uint8_t x, uint8_t y)
Variables
uint8_t colorLoop = 1
CRGBPalette16 currentPalette (PartyColors_p)
const uint8_t kMatrixHeight = 16
const bool kMatrixSerpentineLayout = true
const uint8_t kMatrixWidth = 16
CRGB leds [kMatrixWidth *kMatrixHeight]
uint8_t noise [MAX_DIMENSION][MAX_DIMENSION]
uint16_t scale = 30
uint16_t speed = 20
static uint16_t x
static uint16_t y
static uint16_t z
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 14 of file NoisePlusPalette.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 16 of file NoisePlusPalette.ino.
HOLD_PALETTES_X_TIMES_AS_LONG
#define HOLD_PALETTES_X_TIMES_AS_LONG 1
Examples
NoisePlusPalette.ino.
Definition at line 210 of file NoisePlusPalette.ino.
Referenced by ChangePaletteAndSettingsPeriodically().
LED_PIN
#define LED_PIN 3
Definition at line 13 of file NoisePlusPalette.ino.
LED_TYPE
#define LED_TYPE WS2811
Definition at line 15 of file NoisePlusPalette.ino.
MAX_DIMENSION
#define MAX_DIMENSION ((kMatrixWidth>kMatrixHeight) ? kMatrixWidth : kMatrixHeight)
Definition at line 53 of file NoisePlusPalette.ino.
NUM_LEDS
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Definition at line 52 of file NoisePlusPalette.ino.
Function Documentation
ChangePaletteAndSettingsPeriodically()
void ChangePaletteAndSettingsPeriodically ()
Examples
NoisePlusPalette.ino.
Definition at line 212 of file NoisePlusPalette.ino.
{
  uint8_t secondHand = ((millis() / 1000) / HOLD_PALETTES_X_TIMES_AS_LONG) % 60;
  static uint8_t lastSecond = 99;
  if( lastSecond != secondHand) {
    lastSecond = secondHand;
    if( secondHand ==  0)  { currentPalette = RainbowColors_p;         speed = 20; scale = 30; colorLoop = 1; }
    if( secondHand ==  5)  { SetupPurpleAndGreenPalette();             speed = 10; scale = 50; colorLoop = 1; }
    if( secondHand == 10)  { SetupBlackAndWhiteStripedPalette();       speed = 20; scale = 30; colorLoop = 1; }
    if( secondHand == 15)  { currentPalette = ForestColors_p;          speed =  8; scale =120; colorLoop = 0; }
    if( secondHand == 20)  { currentPalette = CloudColors_p;           speed =  4; scale = 30; colorLoop = 0; }
    if( secondHand == 25)  { currentPalette = LavaColors_p;            speed =  8; scale = 50; colorLoop = 0; }
    if( secondHand == 30)  { currentPalette = OceanColors_p;           speed = 20; scale = 90; colorLoop = 0; }
    if( secondHand == 35)  { currentPalette = PartyColors_p;           speed = 20; scale = 30; colorLoop = 1; }
    if( secondHand == 40)  { SetupRandomPalette();                     speed = 20; scale = 20; colorLoop = 1; }
    if( secondHand == 45)  { SetupRandomPalette();                     speed = 50; scale = 50; colorLoop = 1; }
    if( secondHand == 50)  { SetupRandomPalette();                     speed = 90; scale = 90; colorLoop = 1; }
    if( secondHand == 55)  { currentPalette = RainbowStripeColors_p;   speed = 30; scale = 20; colorLoop = 1; }
  }
}
References CloudColors_p, colorLoop, currentPalette, ForestColors_p, HOLD_PALETTES_X_TIMES_AS_LONG, LavaColors_p, OceanColors_p, PartyColors_p, RainbowColors_p, RainbowStripeColors_p, scale, SetupBlackAndWhiteStripedPalette(), SetupPurpleAndGreenPalette(), SetupRandomPalette(), and speed.
Referenced by loop().
fillnoise8()
void fillnoise8 ()
Definition at line 107 of file NoisePlusPalette.ino.
                  {
  // If we're runing at a low "speed", some 8-bit artifacts become visible
  // from frame-to-frame.  In order to reduce this, we can do some fast data-smoothing.
  // The amount of data smoothing we're doing depends on "speed".
  uint8_t dataSmoothing = 0;
  if( speed < 50) {
    dataSmoothing = 200 - (speed * 4);
  }
  for(int i = 0; i < MAX_DIMENSION; i++) {
    int ioffset = scale * i;
    for(int j = 0; j < MAX_DIMENSION; j++) {
      int joffset = scale * j;
      uint8_t data = inoise8(x + ioffset,y + joffset,z);
      // The range of the inoise8 function is roughly 16-238.
      // These two operations expand those values out to roughly 0..255
      // You can comment them out if you want the raw noise data.
      data = qsub8(data,16);
      data = qadd8(data,scale8(data,39));
      if( dataSmoothing ) {
        uint8_t olddata = noise[i][j];
        uint8_t newdata = scale8( olddata, dataSmoothing) + scale8( data, 256 - dataSmoothing);
        data = newdata;
      }
      noise[i][j] = data;
    }
  }
  z += speed;
  // apply slow drift to X and Y, just for visual variation.
  x += speed / 8;
  y -= speed / 16;
}
References inoise8(), MAX_DIMENSION, noise, qadd8(), qsub8(), scale, scale8(), speed, x, y, and z.
loop()
void loop ()
Definition at line 182 of file NoisePlusPalette.ino.
            {
  // Periodically choose a new palette, speed, and scale
  ChangePaletteAndSettingsPeriodically();
  // generate noise data
  fillnoise8();
  // convert the noise data to colors in the LED array
  // using the current palette
  mapNoiseToLEDsUsingPalette();
  FastLED.show();
  // delay(10);
}
References ChangePaletteAndSettingsPeriodically(), FastLED, fillnoise8(), mapNoiseToLEDsUsingPalette(), and CFastLED::show().
mapNoiseToLEDsUsingPalette()
void mapNoiseToLEDsUsingPalette ()
Examples
NoisePlusPalette.ino.
Definition at line 148 of file NoisePlusPalette.ino.
{
  static uint8_t ihue=0;
  for(int i = 0; i < kMatrixWidth; i++) {
    for(int j = 0; j < kMatrixHeight; j++) {
      // We use the value at the (i,j) coordinate in the noise
      // array for our brightness, and the flipped value from (j,i)
      // for our pixel's index into the color palette.
      uint8_t index = noise[j][i];
      uint8_t bri =   noise[i][j];
      // if this palette is a 'loop', add a slowly-changing base value
      if( colorLoop) {
        index += ihue;
      }
      // brighten up, as the color palette itself often contains the
      // light/dark dynamic range desired
      if( bri > 127 ) {
        bri = 255;
      } else {
        bri = dim8_raw( bri * 2);
      }
      CRGB color = ColorFromPalette( currentPalette, index, bri);
      leds[XY(i,j)] = color;
    }
  }
  ihue+=1;
}
References ColorFromPalette(), colorLoop, currentPalette, dim8_raw(), kMatrixHeight, kMatrixWidth, leds, noise, and XY().
Referenced by fl::NoisePalette::draw(), and loop().
setup()
void setup ()
Definition at line 93 of file NoisePlusPalette.ino.
             {
  delay(3000);
  FastLED.addLeds<LED_TYPE,LED_PIN,COLOR_ORDER>(leds,NUM_LEDS);
  FastLED.setBrightness(BRIGHTNESS);
  // Initialize our coordinates to some random values
  x = random16();
  y = random16();
  z = random16();
}
References CFastLED::addLeds(), BRIGHTNESS, COLOR_ORDER, FastLED, LED_PIN, LED_TYPE, leds, NUM_LEDS, random16(), CFastLED::setBrightness(), x, y, and z.
SetupBlackAndWhiteStripedPalette()
void SetupBlackAndWhiteStripedPalette ()
Definition at line 255 of file NoisePlusPalette.ino.
{
  // 'black out' all 16 palette entries...
  fill_solid( currentPalette, 16, CRGB::Black);
  // and set every fourth one to white.
  currentPalette[0] = CRGB::White;
  currentPalette[4] = CRGB::White;
  currentPalette[8] = CRGB::White;
  currentPalette[12] = CRGB::White;
}
References CRGB::Black, currentPalette, fill_solid(), and CRGB::White.
SetupPurpleAndGreenPalette()
void SetupPurpleAndGreenPalette ()
Definition at line 268 of file NoisePlusPalette.ino.
{
  CRGB purple = CHSV( HUE_PURPLE, 255, 255);
  CRGB green  = CHSV( HUE_GREEN, 255, 255);
  CRGB black  = CRGB::Black;
  currentPalette = CRGBPalette16(
    green,  green,  black,  black,
    purple, purple, black,  black,
    green,  green,  black,  black,
    purple, purple, black,  black );
}
References CRGB::Black, currentPalette, HUE_GREEN, and HUE_PURPLE.
SetupRandomPalette()
void SetupRandomPalette ()
Examples
NoisePlusPalette.ino.
Definition at line 241 of file NoisePlusPalette.ino.
{
  currentPalette = CRGBPalette16(
                      CHSV( random8(), 255, 32),
                      CHSV( random8(), 255, 255),
                      CHSV( random8(), 128, 255),
                      CHSV( random8(), 255, 255));
}
References currentPalette, and random8().
Referenced by ChangePaletteAndSettingsPeriodically().
XY()
uint16_t XY (uint8_t x, uint8_t y)
Definition at line 285 of file NoisePlusPalette.ino.
{
  uint16_t i;
  if( kMatrixSerpentineLayout == false) {
    i = (y * kMatrixWidth) + x;
  }
  if( kMatrixSerpentineLayout == true) {
    if( y & 0x01) {
      // Odd rows run backwards
      uint8_t reverseX = (kMatrixWidth - 1) - x;
      i = (y * kMatrixWidth) + reverseX;
    } else {
      // Even rows run forwards
      i = (y * kMatrixWidth) + x;
    }
  }
  return i;
}
References kMatrixSerpentineLayout, kMatrixWidth, x, and y.
Variable Documentation
colorLoop
uint8_t colorLoop = 1
Examples
NoisePlusPalette.ino.
Definition at line 79 of file NoisePlusPalette.ino.
Referenced by ChangePaletteAndSettingsPeriodically(), and mapNoiseToLEDsUsingPalette().
currentPalette
CRGBPalette16 currentPalette(PartyColors_p) (PartyColors_p)
kMatrixHeight
const uint8_t kMatrixHeight = 16
Definition at line 20 of file NoisePlusPalette.ino.
kMatrixSerpentineLayout
const bool kMatrixSerpentineLayout = true
Definition at line 23 of file NoisePlusPalette.ino.
kMatrixWidth
const uint8_t kMatrixWidth = 16
Definition at line 19 of file NoisePlusPalette.ino.
leds
CRGB leds[kMatrixWidth *kMatrixHeight]
Definition at line 56 of file NoisePlusPalette.ino.
noise
uint8_t noise[MAX_DIMENSION][MAX_DIMENSION]
Definition at line 76 of file NoisePlusPalette.ino.
scale
uint16_t scale = 30
Definition at line 73 of file NoisePlusPalette.ino.
speed
uint16_t speed = 20
Definition at line 67 of file NoisePlusPalette.ino.
x
uint16_t x static
Definition at line 59 of file NoisePlusPalette.ino.
y
uint16_t y static
Definition at line 60 of file NoisePlusPalette.ino.
z
uint16_t z static
Definition at line 61 of file NoisePlusPalette.ino.