FastLED: CountingButton Class Reference
CountingButton Class Reference
Detailed Description
Definition at line 101 of file buttons.h.
#include <buttons.h>
Public Member Functions
CountingButton (int but_pin)
int curr_val () const
void Update (uint32_t time_now)
Private Member Functions
bool Read ()
Private Attributes
DigitalButton button_
int curr_val_
unsigned long debounce_timestamp_
UIButton mButton = UIButton("Counting UIButton")
bool on_
Constructor & Destructor Documentation
CountingButton()
CountingButton::CountingButton (int but_pin) inline explicit
Definition at line 103 of file buttons.h.
                                       : button_(but_pin), curr_val_(0) {
    debounce_timestamp_ = millis();
    on_ = Read();
  }
References debounce_timestamp_, on_, and Read().
Member Function Documentation
curr_val()
int CountingButton::curr_val () const inline
Definition at line 133 of file buttons.h.
{ return curr_val_; }
References curr_val_.
Referenced by ColorSelector::curr_val().
Read()
bool CountingButton::Read () inline private
Definition at line 136 of file buttons.h.
              {
    return button_.Read();
  }
References button_, and MidiShieldButton::Read().
Referenced by CountingButton(), and Update().
Update()
void CountingButton::Update (uint32_t time_now) inline
Definition at line 108 of file buttons.h.
{
    bool clicked = mButton.clicked();
    FASTLED_DBG("clicked: " << clicked);
    bool val = Read() || mButton.clicked();
    bool changed = val != on_;
    if (clicked) {
      ++curr_val_;
      debounce_timestamp_ = time_now;
      return;
    }
    if (changed) {  // Has the toggle switch changed?
      on_ = val;       // Set the new toggle switch value.
      // Protect against debouncing artifacts by putting a 200ms delay from the
      // last time the value changed.
      if ((time_now - debounce_timestamp_) > 16) {
        if (on_) {
          ++curr_val_;     // ... and increment the value.
        }
        debounce_timestamp_ = time_now;
      }
    }
  }
References fl::UIButton::clicked(), curr_val_, debounce_timestamp_, FASTLED_DBG, mButton, on_, and Read().
Referenced by ColorSelector::Update().
Member Data Documentation
button_
DigitalButton CountingButton::button_ private
Definition at line 140 of file buttons.h.
Referenced by Read().
curr_val_
int CountingButton::curr_val_ private
Definition at line 142 of file buttons.h.
Referenced by curr_val(), and Update().
debounce_timestamp_
unsigned long CountingButton::debounce_timestamp_ private
Definition at line 143 of file buttons.h.
Referenced by CountingButton(), and Update().
mButton
UIButton CountingButton::mButton = UIButton("Counting UIButton") private
Definition at line 144 of file buttons.h.
Referenced by Update().
on_
bool CountingButton::on_ private
Definition at line 141 of file buttons.h.
Referenced by CountingButton(), and Update().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/arduino/buttons.h