FastLED: fl::WeakReferent Class Reference
fl::WeakReferent Class Reference
Detailed Description
Definition at line 247 of file ptr.h.
#include <ptr.h>
Public Member Functions
WeakReferent ()
~WeakReferent ()
void destroy ()
Referent * getReferent () const
void ref ()
int ref_count () const
void setReferent (Referent *referent)
void unref ()
Protected Member Functions
WeakReferent (const WeakReferent &)=default
WeakReferent (WeakReferent &&)=default
WeakReferent & operator= (const WeakReferent &)=default
WeakReferent & operator= (WeakReferent &&)=default
Private Attributes
int mRefCount
Referent * mReferent
Constructor & Destructor Documentation
WeakReferent() [1/3]
fl::WeakReferent::WeakReferent () inline
Definition at line 249 of file ptr.h.
: mRefCount(0), mReferent(nullptr) {}
~WeakReferent()
fl::WeakReferent::~WeakReferent () inline
Definition at line 250 of file ptr.h.
{}
WeakReferent() [2/3]
fl::WeakReferent::WeakReferent (const WeakReferent &) protected default
WeakReferent() [3/3]
fl::WeakReferent::WeakReferent (WeakReferent &&) protected default
Member Function Documentation
destroy()
void fl::WeakReferent::destroy () inline
Definition at line 259 of file ptr.h.
{ delete this; }
Referenced by unref().
getReferent()
Referent * fl::WeakReferent::getReferent () const inline
Definition at line 261 of file ptr.h.
{ return mReferent; }
References mReferent.
Referenced by fl::Ptr< T >::weakRefNoCreate().
operator=() [1/2]
WeakReferent & fl::WeakReferent::operator= (const WeakReferent &) protected default
operator=() [2/2]
WeakReferent & fl::WeakReferent::operator= (WeakReferent &&) protected default
ref()
void fl::WeakReferent::ref () inline
Definition at line 252 of file ptr.h.
{ mRefCount++; }
References mRefCount.
ref_count()
int fl::WeakReferent::ref_count () const inline
Definition at line 253 of file ptr.h.
{ return mRefCount; }
References mRefCount.
setReferent()
void fl::WeakReferent::setReferent (Referent * referent) inline
Definition at line 260 of file ptr.h.
{ mReferent = referent; }
References mReferent.
unref()
void fl::WeakReferent::unref () inline
Definition at line 254 of file ptr.h.
                 {
        if (--mRefCount == 0) {
            destroy();
        }
    }
References destroy(), and mRefCount.
Member Data Documentation
mRefCount
int fl::WeakReferent::mRefCount mutable private
Definition at line 270 of file ptr.h.
Referenced by ref(), ref_count(), and unref().
mReferent
Referent* fl::WeakReferent::mReferent private
Definition at line 271 of file ptr.h.
Referenced by getReferent(), and setReferent().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ptr.h