FastLED: fl::PtrTraits< T > Class Template Reference
fl::PtrTraits< T > Class Template Reference
Detailed Description
template<typename T>
class fl::PtrTraits< T >
Definition at line 47 of file ptr.h.
#include <ptr.h>
Public Types
using element_type = T
using ptr_type = Ptr<T>
Static Public Member Functions
static Ptr< T > New ()
template<typename... Args>
static Ptr< T > New (Args... args)
Member Typedef Documentation
element_type
template<typename T > using fl::PtrTraits< T >::element_type = T
Definition at line 49 of file ptr.h.
ptr_type
template<typename T > using fl::PtrTraits< T >::ptr_type = Ptr<T>
Definition at line 50 of file ptr.h.
Member Function Documentation
New() [1/2]
template<typename T > static Ptr< T > fl::PtrTraits< T >::New () inline static
Definition at line 57 of file ptr.h.
{
        T *ptr = new T();
        return Ptr<T>::TakeOwnership(ptr);
    }
References fl::Ptr< T >::TakeOwnership().
Referenced by fl::WeakPtr< T >::WeakPtr(), fl::WeakPtr< T >::WeakPtr(), and fl::Ptr< T >::New().
New() [2/2]
template<typename T > template<typename... Args> static Ptr< T > fl::PtrTraits< T >::New (Args... args) inline static
Definition at line 52 of file ptr.h.
{
        T *ptr = new T(args...);
        return Ptr<T>::TakeOwnership(ptr);
    }
References fl::Ptr< T >::TakeOwnership().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ptr.h