FastLED: gen Namespace Reference
gen Namespace Reference
Detailed Description
Generates the hexegon using math.
Classes
class HexagonAngle
class Point
Functions
list[Point] find_green_anchore_point ()
list[Point] find_red_anchor_point ()
list[Point] gen_points (list[HexagonAngle] input, int leds_per_strip, Point startPos, list[int]|None exclude=None, bool add_last=False)
list[Point] generate_black_points ()
list[Point] generate_blue_points ()
list[Point] generate_green_points ()
list[Point] generate_red_points ()
None main ()
Point next_point (Point pos, HexagonAngle angle, float space)
None simple_test ()
float toRads (float angle)
None two_angle_test ()
None two_angle_test2 ()
None unit_test ()
Variables
BLACK_ANCHOR_POINT = Point(0,0)
BLUE_ANCHOR_POINT = Point(0, 0)
list[Point] GREEN_ANCHOR_POINT = find_green_anchore_point()[-1]
float LED_DIAMETER = SPACE_PER_LED / 4
int LED_PER_STRIP = 14
bool MIRROR_X = True
list[Point] RED_ANCHOR_POINT = find_red_anchor_point()[-1]
int SMALLEST_ANGLE = 360 / 6
float SPACE_PER_LED = 30.0
Function Documentation
find_green_anchore_point()
list[Point] gen.find_green_anchore_point ()
Definition at line 161 of file gen.py.
def find_green_anchore_point() -> list[Point]:
    hexagon_angles = [
        HexagonAngle.RIGHT_UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, Point(0, 0), add_last=True)
    return points
References gen_points().
find_red_anchor_point()
list[Point] gen.find_red_anchor_point ()
Definition at line 151 of file gen.py.
def find_red_anchor_point() -> list[Point]:
    hexagon_angles = [
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, Point(0, 0), add_last=True)
    return points
References gen_points().
gen_points()
list[Point] gen.gen_points (list[HexagonAngle] input, int leds_per_strip, Point startPos, list[int] | None exclude = None, bool add_last = False)
Definition at line 68 of file gen.py.
) -> list[Point]:
    points: list[Point] = []
    if (not input) or (not leds_per_strip):
        return points
    exclude = exclude or []
    # Start FSM. Start pointer get's put into the accumulator.
    curr_point: Point = Point(startPos.x, startPos.y)
    # points.append(curr_point)
    last_angle = input[0]
    for i,angle in enumerate(input):
        excluded = i in exclude
        values = list(range(leds_per_strip))
        last_angle = angle
        for v in values:
            last_angle = angle
            curr_point = next_point(curr_point, angle, SPACE_PER_LED)
            if not excluded:
                points.append(curr_point)
        #if i == len(input) - 1:
        #    break
        # Next starting point
        curr_point = next_point(curr_point, last_angle, SPACE_PER_LED)
        #if not excluded:
        #    points.append(curr_point)
    if add_last:
        points.append(curr_point)
    return points
References next_point().
Referenced by find_green_anchore_point(), find_red_anchor_point(), generate_black_points(), generate_blue_points(), generate_green_points(), generate_red_points(), main(), simple_test(), two_angle_test(), and two_angle_test2().
generate_black_points()
list[Point] gen.generate_black_points ()
Definition at line 192 of file gen.py.
def generate_black_points() -> list[Point]:
    starting_point = BLACK_ANCHOR_POINT.copy()
    hexagon_angles = [
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.RIGHT_DOWN,
        HexagonAngle.DOWN,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, starting_point)
    return points
References gen_points().
Referenced by unit_test().
generate_blue_points()
list[Point] gen.generate_blue_points ()
Definition at line 233 of file gen.py.
def generate_blue_points() -> list[Point]:
    starting_point = BLUE_ANCHOR_POINT.copy()
    hexagon_angles = [
        HexagonAngle.RIGHT_UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.RIGHT_DOWN, # skip
        HexagonAngle.RIGHT_DOWN,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, starting_point, exclude=[6])
    return points
References gen_points().
Referenced by unit_test().
generate_green_points()
list[Point] gen.generate_green_points ()
Definition at line 211 of file gen.py.
def generate_green_points() -> list[Point]:
    starting_point = GREEN_ANCHOR_POINT.copy()
    hexagon_angles = [
        HexagonAngle.RIGHT_UP,
        HexagonAngle.UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.DOWN,
        HexagonAngle.RIGHT_DOWN, # skip
        HexagonAngle.LEFT_DOWN,  # skip
        HexagonAngle.LEFT_UP,
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.RIGHT_DOWN,
        HexagonAngle.RIGHT_UP,   # skip
        HexagonAngle.RIGHT_DOWN,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, starting_point, exclude=[5,6,13])
    return points
References gen_points().
Referenced by unit_test().
generate_red_points()
list[Point] gen.generate_red_points ()
Definition at line 177 of file gen.py.
def generate_red_points() -> list[Point]:
    starting_point = RED_ANCHOR_POINT.copy()
    hexagon_angles = [
        HexagonAngle.UP,
        HexagonAngle.LEFT_UP,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.DOWN,
        HexagonAngle.RIGHT_DOWN,
        HexagonAngle.UP,
        HexagonAngle.LEFT_UP
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, starting_point, exclude=[5])
    return points
References gen_points().
Referenced by unit_test().
main()
None gen.main ()
Definition at line 102 of file gen.py.
def main() -> None:
    startPos = Point(0, 0)
    hexagon_angles = [
        HexagonAngle.UP,
        HexagonAngle.RIGHT_UP,
        HexagonAngle.RIGHT_DOWN,
        HexagonAngle.DOWN,
        HexagonAngle.LEFT_DOWN,
        HexagonAngle.LEFT_UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, startPos)
    print(points)
References gen_points().
next_point()
Point gen.next_point (Point pos, HexagonAngle angle, float space)
Definition at line 60 of file gen.py.
def next_point(pos: Point, angle: HexagonAngle, space: float) -> Point:
    degrees = angle.value
    angle_rad = toRads(degrees)
    x = pos.x + space * cos(angle_rad)
    y = pos.y + space * sin(angle_rad)
    return Point(x, y)
References toRads().
Referenced by gen_points().
simple_test()
None gen.simple_test ()
Definition at line 118 of file gen.py.
def simple_test() -> None:
    startPos = Point(0, 0)
    hexagon_angles = [
        HexagonAngle.UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, startPos)
    print(points)
    # assert len(points) == LED_PER_STRIP + 1
References gen_points().
toRads()
float gen.toRads (float angle)
Definition at line 30 of file gen.py.
def toRads(angle: float) -> float:
    return angle * (pi / 180)
@dataclass
Referenced by next_point().
two_angle_test()
None gen.two_angle_test ()
Definition at line 127 of file gen.py.
def two_angle_test() -> None:
    startPos = Point(0, 0)
    hexagon_angles = [
        HexagonAngle.UP,
        HexagonAngle.UP,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, startPos)
    print(points)
    # assert len(points) == LED_PER_STRIP * 2, f"Expected {LED_PER_STRIP * 2} points, got {len(points)} points"
References gen_points().
two_angle_test2()
None gen.two_angle_test2 ()
Definition at line 139 of file gen.py.
def two_angle_test2() -> None:
    print("two_angle_test2")
    startPos = Point(0, 0)
    hexagon_angles = [
        HexagonAngle.UP,
        HexagonAngle.DOWN,
    ]
    points = gen_points(hexagon_angles, LED_PER_STRIP, startPos)
    print(points)
    # assert len(points) == LED_PER_STRIP * 2, f"Expected {LED_PER_STRIP * 2} points, got {len(points)} points"
# Red is defined by this instruction tutorial: https://voidstar.dozuki.com/Guide/Chromance+Assembly+Instructions/6
References gen_points().
unit_test()
None gen.unit_test ()
Definition at line 252 of file gen.py.
def unit_test() -> None:
    #simple_test()
    #two_angle_test()
    out = {}
    map = out.setdefault("map", {})
    map.update({
        "red_segment": Point.toJson(generate_red_points()),
        "back_segment": Point.toJson(generate_black_points()),
        "green_segment": Point.toJson(generate_green_points()),
        "blue_segment": Point.toJson(generate_blue_points()),
    })
    print(json.dumps(out))
    # write it out to a file
    with open("output.json", "w") as f:
        f.write(json.dumps(out))
References generate_black_points(), generate_blue_points(), generate_green_points(), generate_red_points(), and unit_test().
Referenced by unit_test().
Variable Documentation
BLACK_ANCHOR_POINT
gen.BLACK_ANCHOR_POINT = Point(0,0)
Definition at line 172 of file gen.py.
BLUE_ANCHOR_POINT
gen.BLUE_ANCHOR_POINT = Point(0, 0)
Definition at line 174 of file gen.py.
GREEN_ANCHOR_POINT
list[Point] gen.GREEN_ANCHOR_POINT = find_green_anchore_point()[-1]
Definition at line 173 of file gen.py.
LED_DIAMETER
float gen.LED_DIAMETER = SPACE_PER_LED / 4
Definition at line 15 of file gen.py.
LED_PER_STRIP
int gen.LED_PER_STRIP = 14
Definition at line 13 of file gen.py.
MIRROR_X
bool gen.MIRROR_X = True
Definition at line 16 of file gen.py.
RED_ANCHOR_POINT
list[Point] gen.RED_ANCHOR_POINT = find_red_anchor_point()[-1]
Definition at line 171 of file gen.py.
SMALLEST_ANGLE
int gen.SMALLEST_ANGLE = 360 / 6
Definition at line 18 of file gen.py.
SPACE_PER_LED
float gen.SPACE_PER_LED = 30.0
Definition at line 14 of file gen.py.