FastLED: fl::FastLEDANIMartRIX Class Reference
fl::FastLEDANIMartRIX Class Reference
Detailed Description
Definition at line 126 of file animartrix.hpp.
#include <animartrix.hpp>
Public Member Functions
FastLEDANIMartRIX (Animartrix *_data)
void loop ()
void setPixelColor (int x, int y, CRGB pixel)
void setPixelColorInternal (int x, int y, animartrix_detail::rgb pixel) override
uint16_t xyMap (uint16_t x, uint16_t y) override
Public Member Functions inherited from animartrix_detail::ANIMartRIX
ANIMartRIX ()
ANIMartRIX (int w, int h)
virtual ~ANIMartRIX ()
float add (float &a, float &b)
void Big_Caleido ()
void calculate_oscillators (oscillators &timings)
void Caleido1 ()
void Caleido2 ()
void Caleido3 ()
void Center_Field ()
void Chasing_Spirals ()
float colorburn (float &a, float &b)
float colordodge (float &a, float &b)
void Complex_Kaleido ()
void Complex_Kaleido_2 ()
void Complex_Kaleido_3 ()
void Complex_Kaleido_4 ()
void Complex_Kaleido_5 ()
void Complex_Kaleido_6 ()
void Distance_Experiment ()
float fade (float t)
void get_ready ()
uint32_t getTime ()
float grad (int hash, float x, float y, float z)
void Hot_Blob ()
void init (int w, int h)
void Lava1 ()
float lerp (float t, float a, float b)
void logFrame ()
void logOutput ()
float map_float (float x, float in_min, float in_max, float out_min, float out_max)
void Module_Experiment1 ()
void Module_Experiment10 ()
void Module_Experiment2 ()
void Module_Experiment3 ()
void Module_Experiment4 ()
void Module_Experiment5 ()
void Module_Experiment6 ()
void Module_Experiment7 ()
void Module_Experiment8 ()
void Module_Experiment9 ()
float multiply (float &a, float &b)
void Parametric_Water ()
float pnoise (float x, float y, float z)
void Polar_Waves ()
void render_polar_lookup_table (float cx, float cy)
float render_value (render_parameters &animation)
void report_performance ()
void RGB_Blobs ()
void RGB_Blobs2 ()
void RGB_Blobs3 ()
void RGB_Blobs4 ()
void RGB_Blobs5 ()
rgb rgb_sanity_check (rgb &pixel)
void Rings ()
void Rotating_Blob ()
void run_default_oscillators (float master_speed=0.005)
void Scaledemo1 ()
float screen (float &a, float &b)
void setSpeedFactor (float speed)
Set the Speed Factor 0.1 to 10 - 1 for original speed.
void setTime (uint32_t t)
void Slow_Fade ()
void SM1 ()
void SM10 ()
void SM2 ()
void SM3 ()
void SM4 ()
void SM5 ()
void SM6 ()
void SM8 ()
void SM9 ()
void Spiralus ()
void Spiralus2 ()
float subtract (float &a, float &b)
void Water ()
void Waves ()
void Yves ()
void Zoom ()
void Zoom2 ()
Private Attributes
Animartrix * data = nullptr
Additional Inherited Members
Public Attributes inherited from animartrix_detail::ANIMartRIX
unsigned long a
render_parameters animation
unsigned long b
unsigned long c
uint32_t currentTime = 0
fl::HeapVector< fl::HeapVector< float > > distance
modulators move
int num_x
int num_y
rgb pixel
fl::HeapVector< fl::HeapVector< float > > polar_theta
float radial_filter_radius = 23.0
bool serpentine
float show0
float show1
float show2
float show3
float show4
float show5
float show6
float show7
float show8
float show9
float speed_factor = 1
oscillators timings
Constructor & Destructor Documentation
FastLEDANIMartRIX()
fl::FastLEDANIMartRIX::FastLEDANIMartRIX (Animartrix * _data) inline
Definition at line 130 of file animartrix.hpp.
{
        this->data = _data;
        this->init(data->getWidth(), data->getWidth());
    }
References data, fl::Fx2d::getWidth(), and animartrix_detail::ANIMartRIX::init().
Member Function Documentation
loop()
void fl::FastLEDANIMartRIX::loop ()
Definition at line 231 of file animartrix.hpp.
{
    for (const auto& entry : ANIMATION_TABLE) {
        if (entry.anim == data->current_animation) {
            (this->*entry.func)();
            return;
        }
    }
    // (this->*ANIMATION_TABLE[index].func)();
    FASTLED_DBG("Animation not found for " << int(data->current_animation));
}
References fl::ANIMATION_TABLE, fl::Animartrix::current_animation, data, and FASTLED_DBG.
setPixelColor()
void fl::FastLEDANIMartRIX::setPixelColor (int x, int y, CRGB pixel) inline
Definition at line 135 of file animartrix.hpp.
{
        data->leds[xyMap(x, y)] = pixel;
    }
References data, fl::Animartrix::leds, animartrix_detail::ANIMartRIX::pixel, x, xyMap, and y.
Referenced by setPixelColorInternal().
setPixelColorInternal()
void fl::FastLEDANIMartRIX::setPixelColorInternal (int x, int y, animartrix_detail::rgb pixel) inline override virtual
Implements animartrix_detail::ANIMartRIX.
Definition at line 138 of file animartrix.hpp.
{
        setPixelColor(x, y, CRGB(pixel.red, pixel.green, pixel.blue));
    }
References animartrix_detail::rgb::blue, animartrix_detail::rgb::green, animartrix_detail::ANIMartRIX::pixel, animartrix_detail::rgb::red, setPixelColor(), x, and y.
xyMap()
uint16_t fl::FastLEDANIMartRIX::xyMap (uint16_t x, uint16_t y) inline override virtual
Implements animartrix_detail::ANIMartRIX.
Definition at line 142 of file animartrix.hpp.
{
        return data->xyMap(x, y);
    }
References data, x, fl::Fx2d::xyMap(), and y.
Member Data Documentation
data
Animartrix* fl::FastLEDANIMartRIX::data = nullptr private
Definition at line 127 of file animartrix.hpp.
Referenced by FastLEDANIMartRIX(), loop(), setPixelColor(), and xyMap().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/2d/animartrix.hpp