FastLED: fl::Pacifica Class Reference
fl::Pacifica Class Reference
Detailed Description
Definition at line 15 of file pacifica.h.
#include <pacifica.h>
Public Member Functions
Pacifica (uint16_t num_leds)
void draw (DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Member Functions
void pacifica_add_whitecaps (CRGB *leds)
void pacifica_deepen_colors (CRGB *leds)
void pacifica_one_layer (CRGB *leds, CRGBPalette16 &p, uint16_t cistart, uint16_t wavescale, uint8_t bri, uint16_t ioff)
Private Attributes
CRGBPalette16 pacifica_palette_1
CRGBPalette16 pacifica_palette_2
CRGBPalette16 pacifica_palette_3
uint16_t sCIStart1 = 0
uint16_t sCIStart2 = 0
uint16_t sCIStart3 = 0
uint16_t sCIStart4 = 0
uint32_t sLastms = 0
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
Pacifica()
fl::Pacifica::Pacifica (uint16_t num_leds) inline
Definition at line 17 of file pacifica.h.
: Fx1d(num_leds) {}
Member Function Documentation
draw()
void fl::Pacifica::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 45 of file pacifica.h.
{
    CRGB *leds = ctx.leds;
    uint32_t now = ctx.now;
    if (leds == nullptr || mNumLeds == 0) {
        return;
    }
    // Update the hue each time through the loop
    uint32_t ms = now;
    uint32_t deltams = ms - sLastms;
    sLastms = ms;
    uint16_t speedfactor1 = beatsin16(3, 179, 269);
    uint16_t speedfactor2 = beatsin16(4, 179, 269);
    uint32_t deltams1 = (deltams * speedfactor1) / 256;
    uint32_t deltams2 = (deltams * speedfactor2) / 256;
    uint32_t deltams21 = (deltams1 + deltams2) / 2;
    sCIStart1 += (deltams1 * beatsin88(1011, 10, 13));
    sCIStart2 -= (deltams21 * beatsin88(777, 8, 11));
    sCIStart3 -= (deltams1 * beatsin88(501, 5, 7));
    sCIStart4 -= (deltams2 * beatsin88(257, 4, 6));
    // Clear out the LED array to a dim background blue-green
    fill_solid(leds, mNumLeds, CRGB(2, 6, 10));
    // Render each of four layers, with different scales and speeds, that vary
    // over time
    pacifica_one_layer(leds, pacifica_palette_1, sCIStart1,
                       beatsin16(3, 11 * 256, 14 * 256), beatsin8(10, 70, 130),
                       0 - beat16(301));
    pacifica_one_layer(leds, pacifica_palette_2, sCIStart2,
                       beatsin16(4, 6 * 256, 9 * 256), beatsin8(17, 40, 80),
                       beat16(401));
    pacifica_one_layer(leds, pacifica_palette_3, sCIStart3, 6 * 256,
                       beatsin8(9, 10, 38), 0 - beat16(503));
    pacifica_one_layer(leds, pacifica_palette_3, sCIStart4, 5 * 256,
                       beatsin8(8, 10, 28), beat16(601));
    // Add brighter 'whitecaps' where the waves lines up more
    pacifica_add_whitecaps(leds);
    // Deepen the blues and greens a bit
    pacifica_deepen_colors(leds);
}
References beat16(), beatsin16(), beatsin8(), beatsin88(), fill_solid(), fl::_DrawContext::leds, leds, fl::Fx::mNumLeds, fl::_DrawContext::now, pacifica_add_whitecaps(), pacifica_deepen_colors(), pacifica_one_layer(), pacifica_palette_1, pacifica_palette_2, pacifica_palette_3, sCIStart1, sCIStart2, sCIStart3, sCIStart4, and sLastms.
Referenced by loop().
fxName()
fl::Str fl::Pacifica::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 20 of file pacifica.h.
{ return "Pacifica"; }
pacifica_add_whitecaps()
void fl::Pacifica::pacifica_add_whitecaps (CRGB * leds) private
Definition at line 110 of file pacifica.h.
{
    uint8_t basethreshold = beatsin8(9, 55, 65);
    uint8_t wave = beat8(7);
    for (uint16_t i = 0; i < mNumLeds; i++) {
        uint8_t threshold = scale8(sin8(wave), 20) + basethreshold;
        wave += 7;
        uint8_t l = leds[i].getAverageLight();
        if (l > threshold) {
            uint8_t overage = l - threshold;
            uint8_t overage2 = qadd8(overage, overage);
            leds[i] += CRGB(overage, overage2, qadd8(overage2, overage2));
        }
    }
}
References beat8(), beatsin8(), CRGB::getAverageLight(), leds, fl::Fx::mNumLeds, qadd8(), scale8(), and sin8.
pacifica_deepen_colors()
void fl::Pacifica::pacifica_deepen_colors (CRGB * leds) private
Definition at line 127 of file pacifica.h.
{
    for (uint16_t i = 0; i < mNumLeds; i++) {
        leds[i].blue = scale8(leds[i].blue, 145);
        leds[i].green = scale8(leds[i].green, 200);
        leds[i] |= CRGB(2, 5, 7);
    }
}
References leds, fl::Fx::mNumLeds, and scale8().
pacifica_one_layer()
void fl::Pacifica::pacifica_one_layer (CRGB * leds, CRGBPalette16 & p, uint16_t cistart, uint16_t wavescale, uint8_t bri, uint16_t ioff) private
Definition at line 90 of file pacifica.h.
{
    uint16_t ci = cistart;
    uint16_t waveangle = ioff;
    uint16_t wavescale_half = (wavescale / 2) + 20;
    for (uint16_t i = 0; i < mNumLeds; i++) {
        waveangle += 250;
        uint16_t s16 = sin16(waveangle) + 32768;
        uint16_t cs = scale16(s16, wavescale_half) + wavescale_half;
        ci += cs;
        uint16_t sindex16 = sin16(ci) + 32768;
        uint8_t sindex8 = scale16(sindex16, 240);
        CRGB c = ColorFromPalette(p, sindex8, bri, LINEARBLEND);
        leds[i] += c;
    }
}
References ColorFromPalette(), leds, LINEARBLEND, fl::Fx::mNumLeds, p, scale16(), and sin16.
Referenced by draw().
Member Data Documentation
pacifica_palette_1
CRGBPalette16 fl::Pacifica::pacifica_palette_1 private
Initial value:
= {0x000507, 0x000409, 0x00030B, 0x00030D,
                                        0x000210, 0x000212, 0x000114, 0x000117,
                                        0x000019, 0x00001C, 0x000026, 0x000031,
                                        0x00003B, 0x000046, 0x14554B, 0x28AA50}
Definition at line 26 of file pacifica.h.
                                       {0x000507, 0x000409, 0x00030B, 0x00030D,
                                        0x000210, 0x000212, 0x000114, 0x000117,
                                        0x000019, 0x00001C, 0x000026, 0x000031,
                                        0x00003B, 0x000046, 0x14554B, 0x28AA50};
Referenced by draw().
pacifica_palette_2
CRGBPalette16 fl::Pacifica::pacifica_palette_2 private
Initial value:
= {0x000507, 0x000409, 0x00030B, 0x00030D,
                                        0x000210, 0x000212, 0x000114, 0x000117,
                                        0x000019, 0x00001C, 0x000026, 0x000031,
                                        0x00003B, 0x000046, 0x0C5F52, 0x19BE5F}
Definition at line 30 of file pacifica.h.
                                       {0x000507, 0x000409, 0x00030B, 0x00030D,
                                        0x000210, 0x000212, 0x000114, 0x000117,
                                        0x000019, 0x00001C, 0x000026, 0x000031,
                                        0x00003B, 0x000046, 0x0C5F52, 0x19BE5F};
Referenced by draw().
pacifica_palette_3
CRGBPalette16 fl::Pacifica::pacifica_palette_3 private
Initial value:
= {0x000208, 0x00030E, 0x000514, 0x00061A,
                                        0x000820, 0x000927, 0x000B2D, 0x000C33,
                                        0x000E39, 0x001040, 0x001450, 0x001860,
                                        0x001C70, 0x002080, 0x1040BF, 0x2060FF}
Definition at line 34 of file pacifica.h.
                                       {0x000208, 0x00030E, 0x000514, 0x00061A,
                                        0x000820, 0x000927, 0x000B2D, 0x000C33,
                                        0x000E39, 0x001040, 0x001450, 0x001860,
                                        0x001C70, 0x002080, 0x1040BF, 0x2060FF};
Referenced by draw().
sCIStart1
uint16_t fl::Pacifica::sCIStart1 = 0 private
Definition at line 23 of file pacifica.h.
Referenced by draw().
sCIStart2
uint16_t fl::Pacifica::sCIStart2 = 0 private
Definition at line 23 of file pacifica.h.
Referenced by draw().
sCIStart3
uint16_t fl::Pacifica::sCIStart3 = 0 private
Definition at line 23 of file pacifica.h.
Referenced by draw().
sCIStart4
uint16_t fl::Pacifica::sCIStart4 = 0 private
Definition at line 23 of file pacifica.h.
Referenced by draw().
sLastms
uint32_t fl::Pacifica::sLastms = 0 private
Definition at line 24 of file pacifica.h.
Referenced by draw().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/1d/pacifica.h