FastLED: fl::FrameTracker Class Reference
fl::FrameTracker Class Reference
Detailed Description
Definition at line 14 of file frame_tracker.h.
#include <frame_tracker.h>
Public Member Functions
FrameTracker (float fps)
uint32_t get_exact_timestamp_ms (uint32_t frameNumber) const
void get_interval_frames (uint32_t now, uint32_t *frameNumber, uint32_t *nextFrameNumber, uint8_t *amountOfNextFrame=nullptr) const
uint32_t microsecondsPerFrame () const
Private Attributes
uint32_t mMicrosSecondsPerInterval
uint32_t mStartTime = 0
Constructor & Destructor Documentation
FrameTracker()
fl::FrameTracker::FrameTracker (float fps)
Definition at line 17 of file frame_tracker.cpp.
{
    // Convert fps to microseconds per frame interval
    mMicrosSecondsPerInterval = static_cast<uint32_t>(1000000.0f / fps + .5f);
}
References mMicrosSecondsPerInterval.
Member Function Documentation
get_exact_timestamp_ms()
uint32_t fl::FrameTracker::get_exact_timestamp_ms (uint32_t frameNumber) const
Definition at line 46 of file frame_tracker.cpp.
{
    uint64_t microseconds = frameNumber * mMicrosSecondsPerInterval;
    return static_cast<uint32_t>(microseconds / 1000) + mStartTime;
}
References mMicrosSecondsPerInterval, and mStartTime.
Referenced by fl::FrameInterpolator::get_exact_timestamp_ms().
get_interval_frames()
void fl::FrameTracker::get_interval_frames (uint32_t now, uint32_t * frameNumber, uint32_t * nextFrameNumber, uint8_t * amountOfNextFrame = nullptr) const
Definition at line 22 of file frame_tracker.cpp.
{
    // Account for any pause time
    uint32_t effectiveTime = now;
    // Convert milliseconds to microseconds for precise calculation
    uint64_t microseconds = static_cast<uint64_t>(effectiveTime) * 1000ULL;
    // Calculate frame number with proper rounding
    *frameNumber = microseconds / mMicrosSecondsPerInterval;
    *nextFrameNumber = *frameNumber + 1;
    // Calculate interpolation amount if requested
    if (amountOfNextFrame != nullptr) {
        uint64_t frame1_start = (*frameNumber * mMicrosSecondsPerInterval);
        uint64_t frame2_start = (*nextFrameNumber * mMicrosSecondsPerInterval);
        uint32_t rel_time = microseconds - frame1_start;
        uint32_t frame_duration = frame2_start - frame1_start;
        uint8_t progress = uint8_t(map(rel_time, 0, frame_duration, 0, 255));
        *amountOfNextFrame = progress;
    }
}
References mMicrosSecondsPerInterval.
Referenced by fl::FrameInterpolator::draw(), and fl::FrameInterpolator::needsFrame().
microsecondsPerFrame()
uint32_t fl::FrameTracker::microsecondsPerFrame () const inline
Definition at line 25 of file frame_tracker.h.
{
        return mMicrosSecondsPerInterval;
    }
References mMicrosSecondsPerInterval.
Member Data Documentation
mMicrosSecondsPerInterval
uint32_t fl::FrameTracker::mMicrosSecondsPerInterval private
Definition at line 30 of file frame_tracker.h.
Referenced by FrameTracker(), get_exact_timestamp_ms(), get_interval_frames(), and microsecondsPerFrame().
mStartTime
uint32_t fl::FrameTracker::mStartTime = 0 private
Definition at line 31 of file frame_tracker.h.
Referenced by get_exact_timestamp_ms().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/video/frame_tracker.h
/home/runner/work/FastLED/FastLED/src/fx/video/frame_tracker.cpp