FastLED: Color Fill Functions
Color Fill Functions
Color Utility Functions
Detailed Description
Functions for filling LED arrays with colors and gradients
Macros
#define fill_gradient_HSV fill_gradient
Convenience synonym.
#define saccum87 int16_t
ANSI: signed short _Accum.
Enumerations
enum TGradientDirectionCode { FORWARD_HUES , BACKWARD_HUES , SHORTEST_HUES , LONGEST_HUES }
Hue direction for calculating fill gradients.
Functions
template<typename T >
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between four HSV colors.
template<typename T >
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, const CHSV &c3, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between three HSV colors.
template<typename T >
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
template<typename T >
void fill_gradient (T *targetArray, uint16_t startpos, CHSV startcolor, uint16_t endpos, CHSV endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2, const CRGB &c3)
Fill a range of LEDs with a smooth RGB gradient between three RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Fill a range of LEDs with a smooth RGB gradient between four RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t startpos, CRGB startcolor, uint16_t endpos, CRGB endcolor)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
void fill_rainbow (struct CHSV *targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue=5)
Fill a range of LEDs with a rainbow of colors.
void fill_rainbow (struct CRGB *targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue=5)
Fill a range of LEDs with a rainbow of colors.
void fill_rainbow_circular (struct CHSV *targetArray, int numToFill, uint8_t initialhue, bool reversed=false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
void fill_rainbow_circular (struct CRGB *targetArray, int numToFill, uint8_t initialhue, bool reversed=false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
void fill_solid (struct CHSV *targetArray, int numToFill, const struct CHSV &color)
Fill a range of LEDs with a solid color.
void fill_solid (struct CRGB *targetArray, int numToFill, const struct CRGB &color)
Fill a range of LEDs with a solid color.
CRGB HeatColor (uint8_t temperature)
Approximates a "black body radiation" spectrum for a given "heat" level.
Macro Definition Documentation
fill_gradient_HSV
#define fill_gradient_HSV fill_gradient
Convenience synonym.
Definition at line 353 of file colorutils.h.
saccum87
#define saccum87 int16_t
ANSI: signed short _Accum.
8 bits int, 7 bits fraction
See also
accum88
Definition at line 170 of file colorutils.h.
Referenced by fill_gradient(), and fill_gradient_RGB().
Enumeration Type Documentation
TGradientDirectionCode
enum TGradientDirectionCode
Hue direction for calculating fill gradients.
Since "hue" is a value around a color wheel, there are always two directions to sweep from one hue to another.
Enumerator
FORWARD_HUES
Hue always goes clockwise around the color wheel.
BACKWARD_HUES
Hue always goes counter-clockwise around the color wheel.
SHORTEST_HUES
Hue goes whichever way is shortest.
LONGEST_HUES
Hue goes whichever way is longest.
Definition at line 160 of file colorutils.h.
             {
    FORWARD_HUES,
    BACKWARD_HUES,
    SHORTEST_HUES,
    LONGEST_HUES
} TGradientDirectionCode;
Function Documentation
fill_gradient() [1/4]
template<typename T > void fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between four HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 340 of file colorutils.h.
{
    uint16_t onethird = (numLeds / 3);
    uint16_t twothirds = ((numLeds * 2) / 3);
    uint16_t last = numLeds - 1;
    fill_gradient( targetArray,         0, c1,  onethird, c2, directionCode);
    fill_gradient( targetArray,  onethird, c2, twothirds, c3, directionCode);
    fill_gradient( targetArray, twothirds, c3,      last, c4, directionCode);
}
References fill_gradient().
fill_gradient() [2/4]
template<typename T > void fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, const CHSV & c3, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between three HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 320 of file colorutils.h.
{
    uint16_t half = (numLeds / 2);
    uint16_t last = numLeds - 1;
    fill_gradient( targetArray,    0, c1, half, c2, directionCode);
    fill_gradient( targetArray, half, c2, last, c3, directionCode);
}
References fill_gradient().
fill_gradient() [3/4]
template<typename T > void fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 304 of file colorutils.h.
{
    uint16_t last = numLeds - 1;
    fill_gradient( targetArray, 0, c1, last, c2, directionCode);
}
References fill_gradient().
fill_gradient() [4/4]
template<typename T > void fill_gradient (T * targetArray, uint16_t startpos, CHSV startcolor, uint16_t endpos, CHSV endcolor, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
This function can write the gradient colors either:
Into an array of CRGBs (e.g., an leds[] array, or a CRGB palette)
Into an array of CHSVs (e.g. a CHSV palette).
In the case of writing into a CRGB array, the gradient is computed in HSV space, and then HSV values are converted to RGB as they're written into the CRGB array.
Parameters
targetArray a pointer to the color array to fill
startpos the starting position in the array
startcolor the starting color for the gradient
endpos the ending position in the array
endcolor the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 189 of file colorutils.h.
{
    // if the points are in the wrong order, straighten them
    if( endpos < startpos ) {
        uint16_t t = endpos;
        CHSV tc = endcolor;
        endcolor = startcolor;
        endpos = startpos;
        startpos = t;
        startcolor = tc;
    }
    // If we're fading toward black (val=0) or white (sat=0),
    // then set the endhue to the starthue.
    // This lets us ramp smoothly to black or white, regardless
    // of what 'hue' was set in the endcolor (since it doesn't matter)
    if( endcolor.value == 0 || endcolor.saturation == 0) {
        endcolor.hue = startcolor.hue;
    }
    // Similarly, if we're fading in from black (val=0) or white (sat=0)
    // then set the starthue to the endhue.
    // This lets us ramp smoothly up from black or white, regardless
    // of what 'hue' was set in the startcolor (since it doesn't matter)
    if( startcolor.value == 0 || startcolor.saturation == 0) {
        startcolor.hue = endcolor.hue;
    }
    saccum87 huedistance87;
    saccum87 satdistance87;
    saccum87 valdistance87;
    satdistance87 = (endcolor.sat - startcolor.sat) << 7;
    valdistance87 = (endcolor.val - startcolor.val) << 7;
    uint8_t huedelta8 = endcolor.hue - startcolor.hue;
    if( directionCode == SHORTEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 > 127) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == LONGEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 < 128) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == FORWARD_HUES) {
        huedistance87 = huedelta8 << 7;
    }
    else /* directionCode == BACKWARD_HUES */
    {
        huedistance87 = (uint8_t)(256 - huedelta8) << 7;
        huedistance87 = -huedistance87;
    }
    uint16_t pixeldistance = endpos - startpos;
    int16_t divisor = pixeldistance ? pixeldistance : 1;
    #if FASTLED_USE_32_BIT_GRADIENT_FILL
    // Use higher precision 32 bit math for new micros.
    int32_t huedelta823 = (huedistance87 * 65536) / divisor;
    int32_t satdelta823 = (satdistance87 * 65536) / divisor;
    int32_t valdelta823 = (valdistance87 * 65536) / divisor;
    huedelta823 *= 2;
    satdelta823 *= 2;
    valdelta823 *= 2;
    uint32_t hue824 = static_cast<uint32_t>(startcolor.hue) << 24;
    uint32_t sat824 = static_cast<uint32_t>(startcolor.sat) << 24;
    uint32_t val824 = static_cast<uint32_t>(startcolor.val) << 24;
    for( uint16_t i = startpos; i <= endpos; ++i) {
        targetArray[i] = CHSV( hue824 >> 24, sat824 >> 24, val824 >> 24);
        hue824 += huedelta823;
        sat824 += satdelta823;
        val824 += valdelta823;
    }
    #else
    // Use 8-bit math for older micros.
    saccum87 huedelta87 = huedistance87 / divisor;
    saccum87 satdelta87 = satdistance87 / divisor;
    saccum87 valdelta87 = valdistance87 / divisor;
    huedelta87 *= 2;
    satdelta87 *= 2;
    valdelta87 *= 2;
    accum88 hue88 = startcolor.hue << 8;
    accum88 sat88 = startcolor.sat << 8;
    accum88 val88 = startcolor.val << 8;
    for( uint16_t i = startpos; i <= endpos; ++i) {
        targetArray[i] = CHSV( hue88 >> 8, sat88 >> 8, val88 >> 8);
        hue88 += huedelta87;
        sat88 += satdelta87;
        val88 += valdelta87;
    }
    #endif  // defined(__AVR__)
}
References BACKWARD_HUES, FORWARD_HUES, LONGEST_HUES, saccum87, and SHORTEST_HUES.
Referenced by CHSVPalette16::CHSVPalette16(), CHSVPalette16::CHSVPalette16(), CHSVPalette16::CHSVPalette16(), CHSVPalette256::CHSVPalette256(), CHSVPalette256::CHSVPalette256(), CHSVPalette256::CHSVPalette256(), CHSVPalette32::CHSVPalette32(), CHSVPalette32::CHSVPalette32(), CHSVPalette32::CHSVPalette32(), CRGBPalette16::CRGBPalette16(), CRGBPalette16::CRGBPalette16(), CRGBPalette16::CRGBPalette16(), CRGBPalette256::CRGBPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette32::CRGBPalette32(), CRGBPalette32::CRGBPalette32(), CRGBPalette32::CRGBPalette32(), fill_gradient(), fill_gradient(), and fill_gradient().
fill_gradient_RGB() [1/4]
void fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the end color for the gradient
Definition at line 224 of file colorutils.cpp.
{
    uint16_t last = numLeds - 1;
    fill_gradient_RGB( leds, 0, c1, last, c2);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [2/4]
void fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2, const CRGB & c3)
Fill a range of LEDs with a smooth RGB gradient between three RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 231 of file colorutils.cpp.
{
    uint16_t half = (numLeds / 2);
    uint16_t last = numLeds - 1;
    fill_gradient_RGB( leds,    0, c1, half, c2);
    fill_gradient_RGB( leds, half, c2, last, c3);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [3/4]
void fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2, const CRGB & c3, const CRGB & c4)
Fill a range of LEDs with a smooth RGB gradient between four RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 239 of file colorutils.cpp.
{
    uint16_t onethird = (numLeds / 3);
    uint16_t twothirds = ((numLeds * 2) / 3);
    uint16_t last = numLeds - 1;
    fill_gradient_RGB( leds,         0, c1,  onethird, c2);
    fill_gradient_RGB( leds,  onethird, c2, twothirds, c3);
    fill_gradient_RGB( leds, twothirds, c3,      last, c4);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [4/4]
void fill_gradient_RGB (CRGB * leds, uint16_t startpos, CRGB startcolor, uint16_t endpos, CRGB endcolor)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
Unlike HSV, there is no "color wheel" in RGB space, and therefore there's only one "direction" for the gradient to go. This means there's no TGradientDirectionCode parameter for direction.
Parameters
leds a pointer to the LED array to fill
startpos the starting position in the array
startcolor the starting color for the gradient
endpos the ending position in the array
endcolor the end color for the gradient
Definition at line 145 of file colorutils.cpp.
{
    // if the points are in the wrong order, straighten them
    if( endpos < startpos ) {
        uint16_t t = endpos;
        CRGB tc = endcolor;
        endcolor = startcolor;
        endpos = startpos;
        startpos = t;
        startcolor = tc;
    }
    saccum87 rdistance87;
    saccum87 gdistance87;
    saccum87 bdistance87;
    rdistance87 = (endcolor.r - startcolor.r) << 7;
    gdistance87 = (endcolor.g - startcolor.g) << 7;
    bdistance87 = (endcolor.b - startcolor.b) << 7;
    uint16_t pixeldistance = endpos - startpos;
    int16_t divisor = pixeldistance ? pixeldistance : 1;
    saccum87 rdelta87 = rdistance87 / divisor;
    saccum87 gdelta87 = gdistance87 / divisor;
    saccum87 bdelta87 = bdistance87 / divisor;
    rdelta87 *= 2;
    gdelta87 *= 2;
    bdelta87 *= 2;
    accum88 r88 = startcolor.r << 8;
    accum88 g88 = startcolor.g << 8;
    accum88 b88 = startcolor.b << 8;
    for( uint16_t i = startpos; i <= endpos; ++i) {
        leds[i] = CRGB( r88 >> 8, g88 >> 8, b88 >> 8);
        r88 += rdelta87;
        g88 += gdelta87;
        b88 += bdelta87;
    }
}
References leds, and saccum87.
Referenced by CRGBPalette16::CRGBPalette16(), CRGBPalette16::CRGBPalette16(), CRGBPalette16::CRGBPalette16(), CRGBPalette256::CRGBPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette32::CRGBPalette32(), CRGBPalette32::CRGBPalette32(), CRGBPalette32::CRGBPalette32(), fill_gradient_RGB(), fill_gradient_RGB(), fill_gradient_RGB(), CRGBPalette16::loadDynamicGradientPalette(), CRGBPalette256::loadDynamicGradientPalette(), CRGBPalette32::loadDynamicGradientPalette(), CRGBPalette16::operator=(), CRGBPalette256::operator=(), and CRGBPalette32::operator=().
fill_rainbow() [1/2]
void fill_rainbow (struct CHSV * targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue = 5)
Fill a range of LEDs with a rainbow of colors.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
deltahue how many hue values to advance for each LED
Definition at line 89 of file colorutils.cpp.
{
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    for( int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        hsv.hue += deltahue;
    }
}
fill_rainbow() [2/2]
void fill_rainbow (struct CRGB * targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue = 5)
Fill a range of LEDs with a rainbow of colors.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
deltahue how many hue values to advance for each LED
Definition at line 75 of file colorutils.cpp.
{
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    for( int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        hsv.hue += deltahue;
    }
}
Referenced by loop(), fl::DemoReel100::rainbow(), and rainbow().
fill_rainbow_circular() [1/2]
void fill_rainbow_circular (struct CHSV * targetArray, int numToFill, uint8_t initialhue, bool reversed = false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
reversed whether to progress through the rainbow hues backwards
Definition at line 124 of file colorutils.cpp.
{
    if (numToFill == 0) return;  // avoiding div/0
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    const uint16_t hueChange = 65535 / (uint16_t) numToFill;  // hue change for each LED, * 256 for precision (256 * 256 - 1)
    uint16_t hueOffset = 0;  // offset for hue value, with precision (*256)
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        if (reversed) hueOffset -= hueChange;
        else hueOffset += hueChange;
        hsv.hue = initialhue + (uint8_t)(hueOffset >> 8);  // assign new hue with precise offset (as 8-bit)
    }
}
fill_rainbow_circular() [2/2]
void fill_rainbow_circular (struct CRGB * targetArray, int numToFill, uint8_t initialhue, bool reversed = false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
reversed whether to progress through the rainbow hues backwards
Definition at line 104 of file colorutils.cpp.
{
    if (numToFill == 0) return;  // avoiding div/0
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    const uint16_t hueChange = 65535 / (uint16_t)numToFill;  // hue change for each LED, * 256 for precision (256 * 256 - 1)
    uint16_t hueOffset = 0;  // offset for hue value, with precision (*256)
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        if (reversed) hueOffset -= hueChange;
        else hueOffset += hueChange;
        hsv.hue = initialhue + (uint8_t)(hueOffset >> 8);  // assign new hue with precise offset (as 8-bit)
    }
}
fill_solid() [1/2]
void fill_solid (struct CHSV * targetArray, int numToFill, const struct CHSV & color)
Fill a range of LEDs with a solid color.
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
color the color to fill with
Definition at line 60 of file colorutils.cpp.
{
    for( int i = 0; i < numToFill; ++i) {
        targetArray[i] = color;
    }
}
fill_solid() [2/2]
void fill_solid (struct CRGB * targetArray, int numToFill, const struct CRGB & color)
Fill a range of LEDs with a solid color.
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
color the color to fill with
Definition at line 52 of file colorutils.cpp.
{
    for( int i = 0; i < numToFill; ++i) {
        targetArray[i] = color;
    }
}
Referenced by CHSVPalette16::CHSVPalette16(), CHSVPalette256::CHSVPalette256(), CHSVPalette32::CHSVPalette32(), CRGBPalette16::CRGBPalette16(), CRGBPalette16::CRGBPalette16(), CRGBPalette256::CRGBPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette32::CRGBPalette32(), CRGBPalette32::CRGBPalette32(), fl::Pacifica::draw(), pacifica_loop(), fl::NoisePalette::SetupBlackAndWhiteStripedPalette(), and SetupBlackAndWhiteStripedPalette().
HeatColor()
CRGB HeatColor (uint8_t temperature)
Approximates a "black body radiation" spectrum for a given "heat" level.
This is useful for animations of "fire". Heat is specified as an arbitrary scale from 0 (cool) to 255 (hot). This is NOT a chromatically correct "black body radiation" spectrum, but it's surprisingly close, and it's fast and small.
Definition at line 543 of file colorutils.cpp.
{
    CRGB heatcolor;
    // Scale 'heat' down from 0-255 to 0-191,
    // which can then be easily divided into three
    // equal 'thirds' of 64 units each.
    uint8_t t192 = scale8_video( temperature, 191);
    // calculate a value that ramps up from
    // zero to 255 in each 'third' of the scale.
    uint8_t heatramp = t192 & 0x3F; // 0..63
    heatramp <<= 2; // scale up to 0..252
    // now figure out which third of the spectrum we're in:
    if( t192 & 0x80) {
        // we're in the hottest third
        heatcolor.r = 255; // full red
        heatcolor.g = 255; // full green
        heatcolor.b = heatramp; // ramp up blue
    } else if( t192 & 0x40 ) {
        // we're in the middle third
        heatcolor.r = 255; // full red
        heatcolor.g = heatramp; // ramp up green
        heatcolor.b = 0; // no blue
    } else {
        // we're in the coolest third
        heatcolor.r = heatramp; // ramp up red
        heatcolor.g = 0; // no green
        heatcolor.b = 0; // no blue
    }
    return heatcolor;
}
References scale8_video().
Referenced by Fire2012().