FastLED: /home/runner/work/FastLED/FastLED/examples/FxEngine/FxEngine.ino File Reference
FxEngine.ino File Reference
Detailed Description
Demonstrates how to use the FxEngine to switch between different effects on a 2D LED matrix.
This example is compatible with the new FastLED wasm compiler. Install it by running pip install fastled then running fastled in this sketch directory.
Definition in file FxEngine.ino.
#include <FastLED.h>
#include "fx/2d/noisepalette.h"
#include "fx/2d/animartrix.hpp"
#include "fx/fx_engine.h"
#include "fl/ui.h"
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define IS_SERPINTINE true
#define LED_PIN 2
#define LED_TYPE WS2811
#define MATRIX_HEIGHT 22
#define MATRIX_WIDTH 22
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Functions
void loop ()
void setup ()
Variables
FxEngine fxEngine (NUM_LEDS)
CRGB leds [NUM_LEDS]
NoisePalette noisePalette1 (xyMap)
NoisePalette noisePalette2 (xyMap)
UISlider SCALE ("SCALE", 20, 20, 100)
UISlider SPEED ("SPEED", 30, 20, 100)
UICheckbox switchFx ("Switch Fx", true)
XYMap xyMap (MATRIX_WIDTH, MATRIX_HEIGHT, IS_SERPINTINE)
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 23 of file FxEngine.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 25 of file FxEngine.ino.
Referenced by setup().
IS_SERPINTINE
#define IS_SERPINTINE true
Examples
FxEngine.ino.
Definition at line 35 of file FxEngine.ino.
LED_PIN
#define LED_PIN 2
Definition at line 22 of file FxEngine.ino.
Referenced by setup().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 24 of file FxEngine.ino.
Referenced by setup().
MATRIX_HEIGHT
#define MATRIX_HEIGHT 22
Definition at line 28 of file FxEngine.ino.
Referenced by setup().
MATRIX_WIDTH
#define MATRIX_WIDTH 22
Definition at line 27 of file FxEngine.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Definition at line 30 of file FxEngine.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 61 of file FxEngine.ino.
            {
    noisePalette1.setSpeed(SPEED);
    noisePalette1.setScale(SCALE);
    noisePalette2.setSpeed(SPEED);
    noisePalette2.setScale(int(SCALE) * 3 / 2);  //  Make the different.
    EVERY_N_SECONDS(1) {
        if (switchFx) {
            fxEngine.nextFx(500);
        }
    }
    fxEngine.draw(millis(), leds);
    FastLED.show();
}
References fl::FxEngine::draw(), EVERY_N_SECONDS, FastLED, fxEngine, leds, fl::FxEngine::nextFx(), noisePalette1, noisePalette2, SCALE, fl::NoisePalette::setScale(), fl::NoisePalette::setSpeed(), CFastLED::show(), SPEED, and switchFx.
setup()
void setup ()
Definition at line 49 of file FxEngine.ino.
             {
    delay(1000); // sanity delay
    FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setCorrection(TypicalLEDStrip)
        .setScreenMap(MATRIX_WIDTH, MATRIX_HEIGHT);
    FastLED.setBrightness(96);
    noisePalette1.setPalettePreset(2);
    noisePalette2.setPalettePreset(4);
    fxEngine.addFx(noisePalette1);
    fxEngine.addFx(noisePalette2);
}
References fl::FxEngine::addFx(), CFastLED::addLeds(), COLOR_ORDER, FastLED, fxEngine, LED_PIN, LED_TYPE, leds, MATRIX_HEIGHT, MATRIX_WIDTH, noisePalette1, noisePalette2, NUM_LEDS, CFastLED::setBrightness(), fl::NoisePalette::setPalettePreset(), CLEDController::setScreenMap(), and TypicalLEDStrip.
Variable Documentation
fxEngine
FxEngine fxEngine(NUM_LEDS) (NUM_LEDS)
Referenced by loop(), and setup().
leds
CRGB leds[NUM_LEDS]
Definition at line 42 of file FxEngine.ino.
Referenced by loop(), and setup().
noisePalette1
NoisePalette noisePalette1(xyMap) (xyMap)
Examples
FxEngine.ino.
Referenced by loop(), and setup().
noisePalette2
NoisePalette noisePalette2(xyMap) (xyMap)
Examples
FxEngine.ino.
Referenced by loop(), and setup().
SCALE
UISlider SCALE("SCALE", 20, 20, 100) ("SCALE" , 20 , 20 , 100)
Referenced by loop().
SPEED
UISlider SPEED("SPEED", 30, 20, 100) ("SPEED" , 30 , 20 , 100)
Referenced by loop().
switchFx
UICheckbox switchFx("Switch Fx", true) ("Switch Fx" , true)
Examples
FxEngine.ino.
Referenced by loop().
xyMap
XYMap xyMap(MATRIX_WIDTH, MATRIX_HEIGHT, IS_SERPINTINE) (MATRIX_WIDTH , MATRIX_HEIGHT , IS_SERPINTINE)