FastLED: Easing Functions
Easing Functions
Fast Math Functions
Detailed Description
Specify the rate of change of a parameter over time.
See also
http://easings.net
Functions
LIB8STATIC uint16_t ease16InOutQuad (uint16_t i)
16-bit quadratic ease-in / ease-out function.
LIB8STATIC fract8 ease8InOutApprox (fract8 i)
Fast, rough 8-bit ease-in/ease-out function.
LIB8STATIC fract8 ease8InOutCubic (fract8 i)
8-bit cubic ease-in / ease-out function.
LIB8STATIC uint8_t ease8InOutQuad (uint8_t i)
8-bit quadratic ease-in / ease-out function.
Function Documentation
ease16InOutQuad()
LIB8STATIC uint16_t ease16InOutQuad (uint16_t i)
16-bit quadratic ease-in / ease-out function.
C implementation at this point.
Definition at line 625 of file lib8tion.h.
{
    uint16_t j = i;
    if( j & 0x8000 ) {
        j = 65535 - j;
    }
    uint16_t jj  = scale16( j, j);
    uint16_t jj2 = jj << 1;
    if( i & 0x8000 ) {
        jj2 = 65535 - jj2;
    }
    return jj2;
}
References scale16().
ease8InOutApprox()
LIB8STATIC fract8 ease8InOutApprox (fract8 i)
Fast, rough 8-bit ease-in/ease-out function.
Shaped approximately like ease8InOutCubic(), it's never off by more than a couple of percent from the actual cubic S-curve, and it executes more than twice as fast. Use when the cycles are more important than visual smoothness. Asm version takes around 7 cycles on AVR.
Definition at line 671 of file lib8tion.h.
{
    if( i < 64) {
        // start with slope 0.5
        i /= 2;
    } else if( i > (255 - 64)) {
        // end with slope 0.5
        i = 255 - i;
        i /= 2;
        i = 255 - i;
    } else {
        // in the middle, use slope 192/128 = 1.5
        i -= 64;
        i += (i / 2);
        i += 32;
    }
    return i;
}
ease8InOutCubic()
LIB8STATIC fract8 ease8InOutCubic (fract8 i)
8-bit cubic ease-in / ease-out function.
Takes around 18 cycles on AVR.
Definition at line 642 of file lib8tion.h.
{
    uint8_t ii  = scale8_LEAVING_R1_DIRTY(  i, i);
    uint8_t iii = scale8_LEAVING_R1_DIRTY( ii, i);
    uint16_t r1 = (3 * (uint16_t)(ii)) - ( 2 * (uint16_t)(iii));
    /* the code generated for the above *'s automatically
       cleans up R1, so there's no need to explicitily call
       cleanup_R1(); */
    uint8_t result = r1;
    // if we got "256", return 255:
    if( r1 & 0x100 ) {
        result = 255;
    }
    return result;
}
References scale8_LEAVING_R1_DIRTY().
Referenced by cubicwave8().
ease8InOutQuad()
LIB8STATIC uint8_t ease8InOutQuad (uint8_t i)
8-bit quadratic ease-in / ease-out function.
Takes around 13 cycles on AVR.
Definition at line 580 of file lib8tion.h.
{
    uint8_t j = i;
    if( j & 0x80 ) {
        j = 255 - j;
    }
    uint8_t jj  = scale8(  j, j);
    uint8_t jj2 = jj << 1;
    if( i & 0x80 ) {
        jj2 = 255 - jj2;
    }
    return jj2;
}
References scale8().
Referenced by quadwave8().