FastLED: /home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/ApproximatingFunction.h File Reference
ApproximatingFunction.h File Reference
Classes
struct InterpData< KeyT, ValT >
Functions
template<typename KeyT , typename ValT >
ValT Interp (const KeyT &k, const InterpData< KeyT, ValT > *array, const int n)
template<typename X , typename Y >
const Y MapT (const X &x, const X &x1, const X &x2, const Y &y1, const Y &y2)
template<typename KeyT , typename ValT >
void SelectInterpPoints (const KeyT &k, const InterpData< KeyT, ValT > *array, const int n, int *dest_lower_bound, int *dest_upper_bound)
Function Documentation
Interp()
template<typename KeyT , typename ValT > ValT Interp (const KeyT & k, const InterpData< KeyT, ValT > * array, const int n) inline
Definition at line 54 of file ApproximatingFunction.h.
{
  if (n < 1) {
    return ValT(0);
  }
  int low_idx = -1;
  int high_idx = -1;
  SelectInterpPoints<KeyT, ValT>(k, array, n, &low_idx, &high_idx);
  if (low_idx == high_idx) {
    return array[low_idx].val;
  }
  const InterpData<KeyT, ValT>* curr = &array[low_idx];
  const InterpData<KeyT, ValT>* next = &array[high_idx];
  // map(...) only works on integers. MapT<> is the same thing but it works on
  // all datatypes.
  return MapT<KeyT, ValT>(k, curr->key, next->key, curr->val, next->val);
}
References InterpData< KeyT, ValT >::key, MapT(), SelectInterpPoints(), and InterpData< KeyT, ValT >::val.
Referenced by AttackRemapFactor(), anonymous_namespace{Painter.cpp}::LuminanceDecay(), MapDecayTime(), and ToBrightness().
MapT()
template<typename X , typename Y > const Y MapT (const X & x, const X & x1, const X & x2, const Y & y1, const Y & y2)
Definition at line 10 of file ApproximatingFunction.h.
{
  Y return_val = static_cast<Y>((x - x1) * (y2 - y1) / (x2 - x1) + y1);
  return return_val;
}
References x.
Referenced by Interp().
SelectInterpPoints()
template<typename KeyT , typename ValT > void SelectInterpPoints (const KeyT & k, const InterpData< KeyT, ValT > * array, const int n, int * dest_lower_bound, int * dest_upper_bound) inline
Definition at line 25 of file ApproximatingFunction.h.
{
  if (n < 1) {
    *dest_lower_bound = *dest_upper_bound = -1;
    return;
  }
  if (k < array[0].key) {
    *dest_lower_bound = *dest_upper_bound = 0;
    return;
  }
  for (int i = 0; i < n - 1; ++i) {
    const InterpData<KeyT, ValT>& curr = array[i];
    const InterpData<KeyT, ValT>& next = array[i+1];
    if (curr.key <= k && k <= next.key) {
      *dest_lower_bound = i;
      *dest_upper_bound = i+1;
      return;
    }
  }
  *dest_lower_bound = n - 1;
  *dest_upper_bound = n - 1;
}
References InterpData< KeyT, ValT >::key.
Referenced by Interp().