FastLED: Pixel Data Sets
Pixel Data Sets
Detailed Description
Classes for managing logical groups of LEDs
Classes
class CPixelView< PIXEL_TYPE >
Represents a set of LED objects.
class CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >
Iterator helper class for CPixelView.
class CRGBArray< SIZE >
A version of CPixelView<CRGB> with an included array of CRGB LEDs.
Functions
FASTLED_FORCE_INLINE CRGB * operator+ (const CRGBSet &pixels, int offset)
Retrieve a pointer to a CRGB array, using a CRGBSet and an LED offset.
Class Documentation
CPixelView
class CPixelView
Public Member Functions
CPixelView (const CPixelView &other)
PixelSet copy constructor.
CPixelView (PIXEL_TYPE *_leds, int _len)
PixelSet constructor for a pixel set starting at the given PIXEL_TYPE* and going for _len leds.
CPixelView (PIXEL_TYPE *_leds, int _start, int _end)
PixelSet constructor for the given set of LEDs, with start and end boundaries.
void dump () const
Print debug data to serial, disabled for release.
operator bool ()
Returns whether or not any LEDs in this set are non-zero.
operator PIXEL_TYPE * () const
Return a pointer to the first element in this set.
bool operator!= (const CPixelView &rhs) const
Do these sets point to different things? Note that this is different from the contents of the set being the same.
CPixelView operator() (int start, int end)
Access an inclusive subset of the LEDs in this set.
CPixelView operator- ()
Return the reverse ordering of this set.
CPixelView & operator= (const CPixelView &rhs)
Copy the contents of the passed-in set to our set.
CPixelView & operator= (const PIXEL_TYPE &color)
Assign the passed in color to all elements in this set.
bool operator== (const CPixelView &rhs) const
Do these sets point to the same thing? Note that this is different from the contents of the set being the same.
PIXEL_TYPE & operator[] (int x) const
Access a single element in this set, just like an array operator.
bool reversed ()
Whether or not this set goes backwards.
int size ()
Get the size of this set.
Modification/Scaling Operators
CPixelView & addToRGB (uint8_t inc)
Add the passed in value to all channels for all of the pixels in this set.
CPixelView & operator+= (CPixelView &rhs)
Add every pixel in the other set to this set.
CPixelView & subFromRGB (uint8_t inc)
Subtract the passed in value from all channels for all of the pixels in this set.
CPixelView & operator-= (CPixelView &rhs)
Subtract every pixel in the other set from this set.
CPixelView & operator++ ()
Increment every pixel value in this set.
CPixelView & operator++ (int DUMMY_ARG)
Increment every pixel value in this set.
CPixelView & operator-- ()
Decrement every pixel value in this set.
CPixelView & operator-- (int DUMMY_ARG)
Decrement every pixel value in this set.
CPixelView & operator/= (uint8_t d)
Divide every LED by the given value.
CPixelView & operator>>= (uint8_t d)
Shift every LED in this set right by the given number of bits.
CPixelView & operator*= (uint8_t d)
Multiply every LED in this set by the given value.
CPixelView & nscale8_video (uint8_t scaledown)
Scale every LED by the given scale.
CPixelView & operator%= (uint8_t scaledown)
Scale down every LED by the given scale.
CPixelView & fadeLightBy (uint8_t fadefactor)
Fade every LED down by the given scale.
CPixelView & nscale8 (uint8_t scaledown)
Scale every LED by the given scale.
CPixelView & nscale8 (PIXEL_TYPE &scaledown)
Scale every LED by the given scale.
CPixelView & nscale8 (CPixelView &rhs)
Scale every LED in this set by every led in the other set.
CPixelView & fadeToBlackBy (uint8_t fade)
Fade every LED down by the given scale.
CPixelView & operator|= (const PIXEL_TYPE &rhs)
Apply the PIXEL_TYPE |= operator to every pixel in this set with the given PIXEL_TYPE value.
CPixelView & operator|= (const CPixelView &rhs)
Apply the PIXEL_TYPE |= operator to every pixel in this set with every pixel in the passed in set.
CPixelView & operator|= (uint8_t d)
Apply the PIXEL_TYPE |= operator to every pixel in this set.
CPixelView & operator&= (const PIXEL_TYPE &rhs)
Apply the PIXEL_TYPE &= operator to every pixel in this set with the given PIXEL_TYPE value.
CPixelView & operator&= (const CPixelView &rhs)
Apply the PIXEL_TYPE &= operator to every pixel in this set with every pixel in the passed in set.
CPixelView & operator&= (uint8_t d)
Apply the PIXEL_TYPE &= operator to every pixel in this set with the passed in value.
Color Util Functions
CPixelView & fill_solid (const PIXEL_TYPE &color)
Fill all of the LEDs with a solid color.
CPixelView & fill_solid (const CHSV &color)
Fill all of the LEDs with a solid color.
CPixelView & fill_rainbow (uint8_t initialhue, uint8_t deltahue=5)
Fill all of the LEDs with a rainbow of colors.
CPixelView & fill_gradient (const CHSV &startcolor, const CHSV &endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between two HSV colors.
CPixelView & fill_gradient (const CHSV &c1, const CHSV &c2, const CHSV &c3, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between three HSV colors.
CPixelView & fill_gradient (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between four HSV colors.
CPixelView & fill_gradient_RGB (const PIXEL_TYPE &startcolor, const PIXEL_TYPE &endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth RGB gradient between two RGB colors.
CPixelView & fill_gradient_RGB (const PIXEL_TYPE &c1, const PIXEL_TYPE &c2, const PIXEL_TYPE &c3)
Fill all of the LEDs with a smooth RGB gradient between three RGB colors.
CPixelView & fill_gradient_RGB (const PIXEL_TYPE &c1, const PIXEL_TYPE &c2, const PIXEL_TYPE &c3, const PIXEL_TYPE &c4)
Fill all of the LEDs with a smooth RGB gradient between four RGB colors.
CPixelView & nblend (const PIXEL_TYPE &overlay, fract8 amountOfOverlay)
Destructively modifies all LEDs, blending in a given fraction of an overlay color.
CPixelView & nblend (const CPixelView &rhs, fract8 amountOfOverlay)
Destructively blend another set of LEDs into this one.
CPixelView & blur1d (fract8 blur_amount)
One-dimensional blur filter.
CPixelView & napplyGamma_video (float gamma)
Destructively applies a gamma adjustment to all LEDs.
CPixelView & napplyGamma_video (float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to all LEDs.
Public Attributes
const int8_t dir
direction of the LED data, either 1 or -1. Determines how the pointer is incremented.
PIXEL_TYPE *const end_pos
pointer to the end position of the LED data
PIXEL_TYPE *const leds
pointer to the LED data
const int len
length of the LED data, in PIXEL_TYPE units.
Iterator
typedef pixelset_iterator_base< PIXEL_TYPE > iterator
Iterator helper type for this class.
typedef pixelset_iterator_base< const PIXEL_TYPE > const_iterator
Const iterator helper type for this class.
iterator begin ()
Makes an iterator instance for the start of the LED set.
iterator end ()
Makes an iterator instance for the end of the LED set.
iterator begin () const
Makes an iterator instance for the start of the LED set, const qualified.
iterator end () const
Makes an iterator instance for the end of the LED set, const qualified.
const_iterator cbegin () const
Makes a const iterator instance for the start of the LED set, const qualified.
const_iterator cend () const
Makes a const iterator instance for the end of the LED set, const qualified.
Member Typedef Documentation
const_iterator
template<class PIXEL_TYPE > pixelset_iterator_base<const PIXEL_TYPE> CPixelView< PIXEL_TYPE >::const_iterator
Const iterator helper type for this class.
Definition at line 437 of file pixelset.h.
iterator
template<class PIXEL_TYPE > pixelset_iterator_base<PIXEL_TYPE> CPixelView< PIXEL_TYPE >::iterator
Iterator helper type for this class.
Definition at line 436 of file pixelset.h.
Constructor & Destructor Documentation
CPixelView() [1/3]
template<class PIXEL_TYPE > CPixelView< PIXEL_TYPE >::CPixelView (const CPixelView< PIXEL_TYPE > & other) inline
PixelSet copy constructor.
Definition at line 76 of file pixelset.h.
: dir(other.dir), len(other.len), leds(other.leds), end_pos(other.end_pos) {}
Referenced by CPixelView< PIXEL_TYPE >::operator()(), and CPixelView< PIXEL_TYPE >::operator-().
CPixelView() [2/3]
template<class PIXEL_TYPE > CPixelView< PIXEL_TYPE >::CPixelView (PIXEL_TYPE * _leds, int _len) inline
PixelSet constructor for a pixel set starting at the given PIXEL_TYPE* and going for _len leds.
Note that the length can be backwards, creating a PixelSet that walks backwards over the data
Parameters
_leds pointer to the raw LED data
_len how many LEDs in this set
Definition at line 82 of file pixelset.h.
: dir(_len < 0 ? -1 : 1), len(_len), leds(_leds), end_pos(_leds + _len) {}
CPixelView() [3/3]
template<class PIXEL_TYPE > CPixelView< PIXEL_TYPE >::CPixelView (PIXEL_TYPE * _leds, int _start, int _end) inline
PixelSet constructor for the given set of LEDs, with start and end boundaries.
Note that start can be after end, resulting in a set that will iterate backwards
Parameters
_leds pointer to the raw LED data
_start the start index of the LEDs for this array
_end the end index of the LEDs for this array
Definition at line 89 of file pixelset.h.
: dir(((_end-_start)<0) ? -1 : 1), len((_end - _start) + dir), leds(_leds + _start), end_pos(_leds + _start + len) {}
Member Function Documentation
addToRGB()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::addToRGB (uint8_t inc) inline
Add the passed in value to all channels for all of the pixels in this set.
Definition at line 157 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) += inc; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
begin() [1/2]
template<class PIXEL_TYPE > iterator CPixelView< PIXEL_TYPE >::begin () inline
Makes an iterator instance for the start of the LED set.
Definition at line 439 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::leds.
Referenced by CPixelView< PIXEL_TYPE >::addToRGB(), CPixelView< PIXEL_TYPE >::nblend(), CPixelView< PIXEL_TYPE >::nblend(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8_video(), CPixelView< PIXEL_TYPE >::operator bool(), CPixelView< PIXEL_TYPE >::operator%=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator*=(), CPixelView< PIXEL_TYPE >::operator++(), CPixelView< PIXEL_TYPE >::operator++(), CPixelView< PIXEL_TYPE >::operator+=(), CPixelView< PIXEL_TYPE >::operator--(), CPixelView< PIXEL_TYPE >::operator--(), CPixelView< PIXEL_TYPE >::operator-=(), CPixelView< PIXEL_TYPE >::operator/=(), CPixelView< PIXEL_TYPE >::operator=(), CPixelView< PIXEL_TYPE >::operator=(), CPixelView< PIXEL_TYPE >::operator>>=(), CPixelView< PIXEL_TYPE >::operator|=(), CPixelView< PIXEL_TYPE >::operator|=(), CPixelView< PIXEL_TYPE >::operator|=(), and CPixelView< PIXEL_TYPE >::subFromRGB().
begin() [2/2]
template<class PIXEL_TYPE > iterator CPixelView< PIXEL_TYPE >::begin () const inline
Makes an iterator instance for the start of the LED set, const qualified.
Definition at line 442 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::leds.
blur1d()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::blur1d (fract8 blur_amount) inline
One-dimensional blur filter.
Parameters
blur_amount the amount of blur to apply
Note
Only bringing in a 1d blur, not sure 2d blur makes sense when looking at sub arrays
See also
blur1d(CRGB*, uint16_t, fract8)
Definition at line 368 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_BLUR1D(leds, len, blur_amount);
        } else {
            FUNCTION_BLUR1D(leds + len + 1, -len, blur_amount);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_BLUR1D, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
cbegin()
template<class PIXEL_TYPE > const_iterator CPixelView< PIXEL_TYPE >::cbegin () const inline
Makes a const iterator instance for the start of the LED set, const qualified.
Definition at line 445 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::leds.
cend()
template<class PIXEL_TYPE > const_iterator CPixelView< PIXEL_TYPE >::cend () const inline
Makes a const iterator instance for the end of the LED set, const qualified.
Definition at line 446 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::end_pos.
dump()
template<class PIXEL_TYPE > void CPixelView< PIXEL_TYPE >::dump () const inline
Print debug data to serial, disabled for release.
Edit this file to re-enable these for debugging purposes.
Serial.print("len: "); Serial.print(len); Serial.print(", dir:"); Serial.print((int)dir);
Serial.print(", range:"); Serial.print((uint32_t)leds); Serial.print("-"); Serial.print((uint32_t)end_pos);
Serial.print(", diff:"); Serial.print((int32_t)(end_pos - leds));
Serial.println("");
Definition at line 134 of file pixelset.h.
                      {
    }
end() [1/2]
template<class PIXEL_TYPE > iterator CPixelView< PIXEL_TYPE >::end () inline
Makes an iterator instance for the end of the LED set.
Definition at line 440 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::end_pos.
Referenced by CPixelView< PIXEL_TYPE >::addToRGB(), CPixelView< PIXEL_TYPE >::nblend(), CPixelView< PIXEL_TYPE >::nblend(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8(), CPixelView< PIXEL_TYPE >::nscale8_video(), CPixelView< PIXEL_TYPE >::operator bool(), CPixelView< PIXEL_TYPE >::operator%=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator&=(), CPixelView< PIXEL_TYPE >::operator()(), CPixelView< PIXEL_TYPE >::operator*=(), CPixelView< PIXEL_TYPE >::operator++(), CPixelView< PIXEL_TYPE >::operator++(), CPixelView< PIXEL_TYPE >::operator+=(), CPixelView< PIXEL_TYPE >::operator--(), CPixelView< PIXEL_TYPE >::operator--(), CPixelView< PIXEL_TYPE >::operator-=(), CPixelView< PIXEL_TYPE >::operator/=(), CPixelView< PIXEL_TYPE >::operator=(), CPixelView< PIXEL_TYPE >::operator=(), CPixelView< PIXEL_TYPE >::operator>>=(), CPixelView< PIXEL_TYPE >::operator|=(), CPixelView< PIXEL_TYPE >::operator|=(), CPixelView< PIXEL_TYPE >::operator|=(), and CPixelView< PIXEL_TYPE >::subFromRGB().
end() [2/2]
template<class PIXEL_TYPE > iterator CPixelView< PIXEL_TYPE >::end () const inline
Makes an iterator instance for the end of the LED set, const qualified.
Definition at line 443 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::dir, and CPixelView< PIXEL_TYPE >::end_pos.
fadeLightBy()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fadeLightBy (uint8_t fadefactor) inline
Fade every LED down by the given scale.
Definition at line 200 of file pixelset.h.
{ return nscale8_video(255 - fadefactor); }
References CPixelView< PIXEL_TYPE >::nscale8_video().
fadeToBlackBy()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fadeToBlackBy (uint8_t fade) inline
Fade every LED down by the given scale.
Definition at line 210 of file pixelset.h.
{ return nscale8(255 - fade); }
References CPixelView< PIXEL_TYPE >::nscale8().
fill_gradient() [1/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4, TGradientDirectionCode directionCode = SHORTEST_HUES) inline
Fill all of the LEDs with a smooth HSV gradient between four HSV colors.
Parameters
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
directionCode the direction to travel around the color wheel
See also
fill_gradient(T*, uint16_t, const CHSV&, const CHSV&, const CHSV&, const CHSV&, TGradientDirectionCode)
Definition at line 299 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT4(leds, len, c1, c2, c3, c4, directionCode);
        } else {
            FUNCTION_FILL_GRADIENT4(leds + len + 1, -len, c4, c3, c2, c1, directionCode);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_GRADIENT4, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_gradient() [2/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient (const CHSV & c1, const CHSV & c2, const CHSV & c3, TGradientDirectionCode directionCode = SHORTEST_HUES) inline
Fill all of the LEDs with a smooth HSV gradient between three HSV colors.
Parameters
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
directionCode the direction to travel around the color wheel
See also
fill_gradient(T*, uint16_t, const CHSV&, const CHSV&, const CHSV&, TGradientDirectionCode)
Definition at line 283 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT3(leds, len, c1, c2, c3, directionCode);
        } else {
            FUNCTION_FILL_GRADIENT3(leds + len + 1, -len, c3, c2, c1, directionCode);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_GRADIENT3, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_gradient() [3/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient (const CHSV & startcolor, const CHSV & endcolor, TGradientDirectionCode directionCode = SHORTEST_HUES) inline
Fill all of the LEDs with a smooth HSV gradient between two HSV colors.
Parameters
startcolor the starting color in the gradient
endcolor the end color for the gradient
directionCode the direction to travel around the color wheel
See also
fill_gradient(T*, uint16_t, const CHSV&, const CHSV&, TGradientDirectionCode)
Definition at line 268 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT(leds,len,startcolor, endcolor, directionCode);
        } else {
            FUNCTION_FILL_GRADIENT(leds + len + 1, (-len), endcolor, startcolor, directionCode);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_GRADIENT, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_gradient_RGB() [1/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient_RGB (const PIXEL_TYPE & c1, const PIXEL_TYPE & c2, const PIXEL_TYPE & c3) inline
Fill all of the LEDs with a smooth RGB gradient between three RGB colors.
Parameters
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
See also
fill_gradient_RGB(CRGB*, uint16_t, const CRGB&, const CRGB&, const CRGB&)
Definition at line 328 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT_RGB3(leds, len, c1, c2, c3);
        } else {
            FUNCTION_FILL_GRADIENT_RGB3(leds + len + 1, -len, c3, c2, c1);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_GRADIENT_RGB3, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_gradient_RGB() [2/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient_RGB (const PIXEL_TYPE & c1, const PIXEL_TYPE & c2, const PIXEL_TYPE & c3, const PIXEL_TYPE & c4) inline
Fill all of the LEDs with a smooth RGB gradient between four RGB colors.
Parameters
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
See also
fill_gradient_RGB(CRGB*, uint16_t, const CRGB&, const CRGB&, const CRGB&, const CRGB&)
Definition at line 343 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT_RGB4(leds, len, c1, c2, c3, c4);
        } else {
            FUNCTION_FILL_GRADIENT_RGB4(leds + len + 1, -len, c4, c3, c2, c1);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_GRADIENT_RGB4, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_gradient_RGB() [3/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_gradient_RGB (const PIXEL_TYPE & startcolor, const PIXEL_TYPE & endcolor, TGradientDirectionCode directionCode = SHORTEST_HUES) inline
Fill all of the LEDs with a smooth RGB gradient between two RGB colors.
Parameters
startcolor the starting color in the gradient
endcolor the end color for the gradient
directionCode the direction to travel around the color wheel
See also
fill_gradient_RGB(CRGB*, uint16_t, const CRGB&, const CRGB&)
Definition at line 313 of file pixelset.h.
{
        FASTLED_UNUSED(directionCode); // TODO: why is this not used?
        if(dir >= 0) {
            FUNCTION_FILL_GRADIENT_RGB(leds,len,startcolor, endcolor);
        } else {
            FUNCTION_FILL_GRADIENT_RGB(leds + len + 1, (-len), endcolor, startcolor);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FASTLED_UNUSED, FUNCTION_FILL_GRADIENT_RGB, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_rainbow()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_rainbow (uint8_t initialhue, uint8_t deltahue = 5) inline
Fill all of the LEDs with a rainbow of colors.
Parameters
initialhue the starting hue for the rainbow
deltahue how many hue values to advance for each LED
See also
fill_rainbow(struct CRGB*, int, uint8_t, uint8_t)
Definition at line 254 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_FILL_RAINBOW(leds,len,initialhue,deltahue);
        } else {
            FUNCTION_FILL_RAINBOW(leds + len + 1, -len, initialhue - deltahue * (len+1), -deltahue);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_FILL_RAINBOW, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
fill_solid() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_solid (const CHSV & color) inline
Fill all of the LEDs with a solid color.
Parameters
color the color to fill with
Definition at line 248 of file pixelset.h.
{ *this = color; return *this; }
fill_solid() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::fill_solid (const PIXEL_TYPE & color) inline
Fill all of the LEDs with a solid color.
Parameters
color the color to fill with
Definition at line 246 of file pixelset.h.
{ *this = color; return *this; }
napplyGamma_video() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::napplyGamma_video (float gamma) inline
Destructively applies a gamma adjustment to all LEDs.
Parameters
gamma the gamma value to apply
See also
napplyGamma_video(CRGB&, float)
Definition at line 380 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_NAPPLY_GAMMA(leds, len, gamma);
        } else {
            FUNCTION_NAPPLY_GAMMA(leds + len + 1, -len, gamma);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_NAPPLY_GAMMA, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
napplyGamma_video() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::napplyGamma_video (float gammaR, float gammaG, float gammaB) inline
Destructively applies a gamma adjustment to all LEDs.
Parameters
gammaR the gamma value to apply to the CRGB::red channel
gammaG the gamma value to apply to the CRGB::green channel
gammaB the gamma value to apply to the CRGB::blue channel
See also
napplyGamma_video(CRGB&, float, float, float)
Definition at line 394 of file pixelset.h.
{
        if(dir >= 0) {
            FUNCTION_NAPPLY_GAMMA_RGB(leds, len, gammaR, gammaG, gammaB);
        } else {
            FUNCTION_NAPPLY_GAMMA_RGB(leds + len + 1, -len, gammaR, gammaG, gammaB);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::dir, FUNCTION_NAPPLY_GAMMA_RGB, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
nblend() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nblend (const CPixelView< PIXEL_TYPE > & rhs, fract8 amountOfOverlay) inline
Destructively blend another set of LEDs into this one.
Parameters
rhs the set of LEDs to blend into this set
amountOfOverlay the fraction of each color in the other set to blend in
See also
nblend(CRGB&, const CRGB&, fract8)
Definition at line 362 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { FUNCTION_NBLEND((*pixel), (*rhspixel), amountOfOverlay); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::end(), and FUNCTION_NBLEND.
nblend() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nblend (const PIXEL_TYPE & overlay, fract8 amountOfOverlay) inline
Destructively modifies all LEDs, blending in a given fraction of an overlay color.
Parameters
overlay the color to blend in
amountOfOverlay the fraction of overlay to blend in
See also
nblend(CRGB&, const CRGB&, fract8)
Definition at line 356 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { FUNCTION_NBLEND((*pixel), overlay, amountOfOverlay); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::end(), and FUNCTION_NBLEND.
nscale8() [1/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nscale8 (CPixelView< PIXEL_TYPE > & rhs) inline
Scale every LED in this set by every led in the other set.
Definition at line 207 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { (*pixel).nscale8((*rhspixel)); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
nscale8() [2/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nscale8 (PIXEL_TYPE & scaledown) inline
Scale every LED by the given scale.
Definition at line 205 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel).nscale8(scaledown); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
nscale8() [3/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nscale8 (uint8_t scaledown) inline
Scale every LED by the given scale.
Definition at line 203 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel).nscale8(scaledown); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
Referenced by CPixelView< PIXEL_TYPE >::fadeToBlackBy().
nscale8_video()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::nscale8_video (uint8_t scaledown) inline
Scale every LED by the given scale.
Definition at line 196 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel).nscale8_video(scaledown); } return *this;}
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
Referenced by CPixelView< PIXEL_TYPE >::fadeLightBy().
operator bool()
template<class PIXEL_TYPE > CPixelView< PIXEL_TYPE >::operator bool () inline
Returns whether or not any LEDs in this set are non-zero.
Definition at line 238 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { if((*pixel)) return true; } return false; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator PIXEL_TYPE *()
template<class PIXEL_TYPE > CPixelView< PIXEL_TYPE >::operator PIXEL_TYPE * () const inline
Return a pointer to the first element in this set.
Definition at line 123 of file pixelset.h.
{ return leds; }
operator!=()
template<class PIXEL_TYPE > bool CPixelView< PIXEL_TYPE >::operator!= (const CPixelView< PIXEL_TYPE > & rhs) const inline
Do these sets point to different things? Note that this is different from the contents of the set being the same.
Definition at line 103 of file pixelset.h.
{ return leds != rhs.leds || len != rhs.len || dir != rhs.dir; }
References CPixelView< PIXEL_TYPE >::dir, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
operator%=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator%= (uint8_t scaledown) inline
Scale down every LED by the given scale.
Definition at line 198 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel).nscale8_video(scaledown); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator&=() [1/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator&= (const CPixelView< PIXEL_TYPE > & rhs) inline
Apply the PIXEL_TYPE &= operator to every pixel in this set with every pixel in the passed in set.
With CRGB, this brings up each channel down to the lower of the two values
See also
CRGB::operator&=
Definition at line 229 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { (*pixel) &= (*rhspixel); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator&=() [2/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator&= (const PIXEL_TYPE & rhs) inline
Apply the PIXEL_TYPE &= operator to every pixel in this set with the given PIXEL_TYPE value.
With CRGB, this brings up each channel down to the lower of the two values
See also
CRGB::operator&=
Definition at line 226 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) &= rhs; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator&=() [3/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator&= (uint8_t d) inline
Apply the PIXEL_TYPE &= operator to every pixel in this set with the passed in value.
With CRGB, this brings up each channel down to the lower of the two values
See also
CRGB::operator&=
Definition at line 232 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) &= d; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator()()
template<class PIXEL_TYPE > CPixelView CPixelView< PIXEL_TYPE >::operator() (int start, int end) inline
Access an inclusive subset of the LEDs in this set.
Note
The start point can be greater than end, which will result in a reverse ordering for many functions (useful for mirroring).
Parameters
start the first element from this set for the new subset
end the last element for the new subset
Definition at line 113 of file pixelset.h.
{ if(dir & 0x80) { return CPixelView(leds+len+1, -len-start-1, -len-end-1); } else { return CPixelView(leds, start, end); } }
References CPixelView< PIXEL_TYPE >::CPixelView(), CPixelView< PIXEL_TYPE >::dir, CPixelView< PIXEL_TYPE >::end(), CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
operator*=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator*= (uint8_t d) inline
Multiply every LED in this set by the given value.
Definition at line 193 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) *= d; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator++() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator++ () inline
Increment every pixel value in this set.
Definition at line 167 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel)++; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator++() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator++ (int DUMMY_ARG) inline
Increment every pixel value in this set.
Definition at line 169 of file pixelset.h.
{
        FASTLED_UNUSED(DUMMY_ARG);
        for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) {
            (*pixel)++;
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::end(), and FASTLED_UNUSED.
operator+=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator+= (CPixelView< PIXEL_TYPE > & rhs) inline
Add every pixel in the other set to this set.
Definition at line 159 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { (*pixel) += (*rhspixel); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator-()
template<class PIXEL_TYPE > CPixelView CPixelView< PIXEL_TYPE >::operator- () inline
Return the reverse ordering of this set.
Definition at line 120 of file pixelset.h.
{ return CPixelView(leds, len - dir, 0); }
References CPixelView< PIXEL_TYPE >::CPixelView(), CPixelView< PIXEL_TYPE >::dir, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
operator--() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator-- () inline
Decrement every pixel value in this set.
Definition at line 178 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel)--; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator--() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator-- (int DUMMY_ARG) inline
Decrement every pixel value in this set.
Definition at line 180 of file pixelset.h.
{
        FASTLED_UNUSED(DUMMY_ARG);
        for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) {
            (*pixel)--;
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::end(), and FASTLED_UNUSED.
operator-=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator-= (CPixelView< PIXEL_TYPE > & rhs) inline
Subtract every pixel in the other set from this set.
Definition at line 164 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { (*pixel) -= (*rhspixel); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator/=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator/= (uint8_t d) inline
Divide every LED by the given value.
Definition at line 189 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) /= d; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator=() [1/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator= (const CPixelView< PIXEL_TYPE > & rhs) inline
Copy the contents of the passed-in set to our set.
Note
If one set is smaller than the other, only the smallest number of items will be copied over.
Definition at line 146 of file pixelset.h.
{
        for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) {
            (*pixel) = (*rhspixel);
        }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator=() [2/2]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator= (const PIXEL_TYPE & color) inline
Assign the passed in color to all elements in this set.
Parameters
color the new color for the elements in the set
Definition at line 127 of file pixelset.h.
{
        for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) = color; }
        return *this;
    }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator==()
template<class PIXEL_TYPE > bool CPixelView< PIXEL_TYPE >::operator== (const CPixelView< PIXEL_TYPE > & rhs) const inline
Do these sets point to the same thing? Note that this is different from the contents of the set being the same.
Definition at line 100 of file pixelset.h.
{ return leds == rhs.leds && len == rhs.len && dir == rhs.dir; }
References CPixelView< PIXEL_TYPE >::dir, CPixelView< PIXEL_TYPE >::leds, and CPixelView< PIXEL_TYPE >::len.
operator>>=()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator>>= (uint8_t d) inline
Shift every LED in this set right by the given number of bits.
Definition at line 191 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) >>= d; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator[]()
template<class PIXEL_TYPE > PIXEL_TYPE & CPixelView< PIXEL_TYPE >::operator[] (int x) const inline
Access a single element in this set, just like an array operator.
Definition at line 106 of file pixelset.h.
{ if(dir & 0x80) { return leds[-x]; } else { return leds[x]; } }
References CPixelView< PIXEL_TYPE >::dir, CPixelView< PIXEL_TYPE >::leds, and x.
operator|=() [1/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator|= (const CPixelView< PIXEL_TYPE > & rhs) inline
Apply the PIXEL_TYPE |= operator to every pixel in this set with every pixel in the passed in set.
With CRGB, this brings up each channel to the higher of the two values
See also
CRGB::operator|=
Definition at line 218 of file pixelset.h.
{ for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) { (*pixel) |= (*rhspixel); } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator|=() [2/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator|= (const PIXEL_TYPE & rhs) inline
Apply the PIXEL_TYPE |= operator to every pixel in this set with the given PIXEL_TYPE value.
With CRGB, this brings up each channel to the higher of the two values
See also
CRGB::operator|=
Definition at line 215 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) |= rhs; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
operator|=() [3/3]
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::operator|= (uint8_t d) inline
Apply the PIXEL_TYPE |= operator to every pixel in this set.
With CRGB, this brings up each channel to the higher of the two values
See also
CRGB::operator|=
Definition at line 221 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) |= d; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
reversed()
template<class PIXEL_TYPE > bool CPixelView< PIXEL_TYPE >::reversed () inline
Whether or not this set goes backwards.
Returns
whether or not the set is backwards
Definition at line 97 of file pixelset.h.
{ return len < 0; }
References CPixelView< PIXEL_TYPE >::len.
size()
template<class PIXEL_TYPE > int CPixelView< PIXEL_TYPE >::size () inline
Get the size of this set.
Returns
the size of the set, in number of LEDs
Definition at line 93 of file pixelset.h.
{ return abs(len); }
References CPixelView< PIXEL_TYPE >::len.
subFromRGB()
template<class PIXEL_TYPE > CPixelView & CPixelView< PIXEL_TYPE >::subFromRGB (uint8_t inc) inline
Subtract the passed in value from all channels for all of the pixels in this set.
Definition at line 162 of file pixelset.h.
{ for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) -= inc; } return *this; }
References CPixelView< PIXEL_TYPE >::begin(), and CPixelView< PIXEL_TYPE >::end().
Member Data Documentation
dir
template<class PIXEL_TYPE > const int8_t CPixelView< PIXEL_TYPE >::dir
direction of the LED data, either 1 or -1. Determines how the pointer is incremented.
Definition at line 68 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::blur1d(), CPixelView< PIXEL_TYPE >::cbegin(), CPixelView< PIXEL_TYPE >::cend(), CPixelView< PIXEL_TYPE >::end(), CPixelView< PIXEL_TYPE >::end(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_rainbow(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< PIXEL_TYPE >::operator!=(), CPixelView< PIXEL_TYPE >::operator()(), CPixelView< PIXEL_TYPE >::operator-(), CPixelView< PIXEL_TYPE >::operator==(), and CPixelView< PIXEL_TYPE >::operator[]().
end_pos
template<class PIXEL_TYPE > PIXEL_TYPE* const CPixelView< PIXEL_TYPE >::end_pos
pointer to the end position of the LED data
Definition at line 72 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::cend(), CPixelView< PIXEL_TYPE >::end(), and CPixelView< PIXEL_TYPE >::end().
leds
template<class PIXEL_TYPE > PIXEL_TYPE* const CPixelView< PIXEL_TYPE >::leds
pointer to the LED data
Definition at line 71 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::begin(), CPixelView< PIXEL_TYPE >::blur1d(), CPixelView< PIXEL_TYPE >::cbegin(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_rainbow(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< CRGB >::operator CRGB *(), CPixelView< PIXEL_TYPE >::operator!=(), CPixelView< PIXEL_TYPE >::operator()(), CPixelView< PIXEL_TYPE >::operator-(), CPixelView< PIXEL_TYPE >::operator==(), and CPixelView< PIXEL_TYPE >::operator[]().
len
template<class PIXEL_TYPE > const int CPixelView< PIXEL_TYPE >::len
length of the LED data, in PIXEL_TYPE units.
More accurately, it's the distance from the start of the CPixelView::leds array to the end of the set (CPixelView::end_pos)
Definition at line 69 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::blur1d(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_gradient_RGB(), CPixelView< PIXEL_TYPE >::fill_rainbow(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< PIXEL_TYPE >::napplyGamma_video(), CPixelView< PIXEL_TYPE >::operator!=(), CPixelView< PIXEL_TYPE >::operator()(), CPixelView< PIXEL_TYPE >::operator-(), CPixelView< PIXEL_TYPE >::operator==(), CPixelView< PIXEL_TYPE >::reversed(), and CPixelView< PIXEL_TYPE >::size().
CPixelView::pixelset_iterator_base
class CPixelView::pixelset_iterator_base
Public Member Functions
FASTLED_FORCE_INLINE pixelset_iterator_base (const pixelset_iterator_base &rhs)
Copy constructor.
FASTLED_FORCE_INLINE pixelset_iterator_base (T *_leds, const char _dir)
Base constructor.
FASTLED_FORCE_INLINE bool operator!= (pixelset_iterator_base &other) const
Check if iterator is not at the same position.
FASTLED_FORCE_INLINE PIXEL_TYPE & operator* () const
Dereference operator, to get underlying pointer to the LEDs.
FASTLED_FORCE_INLINE pixelset_iterator_base & operator++ ()
Increment LED pointer in data direction.
FASTLED_FORCE_INLINE pixelset_iterator_base operator++ (int)
Increment LED pointer in data direction.
FASTLED_FORCE_INLINE bool operator== (pixelset_iterator_base &other) const
Check if iterator is at the same position.
Private Attributes
const int8_t dir
direction of LED array, for incrementing the pointer
T * leds
pointer to LED array
Constructor & Destructor Documentation
pixelset_iterator_base() [1/2]
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::pixelset_iterator_base (const pixelset_iterator_base< T > & rhs) inline
Copy constructor.
Definition at line 419 of file pixelset.h.
: leds(rhs.leds), dir(rhs.dir) {}
pixelset_iterator_base() [2/2]
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::pixelset_iterator_base (T * _leds, const char _dir) inline
Base constructor.
Template Parameters
the type of the LED array data
Parameters
_leds pointer to LED array
_dir direction of LED array
Definition at line 425 of file pixelset.h.
: leds(_leds), dir(_dir) {}
Member Function Documentation
operator!=()
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE bool CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator!= (pixelset_iterator_base< T > & other) const inline
Check if iterator is not at the same position.
Definition at line 431 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds.
operator*()
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE PIXEL_TYPE & CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator* () const inline
Dereference operator, to get underlying pointer to the LEDs.
Definition at line 433 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds.
operator++() [1/2]
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE pixelset_iterator_base & CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++ () inline
Increment LED pointer in data direction.
Definition at line 427 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::dir, and CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds.
operator++() [2/2]
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE pixelset_iterator_base CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++ (int) inline
Increment LED pointer in data direction.
Definition at line 428 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::dir, and CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds.
operator==()
template<class PIXEL_TYPE > template<class T > FASTLED_FORCE_INLINE bool CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator== (pixelset_iterator_base< T > & other) const inline
Check if iterator is at the same position.
Definition at line 430 of file pixelset.h.
References CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds.
Member Data Documentation
dir
template<class PIXEL_TYPE > template<class T > const int8_t CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::dir private
direction of LED array, for incrementing the pointer
Definition at line 415 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++(), and CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++().
leds
template<class PIXEL_TYPE > template<class T > T* CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::leds private
pointer to LED array
Definition at line 414 of file pixelset.h.
Referenced by CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator!=(), CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator*(), CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++(), CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator++(), and CPixelView< PIXEL_TYPE >::pixelset_iterator_base< T >::operator==().
CRGBArray
class CRGBArray
Public Member Functions
CRGBArray ()
CRGB * get ()
const CRGB * get () const
CPixelView & operator= (const CPixelView &rhs)
Copy the contents of the passed-in set to our set.
CPixelView & operator= (const PIXEL_TYPE &color)
Assign the passed in color to all elements in this set.
size_t size () const
Public Member Functions inherited from CPixelView< CRGB >
CPixelView (const CPixelView &other)
PixelSet copy constructor.
CPixelView (CRGB *_leds, int _len)
PixelSet constructor for a pixel set starting at the given PIXEL_TYPE* and going for _len leds.
CPixelView (CRGB *_leds, int _start, int _end)
PixelSet constructor for the given set of LEDs, with start and end boundaries.
void dump () const
Print debug data to serial, disabled for release.
operator bool ()
Returns whether or not any LEDs in this set are non-zero.
operator CRGB * () const
Return a pointer to the first element in this set.
bool operator!= (const CPixelView &rhs) const
Do these sets point to different things? Note that this is different from the contents of the set being the same.
CPixelView operator() (int start, int end)
Access an inclusive subset of the LEDs in this set.
CPixelView operator- ()
Return the reverse ordering of this set.
CPixelView & operator= (const CPixelView &rhs)
Copy the contents of the passed-in set to our set.
CPixelView & operator= (const CRGB &color)
Assign the passed in color to all elements in this set.
bool operator== (const CPixelView &rhs) const
Do these sets point to the same thing? Note that this is different from the contents of the set being the same.
CRGB & operator[] (int x) const
Access a single element in this set, just like an array operator.
bool reversed ()
Whether or not this set goes backwards.
int size ()
Get the size of this set.
CPixelView & addToRGB (uint8_t inc)
Add the passed in value to all channels for all of the pixels in this set.
CPixelView & operator+= (CPixelView &rhs)
Add every pixel in the other set to this set.
CPixelView & subFromRGB (uint8_t inc)
Subtract the passed in value from all channels for all of the pixels in this set.
CPixelView & operator-= (CPixelView &rhs)
Subtract every pixel in the other set from this set.
CPixelView & operator++ ()
Increment every pixel value in this set.
CPixelView & operator++ (int DUMMY_ARG)
Increment every pixel value in this set.
CPixelView & operator-- ()
Decrement every pixel value in this set.
CPixelView & operator-- (int DUMMY_ARG)
Decrement every pixel value in this set.
CPixelView & operator/= (uint8_t d)
Divide every LED by the given value.
CPixelView & operator>>= (uint8_t d)
Shift every LED in this set right by the given number of bits.
CPixelView & operator*= (uint8_t d)
Multiply every LED in this set by the given value.
CPixelView & nscale8_video (uint8_t scaledown)
Scale every LED by the given scale.
CPixelView & operator%= (uint8_t scaledown)
Scale down every LED by the given scale.
CPixelView & fadeLightBy (uint8_t fadefactor)
Fade every LED down by the given scale.
CPixelView & nscale8 (uint8_t scaledown)
Scale every LED by the given scale.
CPixelView & nscale8 (CRGB &scaledown)
Scale every LED by the given scale.
CPixelView & nscale8 (CPixelView &rhs)
Scale every LED in this set by every led in the other set.
CPixelView & fadeToBlackBy (uint8_t fade)
Fade every LED down by the given scale.
CPixelView & operator|= (const CRGB &rhs)
Apply the PIXEL_TYPE |= operator to every pixel in this set with the given PIXEL_TYPE value.
CPixelView & operator|= (const CPixelView &rhs)
Apply the PIXEL_TYPE |= operator to every pixel in this set with every pixel in the passed in set.
CPixelView & operator|= (uint8_t d)
Apply the PIXEL_TYPE |= operator to every pixel in this set.
CPixelView & operator&= (const CRGB &rhs)
Apply the PIXEL_TYPE &= operator to every pixel in this set with the given PIXEL_TYPE value.
CPixelView & operator&= (const CPixelView &rhs)
Apply the PIXEL_TYPE &= operator to every pixel in this set with every pixel in the passed in set.
CPixelView & operator&= (uint8_t d)
Apply the PIXEL_TYPE &= operator to every pixel in this set with the passed in value.
CPixelView & fill_solid (const CRGB &color)
Fill all of the LEDs with a solid color.
CPixelView & fill_solid (const CHSV &color)
Fill all of the LEDs with a solid color.
CPixelView & fill_rainbow (uint8_t initialhue, uint8_t deltahue=5)
Fill all of the LEDs with a rainbow of colors.
CPixelView & fill_gradient (const CHSV &startcolor, const CHSV &endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between two HSV colors.
CPixelView & fill_gradient (const CHSV &c1, const CHSV &c2, const CHSV &c3, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between three HSV colors.
CPixelView & fill_gradient (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth HSV gradient between four HSV colors.
CPixelView & fill_gradient_RGB (const CRGB &startcolor, const CRGB &endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill all of the LEDs with a smooth RGB gradient between two RGB colors.
CPixelView & fill_gradient_RGB (const CRGB &c1, const CRGB &c2, const CRGB &c3)
Fill all of the LEDs with a smooth RGB gradient between three RGB colors.
CPixelView & fill_gradient_RGB (const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Fill all of the LEDs with a smooth RGB gradient between four RGB colors.
CPixelView & nblend (const CRGB &overlay, fract8 amountOfOverlay)
Destructively modifies all LEDs, blending in a given fraction of an overlay color.
CPixelView & nblend (const CPixelView &rhs, fract8 amountOfOverlay)
Destructively blend another set of LEDs into this one.
CPixelView & blur1d (fract8 blur_amount)
One-dimensional blur filter.
CPixelView & napplyGamma_video (float gamma)
Destructively applies a gamma adjustment to all LEDs.
CPixelView & napplyGamma_video (float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to all LEDs.
iterator begin ()
Makes an iterator instance for the start of the LED set.
iterator begin () const
Makes an iterator instance for the start of the LED set, const qualified.
iterator end ()
Makes an iterator instance for the end of the LED set.
iterator end () const
Makes an iterator instance for the end of the LED set, const qualified.
const_iterator cbegin () const
Makes a const iterator instance for the start of the LED set, const qualified.
const_iterator cend () const
Makes a const iterator instance for the end of the LED set, const qualified.
Private Attributes
CRGB rawleds [SIZE] = {0}
the LED data
Additional Inherited Members
Public Types inherited from CPixelView< CRGB >
typedef pixelset_iterator_base< CRGB > iterator
Iterator helper type for this class.
typedef pixelset_iterator_base< const CRGB > const_iterator
Const iterator helper type for this class.
Public Attributes inherited from CPixelView< CRGB >
const int8_t dir
direction of the LED data, either 1 or -1. Determines how the pointer is incremented.
CRGB *const end_pos
pointer to the end position of the LED data
CRGB *const leds
pointer to the LED data
const int len
length of the LED data, in PIXEL_TYPE units.
Constructor & Destructor Documentation
CRGBArray()
template<int SIZE> CRGBArray< SIZE >::CRGBArray () inline
Definition at line 464 of file pixelset.h.
: CPixelView<CRGB>(rawleds, SIZE) {}
Member Function Documentation
get() [1/2]
template<int SIZE> CRGB * CRGBArray< SIZE >::get () inline
Definition at line 466 of file pixelset.h.
{ return &rawleds[0]; }
References CRGBArray< SIZE >::rawleds.
get() [2/2]
template<int SIZE> const CRGB * CRGBArray< SIZE >::get () const inline
Definition at line 467 of file pixelset.h.
{  return &rawleds[0]; }
References CRGBArray< SIZE >::rawleds.
operator=() [1/2]
template<int SIZE> CPixelView & CPixelView< PIXEL_TYPE >::operator= (const CPixelView & rhs) inline
Copy the contents of the passed-in set to our set.
Note
If one set is smaller than the other, only the smallest number of items will be copied over.
Definition at line 146 of file pixelset.h.
{
        for(iterator pixel = begin(), rhspixel = rhs.begin(), _end = end(), rhs_end = rhs.end(); (pixel != _end) && (rhspixel != rhs_end); ++pixel, ++rhspixel) {
            (*pixel) = (*rhspixel);
        }
        return *this;
    }
operator=() [2/2]
template<int SIZE> CPixelView & CPixelView< PIXEL_TYPE >::operator= (const PIXEL_TYPE & color) inline
Assign the passed in color to all elements in this set.
Parameters
color the new color for the elements in the set
Definition at line 127 of file pixelset.h.
{
        for(iterator pixel = begin(), _end = end(); pixel != _end; ++pixel) { (*pixel) = color; }
        return *this;
    }
size()
template<int SIZE> size_t CRGBArray< SIZE >::size () const inline
Definition at line 468 of file pixelset.h.
{ return SIZE; }
Member Data Documentation
rawleds
template<int SIZE> CRGB CRGBArray< SIZE >::rawleds[SIZE] = {0} private
the LED data
Definition at line 461 of file pixelset.h.
{0};
Referenced by CRGBArray< SIZE >::get(), and CRGBArray< SIZE >::get().
Function Documentation
operator+()
FASTLED_FORCE_INLINE CRGB * operator+ (const CRGBSet & pixels, int offset)
Retrieve a pointer to a CRGB array, using a CRGBSet and an LED offset.
Definition at line 452 of file pixelset.h.
{
    return (CRGB*)pixels + offset;
}