FastLED: /home/runner/work/FastLED/FastLED/examples/FxDemoReel100/FxDemoReel100.ino File Reference
FxDemoReel100.ino File Reference
#include <FastLED.h>
#include "fx/1d/demoreel100.h"
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define DATA_PIN 3
#define FRAMES_PER_SECOND 120
#define LED_TYPE WS2811
#define NUM_LEDS 64
#define USES_RGBW 0
Functions
void loop ()
void setup ()
Variables
DemoReel100Ptr demoReel = DemoReel100Ptr::New(NUM_LEDS)
CRGB leds [NUM_LEDS]
Rgbw rgbwMode = RgbwInvalid()
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 17 of file FxDemoReel100.ino.
Referenced by setup().
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 13 of file FxDemoReel100.ino.
Referenced by setup().
DATA_PIN
#define DATA_PIN 3
Definition at line 10 of file FxDemoReel100.ino.
Referenced by setup().
FRAMES_PER_SECOND
#define FRAMES_PER_SECOND 120
Definition at line 18 of file FxDemoReel100.ino.
Referenced by loop().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 12 of file FxDemoReel100.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 64
Definition at line 14 of file FxDemoReel100.ino.
Referenced by setup().
USES_RGBW
#define USES_RGBW 0
Definition at line 19 of file FxDemoReel100.ino.
Function Documentation
loop()
void loop ()
Definition at line 41 of file FxDemoReel100.ino.
{
    // Run the DemoReel100 draw function
    demoReel->draw(Fx::DrawContext(millis(), leds));
    // send the 'leds' array out to the actual LED strip
    FastLED.show();
    // insert a delay to keep the framerate modest
    FastLED.delay(1000/FRAMES_PER_SECOND);
}
References CFastLED::delay(), demoReel, FastLED, FRAMES_PER_SECOND, leds, and CFastLED::show().
setup()
void setup ()
Definition at line 29 of file FxDemoReel100.ino.
             {
  delay(3000); // 3 second delay for recovery
  // tell FastLED about the LED strip configuration
  FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS)
    .setCorrection(TypicalLEDStrip)
    .setRgbw(rgbwMode);
  // set master brightness control
  FastLED.setBrightness(BRIGHTNESS);
}
References CFastLED::addLeds(), BRIGHTNESS, COLOR_ORDER, DATA_PIN, FastLED, LED_TYPE, leds, NUM_LEDS, rgbwMode, CFastLED::setBrightness(), CLEDController::setRgbw(), and TypicalLEDStrip.
Variable Documentation
demoReel
DemoReel100Ptr demoReel = DemoReel100Ptr::New(NUM_LEDS)
Definition at line 27 of file FxDemoReel100.ino.
Referenced by loop().
leds
CRGB leds[NUM_LEDS]
Definition at line 15 of file FxDemoReel100.ino.
Referenced by loop(), and setup().
rgbwMode
Rgbw rgbwMode = RgbwInvalid()
Definition at line 24 of file FxDemoReel100.ino.
Referenced by setup().