FastLED: fl::FixedVector< T, N > Class Template Reference
fl::FixedVector< T, N > Class Template Reference
Detailed Description
template<typename T, size_t N>
class fl::FixedVector< T, N >
Definition at line 19 of file vector.h.
#include <vector.h>
Public Types
typedef const T * const_iterator
typedef T * iterator
Public Member Functions
constexpr FixedVector ()
template<size_t M>
FixedVector (const T(&values)[M])
FixedVector (const T(&values)[N])
~FixedVector ()
void assign (const T *values, size_t count)
void assign (const_iterator begin, const_iterator end)
T & back ()
const T & back () const
iterator begin ()
const_iterator begin () const
constexpr size_t capacity () const
void clear ()
iterator data ()
const_iterator data () const
constexpr bool empty () const
iterator end ()
const_iterator end () const
iterator erase (const T &value)
iterator erase (iterator pos)
iterator find (const T &value)
const_iterator find (const T &value) const
template<typename Predicate >
iterator find_if (Predicate pred)
T & front ()
const T & front () const
bool has (const T &value) const
bool insert (iterator pos, const T &value)
T & operator[] (size_t index)
const T & operator[] (size_t index) const
void pop_back ()
void push_back (const T &value)
constexpr size_t size () const
Private Attributes
union {
T mData [N]
char mRaw [N *sizeof(T)]
};
size_t current_size = 0
Member Typedef Documentation
const_iterator
template<typename T , size_t N> const T* fl::FixedVector< T, N >::const_iterator
Definition at line 29 of file vector.h.
iterator
template<typename T , size_t N> T* fl::FixedVector< T, N >::iterator
Definition at line 28 of file vector.h.
Constructor & Destructor Documentation
FixedVector() [1/3]
template<typename T , size_t N> fl::FixedVector< T, N >::FixedVector () inline constexpr
Definition at line 31 of file vector.h.
: current_size(0) {}
FixedVector() [2/3]
template<typename T , size_t N> fl::FixedVector< T, N >::FixedVector (const T(&) values[N]) inline
Definition at line 33 of file vector.h.
                                      : current_size(N) {
        assign(values, N);
    }
References fl::FixedVector< T, N >::assign().
FixedVector() [3/3]
template<typename T , size_t N> template<size_t M> fl::FixedVector< T, N >::FixedVector (const T(&) values[M]) inline
Definition at line 38 of file vector.h.
                                      : current_size(M) {
        static_assert(M <= N, "Too many elements for FixedVector");
        assign(values, M);
    }
References fl::FixedVector< T, N >::assign().
~FixedVector()
template<typename T , size_t N> fl::FixedVector< T, N >::~FixedVector () inline
Definition at line 44 of file vector.h.
                   {
        clear();
    }
References fl::FixedVector< T, N >::clear().
Member Function Documentation
assign() [1/2]
template<typename T , size_t N> void fl::FixedVector< T, N >::assign (const T * values, size_t count) inline
Definition at line 85 of file vector.h.
{
        clear();
        for (size_t i = 0; i < count; ++i) {
            push_back(values[i]);
        }
    }
References fl::FixedVector< T, N >::clear(), and fl::FixedVector< T, N >::push_back().
Referenced by fl::FixedVector< T, N >::FixedVector(), and fl::FixedVector< T, N >::FixedVector().
assign() [2/2]
template<typename T , size_t N> void fl::FixedVector< T, N >::assign (const_iterator begin, const_iterator end) inline
Definition at line 92 of file vector.h.
{
        clear();
        for (const_iterator it = begin; it != end; ++it) {
            push_back(*it);
        }
    }
References fl::FixedVector< T, N >::begin(), fl::FixedVector< T, N >::clear(), fl::FixedVector< T, N >::end(), and fl::FixedVector< T, N >::push_back().
back() [1/2]
template<typename T , size_t N> T & fl::FixedVector< T, N >::back () inline
Definition at line 199 of file vector.h.
              {
        return mData[current_size - 1];
    }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedSet< Key, N >::back(), and fl::FixedMap< Key, Value, N >::operator[]().
back() [2/2]
template<typename T , size_t N> const T & fl::FixedVector< T, N >::back () const inline
Definition at line 203 of file vector.h.
{
        return mData[current_size - 1];
    }
References fl::FixedVector< T, N >::current_size.
begin() [1/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::begin () inline
Definition at line 208 of file vector.h.
{ return &mData[0]; }
Referenced by fl::FixedVector< T, N >::assign(), fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::begin(), fl::FixedSet< Key, N >::begin(), fl::FixedSet< Key, N >::begin(), fl::FixedVector< T, N >::data(), fl::FixedVector< T, N >::data(), fl::FixedVector< T, N >::find(), fl::FixedVector< T, N >::find(), and fl::FixedVector< T, N >::find_if().
begin() [2/2]
template<typename T , size_t N> const_iterator fl::FixedVector< T, N >::begin () const inline
Definition at line 209 of file vector.h.
{ return &mData[0]; }
capacity()
template<typename T , size_t N> size_t fl::FixedVector< T, N >::capacity () const inline constexpr
Definition at line 72 of file vector.h.
{
        return N;
    }
clear()
template<typename T , size_t N> void fl::FixedVector< T, N >::clear () inline
Definition at line 108 of file vector.h.
                 {
        while (current_size > 0) {
            pop_back();
        }
    }
References fl::FixedVector< T, N >::current_size, and fl::FixedVector< T, N >::pop_back().
Referenced by fl::FixedVector< T, N >::~FixedVector(), fl::FixedVector< T, N >::assign(), fl::FixedVector< T, N >::assign(), fl::FixedMap< Key, Value, N >::clear(), and fl::FixedSet< Key, N >::clear().
data() [1/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::data () inline
Definition at line 178 of file vector.h.
                    {
        return begin();
    }
References fl::FixedVector< T, N >::begin().
data() [2/2]
template<typename T , size_t N> const_iterator fl::FixedVector< T, N >::data () const inline
Definition at line 182 of file vector.h.
{
        return begin();
    }
References fl::FixedVector< T, N >::begin().
empty()
template<typename T , size_t N> bool fl::FixedVector< T, N >::empty () const inline constexpr
Definition at line 67 of file vector.h.
{
        return current_size == 0;
    }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedMap< Key, Value, N >::empty(), and fl::FixedSet< Key, N >::empty().
end() [1/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::end () inline
Definition at line 210 of file vector.h.
{ return &mData[current_size]; }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedVector< T, N >::assign(), fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::end(), fl::FixedSet< Key, N >::end(), fl::FixedSet< Key, N >::end(), fl::FixedVector< T, N >::erase(), fl::FixedVector< T, N >::erase(), fl::FixedVector< T, N >::find(), fl::FixedVector< T, N >::find(), fl::FixedVector< T, N >::find_if(), fl::FixedVector< T, N >::has(), fl::FixedMap< Key, Value, N >::insert(), and fl::FixedVector< T, N >::insert().
end() [2/2]
template<typename T , size_t N> const_iterator fl::FixedVector< T, N >::end () const inline
Definition at line 211 of file vector.h.
{ return &mData[current_size]; }
References fl::FixedVector< T, N >::current_size.
erase() [1/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::erase (const T & value) inline
Definition at line 128 of file vector.h.
{
        iterator it = find(value);
        if (it != end()) {
            erase(it);
        }
        return it;
    }
References fl::FixedVector< T, N >::end(), fl::FixedVector< T, N >::erase(), and fl::FixedVector< T, N >::find().
erase() [2/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::erase (iterator pos) inline
Definition at line 115 of file vector.h.
{
        if (pos != end()) {
            pos->~T();
            // shift all elements to the left
            for (iterator p = pos; p != end() - 1; ++p) {
                new (p) T(*(p + 1)); // Use copy constructor instead of std::move
                (p + 1)->~T();
            }
            --current_size;
        }
        return pos;
    }
References fl::FixedVector< T, N >::current_size, fl::FixedVector< T, N >::end(), p, and pos.
Referenced by fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::erase(), and fl::FixedVector< T, N >::erase().
find() [1/2]
template<typename T , size_t N> iterator fl::FixedVector< T, N >::find (const T & value) inline
Definition at line 136 of file vector.h.
{
        for (iterator it = begin(); it != end(); ++it) {
            if (*it == value) {
                return it;
            }
        }
        return end();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedVector< T, N >::end().
Referenced by fl::FixedVector< T, N >::erase(), and fl::FixedVector< T, N >::has().
find() [2/2]
template<typename T , size_t N> const_iterator fl::FixedVector< T, N >::find (const T & value) const inline
Definition at line 169 of file vector.h.
{
        for (const_iterator it = begin(); it != end(); ++it) {
            if (*it == value) {
                return it;
            }
        }
        return end();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedVector< T, N >::end().
find_if()
template<typename T , size_t N> template<typename Predicate > iterator fl::FixedVector< T, N >::find_if (Predicate pred) inline
Definition at line 146 of file vector.h.
{
        for (iterator it = begin(); it != end(); ++it) {
            if (pred(*it)) {
                return it;
            }
        }
        return end();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedVector< T, N >::end().
front() [1/2]
template<typename T , size_t N> T & fl::FixedVector< T, N >::front () inline
Definition at line 191 of file vector.h.
               {
        return mData[0];
    }
Referenced by fl::FixedSet< Key, N >::front().
front() [2/2]
template<typename T , size_t N> const T & fl::FixedVector< T, N >::front () const inline
Definition at line 195 of file vector.h.
{
        return mData[0];
    }
has()
template<typename T , size_t N> bool fl::FixedVector< T, N >::has (const T & value) const inline
Definition at line 186 of file vector.h.
{
        return find(value) != end();
    }
References fl::FixedVector< T, N >::end(), and fl::FixedVector< T, N >::find().
insert()
template<typename T , size_t N> bool fl::FixedVector< T, N >::insert (iterator pos, const T & value) inline
Definition at line 155 of file vector.h.
{
        if (current_size < N) {
            // shift all elements to the right
            for (iterator p = end(); p != pos; --p) {
                new (p) T(*(p - 1)); // Use copy constructor instead of std::move
                (p - 1)->~T();
            }
            new (pos) T(value);
            ++current_size;
            return true;
        }
        return false;
    }
References fl::FixedVector< T, N >::current_size, fl::FixedVector< T, N >::end(), p, and pos.
operator[]() [1/2]
template<typename T , size_t N> T & fl::FixedVector< T, N >::operator[] (size_t index) inline
Definition at line 49 of file vector.h.
{
        return mData[index];
    }
operator[]() [2/2]
template<typename T , size_t N> const T & fl::FixedVector< T, N >::operator[] (size_t index) const inline
Definition at line 54 of file vector.h.
{
        if (index >= current_size) {
            const T* out = nullptr;
            return *out;  // Cause a nullptr dereference
        }
        return mData[index];
    }
References fl::FixedVector< T, N >::current_size.
pop_back()
template<typename T , size_t N> void fl::FixedVector< T, N >::pop_back () inline
Definition at line 100 of file vector.h.
                    {
        if (current_size > 0) {
            --current_size;
            mData[current_size].~T();
        }
    }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedVector< T, N >::clear().
push_back()
template<typename T , size_t N> void fl::FixedVector< T, N >::push_back (const T & value) inline
Definition at line 77 of file vector.h.
{
        if (current_size < N) {
            void* mem = &mData[current_size];
            new (mem) T(value);
            ++current_size;
        }
    }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedVector< T, N >::assign(), fl::FixedVector< T, N >::assign(), fl::FixedMap< Key, Value, N >::insert(), fl::FixedSet< Key, N >::insert(), and fl::FixedMap< Key, Value, N >::operator[]().
size()
template<typename T , size_t N> size_t fl::FixedVector< T, N >::size () const inline constexpr
Definition at line 63 of file vector.h.
{
        return current_size;
    }
References fl::FixedVector< T, N >::current_size.
Referenced by fl::FixedMap< Key, Value, N >::insert(), fl::FixedSet< Key, N >::insert(), fl::FixedMap< Key, Value, N >::prev(), fl::FixedSet< Key, N >::prev(), fl::FixedMap< Key, Value, N >::size(), and fl::FixedSet< Key, N >::size().
Member Data Documentation
[union]
union { ... } fl::FixedVector< T, N >
current_size
template<typename T , size_t N> size_t fl::FixedVector< T, N >::current_size = 0 private
Definition at line 25 of file vector.h.
Referenced by fl::FixedVector< T, N >::back(), fl::FixedVector< T, N >::back(), fl::FixedVector< T, N >::clear(), fl::FixedVector< T, N >::empty(), fl::FixedVector< T, N >::end(), fl::FixedVector< T, N >::end(), fl::FixedVector< T, N >::erase(), fl::FixedVector< T, N >::insert(), fl::FixedVector< T, N >::operator[](), fl::FixedVector< T, N >::pop_back(), fl::FixedVector< T, N >::push_back(), and fl::FixedVector< T, N >::size().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/vector.h