FastLED: /home/runner/work/FastLED/FastLED/examples/Chromancer/Chromancer.ino File Reference
Chromancer.ino File Reference
#include "mapping.h"
#include "net.h"
#include "ripple.h"
#include <FastLED.h>
#include "detail.h"
#include "fl/screenmap.h"
#include "fl/math_macros.h"
#include "fl/json.h"
#include "fl/ui.h"
#include "fl/map.h"
#include "screenmap.json.h"
#include "fl/str.h"
Macros
#define autoPulseChangeTime 30000
#define autoPulseTimeout 5000
#define cubePulsesEnabled true
#define gyroAlpha 0.9
#define gyroThreshold 300
#define heartbeatDelta 300
#define heartbeatLockout 500
#define highTemperature 37.0
#define lowTemperature 33.0
#define numberOfRipples 30
#define randomPulsesEnabled true
#define randomPulseTime 2000
#define simulatedEdaBaseTime 1000
#define simulatedEdaVariance 10000
#define simulatedHeartbeatBaseTime 600
#define simulatedHeartbeatVariance 200
Enumerations
enum { BlackStrip = 0 , GreenStrip = 1 , RedStrip = 2 , BlueStrip = 3 }
Functions
UIDescription description ("Take 6 seconds to boot up. Chromancer is a wall-mounted hexagonal LED display that originally reacted to biometric data from an EmotiBit sensor. It visualizes your heartbeat, skin temperature, and movement in real-time. Chromancer also has a few built-in effects that can be triggered with the push of a button. Enjoy!")
bool isNodeOnBorder (byte node)
void loop ()
void setup ()
Variables
UICheckbox allWhite ("All White", false)
byte currentAutoPulseType = 255
float gyroX
float gyroY
float gyroZ
float highestIrReading
unsigned long lastAutoPulseChange
byte lastAutoPulseNode = 255
unsigned long lastHeartbeat
float lastIrReading
float lastKnownTemperature
unsigned long lastRandomPulse
byte ledColors [40][14][3]
CRGB * leds [] = {leds0, leds1, leds2, leds3}
CRGB leds0 [lengths[BlackStrip]] = {}
CRGB leds1 [lengths[GreenStrip]] = {}
CRGB leds2 [lengths[RedStrip]] = {}
CRGB leds3 [lengths[BlueStrip]] = {}
constexpr int lengths []
unsigned long nextSimulatedEda
unsigned long nextSimulatedHeartbeat
byte numberOfAutoPulseTypes
Ripple ripples [numberOfRipples]
UICheckbox simulatedBiometricsEnabled ("Simulated Biometrics", true)
UIButton simulatedHeartbeat ("Simulated Heartbeat")
UISlider sliderDecay ("decay",.97f,.8, 1.0,.01)
UICheckbox starburstPulsesEnabled ("Starburst Pulses", true)
UITitle title ("Chromancer")
UIButton triggerBorderWave ("Border Wave")
UIButton triggerRainbowCube ("Rainbow Cube")
UIButton triggerSpiral ("Spiral Wave")
UIButton triggerStarburst ("Trigger Starburst")
bool wasBorderWaveClicked = false
bool wasHeartbeatClicked = false
bool wasRainbowCubeClicked = false
bool wasSpiralClicked = false
bool wasStarburstClicked = false
Macro Definition Documentation
autoPulseChangeTime
#define autoPulseChangeTime 30000
Definition at line 130 of file Chromancer.ino.
Referenced by loop().
autoPulseTimeout
#define autoPulseTimeout 5000
Definition at line 120 of file Chromancer.ino.
#define autoPulseTimeout                                                       \
    5000 // If no heartbeat is received in this many ms, begin firing
Referenced by loop().
cubePulsesEnabled
#define cubePulsesEnabled true
Definition at line 116 of file Chromancer.ino.
Referenced by loop().
gyroAlpha
#define gyroAlpha 0.9
Definition at line 108 of file Chromancer.ino.
Referenced by net_init().
gyroThreshold
#define gyroThreshold 300
Definition at line 109 of file Chromancer.ino.
#define gyroThreshold                                                          \
    300 // Minimum angular velocity total (X+Y+Z) that disqualifies readings
heartbeatDelta
#define heartbeatDelta 300
Definition at line 95 of file Chromancer.ino.
Referenced by net_init().
heartbeatLockout
#define heartbeatLockout 500
Definition at line 93 of file Chromancer.ino.
#define heartbeatLockout                                                       \
    500 // Heartbeats that happen within this many milliseconds are ignored
Referenced by net_init().
highTemperature
#define highTemperature 37.0
Definition at line 99 of file Chromancer.ino.
Referenced by net_init().
lowTemperature
#define lowTemperature 33.0
Definition at line 98 of file Chromancer.ino.
Referenced by net_init().
numberOfRipples
#define numberOfRipples 30
Definition at line 78 of file Chromancer.ino.
Referenced by loop().
randomPulsesEnabled
#define randomPulsesEnabled true
Definition at line 115 of file Chromancer.ino.
Referenced by loop().
randomPulseTime
#define randomPulseTime 2000
Definition at line 123 of file Chromancer.ino.
Referenced by loop().
simulatedEdaBaseTime
#define simulatedEdaBaseTime 1000
Definition at line 137 of file Chromancer.ino.
Referenced by loop().
simulatedEdaVariance
#define simulatedEdaVariance 10000
Definition at line 138 of file Chromancer.ino.
Referenced by loop().
simulatedHeartbeatBaseTime
#define simulatedHeartbeatBaseTime 600
Definition at line 133 of file Chromancer.ino.
#define simulatedHeartbeatBaseTime                                             \
    600 // Fire a simulated heartbeat pulse after at least this many ms
Referenced by loop().
simulatedHeartbeatVariance
#define simulatedHeartbeatVariance 200
Definition at line 135 of file Chromancer.ino.
#define simulatedHeartbeatVariance                                             \
    200                           // Add random jitter to simulated heartbeat
Referenced by loop().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
BlackStrip
GreenStrip
RedStrip
BlueStrip
Definition at line 37 of file Chromancer.ino.
     {
    BlackStrip = 0,
    GreenStrip = 1,
    RedStrip = 2,
    BlueStrip = 3,
};
Function Documentation
description()
UIDescription description ("Take 6 seconds to boot up. Chromancer is a wall-mounted hexagonal LED display that originally reacted to biometric data from an EmotiBit sensor. It visualizes your heartbeat, skin temperature, and movement in real-time. Chromancer also has a few built-in effects that can be triggered with the push of a button. Enjoy!")
isNodeOnBorder()
bool isNodeOnBorder (byte node)
Definition at line 143 of file Chromancer.ino.
{
    for (int i = 0; i < numberOfBorderNodes; i++) {
        if (node == borderNodes[i]) {
            return true;
        }
    }
    return false;
}
References borderNodes, and numberOfBorderNodes.
Referenced by loop().
loop()
void loop ()
Definition at line 214 of file Chromancer.ino.
            {
    unsigned long benchmark = millis();
    net_loop();
    // Fade all dots to create trails
    for (int strip = 0; strip < 40; strip++) {
        for (int led = 0; led < 14; led++) {
            for (int i = 0; i < 3; i++) {
                ledColors[strip][led][i] *= sliderDecay.value();
            }
        }
    }
    for (int i = 0; i < numberOfRipples; i++) {
        ripples[i].advance(ledColors);
    }
    for (int segment = 0; segment < 40; segment++) {
        for (int fromBottom = 0; fromBottom < 14; fromBottom++) {
            int strip = ledAssignments[segment][0];
            int led = round(fmap(fromBottom, 0, 13, ledAssignments[segment][2],
                                 ledAssignments[segment][1]));
            leds[strip][led] = CRGB(ledColors[segment][fromBottom][0],
                                    ledColors[segment][fromBottom][1],
                                    ledColors[segment][fromBottom][2]);
        }
    }
    if (allWhite) {
        // for all strips
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < lengths[i]; j++) {
                leds[i][j] = CRGB::White;
            }
        }
    }
    FastLED.show();
    // Check if buttons were clicked
    wasHeartbeatClicked = bool(simulatedHeartbeat);
    wasStarburstClicked = bool(triggerStarburst);
    wasRainbowCubeClicked = bool(triggerRainbowCube);
    wasBorderWaveClicked = bool(triggerBorderWave);
    wasSpiralClicked = bool(triggerSpiral);
    if (wasSpiralClicked) {
        // Trigger spiral wave effect from center
        unsigned int baseColor = random(0xFFFF);
        byte centerNode = 15; // Center node
        // Create 6 ripples in a spiral pattern
        for (int i = 0; i < 6; i++) {
            if (nodeConnections[centerNode][i] >= 0) {
                for (int j = 0; j < numberOfRipples; j++) {
                    if (ripples[j].state == dead) {
                        ripples[j].start(
                            centerNode, i,
                            Adafruit_DotStar_ColorHSV(
                                baseColor + (0xFFFF / 6) * i, 255, 255),
                            0.3 + (i * 0.1), // Varying speeds creates spiral effect
                            2000,
                            i % 2 ? alwaysTurnsLeft : alwaysTurnsRight); // Alternating turn directions
                        break;
                    }
                }
            }
        }
        lastHeartbeat = millis();
    }
    if (wasBorderWaveClicked) {
        // Trigger immediate border wave effect
        unsigned int baseColor = random(0xFFFF);
        // Start ripples from each border node in sequence
        for (int i = 0; i < numberOfBorderNodes; i++) {
            byte node = borderNodes[i];
            // Find an inward direction
            for (int dir = 0; dir < 6; dir++) {
                if (nodeConnections[node][dir] >= 0 &&
                    !isNodeOnBorder(nodeConnections[node][dir])) {
                    for (int j = 0; j < numberOfRipples; j++) {
                        if (ripples[j].state == dead) {
                            ripples[j].start(
                                node, dir,
                                Adafruit_DotStar_ColorHSV(
                                    baseColor + (0xFFFF / numberOfBorderNodes) * i,
                                    255, 255),
                                .4, 2000, 0);
                            break;
                        }
                    }
                    break;
                }
            }
        }
        lastHeartbeat = millis();
    }
    if (wasRainbowCubeClicked) {
        // Trigger immediate rainbow cube effect
        int node = cubeNodes[random(numberOfCubeNodes)];
        unsigned int baseColor = random(0xFFFF);
        byte behavior = random(2) ? alwaysTurnsLeft : alwaysTurnsRight;
        for (int i = 0; i < 6; i++) {
            if (nodeConnections[node][i] >= 0) {
                for (int j = 0; j < numberOfRipples; j++) {
                    if (ripples[j].state == dead) {
                        ripples[j].start(
                            node, i,
                            Adafruit_DotStar_ColorHSV(
                                baseColor + (0xFFFF / 6) * i, 255, 255),
                            .5, 2000, behavior);
                        break;
                    }
                }
            }
        }
        lastHeartbeat = millis();
    }
    if (wasStarburstClicked) {
        // Trigger immediate starburst effect
        unsigned int baseColor = random(0xFFFF);
        byte behavior = random(2) ? alwaysTurnsLeft : alwaysTurnsRight;
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < numberOfRipples; j++) {
                if (ripples[j].state == dead) {
                    ripples[j].start(
                        starburstNode, i,
                        Adafruit_DotStar_ColorHSV(
                            baseColor + (0xFFFF / 6) * i, 255, 255),
                        .65, 1500, behavior);
                    break;
                }
            }
        }
        lastHeartbeat = millis();
    }
    if (wasHeartbeatClicked) {
        // Trigger immediate heartbeat effect
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < numberOfRipples; j++) {
                if (ripples[j].state == dead) {
                    ripples[j].start(15, i, 0xEE1111,
                                   float(random(100)) / 100.0 * .1 + .4, 1000, 0);
                    break;
                }
            }
        }
        lastHeartbeat = millis();
    }
    if (millis() - lastHeartbeat >= autoPulseTimeout) {
        // When biometric data is unavailable, visualize at random
        if (numberOfAutoPulseTypes &&
            millis() - lastRandomPulse >= randomPulseTime) {
            unsigned int baseColor = random(0xFFFF);
            if (currentAutoPulseType == 255 ||
                (numberOfAutoPulseTypes > 1 &&
                 millis() - lastAutoPulseChange >= autoPulseChangeTime)) {
                byte possiblePulse = 255;
                while (true) {
                    possiblePulse = random(3);
                    if (possiblePulse == currentAutoPulseType)
                        continue;
                    switch (possiblePulse) {
                    case 0:
                        if (!randomPulsesEnabled)
                            continue;
                        break;
                    case 1:
                        if (!cubePulsesEnabled)
                            continue;
                        break;
                    case 2:
                        if (!starburstPulsesEnabled)
                            continue;
                        break;
                    default:
                        continue;
                    }
                    currentAutoPulseType = possiblePulse;
                    lastAutoPulseChange = millis();
                    break;
                }
            }
            switch (currentAutoPulseType) {
            case 0: {
                int node = 0;
                bool foundStartingNode = false;
                while (!foundStartingNode) {
                    node = random(25);
                    foundStartingNode = true;
                    for (int i = 0; i < numberOfBorderNodes; i++) {
                        // Don't fire a pulse on one of the outer nodes - it
                        // looks boring
                        if (node == borderNodes[i])
                            foundStartingNode = false;
                    }
                    if (node == lastAutoPulseNode)
                        foundStartingNode = false;
                }
                lastAutoPulseNode = node;
                for (int i = 0; i < 6; i++) {
                    if (nodeConnections[node][i] >= 0) {
                        for (int j = 0; j < numberOfRipples; j++) {
                            if (ripples[j].state == dead) {
                                ripples[j].start(
                                    node, i,
                                    //                      strip0.ColorHSV(baseColor
                                    //                      + (0xFFFF / 6) * i,
                                    //                      255, 255),
                                    Adafruit_DotStar_ColorHSV(baseColor, 255,
                                                              255),
                                    float(random(100)) / 100.0 * .2 + .5, 3000,
                                    1);
                                break;
                            }
                        }
                    }
                }
                break;
            }
            case 1: {
                int node = cubeNodes[random(numberOfCubeNodes)];
                while (node == lastAutoPulseNode)
                    node = cubeNodes[random(numberOfCubeNodes)];
                lastAutoPulseNode = node;
                byte behavior = random(2) ? alwaysTurnsLeft : alwaysTurnsRight;
                for (int i = 0; i < 6; i++) {
                    if (nodeConnections[node][i] >= 0) {
                        for (int j = 0; j < numberOfRipples; j++) {
                            if (ripples[j].state == dead) {
                                ripples[j].start(
                                    node, i,
                                    //                      strip0.ColorHSV(baseColor
                                    //                      + (0xFFFF / 6) * i,
                                    //                      255, 255),
                                    Adafruit_DotStar_ColorHSV(baseColor, 255,
                                                              255),
                                    .5, 2000, behavior);
                                break;
                            }
                        }
                    }
                }
                break;
            }
            case 2: {
                byte behavior = random(2) ? alwaysTurnsLeft : alwaysTurnsRight;
                lastAutoPulseNode = starburstNode;
                for (int i = 0; i < 6; i++) {
                    for (int j = 0; j < numberOfRipples; j++) {
                        if (ripples[j].state == dead) {
                            ripples[j].start(
                                starburstNode, i,
                                Adafruit_DotStar_ColorHSV(
                                    baseColor + (0xFFFF / 6) * i, 255, 255),
                                .65, 1500, behavior);
                            break;
                        }
                    }
                }
                break;
            }
            default:
                break;
            }
            lastRandomPulse = millis();
        }
        if (simulatedBiometricsEnabled) {
            // Simulated heartbeat
            if (millis() >= nextSimulatedHeartbeat) {
                for (int i = 0; i < 6; i++) {
                    for (int j = 0; j < numberOfRipples; j++) {
                        if (ripples[j].state == dead) {
                            ripples[j].start(
                                15, i, 0xEE1111,
                                float(random(100)) / 100.0 * .1 + .4, 1000, 0);
                            break;
                        }
                    }
                }
                nextSimulatedHeartbeat = millis() + simulatedHeartbeatBaseTime +
                                         random(simulatedHeartbeatVariance);
            }
            // Simulated EDA ripples
            if (millis() >= nextSimulatedEda) {
                for (int i = 0; i < 10; i++) {
                    for (int j = 0; j < numberOfRipples; j++) {
                        if (ripples[j].state == dead) {
                            byte targetNode =
                                borderNodes[random(numberOfBorderNodes)];
                            byte direction = 255;
                            while (direction == 255) {
                                direction = random(6);
                                if (nodeConnections[targetNode][direction] < 0)
                                    direction = 255;
                            }
                            ripples[j].start(
                                targetNode, direction, 0x1111EE,
                                float(random(100)) / 100.0 * .5 + 2, 300, 2);
                            break;
                        }
                    }
                }
                nextSimulatedEda = millis() + simulatedEdaBaseTime +
                                   random(simulatedEdaVariance);
            }
        }
    }
    //  Serial.print("Benchmark: ");
    //  Serial.println(millis() - benchmark);
}
References Adafruit_DotStar_ColorHSV(), Ripple::advance(), allWhite, alwaysTurnsLeft, alwaysTurnsRight, autoPulseChangeTime, autoPulseTimeout, borderNodes, cubeNodes, cubePulsesEnabled, currentAutoPulseType, dead, FastLED, fmap(), isNodeOnBorder(), lastAutoPulseChange, lastAutoPulseNode, lastHeartbeat, lastRandomPulse, ledAssignments, ledColors, leds, lengths, net_loop(), nextSimulatedEda, nextSimulatedHeartbeat, nodeConnections, numberOfAutoPulseTypes, numberOfBorderNodes, numberOfCubeNodes, numberOfRipples, randomPulsesEnabled, randomPulseTime, ripples, round, CFastLED::show(), simulatedBiometricsEnabled, simulatedEdaBaseTime, simulatedEdaVariance, simulatedHeartbeat, simulatedHeartbeatBaseTime, simulatedHeartbeatVariance, sliderDecay, starburstNode, starburstPulsesEnabled, Ripple::start(), triggerBorderWave, triggerRainbowCube, triggerSpiral, triggerStarburst, fl::UISlider::value(), wasBorderWaveClicked, wasHeartbeatClicked, wasRainbowCubeClicked, wasSpiralClicked, wasStarburstClicked, and CRGB::White.
setup()
void setup ()
Definition at line 167 of file Chromancer.ino.
             {
    Serial.begin(115200);
    Serial.println("*** LET'S GOOOOO ***");
    Serial.println("JSON SCREENMAP");
    Serial.println(JSON_SCREEN_MAP);
    FixedMap<Str, ScreenMap, 16> segmentMaps;
    ScreenMap::ParseJson(JSON_SCREEN_MAP, &segmentMaps);
    printf("Parsed %d segment maps\n", int(segmentMaps.size()));
    for (auto kv : segmentMaps) {
        Serial.print(kv.first.c_str());
        Serial.print(" ");
        Serial.println(kv.second.getLength());
    }
    // ScreenMap screenmaps[4];
    ScreenMap red, black, green, blue;
    bool ok = true;
    ok = segmentMaps.get("red_segment", &red) && ok;
    ok = segmentMaps.get("back_segment", &black) && ok;
    ok = segmentMaps.get("green_segment", &green) && ok;
    ok = segmentMaps.get("blue_segment", &blue) && ok;
    if (!ok) {
        Serial.println("Failed to get all segment maps");
        return;
    }
    CRGB* red_leds = leds[RedStrip];
    CRGB* black_leds = leds[BlackStrip];
    CRGB* green_leds = leds[GreenStrip];
    CRGB* blue_leds = leds[BlueStrip];
    FastLED.addLeds<WS2812, 2>(black_leds, lengths[BlackStrip]).setScreenMap(black);
    FastLED.addLeds<WS2812, 3>(green_leds, lengths[GreenStrip]).setScreenMap(green);
    FastLED.addLeds<WS2812, 1>(red_leds, lengths[RedStrip]).setScreenMap(red);
    FastLED.addLeds<WS2812, 4>(blue_leds, lengths[BlueStrip]).setScreenMap(blue);
    FastLED.show();
    net_init();
}
References CFastLED::addLeds(), BlackStrip, BlueStrip, FastLED, fl::FixedMap< Key, Value, N >::get(), GreenStrip, JSON_SCREEN_MAP, leds, lengths, net_init(), fl::ScreenMap::ParseJson(), RedStrip, CFastLED::show(), and fl::FixedMap< Key, Value, N >::size().
Variable Documentation
allWhite
UICheckbox allWhite("All White", false) ("All White" , false)
Referenced by loop().
currentAutoPulseType
byte currentAutoPulseType = 255
Definition at line 129 of file Chromancer.ino.
Referenced by loop().
gyroX
float gyroX
Definition at line 111 of file Chromancer.ino.
Referenced by net_init().
gyroY
float gyroY
Definition at line 111 of file Chromancer.ino.
Referenced by net_init().
gyroZ
float gyroZ
Definition at line 111 of file Chromancer.ino.
Referenced by net_init().
highestIrReading
float highestIrReading
Definition at line 90 of file Chromancer.ino.
Referenced by net_init().
lastAutoPulseChange
unsigned long lastAutoPulseChange
Definition at line 131 of file Chromancer.ino.
Referenced by loop().
lastAutoPulseNode
byte lastAutoPulseNode = 255
Definition at line 125 of file Chromancer.ino.
Referenced by loop().
lastHeartbeat
unsigned long lastHeartbeat
Definition at line 92 of file Chromancer.ino.
Referenced by loop(), and net_init().
lastIrReading
float lastIrReading
Definition at line 89 of file Chromancer.ino.
Referenced by net_init().
lastKnownTemperature
float lastKnownTemperature
Initial value:
=
    (lowTemperature + highTemperature) /
    2.0
Definition at line 100 of file Chromancer.ino.
Referenced by net_init().
lastRandomPulse
unsigned long lastRandomPulse
Definition at line 124 of file Chromancer.ino.
Referenced by loop().
ledColors
byte ledColors[40][14][3]
Definition at line 69 of file Chromancer.ino.
Referenced by Ripple::advance(), loop(), and Ripple::renderLed().
leds
CRGB* leds[] = {leds0, leds1, leds2, leds3}
Definition at line 66 of file Chromancer.ino.
{leds0, leds1, leds2, leds3};
Referenced by loop(), and setup().
leds0
CRGB leds0[lengths[BlackStrip]] = {}
Definition at line 62 of file Chromancer.ino.
{};
leds1
CRGB leds1[lengths[GreenStrip]] = {}
Definition at line 63 of file Chromancer.ino.
{};
leds2
CRGB leds2[lengths[RedStrip]] = {}
Definition at line 64 of file Chromancer.ino.
{}; // Red
leds3
CRGB leds3[lengths[BlueStrip]] = {}
Definition at line 65 of file Chromancer.ino.
{};
lengths
int lengths[] constexpr
Initial value:
= {
  154,
  168,
  84,
  154
}
Definition at line 47 of file Chromancer.ino.
{
  154, // Black strip
  168, // Green strip
  84,  // Red strip
  154  // Blue strip
};
Referenced by loop(), and setup().
nextSimulatedEda
unsigned long nextSimulatedEda
Definition at line 140 of file Chromancer.ino.
Referenced by loop().
nextSimulatedHeartbeat
unsigned long nextSimulatedHeartbeat
Definition at line 139 of file Chromancer.ino.
Referenced by loop().
numberOfAutoPulseTypes
byte numberOfAutoPulseTypes
Initial value:
=
    randomPulsesEnabled + cubePulsesEnabled + int(starburstPulsesEnabled)
Definition at line 127 of file Chromancer.ino.
Referenced by loop().
ripples
Ripple ripples[numberOfRipples]
Initial value:
= {
    Ripple(0),  Ripple(1),  Ripple(2),  Ripple(3),  Ripple(4),  Ripple(5),
    Ripple(6),  Ripple(7),  Ripple(8),  Ripple(9),  Ripple(10), Ripple(11),
    Ripple(12), Ripple(13), Ripple(14), Ripple(15), Ripple(16), Ripple(17),
    Ripple(18), Ripple(19), Ripple(20), Ripple(21), Ripple(22), Ripple(23),
    Ripple(24), Ripple(25), Ripple(26), Ripple(27), Ripple(28), Ripple(29),
}
Definition at line 79 of file Chromancer.ino.
{
    Ripple(0),  Ripple(1),  Ripple(2),  Ripple(3),  Ripple(4),  Ripple(5),
    Ripple(6),  Ripple(7),  Ripple(8),  Ripple(9),  Ripple(10), Ripple(11),
    Ripple(12), Ripple(13), Ripple(14), Ripple(15), Ripple(16), Ripple(17),
    Ripple(18), Ripple(19), Ripple(20), Ripple(21), Ripple(22), Ripple(23),
    Ripple(24), Ripple(25), Ripple(26), Ripple(27), Ripple(28), Ripple(29),
};
Referenced by loop(), and net_init().
simulatedBiometricsEnabled
UICheckbox simulatedBiometricsEnabled("Simulated Biometrics", true) ("Simulated Biometrics" , true)
Referenced by loop().
simulatedHeartbeat
UIButton simulatedHeartbeat("Simulated Heartbeat") ("Simulated Heartbeat")
Referenced by loop().
sliderDecay
UISlider sliderDecay("decay",.97f,.8, 1.0,.01) ("decay" , . 97f, . 8, 1. 0, . 01)
Referenced by loop().
starburstPulsesEnabled
UICheckbox starburstPulsesEnabled("Starburst Pulses", true) ("Starburst Pulses" , true)
Referenced by loop().
title
UITitle title("Chromancer") ("Chromancer")
triggerBorderWave
UIButton triggerBorderWave("Border Wave") ("Border Wave")
Referenced by loop().
triggerRainbowCube
UIButton triggerRainbowCube("Rainbow Cube") ("Rainbow Cube")
Referenced by loop().
triggerSpiral
UIButton triggerSpiral("Spiral Wave") ("Spiral Wave")
Referenced by loop().
triggerStarburst
UIButton triggerStarburst("Trigger Starburst") ("Trigger Starburst")
Referenced by loop().
wasBorderWaveClicked
bool wasBorderWaveClicked = false
Definition at line 164 of file Chromancer.ino.
Referenced by loop().
wasHeartbeatClicked
bool wasHeartbeatClicked = false
Definition at line 161 of file Chromancer.ino.
Referenced by loop().
wasRainbowCubeClicked
bool wasRainbowCubeClicked = false
Definition at line 163 of file Chromancer.ino.
Referenced by loop().
wasSpiralClicked
bool wasSpiralClicked = false
Definition at line 165 of file Chromancer.ino.
Referenced by loop().
wasStarburstClicked
bool wasStarburstClicked = false
Definition at line 162 of file Chromancer.ino.
Referenced by loop().