FastLED: fl::Pride2015 Class Reference
fl::Pride2015 Class Reference
Detailed Description
Definition at line 21 of file pride2015.h.
#include <pride2015.h>
Public Member Functions
Pride2015 (uint16_t num_leds)
void draw (Fx::DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Attributes
uint16_t mHue16 = 0
uint16_t mLastMillis = 0
uint16_t mPseudotime = 0
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
Pride2015()
fl::Pride2015::Pride2015 (uint16_t num_leds) inline
Definition at line 23 of file pride2015.h.
: Fx1d(num_leds) {}
Member Function Documentation
draw()
void fl::Pride2015::draw (Fx::DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 36 of file pride2015.h.
{
    if (ctx.leds == nullptr || mNumLeds == 0) {
        return;
    }
    uint8_t sat8 = beatsin88(87, 220, 250);
    uint8_t brightdepth = beatsin88(341, 96, 224);
    uint16_t brightnessthetainc16 = beatsin88(203, (25 * 256), (40 * 256));
    uint8_t msmultiplier = beatsin88(147, 23, 60);
    uint16_t hue16 = mHue16;
    uint16_t hueinc16 = beatsin88(113, 1, 3000);
    uint16_t ms = millis();
    uint16_t deltams = ms - mLastMillis;
    mLastMillis = ms;
    mPseudotime += deltams * msmultiplier;
    mHue16 += deltams * beatsin88(400, 5, 9);
    uint16_t brightnesstheta16 = mPseudotime;
    // set master brightness control
    for (uint16_t i = 0; i < mNumLeds; i++) {
        hue16 += hueinc16;
        uint8_t hue8 = hue16 / 256;
        brightnesstheta16 += brightnessthetainc16;
        uint16_t b16 = sin16(brightnesstheta16) + 32768;
        uint16_t bri16 = (uint32_t)((uint32_t)b16 * (uint32_t)b16) / 65536;
        uint8_t bri8 = (uint32_t)(((uint32_t)bri16) * brightdepth) / 65536;
        bri8 += (255 - brightdepth);
        CRGB newcolor = CHSV(hue8, sat8, bri8);
        uint16_t pixelnumber = (mNumLeds - 1) - i;
        nblend(ctx.leds[pixelnumber], newcolor, 64);
    }
}
References beatsin88(), fl::_DrawContext::leds, mHue16, mLastMillis, fl::Fx::mNumLeds, mPseudotime, nblend(), and sin16.
Referenced by loop().
fxName()
fl::Str fl::Pride2015::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 26 of file pride2015.h.
{ return "Pride2015"; }
Member Data Documentation
mHue16
uint16_t fl::Pride2015::mHue16 = 0 private
Definition at line 31 of file pride2015.h.
Referenced by draw().
mLastMillis
uint16_t fl::Pride2015::mLastMillis = 0 private
Definition at line 30 of file pride2015.h.
Referenced by draw().
mPseudotime
uint16_t fl::Pride2015::mPseudotime = 0 private
Definition at line 29 of file pride2015.h.
Referenced by draw().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/1d/pride2015.h