FastLED: Clocked Chipsets
Clocked Chipsets
LED Chipset Controllers
Detailed Description
Nominally SPI based, these chipsets have a data and a clock line.
Classes
class APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >
APA102 controller class.
class APA102ControllerHD< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
APA102 high definition controller class.
class HD107Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
HD107 is just the APA102 with a default 40Mhz clock rate.
class HD107HDController< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
HD107HD is just the APA102HD with a default 40Mhz clock rate.
class LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
LPD6803 controller class (LPD1101).
class LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
LPD8806 controller class.
class LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806_ADJUST
class P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
P9813 controller class.
class SK9822Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
SK9822 controller class.
class SK9822ControllerHD< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
SK9822 controller class.
class SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
SM16716 controller class.
class WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
WS2801 controller class.
class WS2803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >
WS2803 controller class.
Class Documentation
APA102Controller
class APA102Controller
Public Member Functions
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Member Functions
void endBoundary (int nLeds)
void showPixelsDefault (PixelController< RGB_ORDER > &pixels)
void showPixelsGammaBitShift (PixelController< RGB_ORDER > &pixels)
void startBoundary ()
FASTLED_FORCE_INLINE void write2Bytes (uint8_t b1, uint8_t b2)
FASTLED_FORCE_INLINE void writeLed (uint8_t brightness, uint8_t b0, uint8_t b1, uint8_t b2)
Static Private Member Functions
static void getGlobalBrightnessAndScalingFactors (PixelController< RGB_ORDER > &pixels, uint8_t *out_s0, uint8_t *out_s1, uint8_t *out_s2, uint8_t *out_brightness)
Private Attributes
SPI mSPI
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::SPI private
Definition at line 374 of file chipsets.h.
Constructor & Destructor Documentation
APA102Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::APA102Controller () inline
Definition at line 420 of file chipsets.h.
{}
Member Function Documentation
endBoundary()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::endBoundary (int nLeds) inline private
Definition at line 381 of file chipsets.h.
{
        int nDWords = (nLeds/32);
        const uint8_t b0 = uint8_t(END_FRAME >> 24 & 0x000000ff);
        const uint8_t b1 = uint8_t(END_FRAME >> 16 & 0x000000ff);
        const uint8_t b2 = uint8_t(END_FRAME >>  8 & 0x000000ff);
        const uint8_t b3 = uint8_t(END_FRAME >>  0 & 0x000000ff);
        do {
            mSPI.writeByte(b0);
            mSPI.writeByte(b1);
            mSPI.writeByte(b2);
            mSPI.writeByte(b3);
        } while(nDWords--);
    }
References APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
getGlobalBrightnessAndScalingFactors()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> static void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors (PixelController< RGB_ORDER > & pixels, uint8_t * out_s0, uint8_t * out_s1, uint8_t * out_s2, uint8_t * out_brightness) inline static private
Definition at line 443 of file chipsets.h.
{
#if FASTLED_HD_COLOR_MIXING
        uint8_t brightness;
        pixels.getHdScale(out_s0, out_s1, out_s2, &brightness);
        struct Math {
            static uint16_t map(uint16_t x, uint16_t in_min, uint16_t in_max, uint16_t out_min, uint16_t out_max) {
                const uint16_t run = in_max - in_min;
                const uint16_t rise = out_max - out_min;
                const uint16_t delta = x - in_min;
                return (delta * rise) / run + out_min;
            }
        };
        // *out_brightness = Math::map(brightness, 0, 255, 0, 31);
        uint16_t bri = Math::map(brightness, 0, 255, 0, 31);
        if (bri == 0 && brightness != 0) {
            // Fixes https://github.com/FastLED/FastLED/issues/1908
            bri = 1;
        }
        *out_brightness = static_cast<uint8_t>(bri);
        return;
#else
        uint8_t s0, s1, s2;
        pixels.loadAndScaleRGB(&s0, &s1, &s2);
#if FASTLED_USE_GLOBAL_BRIGHTNESS == 1
        // This function is pure magic.
        const uint16_t maxBrightness = 0x1F;
        uint16_t brightness = ((((uint16_t)max(max(s0, s1), s2) + 1) * maxBrightness - 1) >> 8) + 1;
        s0 = (maxBrightness * s0 + (brightness >> 1)) / brightness;
        s1 = (maxBrightness * s1 + (brightness >> 1)) / brightness;
        s2 = (maxBrightness * s2 + (brightness >> 1)) / brightness;
#else
        const uint8_t brightness = 0x1F;
#endif  // FASTLED_USE_GLOBAL_BRIGHTNESS
        *out_s0 = s0;
        *out_s1 = s1;
        *out_s2 = s2;
        *out_brightness = static_cast<uint8_t>(brightness);
#endif  // FASTLED_HD_COLOR_MIXING
    }
References brightness, PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), and x.
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault().
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> virtual void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::init () inline override virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 422 of file chipsets.h.
{
        mSPI.init();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> virtual void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixels (PixelController< RGB_ORDER > & pixels) inline override protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 428 of file chipsets.h.
{
        switch (GAMMA_CORRECTION_MODE) {
            case fl::kFiveBitGammaCorrectionMode_Null: {
                showPixelsDefault(pixels);
                break;
            }
            case fl::kFiveBitGammaCorrectionMode_BitShift: {
                showPixelsGammaBitShift(pixels);
                break;
            }
        }
    }
References fl::kFiveBitGammaCorrectionMode_BitShift, fl::kFiveBitGammaCorrectionMode_Null, APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
showPixelsDefault()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault (PixelController< RGB_ORDER > & pixels) inline private
Definition at line 486 of file chipsets.h.
{
        mSPI.select();
        uint8_t s0, s1, s2, global_brightness;
        getGlobalBrightnessAndScalingFactors(pixels, &s0, &s1, &s2, &global_brightness);
        startBoundary();
        while (pixels.has(1)) {
            uint8_t c0, c1, c2;
            pixels.loadAndScaleRGB(&c0, &c1, &c2);
            writeLed(global_brightness, c0, c1, c2);
            pixels.stepDithering();
            pixels.advanceData();
        }
        endBoundary(pixels.size());
        mSPI.waitFully();
        mSPI.release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::endBoundary(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), PixelController< RGB_ORDER, LANES, MASK >::size(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::startBoundary(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixels().
showPixelsGammaBitShift()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift (PixelController< RGB_ORDER > & pixels) inline private
Definition at line 504 of file chipsets.h.
{
        mSPI.select();
        startBoundary();
        while (pixels.has(1)) {
            // Load raw uncorrected r,g,b values.
            uint8_t brightness, c0, c1, c2;  // c0-c2 is the RGB data re-ordered for pixel
            pixels.loadAndScale_APA102_HD(&c0, &c1, &c2, &brightness);
            writeLed(brightness, c0, c1, c2);
            pixels.stepDithering();
            pixels.advanceData();
        }
        endBoundary(pixels.size());
        mSPI.waitFully();
        mSPI.release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), brightness, APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::endBoundary(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), PixelController< RGB_ORDER, LANES, MASK >::size(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::startBoundary(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixels().
startBoundary()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::startBoundary () inline private
Definition at line 377 of file chipsets.h.
{
        mSPI.writeWord(START_FRAME >> 16);
        mSPI.writeWord(START_FRAME & 0xFFFF);
    }
References APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
write2Bytes()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> FASTLED_FORCE_INLINE void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::write2Bytes (uint8_t b1, uint8_t b2) inline private
Definition at line 410 of file chipsets.h.
{
#ifdef FASTLED_SPI_BYTE_ONLY
        mSPI.writeByte(b1);
        mSPI.writeByte(b2);
#else
        mSPI.writeWord(uint16_t(b1) << 8 | b2);
#endif
    }
References APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord().
writeLed()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> FASTLED_FORCE_INLINE void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed (uint8_t brightness, uint8_t b0, uint8_t b1, uint8_t b2) inline private
Definition at line 395 of file chipsets.h.
{
#ifdef FASTLED_SPI_BYTE_ONLY
        mSPI.writeByte(0xE0 | brightness);
        mSPI.writeByte(b0);
        mSPI.writeByte(b1);
        mSPI.writeByte(b2);
#else
        uint16_t b = 0xE000 | (brightness << 8) | (uint16_t)b0;
        mSPI.writeWord(b);
        uint16_t w = b1 << 8;
        w |= b2;
        mSPI.writeWord(w);
#endif
    }
References brightness, APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::kFiveBitGammaCorrectionMode_Null, uint32_t START_FRAME = 0x00000000, uint32_t END_FRAME = 0xFF000000> SPI APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::mSPI private
Definition at line 375 of file chipsets.h.
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::endBoundary(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::init(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::startBoundary(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::write2Bytes(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().
APA102ControllerHD
class APA102ControllerHD
Public Member Functions
APA102ControllerHD ()=default
APA102ControllerHD (const APA102ControllerHD &)=delete
Public Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(6), fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(6), fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Constructor & Destructor Documentation
APA102ControllerHD() [1/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6)> APA102ControllerHD< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::APA102ControllerHD () default
APA102ControllerHD() [2/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(6)> APA102ControllerHD< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::APA102ControllerHD (const APA102ControllerHD< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED > &) delete
HD107Controller
class HD107Controller
Additional Inherited Members
Public Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(40), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(40), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
HD107HDController
class HD107HDController
Additional Inherited Members
Public Member Functions inherited from APA102ControllerHD< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(40) >
APA102ControllerHD ()=default
APA102ControllerHD (const APA102ControllerHD &)=delete
Public Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
LPD6803Controller
class LPD6803Controller
Public Member Functions
LPD6803Controller ()
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Member Functions
void endBoundary (int nLeds)
void startBoundary ()
Private Attributes
SPI mSPI
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SPI private
Definition at line 311 of file chipsets.h.
Constructor & Destructor Documentation
LPD6803Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD6803Controller () inline
Definition at line 318 of file chipsets.h.
{}
Member Function Documentation
endBoundary()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> void LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::endBoundary (int nLeds) inline private
Definition at line 315 of file chipsets.h.
{ int nDWords = (nLeds/32); do { mSPI.writeByte(0xFF); mSPI.writeByte(0x00); mSPI.writeByte(0x00); mSPI.writeByte(0x00); } while(nDWords--); }
References LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> virtual void LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 320 of file chipsets.h.
{
        mSPI.init();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), and LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> virtual void LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 326 of file chipsets.h.
{
        mSPI.select();
        startBoundary();
        while(pixels.has(1)) {
            FASTLED_REGISTER uint16_t command;
            command = 0x8000;
            command |= (pixels.loadAndScale0() & 0xF8) << 7; // red is the high 5 bits
            command |= (pixels.loadAndScale1() & 0xF8) << 2; // green is the middle 5 bits
            mSPI.writeByte((command >> 8) & 0xFF);
            command |= pixels.loadAndScale2() >> 3 ; // blue is the low 5 bits
            mSPI.writeByte(command & 0xFF);
            pixels.stepDithering();
            pixels.advanceData();
        }
        endBoundary(pixels.size());
        mSPI.waitFully();
        mSPI.release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::endBoundary(), FASTLED_REGISTER, PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), PixelController< RGB_ORDER, LANES, MASK >::size(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::startBoundary(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
startBoundary()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> void LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::startBoundary () inline private
Definition at line 314 of file chipsets.h.
{ mSPI.writeByte(0); mSPI.writeByte(0); mSPI.writeByte(0); mSPI.writeByte(0); }
References LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> SPI LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI private
Definition at line 312 of file chipsets.h.
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::endBoundary(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), and LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::startBoundary().
LPD8806Controller
class LPD8806Controller
Public Member Functions
LPD8806Controller ()
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Attributes
SPI mSPI
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SPI private
Definition at line 230 of file chipsets.h.
Constructor & Destructor Documentation
LPD8806Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806Controller () inline
Definition at line 246 of file chipsets.h.
{}
Member Function Documentation
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> virtual void LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 247 of file chipsets.h.
{
        mSPI.init();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), and LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> virtual void LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 254 of file chipsets.h.
{
        mSPI.template writePixels<0, LPD8806_ADJUST, RGB_ORDER>(pixels, &mSPI);
    }
References LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI.
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> SPI LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI private
Definition at line 243 of file chipsets.h.
Referenced by LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), and LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
LPD8806Controller::LPD8806_ADJUST
class LPD8806Controller::LPD8806_ADJUST
Static Public Member Functions
static FASTLED_FORCE_INLINE uint8_t adjust (FASTLED_REGISTER uint8_t data)
static FASTLED_FORCE_INLINE void postBlock (int len, void *context=NULL)
Member Function Documentation
adjust()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> static FASTLED_FORCE_INLINE uint8_t LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806_ADJUST::adjust (FASTLED_REGISTER uint8_t data) inline static
Definition at line 235 of file chipsets.h.
{ return ((data>>1) | 0x80) + ((data && (data<254)) & 0x01); }
postBlock()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> static FASTLED_FORCE_INLINE void LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806_ADJUST::postBlock (int len, void * context = NULL) inline static
Definition at line 236 of file chipsets.h.
{
            SPI* pSPI = static_cast<SPI*>(context);
            pSPI->writeBytesValueRaw(0, ((len*3+63)>>6));
        }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw().
P9813Controller
class P9813Controller
Public Member Functions
P9813Controller ()
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Member Functions
void writeBoundary ()
FASTLED_FORCE_INLINE void writeLed (uint8_t r, uint8_t g, uint8_t b)
Private Attributes
SPI mSPI
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SPI private
Definition at line 640 of file chipsets.h.
Constructor & Destructor Documentation
P9813Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::P9813Controller () inline
Definition at line 651 of file chipsets.h.
{}
Member Function Documentation
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> virtual void P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 653 of file chipsets.h.
{
        mSPI.init();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), and P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> virtual void P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 659 of file chipsets.h.
{
        mSPI.select();
        writeBoundary();
        while(pixels.has(1)) {
            writeLed(pixels.loadAndScale0(), pixels.loadAndScale1(), pixels.loadAndScale2());
            pixels.advanceData();
            pixels.stepDithering();
        }
        writeBoundary();
        mSPI.waitFully();
        mSPI.release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeBoundary(), and P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeLed().
writeBoundary()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> void P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeBoundary () inline private
Definition at line 643 of file chipsets.h.
{ mSPI.writeWord(0); mSPI.writeWord(0); }
References P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord().
Referenced by P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
writeLed()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> FASTLED_FORCE_INLINE void P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeLed (uint8_t r, uint8_t g, uint8_t b) inline private
Definition at line 645 of file chipsets.h.
{
        FASTLED_REGISTER uint8_t top = 0xC0 | ((~b & 0xC0) >> 2) | ((~g & 0xC0) >> 4) | ((~r & 0xC0) >> 6);
        mSPI.writeByte(top); mSPI.writeByte(b); mSPI.writeByte(g); mSPI.writeByte(r);
    }
References FASTLED_REGISTER, P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(10)> SPI P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI private
Definition at line 641 of file chipsets.h.
Referenced by P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeBoundary(), and P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeLed().
SK9822Controller
class SK9822Controller
Additional Inherited Members
Public Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
SK9822ControllerHD
class SK9822ControllerHD
Additional Inherited Members
Public Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_BitShift, 0x00000000, 0x00000000 >
APA102Controller ()
virtual void init () override
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_BitShift, 0x00000000, 0x00000000 >
virtual void showPixels (PixelController< RGB_ORDER > &pixels) override
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
SM16716Controller
class SM16716Controller
Public Member Functions
SM16716Controller ()
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Member Functions
void writeHeader ()
Private Attributes
SPI mSPI
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SPI private
Definition at line 690 of file chipsets.h.
Constructor & Destructor Documentation
SM16716Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SM16716Controller () inline
Definition at line 709 of file chipsets.h.
{}
Member Function Documentation
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> virtual void SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 711 of file chipsets.h.
{
        mSPI.init();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), and SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> virtual void SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 717 of file chipsets.h.
{
        // Make sure the FLAG_START_BIT flag is set to ensure that an extra 1 bit is sent at the start
        // of each triplet of bytes for rgb data
        // writeHeader();
        mSPI.template writePixels<FLAG_START_BIT, DATA_NOP, RGB_ORDER>(pixels, NULL);
        writeHeader();
    }
References SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader().
writeHeader()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> void SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader () inline private
Definition at line 693 of file chipsets.h.
                       {
        // Write out 50 zeros to the spi line (6 blocks of 8 followed by two single bit writes)
        mSPI.select();
        mSPI.template writeBit<0>(0);
        mSPI.writeByte(0);
        mSPI.writeByte(0);
        mSPI.writeByte(0);
        mSPI.template writeBit<0>(0);
        mSPI.writeByte(0);
        mSPI.writeByte(0);
        mSPI.writeByte(0);
        mSPI.waitFully();
        mSPI.release();
    }
References SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(16)> SPI SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI private
Definition at line 691 of file chipsets.h.
Referenced by SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), and SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader().
WS2801Controller
class WS2801Controller
Public Member Functions
WS2801Controller ()
virtual void init ()
Initialize the controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Private Types
typedef SPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > SPI
Private Attributes
SPI mSPI
CMinWait< 1000 > mWaitDelay
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
SPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> SPIOutput<DATA_PIN, CLOCK_PIN, SPI_SPEED> WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::SPI private
Definition at line 273 of file chipsets.h.
Constructor & Destructor Documentation
WS2801Controller()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::WS2801Controller () inline
Definition at line 278 of file chipsets.h.
{}
Member Function Documentation
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> virtual void WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init () inline virtual
Initialize the controller.
Implements CLEDController.
Definition at line 281 of file chipsets.h.
{
        mSPI.init();
      mWaitDelay.mark();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), CMinWait< WAIT >::mark(), WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, and WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mWaitDelay.
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> virtual void WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 289 of file chipsets.h.
{
        mWaitDelay.wait();
        mSPI.template writePixels<0, DATA_NOP, RGB_ORDER>(pixels, NULL);
        mWaitDelay.mark();
    }
References CMinWait< WAIT >::mark(), WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI, WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mWaitDelay, and CMinWait< WAIT >::wait().
Member Data Documentation
mSPI
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> SPI WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mSPI private
Definition at line 274 of file chipsets.h.
Referenced by WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), and WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
mWaitDelay
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(1)> CMinWait<1000> WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::mWaitDelay private
Definition at line 275 of file chipsets.h.
Referenced by WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), and WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels().
WS2803Controller
class WS2803Controller
Additional Inherited Members
Public Member Functions inherited from WS2801Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(25) >
WS2801Controller ()
virtual void init ()
Initialize the controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from WS2801Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(25) >
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list