FastLED: LedRopeInterface Class Reference
LedRopeInterface Class Reference abstract
Detailed Description
Definition at line 7 of file led_rope_interface.h.
#include <led_rope_interface.h>
Public Member Functions
virtual ~LedRopeInterface ()
virtual void DrawRepeat (const int *value_array, int array_length)=0
virtual void DrawSequentialRepeat (int repeat)=0
virtual Color3i * GetIterator (int i)=0
virtual int length () const =0
virtual void RawBeginDraw ()=0
virtual void RawCommitDraw ()=0
virtual void RawDrawPixel (const Color3i &c)=0
virtual void RawDrawPixel (uint8_t r, uint8_t g, uint8_t b)=0
virtual void RawDrawPixels (const Color3i &c, int n)=0
virtual void Set (int i, const Color3i &c)=0
virtual void Set (int i, int length, const Color3i &color)
Constructor & Destructor Documentation
~LedRopeInterface()
virtual LedRopeInterface::~LedRopeInterface () inline virtual
Definition at line 9 of file led_rope_interface.h.
{}
Member Function Documentation
DrawRepeat()
virtual void LedRopeInterface::DrawRepeat (const int * value_array, int array_length) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::Paint().
DrawSequentialRepeat()
virtual void LedRopeInterface::DrawSequentialRepeat (int repeat) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::Paint().
GetIterator()
virtual Color3i * LedRopeInterface::GetIterator (int i) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::PaintVuNotes(), and Painter::PaintVuSpaceInvaders().
length()
virtual int LedRopeInterface::length () const pure virtual
Implemented in LedRopeTCL.
Referenced by Set().
RawBeginDraw()
virtual void LedRopeInterface::RawBeginDraw () pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::PaintBrightSurprise(), Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), and Painter::VegasVisualizer().
RawCommitDraw()
virtual void LedRopeInterface::RawCommitDraw () pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::PaintBrightSurprise(), Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), and Painter::VegasVisualizer().
RawDrawPixel() [1/2]
virtual void LedRopeInterface::RawDrawPixel (const Color3i & c) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::PaintBrightSurprise(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), and Painter::VegasVisualizer().
RawDrawPixel() [2/2]
virtual void LedRopeInterface::RawDrawPixel (uint8_t r, uint8_t g, uint8_t b) pure virtual
Implemented in LedRopeTCL.
RawDrawPixels()
virtual void LedRopeInterface::RawDrawPixels (const Color3i & c, int n) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::PaintVuMidNotesFade().
Set() [1/2]
virtual void LedRopeInterface::Set (int i, const Color3i & c) pure virtual
Implemented in LedRopeTCL.
Referenced by Painter::Paint(), and Set().
Set() [2/2]
virtual void LedRopeInterface::Set (int i, int length, const Color3i & color) inline virtual
Definition at line 12 of file led_rope_interface.h.
{
    for (int j = 0; j < length; ++j) {
      Set(i + j, color);
    }
  }
References length(), and Set().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/led_rope_interface.h