FastLED: Timekeeping Functions
Timekeeping Functions
Detailed Description
Tools for tracking and working with time
Classes
class CEveryNMillisDynamic
Create the CEveryNMillisDynamic class for dynamic millisecond intervals.
class CEveryNTime
Time interval checking class.
Macros
#define GET_MILLIS millis
The a number of functions need access to a millisecond counter in order to keep time.
#define INSTANTIATE_EVERY_N_TIME_PERIODS(NAME, TIMETYPE, TIMEGETTER)
Preprocessor-based class "template" for CEveryNTime, used with EVERY_N_TIME timekeepers.
#define USE_GET_MILLISECOND_TIMER
Set this flag to use the get_millisecond_timer() function in place of the default millis() function.
Functions
LIB8STATIC uint16_t bseconds16 ()
Returns the current time-since-boot in "binary seconds", which are actually 1024/1000 of a second long.
LIB8STATIC uint16_t div1024_32_16 (uint32_t in32)
Helper routine to divide a 32-bit value by 1024, returning only the low 16 bits.
LIB8STATIC uint8_t hours8 ()
Return the current hours since boot in an 8-bit value.
LIB8STATIC uint16_t minutes16 ()
Return the current minutes since boot in a 16-bit value.
LIB8STATIC uint16_t seconds16 ()
Return the current seconds since boot in a 16-bit value.
CEveryNTime Base Classes
These macros define the time interval checking classes used in the EVERY_N_TIME time macros.
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNMillis, uint32_t, GET_MILLIS)
Create the CEveryNMillis class for millisecond intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNSeconds, uint16_t, seconds16)
Create the CEveryNSeconds class for second intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNBSeconds, uint16_t, bseconds16)
Create the CEveryNBSeconds class for bsecond intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNMinutes, uint16_t, minutes16)
Create the CEveryNMinutes class for minutes intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNHours, uint8_t, hours8)
Create the CEveryNHours class for hours intervals.
#define CEveryNMilliseconds CEveryNMillis
Alias for CEveryNMillis.
"EVERY_N_TIME" Macros
Check whether to excecute a block of code every N amount of time.
These are useful for limiting how often code runs. For example, you can use fill_rainbow() to fill a strip of LEDs with color, combined with an EVERY_N_MILLIS block to limit how fast the colors change:
static uint8_t hue = 0;
fill_rainbow(leds, NUM_LEDS, hue);
EVERY_N_MILLIS(20) { hue++; }  // advances hue every 20 milliseconds
Note that in order for these to be accurate, the EVERY_N block must be evaluated at a regular basis.
#define EVERY_N_MILLIS(N)
Checks whether to execute a block of code every N milliseconds.
#define EVERY_N_MILLIS_I(NAME, N)
Checks whether to execute a block of code every N milliseconds, using a custom instance name.
#define EVERY_N_SECONDS(N)
Checks whether to execute a block of code every N seconds.
#define EVERY_N_SECONDS_I(NAME, N)
Checks whether to execute a block of code every N seconds, using a custom instance name.
#define EVERY_N_BSECONDS(N)
Checks whether to execute a block of code every N bseconds.
#define EVERY_N_BSECONDS_I(NAME, N)
Checks whether to execute a block of code every N bseconds, using a custom instance name.
#define EVERY_N_MINUTES(N)
Checks whether to execute a block of code every N minutes.
#define EVERY_N_MINUTES_I(NAME, N)
Checks whether to execute a block of code every N minutes, using a custom instance name.
#define EVERY_N_HOURS(N)
Checks whether to execute a block of code every N hours.
#define EVERY_N_HOURS_I(NAME, N)
Checks whether to execute a block of code every N hours, using a custom instance name.
#define EVERY_N_MILLISECONDS(N)
Alias for EVERY_N_MILLIS.
#define EVERY_N_MILLISECONDS_I(NAME, N)
Alias for EVERY_N_MILLIS_I.
#define EVERY_N_MILLISECONDS_DYNAMIC(PERIOD_FUNC)
Checks whether to execute a block of code every N milliseconds, where N is determined dynamically.
#define EVERY_N_MILLISECONDS_DYNAMIC_I(NAME, PERIOD_FUNC)
Checks whether to execute a block of code every N milliseconds, where N is determined dynamically, using a custom instance name.
Class Documentation
CEveryNMillisDynamic
class CEveryNMillisDynamic
Public Member Functions
CEveryNMillisDynamic (uint32_t period)
uint32_t getElapsed ()
uint32_t getLastTriggerTime ()
uint32_t getPeriod () const
uint32_t getRemaining ()
uint32_t getTime ()
operator bool ()
bool ready ()
void reset ()
void setPeriod (uint32_t period)
void trigger ()
Public Attributes
uint32_t mPeriod
uint32_t mPrevTrigger
Constructor & Destructor Documentation
CEveryNMillisDynamic()
CEveryNMillisDynamic::CEveryNMillisDynamic (uint32_t period) inline
Definition at line 1191 of file lib8tion.h.
: mPeriod(period) { reset(); };
References reset().
Member Function Documentation
getElapsed()
uint32_t CEveryNMillisDynamic::getElapsed () inline
Definition at line 1194 of file lib8tion.h.
{ return getTime() - mPrevTrigger; }
References getTime(), and mPrevTrigger.
Referenced by getRemaining(), and ready().
getLastTriggerTime()
uint32_t CEveryNMillisDynamic::getLastTriggerTime () inline
Definition at line 1196 of file lib8tion.h.
{ return mPrevTrigger; }
References mPrevTrigger.
getPeriod()
uint32_t CEveryNMillisDynamic::getPeriod () const inline
Definition at line 1193 of file lib8tion.h.
{ return mPeriod; };
References mPeriod.
Referenced by getRemaining(), ready(), and trigger().
getRemaining()
uint32_t CEveryNMillisDynamic::getRemaining () inline
Definition at line 1195 of file lib8tion.h.
{ return getPeriod() - getElapsed(); }
References getElapsed(), and getPeriod().
getTime()
uint32_t CEveryNMillisDynamic::getTime () inline
Definition at line 1192 of file lib8tion.h.
{ return GET_MILLIS(); };
References GET_MILLIS.
Referenced by getElapsed(), reset(), and trigger().
operator bool()
CEveryNMillisDynamic::operator bool () inline
Definition at line 1206 of file lib8tion.h.
{ return ready(); }
References ready().
ready()
bool CEveryNMillisDynamic::ready () inline
Definition at line 1197 of file lib8tion.h.
                 {
        bool isReady = (getElapsed() >= getPeriod());
        if( isReady ) { reset(); }
        return isReady;
    }
References getElapsed(), getPeriod(), and reset().
Referenced by operator bool().
reset()
void CEveryNMillisDynamic::reset () inline
Definition at line 1202 of file lib8tion.h.
{ mPrevTrigger = getTime(); };
References getTime(), and mPrevTrigger.
Referenced by CEveryNMillisDynamic(), and ready().
setPeriod()
void CEveryNMillisDynamic::setPeriod (uint32_t period) inline
Definition at line 1204 of file lib8tion.h.
{ mPeriod = period; }
References mPeriod.
trigger()
void CEveryNMillisDynamic::trigger () inline
Definition at line 1203 of file lib8tion.h.
{ mPrevTrigger = getTime() - getPeriod(); };
References getPeriod(), getTime(), and mPrevTrigger.
Member Data Documentation
mPeriod
uint32_t CEveryNMillisDynamic::mPeriod
Definition at line 1189 of file lib8tion.h.
Referenced by getPeriod(), and setPeriod().
mPrevTrigger
uint32_t CEveryNMillisDynamic::mPrevTrigger
Definition at line 1188 of file lib8tion.h.
Referenced by getElapsed(), getLastTriggerTime(), reset(), and trigger().
CEveryNTime
class CEveryNTime
Public Member Functions
CEveryNTime ()
Default constructor.
CEveryNTime (TIMETYPE period)
Constructor.
TIMETYPE getElapsed ()
Get the time elapsed since the last trigger event.
TIMETYPE getLastTriggerTime ()
Get the timestamp of the most recent trigger event.
TIMETYPE getPeriod ()
Get the time interval between triggers.
TIMETYPE getRemaining ()
Get the time until the next trigger event.
TIMETYPE getTime ()
Get the current time according to the class' timekeeper.
operator bool ()
Check if the time interval has elapsed.
bool ready ()
Check if the time interval has elapsed.
void reset ()
Reset the timestamp to the current time.
void setPeriod (TIMETYPE period)
Set the time interval between triggers.
void trigger ()
Reset the timestamp so it is ready() on next call.
Public Attributes
TIMETYPE mPeriod
Timing interval to check.
TIMETYPE mPrevTrigger
Timestamp of the last time the class was "ready".
Constructor & Destructor Documentation
CEveryNTime() [1/2]
CEveryNTime::CEveryNTime () inline
Default constructor.
Definition at line 1126 of file lib8tion.h.
{ reset(); mPeriod = 1; };
References mPeriod, and reset().
CEveryNTime() [2/2]
CEveryNTime::CEveryNTime (TIMETYPE period) inline
Constructor.
Parameters
period the time interval between triggers
Definition at line 1129 of file lib8tion.h.
{ reset(); setPeriod(period); };
References reset(), and setPeriod().
Member Function Documentation
getElapsed()
TIMETYPE CEveryNTime::getElapsed () inline
Get the time elapsed since the last trigger event.
Definition at line 1141 of file lib8tion.h.
{ return getTime() - mPrevTrigger; }
References getTime(), and mPrevTrigger.
Referenced by getRemaining(), and ready().
getLastTriggerTime()
TIMETYPE CEveryNTime::getLastTriggerTime () inline
Get the timestamp of the most recent trigger event.
Definition at line 1147 of file lib8tion.h.
{ return mPrevTrigger; }
References mPrevTrigger.
getPeriod()
TIMETYPE CEveryNTime::getPeriod () inline
Get the time interval between triggers.
Definition at line 1138 of file lib8tion.h.
{ return mPeriod; };
References mPeriod.
getRemaining()
TIMETYPE CEveryNTime::getRemaining () inline
Get the time until the next trigger event.
Definition at line 1144 of file lib8tion.h.
{ return mPeriod - getElapsed(); }
References getElapsed(), and mPeriod.
getTime()
TIMETYPE CEveryNTime::getTime () inline
Get the current time according to the class' timekeeper.
Definition at line 1135 of file lib8tion.h.
{ return (TIMETYPE)(TIMEGETTER()); };
Referenced by getElapsed(), reset(), and trigger().
operator bool()
CEveryNTime::operator bool () inline
Check if the time interval has elapsed.
Definition at line 1163 of file lib8tion.h.
{ return ready(); }
References ready().
ready()
bool CEveryNTime::ready () inline
Check if the time interval has elapsed.
Definition at line 1150 of file lib8tion.h.
                 {
        bool isReady = (getElapsed() >= mPeriod);
        if( isReady ) { reset(); }
        return isReady;
    }
References getElapsed(), mPeriod, and reset().
Referenced by operator bool().
reset()
void CEveryNTime::reset () inline
Reset the timestamp to the current time.
Definition at line 1157 of file lib8tion.h.
{ mPrevTrigger = getTime(); };
References getTime(), and mPrevTrigger.
Referenced by CEveryNTime(), CEveryNTime(), and ready().
setPeriod()
void CEveryNTime::setPeriod (TIMETYPE period) inline
Set the time interval between triggers.
Definition at line 1132 of file lib8tion.h.
{ mPeriod = period; };
References mPeriod.
Referenced by CEveryNTime().
trigger()
void CEveryNTime::trigger () inline
Reset the timestamp so it is ready() on next call.
Definition at line 1160 of file lib8tion.h.
{ mPrevTrigger = getTime() - mPeriod; };
References getTime(), mPeriod, and mPrevTrigger.
Member Data Documentation
mPeriod
TIMETYPE CEveryNTime::mPeriod
Timing interval to check.
Definition at line 1123 of file lib8tion.h.
Referenced by CEveryNTime(), getPeriod(), getRemaining(), ready(), setPeriod(), and trigger().
mPrevTrigger
TIMETYPE CEveryNTime::mPrevTrigger
Timestamp of the last time the class was "ready".
Definition at line 1122 of file lib8tion.h.
Referenced by getElapsed(), getLastTriggerTime(), reset(), and trigger().
Macro Definition Documentation
CEveryNMilliseconds
#define CEveryNMilliseconds CEveryNMillis
Alias for CEveryNMillis.
Definition at line 1183 of file lib8tion.h.
EVERY_N_BSECONDS
#define EVERY_N_BSECONDS (N)
Value:
EVERY_N_BSECONDS_I(CONCAT_MACRO(PER, __COUNTER__),N)
Checks whether to execute a block of code every N bseconds.
See also
bseconds16()
Definition at line 1292 of file lib8tion.h.
EVERY_N_BSECONDS_I
#define EVERY_N_BSECONDS_I (NAME, N)
Value:
static CEveryNBSeconds NAME(N); if(NAME)
Checks whether to execute a block of code every N bseconds, using a custom instance name.
See also
bseconds16()
Definition at line 1296 of file lib8tion.h.
EVERY_N_HOURS
#define EVERY_N_HOURS (N)
Value:
EVERY_N_HOURS_I(CONCAT_MACRO(PER, __COUNTER__),N)
Checks whether to execute a block of code every N hours.
See also
hours8()
Definition at line 1310 of file lib8tion.h.
EVERY_N_HOURS_I
#define EVERY_N_HOURS_I (NAME, N)
Value:
static CEveryNHours NAME(N); if(NAME)
Checks whether to execute a block of code every N hours, using a custom instance name.
See also
hours8()
Definition at line 1314 of file lib8tion.h.
EVERY_N_MILLIS
#define EVERY_N_MILLIS (N)
Value:
EVERY_N_MILLIS_I(CONCAT_MACRO(PER, __COUNTER__),N)
Checks whether to execute a block of code every N milliseconds.
See also
GET_MILLIS
Definition at line 1274 of file lib8tion.h.
EVERY_N_MILLIS_I
#define EVERY_N_MILLIS_I (NAME, N)
Value:
static CEveryNMillis NAME(N); if(NAME)
Checks whether to execute a block of code every N milliseconds, using a custom instance name.
See also
GET_MILLIS
Definition at line 1278 of file lib8tion.h.
EVERY_N_MILLISECONDS
#define EVERY_N_MILLISECONDS (N)
Value:
EVERY_N_MILLIS(N)
Alias for EVERY_N_MILLIS.
Examples
DemoReel100.ino, Pacifica.ino, and TwinkleFox.ino.
Definition at line 1318 of file lib8tion.h.
Referenced by fl::DemoReel100::draw(), fl::TwinkleFox::draw(), and loop().
EVERY_N_MILLISECONDS_DYNAMIC
#define EVERY_N_MILLISECONDS_DYNAMIC (PERIOD_FUNC)
Value:
EVERY_N_MILLISECONDS_DYNAMIC_I(CONCAT_MACRO(__dynamic_millis_timer, __COUNTER__), (PERIOD_FUNC))
Checks whether to execute a block of code every N milliseconds, where N is determined dynamically.
Definition at line 1323 of file lib8tion.h.
Referenced by loop().
EVERY_N_MILLISECONDS_DYNAMIC_I
#define EVERY_N_MILLISECONDS_DYNAMIC_I (NAME, PERIOD_FUNC)
Value:
    static CEveryNMillisDynamic NAME(1); \
    NAME.setPeriod(PERIOD_FUNC); \
    if( NAME )
Checks whether to execute a block of code every N milliseconds, where N is determined dynamically, using a custom instance name.
Definition at line 1326 of file lib8tion.h.
#define EVERY_N_MILLISECONDS_DYNAMIC_I(NAME, PERIOD_FUNC) \
    static CEveryNMillisDynamic NAME(1); \
    NAME.setPeriod(PERIOD_FUNC); \
    if( NAME )
EVERY_N_MILLISECONDS_I
#define EVERY_N_MILLISECONDS_I (NAME, N)
Value:
EVERY_N_MILLIS_I(NAME,N)
Alias for EVERY_N_MILLIS_I.
Definition at line 1320 of file lib8tion.h.
EVERY_N_MINUTES
#define EVERY_N_MINUTES (N)
Value:
EVERY_N_MINUTES_I(CONCAT_MACRO(PER, __COUNTER__),N)
Checks whether to execute a block of code every N minutes.
See also
minutes16()
Definition at line 1301 of file lib8tion.h.
EVERY_N_MINUTES_I
#define EVERY_N_MINUTES_I (NAME, N)
Value:
static CEveryNMinutes NAME(N); if(NAME)
Checks whether to execute a block of code every N minutes, using a custom instance name.
See also
minutes16()
Definition at line 1305 of file lib8tion.h.
EVERY_N_SECONDS
#define EVERY_N_SECONDS (N)
Value:
EVERY_N_SECONDS_I(CONCAT_MACRO(PER, __COUNTER__),N)
Checks whether to execute a block of code every N seconds.
See also
seconds16()
Examples
DemoReel100.ino, FxEngine.ino, and TwinkleFox.ino.
Definition at line 1283 of file lib8tion.h.
Referenced by fl::DemoReel100::draw(), and loop().
EVERY_N_SECONDS_I
#define EVERY_N_SECONDS_I (NAME, N)
Value:
static CEveryNSeconds NAME(N); if(NAME)
Checks whether to execute a block of code every N seconds, using a custom instance name.
See also
seconds16()
Definition at line 1287 of file lib8tion.h.
GET_MILLIS
#define GET_MILLIS millis
The a number of functions need access to a millisecond counter in order to keep time.
On Arduino, this is "millis()". On other platforms, you'll need to provide a function with this signature which provides similar functionality:
uint32_t get_millisecond_timer();
You can also force use of the get_millisecond_timer() function by #defining USE_GET_MILLISECOND_TIMER.
Examples
Pacifica.ino.
Definition at line 837 of file lib8tion.h.
Referenced by beat88(), bseconds16(), CEveryNMillisDynamic::getTime(), hours8(), minutes16(), pacifica_loop(), and seconds16().
INSTANTIATE_EVERY_N_TIME_PERIODS
#define INSTANTIATE_EVERY_N_TIME_PERIODS (NAME, TIMETYPE, TIMEGETTER)
Value:
class NAME {    \
public: \
    TIMETYPE mPrevTrigger;  \
    TIMETYPE mPeriod;   \
    \
    NAME() { reset(); mPeriod = 1; }; \
    NAME(TIMETYPE period) { reset(); setPeriod(period); };    \
    void setPeriod( TIMETYPE period) { mPeriod = period; }; \
    TIMETYPE getTime() { return (TIMETYPE)(TIMEGETTER()); };    \
    TIMETYPE getPeriod() { return mPeriod; };   \
    TIMETYPE getElapsed() { return getTime() - mPrevTrigger; }  \
    TIMETYPE getRemaining() { return mPeriod - getElapsed(); }  \
    TIMETYPE getLastTriggerTime() { return mPrevTrigger; }  \
    bool ready() { \
        bool isReady = (getElapsed() >= mPeriod);   \
        if( isReady ) { reset(); }  \
        return isReady; \
    }   \
    void reset() { mPrevTrigger = getTime(); }; \
    void trigger() { mPrevTrigger = getTime() - mPeriod; }; \
        \
    operator bool() { return ready(); } \
};
Preprocessor-based class "template" for CEveryNTime, used with EVERY_N_TIME timekeepers.
Classes to implement EVERY_N_MILLIS, EVERY_N_SECONDS, EVERY_N_MINUTES, EVERY_N_HOURS, and EVERY_N_BSECONDS.
Definition at line 1077 of file lib8tion.h.
#define INSTANTIATE_EVERY_N_TIME_PERIODS(NAME,TIMETYPE,TIMEGETTER) \
class NAME {    \
public: \
    TIMETYPE mPrevTrigger;  \
    TIMETYPE mPeriod;   \
    \
    NAME() { reset(); mPeriod = 1; }; \
    NAME(TIMETYPE period) { reset(); setPeriod(period); };    \
    void setPeriod( TIMETYPE period) { mPeriod = period; }; \
    TIMETYPE getTime() { return (TIMETYPE)(TIMEGETTER()); };    \
    TIMETYPE getPeriod() { return mPeriod; };   \
    TIMETYPE getElapsed() { return getTime() - mPrevTrigger; }  \
    TIMETYPE getRemaining() { return mPeriod - getElapsed(); }  \
    TIMETYPE getLastTriggerTime() { return mPrevTrigger; }  \
    bool ready() { \
        bool isReady = (getElapsed() >= mPeriod);   \
        if( isReady ) { reset(); }  \
        return isReady; \
    }   \
    void reset() { mPrevTrigger = getTime(); }; \
    void trigger() { mPrevTrigger = getTime() - mPeriod; }; \
        \
    operator bool() { return ready(); } \
};
USE_GET_MILLISECOND_TIMER
#define USE_GET_MILLISECOND_TIMER
Set this flag to use the get_millisecond_timer() function in place of the default millis() function.
Definition at line 1341 of file lib8tion.h.
Function Documentation
bseconds16()
LIB8STATIC uint16_t bseconds16 ()
Returns the current time-since-boot in "binary seconds", which are actually 1024/1000 of a second long.
Definition at line 1065 of file lib8tion.h.
{
    uint32_t ms = GET_MILLIS();
    uint16_t s16;
    s16 = div1024_32_16( ms);
    return s16;
}
References div1024_32_16(), and GET_MILLIS.
div1024_32_16()
LIB8STATIC uint16_t div1024_32_16 (uint32_t in32)
Helper routine to divide a 32-bit value by 1024, returning only the low 16 bits.
You'd think this would be just
result = (in32 >> 10) & 0xFFFF;
And on ARM, that's what you want and all is well. But on AVR that code turns into a loop that executes a four-byte shift ten times: 40 shifts in all, plus loop overhead. This routine gets exactly the same result with just six shifts (vs 40), and no loop overhead. Used to convert millis to "binary seconds" aka bseconds: one bsecond == 1024 millis.
Definition at line 1040 of file lib8tion.h.
{
    uint16_t out16;
#if defined(__AVR__)
    asm volatile (
        "  lsr %D[in]  \n\t"
        "  ror %C[in]  \n\t"
        "  ror %B[in]  \n\t"
        "  lsr %D[in]  \n\t"
        "  ror %C[in]  \n\t"
        "  ror %B[in]  \n\t"
        "  mov %B[out],%C[in] \n\t"
        "  mov %A[out],%B[in] \n\t"
        : [in] "+r" (in32),
        [out] "=r" (out16)
    );
#else
    out16 = (in32 >> 10) & 0xFFFF;
#endif
    return out16;
}
Referenced by bseconds16().
hours8()
LIB8STATIC uint8_t hours8 ()
Return the current hours since boot in an 8-bit value.
Used as part of the "every N time-periods" mechanism
Definition at line 1018 of file lib8tion.h.
{
    uint32_t ms = GET_MILLIS();
    uint8_t h8;
    h8 = (ms / (3600000L)) & 0xFF;
    return h8;
}
References GET_MILLIS.
INSTANTIATE_EVERY_N_TIME_PERIODS() [1/5]
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNBSeconds , uint16_t , bseconds16)
Create the CEveryNBSeconds class for bsecond intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS() [2/5]
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNHours , uint8_t , hours8)
Create the CEveryNHours class for hours intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS() [3/5]
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNMillis , uint32_t , GET_MILLIS)
Create the CEveryNMillis class for millisecond intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS() [4/5]
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNMinutes , uint16_t , minutes16)
Create the CEveryNMinutes class for minutes intervals.
INSTANTIATE_EVERY_N_TIME_PERIODS() [5/5]
INSTANTIATE_EVERY_N_TIME_PERIODS (CEveryNSeconds , uint16_t , seconds16)
Create the CEveryNSeconds class for second intervals.
minutes16()
LIB8STATIC uint16_t minutes16 ()
Return the current minutes since boot in a 16-bit value.
Used as part of the "every N time-periods" mechanism
Definition at line 1008 of file lib8tion.h.
{
    uint32_t ms = GET_MILLIS();
    uint16_t m16;
    m16 = (ms / (60000L)) & 0xFFFF;
    return m16;
}
References GET_MILLIS.
seconds16()
LIB8STATIC uint16_t seconds16 ()
Return the current seconds since boot in a 16-bit value.
Used as part of the "every N time-periods" mechanism
Definition at line 998 of file lib8tion.h.
{
    uint32_t ms = GET_MILLIS();
    uint16_t s16;
    s16 = ms / 1000;
    return s16;
}
References GET_MILLIS.