FastLED: /home/runner/work/FastLED/FastLED/examples/RGBWEmulated/RGBWEmulated.ino File Reference
RGBWEmulated.ino File Reference
#include <FastLED.h>
Macros
#define DATA_PIN 3
#define NUM_LEDS 10
#define TIME_FACTOR_HUE 60
#define TIME_FACTOR_SAT 100
#define TIME_FACTOR_VAL 100
Typedefs
typedef WS2812< DATA_PIN, RGB > ControllerT
Functions
void fillAndShow (CRGB color)
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Rgbw rgbw
static RGBWEmulatedController< ControllerT, GRB > rgbwEmu (rgbw)
Macro Definition Documentation
DATA_PIN
#define DATA_PIN 3
Definition at line 11 of file RGBWEmulated.ino.
NUM_LEDS
#define NUM_LEDS 10
Definition at line 5 of file RGBWEmulated.ino.
Referenced by fillAndShow(), and setup().
TIME_FACTOR_HUE
#define TIME_FACTOR_HUE 60
Definition at line 17 of file RGBWEmulated.ino.
TIME_FACTOR_SAT
#define TIME_FACTOR_SAT 100
Definition at line 18 of file RGBWEmulated.ino.
TIME_FACTOR_VAL
#define TIME_FACTOR_VAL 100
Definition at line 19 of file RGBWEmulated.ino.
Typedef Documentation
ControllerT
typedef WS2812<DATA_PIN, RGB> ControllerT
Definition at line 27 of file RGBWEmulated.ino.
Function Documentation
fillAndShow()
void fillAndShow (CRGB color)
Definition at line 38 of file RGBWEmulated.ino.
{
    for (int i = 0; i < NUM_LEDS; ++i) {
        leds[i] = color;
    }
    FastLED.show();
}
References FastLED, leds, NUM_LEDS, and CFastLED::show().
Referenced by loop().
loop()
void loop ()
Definition at line 46 of file RGBWEmulated.ino.
            {
    static size_t frame_count = 0;
    int frame_cycle = frame_count % 4;
    frame_count++;
    CRGB pixel;
    switch (frame_cycle) {
        case 0:
            pixel = CRGB::Red;
            break;
        case 1:
            pixel = CRGB::Green;
            break;
        case 2:
            pixel = CRGB::Blue;
            break;
        case 3:
            pixel = CRGB::White;
            break;
    }
    for (int i = -1; i < frame_cycle; ++i) {
        fillAndShow(pixel);
        delay(200);
        fillAndShow(CRGB::Black);
        delay(200);
    }
    delay(1000);
}
References CRGB::Black, CRGB::Blue, fillAndShow(), CRGB::Green, CRGB::Red, and CRGB::White.
setup()
void setup ()
Definition at line 30 of file RGBWEmulated.ino.
             {
    Serial.begin(115200);
    //FastLED.addLeds<WS2812, DATA_PIN, GRB>(leds, NUM_LEDS).setRgbw(RgbwDefault());
    FastLED.addLeds(&rgbwEmu, leds, NUM_LEDS);
    FastLED.setBrightness(128);  // Set global brightness to 50%
    delay(2000);  // If something ever goes wrong this delay will allow upload.
}
References CFastLED::addLeds(), FastLED, leds, NUM_LEDS, rgbwEmu, and CFastLED::setBrightness().
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 14 of file RGBWEmulated.ino.
Referenced by fillAndShow(), and setup().
rgbw
Rgbw rgbw
Initial value:
= Rgbw(
    kRGBWDefaultColorTemp,
    kRGBWExactColors,
    W3
)
Definition at line 21 of file RGBWEmulated.ino.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::RGBWEmulatedController(), PixelController< RGB_ORDER, LANES, MASK >::as_iterator(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), PixelControllerVtable< PixelControllerT >::loadAndScaleRGBW(), PixelIterator::set_rgbw(), and RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
rgbwEmu
RGBWEmulatedController< ControllerT, GRB > rgbwEmu(rgbw) (rgbw) static
Referenced by setup().