FastLED: FrameBufferBase Class Reference
FrameBufferBase Class Reference
Detailed Description
Definition at line 8 of file framebuffer.h.
#include <framebuffer.h>
Public Member Functions
FrameBufferBase (Color3i *array, int n_pixels)
virtual ~FrameBufferBase ()
void ApplyBlendAdd (const Color3i &color)
void ApplyBlendMultiply (const Color3i &color)
void ApplyBlendSubtract (const Color3i &color)
void FillColor (const Color3i &color)
Color3i * GetIterator (int i)
int length () const
void Set (int i, const Color3i &c)
void Set (int i, int length, const Color3i &color)
Protected Attributes
Color3i * color_array_
int n_color_array_
Constructor & Destructor Documentation
FrameBufferBase()
FrameBufferBase::FrameBufferBase (Color3i * array, int n_pixels)
Definition at line 10 of file framebuffer.cpp.
    : color_array_(array), n_color_array_(n_pixels) {}
~FrameBufferBase()
FrameBufferBase::~FrameBufferBase () virtual
Definition at line 13 of file framebuffer.cpp.
{}
Member Function Documentation
ApplyBlendAdd()
void FrameBufferBase::ApplyBlendAdd (const Color3i & color)
Definition at line 33 of file framebuffer.cpp.
{
  for (int i = 0; i < n_color_array_; ++i) {
    color_array_[i].Add(color);
  }
}
References Color3i::Add(), color_array_, and n_color_array_.
ApplyBlendMultiply()
void FrameBufferBase::ApplyBlendMultiply (const Color3i & color)
Definition at line 38 of file framebuffer.cpp.
{
  for (int i = 0; i < n_color_array_; ++i) {
    color_array_[i].Mul(color);
  }
}
References color_array_, Color3i::Mul(), and n_color_array_.
ApplyBlendSubtract()
void FrameBufferBase::ApplyBlendSubtract (const Color3i & color)
Definition at line 28 of file framebuffer.cpp.
{
  for (int i = 0; i < n_color_array_; ++i) {
    color_array_[i].Sub(color);
  }
}
References color_array_, n_color_array_, and Color3i::Sub().
FillColor()
void FrameBufferBase::FillColor (const Color3i & color)
Definition at line 23 of file framebuffer.cpp.
{
  for (int i = 0; i < n_color_array_; ++i) {
    color_array_[i] = color;
  }
}
References color_array_, and n_color_array_.
GetIterator()
Color3i * FrameBufferBase::GetIterator (int i)
Definition at line 43 of file framebuffer.cpp.
{
  return color_array_ + i;
}
References color_array_.
Referenced by LedRopeTCL::GetIterator().
length()
int FrameBufferBase::length () const
Definition at line 47 of file framebuffer.cpp.
{ return n_color_array_; }
References n_color_array_.
Referenced by LedRopeTCL::DrawRepeat(), LedRopeTCL::length(), Set(), and LedRopeTCL::set_draw_offset().
Set() [1/2]
void FrameBufferBase::Set (int i, const Color3i & c)
Definition at line 15 of file framebuffer.cpp.
{
  color_array_[i] = c;
}
References color_array_.
Referenced by Set(), and LedRopeTCL::Set().
Set() [2/2]
void FrameBufferBase::Set (int i, int length, const Color3i & color)
Definition at line 18 of file framebuffer.cpp.
{
  for (int j = 0; j < length; ++j) {
    Set(i + j, color);
  }
}
References length(), and Set().
Member Data Documentation
color_array_
Color3i* FrameBufferBase::color_array_ protected
Definition at line 25 of file framebuffer.h.
Referenced by FrameBuffer::~FrameBuffer(), ApplyBlendAdd(), ApplyBlendMultiply(), ApplyBlendSubtract(), FillColor(), GetIterator(), and Set().
n_color_array_
int FrameBufferBase::n_color_array_ protected
Definition at line 26 of file framebuffer.h.
Referenced by FrameBuffer::~FrameBuffer(), ApplyBlendAdd(), ApplyBlendMultiply(), ApplyBlendSubtract(), FillColor(), and length().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/framebuffer.h
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/framebuffer.cpp