FastLED: LedRopeTCL Class Reference
LedRopeTCL Class Reference
Detailed Description
Definition at line 45 of file LedRopeTCL.h.
#include <LedRopeTCL.h>
Public Member Functions
LedRopeTCL (int n_pixels)
virtual ~LedRopeTCL ()
void Draw ()
void DrawRepeat (const int *value_array, int array_length)
void DrawSequentialRepeat (int repeat)
Color3i * GetIterator (int i)
int length () const
void RawBeginDraw ()
void RawCommitDraw ()
void RawDrawPixel (const Color3i &c)
void RawDrawPixel (uint8_t r, uint8_t g, uint8_t b)
void RawDrawPixels (const Color3i &c, int n)
virtual void Set (int i, const Color3i &c)
void set_draw_offset (int val)
Public Member Functions inherited from LedRopeInterface
virtual ~LedRopeInterface ()
virtual void Set (int i, int length, const Color3i &color)
Protected Member Functions
void PreDrawSetup ()
Protected Attributes
bool controller_added_ = false
int draw_offset_ = 0
FrameBuffer frame_buffer_
bool lazy_initialized_
fl::HeapVector< CRGB > led_buffer_
fl::ScreenMap mScreenMap
Constructor & Destructor Documentation
LedRopeTCL()
LedRopeTCL::LedRopeTCL (int n_pixels)
Definition at line 111 of file LedRopeTCL.cpp.
    : draw_offset_(0), lazy_initialized_(false), frame_buffer_(n_pixels) {
  mScreenMap = init_screenmap();
  led_buffer_.reserve(mScreenMap.getLength());
}
References fl::ScreenMap::getLength(), led_buffer_, mScreenMap, and fl::HeapVector< T >::reserve().
~LedRopeTCL()
LedRopeTCL::~LedRopeTCL () virtual
Definition at line 118 of file LedRopeTCL.cpp.
{
}
Member Function Documentation
Draw()
void LedRopeTCL::Draw ()
Definition at line 122 of file LedRopeTCL.cpp.
                      {
  RawBeginDraw();
  const Color3i* begin = GetIterator(0);
  const Color3i* middle = GetIterator(draw_offset_);
  const Color3i* end = GetIterator(length() - 1);
  for (const Color3i* it = middle; it != end; ++it) {
    RawDrawPixel(*it);
  }
  for (const Color3i* it = begin; it != middle; ++it) {
    RawDrawPixel(*it);
  }
  RawCommitDraw();
}
References draw_offset_, GetIterator(), length(), RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().
DrawRepeat()
void LedRopeTCL::DrawRepeat (const int * value_array, int array_length) virtual
Implements LedRopeInterface.
Definition at line 159 of file LedRopeTCL.cpp.
{
  RawBeginDraw();
  // Make sure that the number of colors to repeat does not exceed the length
  // of the rope.
  const int len = min(array_length, frame_buffer_.length());
  for (int i = 0; i < len; ++i) {
     const Color3i* cur_color = GetIterator(i);  // Current color.
     const int repeat_count = value_array[i];
     // Repeatedly send the same color down the led rope.
     for (int k = 0; k < repeat_count; ++k) {
       RawDrawPixel(cur_color->r_, cur_color->g_, cur_color->b_);
     }
  }
  // Finish the drawing.
  RawCommitDraw();
}
References Color3i::b_, frame_buffer_, Color3i::g_, GetIterator(), FrameBufferBase::length(), Color3i::r_, RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().
DrawSequentialRepeat()
void LedRopeTCL::DrawSequentialRepeat (int repeat) virtual
Implements LedRopeInterface.
Definition at line 139 of file LedRopeTCL.cpp.
{
  RawBeginDraw();
  const Color3i* begin = GetIterator(0);
  const Color3i* middle = GetIterator(draw_offset_);
  const Color3i* end = GetIterator(length());
  for (const Color3i* it = middle; it != end; ++it) {
    for (int i = 0; i < repeat; ++i) {
      RawDrawPixel(it->r_, it->g_, it->b_);
    }
  }
  for (const Color3i* it = begin; it != middle; ++it) {
    for (int i = 0; i < repeat; ++i) {
      RawDrawPixel(it->r_, it->g_, it->b_);
    }
  }
  RawCommitDraw();
}
References draw_offset_, GetIterator(), length(), RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().
GetIterator()
Color3i * LedRopeTCL::GetIterator (int i) inline virtual
Implements LedRopeInterface.
Definition at line 59 of file LedRopeTCL.h.
{
    return frame_buffer_.GetIterator(i);
  }
References frame_buffer_, and FrameBufferBase::GetIterator().
Referenced by Draw(), DrawRepeat(), and DrawSequentialRepeat().
length()
int LedRopeTCL::length () const inline virtual
Implements LedRopeInterface.
Definition at line 63 of file LedRopeTCL.h.
{ return frame_buffer_.length(); }
References frame_buffer_, and FrameBufferBase::length().
Referenced by Draw(), and DrawSequentialRepeat().
PreDrawSetup()
void LedRopeTCL::PreDrawSetup () protected
Definition at line 54 of file LedRopeTCL.cpp.
{
  if (!lazy_initialized_) {
    // This used to do something, now it does nothing.
    lazy_initialized_ = true;
  }
}
References lazy_initialized_.
Referenced by RawBeginDraw().
RawBeginDraw()
void LedRopeTCL::RawBeginDraw () virtual
Implements LedRopeInterface.
Definition at line 62 of file LedRopeTCL.cpp.
{
  PreDrawSetup();
  led_buffer_.clear();
}
References fl::HeapVector< T >::clear(), led_buffer_, and PreDrawSetup().
Referenced by Draw(), DrawRepeat(), and DrawSequentialRepeat().
RawCommitDraw()
void LedRopeTCL::RawCommitDraw () virtual
Implements LedRopeInterface.
Definition at line 100 of file LedRopeTCL.cpp.
{
  if (!controller_added_) {
    controller_added_ = true;
    CRGB* leds = led_buffer_.data();
    size_t n_leds = led_buffer_.size();
    FastLED.addLeds<APA102, PIN_DATA, PIN_CLOCK>(leds, n_leds).setScreenMap(mScreenMap);
  }
  FastLED.show();
}
References CFastLED::addLeds(), APA102, controller_added_, fl::HeapVector< T >::data(), FastLED, led_buffer_, leds, mScreenMap, PIN_CLOCK, PIN_DATA, CFastLED::show(), and fl::HeapVector< T >::size().
Referenced by Draw(), DrawRepeat(), and DrawSequentialRepeat().
RawDrawPixel() [1/2]
void LedRopeTCL::RawDrawPixel (const Color3i & c) virtual
Implements LedRopeInterface.
Definition at line 68 of file LedRopeTCL.cpp.
{
  RawDrawPixel(c.r_, c.g_, c.b_);
}
References Color3i::b_, Color3i::g_, Color3i::r_, and RawDrawPixel().
Referenced by Draw(), DrawRepeat(), DrawSequentialRepeat(), RawDrawPixel(), and RawDrawPixels().
RawDrawPixel() [2/2]
void LedRopeTCL::RawDrawPixel (uint8_t r, uint8_t g, uint8_t b) virtual
Implements LedRopeInterface.
Definition at line 73 of file LedRopeTCL.cpp.
{
  if (led_buffer_.size() >= mScreenMap.getLength()) {
    return;
  }
  if (buttonAllWhite.isPressed()) {
    r = 0xff;
    g = 0xff;
    b = 0xff;
  }
  CRGB c(r, g, b);
  led_buffer_.push_back(CRGB(r, g, b));
}
References fl::ScreenMap::getLength(), fl::UIButton::isPressed(), led_buffer_, mScreenMap, fl::HeapVector< T >::push_back(), and fl::HeapVector< T >::size().
RawDrawPixels()
void LedRopeTCL::RawDrawPixels (const Color3i & c, int n) virtual
Implements LedRopeInterface.
Definition at line 87 of file LedRopeTCL.cpp.
{
  for (int i = 0; i < n; ++i) {
    RawDrawPixel(c);
  }
}
References RawDrawPixel().
Set()
virtual void LedRopeTCL::Set (int i, const Color3i & c) inline virtual
Implements LedRopeInterface.
Definition at line 55 of file LedRopeTCL.h.
{
    frame_buffer_.Set(i, c);
  }
References frame_buffer_, and FrameBufferBase::Set().
set_draw_offset()
void LedRopeTCL::set_draw_offset (int val)
Definition at line 94 of file LedRopeTCL.cpp.
{
  draw_offset_ = constrain(val, 0, frame_buffer_.length());
}
References draw_offset_, frame_buffer_, and FrameBufferBase::length().
Member Data Documentation
controller_added_
bool LedRopeTCL::controller_added_ = false protected
Definition at line 76 of file LedRopeTCL.h.
Referenced by RawCommitDraw().
draw_offset_
int LedRopeTCL::draw_offset_ = 0 protected
Definition at line 73 of file LedRopeTCL.h.
Referenced by Draw(), DrawSequentialRepeat(), and set_draw_offset().
frame_buffer_
FrameBuffer LedRopeTCL::frame_buffer_ protected
Definition at line 75 of file LedRopeTCL.h.
Referenced by DrawRepeat(), GetIterator(), length(), Set(), and set_draw_offset().
lazy_initialized_
bool LedRopeTCL::lazy_initialized_ protected
Definition at line 74 of file LedRopeTCL.h.
Referenced by PreDrawSetup().
led_buffer_
fl::HeapVector<CRGB> LedRopeTCL::led_buffer_ protected
Definition at line 77 of file LedRopeTCL.h.
Referenced by LedRopeTCL(), RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().
mScreenMap
fl::ScreenMap LedRopeTCL::mScreenMap protected
Definition at line 78 of file LedRopeTCL.h.
Referenced by LedRopeTCL(), RawCommitDraw(), and RawDrawPixel().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/arduino/LedRopeTCL.h
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/arduino/LedRopeTCL.cpp