FastLED: fl::StrN< SIZE > Class Template Reference
fl::StrN< SIZE > Class Template Reference
Detailed Description
template<size_t SIZE = 64>
class fl::StrN< SIZE >
Definition at line 79 of file str.h.
#include <str.h>
Public Member Functions
StrN ()=default
StrN (const char *str)
template<int N>
StrN (const char(&str)[N])
StrN (const StrN &other)
template<size_t M>
StrN (const StrN< M > &other)
~StrN ()
const char * c_str () const
char * c_str_mutable ()
size_t capacity () const
void clear (bool freeMemory=false)
void copy (const char *str)
void copy (const char *str, size_t len)
template<size_t M>
void copy (const StrN< M > &other)
bool empty () const
int16_t find (const char &value) const
size_t length () const
bool operator!= (const StrN &other) const
bool operator< (const StrN &other) const
template<size_t M>
bool operator< (const StrN< M > &other) const
template<int N>
StrN & operator= (const char(&str)[N])
StrN & operator= (const StrN &other)
template<size_t M>
StrN & operator= (const StrN< M > &other)
bool operator== (const StrN &other) const
char & operator[] (size_t index)
const char & operator[] (size_t index) const
void reserve (size_t newCapacity)
size_t size () const
StrN substring (size_t start, size_t end) const
float toFloat () const
StrN trim () const
size_t write (char c)
size_t write (const char *str, size_t n)
size_t write (const int32_t &val)
size_t write (const int8_t val)
size_t write (const uint16_t &n)
size_t write (const uint32_t &val)
size_t write (const uint8_t *data, size_t n)
size_t write (uint8_t c)
Private Attributes
StringHolderPtr mData
StringHolderPtr mHeapData
char mInlineData [SIZE] = {0}
size_t mLength = 0
Constructor & Destructor Documentation
StrN() [1/5]
template<size_t SIZE = 64> fl::StrN< SIZE >::StrN () default
Referenced by fl::StrN< SIZE >::substring().
StrN() [2/5]
template<size_t SIZE = 64> template<size_t M> fl::StrN< SIZE >::StrN (const StrN< M > & other) inline
Definition at line 90 of file str.h.
{ copy(other); }
References fl::StrN< SIZE >::copy().
StrN() [3/5]
template<size_t SIZE = 64> fl::StrN< SIZE >::StrN (const char * str) inline
Definition at line 91 of file str.h.
{
        size_t len = strlen(str);
        mLength = len;  // Length is without null terminator
        if (len + 1 <= SIZE) {  // Check capacity including null
            memcpy(mInlineData, str, len + 1);  // Copy including null
            mHeapData.reset();
        } else {
            mHeapData = StringHolderPtr::New(str);
        }
    }
References fl::StrN< SIZE >::mHeapData, fl::StrN< SIZE >::mInlineData, and fl::StrN< SIZE >::mLength.
StrN() [4/5]
template<size_t SIZE = 64> fl::StrN< SIZE >::StrN (const StrN< SIZE > & other) inline
Definition at line 101 of file str.h.
{ copy(other); }
References fl::StrN< SIZE >::copy().
StrN() [5/5]
template<size_t SIZE = 64> template<int N> fl::StrN< SIZE >::StrN (const char(&) str[N]) inline
Definition at line 119 of file str.h.
{
        copy(str, N-1);  // Subtract 1 to not count null terminator
    }
References fl::StrN< SIZE >::copy().
~StrN()
template<size_t SIZE = 64> fl::StrN< SIZE >::~StrN () inline
Definition at line 242 of file str.h.
{}
Member Function Documentation
c_str()
template<size_t SIZE = 64> const char * fl::StrN< SIZE >::c_str () const inline
Definition at line 247 of file str.h.
{
        return mHeapData ? mHeapData->data() : mInlineData;
    }
References fl::StrN< SIZE >::mHeapData, and fl::StrN< SIZE >::mInlineData.
Referenced by fl::Str::append(), fl::StrStream::c_str(), fl::StrN< SIZE >::copy(), fl::Video::draw(), fl::Video::draw(), fl::StrN< SIZE >::find(), fl::Str::operator!=(), fl::StrN< SIZE >::operator!=(), fl::Str::operator<(), fl::StrN< SIZE >::operator<(), fl::StrN< SIZE >::operator<(), fl::Str::operator<=(), fl::Str::operator==(), fl::StrN< SIZE >::operator==(), fl::Str::operator>(), fl::Str::operator>=(), fl::StrN< SIZE >::operator[](), fl::ScreenMap::ParseJson(), fl::ScreenMap::ParseJson(), fl::parseJson(), fl::FileSystem::readJson(), fl::FileSystem::readScreenMap(), fl::FileSystem::readScreenMaps(), fl::StrN< SIZE >::reserve(), fl::StrN< SIZE >::substring(), fl::StrN< SIZE >::toFloat(), fl::StrN< SIZE >::trim(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), and fl::StrN< SIZE >::write().
c_str_mutable()
template<size_t SIZE = 64> char * fl::StrN< SIZE >::c_str_mutable () inline
Definition at line 251 of file str.h.
{
        return mHeapData ? mHeapData->data() : mInlineData;
    }
References fl::StrN< SIZE >::mHeapData, and fl::StrN< SIZE >::mInlineData.
Referenced by fl::StrN< SIZE >::operator[]().
capacity()
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::capacity () const inline
Definition at line 169 of file str.h.
{
        return mHeapData ? mHeapData->capacity() : SIZE;
    }
References fl::StrN< SIZE >::mHeapData.
clear()
template<size_t SIZE = 64> void fl::StrN< SIZE >::clear (bool freeMemory = false) inline
Definition at line 310 of file str.h.
{
        mLength = 0;
        if (freeMemory && mHeapData) {
            mHeapData.reset();
        }
    }
References fl::StrN< SIZE >::mHeapData, and fl::StrN< SIZE >::mLength.
Referenced by fl::StrStream::operator=(), fl::StrStream::operator=(), fl::StrStream::operator=(), and fl::StrStream::operator=().
copy() [1/3]
template<size_t SIZE = 64> void fl::StrN< SIZE >::copy (const char * str) inline
Definition at line 102 of file str.h.
{
        size_t len = strlen(str);
        mLength = len;
        if (len + 1 <= SIZE) {
            memcpy(mInlineData, str, len + 1);
            mHeapData.reset();
        } else {
            if (mHeapData && !mHeapData->isShared()) {
                // We are the sole owners of this data so we can modify it
                mHeapData->copy(str, len);
                return;
            }
            mHeapData.reset();
            mHeapData = StringHolderPtr::New(str);
        }
    }
References fl::StrN< SIZE >::mHeapData, fl::StrN< SIZE >::mInlineData, and fl::StrN< SIZE >::mLength.
Referenced by fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::operator=(), fl::StrN< SIZE >::operator=(), and fl::StrN< SIZE >::substring().
copy() [2/3]
template<size_t SIZE = 64> void fl::StrN< SIZE >::copy (const char * str, size_t len) inline
Definition at line 144 of file str.h.
{
        mLength = len;
        if (len + 1 <= SIZE) {
            memcpy(mInlineData, str, len + 1);
            mHeapData.reset();
        } else {
            mHeapData = StringHolderPtr::New(str, len);
        }
    }
References fl::StrN< SIZE >::mHeapData, fl::StrN< SIZE >::mInlineData, and fl::StrN< SIZE >::mLength.
copy() [3/3]
template<size_t SIZE = 64> template<size_t M> void fl::StrN< SIZE >::copy (const StrN< M > & other) inline
Definition at line 154 of file str.h.
{
        size_t len = other.size();
        if (len + 1 <= SIZE) {
            memcpy(mInlineData, other.c_str(), len + 1);
            mHeapData.reset();
        } else {
            if (other.mHeapData) {
                mHeapData = other.mHeapData;
            } else {
                mHeapData = StringHolderPtr::New(other.c_str());
            }
        }
        mLength = len;
    }
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::mHeapData, fl::StrN< SIZE >::mInlineData, fl::StrN< SIZE >::mLength, and fl::StrN< SIZE >::size().
empty()
template<size_t SIZE = 64> bool fl::StrN< SIZE >::empty () const inline
Definition at line 271 of file str.h.
{ return mLength == 0; }
References fl::StrN< SIZE >::mLength.
Referenced by fl::Video::draw(), and fl::Video::draw().
find()
template<size_t SIZE = 64> int16_t fl::StrN< SIZE >::find (const char & value) const inline
Definition at line 319 of file str.h.
{
        for (size_t i = 0; i < mLength; ++i) {
            if (c_str()[i] == value) {
                return i;
            }
        }
        return -1;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< SIZE >::mLength.
length()
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::length () const inline
Definition at line 246 of file str.h.
{ return size(); }
References fl::StrN< SIZE >::size().
operator!=()
template<size_t SIZE = 64> bool fl::StrN< SIZE >::operator!= (const StrN< SIZE > & other) const inline
Definition at line 140 of file str.h.
{
        return strcmp(c_str(), other.c_str()) != 0;
    }
References fl::StrN< SIZE >::c_str().
operator<() [1/2]
template<size_t SIZE = 64> bool fl::StrN< SIZE >::operator< (const StrN< SIZE > & other) const inline
Definition at line 276 of file str.h.
{
        return strcmp(c_str(), other.c_str()) < 0;
    }
References fl::StrN< SIZE >::c_str().
operator<() [2/2]
template<size_t SIZE = 64> template<size_t M> bool fl::StrN< SIZE >::operator< (const StrN< M > & other) const inline
Definition at line 280 of file str.h.
{
        return strcmp(c_str(), other.c_str()) < 0;
    }
References fl::StrN< SIZE >::c_str().
operator=() [1/3]
template<size_t SIZE = 64> template<int N> StrN & fl::StrN< SIZE >::operator= (const char(&) str[N]) inline
Definition at line 122 of file str.h.
{
        assign(str, N);
        return *this;
    }
operator=() [2/3]
template<size_t SIZE = 64> StrN & fl::StrN< SIZE >::operator= (const StrN< SIZE > & other) inline
Definition at line 126 of file str.h.
{
        copy(other);
        return *this;
    }
References fl::StrN< SIZE >::copy().
operator=() [3/3]
template<size_t SIZE = 64> template<size_t M> StrN & fl::StrN< SIZE >::operator= (const StrN< M > & other) inline
Definition at line 130 of file str.h.
{
        copy(other);
        return *this;
    }
References fl::StrN< SIZE >::copy().
operator==()
template<size_t SIZE = 64> bool fl::StrN< SIZE >::operator== (const StrN< SIZE > & other) const inline
Definition at line 136 of file str.h.
{
        return strcmp(c_str(), other.c_str()) == 0;
    }
References fl::StrN< SIZE >::c_str().
operator[]() [1/2]
template<size_t SIZE = 64> char & fl::StrN< SIZE >::operator[] (size_t index) inline
Definition at line 255 of file str.h.
{
        if (index >= mLength) {
            static char dummy = '\0';
            return dummy;
        }
        return c_str_mutable()[index];
    }
References fl::StrN< SIZE >::c_str_mutable(), and fl::StrN< SIZE >::mLength.
operator[]() [2/2]
template<size_t SIZE = 64> const char & fl::StrN< SIZE >::operator[] (size_t index) const inline
Definition at line 263 of file str.h.
{
        if (index >= mLength) {
            static char dummy = '\0';
            return dummy;
        }
        return c_str()[index];
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< SIZE >::mLength.
reserve()
template<size_t SIZE = 64> void fl::StrN< SIZE >::reserve (size_t newCapacity) inline
Definition at line 284 of file str.h.
{
        // If capacity is less than current length, do nothing
        if (newCapacity <= mLength) {
            return;
        }
        // If new capacity fits in inline buffer, no need to allocate
        if (newCapacity + 1 <= SIZE) {
            return;
        }
        // If we already have unshared heap data with sufficient capacity, do nothing
        if (mHeapData && !mHeapData->isShared() && mHeapData->hasCapacity(newCapacity)) {
            return;
        }
        // Need to allocate new storage
        StringHolderPtr newData = StringHolderPtr::New(newCapacity);
        if (newData) {
            // Copy existing content
            memcpy(newData->data(), c_str(), mLength);
            newData->data()[mLength] = '\0';
            mHeapData = newData;
        }
    }
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::mHeapData, and fl::StrN< SIZE >::mLength.
Referenced by fl::FileSystem::readText().
size()
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::size () const inline
Definition at line 245 of file str.h.
{ return mLength; }
References fl::StrN< SIZE >::mLength.
Referenced by fl::Str::append(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::length(), fl::FileSystem::readText(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), and fl::StrN< SIZE >::write().
substring()
template<size_t SIZE = 64> StrN fl::StrN< SIZE >::substring (size_t start, size_t end) const inline
Definition at line 328 of file str.h.
{
        if (start >= mLength) {
            return StrN();
        }
        if (end > mLength) {
            end = mLength;
        }
        if (start >= end) {
            return StrN();
        }
        StrN out;
        out.copy(c_str() + start, end - start);
        return out;
    }
References fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::copy(), and fl::StrN< SIZE >::mLength.
Referenced by fl::StrN< SIZE >::trim().
toFloat()
template<size_t SIZE = 64> float fl::StrN< SIZE >::toFloat () const inline
Definition at line 358 of file str.h.
{
        return StringFormatter::parseFloat(c_str(), mLength);
    }
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::mLength, and fl::StringFormatter::parseFloat().
trim()
template<size_t SIZE = 64> StrN fl::StrN< SIZE >::trim () const inline
Definition at line 345 of file str.h.
                      {
        StrN out;
        size_t start = 0;
        size_t end = mLength;
        while (start < mLength && StringFormatter::isSpace(c_str()[start])) {
            start++;
        }
        while (end > start && StringFormatter::isSpace(c_str()[end - 1])) {
            end--;
        }
        return substring(start, end);
    }
References fl::StrN< SIZE >::c_str(), fl::StringFormatter::isSpace(), fl::StrN< SIZE >::mLength, and fl::StrN< SIZE >::substring().
write() [1/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (char c) inline
Definition at line 210 of file str.h.
{ return write(&c, 1); }
References fl::StrN< SIZE >::write().
Referenced by fl::StrN< SIZE >::write().
write() [2/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const char * str, size_t n) inline
Definition at line 179 of file str.h.
{
        size_t newLen = mLength + n;
        if (mHeapData && !mHeapData->isShared()) {
            if (!mHeapData->hasCapacity(newLen)) {
                size_t grow_length = MAX(3, newLen * 3 / 2);
                mHeapData->grow(grow_length); // Grow by 50%
            }
            memcpy(mHeapData->data() + mLength, str, n);
            mLength = newLen;
            mHeapData->data()[mLength] = '\0';
            return mLength;
        }
        if (newLen + 1 <= SIZE) {
            memcpy(mInlineData + mLength, str, n);
            mLength = newLen;
            mInlineData[mLength] = '\0';
            return mLength;
        }
        mHeapData.reset();
        StringHolderPtr newData = StringHolderPtr::New(newLen);
        if (newData) {
            memcpy(newData->data(), c_str(), mLength);
            memcpy(newData->data() + mLength, str, n);
            newData->data()[newLen] = '\0';
            mHeapData = newData;
            mLength = newLen;
        }
        mHeapData = newData;
        return mLength;
    }
References fl::StrN< SIZE >::c_str(), MAX, fl::StrN< SIZE >::mHeapData, fl::StrN< SIZE >::mInlineData, and fl::StrN< SIZE >::mLength.
write() [3/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const int32_t & val) inline
Definition at line 229 of file str.h.
{
        StrN<64> dst;
        StringFormatter::append(val, &dst); // Inlined size should suffice
        return write(dst.c_str(), dst.size());
    }
References fl::StringFormatter::append(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::size(), and fl::StrN< SIZE >::write().
write() [4/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const int8_t val) inline
Definition at line 235 of file str.h.
{
        StrN<64> dst;
        StringFormatter::append(int16_t(val), &dst); // Inlined size should suffice
        return write(dst.c_str(), dst.size());
    }
References fl::StringFormatter::append(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::size(), and fl::StrN< SIZE >::write().
write() [5/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const uint16_t & n) inline
Definition at line 217 of file str.h.
{
        StrN<64> dst;
        StringFormatter::append(n, &dst); // Inlined size should suffice
        return write(dst.c_str(), dst.size());
    }
References fl::StringFormatter::append(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::size(), and fl::StrN< SIZE >::write().
write() [6/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const uint32_t & val) inline
Definition at line 223 of file str.h.
{
        StrN<64> dst;
        StringFormatter::append(val, &dst); // Inlined size should suffice
        return write(dst.c_str(), dst.size());
    }
References fl::StringFormatter::append(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::size(), and fl::StrN< SIZE >::write().
write() [7/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const uint8_t * data, size_t n) inline
Definition at line 174 of file str.h.
{
        const char *str = reinterpret_cast<const char *>(data);
        return write(str, n);
    }
References fl::StrN< SIZE >::write().
Referenced by fl::StringFormatter::append(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), and fl::StrN< SIZE >::write().
write() [8/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (uint8_t c) inline
Definition at line 212 of file str.h.
{
        const char *str = reinterpret_cast<const char *>(&c);
        return write(str, 1);
    }
References fl::StrN< SIZE >::write().
Member Data Documentation
mData
template<size_t SIZE = 64> StringHolderPtr fl::StrN< SIZE >::mData private
Definition at line 365 of file str.h.
mHeapData
template<size_t SIZE = 64> StringHolderPtr fl::StrN< SIZE >::mHeapData private
Definition at line 83 of file str.h.
Referenced by fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::c_str_mutable(), fl::StrN< SIZE >::capacity(), fl::StrN< SIZE >::clear(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::reserve(), and fl::StrN< SIZE >::write().
mInlineData
template<size_t SIZE = 64> char fl::StrN< SIZE >::mInlineData[SIZE] = {0} private
Definition at line 82 of file str.h.
{0};
Referenced by fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::c_str_mutable(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), and fl::StrN< SIZE >::write().
mLength
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::mLength = 0 private
Definition at line 81 of file str.h.
Referenced by fl::StrN< SIZE >::StrN(), fl::StrN< SIZE >::clear(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::copy(), fl::StrN< SIZE >::empty(), fl::StrN< SIZE >::find(), fl::StrN< SIZE >::operator[](), fl::StrN< SIZE >::operator[](), fl::StrN< SIZE >::reserve(), fl::StrN< SIZE >::size(), fl::StrN< SIZE >::substring(), fl::StrN< SIZE >::toFloat(), fl::StrN< SIZE >::trim(), and fl::StrN< SIZE >::write().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/str.h