FastLED: Color Fade Functions
Color Fade Functions
Color Utility Functions
Detailed Description
Functions for fading LED arrays
Functions
void fade_raw (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
void fade_video (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
void fadeLightBy (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
void fadeToBlackBy (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
void fadeUsingColor (CRGB *leds, uint16_t numLeds, const CRGB &colormask)
Reduce the brightness of an array of pixels as thought it were seen through a transparent filter with the specified color.
void nscale8 (CRGB *leds, uint16_t num_leds, uint8_t scale)
Scale the brightness of an array of pixels all at once.
void nscale8_video (CRGB *leds, uint16_t num_leds, uint8_t scale)
Scale the brightness of an array of pixels all at once.
Function Documentation
fade_raw()
void fade_raw (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
This function will eventually fade all the way to black.
Parameters
leds a pointer to the LED array to fade
num_leds the number of LEDs to fade
fadeBy how much to fade each LED
Definition at line 275 of file colorutils.cpp.
{
    nscale8( leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8().
fade_video()
void fade_video (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
Guaranteed to never fade all the way to black.
Parameters
leds a pointer to the LED array to fade
num_leds the number of LEDs to fade
fadeBy how much to fade each LED
Definition at line 259 of file colorutils.cpp.
{
    nscale8_video( leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8_video().
fadeLightBy()
void fadeLightBy (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
Guaranteed to never fade all the way to black.
Parameters
leds a pointer to the LED array to fade
num_leds the number of LEDs to fade
fadeBy how much to fade each LED
Definition at line 264 of file colorutils.cpp.
{
    nscale8_video( leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8_video().
fadeToBlackBy()
void fadeToBlackBy (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Reduce the brightness of an array of pixels all at once.
This function will eventually fade all the way to black.
Parameters
leds a pointer to the LED array to fade
num_leds the number of LEDs to fade
fadeBy how much to fade each LED
Definition at line 270 of file colorutils.cpp.
{
    nscale8( leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8().
Referenced by confetti(), fl::DemoReel100::confetti(), fl::DemoReel100::juggle(), juggle(), loop(), fl::DemoReel100::sinelon(), and sinelon().
fadeUsingColor()
void fadeUsingColor (CRGB * leds, uint16_t numLeds, const CRGB & colormask)
Reduce the brightness of an array of pixels as thought it were seen through a transparent filter with the specified color.
For example, if the colormask if CRGB(200, 100, 50), then the pixels' red will be faded to 200/256ths, their green to 100/256ths, and their blue to 50/256ths. This particular example will give a "hot fade" look, with white fading to yellow, then red, then black. You can also use colormasks like CRGB::Blue to zero out the red and green elements, leaving blue (largely) the same.
Parameters
leds a pointer to the LED array to fade
numLeds the number of LEDs to fade
colormask the color mask to fade with
Definition at line 288 of file colorutils.cpp.
{
    uint8_t fr, fg, fb;
    fr = colormask.r;
    fg = colormask.g;
    fb = colormask.b;
    for( uint16_t i = 0; i < numLeds; ++i) {
        leds[i].r = scale8_LEAVING_R1_DIRTY( leds[i].r, fr);
        leds[i].g = scale8_LEAVING_R1_DIRTY( leds[i].g, fg);
        leds[i].b = scale8                 ( leds[i].b, fb);
    }
}
References leds, scale8(), and scale8_LEAVING_R1_DIRTY().
nscale8()
void nscale8 (CRGB * leds, uint16_t num_leds, uint8_t scale)
Scale the brightness of an array of pixels all at once.
This function will eventually fade all the way to black, even if "scale" is not zero.
Parameters
leds a pointer to the LED array to scale
num_leds the number of LEDs to scale
scale how much to scale each LED
Definition at line 281 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < num_leds; ++i) {
        leds[i].nscale8( scale);
    }
}
References leds, CRGB::nscale8(), and scale.
Referenced by fade_raw(), and fadeToBlackBy().
nscale8_video()
void nscale8_video (CRGB * leds, uint16_t num_leds, uint8_t scale)
Scale the brightness of an array of pixels all at once.
Guaranteed to never fade all the way to black.
Parameters
leds a pointer to the LED array to scale
num_leds the number of LEDs to scale
scale how much to scale each LED
Definition at line 252 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < num_leds; ++i) {
        leds[i].nscale8_video( scale);
    }
}
References leds, CRGB::nscale8_video(), and scale.
Referenced by fade_video(), and fadeLightBy().