FastLED: fl::LargeBlockAllocator< T > Class Template Reference
fl::LargeBlockAllocator< T > Class Template Reference
Detailed Description
template<typename T>
class fl::LargeBlockAllocator< T >
Definition at line 16 of file allocator.h.
#include <allocator.h>
Static Public Member Functions
static T * Alloc (size_t n)
static void Free (T *p)
Member Function Documentation
Alloc()
template<typename T > static T * fl::LargeBlockAllocator< T >::Alloc (size_t n) inline static
Definition at line 18 of file allocator.h.
{
        void* ptr = LargeBlockAllocate(sizeof(T) * n, true);
        return reinterpret_cast<T*>(ptr);
    }
References fl::LargeBlockAllocate().
Referenced by fl::LUT< T >::LUT(), and fl::RectangularDrawBuffer::onQueuingDone().
Free()
template<typename T > static void fl::LargeBlockAllocator< T >::Free (T * p) inline static
Definition at line 23 of file allocator.h.
{
        if (p == nullptr) {
            return;
        }
        LargeBlockDeallocate(p);
    }
References fl::LargeBlockDeallocate(), and p.
Referenced by fl::LUT< T >::~LUT(), and fl::RectangularDrawBuffer::onQueuingDone().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/allocator.h