FastLED: CFastLED Class Reference
CFastLED Class Reference
Detailed Description
High level controller interface for FastLED.
This class manages controllers, global settings, and trackings such as brightness and refresh rates, and provides access functions for driving led data to controllers via the show() / showColor() / clear() methods. This is instantiated as a global object with the name FastLED.
Definition at line 353 of file FastLED.h.
#include <FastLED.h>
Classes
struct ClockedChipsetHelper
Public Member Functions
CFastLED ()
void addListener (fl::EngineEvents::Listener *listener)
void clear (bool writeData=false)
Clear the leds, wiping the local array of data.
void clearData ()
Clear out the local data array.
int count ()
Get how many controllers have been registered.
void countFPS (int nFrames=25)
For debugging, this will keep track of time between calls to countFPS().
void delay (unsigned long ms)
Delay for the given number of milliseconds.
uint8_t getBrightness ()
Get the current global brightness setting.
uint16_t getFPS ()
Get the number of frames/second being written out.
CRGB * leds ()
Get a pointer to led data for the first controller.
CLEDController & operator[] (int x)
Get a reference to a registered controller.
void removeListener (fl::EngineEvents::Listener *listener)
void setBrightness (uint8_t scale)
Set the global brightness scaling.
void setCorrection (const struct CRGB &correction)
Set a global color correction.
void setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode.
void setMaxPowerInMilliWatts (uint32_t milliwatts)
Set the maximum power to be used, given in milliwatts.
void setMaxPowerInVoltsAndMilliamps (uint8_t volts, uint32_t milliamps)
Set the maximum power to be used, given in volts and milliamps.
void setMaxRefreshRate (uint16_t refresh, bool constrain=false)
Set the maximum refresh rate.
void setTemperature (const struct CRGB &temp)
Set a global color temperature.
void show ()
Update all our controllers with the current led colors.
void show (uint8_t scale)
Update all our controllers with the current led colors, using the passed in brightness.
void showColor (const struct CRGB &color)
Set all leds on all controllers to the given color.
void showColor (const struct CRGB &color, uint8_t scale)
Set all leds on all controllers to the given color/scale.
int size ()
Get the number of leds in the first controller.
Static Public Member Functions
static CLEDController & addLeds (CLEDController *pLed, struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a CLEDController instance to the world.
Private Attributes
uint16_t m_nFPS
tracking for current frames per second (FPS) value
uint32_t m_nMinMicros
minimum µs between frames, used for capping frame rates
uint32_t m_nPowerData
max power use parameter
power_func m_pPowerFunc
function for overriding brightness when using FastLED.show();
uint8_t m_Scale
the current global brightness scale setting
Adding SPI-based controllers
Add an SPI based CLEDController instance to the world.
There are two ways to call this method (as well as the other addLeds() variations). The first is with 2 arguments, in which case the arguments are a pointer to led data, and the number of leds used by this controller. The second is with 3 arguments, in which case the first argument is the same, the second argument is an offset into the CRGB data where this controller's CRGB data begins, and the third argument is the number of leds for this controller object.
Parameters
data base pointer to an array of CRGB data structures
nLedsOrOffset number of leds (3 argument version) or offset into the data array
nLedsIfOffset number of leds (4 argument version)
Template Parameters
CHIPSET the chipset type
DATA_PIN the optional data pin for the leds (if omitted, will default to the first hardware SPI MOSI pin)
CLOCK_PIN the optional clock pin for the leds (if omitted, will default to the first hardware SPI clock pin)
RGB_ORDER the rgb ordering for the leds (e.g. what order red, green, and blue data is written out in)
SPI_DATA_RATE the data rate to drive the SPI clock at, defined using DATA_RATE_MHZ or DATA_RATE_KHZ macros
Returns
a reference to the added controller
_FL_MAP_CLOCKED_CHIPSET (LPD6803, LPD6803Controller) _FL_MAP_CLOCKED_CHIPSET(LPD8806
LPD8806Controller _FL_MAP_CLOCKED_CHIPSET (WS2801, WS2801Controller) _FL_MAP_CLOCKED_CHIPSET(WS2803
LPD8806Controller WS2803Controller _FL_MAP_CLOCKED_CHIPSET (SM16716, SM16716Controller) _FL_MAP_CLOCKED_CHIPSET(P9813
LPD8806Controller WS2803Controller P9813Controller _FL_MAP_CLOCKED_CHIPSET (DOTSTAR, APA102Controller) _FL_MAP_CLOCKED_CHIPSET(APA102
LPD8806Controller WS2803Controller P9813Controller APA102Controller _FL_MAP_CLOCKED_CHIPSET (DOTSTARHD, APA102ControllerHD) _FL_MAP_CLOCKED_CHIPSET(APA102HD
LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD _FL_MAP_CLOCKED_CHIPSET (HD107, APA102Controller) _FL_MAP_CLOCKED_CHIPSET(HD107HD
LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD APA102ControllerHD _FL_MAP_CLOCKED_CHIPSET (SK9822, SK9822Controller) _FL_MAP_CLOCKED_CHIPSET(SK9822HD
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER, uint32_t SPI_DATA_RATE>
LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD APA102ControllerHD SK9822ControllerHD CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add an SPI based CLEDController instance to the world.
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER>
CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add an SPI based CLEDController instance to the world.
Adding 3-wire led controllers
Add a clockless (aka 3-wire, also DMX) based CLEDController instance to the world.
There are two ways to call this method (as well as the other addLeds() variations). The first is with 2 arguments, in which case the arguments are a pointer to led data, and the number of leds used by this controller. The second is with 3 arguments, in which case the first argument is the same, the second argument is an offset into the CRGB data where this controller's CRGB data begins, and the third argument is the number of leds for this controller object.
This method also takes 2 to 3 template parameters for identifying the specific chipset, data pin, RGB ordering, and SPI data rate
Parameters
data base pointer to an array of CRGB data structures
nLedsOrOffset number of leds (3 argument version) or offset into the data array
nLedsIfOffset number of leds (4 argument version)
Template Parameters
CHIPSET the chipset type (required)
DATA_PIN the data pin for the leds (required)
RGB_ORDER the rgb ordering for the leds (e.g. what order red, green, and blue data is written out in)
Returns
a reference to the added controller
template<template< uint8_t DATA_PIN, EOrder RGB_ORDER > class CHIPSET, uint8_t DATA_PIN, EOrder RGB_ORDER>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a clockless based CLEDController instance to the world.
template<template< uint8_t DATA_PIN, EOrder RGB_ORDER > class CHIPSET, uint8_t DATA_PIN>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a clockless based CLEDController instance to the world.
template<template< uint8_t DATA_PIN > class CHIPSET, uint8_t DATA_PIN>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a clockless based CLEDController instance to the world.
Adding 3rd party library controllers
Add a 3rd party library based CLEDController instance to the world.
There are two ways to call this method (as well as the other addLeds() variations). The first is with 2 arguments, in which case the arguments are a pointer to led data, and the number of leds used by this controller. The second is with 3 arguments, in which case the first argument is the same, the second argument is an offset into the CRGB data where this controller's CRGB data begins, and the third argument is the number of leds for this controller object. This class includes the SmartMatrix and OctoWS2811 based controllers
This method also takes 1 to 2 template parameters for identifying the specific chipset and RGB ordering.
Parameters
data base pointer to an array of CRGB data structures
nLedsOrOffset number of leds (3 argument version) or offset into the data array
nLedsIfOffset number of leds (4 argument version)
Template Parameters
CHIPSET the chipset type (required)
RGB_ORDER the rgb ordering for the leds (e.g. what order red, green, and blue data is written out in)
Returns
a reference to the added controller
template<template< EOrder RGB_ORDER > class CHIPSET, EOrder RGB_ORDER>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a 3rd party library based CLEDController instance to the world.
template<template< EOrder RGB_ORDER > class CHIPSET>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a 3rd party library based CLEDController instance to the world.
template<OWS2811 CHIPSET, EOrder RGB_ORDER>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a OCTOWS2811 based CLEDController instance to the world.
template<OWS2811 CHIPSET>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a OCTOWS2811 library based CLEDController instance to the world.
template<SWS2812 CHIPSET, int DATA_PIN, EOrder RGB_ORDER>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a WS2812Serial library based CLEDController instance to the world.
template<ESM CHIPSET>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a SmartMatrix library based CLEDController instance to the world.
Adding parallel output controllers
Add a block based CLEDController instance to the world.
There are two ways to call this method (as well as the other addLeds() variations). The first is with 2 arguments, in which case the arguments are a pointer to led data, and the number of leds used by this controller. The second is with 3 arguments, in which case the first argument is the same, the second argument is an offset into the CRGB data where this controller's CRGB data begins, and the third argument is the number of leds for this controller object.
This method also takes a 2 to 3 template parameters for identifying the specific chipset and rgb ordering RGB ordering, and SPI data rate
Parameters
data base pointer to an array of CRGB data structures
nLedsOrOffset number of leds (3 argument version) or offset into the data array
nLedsIfOffset number of leds (4 argument version)
Template Parameters
CHIPSET the chipset/port type (required)
NUM_LANES how many parallel lanes of output to write
RGB_ORDER the rgb ordering for the leds (e.g. what order red, green, and blue data is written out in)
Returns
a reference to the added controller
template<EBlockChipsets CHIPSET, int NUM_LANES, EOrder RGB_ORDER>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a block based parallel output CLEDController instance to the world.
template<EBlockChipsets CHIPSET, int NUM_LANES>
static CLEDController & addLeds (struct CRGB *data, int nLedsOrOffset, int nLedsIfOffset=0)
Add a block based parallel output CLEDController instance to the world.
Constructor & Destructor Documentation
CFastLED()
CFastLED::CFastLED ()
Definition at line 74 of file FastLED.cpp.
                   {
    // clear out the array of led controllers
    // m_nControllers = 0;
    m_Scale = 255;
    m_nFPS = 0;
    m_pPowerFunc = NULL;
    m_nPowerData = 0xFFFFFFFF;
    m_nMinMicros = 0;
}
References m_nFPS, m_nMinMicros, m_nPowerData, m_pPowerFunc, and m_Scale.
Member Function Documentation
_FL_MAP_CLOCKED_CHIPSET() [1/7]
LPD8806Controller WS2803Controller P9813Controller CFastLED::_FL_MAP_CLOCKED_CHIPSET (DOTSTAR , APA102Controller)
_FL_MAP_CLOCKED_CHIPSET() [2/7]
LPD8806Controller WS2803Controller P9813Controller APA102Controller CFastLED::_FL_MAP_CLOCKED_CHIPSET (DOTSTARHD , APA102ControllerHD)
_FL_MAP_CLOCKED_CHIPSET() [3/7]
LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD CFastLED::_FL_MAP_CLOCKED_CHIPSET (HD107 , APA102Controller)
_FL_MAP_CLOCKED_CHIPSET() [4/7]
CFastLED::_FL_MAP_CLOCKED_CHIPSET (LPD6803 , LPD6803Controller)
_FL_MAP_CLOCKED_CHIPSET() [5/7]
LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD APA102ControllerHD CFastLED::_FL_MAP_CLOCKED_CHIPSET (SK9822 , SK9822Controller)
_FL_MAP_CLOCKED_CHIPSET() [6/7]
LPD8806Controller WS2803Controller CFastLED::_FL_MAP_CLOCKED_CHIPSET (SM16716 , SM16716Controller)
_FL_MAP_CLOCKED_CHIPSET() [7/7]
LPD8806Controller CFastLED::_FL_MAP_CLOCKED_CHIPSET (WS2801 , WS2801Controller)
addLeds() [1/15]
CLEDController & CFastLED::addLeds (CLEDController * pLed, struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) static
Add a CLEDController instance to the world.
Exposed to the public to allow people to implement their own CLEDController objects or instances. There are two ways to call this method (as well as the other addLeds() variations). The first is with 3 arguments, in which case the arguments are the controller, a pointer to led data, and the number of leds used by this controller. The second is with 4 arguments, in which case the first two arguments are the same, the third argument is an offset into the CRGB data where this controller's CRGB data begins, and the fourth argument is the number of leds for this controller object.
Parameters
pLed the led controller being added
data base pointer to an array of CRGB data structures
nLedsOrOffset number of leds (3 argument version) or offset into the data array
nLedsIfOffset number of leds (4 argument version)
Returns
a reference to the added controller
Examples
ArrayOfLedArrays.ino, Blink.ino, BlinkParallel.ino, ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FirstLight.ino, FxEngine.ino, MirroringSample.ino, MultiArrays.ino, MultipleStripsInOneArray.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, OctoWS2811Demo.ino, PJRCSpectrumAnalyzer.ino, Pacifica.ino, ParallelOutputDemo.ino, Pride2015.ino, RGBSetDemo.ino, SmartMatrix.ino, TwinkleFox.ino, WS2816.ino, and XYMatrix.ino.
Definition at line 92 of file FastLED.cpp.
{
    int nOffset = (nLedsIfOffset > 0) ? nLedsOrOffset : 0;
    int nLeds = (nLedsIfOffset > 0) ? nLedsIfOffset : nLedsOrOffset;
    pLed->init();
    pLed->setLeds(data + nOffset, nLeds);
    FastLED.setMaxRefreshRate(pLed->getMaxRefreshRate(),true);
    fl::EngineEvents::onStripAdded(pLed, nLedsOrOffset - nOffset);
    return *pLed;
}
References FastLED, CLEDController::getMaxRefreshRate(), CLEDController::init(), fl::EngineEvents::onStripAdded(), CLEDController::setLeds(), and setMaxRefreshRate().
Referenced by addLeds(), LedRopeTCL::RawCommitDraw(), setup(), and setup_i2s_using_fastled_api().
addLeds() [2/15]
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER, uint32_t SPI_DATA_RATE> LPD8806Controller WS2803Controller P9813Controller APA102Controller APA102ControllerHD APA102ControllerHD SK9822ControllerHD CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline
Add an SPI based CLEDController instance to the world.
Definition at line 453 of file FastLED.h.
{
        // Instantiate the controller using ClockedChipsetHelper
        typedef ClockedChipsetHelper<CHIPSET, DATA_PIN, CLOCK_PIN> CHIP;
        typedef typename CHIP::template CONTROLLER_CLASS_WITH_ORDER_AND_FREQ<RGB_ORDER, SPI_DATA_RATE>::ControllerType ControllerTypeWithFreq;
        static_assert(CHIP::IS_VALID, "Unsupported chipset");
        static ControllerTypeWithFreq c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds().
addLeds() [3/15]
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add an SPI based CLEDController instance to the world.
Definition at line 463 of file FastLED.h.
{
        typedef ClockedChipsetHelper<CHIPSET, DATA_PIN, CLOCK_PIN> CHIP;
        typedef typename CHIP::ControllerType ControllerType;
        static_assert(CHIP::IS_VALID, "Unsupported chipset");
        static ControllerType c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds().
addLeds() [4/15]
template<ESPIChipsets CHIPSET, uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER> CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline
Definition at line 474 of file FastLED.h.
{
        typedef ClockedChipsetHelper<CHIPSET, DATA_PIN, CLOCK_PIN> CHIP;
        static_assert(CHIP::IS_VALID, "Unsupported chipset");
        typedef typename CHIP::template CONTROLLER_CLASS_WITH_ORDER<RGB_ORDER>::ControllerType ControllerTypeWithOrder;
        static ControllerTypeWithOrder c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds().
addLeds() [5/15]
template<template< uint8_t DATA_PIN, EOrder RGB_ORDER > class CHIPSET, uint8_t DATA_PIN, EOrder RGB_ORDER> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a clockless based CLEDController instance to the world.
Definition at line 523 of file FastLED.h.
{
        static CHIPSET<DATA_PIN, RGB_ORDER> c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and CHIPSET.
addLeds() [6/15]
template<template< uint8_t DATA_PIN, EOrder RGB_ORDER > class CHIPSET, uint8_t DATA_PIN> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a clockless based CLEDController instance to the world.
Definition at line 530 of file FastLED.h.
{
        static CHIPSET<DATA_PIN, RGB> c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and CHIPSET.
addLeds() [7/15]
template<template< uint8_t DATA_PIN > class CHIPSET, uint8_t DATA_PIN> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a clockless based CLEDController instance to the world.
Definition at line 537 of file FastLED.h.
{
        static CHIPSET<DATA_PIN> c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and CHIPSET.
addLeds() [8/15]
template<template< EOrder RGB_ORDER > class CHIPSET, EOrder RGB_ORDER> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a 3rd party library based CLEDController instance to the world.
Definition at line 585 of file FastLED.h.
{
        static CHIPSET<RGB_ORDER> c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and CHIPSET.
addLeds() [9/15]
template<template< EOrder RGB_ORDER > class CHIPSET> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a 3rd party library based CLEDController instance to the world.
Definition at line 592 of file FastLED.h.
{
        static CHIPSET<RGB> c;
        return addLeds(&c, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and CHIPSET.
addLeds() [10/15]
template<OWS2811 CHIPSET, EOrder RGB_ORDER> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a OCTOWS2811 based CLEDController instance to the world.
See also
https://www.pjrc.com/teensy/td_libs_OctoWS2811.html
https://github.com/PaulStoffregen/OctoWS2811
Definition at line 602 of file FastLED.h.
    {
        switch(CHIPSET) {
            case OCTOWS2811: { static COctoWS2811Controller<RGB_ORDER,WS2811_800kHz> controller; return addLeds(&controller, data, nLedsOrOffset, nLedsIfOffset); }
            case OCTOWS2811_400: { static COctoWS2811Controller<RGB_ORDER,WS2811_400kHz> controller; return addLeds(&controller, data, nLedsOrOffset, nLedsIfOffset); }
#ifdef WS2813_800kHz
      case OCTOWS2813: { static COctoWS2811Controller<RGB_ORDER,WS2813_800kHz> controller; return addLeds(&controller, data, nLedsOrOffset, nLedsIfOffset); }
#endif
        }
    }
References addLeds(), CHIPSET, controller, OCTOWS2811, OCTOWS2811_400, and OCTOWS2813.
addLeds() [11/15]
template<OWS2811 CHIPSET> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a OCTOWS2811 library based CLEDController instance to the world.
See also
https://www.pjrc.com/teensy/td_libs_OctoWS2811.html
https://github.com/PaulStoffregen/OctoWS2811
Definition at line 617 of file FastLED.h.
    {
        return addLeds<CHIPSET,GRB>(data,nLedsOrOffset,nLedsIfOffset);
    }
References addLeds().
addLeds() [12/15]
template<SWS2812 CHIPSET, int DATA_PIN, EOrder RGB_ORDER> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a WS2812Serial library based CLEDController instance to the world.
See also
https://www.pjrc.com/non-blocking-ws2812-led-library/
https://github.com/PaulStoffregen/WS2812Serial
Definition at line 629 of file FastLED.h.
    {
        static CWS2812SerialController<DATA_PIN,RGB_ORDER> controller;
        return addLeds(&controller, data, nLedsOrOffset, nLedsIfOffset);
    }
References addLeds(), and controller.
addLeds() [13/15]
template<ESM CHIPSET> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a SmartMatrix library based CLEDController instance to the world.
See also
https://github.com/pixelmatix/SmartMatrix
Definition at line 640 of file FastLED.h.
    {
        switch(CHIPSET) {
            case SMART_MATRIX: { static CSmartMatrixController controller; return addLeds(&controller, data, nLedsOrOffset, nLedsIfOffset); }
        }
    }
References addLeds(), CHIPSET, controller, and SMART_MATRIX.
addLeds() [14/15]
template<EBlockChipsets CHIPSET, int NUM_LANES, EOrder RGB_ORDER> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a block based parallel output CLEDController instance to the world.
Definition at line 675 of file FastLED.h.
{
        switch(CHIPSET) {
        #ifdef PORTA_FIRST_PIN
                case WS2811_PORTA: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTA_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case WS2811_400_PORTA: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTA_FIRST_PIN, NS(800), NS(800), NS(900), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        case WS2813_PORTA: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTA_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
                case TM1803_PORTA: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTA_FIRST_PIN, NS(700), NS(1100), NS(700), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case UCS1903_PORTA: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTA_FIRST_PIN, NS(500), NS(1500), NS(500), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        #endif
        #ifdef PORTB_FIRST_PIN
                case WS2811_PORTB: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTB_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case WS2811_400_PORTB: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTB_FIRST_PIN, NS(800), NS(800), NS(900), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        case WS2813_PORTB: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTB_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
                case TM1803_PORTB: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTB_FIRST_PIN, NS(700), NS(1100), NS(700), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case UCS1903_PORTB: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTB_FIRST_PIN, NS(500), NS(1500), NS(500), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        #endif
        #ifdef PORTC_FIRST_PIN
                case WS2811_PORTC: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTC_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case WS2811_400_PORTC: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTC_FIRST_PIN, NS(800), NS(800), NS(900), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        case WS2813_PORTC: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTC_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
                case TM1803_PORTC: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTC_FIRST_PIN, NS(700), NS(1100), NS(700), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case UCS1903_PORTC: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTC_FIRST_PIN, NS(500), NS(1500), NS(500), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        #endif
        #ifdef PORTD_FIRST_PIN
                case WS2811_PORTD: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTD_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case WS2811_400_PORTD: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTD_FIRST_PIN, NS(800), NS(800), NS(900), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        case WS2813_PORTD: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTD_FIRST_PIN, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
                case TM1803_PORTD: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTD_FIRST_PIN, NS(700), NS(1100), NS(700), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case UCS1903_PORTD: return addLeds(new InlineBlockClocklessController<NUM_LANES, PORTD_FIRST_PIN, NS(500), NS(1500), NS(500), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        #endif
        #ifdef HAS_PORTDC
                case WS2811_PORTDC: return addLeds(new SixteenWayInlineBlockClocklessController<NUM_LANES,NS(320), NS(320), NS(640), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case WS2811_400_PORTDC: return addLeds(new SixteenWayInlineBlockClocklessController<NUM_LANES,NS(800), NS(800), NS(900), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        case WS2813_PORTDC: return addLeds(new SixteenWayInlineBlockClocklessController<NUM_LANES, NS(320), NS(320), NS(640), RGB_ORDER, 0, false, 300>(), data, nLedsOrOffset, nLedsIfOffset);
                case TM1803_PORTDC: return addLeds(new SixteenWayInlineBlockClocklessController<NUM_LANES, NS(700), NS(1100), NS(700), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
                case UCS1903_PORTDC: return addLeds(new SixteenWayInlineBlockClocklessController<NUM_LANES, NS(500), NS(1500), NS(500), RGB_ORDER>(), data, nLedsOrOffset, nLedsIfOffset);
        #endif
        }
    }
References addLeds(), CHIPSET, and NS.
addLeds() [15/15]
template<EBlockChipsets CHIPSET, int NUM_LANES> static CLEDController & CFastLED::addLeds (struct CRGB * data, int nLedsOrOffset, int nLedsIfOffset = 0) inline static
Add a block based parallel output CLEDController instance to the world.
Definition at line 717 of file FastLED.h.
{
        return addLeds<CHIPSET,NUM_LANES,GRB>(data,nLedsOrOffset,nLedsIfOffset);
    }
References addLeds().
addListener()
void CFastLED::addListener (fl::EngineEvents::Listener * listener) inline
Definition at line 366 of file FastLED.h.
{ fl::EngineEvents::addListener(listener); }
References fl::EngineEvents::addListener().
clear()
void CFastLED::clear (bool writeData = false)
Clear the leds, wiping the local array of data.
Optionally you can also send the cleared data to the LEDs.
Parameters
writeData whether or not to write out to the leds as well
Definition at line 219 of file FastLED.cpp.
{
    if(writeData) {
        showColor(CRGB(0,0,0), 0);
    }
    clearData();
}
References clearData(), and showColor().
clearData()
void CFastLED::clearData ()
Clear out the local data array.
Definition at line 226 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        pCur->clearLedDataInternal();
        pCur = pCur->next();
    }
}
References CLEDController::clearLedDataInternal(), CLEDController::head(), and CLEDController::next().
Referenced by clear().
count()
int CFastLED::count ()
Get how many controllers have been registered.
Returns
the number of controllers (strips) that have been added with addLeds()
Definition at line 155 of file FastLED.cpp.
                    {
    int x = 0;
    CLEDController *pCur = CLEDController::head();
    while( pCur) {
        ++x;
        pCur = pCur->next();
    }
    return x;
}
References CLEDController::head(), CLEDController::next(), and x.
countFPS()
void CFastLED::countFPS (int nFrames = 25)
For debugging, this will keep track of time between calls to countFPS().
Every nFrames calls, it will update an internal counter for the current FPS.
Todo
Make this a rolling counter
Parameters
nFrames how many frames to time for determining FPS
Definition at line 323 of file FastLED.cpp.
{
    static int br = 0;
    static uint32_t lastframe = 0; // millis();
    if(br++ >= nFrames) {
        uint32_t now = millis();
        now -= lastframe;
        if(now == 0) {
            now = 1; // prevent division by zero below
        }
        m_nFPS = (br * 1000) / now;
        br = 0;
        lastframe = millis();
    }
}
References m_nFPS.
Referenced by show(), and showColor().
delay()
void CFastLED::delay (unsigned long ms)
Delay for the given number of milliseconds.
Provided to allow the library to be used on platforms that don't have a delay function (to allow code to be more portable).
Note
This will call show() constantly to drive the dithering engine (and will call show() at least once).
Parameters
ms the number of milliseconds to pause for
Examples
ColorPalette.ino, ColorTemperature.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, OctoWS2811Demo.ino, and RGBSetDemo.ino.
Definition at line 234 of file FastLED.cpp.
{
    unsigned long start = millis();
        do {
#ifndef FASTLED_ACCURATE_CLOCK
        // make sure to allow at least one ms to pass to ensure the clock moves
        // forward
        ::delay(1);
#endif
        show();
        yield();
    }
    while((millis()-start) < ms);
}
References delay(), and show().
Referenced by delay(), delay_at_max_brightness_for_power(), and loop().
getBrightness()
uint8_t CFastLED::getBrightness () inline
Get the current global brightness setting.
Returns
the current global brightness value
Definition at line 729 of file FastLED.h.
{ return m_Scale; }
References m_Scale.
Referenced by get_brightness().
getFPS()
uint16_t CFastLED::getFPS () inline
Get the number of frames/second being written out.
Returns
the most recently computed FPS value
Definition at line 802 of file FastLED.h.
{ return m_nFPS; }
References m_nFPS.
leds()
CRGB * CFastLED::leds ()
Get a pointer to led data for the first controller.
Returns
pointer to the CRGB buffer for the first controller
Definition at line 88 of file FastLED.cpp.
                     {
    return (*this)[0].leds();
}
operator[]()
CLEDController & CFastLED::operator[] (int x)
Get a reference to a registered controller.
Returns
a reference to the Nth controller
Definition at line 165 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(x-- && pCur) {
        pCur = pCur->next();
    }
    if(pCur == NULL) {
        return *(CLEDController::head());
    } else {
        return *pCur;
    }
}
References CLEDController::head(), CLEDController::next(), and x.
removeListener()
void CFastLED::removeListener (fl::EngineEvents::Listener * listener) inline
Definition at line 367 of file FastLED.h.
{ fl::EngineEvents::removeListener(listener); }
References fl::EngineEvents::removeListener().
setBrightness()
void CFastLED::setBrightness (uint8_t scale) inline
Set the global brightness scaling.
Parameters
scale a 0-255 value for how much to scale all leds before writing them out
Examples
ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FxEngine.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, OctoWS2811Demo.ino, Pride2015.ino, SmartMatrix.ino, and XYMatrix.ino.
Definition at line 725 of file FastLED.h.
{ m_Scale = scale; }
References m_Scale, and scale.
Referenced by loop(), setup(), and setup_i2s_using_fastled_api().
setCorrection()
void CFastLED::setCorrection (const struct CRGB & correction)
Set a global color correction.
Sets the color correction for all added led strips, overriding whatever previous color correction those controllers may have had.
Parameters
correction A CRGB structure describin the color correction.
Definition at line 256 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        pCur->setCorrection(correction);
        pCur = pCur->next();
    }
}
References CLEDController::head(), CLEDController::next(), and CLEDController::setCorrection().
setDither()
void CFastLED::setDither (uint8_t ditherMode = BINARY_DITHER)
Set the dithering mode.
Sets the dithering mode for all added led strips, overriding whatever previous dithering option those controllers may have had.
Parameters
ditherMode what type of dithering to use, either BINARY_DITHER or DISABLE_DITHER
Definition at line 264 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        pCur->setDither(ditherMode);
        pCur = pCur->next();
    }
}
References CLEDController::head(), CLEDController::next(), and CLEDController::setDither().
Referenced by setup().
setMaxPowerInMilliWatts()
void CFastLED::setMaxPowerInMilliWatts (uint32_t milliwatts) inline
Set the maximum power to be used, given in milliwatts.
Parameters
milliwatts the max power draw desired, in milliwatts
Definition at line 738 of file FastLED.h.
{ m_pPowerFunc = &calculate_max_brightness_for_power_mW; m_nPowerData = milliwatts; }
References calculate_max_brightness_for_power_mW(), m_nPowerData, and m_pPowerFunc.
Referenced by set_max_power_in_milliwatts(), and setMaxPowerInVoltsAndMilliamps().
setMaxPowerInVoltsAndMilliamps()
void CFastLED::setMaxPowerInVoltsAndMilliamps (uint8_t volts, uint32_t milliamps) inline
Set the maximum power to be used, given in volts and milliamps.
Parameters
volts how many volts the leds are being driven at (usually 5)
milliamps the maximum milliamps of power draw you want
Examples
Pacifica.ino, and TwinkleFox.ino.
Definition at line 734 of file FastLED.h.
{ setMaxPowerInMilliWatts(volts * milliamps); }
References setMaxPowerInMilliWatts().
Referenced by set_max_power_in_volts_and_milliamps(), and setup().
setMaxRefreshRate()
void CFastLED::setMaxRefreshRate (uint16_t refresh, bool constrain = false)
Set the maximum refresh rate.
This is global for all leds. Attempts to call show() faster than this rate will simply wait.
Note
The refresh rate defaults to the slowest refresh rate of all the leds added through addLeds(). If you wish to set/override this rate, be sure to call setMaxRefreshRate() after adding all of your leds.
Parameters
refresh maximum refresh rate in hz
constrain constrain refresh rate to the slowest speed yet set
Definition at line 339 of file FastLED.cpp.
{
    if(constrain) {
        // if we're constraining, the new value of m_nMinMicros _must_ be higher than previously (because we're only
        // allowed to slow things down if constraining)
        if(refresh > 0) {
            m_nMinMicros = ((1000000 / refresh) > m_nMinMicros) ? (1000000 / refresh) : m_nMinMicros;
        }
    } else if(refresh > 0) {
        m_nMinMicros = 1000000 / refresh;
    } else {
        m_nMinMicros = 0;
    }
}
References m_nMinMicros.
Referenced by addLeds().
setTemperature()
void CFastLED::setTemperature (const struct CRGB & temp)
Set a global color temperature.
Sets the color temperature for all added led strips, overriding whatever previous color temperature those controllers may have had.
Parameters
temp A CRGB structure describing the color temperature
Examples
ColorTemperature.ino.
Definition at line 248 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        pCur->setTemperature(temp);
        pCur = pCur->next();
    }
}
References CLEDController::head(), CLEDController::next(), and CLEDController::setTemperature().
Referenced by loop().
show() [1/2]
void CFastLED::show () inline
Update all our controllers with the current led colors.
Definition at line 745 of file FastLED.h.
{ show(m_Scale); }
References m_Scale, and show().
Referenced by delay(), and show().
show() [2/2]
void CFastLED::show (uint8_t scale)
Update all our controllers with the current led colors, using the passed in brightness.
Parameters
scale the brightness value to use in place of the stored value
Examples
ArrayOfLedArrays.ino, Blink.ino, BlinkParallel.ino, ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FirstLight.ino, FxEngine.ino, MirroringSample.ino, MultiArrays.ino, MultipleStripsInOneArray.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, OctoWS2811Demo.ino, PJRCSpectrumAnalyzer.ino, Pacifica.ino, ParallelOutputDemo.ino, Pride2015.ino, RGBCalibrate.ino, SmartMatrix.ino, TwinkleFox.ino, WS2816.ino, and XYMatrix.ino.
Definition at line 107 of file FastLED.cpp.
{
    fl::EngineEvents::onBeginFrame();
    while(m_nMinMicros && ((micros()-lastshow) < m_nMinMicros));
    lastshow = micros();
    // If we have a function for computing power, use it!
    if(m_pPowerFunc) {
        scale = (*m_pPowerFunc)(scale, m_nPowerData);
    }
    // static uninitialized gControllersData produces the smallest binary on attiny85.
    int length = 0;
    CLEDController *pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            gControllersData[length] = pCur->beginShowLeds(pCur->size());
        } else {
            gControllersData[length] = nullptr;
        }
        length++;
        if (m_nFPS < 100) { pCur->setDither(0); }
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    for (length = 0; length < MAX_CLED_CONTROLLERS && pCur; length++) {
        if (pCur->getEnabled()) {
            pCur->showLedsInternal(scale);
        }
        pCur = pCur->next();
    }
    length = 0;  // Reset length to 0 and iterate again.
    pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            pCur->endShowLeds(gControllersData[length]);
        }
        length++;
        pCur = pCur->next();
    }
    countFPS();
    fl::EngineEvents::onEndShowLeds();
    fl::EngineEvents::onEndFrame();
}
References CLEDController::beginShowLeds(), countFPS(), CLEDController::endShowLeds(), gControllersData, CLEDController::getEnabled(), CLEDController::head(), lastshow, m_nFPS, m_nMinMicros, m_nPowerData, m_pPowerFunc, MAX_CLED_CONTROLLERS, CLEDController::next(), fl::EngineEvents::onBeginFrame(), fl::EngineEvents::onEndFrame(), fl::EngineEvents::onEndShowLeds(), scale, CLEDController::setDither(), CLEDController::showLedsInternal(), and CLEDController::size().
Referenced by blink(), colorWipe(), fillAndShow(), loop(), LedRopeTCL::RawCommitDraw(), setup(), and show_at_max_brightness_for_power().
showColor() [1/2]
void CFastLED::showColor (const struct CRGB & color) inline
Set all leds on all controllers to the given color.
Parameters
color what color to set the leds to
Definition at line 762 of file FastLED.h.
{ showColor(color, m_Scale); }
References m_Scale, and showColor().
Referenced by showColor().
showColor() [2/2]
void CFastLED::showColor (const struct CRGB & color, uint8_t scale)
Set all leds on all controllers to the given color/scale.
Parameters
color what color to set the leds to
scale what brightness scale to show at
Definition at line 177 of file FastLED.cpp.
{
    while(m_nMinMicros && ((micros()-lastshow) < m_nMinMicros));
    lastshow = micros();
    // If we have a function for computing power, use it!
    if(m_pPowerFunc) {
        scale = (*m_pPowerFunc)(scale, m_nPowerData);
    }
    int length = 0;
    CLEDController *pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            gControllersData[length] = pCur->beginShowLeds(pCur->size());
        } else {
            gControllersData[length] = nullptr;
        }
        length++;
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if(m_nFPS < 100) { pCur->setDither(0); }
        if (pCur->getEnabled()) {
            pCur->showColorInternal(color, scale);
        }
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    length = 0;  // Reset length to 0 and iterate again.
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            pCur->endShowLeds(gControllersData[length]);
        }
        length++;
        pCur = pCur->next();
    }
    countFPS();
}
References CLEDController::beginShowLeds(), countFPS(), CLEDController::endShowLeds(), gControllersData, CLEDController::getEnabled(), CLEDController::head(), lastshow, m_nFPS, m_nMinMicros, m_nPowerData, m_pPowerFunc, MAX_CLED_CONTROLLERS, CLEDController::next(), scale, CLEDController::setDither(), CLEDController::showColorInternal(), and CLEDController::size().
Referenced by clear().
size()
int CFastLED::size ()
Get the number of leds in the first controller.
Returns
the number of LEDs in the first controller
Definition at line 84 of file FastLED.cpp.
                   {
    return (*this)[0].size();
}
References CLEDController::size().
Member Data Documentation
m_nFPS
uint16_t CFastLED::m_nFPS private
tracking for current frames per second (FPS) value
Definition at line 356 of file FastLED.h.
Referenced by CFastLED(), countFPS(), getFPS(), show(), and showColor().
m_nMinMicros
uint32_t CFastLED::m_nMinMicros private
minimum µs between frames, used for capping frame rates
Definition at line 357 of file FastLED.h.
Referenced by CFastLED(), setMaxRefreshRate(), show(), and showColor().
m_nPowerData
uint32_t CFastLED::m_nPowerData private
max power use parameter
Definition at line 358 of file FastLED.h.
Referenced by CFastLED(), setMaxPowerInMilliWatts(), show(), and showColor().
m_pPowerFunc
power_func CFastLED::m_pPowerFunc private
function for overriding brightness when using FastLED.show();
Definition at line 359 of file FastLED.h.
Referenced by CFastLED(), setMaxPowerInMilliWatts(), show(), and showColor().
m_Scale
uint8_t CFastLED::m_Scale private
the current global brightness scale setting
Definition at line 355 of file FastLED.h.
Referenced by CFastLED(), getBrightness(), setBrightness(), show(), and showColor().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/FastLED.h
/home/runner/work/FastLED/FastLED/src/FastLED.cpp