FastLED: Color Blurring Functions
Color Blurring Functions
Color Utility Functions
Detailed Description
Functions for blurring colors
Functions
void blur1d (CRGB *leds, uint16_t numLeds, fract8 blur_amount)
One-dimensional blur filter.
void blur2d (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount) FASTLED_DEPRECATED("Use blur2d(...
Legacy version of blur2d, which does not require an XYMap but instead implicitly binds to XY() function.
void blur2d (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Two-dimensional blur filter.
void blurColumns (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Perform a blur1d() on every column of a rectangular matrix.
void blurRows (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Perform a blur1d() on every row of a rectangular matrix.
Variables
void const fl::XYMap &xymap instead
Function Documentation
blur1d()
void blur1d (CRGB * leds, uint16_t numLeds, fract8 blur_amount)
One-dimensional blur filter.
Spreads light to 2 line neighbors.
0 = no spread at all
64 = moderate spreading
172 = maximum smooth, even spreading
173..255 = wider spreading, but increasing flicker
Total light is NOT entirely conserved, so many repeated calls to 'blur' will also result in the light fading, eventually all the way to black; this is by design so that it can be used to (slowly) clear the LEDs to black.
Parameters
leds a pointer to the LED array to blur
numLeds the number of LEDs to blur
blur_amount the amount of blur to apply
Definition at line 454 of file colorutils.cpp.
{
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    CRGB carryover = CRGB::Black;
    for( uint16_t i = 0; i < numLeds; ++i) {
        CRGB cur = leds[i];
        CRGB part = cur;
        part.nscale8( seep);
        cur.nscale8( keep);
        cur += carryover;
        if( i) leds[i-1] += part;
        leds[i] = cur;
        carryover = part;
    }
}
References CRGB::Black, leds, and CRGB::nscale8().
Referenced by loop().
blur2d() [1/2]
void blur2d (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount)
Legacy version of blur2d, which does not require an XYMap but instead implicitly binds to XY() function.
If you are hitting a linker error here, then use blur2d(..., const fl::XYMap& xymap) instead.
blur2d() [2/2]
void blur2d (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Two-dimensional blur filter.
Spreads light to 8 XY neighbors.
0 = no spread at all
64 = moderate spreading
172 = maximum smooth, even spreading
173..255 = wider spreading, but increasing flicker
Total light is NOT entirely conserved, so many repeated calls to 'blur' will also result in the light fading, eventually all the way to black; this is by design so that it can be used to (slowly) clear the LEDs to black.
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 471 of file colorutils.cpp.
{
    blurRows(leds, width, height, blur_amount, xymap);
    blurColumns(leds, width, height, blur_amount, xymap);
}
References blurColumns(), blurRows(), leds, and xymap.
Referenced by blur2d(), and loop().
blurColumns()
void blurColumns (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Perform a blur1d() on every column of a rectangular matrix.
See also
blur1d()
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 510 of file colorutils.cpp.
{
    // blur columns
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    for( uint8_t col = 0; col < width; ++col) {
        CRGB carryover = CRGB::Black;
        for( uint8_t i = 0; i < height; ++i) {
            CRGB cur = leds[xyMap.mapToIndex(col,i)];
            CRGB part = cur;
            part.nscale8( seep);
            cur.nscale8( keep);
            cur += carryover;
            if( i) leds[xyMap.mapToIndex(col,i-1)] += part;
            leds[xyMap.mapToIndex(col,i)] = cur;
            carryover = part;
        }
    }
}
References CRGB::Black, leds, fl::XYMap::mapToIndex(), CRGB::nscale8(), and xyMap.
Referenced by blur2d().
blurRows()
void blurRows (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Perform a blur1d() on every row of a rectangular matrix.
See also
blur1d()
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 483 of file colorutils.cpp.
{
/*    for(uint8_t row = 0; row < height; row++) {
        CRGB* rowbase = leds + (row * width);
        blur1d( rowbase, width, blur_amount);
    }
*/
    // blur rows same as columns, for irregular matrix
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    for( uint8_t row = 0; row < height; row++) {
        CRGB carryover = CRGB::Black;
        for( uint8_t i = 0; i < width; i++) {
            CRGB cur = leds[xyMap.mapToIndex(i,row)];
            CRGB part = cur;
            part.nscale8( seep);
            cur.nscale8( keep);
            cur += carryover;
            if( i) leds[xyMap.mapToIndex(i-1,row)] += part;
            leds[xyMap.mapToIndex(i,row)] = cur;
            carryover = part;
        }
    }
}
References CRGB::Black, leds, fl::XYMap::mapToIndex(), CRGB::nscale8(), and xyMap.
Referenced by blur2d().
Variable Documentation
instead
void const fl::XYMap& xymap instead
Definition at line 556 of file colorutils.h.