FastLED: fl::Ptr< T > Class Template Reference
fl::Ptr< T > Class Template Reference
Detailed Description
template<typename T>
class fl::Ptr< T >
Definition at line 102 of file ptr.h.
#include <ptr.h>
Public Member Functions
Ptr ()
Ptr (const Ptr &other)
template<typename U , typename = fl::is_derived<T, U>>
Ptr (const Ptr< U > &refptr)
Ptr (Ptr &&other) noexcept
Ptr (T *referent)=delete
~Ptr ()
T * get () const
bool isOwned () const
operator bool () const noexcept
bool operator!= (const Ptr &other) const
bool operator!= (const T *other) const
T & operator* () const
T * operator-> () const
bool operator< (const Ptr &other) const
Ptr & operator= (const Ptr &other)
Ptr & operator= (Ptr &&other) noexcept
Ptr & operator= (T *referent)=delete
bool operator== (const Ptr &other) const
bool operator== (const T *other) const
T * release ()
void reset ()
void reset (Ptr< T > &refptr)
void swap (Ptr &other) noexcept
WeakPtr< T > weakPtr () const
WeakPtr< T > weakRefNoCreate () const
Static Public Member Functions
template<typename... Args>
static Ptr< T > New (Args... args)
static Ptr NoTracking (T &referent)
static Ptr< T > Null ()
static Ptr TakeOwnership (T *ptr)
Static Public Member Functions inherited from fl::PtrTraits< T >
static Ptr< T > New ()
template<typename... Args>
static Ptr< T > New (Args... args)
Private Member Functions
Ptr (T *referent, bool from_heap)
Private Attributes
T * referent_
Friends
class PtrTraits< T >
Additional Inherited Members
Public Types inherited from fl::PtrTraits< T >
using element_type = T
using ptr_type = Ptr<T>
Constructor & Destructor Documentation
Ptr() [1/6]
template<typename T > template<typename U , typename = fl::is_derived<T, U>> fl::Ptr< T >::Ptr (const Ptr< U > & refptr) inline
Definition at line 121 of file ptr.h.
                              : referent_(refptr.get()) {
        if (referent_ && isOwned()) {
            referent_->ref();
        }
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
Ptr() [2/6]
template<typename T > fl::Ptr< T >::Ptr () inline
Definition at line 129 of file ptr.h.
: referent_(nullptr) {}
Referenced by fl::Ptr< T >::NoTracking(), fl::Ptr< T >::Null(), and fl::Ptr< T >::TakeOwnership().
Ptr() [3/6]
template<typename T > fl::Ptr< T >::Ptr (T * referent) delete
Ptr() [4/6]
template<typename T > fl::Ptr< T >::Ptr (const Ptr< T > & other) inline
Definition at line 136 of file ptr.h.
                          : referent_(other.referent_) {
        if (referent_ && isOwned()) {
            referent_->ref();
        }
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
Ptr() [5/6]
template<typename T > fl::Ptr< T >::Ptr (Ptr< T > && other) inline noexcept
Definition at line 142 of file ptr.h.
                              : referent_(other.referent_) {
        other.referent_ = nullptr;
    }
~Ptr()
template<typename T > fl::Ptr< T >::~Ptr () inline
Definition at line 146 of file ptr.h.
           {
        if (referent_ && isOwned()) {
            referent_->unref();
        }
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
Ptr() [6/6]
template<typename T > fl::Ptr< T >::Ptr (T * referent, bool from_heap) inline private
Definition at line 238 of file ptr.h.
                                     : referent_(referent) {
        if (referent_ && from_heap) {
            referent_->ref();
        }
    }
References fl::Ptr< T >::referent_.
Member Function Documentation
get()
template<typename T > T * fl::Ptr< T >::get () const inline
Definition at line 195 of file ptr.h.
{ return referent_; }
References fl::Ptr< T >::referent_.
Referenced by fl::WeakPtr< T >::WeakPtr(), fl::WeakPtr< T >::WeakPtr(), and fl::WeakPtr< T >::operator==().
isOwned()
template<typename T > bool fl::Ptr< T >::isOwned () const inline
Definition at line 235 of file ptr.h.
{ return referent_ && referent_->ref_count() > 0; }
References fl::Ptr< T >::referent_.
Referenced by fl::Ptr< T >::Ptr(), fl::Ptr< T >::Ptr(), fl::Ptr< T >::~Ptr(), fl::Ptr< T >::operator=(), fl::Ptr< T >::operator=(), fl::Ptr< T >::reset(), and fl::Ptr< T >::reset().
New()
template<typename T > template<typename... Args> static Ptr< T > fl::Ptr< T >::New (Args... args) inline static
Definition at line 106 of file ptr.h.
{
        return PtrTraits<T>::New(args...);
    }
References fl::PtrTraits< T >::New().
NoTracking()
template<typename T > static Ptr fl::Ptr< T >::NoTracking (T & referent) inline static
Definition at line 116 of file ptr.h.
{ return Ptr(&referent, false); }
References fl::Ptr< T >::Ptr().
Referenced by fl::WeakPtr< T >::lock().
Null()
template<typename T > static Ptr< T > fl::Ptr< T >::Null () inline static
Definition at line 127 of file ptr.h.
{ return Ptr<T>(); }
References fl::Ptr< T >::Ptr().
operator bool()
template<typename T > fl::Ptr< T >::operator bool () const inline explicit noexcept
Definition at line 201 of file ptr.h.
{ return referent_ != nullptr; }
References fl::Ptr< T >::referent_.
operator!=() [1/2]
template<typename T > bool fl::Ptr< T >::operator!= (const Ptr< T > & other) const inline
Definition at line 176 of file ptr.h.
{
        return referent_ != other.referent_;
    }
References fl::Ptr< T >::referent_.
operator!=() [2/2]
template<typename T > bool fl::Ptr< T >::operator!= (const T * other) const inline
Definition at line 171 of file ptr.h.
{ return referent_ != other; }
References fl::Ptr< T >::referent_.
operator*()
template<typename T > T & fl::Ptr< T >::operator* () const inline
Definition at line 199 of file ptr.h.
{ return *referent_; }
References fl::Ptr< T >::referent_.
operator->()
template<typename T > T * fl::Ptr< T >::operator-> () const inline
Definition at line 197 of file ptr.h.
{ return referent_; }
References fl::Ptr< T >::referent_.
operator<()
template<typename T > bool fl::Ptr< T >::operator< (const Ptr< T > & other) const inline
Definition at line 180 of file ptr.h.
{
        return referent_ < other.referent_;
    }
References fl::Ptr< T >::referent_.
operator=() [1/3]
template<typename T > Ptr & fl::Ptr< T >::operator= (const Ptr< T > & other) inline
Definition at line 152 of file ptr.h.
{
        if (this != &other) {
            if (referent_ && isOwned()) {
                referent_->unref();
            }
            referent_ = other.referent_;
            if (referent_ && isOwned()) {
                referent_->ref();
            }
        }
        return *this;
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
operator=() [2/3]
template<typename T > Ptr & fl::Ptr< T >::operator= (Ptr< T > && other) inline noexcept
Definition at line 184 of file ptr.h.
{
        if (this != &other) {
            if (referent_ && isOwned()) {
                referent_->unref();
            }
            referent_ = other.referent_;
            other.referent_ = nullptr;
        }
        return *this;
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
operator=() [3/3]
template<typename T > Ptr & fl::Ptr< T >::operator= (T * referent) delete
operator==() [1/2]
template<typename T > bool fl::Ptr< T >::operator== (const Ptr< T > & other) const inline
Definition at line 173 of file ptr.h.
{
        return referent_ == other.referent_;
    }
References fl::Ptr< T >::referent_.
operator==() [2/2]
template<typename T > bool fl::Ptr< T >::operator== (const T * other) const inline
Definition at line 169 of file ptr.h.
{ return referent_ == other; }
References fl::Ptr< T >::referent_.
release()
template<typename T > T * fl::Ptr< T >::release () inline
Definition at line 223 of file ptr.h.
                 {
        T *temp = referent_;
        referent_ = nullptr;
        return temp;
    }
References fl::Ptr< T >::referent_.
reset() [1/2]
template<typename T > void fl::Ptr< T >::reset () inline
Definition at line 203 of file ptr.h.
                 {
        if (referent_ && isOwned()) {
            referent_->unref();
        }
        referent_ = nullptr;
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
reset() [2/2]
template<typename T > void fl::Ptr< T >::reset (Ptr< T > & refptr) inline
Definition at line 210 of file ptr.h.
{
        if (refptr.referent_ != referent_) {
            if (refptr.referent_ && refptr.isOwned()) {
                refptr.referent_->ref();
            }
            if (referent_ && isOwned()) {
                referent_->unref();
            }
            referent_ = refptr.referent_;
        }
    }
References fl::Ptr< T >::isOwned(), and fl::Ptr< T >::referent_.
swap()
template<typename T > void fl::Ptr< T >::swap (Ptr< T > & other) inline noexcept
Definition at line 229 of file ptr.h.
{
        T *temp = referent_;
        referent_ = other.referent_;
        other.referent_ = temp;
    }
References fl::Ptr< T >::referent_.
TakeOwnership()
template<typename T > static Ptr fl::Ptr< T >::TakeOwnership (T * ptr) inline static
Definition at line 111 of file ptr.h.
{ return Ptr(ptr, true); }
References fl::Ptr< T >::Ptr().
Referenced by fl::WeakPtr< T >::lock(), fl::PtrTraits< T >::New(), and fl::PtrTraits< T >::New().
weakPtr()
template<typename T > WeakPtr< T > fl::Ptr< T >::weakPtr () const inline
Definition at line 167 of file ptr.h.
{ return WeakPtr<T>(*this); }
weakRefNoCreate()
template<typename T > WeakPtr< T > fl::Ptr< T >::weakRefNoCreate () const inline
Definition at line 414 of file ptr.h.
{
    if (!referent_) {
        return WeakPtr<T>();
    }
    WeakReferent *tmp = get()->mWeakPtr.get();
    if (!tmp) {
        return WeakPtr<T>();
    }
    T *referent = static_cast<T *>(tmp->getReferent());
    if (!referent) {
        return WeakPtr<T>();
    }
    // At this point, we know that our weak referent is valid.
    // However, the template parameter ensures that either we have
    // an exact type, or are at least down-castable of it.
    WeakPtr<T> out;
    out.mWeakPtr = get()->mWeakPtr;
    return out;
}
References fl::WeakReferent::getReferent(), and fl::WeakPtr< T >::mWeakPtr.
Referenced by fl::WeakPtr< T >::WeakPtr(), and fl::WeakPtr< T >::WeakPtr().
Friends And Related Symbol Documentation
PtrTraits< T >
template<typename T > friend class PtrTraits< T > friend
Definition at line 57 of file ptr.h.
Member Data Documentation
referent_
template<typename T > T* fl::Ptr< T >::referent_ private
Definition at line 243 of file ptr.h.
Referenced by fl::Ptr< T >::Ptr(), fl::Ptr< T >::Ptr(), fl::Ptr< T >::Ptr(), fl::Ptr< T >::~Ptr(), fl::Ptr< T >::get(), fl::Ptr< T >::isOwned(), fl::Ptr< T >::operator bool(), fl::Ptr< T >::operator!=(), fl::Ptr< T >::operator!=(), fl::Ptr< T >::operator*(), fl::Ptr< T >::operator->(), fl::Ptr< T >::operator<(), fl::Ptr< T >::operator=(), fl::Ptr< T >::operator=(), fl::Ptr< T >::operator==(), fl::Ptr< T >::operator==(), fl::Ptr< T >::release(), fl::Ptr< T >::reset(), fl::Ptr< T >::reset(), and fl::Ptr< T >::swap().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ptr.h