FastLED: /home/runner/work/FastLED/FastLED/examples/BlinkParallel/BlinkParallel.ino File Reference
BlinkParallel.ino File Reference
Detailed Description
Shows parallel usage of WS2812 strips.
Blinks once for red, twice for green, thrice for blue.
Definition in file BlinkParallel.ino.
#include "FastLED.h"
Macros
#define NUM_LEDS 256
Functions
void blink (CRGB color, int times)
void fill (CRGB color)
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Macro Definition Documentation
NUM_LEDS
#define NUM_LEDS 256
Definition at line 9 of file BlinkParallel.ino.
Function Documentation
blink()
void blink (CRGB color, int times)
Examples
BlinkParallel.ino.
Definition at line 32 of file BlinkParallel.ino.
{
  for (int i = 0; i < times; i++) {
    fill(color);
    FastLED.show();
    delay(500);
    fill(CRGB::Black);
    FastLED.show();
    delay(500);
  }
}
References CRGB::Black, FastLED, fill(), and CFastLED::show().
Referenced by loop().
fill()
void fill (CRGB color)
Examples
BlinkParallel.ino.
Definition at line 26 of file BlinkParallel.ino.
                      {
  for (int i = 0; i < NUM_LEDS; i++) {
    leds[i] = color;
  }
}
References leds, and NUM_LEDS.
Referenced by blink(), and loop().
loop()
void loop ()
Definition at line 43 of file BlinkParallel.ino.
            {
  // Turn the LED on, then pause
  blink(CRGB(8,0,0), 1);  // blink once for red
  blink(CRGB(0,8,0), 2);  // blink twice for green
  blink(CRGB(0,0,8), 3);  // blink thrice for blue
  delay(50);
  // now benchmark
  uint32_t start = millis();
  fill(CRGB(8,8,8));
  FastLED.show();
  uint32_t diff = millis() - start;
  Serial.print("Time to fill and show for non blocking (ms): ");
  Serial.println(diff);
  delay(50);
  start = millis();
  fill(CRGB(8,8,8));
  FastLED.show();
  FastLED.show();
  diff = millis() - start;
  Serial.print("Time to fill and show for 2nd blocking (ms): ");
  Serial.println(diff);
}
References blink(), FastLED, fill(), and CFastLED::show().
setup()
void setup ()
Definition at line 16 of file BlinkParallel.ino.
             {
    Serial.begin(115200);
    //FastLED.addLeds<WS2812, 5>(leds, NUM_LEDS);  // GRB ordering is assumed
    FastLED.addLeds<WS2812, 1>(leds, NUM_LEDS);  // GRB ordering is assumed
    FastLED.addLeds<WS2812, 2>(leds, NUM_LEDS);  // GRB ordering is assumed
    FastLED.addLeds<WS2812, 3>(leds, NUM_LEDS);  // GRB ordering is assumed
    FastLED.addLeds<WS2812, 4>(leds, NUM_LEDS);  // GRB ordering is assumed
    delay(1000);
}
References CFastLED::addLeds(), FastLED, leds, and NUM_LEDS.
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 14 of file BlinkParallel.ino.