FastLED: NoiseGenerator Struct Reference
NoiseGenerator Struct Reference
Detailed Description
Definition at line 17 of file noisegen.h.
#include <noisegen.h>
Public Member Functions
NoiseGenerator ()
NoiseGenerator (int32_t itScale, int32_t timeMul)
int LedValue (int32_t i, unsigned long time_ms) const
uint8_t Value (int32_t i, unsigned long time_ms) const
Public Attributes
int32_t iteration_scale
unsigned long time_multiplier
Constructor & Destructor Documentation
NoiseGenerator() [1/2]
NoiseGenerator::NoiseGenerator () inline
Definition at line 21 of file noisegen.h.
: iteration_scale(10), time_multiplier(10) {}
NoiseGenerator() [2/2]
NoiseGenerator::NoiseGenerator (int32_t itScale, int32_t timeMul) inline
Definition at line 22 of file noisegen.h.
: iteration_scale(itScale), time_multiplier(timeMul) {}
Member Function Documentation
LedValue()
int NoiseGenerator::LedValue (int32_t i, unsigned long time_ms) const inline
Definition at line 30 of file noisegen.h.
{
        int val = Value(i, time_ms);
        return MAX(0, val - 128) * 2;
    }
References MAX, and Value().
Referenced by fl::NoiseWave::draw().
Value()
uint8_t NoiseGenerator::Value (int32_t i, unsigned long time_ms) const inline
Definition at line 24 of file noisegen.h.
{
        uint32_t input = iteration_scale * i + time_ms * time_multiplier;
        uint16_t v1 = inoise16(input);
        return uint8_t(v1 >> 8);
    }
References inoise16(), iteration_scale, and time_multiplier.
Referenced by LedValue().
Member Data Documentation
iteration_scale
int32_t NoiseGenerator::iteration_scale
Definition at line 18 of file noisegen.h.
Referenced by Value().
time_multiplier
unsigned long NoiseGenerator::time_multiplier
Definition at line 19 of file noisegen.h.
Referenced by Value().
The documentation for this struct was generated from the following file:
/home/runner/work/FastLED/FastLED/src/noisegen.h