FastLED: fl::FxEngine Class Reference
fl::FxEngine Class Reference
Detailed Description
Manages and renders multiple visual effects (Fx) for LED strips.
The FxEngine class is responsible for:
Storing and managing a collection of visual effects (Fx objects)
Handling transitions between effects
Rendering the current effect or transition to an output buffer
Examples
FxEngine.ino.
Definition at line 38 of file fx_engine.h.
#include <fx_engine.h>
Public Types
typedef fl::FixedMap< int, FxPtr, FASTLED_FX_ENGINE_MAX_FX > IntFxMap
Public Member Functions
FxEngine (uint16_t numLeds, bool interpolate=true)
Constructs an FxEngine with the specified number of LEDs.
~FxEngine ()
Destructor for FxEngine.
IntFxMap & _getEffects ()
int addFx (Fx &effect)
Adds a new effect to the engine.
int addFx (FxPtr effect)
Adds a new effect to the engine.
bool draw (uint32_t now, CRGB *outputBuffer)
Renders the current effect or transition to the output buffer.
int getCurrentFxId () const
FxPtr getFx (int index)
Retrieves an effect from the engine without removing it.
bool nextFx (uint16_t transition_ms=500)
Transitions to the next effect in the sequence.
FxPtr removeFx (int index)
Requests removal of an effect from the engine, which might not happen immediately (for example the Fx needs to finish a transition).
bool setNextFx (int index, uint16_t duration)
Sets the next effect to transition to.
void setSpeed (float scale)
Sets the speed of the fx engine, which will impact the speed of all effects.
Private Attributes
FxCompositor mCompositor
Handles effect transitions and rendering.
int mCounter = 0
int mCurrId
Id of the current effect.
uint16_t mDuration = 0
Duration of the current transition.
bool mDurationSet = false
Flag indicating if a new transition has been set.
IntFxMap mEffects
Collection of effects.
bool mInterpolate = true
TimeScale mTimeFunction
Member Typedef Documentation
IntFxMap
fl::FixedMap<int, FxPtr, FASTLED_FX_ENGINE_MAX_FX> fl::FxEngine::IntFxMap
Definition at line 40 of file fx_engine.h.
Constructor & Destructor Documentation
FxEngine()
fl::FxEngine::FxEngine (uint16_t numLeds, bool interpolate = true)
Constructs an FxEngine with the specified number of LEDs.
Parameters
numLeds The number of LEDs in the strip.
Definition at line 7 of file fx_engine.cpp.
                                                    :
      mTimeFunction(0),
      mCompositor(numLeds),
      mCurrId(0),
      mInterpolate(interpolate) {
}
~FxEngine()
fl::FxEngine::~FxEngine ()
Destructor for FxEngine.
Definition at line 14 of file fx_engine.cpp.
{}
Member Function Documentation
_getEffects()
IntFxMap & fl::FxEngine::_getEffects () inline
Definition at line 110 of file fx_engine.h.
{ return mEffects; }
References mEffects.
addFx() [1/2]
int fl::FxEngine::addFx (Fx & effect) inline
Adds a new effect to the engine.
Allocate from static memory. This is not reference tracked and an object passed in must never be deleted, as the engine will use a non tracking Ptr which may outlive a call to removeFx() and the engine will thefore not know that an object has been deleted. But if it's a static object that's then the object probably wasn't going to be deleted anyway.
Definition at line 68 of file fx_engine.h.
{ return addFx(fl::Ptr<Fx>::NoTracking(effect)); }
References addFx().
Referenced by addFx().
addFx() [2/2]
int fl::FxEngine::addFx (FxPtr effect)
Adds a new effect to the engine.
Parameters
effect Pointer to the effect to be added.
Returns
The index of the added effect, or -1 if the effect couldn't be added.
Definition at line 16 of file fx_engine.cpp.
{
    float fps = 0;
    if (mInterpolate && effect->hasFixedFrameRate(&fps)) {
        // Wrap the effect in a VideoFxWrapper so that we can get
        // interpolation.
        VideoFxWrapperPtr vid_fx = VideoFxWrapperPtr::New(effect);
        vid_fx->setFade(0, 0);  // No fade for interpolated effects
        effect = vid_fx;
    }
    bool auto_set = mEffects.empty();
    bool ok = mEffects.insert(mCounter, effect).first;
    if (!ok) {
        return -1;
    }
    if (auto_set) {
        mCurrId = mCounter;
        mCompositor.startTransition(0, 0, effect);
    }
    return mCounter++;
}
References fl::FixedMap< Key, Value, N >::empty(), fl::FixedMap< Key, Value, N >::insert(), mCompositor, mCounter, mCurrId, mEffects, mInterpolate, and fl::FxCompositor::startTransition().
Referenced by setup().
draw()
bool fl::FxEngine::draw (uint32_t now, CRGB * outputBuffer)
Renders the current effect or transition to the output buffer.
Parameters
now The current time in milliseconds.
outputBuffer The buffer to render the effect into.
Definition at line 86 of file fx_engine.cpp.
{
    mTimeFunction.update(now);
    uint32_t warpedTime = mTimeFunction.time();
    if (mEffects.empty()) {
        return false;
    }
    if (mDurationSet) {
        FxPtr fx;
        bool ok = mEffects.get(mCurrId, &fx);
        if (!ok) {
            // something went wrong.
            return false;
        }
        mCompositor.startTransition(now, mDuration, fx);
        mDurationSet = false;
    }
    if (!mEffects.empty()) {
        mCompositor.draw(now, warpedTime, finalBuffer);
    }
    return true;
}
References fl::FxCompositor::draw(), fl::FixedMap< Key, Value, N >::empty(), fl::FixedMap< Key, Value, N >::get(), mCompositor, mCurrId, mDuration, mDurationSet, mEffects, mTimeFunction, fl::FxCompositor::startTransition(), fl::TimeScale::time(), and fl::TimeScale::update().
Referenced by loop().
getCurrentFxId()
int fl::FxEngine::getCurrentFxId () const inline
Definition at line 85 of file fx_engine.h.
{ return mCurrId; }
References mCurrId.
getFx()
FxPtr fl::FxEngine::getFx (int index)
Retrieves an effect from the engine without removing it.
Parameters
index The id of the effect to retrieve.
Returns
A pointer to the effect, or nullptr if the index was invalid.
Definition at line 77 of file fx_engine.cpp.
{
    if (mEffects.has(id)) {
        FxPtr fx;
        mEffects.get(id, &fx);
        return fx;
    }
    return FxPtr();
}
References fl::FixedMap< Key, Value, N >::get(), fl::FixedMap< Key, Value, N >::has(), and mEffects.
nextFx()
bool fl::FxEngine::nextFx (uint16_t transition_ms = 500)
Transitions to the next effect in the sequence.
Parameters
duration The duration of the transition in milliseconds.
Returns
True if the transition was initiated, false otherwise.
Definition at line 37 of file fx_engine.cpp.
{
    bool ok = mEffects.next(mCurrId, &mCurrId, true);
    if (!ok) {
        return false;
    }
    setNextFx(mCurrId, duration);
    return true;
}
References mCurrId, mEffects, fl::FixedMap< Key, Value, N >::next(), and setNextFx().
Referenced by loop().
removeFx()
FxPtr fl::FxEngine::removeFx (int index)
Requests removal of an effect from the engine, which might not happen immediately (for example the Fx needs to finish a transition).
Parameters
index The index of the effect to remove.
Returns
A pointer to the removed effect, or nullptr if the index was invalid.
Definition at line 56 of file fx_engine.cpp.
{
    if (!mEffects.has(index)) {
        return FxPtr();
    }
    FxPtr removedFx;
    bool ok = mEffects.get(index, &removedFx);
    if (!ok) {
        return FxPtr();
    }
    if (mCurrId == index) {
        // If we're removing the current effect, switch to the next one
        mEffects.next(mCurrId, &mCurrId, true);
        mDurationSet = true;
        mDuration = 0; // Instant transition
    }
    return removedFx;
}
References fl::FixedMap< Key, Value, N >::get(), fl::FixedMap< Key, Value, N >::has(), mCurrId, mDuration, mDurationSet, mEffects, and fl::FixedMap< Key, Value, N >::next().
setNextFx()
bool fl::FxEngine::setNextFx (int index, uint16_t duration)
Sets the next effect to transition to.
Parameters
index The index of the effect to transition to.
duration The duration of the transition in milliseconds.
Returns
True if the transition was set, false if the index was invalid.
Definition at line 46 of file fx_engine.cpp.
{
    if (!mEffects.has(index)) {
        return false;
    }
    mCurrId = index;
    mDuration = duration;
    mDurationSet = true;
    return true;
}
References fl::FixedMap< Key, Value, N >::has(), mCurrId, mDuration, mDurationSet, and mEffects.
Referenced by nextFx().
setSpeed()
void fl::FxEngine::setSpeed (float scale) inline
Sets the speed of the fx engine, which will impact the speed of all effects.
Parameters
timeScale The new time scale value.
Definition at line 116 of file fx_engine.h.
{ mTimeFunction.setScale(scale); }
References mTimeFunction, scale, and fl::TimeScale::setScale().
Referenced by loop().
Member Data Documentation
mCompositor
FxCompositor fl::FxEngine::mCompositor private
Handles effect transitions and rendering.
Definition at line 122 of file fx_engine.h.
Referenced by addFx(), and draw().
mCounter
int fl::FxEngine::mCounter = 0 private
Definition at line 119 of file fx_engine.h.
Referenced by addFx().
mCurrId
int fl::FxEngine::mCurrId private
Id of the current effect.
Definition at line 123 of file fx_engine.h.
Referenced by addFx(), draw(), getCurrentFxId(), nextFx(), removeFx(), and setNextFx().
mDuration
uint16_t fl::FxEngine::mDuration = 0 private
Duration of the current transition.
Definition at line 124 of file fx_engine.h.
Referenced by draw(), removeFx(), and setNextFx().
mDurationSet
bool fl::FxEngine::mDurationSet = false private
Flag indicating if a new transition has been set.
Definition at line 125 of file fx_engine.h.
Referenced by draw(), removeFx(), and setNextFx().
mEffects
IntFxMap fl::FxEngine::mEffects private
Collection of effects.
Definition at line 121 of file fx_engine.h.
Referenced by _getEffects(), addFx(), draw(), getFx(), nextFx(), removeFx(), and setNextFx().
mInterpolate
bool fl::FxEngine::mInterpolate = true private
Definition at line 126 of file fx_engine.h.
Referenced by addFx().
mTimeFunction
TimeScale fl::FxEngine::mTimeFunction private
Definition at line 120 of file fx_engine.h.
Referenced by draw(), and setSpeed().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/fx_engine.h
/home/runner/work/FastLED/FastLED/src/fx/fx_engine.cpp