FastLED: fl::FixedSet< Key, N > Class Template Reference
fl::FixedSet< Key, N > Class Template Reference
Detailed Description
template<typename Key, size_t N>
class fl::FixedSet< Key, N >
Definition at line 17 of file set.h.
#include <set.h>
Public Types
typedef VectorType::const_iterator const_iterator
typedef VectorType::iterator iterator
typedef FixedVector< Key, N > VectorType
Public Member Functions
constexpr FixedSet ()=default
const Key & back () const
iterator begin ()
const_iterator begin () const
constexpr size_t capacity () const
void clear ()
constexpr bool empty () const
iterator end ()
const_iterator end () const
bool erase (const Key &key)
bool erase (iterator pos)
iterator find (const Key &key)
const_iterator find (const Key &key) const
const Key & front () const
bool has (const Key &key) const
bool insert (const Key &key)
bool next (const Key &key, Key *next_key, bool allow_rollover=false) const
bool prev (const Key &key, Key *prev_key, bool allow_rollover=false) const
constexpr size_t size () const
Private Attributes
VectorType data
Member Typedef Documentation
const_iterator
template<typename Key , size_t N> VectorType::const_iterator fl::FixedSet< Key, N >::const_iterator
Definition at line 21 of file set.h.
iterator
template<typename Key , size_t N> VectorType::iterator fl::FixedSet< Key, N >::iterator
Definition at line 20 of file set.h.
VectorType
template<typename Key , size_t N> FixedVector<Key, N> fl::FixedSet< Key, N >::VectorType
Definition at line 19 of file set.h.
Constructor & Destructor Documentation
FixedSet()
template<typename Key , size_t N> fl::FixedSet< Key, N >::FixedSet () constexpr default
Member Function Documentation
back()
template<typename Key , size_t N> const Key & fl::FixedSet< Key, N >::back () const inline
Definition at line 144 of file set.h.
{
        return data.back();
    }
References fl::FixedVector< T, N >::back(), and fl::FixedSet< Key, N >::data.
begin() [1/2]
template<typename Key , size_t N> iterator fl::FixedSet< Key, N >::begin () inline
Definition at line 26 of file set.h.
                     {
        return data.begin();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedSet< Key, N >::data.
Referenced by fl::FixedSet< Key, N >::find(), fl::FixedSet< Key, N >::find(), fl::FixedSet< Key, N >::next(), and fl::FixedSet< Key, N >::prev().
begin() [2/2]
template<typename Key , size_t N> const_iterator fl::FixedSet< Key, N >::begin () const inline
Definition at line 32 of file set.h.
{
        return data.begin();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedSet< Key, N >::data.
capacity()
template<typename Key , size_t N> size_t fl::FixedSet< Key, N >::capacity () const inline constexpr
Definition at line 125 of file set.h.
{
        return N;
    }
clear()
template<typename Key , size_t N> void fl::FixedSet< Key, N >::clear () inline
Definition at line 130 of file set.h.
                 {
        data.clear();
    }
References fl::FixedVector< T, N >::clear(), and fl::FixedSet< Key, N >::data.
empty()
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::empty () const inline constexpr
Definition at line 120 of file set.h.
{
        return data.empty();
    }
References fl::FixedSet< Key, N >::data, and fl::FixedVector< T, N >::empty().
Referenced by fl::FixedSet< Key, N >::next(), and fl::FixedSet< Key, N >::prev().
end() [1/2]
template<typename Key , size_t N> iterator fl::FixedSet< Key, N >::end () inline
Definition at line 29 of file set.h.
                   {
        return data.end();
    }
References fl::FixedSet< Key, N >::data, and fl::FixedVector< T, N >::end().
Referenced by fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::find(), fl::FixedSet< Key, N >::find(), fl::FixedSet< Key, N >::has(), fl::FixedSet< Key, N >::insert(), fl::FixedSet< Key, N >::next(), and fl::FixedSet< Key, N >::prev().
end() [2/2]
template<typename Key , size_t N> const_iterator fl::FixedSet< Key, N >::end () const inline
Definition at line 35 of file set.h.
{
        return data.end();
    }
References fl::FixedSet< Key, N >::data, and fl::FixedVector< T, N >::end().
erase() [1/2]
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::erase (const Key & key) inline
Definition at line 68 of file set.h.
{
        auto it = find(key);
        if (it != end()) {
            data.erase(it);
            return true;
        }
        return false;
    }
References fl::FixedSet< Key, N >::data, fl::FixedSet< Key, N >::end(), fl::FixedVector< T, N >::erase(), and fl::FixedSet< Key, N >::find().
erase() [2/2]
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::erase (iterator pos) inline
Definition at line 77 of file set.h.
{
        if (pos != end()) {
            data.erase(pos);
            return true;
        }
        return false;
    }
References fl::FixedSet< Key, N >::data, fl::FixedSet< Key, N >::end(), fl::FixedVector< T, N >::erase(), and pos.
find() [1/2]
template<typename Key , size_t N> iterator fl::FixedSet< Key, N >::find (const Key & key) inline
Definition at line 39 of file set.h.
{
        for (auto it = begin(); it != end(); ++it) {
            if (*it == key) {
                return it;
            }
        }
        return end();
    }
References fl::FixedSet< Key, N >::begin(), and fl::FixedSet< Key, N >::end().
Referenced by fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::has(), fl::FixedSet< Key, N >::insert(), fl::FixedSet< Key, N >::next(), and fl::FixedSet< Key, N >::prev().
find() [2/2]
template<typename Key , size_t N> const_iterator fl::FixedSet< Key, N >::find (const Key & key) const inline
Definition at line 48 of file set.h.
{
        for (auto it = begin(); it != end(); ++it) {
            if (*it == key) {
                return it;
            }
        }
        return end();
    }
References fl::FixedSet< Key, N >::begin(), and fl::FixedSet< Key, N >::end().
front()
template<typename Key , size_t N> const Key & fl::FixedSet< Key, N >::front () const inline
Definition at line 139 of file set.h.
{
        return data.front();
    }
References fl::FixedSet< Key, N >::data, and fl::FixedVector< T, N >::front().
has()
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::has (const Key & key) const inline
Definition at line 134 of file set.h.
{
        return find(key) != end();
    }
References fl::FixedSet< Key, N >::end(), and fl::FixedSet< Key, N >::find().
insert()
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::insert (const Key & key) inline
Definition at line 57 of file set.h.
{
        if (data.size() < N) {
            auto it = find(key);
            if (it == end()) {
                data.push_back(key);
                return true;
            }
        }
        return false;
    }
References fl::FixedSet< Key, N >::data, fl::FixedSet< Key, N >::end(), fl::FixedSet< Key, N >::find(), fl::FixedVector< T, N >::push_back(), and fl::FixedVector< T, N >::size().
next()
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::next (const Key & key, Key * next_key, bool allow_rollover = false) const inline
Definition at line 85 of file set.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            ++it;
            if (it != end()) {
                *next_key = *it;
                return true;
            } else if (allow_rollover && !empty()) {
                *next_key = *begin();
                return true;
            }
        }
        return false;
    }
References fl::FixedSet< Key, N >::begin(), fl::FixedSet< Key, N >::empty(), fl::FixedSet< Key, N >::end(), and fl::FixedSet< Key, N >::find().
prev()
template<typename Key , size_t N> bool fl::FixedSet< Key, N >::prev (const Key & key, Key * prev_key, bool allow_rollover = false) const inline
Definition at line 100 of file set.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            if (it != begin()) {
                --it;
                *prev_key = *it;
                return true;
            } else if (allow_rollover && !empty()) {
                *prev_key = data[data.size() - 1];
                return true;
            }
        }
        return false;
    }
References fl::FixedSet< Key, N >::begin(), fl::FixedSet< Key, N >::data, fl::FixedSet< Key, N >::empty(), fl::FixedSet< Key, N >::end(), fl::FixedSet< Key, N >::find(), and fl::FixedVector< T, N >::size().
size()
template<typename Key , size_t N> size_t fl::FixedSet< Key, N >::size () const inline constexpr
Definition at line 116 of file set.h.
{
        return data.size();
    }
References fl::FixedSet< Key, N >::data, and fl::FixedVector< T, N >::size().
Member Data Documentation
data
template<typename Key , size_t N> VectorType fl::FixedSet< Key, N >::data private
Definition at line 150 of file set.h.
Referenced by fl::FixedSet< Key, N >::back(), fl::FixedSet< Key, N >::begin(), fl::FixedSet< Key, N >::begin(), fl::FixedSet< Key, N >::clear(), fl::FixedSet< Key, N >::empty(), fl::FixedSet< Key, N >::end(), fl::FixedSet< Key, N >::end(), fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::erase(), fl::FixedSet< Key, N >::front(), fl::FixedSet< Key, N >::insert(), fl::FixedSet< Key, N >::prev(), and fl::FixedSet< Key, N >::size().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/set.h