FastLED: fl::StringFormatter Class Reference
fl::StringFormatter Class Reference
Detailed Description
Definition at line 38 of file str.h.
#include <str.h>
Static Public Member Functions
static void append (int32_t val, StrN< 64 > *dst)
static bool isDigit (char c)
static bool isSpace (char c)
static float parseFloat (const char *str, size_t len)
Member Function Documentation
append()
void fl::StringFormatter::append (int32_t val, StrN< 64 > * dst) static
Definition at line 99 of file str.cpp.
{
    char buf[63] = {0};
    string_functions::itoa(val, buf, 10);
    dst->write(buf, strlen(buf));
}
References fl::string_functions::itoa(), and fl::StrN< SIZE >::write().
Referenced by fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), fl::StrN< SIZE >::write(), and fl::StrN< SIZE >::write().
isDigit()
static bool fl::StringFormatter::isDigit (char c) inline static
Definition at line 43 of file str.h.
{ return c >= '0' && c <= '9'; }
isSpace()
static bool fl::StringFormatter::isSpace (char c) inline static
Definition at line 41 of file str.h.
{ return c == ' ' || c == '\t' || c == '\n' || c == '\r'; }
Referenced by fl::StrN< SIZE >::trim().
parseFloat()
float fl::StringFormatter::parseFloat (const char * str, size_t len) static
Definition at line 166 of file str.cpp.
{
    return string_functions::atoff(str, len);
}
References fl::string_functions::atoff().
Referenced by fl::StrN< SIZE >::toFloat().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/str.h
/home/runner/work/FastLED/FastLED/src/fl/str.cpp