FastLED: Scaling Functions that Leave R1 Dirty
Scaling Functions that Leave R1 Dirty
Fast Math Functions » Scaling Functions
Detailed Description
These functions are more efficient for scaling multiple bytes at once, but require calling cleanup_R1() afterwards.
Functions
LIB8STATIC_ALWAYS_INLINE void cleanup_R1 ()
Clean up the r1 register after a series of *LEAVING_R1_DIRTY calls.
LIB8STATIC_ALWAYS_INLINE void nscale8_LEAVING_R1_DIRTY (uint8_t &i, fract8 scale)
In place modifying version of scale8() that does not clean up the R1 register on AVR.
LIB8STATIC_ALWAYS_INLINE void nscale8_video_LEAVING_R1_DIRTY (uint8_t &i, fract8 scale)
In place modifying version of scale8_video() that does not clean up the R1 register on AVR.
constexpr CRGB nscale8x3_constexpr (uint8_t r, uint8_t g, uint8_t b, fract8 scale)
LIB8STATIC_ALWAYS_INLINE uint8_t scale8_LEAVING_R1_DIRTY (uint8_t i, fract8 scale)
This version of scale8() does not clean up the R1 register on AVR.
LIB8STATIC_ALWAYS_INLINE uint8_t scale8_video_LEAVING_R1_DIRTY (uint8_t i, fract8 scale)
This version of scale8_video() does not clean up the R1 register on AVR.
Function Documentation
cleanup_R1()
LIB8STATIC_ALWAYS_INLINE void cleanup_R1 ()
Clean up the r1 register after a series of *LEAVING_R1_DIRTY calls.
Definition at line 333 of file scale8.h.
{
#if CLEANUP_R1_AVRASM == 1
    // Restore r1 to "0"; it's expected to always be that
    asm volatile("clr __zero_reg__  \n\t" : : : "r1");
#endif
}
Referenced by blend8(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), CRGB::getAverageLight(), CRGB::getLuma(), hsv2rgb_rainbow(), MyColorFromPaletteExtended(), nblend(), nblend(), nscale8x2(), nscale8x2_video(), nscale8x3(), and nscale8x3_video().
nscale8_LEAVING_R1_DIRTY()
LIB8STATIC_ALWAYS_INLINE void nscale8_LEAVING_R1_DIRTY (uint8_t & i, fract8 scale)
In place modifying version of scale8() that does not clean up the R1 register on AVR.
If you are doing several "scale8()'s" in a row, use this, and then explicitly call cleanup_R1().
Warning
You MUST call cleanup_R1() after using this function!
Warning
This function always modifies its arguments in place!
Parameters
i input value to scale
scale scale factor, in n/256 units
See also
scale8()
Definition at line 217 of file scale8.h.
{
#if SCALE8_C == 1
#if (FASTLED_SCALE8_FIXED == 1)
    i = (((uint16_t)i) * ((uint16_t)(scale) + 1)) >> 8;
#else
    i = ((int)i * (int)(scale)) >> 8;
#endif
#elif SCALE8_AVRASM == 1
    asm volatile(
#if (FASTLED_SCALE8_FIXED == 1)
        // Multiply 8-bit i * 8-bit scale, giving 16-bit r1,r0
        "mul %0, %1          \n\t"
        // Add i to r0, possibly setting the carry flag
        "add r0, %0         \n\t"
        // load the immediate 0 into i (note, this does _not_ touch any flags)
        "ldi %0, 0x00       \n\t"
        // walk and chew gum at the same time
        "adc %0, r1          \n\t"
#else
        /* Multiply 8-bit i * 8-bit scale, giving 16-bit r1,r0 */
        "mul %0, %1    \n\t"
        /* Move the high 8-bits of the product (r1) back to i */
        "mov %0, r1    \n\t"
#endif
        /* R1 IS LEFT DIRTY HERE; YOU MUST ZERO IT OUT YOURSELF */
        /* "clr __zero_reg__    \n\t" */
        : "+d"(i)    /* writes to i; r16-r31, restricted by ldi */
        : "r"(scale) /* uses scale */
        : "r0", "r1" /* clobbers r0, r1 */
    );
#else
#error "No implementation for nscale8_LEAVING_R1_DIRTY available."
#endif
}
References scale.
nscale8_video_LEAVING_R1_DIRTY()
LIB8STATIC_ALWAYS_INLINE void nscale8_video_LEAVING_R1_DIRTY (uint8_t & i, fract8 scale)
In place modifying version of scale8_video() that does not clean up the R1 register on AVR.
If you are doing several "scale8_video()'s" in a row, use this, and then explicitly call cleanup_R1().
Warning
You MUST call cleanup_R1() after using this function!
Warning
This function always modifies its arguments in place!
Parameters
i input value to scale
scale scale factor, in n/256 units
See also
scale8_video()
Definition at line 311 of file scale8.h.
{
#if SCALE8_C == 1 || defined(LIB8_ATTINY)
    i = (((int)i * (int)scale) >> 8) + ((i && scale) ? 1 : 0);
#elif SCALE8_AVRASM == 1
    asm volatile("  tst %[i]\n\t"
                 "  breq L_%=\n\t"
                 "  mul %[i], %[scale]\n\t"
                 "  mov %[i], r1\n\t"
                 "  breq L_%=\n\t"
                 "  subi %[i], 0xFF\n\t"
                 "L_%=: \n\t"
                 : [i] "+d"(i) // r16-r31, restricted by subi
                 : [scale] "r"(scale)
                 : "r0", "r1");
#else
#error "No implementation for scale8_video_LEAVING_R1_DIRTY available."
#endif
}
References scale.
Referenced by nscale8x2_video(), and nscale8x3_video().
nscale8x3_constexpr()
CRGB nscale8x3_constexpr (uint8_t r, uint8_t g, uint8_t b, fract8 scale) constexpr
Definition at line 340 of file scale8.h.
{
    return CRGB(((int)r * (int)(scale)) >> 8, ((int)g * (int)(scale)) >> 8,
                ((int)b * (int)(scale)) >> 8);
}
References scale.
scale8_LEAVING_R1_DIRTY()
LIB8STATIC_ALWAYS_INLINE uint8_t scale8_LEAVING_R1_DIRTY (uint8_t i, fract8 scale)
This version of scale8() does not clean up the R1 register on AVR.
If you are doing several "scale8()'s" in a row, use this, and then explicitly call cleanup_R1().
Warning
You MUST call cleanup_R1() after using this function!
Parameters
i input value to scale
scale scale factor, in n/256 units
Returns
scaled value
See also
scale8()
Definition at line 170 of file scale8.h.
{
#if SCALE8_C == 1
#if (FASTLED_SCALE8_FIXED == 1)
    return (((uint16_t)i) * ((uint16_t)(scale) + 1)) >> 8;
#else
    return ((int)i * (int)(scale)) >> 8;
#endif
#elif SCALE8_AVRASM == 1
    asm volatile(
#if (FASTLED_SCALE8_FIXED == 1)
        // Multiply 8-bit i * 8-bit scale, giving 16-bit r1,r0
        "mul %0, %1          \n\t"
        // Add i to r0, possibly setting the carry flag
        "add r0, %0         \n\t"
        // load the immediate 0 into i (note, this does _not_ touch any flags)
        "ldi %0, 0x00       \n\t"
        // walk and chew gum at the same time
        "adc %0, r1          \n\t"
#else
        /* Multiply 8-bit i * 8-bit scale, giving 16-bit r1,r0 */
        "mul %0, %1    \n\t"
        /* Move the high 8-bits of the product (r1) back to i */
        "mov %0, r1    \n\t"
#endif
        /* R1 IS LEFT DIRTY HERE; YOU MUST ZERO IT OUT YOURSELF  */
        /* "clr __zero_reg__    \n\t" */
        : "+d"(i)    /* writes to i; r16-r31, restricted by ldi */
        : "r"(scale) /* uses scale */
        : "r0", "r1" /* clobbers r0, r1 */
    );
    // Return the result
    return i;
#else
#error "No implementation for scale8_LEAVING_R1_DIRTY available."
#endif
}
References scale.
Referenced by blend8(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ease8InOutCubic(), fadeUsingColor(), CRGB::getAverageLight(), CRGB::getLuma(), hsv2rgb_rainbow(), MyColorFromPaletteExtended(), nblend(), nblend(), nscale8x2(), and nscale8x3().
scale8_video_LEAVING_R1_DIRTY()
LIB8STATIC_ALWAYS_INLINE uint8_t scale8_video_LEAVING_R1_DIRTY (uint8_t i, fract8 scale)
This version of scale8_video() does not clean up the R1 register on AVR.
If you are doing several "scale8_video()'s" in a row, use this, and then explicitly call cleanup_R1().
Warning
You MUST call cleanup_R1() after using this function!
Parameters
i input value to scale
scale scale factor, in n/256 units
Returns
scaled value
See also
scale8_video()
Definition at line 262 of file scale8.h.
{
#if SCALE8_C == 1 || defined(LIB8_ATTINY)
    uint8_t j = (((int)i * (int)scale) >> 8) + ((i && scale) ? 1 : 0);
    // uint8_t nonzeroscale = (scale != 0) ? 1 : 0;
    // uint8_t j = (i == 0) ? 0 : (((int)i * (int)(scale) ) >> 8) +
    // nonzeroscale;
    return j;
#elif SCALE8_AVRASM == 1
    uint8_t j = 0;
    asm volatile("  tst %[i]\n\t"
                 "  breq L_%=\n\t"
                 "  mul %[i], %[scale]\n\t"
                 "  mov %[j], r1\n\t"
                 "  breq L_%=\n\t"
                 "  subi %[j], 0xFF\n\t"
                 "L_%=: \n\t"
                 : [j] "+d"(j) // r16-r31, restricted by subi
                 : [i] "r"(i), [scale] "r"(scale)
                 : "r0", "r1");
    return j;
    // uint8_t nonzeroscale = (scale != 0) ? 1 : 0;
    // asm volatile(
    //      "      tst %0           \n"
    //      "      breq L_%=        \n"
    //      "      mul %0, %1       \n"
    //      "      mov %0, r1       \n"
    //      "      add %0, %2       \n"
    //      "      clr __zero_reg__ \n"
    //      "L_%=:                  \n"
    //      : "+a" (i)
    //      : "a" (scale), "a" (nonzeroscale)
    //      : "r0", "r1");
    // // Return the result
    // return i;
#else
#error "No implementation for scale8_video_LEAVING_R1_DIRTY available."
#endif
}
References scale.
Referenced by ColorFromPalette(), and hsv2rgb_rainbow().