FastLED: fl::TwinkleFox Class Reference
fl::TwinkleFox Class Reference
Detailed Description
Definition at line 112 of file twinklefox.h.
#include <twinklefox.h>
Public Member Functions
TwinkleFox (uint16_t num_leds)
void chooseNextColorPalette (CRGBPalette16 &pal)
void draw (DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Public Attributes
CRGBPalette16 currentPalette
CRGBPalette16 targetPalette
Private Member Functions
uint8_t attackDecayWave8 (uint8_t i)
CRGB computeOneTwinkle (uint32_t ms, uint8_t salt)
void coolLikeIncandescentFunction (CRGB &c, uint8_t phase)
void drawTwinkleFox (CRGB *leds)
Private Attributes
bool autoSelectBackgroundColor
CRGB backgroundColor
bool coolLikeIncandescent
uint8_t twinkleDensity
uint8_t twinkleSpeed
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
TwinkleFox()
fl::TwinkleFox::TwinkleFox (uint16_t num_leds) inline
Definition at line 117 of file twinklefox.h.
        : Fx1d(num_leds), backgroundColor(CRGB::Black),
          twinkleSpeed(TWINKLE_SPEED), twinkleDensity(TWINKLE_DENSITY),
          coolLikeIncandescent(COOL_LIKE_INCANDESCENT),
          autoSelectBackgroundColor(AUTO_SELECT_BACKGROUND_COLOR) {
        chooseNextColorPalette(targetPalette);
    }
References chooseNextColorPalette(), and targetPalette.
Member Function Documentation
attackDecayWave8()
uint8_t fl::TwinkleFox::attackDecayWave8 (uint8_t i) inline private
Definition at line 217 of file twinklefox.h.
{
        if (i < 86) {
            return i * 3;
        } else {
            i -= 86;
            return 255 - (i + (i / 2));
        }
    }
Referenced by computeOneTwinkle().
chooseNextColorPalette()
void fl::TwinkleFox::chooseNextColorPalette (CRGBPalette16 & pal)
Definition at line 300 of file twinklefox.h.
{
    const uint8_t numberOfPalettes =
        sizeof(ActivePaletteList) / sizeof(ActivePaletteList[0]);
    static uint8_t whichPalette = -1;
    whichPalette = addmod8(whichPalette, 1, numberOfPalettes);
    pal = *(ActivePaletteList[whichPalette]);
}
References fl::ActivePaletteList, and addmod8().
Referenced by TwinkleFox(), and loop().
computeOneTwinkle()
CRGB fl::TwinkleFox::computeOneTwinkle (uint32_t ms, uint8_t salt) inline private
Definition at line 191 of file twinklefox.h.
{
        uint16_t ticks = ms >> (8 - twinkleSpeed);
        uint8_t fastcycle8 = ticks;
        uint16_t slowcycle16 = (ticks >> 8) + salt;
        slowcycle16 += sin8(slowcycle16);
        slowcycle16 = (slowcycle16 * 2053) + 1384;
        uint8_t slowcycle8 = (slowcycle16 & 0xFF) + (slowcycle16 >> 8);
        uint8_t bright = 0;
        if (((slowcycle8 & 0x0E) / 2) < twinkleDensity) {
            bright = attackDecayWave8(fastcycle8);
        }
        uint8_t hue = slowcycle8 - salt;
        CRGB c;
        if (bright > 0) {
            c = ColorFromPalette(currentPalette, hue, bright, NOBLEND);
            if (coolLikeIncandescent) {
                coolLikeIncandescentFunction(c, fastcycle8);
            }
        } else {
            c = CRGB::Black;
        }
        return c;
    }
References attackDecayWave8(), CRGB::Black, ColorFromPalette(), coolLikeIncandescent, coolLikeIncandescentFunction(), currentPalette, NOBLEND, sin8, twinkleDensity, and twinkleSpeed.
Referenced by drawTwinkleFox().
coolLikeIncandescentFunction()
void fl::TwinkleFox::coolLikeIncandescentFunction (CRGB & c, uint8_t phase) inline private
Definition at line 226 of file twinklefox.h.
{
        if (phase < 128)
            return;
        uint8_t cooling = (phase - 128) >> 4;
        c.g = qsub8(c.g, cooling);
        c.b = qsub8(c.b, cooling * 2);
    }
References qsub8().
Referenced by computeOneTwinkle().
draw()
void fl::TwinkleFox::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 125 of file twinklefox.h.
{
        EVERY_N_MILLISECONDS(10) {
            nblendPaletteTowardPalette(currentPalette, targetPalette, 12);
        }
        drawTwinkleFox(context.leds);
    }
References currentPalette, drawTwinkleFox(), EVERY_N_MILLISECONDS, fl::_DrawContext::leds, nblendPaletteTowardPalette(), and targetPalette.
Referenced by loop().
drawTwinkleFox()
void fl::TwinkleFox::drawTwinkleFox (CRGB * leds) inline private
Definition at line 142 of file twinklefox.h.
{
        // "PRNG16" is the pseudorandom number generator
        // It MUST be reset to the same starting value each time
        // this function is called, so that the sequence of 'random'
        // numbers that it generates is (paradoxically) stable.
        uint16_t PRNG16 = 11337;
        uint32_t clock32 = millis();
        CRGB bg = backgroundColor;
        if (autoSelectBackgroundColor &&
            currentPalette[0] == currentPalette[1]) {
            bg = currentPalette[0];
            uint8_t bglight = bg.getAverageLight();
            if (bglight > 64) {
                bg.nscale8_video(16);
            } else if (bglight > 16) {
                bg.nscale8_video(64);
            } else {
                bg.nscale8_video(86);
            }
        }
        uint8_t backgroundBrightness = bg.getAverageLight();
        for (uint16_t i = 0; i < mNumLeds; i++) {
            PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384;
            uint16_t myclockoffset16 = PRNG16;
            PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384;
            uint8_t myspeedmultiplierQ5_3 =
                ((((PRNG16 & 0xFF) >> 4) + (PRNG16 & 0x0F)) & 0x0F) + 0x08;
            uint32_t myclock30 =
                (uint32_t)((clock32 * myspeedmultiplierQ5_3) >> 3) +
                myclockoffset16;
            uint8_t myunique8 = PRNG16 >> 8;
            CRGB c = computeOneTwinkle(myclock30, myunique8);
            uint8_t cbright = c.getAverageLight();
            int16_t deltabright = cbright - backgroundBrightness;
            if (deltabright >= 32 || (!bg)) {
                leds[i] = c;
            } else if (deltabright > 0) {
                leds[i] = blend(bg, c, deltabright * 8);
            } else {
                leds[i] = bg;
            }
        }
    }
References autoSelectBackgroundColor, backgroundColor, blend(), computeOneTwinkle(), currentPalette, CRGB::getAverageLight(), leds, fl::Fx::mNumLeds, and CRGB::nscale8_video().
Referenced by draw().
fxName()
fl::Str fl::TwinkleFox::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 133 of file twinklefox.h.
{ return "TwinkleFox"; }
Member Data Documentation
autoSelectBackgroundColor
bool fl::TwinkleFox::autoSelectBackgroundColor private
Definition at line 140 of file twinklefox.h.
Referenced by drawTwinkleFox().
backgroundColor
CRGB fl::TwinkleFox::backgroundColor private
Definition at line 136 of file twinklefox.h.
Referenced by drawTwinkleFox().
coolLikeIncandescent
bool fl::TwinkleFox::coolLikeIncandescent private
Definition at line 139 of file twinklefox.h.
Referenced by computeOneTwinkle().
currentPalette
CRGBPalette16 fl::TwinkleFox::currentPalette
Definition at line 115 of file twinklefox.h.
Referenced by computeOneTwinkle(), draw(), and drawTwinkleFox().
targetPalette
CRGBPalette16 fl::TwinkleFox::targetPalette
Definition at line 114 of file twinklefox.h.
Referenced by TwinkleFox(), draw(), and loop().
twinkleDensity
uint8_t fl::TwinkleFox::twinkleDensity private
Definition at line 138 of file twinklefox.h.
Referenced by computeOneTwinkle().
twinkleSpeed
uint8_t fl::TwinkleFox::twinkleSpeed private
Definition at line 137 of file twinklefox.h.
Referenced by computeOneTwinkle().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/1d/twinklefox.h