FastLED: KeyboardState Class Reference
KeyboardState Class Reference
Detailed Description
Definition at line 55 of file Keyboard.h.
#include <Keyboard.h>
Public Member Functions
KeyboardState ()
Key * GetKey (int midi_pitch)
void HandleAfterTouchPoly (uint8_t note, uint8_t pressure)
void HandleControlChange (uint8_t d1, uint8_t d2)
void HandleNoteOff (uint8_t midi_note, uint8_t velocity, uint32_t now_ms)
void HandleNoteOn (uint8_t midi_note, uint8_t velocity, int color_selector_value, uint32_t now_ms)
void Update (uint32_t now_ms, uint32_t delta_ms)
Static Public Member Functions
static uint8_t KeyIndex (int midi_pitch)
Public Attributes
Key keys_ [kNumKeys]
bool sustain_pedal_
Static Public Attributes
static const int kNumKeys = 88
Constructor & Destructor Documentation
KeyboardState()
KeyboardState::KeyboardState ()
Definition at line 190 of file Keyboard.cpp.
                             : sustain_pedal_(false), keys_() {
  for (int i = 0; i < kNumKeys; ++i) {
    keys_[i].idx_ = i;
  }
}
References Key::idx_, keys_, and kNumKeys.
Member Function Documentation
GetKey()
Key * KeyboardState::GetKey (int midi_pitch)
Definition at line 207 of file Keyboard.cpp.
{
  uint8_t idx = KeyIndex(midi_pitch);
  return &keys_[idx];
}
References KeyIndex(), and keys_.
Referenced by HandleNoteOff(), and HandleNoteOn().
HandleAfterTouchPoly()
void KeyboardState::HandleAfterTouchPoly (uint8_t note, uint8_t pressure)
Definition at line 180 of file Keyboard.cpp.
{
  dprintln("HandleAfterTouchPoly");
  dprint("\tnote = ");
  dprint(note);
  dprint(", pressure = ");
  dprintln(pressure);
}
References dprint, and dprintln.
HandleControlChange()
void KeyboardState::HandleControlChange (uint8_t d1, uint8_t d2)
Definition at line 169 of file Keyboard.cpp.
{
  // Note that d1 and d2 just mean "data-1" and "data-2".
  // TODO: Find out what d1 and d2 should be called.
  const bool foot_pedal = (d1 == kMidiFootPedal);
  if (foot_pedal) {
    // Spec says that if that values 0-63 are OFF, otherwise ON.
    sustain_pedal_ = (d2 >= 64);
  }
}
References kMidiFootPedal, and sustain_pedal_.
HandleNoteOff()
void KeyboardState::HandleNoteOff (uint8_t midi_note, uint8_t velocity, uint32_t now_ms)
Definition at line 149 of file Keyboard.cpp.
{
#ifdef DEBUG_KEYBOARD
  dprint("HandleNoteOff:");
  dprint("midi_note = ");
  dprint(midi_note);
  dprint(", velocity = ");
  dprintln(velocity);
#endif
  Key* key = GetKey(midi_note);
  if (sustain_pedal_) {
    key->SetSustained();
  } else {
    key->SetOff(now_ms);
  }
}
References dprint, dprintln, GetKey(), Key::SetOff(), Key::SetSustained(), and sustain_pedal_.
Referenced by HandleNoteOn().
HandleNoteOn()
void KeyboardState::HandleNoteOn (uint8_t midi_note, uint8_t velocity, int color_selector_value, uint32_t now_ms)
Definition at line 116 of file Keyboard.cpp.
{
  if (0 == velocity) {
    // Some keyboards signify "NoteOff" with a velocity of zero.
    HandleNoteOff(midi_note, velocity, now_ms);
    return;
  }
#ifdef DEBUG_KEYBOARD
  dprint("HandleNoteOn:");
  dprint("midi_note = ");
  dprint(midi_note);
  dprint(", velocity = ");
  dprintln(velocity);
 #endif
  float brightness = ToBrightness(velocity);
  dprint("brightness: "); dprintln(brightness);
  ColorHSV pixel_color_hsv = SelectColor(midi_note, brightness,
                                         color_selector_value);
  // TODO: Give a key access to the Keyboard owner, therefore it could inspect the
  // sustained variable instead of passing it here.
  Key* key = GetKey(midi_note);
  dprint("key indx: "); dprintln(key->idx_);
  key->SetOn(velocity, pixel_color_hsv, now_ms);
}
References brightness, dprint, dprintln, GetKey(), HandleNoteOff(), Key::idx_, SelectColor(), Key::SetOn(), and ToBrightness().
KeyIndex()
uint8_t KeyboardState::KeyIndex (int midi_pitch) static
Definition at line 202 of file Keyboard.cpp.
{
  //return constrain(midi_pitch, 21, 108) - 21;
  return ::KeyIndex(midi_pitch);
}
Referenced by GetKey().
Update()
void KeyboardState::Update (uint32_t now_ms, uint32_t delta_ms)
Definition at line 196 of file Keyboard.cpp.
{
  for (int i = 0; i < kNumKeys; ++i) {
    keys_[i].Update(now_ms, delta_ms, sustain_pedal_);
  }
}
References keys_, kNumKeys, sustain_pedal_, and Key::Update().
Member Data Documentation
keys_
Key KeyboardState::keys_[kNumKeys]
Definition at line 103 of file Keyboard.h.
Referenced by KeyboardState(), GetKey(), Painter::Paint(), Painter::PaintBrightSurprise(), Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), Update(), and Painter::VegasVisualizer().
kNumKeys
const int KeyboardState::kNumKeys = 88 static
Definition at line 101 of file Keyboard.h.
Referenced by KeyboardState(), Painter::Paint(), Painter::PaintBrightSurprise(), and Update().
sustain_pedal_
bool KeyboardState::sustain_pedal_
Definition at line 102 of file Keyboard.h.
Referenced by HandleControlChange(), HandleNoteOff(), Painter::Paint(), and Update().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/Keyboard.h
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/Keyboard.cpp