FastLED: fl::SortedHeapMap< Key, Value, Less > Class Template Reference
fl::SortedHeapMap< Key, Value, Less > Class Template Reference
Detailed Description
template<typename Key, typename Value, typename Less = fl::DefaultLess<Key>>
class fl::SortedHeapMap< Key, Value, Less >
Definition at line 257 of file map.h.
#include <map.h>
Classes
struct Pair
struct PairLess
Public Types
typedef SortedHeapVector< Pair, PairLess >::const_iterator const_iterator
typedef SortedHeapVector< Pair, PairLess >::iterator iterator
typedef Pair value_type
Public Member Functions
SortedHeapMap (Less less=Less())
Value & at (const Key &key)
Pair & back ()
const Pair & back () const
iterator begin ()
const_iterator begin () const
size_t capacity () const
void clear ()
bool contains (const Key &key) const
bool empty () const
iterator end ()
const_iterator end () const
bool erase (const Key &key)
bool erase (iterator it)
iterator find (const Key &key)
const_iterator find (const Key &key) const
Pair & front ()
const Pair & front () const
bool full () const
bool has (const Key &key) const
bool insert (const Key &key, const Value &value, InsertResult *result=nullptr)
iterator lower_bound (const Key &key)
const_iterator lower_bound (const Key &key) const
bool operator!= (const SortedHeapMap &other) const
bool operator== (const SortedHeapMap &other) const
Value & operator[] (const Key &key)
void reserve (size_t n)
void setMaxSize (size_t n)
size_t size () const
void swap (SortedHeapMap &other)
void update (const Key &key, const Value &value)
iterator upper_bound (const Key &key)
const_iterator upper_bound (const Key &key) const
Private Attributes
SortedHeapVector< Pair, PairLess > data
Member Typedef Documentation
const_iterator
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> SortedHeapVector<Pair,PairLess>::const_iterator fl::SortedHeapMap< Key, Value, Less >::const_iterator
Definition at line 279 of file map.h.
iterator
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> SortedHeapVector<Pair,PairLess>::iterator fl::SortedHeapMap< Key, Value, Less >::iterator
Definition at line 278 of file map.h.
value_type
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> Pair fl::SortedHeapMap< Key, Value, Less >::value_type
Definition at line 280 of file map.h.
Constructor & Destructor Documentation
SortedHeapMap()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> fl::SortedHeapMap< Key, Value, Less >::SortedHeapMap (Less less = Less()) inline
Definition at line 282 of file map.h.
        : data(PairLess{less}) {
    }
Member Function Documentation
at()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> Value & fl::SortedHeapMap< Key, Value, Less >::at (const Key & key) inline
Definition at line 309 of file map.h.
{
        iterator it = find(key);
        return it->second;
    }
References fl::SortedHeapMap< Key, Value, Less >::find(), and fl::Pair< Key, Value >::second.
back() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> Pair & fl::SortedHeapMap< Key, Value, Less >::back () inline
Definition at line 391 of file map.h.
{ return data.back(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::get_newest_frame_number().
back() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const Pair & fl::SortedHeapMap< Key, Value, Less >::back () const inline
Definition at line 392 of file map.h.
{ return data.back(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
begin() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> iterator fl::SortedHeapMap< Key, Value, Less >::begin () inline
Definition at line 346 of file map.h.
{ return data.begin(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::SortedHeapMap< Key, Value, Less >::operator==().
begin() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const_iterator fl::SortedHeapMap< Key, Value, Less >::begin () const inline
Definition at line 348 of file map.h.
{ return data.begin(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
capacity()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> size_t fl::SortedHeapMap< Key, Value, Less >::capacity () const inline
Definition at line 342 of file map.h.
{ return data.capacity(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::capacity().
clear()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> void fl::SortedHeapMap< Key, Value, Less >::clear () inline
Definition at line 343 of file map.h.
{ data.clear(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::clear().
contains()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::contains (const Key & key) const inline
Definition at line 318 of file map.h.
{
        return has(key);
    }
References fl::SortedHeapMap< Key, Value, Less >::has().
empty()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::empty () const inline
Definition at line 340 of file map.h.
{ return data.empty(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::empty(), fl::FrameInterpolator::get_newest_frame_number(), and fl::FrameInterpolator::get_oldest_frame_number().
end() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> iterator fl::SortedHeapMap< Key, Value, Less >::end () inline
Definition at line 347 of file map.h.
{ return data.end(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::erase(), fl::FrameInterpolator::get(), fl::SortedHeapMap< Key, Value, Less >::operator==(), fl::SortedHeapMap< Key, Value, Less >::operator[](), fl::SortedHeapMap< Key, Value, Less >::upper_bound(), and fl::SortedHeapMap< Key, Value, Less >::upper_bound().
end() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const_iterator fl::SortedHeapMap< Key, Value, Less >::end () const inline
Definition at line 349 of file map.h.
{ return data.end(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
erase() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::erase (const Key & key) inline
Definition at line 358 of file map.h.
{
        return data.erase(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::erase().
erase() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::erase (iterator it) inline
Definition at line 361 of file map.h.
{
        return data.erase(it);
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
find() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> iterator fl::SortedHeapMap< Key, Value, Less >::find (const Key & key) inline
Definition at line 351 of file map.h.
{
        return data.find(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::SortedHeapMap< Key, Value, Less >::at(), fl::FrameInterpolator::erase(), fl::FrameInterpolator::get(), fl::SortedHeapMap< Key, Value, Less >::operator[](), and fl::SortedHeapMap< Key, Value, Less >::update().
find() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const_iterator fl::SortedHeapMap< Key, Value, Less >::find (const Key & key) const inline
Definition at line 354 of file map.h.
{
        return data.find(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
front() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> Pair & fl::SortedHeapMap< Key, Value, Less >::front () inline
Definition at line 389 of file map.h.
{ return data.front(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::get_oldest_frame_number().
front() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const Pair & fl::SortedHeapMap< Key, Value, Less >::front () const inline
Definition at line 390 of file map.h.
{ return data.front(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
full()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::full () const inline
Definition at line 341 of file map.h.
{ return data.full(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::full().
has()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::has (const Key & key) const inline
Definition at line 314 of file map.h.
{
        return data.has(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::SortedHeapMap< Key, Value, Less >::contains(), and fl::FrameInterpolator::has().
insert()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::insert (const Key & key, const Value & value, InsertResult * result = nullptr) inline
Definition at line 294 of file map.h.
{
        return data.insert(Pair(key, value), result);
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::insert(), and fl::SortedHeapMap< Key, Value, Less >::update().
lower_bound() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> iterator fl::SortedHeapMap< Key, Value, Less >::lower_bound (const Key & key) inline
Definition at line 365 of file map.h.
{
        return data.lower_bound(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::SortedHeapMap< Key, Value, Less >::upper_bound(), and fl::SortedHeapMap< Key, Value, Less >::upper_bound().
lower_bound() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const_iterator fl::SortedHeapMap< Key, Value, Less >::lower_bound (const Key & key) const inline
Definition at line 369 of file map.h.
{
        return data.lower_bound(Pair(key));
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
operator!=()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::operator!= (const SortedHeapMap< Key, Value, Less > & other) const inline
Definition at line 335 of file map.h.
{
        return !(*this == other);
    }
operator==()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> bool fl::SortedHeapMap< Key, Value, Less >::operator== (const SortedHeapMap< Key, Value, Less > & other) const inline
Definition at line 322 of file map.h.
{
        if (size() != other.size()) {
            return false;
        }
        for (const_iterator it = begin(), other_it = other.begin();
             it != end(); ++it, ++other_it) {
            if (it->first != other_it->first || it->second != other_it->second) {
                return false;
            }
        }
        return true;
    }
References fl::SortedHeapMap< Key, Value, Less >::begin(), fl::SortedHeapMap< Key, Value, Less >::end(), and fl::SortedHeapMap< Key, Value, Less >::size().
operator[]()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> Value & fl::SortedHeapMap< Key, Value, Less >::operator[] (const Key & key) inline
Definition at line 395 of file map.h.
{
        iterator it = find(key);
        if (it != end()) {
            return it->second;
        }
        Pair pair(key, Value());
        bool ok = data.insert(pair);
        FASTLED_ASSERT(ok, "Failed to insert into SortedHeapMap");
        return data.find(pair)->second;  // TODO: optimize.
    }
References fl::SortedHeapMap< Key, Value, Less >::data, fl::SortedHeapMap< Key, Value, Less >::end(), FASTLED_ASSERT, fl::SortedHeapMap< Key, Value, Less >::find(), and fl::Pair< Key, Value >::second.
reserve()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> void fl::SortedHeapMap< Key, Value, Less >::reserve (size_t n) inline
Definition at line 290 of file map.h.
{
        data.reserve(n);
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
setMaxSize()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> void fl::SortedHeapMap< Key, Value, Less >::setMaxSize (size_t n) inline
Definition at line 286 of file map.h.
{
        data.setMaxSize(n);
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::FrameInterpolator::FrameInterpolator().
size()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> size_t fl::SortedHeapMap< Key, Value, Less >::size () const inline
Definition at line 339 of file map.h.
{ return data.size(); }
References fl::SortedHeapMap< Key, Value, Less >::data.
Referenced by fl::SortedHeapMap< Key, Value, Less >::operator==().
swap()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> void fl::SortedHeapMap< Key, Value, Less >::swap (SortedHeapMap< Key, Value, Less > & other) inline
Definition at line 305 of file map.h.
{
        data.swap(other.data);
    }
References fl::SortedHeapMap< Key, Value, Less >::data.
update()
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> void fl::SortedHeapMap< Key, Value, Less >::update (const Key & key, const Value & value) inline
Definition at line 298 of file map.h.
{
        if (!insert(key, value)) {
            iterator it = find(key);
            it->second = value;
        }
    }
References fl::SortedHeapMap< Key, Value, Less >::find(), fl::SortedHeapMap< Key, Value, Less >::insert(), and fl::Pair< Key, Value >::second.
upper_bound() [1/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> iterator fl::SortedHeapMap< Key, Value, Less >::upper_bound (const Key & key) inline
Definition at line 373 of file map.h.
{
        iterator it = lower_bound(key);
        if (it != end() && it->first == key) {
            ++it;
        }
        return it;
    }
References fl::SortedHeapMap< Key, Value, Less >::end(), fl::Pair< Key, Value >::first, and fl::SortedHeapMap< Key, Value, Less >::lower_bound().
upper_bound() [2/2]
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> const_iterator fl::SortedHeapMap< Key, Value, Less >::upper_bound (const Key & key) const inline
Definition at line 381 of file map.h.
{
        const_iterator it = lower_bound(key);
        if (it != end() && it->first == key) {
            ++it;
        }
        return it;
    }
References fl::SortedHeapMap< Key, Value, Less >::end(), fl::Pair< Key, Value >::first, and fl::SortedHeapMap< Key, Value, Less >::lower_bound().
Member Data Documentation
data
template<typename Key , typename Value , typename Less = fl::DefaultLess<Key>> SortedHeapVector<Pair, PairLess> fl::SortedHeapMap< Key, Value, Less >::data private
Definition at line 274 of file map.h.
Referenced by fl::SortedHeapMap< Key, Value, Less >::back(), fl::SortedHeapMap< Key, Value, Less >::back(), fl::SortedHeapMap< Key, Value, Less >::begin(), fl::SortedHeapMap< Key, Value, Less >::begin(), fl::SortedHeapMap< Key, Value, Less >::capacity(), fl::SortedHeapMap< Key, Value, Less >::clear(), fl::SortedHeapMap< Key, Value, Less >::empty(), fl::SortedHeapMap< Key, Value, Less >::end(), fl::SortedHeapMap< Key, Value, Less >::end(), fl::SortedHeapMap< Key, Value, Less >::erase(), fl::SortedHeapMap< Key, Value, Less >::erase(), fl::SortedHeapMap< Key, Value, Less >::find(), fl::SortedHeapMap< Key, Value, Less >::find(), fl::SortedHeapMap< Key, Value, Less >::front(), fl::SortedHeapMap< Key, Value, Less >::front(), fl::SortedHeapMap< Key, Value, Less >::full(), fl::SortedHeapMap< Key, Value, Less >::has(), fl::SortedHeapMap< Key, Value, Less >::insert(), fl::SortedHeapMap< Key, Value, Less >::lower_bound(), fl::SortedHeapMap< Key, Value, Less >::lower_bound(), fl::SortedHeapMap< Key, Value, Less >::operator[](), fl::SortedHeapMap< Key, Value, Less >::reserve(), fl::SortedHeapMap< Key, Value, Less >::setMaxSize(), fl::SortedHeapMap< Key, Value, Less >::size(), and fl::SortedHeapMap< Key, Value, Less >::swap().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/map.h