FastLED: fl::EngineEvents Class Reference
fl::EngineEvents Class Reference
Detailed Description
Definition at line 29 of file engine_events.h.
#include <engine_events.h>
Classes
class Listener
Static Public Member Functions
static void addListener (Listener *listener, int priority=0)
static bool hasListener (Listener *listener)
static void onBeginFrame ()
static void onCanvasUiSet (CLEDController *strip, const ScreenMap &xymap)
static void onEndFrame ()
static void onEndShowLeds ()
static void onPlatformPreLoop ()
static void onStripAdded (CLEDController *strip, uint32_t num_leds)
static void removeListener (Listener *listener)
Private Member Functions
EngineEvents ()=default
void _addListener (Listener *listener, int priority)
bool _hasListener (Listener *listener)
void _onBeginFrame ()
void _onCanvasUiSet (CLEDController *strip, const ScreenMap &xymap)
void _onEndFrame ()
void _onEndShowLeds ()
void _onPlatformPreLoop ()
void _onStripAdded (CLEDController *strip, uint32_t num_leds)
void _removeListener (Listener *listener)
Static Private Member Functions
static EngineEvents * getInstance ()
Friends
class fl::Singleton< EngineEvents >
Constructor & Destructor Documentation
EngineEvents()
fl::EngineEvents::EngineEvents () private default
Member Function Documentation
_addListener()
void fl::EngineEvents::_addListener (Listener * listener, int priority) private
Referenced by addListener().
_hasListener()
bool fl::EngineEvents::_hasListener (Listener * listener) private
Referenced by fl::EngineEvents::Listener::~Listener(), and hasListener().
_onBeginFrame()
void fl::EngineEvents::_onBeginFrame () private
Referenced by onBeginFrame().
_onCanvasUiSet()
void fl::EngineEvents::_onCanvasUiSet (CLEDController * strip, const ScreenMap & xymap) private
Referenced by onCanvasUiSet().
_onEndFrame()
void fl::EngineEvents::_onEndFrame () private
Referenced by onEndFrame().
_onEndShowLeds()
void fl::EngineEvents::_onEndShowLeds () private
Referenced by onEndShowLeds().
_onPlatformPreLoop()
void fl::EngineEvents::_onPlatformPreLoop () private
Referenced by onPlatformPreLoop().
_onStripAdded()
void fl::EngineEvents::_onStripAdded (CLEDController * strip, uint32_t num_leds) private
Referenced by onStripAdded().
_removeListener()
void fl::EngineEvents::_removeListener (Listener * listener) private
Referenced by fl::EngineEvents::Listener::~Listener(), and removeListener().
addListener()
static void fl::EngineEvents::addListener (Listener * listener, int priority = 0) inline static
Definition at line 55 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_addListener(listener, priority);
        #else
        (void)listener;
        (void)priority;
        #endif
    }
References _addListener(), and getInstance().
Referenced by CFastLED::addListener().
getInstance()
EngineEvents * EngineEvents::getInstance () static private
Definition at line 29 of file engine_events.cpp.
{
    #if FASTLED_HAS_ENGINE_EVENTS
    return &Singleton<EngineEvents>::instance();
    #else
    return nullptr;  // strip out when engine events are disabled.
    #endif
}
References fl::Singleton< T, N >::instance().
Referenced by fl::EngineEvents::Listener::~Listener(), addListener(), hasListener(), onBeginFrame(), onCanvasUiSet(), onEndFrame(), onEndShowLeds(), onPlatformPreLoop(), onStripAdded(), and removeListener().
hasListener()
static bool fl::EngineEvents::hasListener (Listener * listener) inline static
Definition at line 72 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        return EngineEvents::getInstance()->_hasListener(listener);
        #else
        (void)listener;
        return false;
        #endif
    }
References _hasListener(), and getInstance().
onBeginFrame()
static void fl::EngineEvents::onBeginFrame () inline static
Definition at line 81 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onBeginFrame();
        #endif
    }
References _onBeginFrame(), and getInstance().
Referenced by CFastLED::show().
onCanvasUiSet()
static void fl::EngineEvents::onCanvasUiSet (CLEDController * strip, const ScreenMap & xymap) inline static
Definition at line 109 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onCanvasUiSet(strip, xymap);
        #else
        (void)strip;
        (void)xymap;
        #endif
    }
References _onCanvasUiSet(), getInstance(), and xymap.
Referenced by CLEDController::setScreenMap(), and CLEDController::setScreenMap().
onEndFrame()
static void fl::EngineEvents::onEndFrame () inline static
Definition at line 93 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onEndFrame();
        #endif
    }
References _onEndFrame(), and getInstance().
Referenced by CFastLED::show().
onEndShowLeds()
static void fl::EngineEvents::onEndShowLeds () inline static
Definition at line 87 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onEndShowLeds();
        #endif
    }
References _onEndShowLeds(), and getInstance().
Referenced by CFastLED::show().
onPlatformPreLoop()
static void fl::EngineEvents::onPlatformPreLoop () inline static
Definition at line 118 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onPlatformPreLoop();
        #endif
    }
References _onPlatformPreLoop(), and getInstance().
onStripAdded()
static void fl::EngineEvents::onStripAdded (CLEDController * strip, uint32_t num_leds) inline static
Definition at line 99 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onStripAdded(strip, num_leds);
        #else
        (void)strip;
        (void)num_leds;
        #endif
    }
References _onStripAdded(), and getInstance().
Referenced by CFastLED::addLeds().
removeListener()
static void fl::EngineEvents::removeListener (Listener * listener) inline static
Definition at line 64 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_removeListener(listener);
        #else
        (void)listener;
        #endif
    }
References _removeListener(), and getInstance().
Referenced by CFastLED::removeListener().
Friends And Related Symbol Documentation
fl::Singleton< EngineEvents >
friend class fl::Singleton< EngineEvents > friend
Definition at line 149 of file engine_events.h.
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/engine_events.h
/home/runner/work/FastLED/FastLED/src/fl/engine_events.cpp