FastLED: Palette Classes
Palette Classes
Color Palettes
Detailed Description
Class definitions for color palettes.
Todo
For documentation purposes it would be nice to reorder these definitions by type and in ascending number of entries.
Classes
class CHSVPalette16
HSV color palette with 16 discrete values.
class CHSVPalette256
HSV color palette with 256 discrete values.
class CHSVPalette32
HSV color palette with 32 discrete values.
class CRGBPalette16
RGB color palette with 16 discrete values.
class CRGBPalette256
RGB color palette with 256 discrete values.
class CRGBPalette32
RGB color palette with 32 discrete values.
union TRGBGradientPaletteEntryUnion
Struct for digesting gradient pointer data into its components.
struct TRGBGradientPaletteEntryUnion.__unnamed25__
Typedefs
typedef uint8_t TDynamicRGBGradientPalette_byte
Byte of an RGB gradient entry, stored in dynamic (heap) memory.
typedef const TDynamicRGBGradientPalette_byte * TDynamicRGBGradientPalette_bytes
Pointer to bytes of an RGB gradient, stored in dynamic (heap) memory.
typedef TDynamicRGBGradientPalette_bytes TDynamicRGBGradientPaletteRef
Alias of TDynamicRGBGradientPalette_bytes.
Class Documentation
CHSVPalette16
class CHSVPalette16
Public Member Functions
CHSVPalette16 ()
Default constructor.
CHSVPalette16 (const CHSV &c00, const CHSV &c01, const CHSV &c02, const CHSV &c03, const CHSV &c04, const CHSV &c05, const CHSV &c06, const CHSV &c07, const CHSV &c08, const CHSV &c09, const CHSV &c10, const CHSV &c11, const CHSV &c12, const CHSV &c13, const CHSV &c14, const CHSV &c15)
Create palette from 16 CHSV values.
CHSVPalette16 (const CHSV &c1)
Create palette filled with one color.
CHSVPalette16 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CHSVPalette16 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CHSVPalette16 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CHSVPalette16 (const CHSVPalette16 &rhs)
Copy constructor.
CHSVPalette16 (const TProgmemHSVPalette16 &rhs)
Create palette from palette stored in PROGMEM.
operator CHSV * ()
Get the underlying pointer to the CHSV entries making up the palette.
bool operator!= (const CHSVPalette16 &rhs) const
Check if two palettes do not have the same color entries.
CHSVPalette16 & operator= (const CHSVPalette16 &rhs)
Copy constructor.
CHSVPalette16 & operator= (const TProgmemHSVPalette16 &rhs)
Create palette from palette stored in PROGMEM.
bool operator== (const CHSVPalette16 &rhs) const
Check if two palettes have the same color entries.
CHSV & operator[] (int x)
Array access operator to index into the gradient entries.
const CHSV & operator[] (int x) const
Array access operator to index into the gradient entries.
CHSV & operator[] (uint8_t x)
Array access operator to index into the gradient entries.
const CHSV & operator[] (uint8_t x) const
Array access operator to index into the gradient entries.
Public Attributes
CHSV entries [16]
the color entries that make up the palette
Constructor & Destructor Documentation
CHSVPalette16() [1/8]
CHSVPalette16::CHSVPalette16 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 732 of file colorutils.h.
{};
CHSVPalette16() [2/8]
CHSVPalette16::CHSVPalette16 (const CHSV & c00, const CHSV & c01, const CHSV & c02, const CHSV & c03, const CHSV & c04, const CHSV & c05, const CHSV & c06, const CHSV & c07, const CHSV & c08, const CHSV & c09, const CHSV & c10, const CHSV & c11, const CHSV & c12, const CHSV & c13, const CHSV & c14, const CHSV & c15) inline
Create palette from 16 CHSV values.
Definition at line 735 of file colorutils.h.
    {
        entries[0]=c00; entries[1]=c01; entries[2]=c02; entries[3]=c03;
        entries[4]=c04; entries[5]=c05; entries[6]=c06; entries[7]=c07;
        entries[8]=c08; entries[9]=c09; entries[10]=c10; entries[11]=c11;
        entries[12]=c12; entries[13]=c13; entries[14]=c14; entries[15]=c15;
    };
References entries.
CHSVPalette16() [3/8]
CHSVPalette16::CHSVPalette16 (const CHSVPalette16 & rhs) inline
Copy constructor.
Definition at line 747 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CHSVPalette16() [4/8]
CHSVPalette16::CHSVPalette16 (const TProgmemHSVPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 760 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            CRGB xyz(FL_PGM_READ_DWORD_NEAR( rhs + i));
            entries[i].hue = xyz.red;
            entries[i].sat = xyz.green;
            entries[i].val = xyz.blue;
        }
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
CHSVPalette16() [5/8]
CHSVPalette16::CHSVPalette16 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 839 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 16, c1);
    }
References entries, and fill_solid().
CHSVPalette16() [6/8]
CHSVPalette16::CHSVPalette16 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 847 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2);
    }
References entries, and fill_gradient().
CHSVPalette16() [7/8]
CHSVPalette16::CHSVPalette16 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 856 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2, c3);
    }
References entries, and fill_gradient().
CHSVPalette16() [8/8]
CHSVPalette16::CHSVPalette16 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 866 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
Member Function Documentation
operator CHSV *()
CHSVPalette16::operator CHSV * () inline
Get the underlying pointer to the CHSV entries making up the palette.
Definition at line 812 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CHSVPalette16::operator!= (const CHSVPalette16 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 832 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/2]
CHSVPalette16 & CHSVPalette16::operator= (const CHSVPalette16 & rhs) inline
Copy constructor.
Definition at line 753 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [2/2]
CHSVPalette16 & CHSVPalette16::operator= (const TProgmemHSVPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 771 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            CRGB xyz(FL_PGM_READ_DWORD_NEAR( rhs + i));
            entries[i].hue = xyz.red;
            entries[i].sat = xyz.green;
            entries[i].val = xyz.blue;
        }
        return *this;
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
operator==()
bool CHSVPalette16::operator== (const CHSVPalette16 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 818 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint8_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CHSV & CHSVPalette16::operator[] (int x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 800 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CHSV & CHSVPalette16::operator[] (int x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 806 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CHSV & CHSVPalette16::operator[] (uint8_t x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 788 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CHSV & CHSVPalette16::operator[] (uint8_t x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 794 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CHSV CHSVPalette16::entries[16]
the color entries that make up the palette
Definition at line 729 of file colorutils.h.
Referenced by CHSVPalette16(), CHSVPalette16(), CHSVPalette16(), CHSVPalette16(), CHSVPalette16(), CHSVPalette16(), CHSVPalette16(), CRGBPalette16::CRGBPalette16(), operator CHSV *(), operator=(), operator=(), CRGBPalette16::operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
CHSVPalette256
class CHSVPalette256
Public Member Functions
CHSVPalette256 ()
Default constructor.
CHSVPalette256 (const CHSV &c00, const CHSV &c01, const CHSV &c02, const CHSV &c03, const CHSV &c04, const CHSV &c05, const CHSV &c06, const CHSV &c07, const CHSV &c08, const CHSV &c09, const CHSV &c10, const CHSV &c11, const CHSV &c12, const CHSV &c13, const CHSV &c14, const CHSV &c15)
Create palette from 16 CHSV values.
CHSVPalette256 (const CHSV &c1)
Create palette filled with one color.
CHSVPalette256 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CHSVPalette256 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CHSVPalette256 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CHSVPalette256 (const CHSVPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CHSVPalette256 (const CHSVPalette256 &rhs)
Copy constructor.
CHSVPalette256 (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
operator CHSV * ()
Get the underlying pointer to the CHSV entries making up the palette.
bool operator!= (const CHSVPalette256 &rhs) const
Check if two palettes do not have the same color entries.
CHSVPalette256 & operator= (const CHSVPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CHSVPalette256 & operator= (const CHSVPalette256 &rhs)
Copy constructor.
CHSVPalette256 & operator= (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
bool operator== (const CHSVPalette256 &rhs) const
Check if two palettes have the same color entries.
CHSV & operator[] (int x)
Array access operator to index into the gradient entries.
const CHSV & operator[] (int x) const
Array access operator to index into the gradient entries.
CHSV & operator[] (uint8_t x)
Array access operator to index into the gradient entries.
const CHSV & operator[] (uint8_t x) const
Array access operator to index into the gradient entries.
Public Attributes
CHSV entries [256]
the color entries that make up the palette
Constructor & Destructor Documentation
CHSVPalette256() [1/9]
CHSVPalette256::CHSVPalette256 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 879 of file colorutils.h.
{};
CHSVPalette256() [2/9]
CHSVPalette256::CHSVPalette256 (const CHSV & c00, const CHSV & c01, const CHSV & c02, const CHSV & c03, const CHSV & c04, const CHSV & c05, const CHSV & c06, const CHSV & c07, const CHSV & c08, const CHSV & c09, const CHSV & c10, const CHSV & c11, const CHSV & c12, const CHSV & c13, const CHSV & c14, const CHSV & c15) inline
Create palette from 16 CHSV values.
Definition at line 885 of file colorutils.h.
    {
        CHSVPalette16 p16(c00,c01,c02,c03,c04,c05,c06,c07,
                          c08,c09,c10,c11,c12,c13,c14,c15);
        *this = p16;
    };
CHSVPalette256() [3/9]
CHSVPalette256::CHSVPalette256 (const CHSVPalette256 & rhs) inline
Copy constructor.
Definition at line 896 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CHSVPalette256() [4/9]
CHSVPalette256::CHSVPalette256 (const CHSVPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 908 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
    }
References UpscalePalette().
CHSVPalette256() [5/9]
CHSVPalette256::CHSVPalette256 (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 920 of file colorutils.h.
    {
        CHSVPalette16 p16(rhs);
        *this = p16;
    }
CHSVPalette256() [6/9]
CHSVPalette256::CHSVPalette256 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 982 of file colorutils.h.
    {
      fill_solid( &(entries[0]), 256, c1);
    }
References entries, and fill_solid().
CHSVPalette256() [7/9]
CHSVPalette256::CHSVPalette256 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 987 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2);
    }
References entries, and fill_gradient().
CHSVPalette256() [8/9]
CHSVPalette256::CHSVPalette256 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 992 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2, c3);
    }
References entries, and fill_gradient().
CHSVPalette256() [9/9]
CHSVPalette256::CHSVPalette256 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 997 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
Member Function Documentation
operator CHSV *()
CHSVPalette256::operator CHSV * () inline
Get the underlying pointer to the CHSV entries making up the palette.
Definition at line 956 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CHSVPalette256::operator!= (const CHSVPalette256 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 976 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/3]
CHSVPalette256 & CHSVPalette256::operator= (const CHSVPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 913 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
        return *this;
    }
References UpscalePalette().
operator=() [2/3]
CHSVPalette256 & CHSVPalette256::operator= (const CHSVPalette256 & rhs) inline
Copy constructor.
Definition at line 901 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [3/3]
CHSVPalette256 & CHSVPalette256::operator= (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 926 of file colorutils.h.
    {
        CHSVPalette16 p16(rhs);
        *this = p16;
        return *this;
    }
operator==()
bool CHSVPalette256::operator== (const CHSVPalette256 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 962 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint16_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CHSV & CHSVPalette256::operator[] (int x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 945 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CHSV & CHSVPalette256::operator[] (int x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 950 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CHSV & CHSVPalette256::operator[] (uint8_t x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 934 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CHSV & CHSVPalette256::operator[] (uint8_t x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 939 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CHSV CHSVPalette256::entries[256]
the color entries that make up the palette
Definition at line 876 of file colorutils.h.
Referenced by CHSVPalette256(), CHSVPalette256(), CHSVPalette256(), CHSVPalette256(), CHSVPalette256(), CRGBPalette256::CRGBPalette256(), operator CHSV *(), operator=(), CRGBPalette256::operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
CHSVPalette32
class CHSVPalette32
Public Member Functions
CHSVPalette32 ()
Default constructor.
CHSVPalette32 (const CHSV &c00, const CHSV &c01, const CHSV &c02, const CHSV &c03, const CHSV &c04, const CHSV &c05, const CHSV &c06, const CHSV &c07, const CHSV &c08, const CHSV &c09, const CHSV &c10, const CHSV &c11, const CHSV &c12, const CHSV &c13, const CHSV &c14, const CHSV &c15)
Create palette from 16 CHSV values.
CHSVPalette32 (const CHSV &c1)
Create palette filled with one color.
CHSVPalette32 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CHSVPalette32 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CHSVPalette32 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CHSVPalette32 (const CHSVPalette32 &rhs)
Copy constructor.
CHSVPalette32 (const TProgmemHSVPalette32 &rhs)
Create palette from palette stored in PROGMEM.
operator CHSV * ()
Get the underlying pointer to the CHSV entries making up the palette.
bool operator!= (const CHSVPalette32 &rhs) const
Check if two palettes do not have the same color entries.
CHSVPalette32 & operator= (const CHSVPalette32 &rhs)
Copy constructor.
CHSVPalette32 & operator= (const TProgmemHSVPalette32 &rhs)
Create palette from palette stored in PROGMEM.
bool operator== (const CHSVPalette32 &rhs) const
Check if two palettes have the same color entries.
CHSV & operator[] (int x)
Create palette from palette stored in PROGMEM.
const CHSV & operator[] (int x) const
Create palette from palette stored in PROGMEM.
CHSV & operator[] (uint8_t x)
Create palette from palette stored in PROGMEM.
const CHSV & operator[] (uint8_t x) const
Create palette from palette stored in PROGMEM.
Public Attributes
CHSV entries [32]
the color entries that make up the palette
Constructor & Destructor Documentation
CHSVPalette32() [1/8]
CHSVPalette32::CHSVPalette32 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 1312 of file colorutils.h.
{};
CHSVPalette32() [2/8]
CHSVPalette32::CHSVPalette32 (const CHSV & c00, const CHSV & c01, const CHSV & c02, const CHSV & c03, const CHSV & c04, const CHSV & c05, const CHSV & c06, const CHSV & c07, const CHSV & c08, const CHSV & c09, const CHSV & c10, const CHSV & c11, const CHSV & c12, const CHSV & c13, const CHSV & c14, const CHSV & c15) inline
Create palette from 16 CHSV values.
Definition at line 1318 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 2; ++i) {
            entries[0+i]=c00; entries[2+i]=c01; entries[4+i]=c02; entries[6+i]=c03;
            entries[8+i]=c04; entries[10+i]=c05; entries[12+i]=c06; entries[14+i]=c07;
            entries[16+i]=c08; entries[18+i]=c09; entries[20+i]=c10; entries[22+i]=c11;
            entries[24+i]=c12; entries[26+i]=c13; entries[28+i]=c14; entries[30+i]=c15;
        }
    };
References entries.
CHSVPalette32() [3/8]
CHSVPalette32::CHSVPalette32 (const CHSVPalette32 & rhs) inline
Copy constructor.
Definition at line 1332 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CHSVPalette32() [4/8]
CHSVPalette32::CHSVPalette32 (const TProgmemHSVPalette32 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1344 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            CRGB xyz(FL_PGM_READ_DWORD_NEAR( rhs + i));
            entries[i].hue = xyz.red;
            entries[i].sat = xyz.green;
            entries[i].val = xyz.blue;
        }
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
CHSVPalette32() [5/8]
CHSVPalette32::CHSVPalette32 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1413 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 32, c1);
    }
References entries, and fill_solid().
CHSVPalette32() [6/8]
CHSVPalette32::CHSVPalette32 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1418 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2);
    }
References entries, and fill_gradient().
CHSVPalette32() [7/8]
CHSVPalette32::CHSVPalette32 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1423 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2, c3);
    }
References entries, and fill_gradient().
CHSVPalette32() [8/8]
CHSVPalette32::CHSVPalette32 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1428 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
Member Function Documentation
operator CHSV *()
CHSVPalette32::operator CHSV * () inline
Get the underlying pointer to the CHSV entries making up the palette.
Definition at line 1388 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CHSVPalette32::operator!= (const CHSVPalette32 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 1407 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/2]
CHSVPalette32 & CHSVPalette32::operator= (const CHSVPalette32 & rhs) inline
Copy constructor.
Definition at line 1337 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [2/2]
CHSVPalette32 & CHSVPalette32::operator= (const TProgmemHSVPalette32 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1354 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            CRGB xyz(FL_PGM_READ_DWORD_NEAR( rhs + i));
            entries[i].hue = xyz.red;
            entries[i].sat = xyz.green;
            entries[i].val = xyz.blue;
        }
        return *this;
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
operator==()
bool CHSVPalette32::operator== (const CHSVPalette32 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 1394 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint8_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CHSV & CHSVPalette32::operator[] (int x) inline
Create palette from palette stored in PROGMEM.
Definition at line 1377 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CHSV & CHSVPalette32::operator[] (int x) const inline
Create palette from palette stored in PROGMEM.
Definition at line 1382 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CHSV & CHSVPalette32::operator[] (uint8_t x) inline
Create palette from palette stored in PROGMEM.
Definition at line 1366 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CHSV & CHSVPalette32::operator[] (uint8_t x) const inline
Create palette from palette stored in PROGMEM.
Definition at line 1371 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CHSV CHSVPalette32::entries[32]
the color entries that make up the palette
Definition at line 1309 of file colorutils.h.
Referenced by CHSVPalette32(), CHSVPalette32(), CHSVPalette32(), CHSVPalette32(), CHSVPalette32(), CHSVPalette32(), CHSVPalette32(), CRGBPalette32::CRGBPalette32(), operator CHSV *(), operator=(), operator=(), CRGBPalette32::operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
CRGBPalette16
class CRGBPalette16
Public Member Functions
CRGBPalette16 ()
Default constructor.
CRGBPalette16 (const CHSV &c1)
Create palette filled with one color.
CRGBPalette16 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CRGBPalette16 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CRGBPalette16 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CRGBPalette16 (const CHSV rhs[16])
Create palette from array of CHSV colors.
CRGBPalette16 (const CHSVPalette16 &rhs)
Create palette from CHSV palette.
CRGBPalette16 (const CRGB &c00, const CRGB &c01, const CRGB &c02, const CRGB &c03, const CRGB &c04, const CRGB &c05, const CRGB &c06, const CRGB &c07, const CRGB &c08, const CRGB &c09, const CRGB &c10, const CRGB &c11, const CRGB &c12, const CRGB &c13, const CRGB &c14, const CRGB &c15)
Create palette from 16 CRGB values.
CRGBPalette16 (const CRGB &c1)
Create palette filled with one color.
CRGBPalette16 (const CRGB &c1, const CRGB &c2)
Create palette with a gradient from one color to another.
CRGBPalette16 (const CRGB &c1, const CRGB &c2, const CRGB &c3)
Create palette with three-color gradient.
CRGBPalette16 (const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Create palette with four-color gradient.
CRGBPalette16 (const CRGB rhs[16])
Create palette from array of CRGB colors.
CRGBPalette16 (const CRGBPalette16 &rhs)
Copy constructor.
CRGBPalette16 (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette16 (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
CRGBPalette16 & loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal)
Creates a palette from a gradient palette in dynamic (heap) memory.
operator CRGB * ()
Get the underlying pointer to the CHSV entries making up the palette.
bool operator!= (const CRGBPalette16 &rhs) const
Check if two palettes do not have the same color entries.
CRGBPalette16 & operator= (const CHSV rhs[16])
Create palette from array of CHSV colors.
CRGBPalette16 & operator= (const CHSVPalette16 &rhs)
Create palette from CHSV palette.
CRGBPalette16 & operator= (const CRGB rhs[16])
Create palette from array of CRGB colors.
CRGBPalette16 & operator= (const CRGBPalette16 &rhs)
Copy constructor.
CRGBPalette16 & operator= (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette16 & operator= (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
bool operator== (const CRGBPalette16 &rhs) const
Check if two palettes have the same color entries.
CRGB & operator[] (int x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (int x) const
Array access operator to index into the gradient entries.
CRGB & operator[] (uint8_t x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (uint8_t x) const
Array access operator to index into the gradient entries.
Public Attributes
CRGB entries [16]
the color entries that make up the palette
Constructor & Destructor Documentation
CRGBPalette16() [1/16]
CRGBPalette16::CRGBPalette16 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 1009 of file colorutils.h.
{};
CRGBPalette16() [2/16]
CRGBPalette16::CRGBPalette16 (const CRGB & c00, const CRGB & c01, const CRGB & c02, const CRGB & c03, const CRGB & c04, const CRGB & c05, const CRGB & c06, const CRGB & c07, const CRGB & c08, const CRGB & c09, const CRGB & c10, const CRGB & c11, const CRGB & c12, const CRGB & c13, const CRGB & c14, const CRGB & c15) inline
Create palette from 16 CRGB values.
Definition at line 1012 of file colorutils.h.
    {
        entries[0]=c00; entries[1]=c01; entries[2]=c02; entries[3]=c03;
        entries[4]=c04; entries[5]=c05; entries[6]=c06; entries[7]=c07;
        entries[8]=c08; entries[9]=c09; entries[10]=c10; entries[11]=c11;
        entries[12]=c12; entries[13]=c13; entries[14]=c14; entries[15]=c15;
    };
References entries.
CRGBPalette16() [3/16]
CRGBPalette16::CRGBPalette16 (const CRGBPalette16 & rhs) inline
Copy constructor.
Definition at line 1024 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette16() [4/16]
CRGBPalette16::CRGBPalette16 (const CRGB rhs[16]) inline
Create palette from array of CRGB colors.
Definition at line 1029 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette16() [5/16]
CRGBPalette16::CRGBPalette16 (const CHSVPalette16 & rhs) inline
Create palette from CHSV palette.
Definition at line 1047 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
    }
References CHSVPalette16::entries, and entries.
CRGBPalette16() [6/16]
CRGBPalette16::CRGBPalette16 (const CHSV rhs[16]) inline
Create palette from array of CHSV colors.
Definition at line 1054 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
    }
References entries.
CRGBPalette16() [7/16]
CRGBPalette16::CRGBPalette16 (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1078 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] =  FL_PGM_READ_DWORD_NEAR( rhs + i);
        }
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
CRGBPalette16() [8/16]
CRGBPalette16::CRGBPalette16 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1140 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 16, c1);
    }
References entries, and fill_solid().
CRGBPalette16() [9/16]
CRGBPalette16::CRGBPalette16 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1145 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2);
    }
References entries, and fill_gradient().
CRGBPalette16() [10/16]
CRGBPalette16::CRGBPalette16 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1150 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2, c3);
    }
References entries, and fill_gradient().
CRGBPalette16() [11/16]
CRGBPalette16::CRGBPalette16 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1155 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 16, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
CRGBPalette16() [12/16]
CRGBPalette16::CRGBPalette16 (const CRGB & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1161 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 16, c1);
    }
References entries, and fill_solid().
CRGBPalette16() [13/16]
CRGBPalette16::CRGBPalette16 (const CRGB & c1, const CRGB & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1166 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 16, c1, c2);
    }
References entries, and fill_gradient_RGB().
CRGBPalette16() [14/16]
CRGBPalette16::CRGBPalette16 (const CRGB & c1, const CRGB & c2, const CRGB & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1171 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 16, c1, c2, c3);
    }
References entries, and fill_gradient_RGB().
CRGBPalette16() [15/16]
CRGBPalette16::CRGBPalette16 (const CRGB & c1, const CRGB & c2, const CRGB & c3, const CRGB & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1176 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 16, c1, c2, c3, c4);
    }
References entries, and fill_gradient_RGB().
CRGBPalette16() [16/16]
CRGBPalette16::CRGBPalette16 (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1210 of file colorutils.h.
    {
        *this = progpal;
    }
Member Function Documentation
loadDynamicGradientPalette()
CRGBPalette16 & CRGBPalette16::loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal) inline
Creates a palette from a gradient palette in dynamic (heap) memory.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1259 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* ent = (TRGBGradientPaletteEntryUnion*)(gpal);
        TRGBGradientPaletteEntryUnion u;
        // Count entries
        uint16_t count = 0;
        do {
            u = *(ent + count);
            ++count;
        } while ( u.index != 255);
        int8_t lastSlotUsed = -1;
        u = *ent;
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        uint8_t istart8 = 0;
        uint8_t iend8 = 0;
        while( indexstart < 255) {
            ++ent;
            u = *ent;
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            istart8 = indexstart / 16;
            iend8   = indexend   / 16;
            if( count < 16) {
                if( (istart8 <= lastSlotUsed) && (lastSlotUsed < 15)) {
                    istart8 = lastSlotUsed + 1;
                    if( iend8 < istart8) {
                        iend8 = istart8;
                    }
                }
                lastSlotUsed = iend8;
            }
            fill_gradient_RGB( &(entries[0]), istart8, rgbstart, iend8, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References entries, and fill_gradient_RGB().
operator CRGB *()
CRGBPalette16::operator CRGB * () inline
Get the underlying pointer to the CHSV entries making up the palette.
Definition at line 1134 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CRGBPalette16::operator!= (const CRGBPalette16 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 1107 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/6]
CRGBPalette16 & CRGBPalette16::operator= (const CHSV rhs[16]) inline
Create palette from array of CHSV colors.
Definition at line 1069 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References entries.
operator=() [2/6]
CRGBPalette16 & CRGBPalette16::operator= (const CHSVPalette16 & rhs) inline
Create palette from CHSV palette.
Definition at line 1061 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References CHSVPalette16::entries, and entries.
operator=() [3/6]
CRGBPalette16 & CRGBPalette16::operator= (const CRGB rhs[16]) inline
Create palette from array of CRGB colors.
Definition at line 1040 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [4/6]
CRGBPalette16 & CRGBPalette16::operator= (const CRGBPalette16 & rhs) inline
Copy constructor.
Definition at line 1034 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [5/6]
CRGBPalette16 & CRGBPalette16::operator= (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1085 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 16; ++i) {
            entries[i] =  FL_PGM_READ_DWORD_NEAR( rhs + i);
        }
        return *this;
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
operator=() [6/6]
CRGBPalette16 & CRGBPalette16::operator= (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1215 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* progent = (TRGBGradientPaletteEntryUnion*)(progpal);
        TRGBGradientPaletteEntryUnion u;
        // Count entries
        uint16_t count = 0;
        do {
            u.dword = FL_PGM_READ_DWORD_NEAR(progent + count);
            ++count;
        } while ( u.index != 255);
        int8_t lastSlotUsed = -1;
        u.dword = FL_PGM_READ_DWORD_NEAR( progent);
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        uint8_t istart8 = 0;
        uint8_t iend8 = 0;
        while( indexstart < 255) {
            ++progent;
            u.dword = FL_PGM_READ_DWORD_NEAR( progent);
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            istart8 = indexstart / 16;
            iend8   = indexend   / 16;
            if( count < 16) {
                if( (istart8 <= lastSlotUsed) && (lastSlotUsed < 15)) {
                    istart8 = lastSlotUsed + 1;
                    if( iend8 < istart8) {
                        iend8 = istart8;
                    }
                }
                lastSlotUsed = iend8;
            }
            fill_gradient_RGB( &(entries[0]), istart8, rgbstart, iend8, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References TRGBGradientPaletteEntryUnion::dword, entries, fill_gradient_RGB(), and FL_PGM_READ_DWORD_NEAR.
operator==()
bool CRGBPalette16::operator== (const CRGBPalette16 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 1094 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint8_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CRGB & CRGBPalette16::operator[] (int x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1123 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CRGB & CRGBPalette16::operator[] (int x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1128 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CRGB & CRGBPalette16::operator[] (uint8_t x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1112 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CRGB & CRGBPalette16::operator[] (uint8_t x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1117 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CRGB CRGBPalette16::entries[16]
the color entries that make up the palette
Definition at line 1006 of file colorutils.h.
Referenced by CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), CRGBPalette16(), loadDynamicGradientPalette(), nblendPaletteTowardPalette(), operator CRGB *(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
CRGBPalette256
class CRGBPalette256
Public Member Functions
CRGBPalette256 ()
Default constructor.
CRGBPalette256 (const CHSV &c1)
Create palette filled with one color.
CRGBPalette256 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CRGBPalette256 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CRGBPalette256 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CRGBPalette256 (const CHSV rhs[256])
Create palette from array of CHSV colors.
CRGBPalette256 (const CHSVPalette256 &rhs)
Create palette from CHSV palette.
CRGBPalette256 (const CRGB &c00, const CRGB &c01, const CRGB &c02, const CRGB &c03, const CRGB &c04, const CRGB &c05, const CRGB &c06, const CRGB &c07, const CRGB &c08, const CRGB &c09, const CRGB &c10, const CRGB &c11, const CRGB &c12, const CRGB &c13, const CRGB &c14, const CRGB &c15)
Create palette from 16 CRGB values.
CRGBPalette256 (const CRGB &c1)
Create palette filled with one color.
CRGBPalette256 (const CRGB &c1, const CRGB &c2)
Create palette with a gradient from one color to another.
CRGBPalette256 (const CRGB &c1, const CRGB &c2, const CRGB &c3)
Create palette with three-color gradient.
CRGBPalette256 (const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Create palette with four-color gradient.
CRGBPalette256 (const CRGB rhs[256])
Create palette from array of CRGB colors.
CRGBPalette256 (const CRGBPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CRGBPalette256 (const CRGBPalette256 &rhs)
Copy constructor.
CRGBPalette256 (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette256 (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
CRGBPalette256 & loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal)
Creates a palette from a gradient palette in dynamic (heap) memory.
operator CRGB * ()
Get the underlying pointer to the CHSV entries making up the palette.
bool operator!= (const CRGBPalette256 &rhs) const
Check if two palettes do not have the same color entries.
CRGBPalette256 & operator= (const CHSV rhs[256])
Create palette from array of CHSV colors.
CRGBPalette256 & operator= (const CHSVPalette256 &rhs)
Copy constructor.
CRGBPalette256 & operator= (const CRGB rhs[256])
Create palette from array of CRGB colors.
CRGBPalette256 & operator= (const CRGBPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CRGBPalette256 & operator= (const CRGBPalette256 &rhs)
Copy constructor.
CRGBPalette256 & operator= (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette256 & operator= (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
bool operator== (const CRGBPalette256 &rhs) const
Check if two palettes have the same color entries.
CRGB & operator[] (int x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (int x) const
Array access operator to index into the gradient entries.
CRGB & operator[] (uint8_t x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (uint8_t x) const
Array access operator to index into the gradient entries.
Public Attributes
CRGB entries [256]
the color entries that make up the palette
Constructor & Destructor Documentation
CRGBPalette256() [1/17]
CRGBPalette256::CRGBPalette256 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 1750 of file colorutils.h.
{};
CRGBPalette256() [2/17]
CRGBPalette256::CRGBPalette256 (const CRGB & c00, const CRGB & c01, const CRGB & c02, const CRGB & c03, const CRGB & c04, const CRGB & c05, const CRGB & c06, const CRGB & c07, const CRGB & c08, const CRGB & c09, const CRGB & c10, const CRGB & c11, const CRGB & c12, const CRGB & c13, const CRGB & c14, const CRGB & c15) inline
Create palette from 16 CRGB values.
Definition at line 1757 of file colorutils.h.
    {
        CRGBPalette16 p16(c00,c01,c02,c03,c04,c05,c06,c07,
                          c08,c09,c10,c11,c12,c13,c14,c15);
        *this = p16;
    };
CRGBPalette256() [3/17]
CRGBPalette256::CRGBPalette256 (const CRGBPalette256 & rhs) inline
Copy constructor.
Definition at line 1768 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette256() [4/17]
CRGBPalette256::CRGBPalette256 (const CRGB rhs[256]) inline
Create palette from array of CRGB colors.
Definition at line 1773 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette256() [5/17]
CRGBPalette256::CRGBPalette256 (const CHSVPalette256 & rhs) inline
Create palette from CHSV palette.
Definition at line 1791 of file colorutils.h.
    {
        for( int i = 0; i < 256; ++i) {
           entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
    }
References CHSVPalette256::entries, and entries.
CRGBPalette256() [6/17]
CRGBPalette256::CRGBPalette256 (const CHSV rhs[256]) inline
Create palette from array of CHSV colors.
Definition at line 1798 of file colorutils.h.
    {
        for( int i = 0; i < 256; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
    }
References entries.
CRGBPalette256() [7/17]
CRGBPalette256::CRGBPalette256 (const CRGBPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 1822 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
    }
References UpscalePalette().
CRGBPalette256() [8/17]
CRGBPalette256::CRGBPalette256 (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1834 of file colorutils.h.
    {
        CRGBPalette16 p16(rhs);
        *this = p16;
    }
CRGBPalette256() [9/17]
CRGBPalette256::CRGBPalette256 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1895 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 256, c1);
    }
References entries, and fill_solid().
CRGBPalette256() [10/17]
CRGBPalette256::CRGBPalette256 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1900 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2);
    }
References entries, and fill_gradient().
CRGBPalette256() [11/17]
CRGBPalette256::CRGBPalette256 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1905 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2, c3);
    }
References entries, and fill_gradient().
CRGBPalette256() [12/17]
CRGBPalette256::CRGBPalette256 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1910 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 256, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
CRGBPalette256() [13/17]
CRGBPalette256::CRGBPalette256 (const CRGB & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1916 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 256, c1);
    }
References entries, and fill_solid().
CRGBPalette256() [14/17]
CRGBPalette256::CRGBPalette256 (const CRGB & c1, const CRGB & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1921 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 256, c1, c2);
    }
References entries, and fill_gradient_RGB().
CRGBPalette256() [15/17]
CRGBPalette256::CRGBPalette256 (const CRGB & c1, const CRGB & c2, const CRGB & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1926 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 256, c1, c2, c3);
    }
References entries, and fill_gradient_RGB().
CRGBPalette256() [16/17]
CRGBPalette256::CRGBPalette256 (const CRGB & c1, const CRGB & c2, const CRGB & c3, const CRGB & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1931 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 256, c1, c2, c3, c4);
    }
References entries, and fill_gradient_RGB().
CRGBPalette256() [17/17]
CRGBPalette256::CRGBPalette256 (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1937 of file colorutils.h.
    {
        *this = progpal;
    }
Member Function Documentation
loadDynamicGradientPalette()
CRGBPalette256 & CRGBPalette256::loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal) inline
Creates a palette from a gradient palette in dynamic (heap) memory.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1962 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* ent = (TRGBGradientPaletteEntryUnion*)(gpal);
        TRGBGradientPaletteEntryUnion u;
        u = *ent;
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        while( indexstart < 255) {
            ++ent;
            u = *ent;
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            fill_gradient_RGB( &(entries[0]), indexstart, rgbstart, indexend, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References entries, and fill_gradient_RGB().
operator CRGB *()
CRGBPalette256::operator CRGB * () inline
Get the underlying pointer to the CHSV entries making up the palette.
Definition at line 1889 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CRGBPalette256::operator!= (const CRGBPalette256 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 1861 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/7]
CRGBPalette256 & CRGBPalette256::operator= (const CHSV rhs[256]) inline
Create palette from array of CHSV colors.
Definition at line 1813 of file colorutils.h.
    {
        for( int i = 0; i < 256; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References entries.
operator=() [2/7]
CRGBPalette256 & CRGBPalette256::operator= (const CHSVPalette256 & rhs) inline
Copy constructor.
Definition at line 1805 of file colorutils.h.
    {
        for( int i = 0; i < 256; ++i) {
            entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References CHSVPalette256::entries, and entries.
operator=() [3/7]
CRGBPalette256 & CRGBPalette256::operator= (const CRGB rhs[256]) inline
Create palette from array of CRGB colors.
Definition at line 1784 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [4/7]
CRGBPalette256 & CRGBPalette256::operator= (const CRGBPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 1827 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
        return *this;
    }
References UpscalePalette().
operator=() [5/7]
CRGBPalette256 & CRGBPalette256::operator= (const CRGBPalette256 & rhs) inline
Copy constructor.
Definition at line 1778 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [6/7]
CRGBPalette256 & CRGBPalette256::operator= (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1840 of file colorutils.h.
    {
        CRGBPalette16 p16(rhs);
        *this = p16;
        return *this;
    }
operator=() [7/7]
CRGBPalette256 & CRGBPalette256::operator= (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1942 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* progent = (TRGBGradientPaletteEntryUnion*)(progpal);
        TRGBGradientPaletteEntryUnion u;
        u.dword = FL_PGM_READ_DWORD_NEAR( progent);
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        while( indexstart < 255) {
            ++progent;
            u.dword = FL_PGM_READ_DWORD_NEAR( progent);
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            fill_gradient_RGB( &(entries[0]), indexstart, rgbstart, indexend, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References TRGBGradientPaletteEntryUnion::dword, entries, fill_gradient_RGB(), and FL_PGM_READ_DWORD_NEAR.
operator==()
bool CRGBPalette256::operator== (const CRGBPalette256 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 1848 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint16_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CRGB & CRGBPalette256::operator[] (int x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1878 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CRGB & CRGBPalette256::operator[] (int x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1883 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CRGB & CRGBPalette256::operator[] (uint8_t x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1867 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CRGB & CRGBPalette256::operator[] (uint8_t x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1872 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CRGB CRGBPalette256::entries[256]
the color entries that make up the palette
Definition at line 1747 of file colorutils.h.
Referenced by CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), CRGBPalette256(), loadDynamicGradientPalette(), operator CRGB *(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
CRGBPalette32
class CRGBPalette32
Public Member Functions
CRGBPalette32 ()
Default constructor.
CRGBPalette32 (const CHSV &c1)
Create palette filled with one color.
CRGBPalette32 (const CHSV &c1, const CHSV &c2)
Create palette with a gradient from one color to another.
CRGBPalette32 (const CHSV &c1, const CHSV &c2, const CHSV &c3)
Create palette with three-color gradient.
CRGBPalette32 (const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4)
Create palette with four-color gradient.
CRGBPalette32 (const CHSV rhs[32])
Create palette from array of CHSV colors.
CRGBPalette32 (const CHSVPalette32 &rhs)
Create palette from CHSV palette.
CRGBPalette32 (const CRGB &c00, const CRGB &c01, const CRGB &c02, const CRGB &c03, const CRGB &c04, const CRGB &c05, const CRGB &c06, const CRGB &c07, const CRGB &c08, const CRGB &c09, const CRGB &c10, const CRGB &c11, const CRGB &c12, const CRGB &c13, const CRGB &c14, const CRGB &c15)
Create palette from 16 CRGB values.
CRGBPalette32 (const CRGB &c1)
Create palette filled with one color.
CRGBPalette32 (const CRGB &c1, const CRGB &c2)
Create palette with a gradient from one color to another.
CRGBPalette32 (const CRGB &c1, const CRGB &c2, const CRGB &c3)
Create palette with three-color gradient.
CRGBPalette32 (const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Create palette with four-color gradient.
CRGBPalette32 (const CRGB rhs[32])
Create palette from array of CRGB colors.
CRGBPalette32 (const CRGBPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CRGBPalette32 (const CRGBPalette32 &rhs)
Copy constructor.
CRGBPalette32 (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette32 (const TProgmemRGBPalette32 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette32 (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
CRGBPalette32 & loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal)
Creates a palette from a gradient palette in dynamic (heap) memory.
operator CRGB * ()
Get the underlying pointer to the CRGB entries making up the palette.
bool operator!= (const CRGBPalette32 &rhs) const
Check if two palettes do not have the same color entries.
CRGBPalette32 & operator= (const CHSV rhs[32])
Create palette from array of CHSV colors.
CRGBPalette32 & operator= (const CHSVPalette32 &rhs)
Create palette from CHSV palette.
CRGBPalette32 & operator= (const CRGB rhs[32])
Create palette from array of CRGB colors.
CRGBPalette32 & operator= (const CRGBPalette16 &rhs16)
Create upscaled palette from 16-entry palette.
CRGBPalette32 & operator= (const CRGBPalette32 &rhs)
Copy constructor.
CRGBPalette32 & operator= (const TProgmemRGBPalette16 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette32 & operator= (const TProgmemRGBPalette32 &rhs)
Create palette from palette stored in PROGMEM.
CRGBPalette32 & operator= (TProgmemRGBGradientPalette_bytes progpal)
Creates a palette from a gradient palette in PROGMEM.
bool operator== (const CRGBPalette32 &rhs) const
Check if two palettes have the same color entries.
CRGB & operator[] (int x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (int x) const
Array access operator to index into the gradient entries.
CRGB & operator[] (uint8_t x)
Array access operator to index into the gradient entries.
const CRGB & operator[] (uint8_t x) const
Array access operator to index into the gradient entries.
Public Attributes
CRGB entries [32]
the color entries that make up the palette
Constructor & Destructor Documentation
CRGBPalette32() [1/18]
CRGBPalette32::CRGBPalette32 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 1441 of file colorutils.h.
{};
CRGBPalette32() [2/18]
CRGBPalette32::CRGBPalette32 (const CRGB & c00, const CRGB & c01, const CRGB & c02, const CRGB & c03, const CRGB & c04, const CRGB & c05, const CRGB & c06, const CRGB & c07, const CRGB & c08, const CRGB & c09, const CRGB & c10, const CRGB & c11, const CRGB & c12, const CRGB & c13, const CRGB & c14, const CRGB & c15) inline
Create palette from 16 CRGB values.
Definition at line 1448 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 2; ++i) {
            entries[0+i]=c00; entries[2+i]=c01; entries[4+i]=c02; entries[6+i]=c03;
            entries[8+i]=c04; entries[10+i]=c05; entries[12+i]=c06; entries[14+i]=c07;
            entries[16+i]=c08; entries[18+i]=c09; entries[20+i]=c10; entries[22+i]=c11;
            entries[24+i]=c12; entries[26+i]=c13; entries[28+i]=c14; entries[30+i]=c15;
        }
    };
References entries.
CRGBPalette32() [3/18]
CRGBPalette32::CRGBPalette32 (const CRGBPalette32 & rhs) inline
Copy constructor.
Definition at line 1462 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette32() [4/18]
CRGBPalette32::CRGBPalette32 (const CRGB rhs[32]) inline
Create palette from array of CRGB colors.
Definition at line 1467 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
    }
References entries, and memmove8().
CRGBPalette32() [5/18]
CRGBPalette32::CRGBPalette32 (const CHSVPalette32 & rhs) inline
Create palette from CHSV palette.
Definition at line 1485 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
    }
References CHSVPalette32::entries, and entries.
CRGBPalette32() [6/18]
CRGBPalette32::CRGBPalette32 (const CHSV rhs[32]) inline
Create palette from array of CHSV colors.
Definition at line 1492 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
    }
References entries.
CRGBPalette32() [7/18]
CRGBPalette32::CRGBPalette32 (const TProgmemRGBPalette32 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1516 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] =  FL_PGM_READ_DWORD_NEAR( rhs + i);
        }
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
CRGBPalette32() [8/18]
CRGBPalette32::CRGBPalette32 (const CHSV & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1579 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 32, c1);
    }
References entries, and fill_solid().
CRGBPalette32() [9/18]
CRGBPalette32::CRGBPalette32 (const CHSV & c1, const CHSV & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1584 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2);
    }
References entries, and fill_gradient().
CRGBPalette32() [10/18]
CRGBPalette32::CRGBPalette32 (const CHSV & c1, const CHSV & c2, const CHSV & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1589 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2, c3);
    }
References entries, and fill_gradient().
CRGBPalette32() [11/18]
CRGBPalette32::CRGBPalette32 (const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1594 of file colorutils.h.
    {
        fill_gradient( &(entries[0]), 32, c1, c2, c3, c4);
    }
References entries, and fill_gradient().
CRGBPalette32() [12/18]
CRGBPalette32::CRGBPalette32 (const CRGB & c1) inline
Create palette filled with one color.
Parameters
c1 the color to fill the palette with
Definition at line 1600 of file colorutils.h.
    {
        fill_solid( &(entries[0]), 32, c1);
    }
References entries, and fill_solid().
CRGBPalette32() [13/18]
CRGBPalette32::CRGBPalette32 (const CRGB & c1, const CRGB & c2) inline
Create palette with a gradient from one color to another.
Parameters
c1 the starting color for the gradient
c2 the end color for the gradient
Definition at line 1605 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 32, c1, c2);
    }
References entries, and fill_gradient_RGB().
CRGBPalette32() [14/18]
CRGBPalette32::CRGBPalette32 (const CRGB & c1, const CRGB & c2, const CRGB & c3) inline
Create palette with three-color gradient.
Parameters
c1 the starting color for the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 1610 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 32, c1, c2, c3);
    }
References entries, and fill_gradient_RGB().
CRGBPalette32() [15/18]
CRGBPalette32::CRGBPalette32 (const CRGB & c1, const CRGB & c2, const CRGB & c3, const CRGB & c4) inline
Create palette with four-color gradient.
Parameters
c1 the starting color for the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 1615 of file colorutils.h.
    {
        fill_gradient_RGB( &(entries[0]), 32, c1, c2, c3, c4);
    }
References entries, and fill_gradient_RGB().
CRGBPalette32() [16/18]
CRGBPalette32::CRGBPalette32 (const CRGBPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 1622 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
    }
References UpscalePalette().
CRGBPalette32() [17/18]
CRGBPalette32::CRGBPalette32 (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1634 of file colorutils.h.
    {
        CRGBPalette16 p16(rhs);
        *this = p16;
    }
CRGBPalette32() [18/18]
CRGBPalette32::CRGBPalette32 (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1649 of file colorutils.h.
    {
        *this = progpal;
    }
Member Function Documentation
loadDynamicGradientPalette()
CRGBPalette32 & CRGBPalette32::loadDynamicGradientPalette (TDynamicRGBGradientPalette_bytes gpal) inline
Creates a palette from a gradient palette in dynamic (heap) memory.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1697 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* ent = (TRGBGradientPaletteEntryUnion*)(gpal);
        TRGBGradientPaletteEntryUnion u;
        // Count entries
        uint16_t count = 0;
        do {
            u = *(ent + count);
            ++count;
        } while ( u.index != 255);
        int8_t lastSlotUsed = -1;
        u = *ent;
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        uint8_t istart8 = 0;
        uint8_t iend8 = 0;
        while( indexstart < 255) {
            ++ent;
            u = *ent;
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            istart8 = indexstart / 8;
            iend8   = indexend   / 8;
            if( count < 16) {
                if( (istart8 <= lastSlotUsed) && (lastSlotUsed < 31)) {
                    istart8 = lastSlotUsed + 1;
                    if( iend8 < istart8) {
                        iend8 = istart8;
                    }
                }
                lastSlotUsed = iend8;
            }
            fill_gradient_RGB( &(entries[0]), istart8, rgbstart, iend8, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References entries, and fill_gradient_RGB().
operator CRGB *()
CRGBPalette32::operator CRGB * () inline
Get the underlying pointer to the CRGB entries making up the palette.
Definition at line 1573 of file colorutils.h.
    {
        return &(entries[0]);
    }
References entries.
operator!=()
bool CRGBPalette32::operator!= (const CRGBPalette32 & rhs) const inline
Check if two palettes do not have the same color entries.
Definition at line 1545 of file colorutils.h.
    {
        return !( *this == rhs);
    }
operator=() [1/8]
CRGBPalette32 & CRGBPalette32::operator= (const CHSV rhs[32]) inline
Create palette from array of CHSV colors.
Definition at line 1507 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] = rhs[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References entries.
operator=() [2/8]
CRGBPalette32 & CRGBPalette32::operator= (const CHSVPalette32 & rhs) inline
Create palette from CHSV palette.
Definition at line 1499 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] = rhs.entries[i]; // implicit HSV-to-RGB conversion
        }
        return *this;
    }
References CHSVPalette32::entries, and entries.
operator=() [3/8]
CRGBPalette32 & CRGBPalette32::operator= (const CRGB rhs[32]) inline
Create palette from array of CRGB colors.
Definition at line 1478 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [4/8]
CRGBPalette32 & CRGBPalette32::operator= (const CRGBPalette16 & rhs16) inline
Create upscaled palette from 16-entry palette.
Definition at line 1627 of file colorutils.h.
    {
        UpscalePalette( rhs16, *this);
        return *this;
    }
References UpscalePalette().
operator=() [5/8]
CRGBPalette32 & CRGBPalette32::operator= (const CRGBPalette32 & rhs) inline
Copy constructor.
Definition at line 1472 of file colorutils.h.
    {
        memmove8( (void *) &(entries[0]), &(rhs.entries[0]), sizeof( entries));
        return *this;
    }
References entries, and memmove8().
operator=() [6/8]
CRGBPalette32 & CRGBPalette32::operator= (const TProgmemRGBPalette16 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1640 of file colorutils.h.
    {
        CRGBPalette16 p16(rhs);
        *this = p16;
        return *this;
    }
operator=() [7/8]
CRGBPalette32 & CRGBPalette32::operator= (const TProgmemRGBPalette32 & rhs) inline
Create palette from palette stored in PROGMEM.
Definition at line 1523 of file colorutils.h.
    {
        for( uint8_t i = 0; i < 32; ++i) {
            entries[i] =  FL_PGM_READ_DWORD_NEAR( rhs + i);
        }
        return *this;
    }
References entries, and FL_PGM_READ_DWORD_NEAR.
operator=() [8/8]
CRGBPalette32 & CRGBPalette32::operator= (TProgmemRGBGradientPalette_bytes progpal) inline
Creates a palette from a gradient palette in PROGMEM.
Gradient palettes are loaded into CRGBPalettes in such a way that, if possible, every color represented in the gradient palette is also represented in the CRGBPalette.
For example, consider a gradient palette that is all black except for a single, one-element-wide (1/256th!) spike of red in the middle:
  0,   0,0,0
124,   0,0,0
125, 255,0,0  // one 1/256th-palette-wide red stripe
126,   0,0,0
255,   0,0,0
A naive conversion of this 256-element palette to a 16-element palette might accidentally completely eliminate the red spike, rendering the palette completely black.
However, the conversions provided here would attempt to include a the red stripe in the output, more-or-less as faithfully as possible. So in this case, the resulting CRGBPalette16 palette would have a red stripe in the middle which was 1/16th of a palette wide – the narrowest possible in a CRGBPalette16.
This means that the relative width of stripes in a CRGBPalette16 will be, by definition, different from the widths in the gradient palette. This code attempts to preserve "all the colors", rather than the exact stripe widths at the expense of dropping some colors.
Definition at line 1654 of file colorutils.h.
    {
        TRGBGradientPaletteEntryUnion* progent = (TRGBGradientPaletteEntryUnion*)(progpal);
        TRGBGradientPaletteEntryUnion u;
        // Count entries
        uint16_t count = 0;
        do {
            u.dword = FL_PGM_READ_DWORD_NEAR(progent + count);
            ++count;
        } while ( u.index != 255);
        int8_t lastSlotUsed = -1;
        u.dword = FL_PGM_READ_DWORD_NEAR( progent);
        CRGB rgbstart( u.r, u.g, u.b);
        int indexstart = 0;
        uint8_t istart8 = 0;
        uint8_t iend8 = 0;
        while( indexstart < 255) {
            ++progent;
            u.dword = FL_PGM_READ_DWORD_NEAR( progent);
            int indexend  = u.index;
            CRGB rgbend( u.r, u.g, u.b);
            istart8 = indexstart / 8;
            iend8   = indexend   / 8;
            if( count < 16) {
                if( (istart8 <= lastSlotUsed) && (lastSlotUsed < 31)) {
                    istart8 = lastSlotUsed + 1;
                    if( iend8 < istart8) {
                        iend8 = istart8;
                    }
                }
                lastSlotUsed = iend8;
            }
            fill_gradient_RGB( &(entries[0]), istart8, rgbstart, iend8, rgbend);
            indexstart = indexend;
            rgbstart = rgbend;
        }
        return *this;
    }
References TRGBGradientPaletteEntryUnion::dword, entries, fill_gradient_RGB(), and FL_PGM_READ_DWORD_NEAR.
operator==()
bool CRGBPalette32::operator== (const CRGBPalette32 & rhs) const inline
Check if two palettes have the same color entries.
Definition at line 1532 of file colorutils.h.
    {
        const uint8_t* p = (const uint8_t*)(&(this->entries[0]));
        const uint8_t* q = (const uint8_t*)(&(rhs.entries[0]));
        if( p == q) return true;
        for( uint8_t i = 0; i < (sizeof( entries)); ++i) {
            if( *p != *q) return false;
            ++p;
            ++q;
        }
        return true;
    }
References entries, and p.
operator[]() [1/4]
CRGB & CRGBPalette32::operator[] (int x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1562 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [2/4]
const CRGB & CRGBPalette32::operator[] (int x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1567 of file colorutils.h.
    {
        return entries[(uint8_t)x];
    }
References entries, and x.
operator[]() [3/4]
CRGB & CRGBPalette32::operator[] (uint8_t x) inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1551 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
operator[]() [4/4]
const CRGB & CRGBPalette32::operator[] (uint8_t x) const inline
Array access operator to index into the gradient entries.
Parameters
x the index to retrieve
Returns
reference to an entry in the palette's color array
Note
This does not perform any interpolation like ColorFromPalette(), it accesses the underlying entries that make up the gradient. Beware of bounds issues!
Definition at line 1556 of file colorutils.h.
    {
        return entries[x];
    }
References entries, and x.
Member Data Documentation
entries
CRGB CRGBPalette32::entries[32]
the color entries that make up the palette
Definition at line 1438 of file colorutils.h.
Referenced by CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), CRGBPalette32(), loadDynamicGradientPalette(), operator CRGB *(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator==(), operator[](), operator[](), operator[](), and operator[]().
TRGBGradientPaletteEntryUnion
union TRGBGradientPaletteEntryUnion
Class Members
struct TRGBGradientPaletteEntryUnion.__unnamed25__ __unnamed__
uint8_t bytes[4] values as an array
uint32_t dword values as a packed 32-bit double word
TRGBGradientPaletteEntryUnion.__unnamed25__
struct TRGBGradientPaletteEntryUnion.__unnamed25__
Class Members
uint8_t b CRGB::blue channel value of the color entry.
uint8_t g CRGB::green channel value of the color entry.
uint8_t index index of the color entry in the gradient
uint8_t r CRGB::red channel value of the color entry.
Typedef Documentation
TDynamicRGBGradientPalette_byte
typedef uint8_t TDynamicRGBGradientPalette_byte
Byte of an RGB gradient entry, stored in dynamic (heap) memory.
Definition at line 688 of file colorutils.h.
TDynamicRGBGradientPalette_bytes
typedef const TDynamicRGBGradientPalette_byte* TDynamicRGBGradientPalette_bytes
Pointer to bytes of an RGB gradient, stored in dynamic (heap) memory.
Definition at line 689 of file colorutils.h.
TDynamicRGBGradientPaletteRef
typedef TDynamicRGBGradientPalette_bytes TDynamicRGBGradientPaletteRef
Alias of TDynamicRGBGradientPalette_bytes.
Definition at line 690 of file colorutils.h.