FastLED: FastPin< PIN > Class Template Reference
FastPin< PIN > Class Template Reference
Detailed Description
template<uint8_t PIN>
class FastPin< PIN >
The simplest level of Pin class.
This relies on runtime functions during initialization to get the port/pin mask for the pin. Most of the accesses involve references to these static globals that get set up. This won't be the fastest set of pin operations, but it will provide pin level access on pretty much all Arduino environments. In addition, it includes some methods to help optimize access in various ways. Namely, the versions of hi(), lo(), and fastset() that take the port register as a passed in register variable (saving a global dereference), since these functions are aggressively inlined, that can help collapse out a lot of extraneous memory loads/dereferences.
In addition, if, while writing a bunch of data to a pin, you know no other pins will be getting written to, you can get/cache a value of the pin's port register and use that to do a full set to the register. This results in one being able to simply do a store to the register, vs. the load, and/or, and store that would be done normally.
There are platform specific instantiations of this class that provide direct i/o register access to pins for much higher speed pin twiddling.
Note that these classes are all static functions. So the proper usage is Pin<13>::hi(); or such. Instantiating objects is not recommended, as passing Pin objects around will likely -not- have the effect you're expecting.
Examples
Pintest.ino.
Definition at line 217 of file fastpin.h.
#include <fastpin.h>
Public Types
typedef volatile RwReg * port_ptr_t
type for a pin read/write register, volatile
typedef RwReg port_t
type for a pin read/write register, non-volatile
Static Public Member Functions
static void fastset (FASTLED_REGISTER port_ptr_t port, FASTLED_REGISTER port_t val)
Set the state of a port.
static void hi ()
Set the pin state to HIGH
static void hi (FASTLED_REGISTER port_ptr_t port)
Set the same pin on another port to HIGH
static port_t hival ()
Gets the state of the port with this pin HIGH
static void lo ()
Set the pin state to LOW
static void lo (FASTLED_REGISTER port_ptr_t port)
Set the same pin on another port to LOW
static port_t loval ()
Gets the state of the port with this pin LOW
static port_t mask ()
Get the pin mask.
static port_ptr_t port ()
Get the output state of the port.
static void set (FASTLED_REGISTER port_t val)
Set the state of the output register.
static void setInput ()
Set the pin mode as INPUT
static void setOutput ()
Set the pin mode as OUTPUT
static void strobe ()
Toggle the pin twice to create a short pulse.
static void toggle ()
Toggle the pin.
Static Private Member Functions
static void _init ()
Static Private Attributes
static volatile RoReg * sInPort
Input register for the pin.
static RwReg sPinMask
Bitmask for the pin within its register.
static volatile RwReg * sPort
Output register for the pin.
Member Typedef Documentation
port_ptr_t
template<uint8_t PIN> volatile RwReg* FastPin< PIN >::port_ptr_t
type for a pin read/write register, volatile
Definition at line 230 of file fastpin.h.
port_t
template<uint8_t PIN> RwReg FastPin< PIN >::port_t
type for a pin read/write register, non-volatile
Definition at line 231 of file fastpin.h.
Member Function Documentation
_init()
template<uint8_t PIN> static void FastPin< PIN >::_init () inline static private
Definition at line 221 of file fastpin.h.
{
#if !defined(FASTLED_NO_PINMAP)
        sPinMask = digitalPinToBitMask(PIN);
        sPort = portOutputRegister(digitalPinToPort(PIN));
        sInPort = portInputRegister(digitalPinToPort(PIN));
#endif
    }
References PIN, FastPin< PIN >::sInPort, FastPin< PIN >::sPinMask, and FastPin< PIN >::sPort.
Referenced by FastPin< PIN >::setInput(), and FastPin< PIN >::setOutput().
fastset()
template<uint8_t PIN> static void FastPin< PIN >::fastset (FASTLED_REGISTER port_ptr_t port, FASTLED_REGISTER port_t val) inline static
Set the state of a port.
Parameters
port the port to modify
val the state to set the port to
Definition at line 257 of file fastpin.h.
{ *port  = val; }
References FastPin< PIN >::port().
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
hi() [1/2]
template<uint8_t PIN> static void FastPin< PIN >::hi () inline static
Set the pin state to HIGH
Definition at line 239 of file fastpin.h.
{ *sPort |= sPinMask; }
References FastPin< PIN >::sPinMask, and FastPin< PIN >::sPort.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
hi() [2/2]
template<uint8_t PIN> static void FastPin< PIN >::hi (FASTLED_REGISTER port_ptr_t port) inline static
Set the same pin on another port to HIGH
Parameters
port the port to modify
Definition at line 250 of file fastpin.h.
{ *port |= sPinMask; }
References FastPin< PIN >::port(), and FastPin< PIN >::sPinMask.
hival()
template<uint8_t PIN> static port_t FastPin< PIN >::hival () inline static
Gets the state of the port with this pin HIGH
Definition at line 260 of file fastpin.h.
{ return *sPort | sPinMask;  }
References FastPin< PIN >::sPinMask, and FastPin< PIN >::sPort.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
lo() [1/2]
template<uint8_t PIN> static void FastPin< PIN >::lo () inline static
Set the pin state to LOW
Definition at line 241 of file fastpin.h.
{ *sPort &= ~sPinMask; }
References FastPin< PIN >::sPort.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
lo() [2/2]
template<uint8_t PIN> static void FastPin< PIN >::lo (FASTLED_REGISTER port_ptr_t port) inline static
Set the same pin on another port to LOW
Parameters
port the port to modify
Definition at line 252 of file fastpin.h.
{ *port &= ~sPinMask; }
References FastPin< PIN >::port().
loval()
template<uint8_t PIN> static port_t FastPin< PIN >::loval () inline static
Gets the state of the port with this pin LOW
Definition at line 262 of file fastpin.h.
{ return *sPort & ~sPinMask; }
References FastPin< PIN >::sPort.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
mask()
template<uint8_t PIN> static port_t FastPin< PIN >::mask () inline static
Get the pin mask.
Definition at line 266 of file fastpin.h.
{ return sPinMask; }
References FastPin< PIN >::sPinMask.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
port()
template<uint8_t PIN> static port_ptr_t FastPin< PIN >::port () inline static
Get the output state of the port.
Definition at line 264 of file fastpin.h.
{ return sPort; }
References FastPin< PIN >::sPort.
Referenced by FastPin< PIN >::fastset(), FastPin< PIN >::hi(), FastPin< PIN >::lo(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
set()
template<uint8_t PIN> static void FastPin< PIN >::set (FASTLED_REGISTER port_t val) inline static
Set the state of the output register.
Parameters
val the state to set the output register to
Note
This function is not limited to the current pin! It modifies the entire register.
Definition at line 254 of file fastpin.h.
{ *sPort = val; }
References FastPin< PIN >::sPort.
setInput()
template<uint8_t PIN> static void FastPin< PIN >::setInput () inline static
Set the pin mode as INPUT
Definition at line 236 of file fastpin.h.
{ _init(); pinMode(PIN, INPUT); }
References FastPin< PIN >::_init(), and PIN.
setOutput()
template<uint8_t PIN> static void FastPin< PIN >::setOutput () inline static
Set the pin mode as OUTPUT
Definition at line 234 of file fastpin.h.
{ _init(); pinMode(PIN, OUTPUT); }
References FastPin< PIN >::_init(), and PIN.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init().
strobe()
template<uint8_t PIN> static void FastPin< PIN >::strobe () inline static
Toggle the pin twice to create a short pulse.
Definition at line 244 of file fastpin.h.
{ toggle(); toggle(); }
References FastPin< PIN >::toggle().
toggle()
template<uint8_t PIN> static void FastPin< PIN >::toggle () inline static
Toggle the pin.
If the pin was high, set it low. If was low, set it high.
Definition at line 247 of file fastpin.h.
{ *sInPort = sPinMask; }
References FastPin< PIN >::sInPort, and FastPin< PIN >::sPinMask.
Referenced by FastPin< PIN >::strobe(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
Member Data Documentation
sInPort
template<uint8_t PIN> volatile RoReg * FastPin< PIN >::sInPort static private
Input register for the pin.
Definition at line 220 of file fastpin.h.
Referenced by FastPin< PIN >::_init(), and FastPin< PIN >::toggle().
sPinMask
template<uint8_t PIN> RwReg FastPin< PIN >::sPinMask static private
Bitmask for the pin within its register.
Definition at line 218 of file fastpin.h.
Referenced by FastPin< PIN >::_init(), FastPin< PIN >::hi(), FastPin< PIN >::hi(), FastPin< PIN >::hival(), FastPin< PIN >::mask(), and FastPin< PIN >::toggle().
sPort
template<uint8_t PIN> volatile RwReg * FastPin< PIN >::sPort static private
Output register for the pin.
Definition at line 219 of file fastpin.h.
Referenced by FastPin< PIN >::_init(), FastPin< PIN >::hi(), FastPin< PIN >::hival(), FastPin< PIN >::lo(), FastPin< PIN >::loval(), FastPin< PIN >::port(), and FastPin< PIN >::set().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fastpin.h