FastLED: fl::FileHandle Class Reference
fl::FileHandle Class Reference abstract
Detailed Description
Definition at line 65 of file file_system.h.
#include <file_system.h>
Public Member Functions
virtual ~FileHandle ()
virtual bool available () const =0
virtual size_t bytesLeft () const
virtual void close ()=0
virtual const char * path () const =0
virtual size_t pos () const =0
virtual size_t read (uint8_t *dst, size_t bytesToRead)=0
size_t readCRGB (CRGB *dst, size_t n)
virtual bool seek (size_t pos)=0
virtual size_t size () const =0
virtual bool valid () const =0
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
~FileHandle()
virtual fl::FileHandle::~FileHandle () inline virtual
Definition at line 67 of file file_system.h.
{}
Member Function Documentation
available()
virtual bool fl::FileHandle::available () const pure virtual
Implemented in fl::NullFileHandle.
bytesLeft()
size_t fl::FileHandle::bytesLeft () const virtual
Definition at line 94 of file file_system.cpp.
{ return size() - pos(); }
References pos(), and size().
close()
virtual void fl::FileHandle::close () pure virtual
Implemented in fl::NullFileHandle.
path()
virtual const char * fl::FileHandle::path () const pure virtual
Implemented in fl::NullFileHandle.
pos()
virtual size_t fl::FileHandle::pos () const pure virtual
Implemented in fl::NullFileHandle.
Referenced by bytesLeft().
read()
virtual size_t fl::FileHandle::read (uint8_t * dst, size_t bytesToRead) pure virtual
Implemented in fl::NullFileHandle.
Referenced by readCRGB().
readCRGB()
size_t fl::FileHandle::readCRGB (CRGB * dst, size_t n) inline
Definition at line 79 of file file_system.h.
{
      return read((uint8_t*)dst, n * 3) / 3;
    }
References read().
seek()
virtual bool fl::FileHandle::seek (size_t pos) pure virtual
Implemented in fl::NullFileHandle.
size()
virtual size_t fl::FileHandle::size () const pure virtual
Implemented in fl::NullFileHandle.
Referenced by bytesLeft().
valid()
virtual bool fl::FileHandle::valid () const pure virtual
Implemented in fl::NullFileHandle.
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/file_system.h
/home/runner/work/FastLED/FastLED/src/fl/file_system.cpp