FastLED: animartrix_detail::ANIMartRIX Class Reference
animartrix_detail::ANIMartRIX Class Reference abstract
Detailed Description
Definition at line 148 of file animartrix_detail.hpp.
#include <animartrix_detail.hpp>
Public Member Functions
ANIMartRIX ()
ANIMartRIX (int w, int h)
virtual ~ANIMartRIX ()
float add (float &a, float &b)
void Big_Caleido ()
void calculate_oscillators (oscillators &timings)
void Caleido1 ()
void Caleido2 ()
void Caleido3 ()
void Center_Field ()
void Chasing_Spirals ()
float colorburn (float &a, float &b)
float colordodge (float &a, float &b)
void Complex_Kaleido ()
void Complex_Kaleido_2 ()
void Complex_Kaleido_3 ()
void Complex_Kaleido_4 ()
void Complex_Kaleido_5 ()
void Complex_Kaleido_6 ()
void Distance_Experiment ()
float fade (float t)
void get_ready ()
uint32_t getTime ()
float grad (int hash, float x, float y, float z)
void Hot_Blob ()
void init (int w, int h)
void Lava1 ()
float lerp (float t, float a, float b)
void logFrame ()
void logOutput ()
float map_float (float x, float in_min, float in_max, float out_min, float out_max)
void Module_Experiment1 ()
void Module_Experiment10 ()
void Module_Experiment2 ()
void Module_Experiment3 ()
void Module_Experiment4 ()
void Module_Experiment5 ()
void Module_Experiment6 ()
void Module_Experiment7 ()
void Module_Experiment8 ()
void Module_Experiment9 ()
float multiply (float &a, float &b)
void Parametric_Water ()
float pnoise (float x, float y, float z)
void Polar_Waves ()
void render_polar_lookup_table (float cx, float cy)
float render_value (render_parameters &animation)
void report_performance ()
void RGB_Blobs ()
void RGB_Blobs2 ()
void RGB_Blobs3 ()
void RGB_Blobs4 ()
void RGB_Blobs5 ()
rgb rgb_sanity_check (rgb &pixel)
void Rings ()
void Rotating_Blob ()
void run_default_oscillators (float master_speed=0.005)
void Scaledemo1 ()
float screen (float &a, float &b)
virtual void setPixelColorInternal (int x, int y, rgb pixel)=0
void setSpeedFactor (float speed)
Set the Speed Factor 0.1 to 10 - 1 for original speed.
void setTime (uint32_t t)
void Slow_Fade ()
void SM1 ()
void SM10 ()
void SM2 ()
void SM3 ()
void SM4 ()
void SM5 ()
void SM6 ()
void SM8 ()
void SM9 ()
void Spiralus ()
void Spiralus2 ()
float subtract (float &a, float &b)
void Water ()
void Waves ()
virtual uint16_t xyMap (uint16_t x, uint16_t y)=0
void Yves ()
void Zoom ()
void Zoom2 ()
Public Attributes
unsigned long a
render_parameters animation
unsigned long b
unsigned long c
uint32_t currentTime = 0
fl::HeapVector< fl::HeapVector< float > > distance
modulators move
int num_x
int num_y
rgb pixel
fl::HeapVector< fl::HeapVector< float > > polar_theta
float radial_filter_radius = 23.0
bool serpentine
float show0
float show1
float show2
float show3
float show4
float show5
float show6
float show7
float show8
float show9
float speed_factor = 1
oscillators timings
Constructor & Destructor Documentation
ANIMartRIX() [1/2]
animartrix_detail::ANIMartRIX::ANIMartRIX () inline
Definition at line 174 of file animartrix_detail.hpp.
{}
ANIMartRIX() [2/2]
animartrix_detail::ANIMartRIX::ANIMartRIX (int w, int h) inline
Definition at line 176 of file animartrix_detail.hpp.
{ this->init(w, h); }
References init().
~ANIMartRIX()
virtual animartrix_detail::ANIMartRIX::~ANIMartRIX () inline virtual
Definition at line 178 of file animartrix_detail.hpp.
{}
Member Function Documentation
add()
float animartrix_detail::ANIMartRIX::add (float & a, float & b) inline
Definition at line 231 of file animartrix_detail.hpp.
{ return a + b; }
References a, and b.
Referenced by SM4(), SM5(), and SM8().
Big_Caleido()
void animartrix_detail::ANIMartRIX::Big_Caleido () inline
Definition at line 1875 of file animartrix_detail.hpp.
                       { // nice one
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] +
                                  5 * move.noise_angle[0] +
                                  animation.dist * 0.1;
                animation.z = 5;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 50 * move.linear[0];
                animation.offset_x = 50 * move.noise_angle[0];
                animation.offset_y = 50 * move.noise_angle[1];
                float show1 = render_value(animation);
                animation.angle = 6 * polar_theta[x][y] +
                                  5 * move.noise_angle[1] +
                                  animation.dist * 0.15;
                animation.z = 5;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 50 * move.linear[1];
                animation.offset_x = 50 * move.noise_angle[1];
                animation.offset_y = 50 * move.noise_angle[2];
                float show2 = render_value(animation);
                animation.angle = 5;
                animation.z = 5;
                animation.scale_x = 0.10;
                animation.scale_y = 0.10;
                animation.offset_z = 10 * move.linear[2];
                animation.offset_x = 10 * move.noise_angle[2];
                animation.offset_y = 10 * move.noise_angle[3];
                float show3 = render_value(animation);
                animation.angle = 15;
                animation.z = 15;
                animation.scale_x = 0.10;
                animation.scale_y = 0.10;
                animation.offset_z = 10 * move.linear[3];
                animation.offset_x = 10 * move.noise_angle[3];
                animation.offset_y = 10 * move.noise_angle[4];
                float show4 = render_value(animation);
                animation.angle = 2;
                animation.z = 15;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_z = 10 * move.linear[4];
                animation.offset_x = 10 * move.noise_angle[4];
                animation.offset_y = 10 * move.noise_angle[5];
                float show5 = render_value(animation);
                pixel.red = show1 - show4;
                pixel.green = show2 - show5;
                pixel.blue = show3 - show2 + show1;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
        // show_frame();
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, show5, timings, x, y, and animartrix_detail::render_parameters::z.
calculate_oscillators()
void animartrix_detail::ANIMartRIX::calculate_oscillators (oscillators & timings) inline
Definition at line 289 of file animartrix_detail.hpp.
{
        double runtime = getTime() * timings.master_speed *
                         speed_factor; // global anaimation speed
        for (int i = 0; i < num_oscillators; i++) {
            move.linear[i] =
                (runtime + timings.offset[i]) *
                timings.ratio[i]; // continously rising offsets, returns 0 to
                                  // max_float
            move.radial[i] = fmodf(move.linear[i],
                                   2 * PI); // angle offsets for continous
                                            // rotation, returns    0 to 2 * PI
            move.directional[i] =
                sinf(move.radial[i]); // directional offsets or factors, returns
                                      // -1 to 1
            move.noise_angle[i] =
                PI *
                (1 +
                 pnoise(move.linear[i], 0,
                        0)); // noise based angle offset, returns 0 to 2 * PI
        }
    }
References animartrix_detail::modulators::directional, getTime(), animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_oscillators, animartrix_detail::oscillators::offset, PI, pnoise(), animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, speed_factor, and timings.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), run_default_oscillators(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
Caleido1()
void animartrix_detail::ANIMartRIX::Caleido1 () inline
Definition at line 843 of file animartrix_detail.hpp.
                    {
        get_ready();
        timings.master_speed = 0.003; // speed ratios for the oscillators
        timings.ratio[0] = 0.02;      // higher values = faster transitions
        timings.ratio[1] = 0.03;
        timings.ratio[2] = 0.04;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.6;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = distance[x][y] * (2 + move.directional[0]) / 3;
                animation.angle = 3 * polar_theta[x][y] +
                                  3 * move.noise_angle[0] + move.radial[4];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.scale_z = 0.1;
                animation.offset_y = 2 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = move.linear[0];
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[1]) / 3;
                animation.angle = 4 * polar_theta[x][y] +
                                  3 * move.noise_angle[1] + move.radial[4];
                animation.offset_x = 2 * move.linear[1];
                animation.z = move.linear[1];
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[2]) / 3;
                animation.angle = 5 * polar_theta[x][y] +
                                  3 * move.noise_angle[2] + move.radial[4];
                animation.offset_y = 2 * move.linear[2];
                animation.z = move.linear[2];
                float show3 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[3]) / 3;
                animation.angle = 4 * polar_theta[x][y] +
                                  3 * move.noise_angle[3] + move.radial[4];
                animation.offset_x = 2 * move.linear[3];
                animation.z = move.linear[3];
                float show4 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = show3 * distance[x][y] / 10;
                pixel.blue = (show2 + show4) / 2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Caleido2()
void animartrix_detail::ANIMartRIX::Caleido2 () inline
Definition at line 911 of file animartrix_detail.hpp.
                    {
        get_ready();
        timings.master_speed = 0.002; // speed ratios for the oscillators
        timings.ratio[0] = 0.02;      // higher values = faster transitions
        timings.ratio[1] = 0.03;
        timings.ratio[2] = 0.04;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.6;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = distance[x][y] * (2 + move.directional[0]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[0] + move.radial[4];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.scale_z = 0.1;
                animation.offset_y = 2 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = move.linear[0];
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[1]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[1] + move.radial[4];
                animation.offset_x = 2 * move.linear[1];
                animation.z = move.linear[1];
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[2]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[2] + move.radial[4];
                animation.offset_y = 2 * move.linear[2];
                animation.z = move.linear[2];
                float show3 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[3]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[3] + move.radial[4];
                animation.offset_x = 2 * move.linear[3];
                animation.z = move.linear[3];
                float show4 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = show3 * distance[x][y] / 10;
                pixel.blue = (show2 + show4) / 2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Caleido3()
void animartrix_detail::ANIMartRIX::Caleido3 () inline
Definition at line 979 of file animartrix_detail.hpp.
                    {
        get_ready();
        timings.master_speed = 0.004; // speed ratios for the oscillators
        timings.ratio[0] = 0.02;      // higher values = faster transitions
        timings.ratio[1] = 0.03;
        timings.ratio[2] = 0.04;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.6;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = distance[x][y] * (2 + move.directional[0]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[0] + move.radial[4];
                animation.scale_x = 0.1; // + (move.directional[0] + 2)/100;
                animation.scale_y = 0.1; // + (move.directional[1] + 2)/100;
                animation.scale_z = 0.1;
                animation.offset_y = 2 * move.linear[0];
                animation.offset_x = 2 * move.linear[1];
                animation.offset_z = 0;
                animation.z = move.linear[0];
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[1]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[1] + move.radial[4];
                animation.offset_x = 2 * move.linear[1];
                animation.offset_y = show1 / 20.0;
                animation.z = move.linear[1];
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[2]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[2] + move.radial[4];
                animation.offset_y = 2 * move.linear[2];
                animation.offset_x = show2 / 20.0;
                animation.z = move.linear[2];
                float show3 = render_value(animation);
                animation.dist = distance[x][y] * (2 + move.directional[3]) / 3;
                animation.angle = 2 * polar_theta[x][y] +
                                  3 * move.noise_angle[3] + move.radial[4];
                animation.offset_x = 2 * move.linear[3];
                animation.offset_y = show3 / 20.0;
                animation.z = move.linear[3];
                float show4 = render_value(animation);
                // colormapping
                float radius = radial_filter_radius; // radial mask
                pixel.red = show1 * (y + 1) / num_y;
                pixel.green = show3 * distance[x][y] / 10;
                pixel.blue = (show2 + show4) / 2;
                if (distance[x][y] > radius) {
                    pixel.red = 0;
                    pixel.green = 0;
                    pixel.blue = 0;
                }
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Center_Field()
void animartrix_detail::ANIMartRIX::Center_Field () inline
Definition at line 737 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 1;        // higher values = faster transitions
        timings.ratio[1] = 1.1;
        timings.ratio[2] = 1.2;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.dist = 5 * sqrtf(distance[x][y]);
                animation.offset_y = move.linear[0];
                animation.offset_x = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.dist = 4 * sqrtf(distance[x][y]);
                animation.offset_y = move.linear[0];
                animation.offset_x = 0;
                animation.z = 0;
                float show2 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = show2;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
Chasing_Spirals()
void animartrix_detail::ANIMartRIX::Chasing_Spirals () inline
Definition at line 576 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 0.1;      // higher values = faster transitions
        timings.ratio[1] = 0.13;
        timings.ratio[2] = 0.16;
        timings.offset[1] = 10;
        timings.offset[2] = 20;
        timings.offset[3] = 30;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.angle =
                    3 * polar_theta[x][y] + move.radial[0] - distance[x][y] / 3;
                animation.dist = distance[x][y];
                animation.scale_z = 0.1;
                animation.scale_y = 0.1;
                animation.scale_x = 0.1;
                animation.offset_x = move.linear[0];
                animation.offset_y = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.angle =
                    3 * polar_theta[x][y] + move.radial[1] - distance[x][y] / 3;
                animation.dist = distance[x][y];
                animation.offset_x = move.linear[1];
                float show2 = render_value(animation);
                animation.angle =
                    3 * polar_theta[x][y] + move.radial[2] - distance[x][y] / 3;
                animation.dist = distance[x][y];
                animation.offset_x = move.linear[2];
                float show3 = render_value(animation);
                // colormapping
                float radius = radial_filter_radius;
                float radial_filter = (radius - distance[x][y]) / radius;
                pixel.red = 3 * show1 * radial_filter;
                pixel.green = show2 * radial_filter / 2;
                pixel.blue = show3 * radial_filter / 4;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
colorburn()
float animartrix_detail::ANIMartRIX::colorburn (float & a, float & b) inline
Definition at line 224 of file animartrix_detail.hpp.
{
        return (1 - ((1 - a / 255.f) / (b / 255.f))) * 255.f;
    }
References a, and b.
colordodge()
float animartrix_detail::ANIMartRIX::colordodge (float & a, float & b) inline
Definition at line 240 of file animartrix_detail.hpp.
{ return (a / (255.f - b)) * 255.f; }
References a, and b.
Referenced by Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Module_Experiment10(), Module_Experiment8(), SM10(), SM4(), SM5(), SM6(), and SM9().
Complex_Kaleido()
void animartrix_detail::ANIMartRIX::Complex_Kaleido () inline
Definition at line 2693 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.009; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        // float size = 1.5;
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] + 10 * move.radial[0] +
                                  animation.dist / 2;
                animation.z = 5;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 0;
                animation.offset_x = -30 * move.linear[0];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = -5 * polar_theta[x][y] + 12 * move.radial[1] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 0;
                animation.offset_x = -30 * move.linear[1];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = -5 * polar_theta[x][y] + 12 * move.radial[2] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 0;
                animation.offset_x = -40 * move.linear[2];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] + 12 * move.radial[3] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = -35 * move.linear[3];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                show5 = screen(show4, show3);
                show6 = colordodge(show2, show3);
                // float linear1 = y / 32.f;
                // float linear2 = (32-y) / 32.f;
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 + show2);
                pixel.green = 0.3 * radial * show6; //(radial*(show1))*0.3f;
                pixel.blue = radial * show5;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
Complex_Kaleido_2()
void animartrix_detail::ANIMartRIX::Complex_Kaleido_2 () inline
Definition at line 2784 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.009; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        float size = 0.5;
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] + 10 * move.radial[0] +
                                  animation.dist / 2;
                animation.z = 5;
                animation.scale_x = 0.07 * size;
                animation.scale_y = 0.07 * size;
                animation.offset_z = 0;
                animation.offset_x = -30 * move.linear[0];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = -5 * polar_theta[x][y] + 12 * move.radial[1] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.07 * size;
                animation.scale_y = 0.07 * size;
                animation.offset_z = 0;
                animation.offset_x = -30 * move.linear[1];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = -5 * polar_theta[x][y] + 12 * move.radial[2] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.05 * size;
                animation.scale_y = 0.05 * size;
                animation.offset_z = 0;
                animation.offset_x = -40 * move.linear[2];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] + 12 * move.radial[3] +
                                  animation.dist / 2;
                animation.z = 500;
                animation.scale_x = 0.09 * size;
                animation.scale_y = 0.09 * size;
                animation.offset_z = 0;
                animation.offset_x = -35 * move.linear[3];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                show5 = screen(show4, show3);
                show6 = colordodge(show2, show3);
                // float linear1 = y / 32.f;
                // float linear2 = (32-y) / 32.f;
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 + show2);
                pixel.green = 0.3 * radial * show6; //(radial*(show1))*0.3f;
                pixel.blue = radial * show5;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
Complex_Kaleido_3()
void animartrix_detail::ANIMartRIX::Complex_Kaleido_3 () inline
Definition at line 2875 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.001; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.038;
        timings.ratio[5] = 0.041;
        calculate_oscillators(timings);
        float size = 0.4 + move.directional[0] * 0.1;
        float q = 2;
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle =
                    5 * polar_theta[x][y] + 10 * move.radial[0] +
                    animation.dist / (((move.directional[0] + 3) * 2)) +
                    move.noise_angle[0] * q;
                animation.z = 5;
                animation.scale_x = 0.08 * size * (move.directional[0] + 1.5);
                animation.scale_y = 0.07 * size;
                animation.offset_z = -10 * move.linear[0];
                animation.offset_x = -30 * move.linear[0];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    -5 * polar_theta[x][y] + 10 * move.radial[1] +
                    animation.dist / (((move.directional[1] + 3) * 2)) +
                    move.noise_angle[1] * q;
                animation.z = 500;
                animation.scale_x = 0.07 * size * (move.directional[1] + 1.1);
                animation.scale_y = 0.07 * size * (move.directional[2] + 1.3);
                ;
                animation.offset_z = -12 * move.linear[1];
                ;
                animation.offset_x = -(num_x - 1) * move.linear[1];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    -5 * polar_theta[x][y] + 12 * move.radial[2] +
                    animation.dist / (((move.directional[3] + 3) * 2)) +
                    move.noise_angle[2] * q;
                animation.z = 500;
                animation.scale_x = 0.05 * size * (move.directional[3] + 1.5);
                ;
                animation.scale_y = 0.05 * size * (move.directional[4] + 1.5);
                ;
                animation.offset_z = -12 * move.linear[3];
                animation.offset_x = -40 * move.linear[3];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    5 * polar_theta[x][y] + 12 * move.radial[3] +
                    animation.dist / (((move.directional[5] + 3) * 2)) +
                    move.noise_angle[3] * q;
                animation.z = 500;
                animation.scale_x = 0.09 * size * (move.directional[5] + 1.5);
                ;
                ;
                animation.scale_y = 0.09 * size * (move.directional[6] + 1.5);
                ;
                ;
                animation.offset_z = 0;
                animation.offset_x = -35 * move.linear[3];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                show5 = screen(show4, show3) - show2;
                show6 = colordodge(show4, show1);
                show7 = multiply(show1, show2);
                float linear1 = y / 32.f;
                // float linear2 = (32-y) / 32.f;
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                show7 = multiply(show1, show2) * linear1 * 2;
                show8 = subtract(show7, show5);
                // pixel.red    = radial*(show1+show2);
                pixel.green = 0.2 * show8; //(radial*(show1))*0.3f;
                pixel.blue = show5 * radial;
                pixel.red = (1 * show1 + 1 * show2) - show7 / 2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, multiply(), animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, show7, show8, subtract(), timings, x, y, and animartrix_detail::render_parameters::z.
Complex_Kaleido_4()
void animartrix_detail::ANIMartRIX::Complex_Kaleido_4 () inline
Definition at line 2991 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed 0.01 in the video
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.038;
        timings.ratio[6] = 0.041;
        calculate_oscillators(timings);
        float size = 0.6;
        float q = 1;
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 1 + move.directional[6] * 0.3;
                animation.dist = distance[x][y] * s;
                animation.angle =
                    5 * polar_theta[x][y] + 1 * move.radial[0] -
                    animation.dist / (3 + move.directional[0] * 0.5);
                animation.z = 5;
                animation.scale_x = 0.08 * size + (move.directional[0] * 0.01);
                animation.scale_y = 0.07 * size + (move.directional[1] * 0.01);
                animation.offset_z = -10 * move.linear[0];
                animation.offset_x = 0; //-30 * move.linear[0];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y] * s;
                animation.angle =
                    5 * polar_theta[x][y] + 1 * move.radial[1] +
                    animation.dist / (3 + move.directional[1] * 0.5);
                animation.z = 50;
                animation.scale_x = 0.08 * size + (move.directional[1] * 0.01);
                animation.scale_y = 0.07 * size + (move.directional[2] * 0.01);
                animation.offset_z = -10 * move.linear[1];
                animation.offset_x = 0; //-30 * move.linear[0];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 1;
                animation.z = 500;
                animation.scale_x = 0.2 * size;
                animation.scale_y = 0.2 * size;
                animation.offset_z = 0; //-12 * move.linear[3];
                animation.offset_y = +7 * move.linear[3] + move.noise_angle[3];
                animation.offset_x = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    5 * polar_theta[x][y] + 12 * move.radial[3] +
                    animation.dist / (((move.directional[5] + 3) * 2)) +
                    move.noise_angle[3] * q;
                animation.z = 500;
                animation.scale_x = 0.09 * size * (move.directional[5] + 1.5);
                ;
                ;
                animation.scale_y = 0.09 * size * (move.directional[6] + 1.5);
                ;
                ;
                animation.offset_z = 0;
                animation.offset_x = -35 * move.linear[3];
                animation.offset_y = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                // show5 = screen(show4, show3)-show2;
                // show6 = colordodge(show4, show1);
                // show7 = multiply(show1, show2);
                /*
                float linear1 = y / 32.f;
                float linear2 = (32-y) / 32.f;
                */
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                /*
                show7 = multiply(show1, show2) * linear1*2;
                show8 = subtract(show7, show5);
                */
                show5 = ((show1 + show2)) - show3;
                if (show5 > 255)
                    show5 = 255;
                if (show5 < 0)
                    show5 = 0;
                show6 = colordodge(show1, show2);
                pixel.red = show5 * radial;
                pixel.blue = (64 - show5 - show3) * radial;
                pixel.green = 0.5 * (show6);
                // pixel.blue   = show5 * radial;
                // pixel.red    = (1*show1 + 1*show2) - show7/2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
Complex_Kaleido_5()
void animartrix_detail::ANIMartRIX::Complex_Kaleido_5 () inline
Definition at line 3111 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.0038;
        timings.ratio[6] = 0.041;
        calculate_oscillators(timings);
        float size = 0.6;
        // float q = 1;
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 1 + move.directional[6] * 0.8;
                animation.dist = distance[x][y] * s;
                animation.angle = 10 * move.radial[6] +
                                  50 * move.directional[5] * polar_theta[x][y] -
                                  animation.dist / 3;
                animation.z = 5;
                animation.scale_x = 0.08 * size;
                animation.scale_y = 0.07 * size;
                animation.offset_z = -10 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_y = 0;
                animation.low_limit = -0.5;
                show1 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = show1 * radial;
                pixel.green = 0;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Complex_Kaleido_6()
void animartrix_detail::ANIMartRIX::Complex_Kaleido_6 () inline
Definition at line 3166 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.0038;
        timings.ratio[6] = 0.041;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 16 * polar_theta[x][y] + 16 * move.radial[0];
                animation.z = 5;
                animation.scale_x = 0.06;
                animation.scale_y = 0.06;
                animation.offset_z = -10 * move.linear[0];
                animation.offset_y = 10 * move.noise_angle[0];
                animation.offset_x = 10 * move.noise_angle[4];
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 16 * polar_theta[x][y] + 16 * move.radial[1];
                animation.z = 500;
                animation.scale_x = 0.06;
                animation.scale_y = 0.06;
                animation.offset_z = -10 * move.linear[1];
                animation.offset_y = 10 * move.noise_angle[1];
                animation.offset_x = 10 * move.noise_angle[3];
                animation.low_limit = 0;
                show2 = render_value(animation);
                // float radius = radial_filter_radius;   // radius of a radial
                // brightness filter float radial =
                // (radius-distance[x][y])/distance[x][y];
                pixel.red = show1;
                pixel.green = 0;
                pixel.blue = show2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
Distance_Experiment()
void animartrix_detail::ANIMartRIX::Distance_Experiment () inline
Definition at line 789 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 0.2;      // higher values = faster transitions
        timings.ratio[1] = 0.13;
        timings.ratio[2] = 0.012;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = powf(distance[x][y], 0.5);
                animation.angle = polar_theta[x][y] + move.radial[0];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.offset_y = move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.dist = powf(distance[x][y], 0.6);
                animation.angle = polar_theta[x][y] + move.noise_angle[2];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.offset_y = move.linear[1];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show2 = render_value(animation);
                // colormapping
                pixel.red = show1 + show2;
                pixel.green = show2;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
fade()
float animartrix_detail::ANIMartRIX::fade (float t) inline
Definition at line 248 of file animartrix_detail.hpp.
{ return t * t * t * (t * (t * 6 - 15) + 10); }
Referenced by pnoise().
get_ready()
void animartrix_detail::ANIMartRIX::get_ready () inline
Definition at line 465 of file animartrix_detail.hpp.
                     { // wait until new buffer is ready, measure time
        a = micros();
        logOutput();
    }
References a, and logOutput().
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
getTime()
uint32_t animartrix_detail::ANIMartRIX::getTime () inline
Definition at line 184 of file animartrix_detail.hpp.
{ return currentTime ? currentTime : millis(); }
References currentTime.
Referenced by calculate_oscillators(), and Module_Experiment10().
grad()
float animartrix_detail::ANIMartRIX::grad (int hash, float x, float y, float z) inline
Definition at line 250 of file animartrix_detail.hpp.
{
        int h = hash & 15;       /* CONVERT LO 4 BITS OF HASH CODE */
        float u = h < 8 ? x : y, /* INTO 12 GRADIENT DIRECTIONS.   */
            v = h < 4                ? y
                : h == 12 || h == 14 ? x
                                     : z;
        return ((h & 1) == 0 ? u : -u) + ((h & 2) == 0 ? v : -v);
    }
References x, y, and z.
Referenced by pnoise().
Hot_Blob()
void animartrix_detail::ANIMartRIX::Hot_Blob () inline
Definition at line 1393 of file animartrix_detail.hpp.
                    { // nice one
        get_ready();
        run_default_oscillators(0.001);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07 + move.directional[0] * 0.002;
                animation.scale_y = 0.07;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                animation.low_limit = -1;
                float show1 = render_value(animation);
                animation.offset_y = -move.linear[1];
                float show3 = render_value(animation);
                animation.offset_x = show3 / 20;
                animation.offset_y = -move.linear[0] / 2 + show1 / 70;
                animation.low_limit = 0;
                float show2 = render_value(animation);
                animation.offset_x = show3 / 20;
                animation.offset_y = -move.linear[0] / 2 + show1 / 70;
                animation.z = 100;
                float show4 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - animation.dist) / animation.dist;
                float linear = (y + 1) / (num_y - 1.f);
                pixel.red = radial * show2;
                pixel.green = linear * radial * 0.3 * (show2 - show4);
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, radial_filter_radius, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), run_default_oscillators(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, x, y, and animartrix_detail::render_parameters::z.
init()
void animartrix_detail::ANIMartRIX::init (int w, int h) inline
Definition at line 187 of file animartrix_detail.hpp.
{
        animation = render_parameters();
        timings = oscillators();
        move = modulators();
        pixel = rgb();
        this->num_x = w;
        this->num_y = h;
        if (w <= 16) {
            this->radial_filter_radius = 11;
        } else {
            this->radial_filter_radius = 23; // on 32x32, use 11 for 16x16
        }
        render_polar_lookup_table(
            (num_x / 2) - 0.5,
            (num_y / 2) - 0.5); // precalculate all polar coordinates
                                // polar origin is set to matrix centre
        // set default speed ratio for the oscillators, not all effects set their own, so start from know state
        timings.master_speed = 0.01;
    }
References animation, animartrix_detail::oscillators::master_speed, move, num_x, num_y, pixel, render_polar_lookup_table(), and timings.
Referenced by ANIMartRIX(), and fl::FastLEDANIMartRIX::FastLEDANIMartRIX().
Lava1()
void animartrix_detail::ANIMartRIX::Lava1 () inline
Definition at line 1057 of file animartrix_detail.hpp.
                 {
        get_ready();
        timings.master_speed = 0.0015; // speed ratios for the oscillators
        timings.ratio[0] = 4;          // higher values = faster transitions
        timings.ratio[1] = 1;
        timings.ratio[2] = 1;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.6;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = distance[x][y] * 0.8;
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.15; // + (move.directional[0] + 2)/100;
                animation.scale_y = 0.12; // + (move.directional[1] + 2)/100;
                animation.scale_z = 0.01;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 30;
                float show1 = render_value(animation);
                animation.offset_y = -move.linear[1];
                animation.scale_x = 0.15; // + (move.directional[0] + 2)/100;
                animation.scale_y = 0.12; // + (move.directional[1] + 2)/100;
                animation.offset_x = show1 / 100;
                animation.offset_y += show1 / 100;
                float show2 = render_value(animation);
                animation.offset_y = -move.linear[2];
                animation.scale_x = 0.15; // + (move.directional[0] + 2)/100;
                animation.scale_y = 0.12; // + (move.directional[1] + 2)/100;
                animation.offset_x = show2 / 100;
                animation.offset_y += show2 / 100;
                float show3 = render_value(animation);
                // colormapping
                float linear = (y) / (num_y - 1.f); // radial mask
                pixel.red = linear * show2;
                pixel.green = 0.1 * linear * (show2 - show3);
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
lerp()
float animartrix_detail::ANIMartRIX::lerp (float t, float a, float b) inline
Definition at line 249 of file animartrix_detail.hpp.
{ return a + t * (b - a); }
References a, and b.
Referenced by pnoise().
logFrame()
void animartrix_detail::ANIMartRIX::logFrame () inline
Definition at line 476 of file animartrix_detail.hpp.
{ c = micros(); }
References c.
logOutput()
void animartrix_detail::ANIMartRIX::logOutput () inline
Definition at line 474 of file animartrix_detail.hpp.
{ b = micros(); }
References b.
Referenced by get_ready().
map_float()
float animartrix_detail::ANIMartRIX::map_float (float x, float in_min, float in_max, float out_min, float out_max) inline
Definition at line 405 of file animartrix_detail.hpp.
{
        float result =
            (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
        if (result < out_min)
            result = out_min;
        if (result > out_max)
            result = out_max;
        return result;
    }
References x.
Referenced by render_value().
Module_Experiment1()
void animartrix_detail::ANIMartRIX::Module_Experiment1 () inline
Definition at line 3413 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.03; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] + 20 * move.directional[0];
                animation.angle = move.noise_angle[0] + move.noise_angle[1] +
                                  polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                pixel.red = 0;
                pixel.green = 0;
                pixel.blue = show1;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment10()
void animartrix_detail::ANIMartRIX::Module_Experiment10 () inline
Definition at line 3968 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed 0.031
        float w = 1;
        timings.ratio[0] = 0.01; // speed ratios for the oscillators, higher
                                 // values = faster transitions
        timings.ratio[1] = 0.011;
        timings.ratio[2] = 0.013;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        timings.ratio[5] = 0.38 * w;
        timings.ratio[6] = 0.0003; // master rotation
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.4; // scale
                float r = 1.5; // scroll speed
                animation.dist =
                    3 + distance[x][y] +
                    3 * sinf(0.25 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y] + move.noise_angle[0] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 10 * move.linear[0];
                animation.offset_y = -5 * r * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist =
                    4 + distance[x][y] +
                    4 * sinf(0.24 * distance[x][y] - move.radial[4]);
                animation.angle = polar_theta[x][y] + move.noise_angle[1] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[1];
                animation.offset_y = -5 * r * move.linear[1];
                animation.offset_x = 100;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist =
                    5 + distance[x][y] +
                    5 * sinf(0.23 * distance[x][y] - move.radial[5]);
                animation.angle = polar_theta[x][y] + move.noise_angle[2] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[2];
                animation.offset_y = -5 * r * move.linear[2];
                animation.offset_x = 1000;
                animation.low_limit = 0;
                show3 = render_value(animation);
                show4 = colordodge(show1, show2);
                float rad = sinf(PI / 2 +
                                 distance[x][y] / 14); // better radial filter?!
                /*
                pixel.red    = show1;
                pixel.green  = show1 * 0.3;
                pixel.blue   = show2-show1;
                */
                CHSV(rad * ((show1 + show2) + show3), 255, 255);
                pixel = rgb_sanity_check(pixel);
                uint8_t a = getTime() / 100;
                CRGB p = CRGB(CHSV(((a + show1 + show2) + show3), 255, 255));
                rgb pixel;
                pixel.red = p.red;
                pixel.green = p.green;
                pixel.blue = p.blue;
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References a, animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), getTime(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, p, PI, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment2()
void animartrix_detail::ANIMartRIX::Module_Experiment2 () inline
Definition at line 3454 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist =
                    distance[x][y] - (16 + move.directional[0] * 16);
                animation.angle = move.noise_angle[0] + move.noise_angle[1] +
                                  polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                pixel.red = show1;
                pixel.green = show1 - 80;
                pixel.blue = show1 - 150;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment3()
void animartrix_detail::ANIMartRIX::Module_Experiment3 () inline
Definition at line 3496 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist =
                    distance[x][y] - (12 + move.directional[3] * 4);
                animation.angle = move.noise_angle[0] + move.noise_angle[1] +
                                  polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                pixel.red = show1;
                pixel.green = show1 - 80;
                pixel.blue = show1 - 150;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment4()
void animartrix_detail::ANIMartRIX::Module_Experiment4 () inline
Definition at line 3575 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.031; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033;
        timings.ratio[4] = 0.036; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.8;
                animation.dist = (distance[x][y] * distance[x][y]) * 0.7;
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.004 * s;
                animation.scale_y = 0.003 * s;
                animation.offset_z = 0.1 * move.linear[2];
                animation.offset_y = -20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = (distance[x][y] * distance[x][y]) * 0.8;
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.004 * s;
                animation.scale_y = 0.003 * s;
                animation.offset_z = 0.1 * move.linear[3];
                animation.offset_y = -20 * move.linear[3];
                animation.offset_x = 100;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = (distance[x][y] * distance[x][y]) * 0.9;
                animation.angle = polar_theta[x][y];
                animation.z = 5000;
                animation.scale_x = 0.004 * s;
                animation.scale_y = 0.003 * s;
                animation.offset_z = 0.1 * move.linear[4];
                animation.offset_y = -20 * move.linear[4];
                animation.offset_x = 1000;
                animation.low_limit = 0;
                show3 = render_value(animation);
                // overlapping color mapping
                /*
                float r = show1;
                float g = show2-show1;
                float b = show3-show1-show2;
                */
                pixel.red = show1 - show2 - show3;
                pixel.blue = show2 - show1 - show3;
                pixel.green = show3 - show1 - show2;
                // pixel.green  = b;
                // pixel.green  = show1 - 80;
                // pixel.blue   = show1 - 150;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment5()
void animartrix_detail::ANIMartRIX::Module_Experiment5 () inline
Definition at line 3650 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.031; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.33;
        timings.ratio[4] = 0.036; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 1.5;
                animation.dist = distance[x][y] +
                                 sinf(0.5 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[0];
                animation.offset_y = -20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                pixel.red = show1;
                pixel.green = 0;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment6()
void animartrix_detail::ANIMartRIX::Module_Experiment6 () inline
Definition at line 3694 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed 0.031
        float w = 0.7;
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.8;
                animation.dist = distance[x][y] +
                                 sinf(0.25 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[0];
                animation.offset_y = -20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = distance[x][y] +
                                 sinf(0.24 * distance[x][y] - move.radial[4]);
                animation.angle = polar_theta[x][y];
                animation.z = 10;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[1];
                animation.offset_y = -20 * move.linear[1];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show2 = render_value(animation);
                /*
                pixel.red    = show1;
                pixel.green  = show1 * 0.3;
                pixel.blue   = show2-show1;
                */
                pixel.red = (show1 + show2);
                pixel.green = ((show1 + show2) * 0.6) - 30;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment7()
void animartrix_detail::ANIMartRIX::Module_Experiment7 () inline
Definition at line 3758 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.005; // master speed 0.031
        float w = 0.3;
        timings.ratio[0] = 0.01; // speed ratios for the oscillators, higher
                                 // values = faster transitions
        timings.ratio[1] = 0.011;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.7;
                animation.dist =
                    2 + distance[x][y] +
                    2 * sinf(0.25 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 10 * move.linear[0];
                animation.offset_y = -20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist =
                    2 + distance[x][y] +
                    2 * sinf(0.24 * distance[x][y] - move.radial[4]);
                animation.angle = polar_theta[x][y];
                animation.z = 10;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[1];
                animation.offset_y = -20 * move.linear[1];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show2 = render_value(animation);
                /*
                pixel.red    = show1;
                pixel.green  = show1 * 0.3;
                pixel.blue   = show2-show1;
                */
                pixel.red = (show1 + show2);
                pixel.green = ((show1 + show2) * 0.6) - 50;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment8()
void animartrix_detail::ANIMartRIX::Module_Experiment8 () inline
Definition at line 3824 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed 0.031
        float w = 0.3;
        timings.ratio[0] = 0.01; // speed ratios for the oscillators, higher
                                 // values = faster transitions
        timings.ratio[1] = 0.011;
        timings.ratio[2] = 0.013;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        timings.ratio[5] = 0.38 * w;
        timings.ratio[6] = 0.0003; // master rotation
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.4; // scale
                float r = 1.5; // scroll speed
                animation.dist =
                    3 + distance[x][y] +
                    3 * sinf(0.25 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y] + move.noise_angle[0] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 10 * move.linear[0];
                animation.offset_y = -5 * r * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist =
                    4 + distance[x][y] +
                    4 * sinf(0.24 * distance[x][y] - move.radial[4]);
                animation.angle = polar_theta[x][y] + move.noise_angle[1] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[1];
                animation.offset_y = -5 * r * move.linear[1];
                animation.offset_x = 100;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist =
                    5 + distance[x][y] +
                    5 * sinf(0.23 * distance[x][y] - move.radial[5]);
                animation.angle = polar_theta[x][y] + move.noise_angle[2] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[2];
                animation.offset_y = -5 * r * move.linear[2];
                animation.offset_x = 1000;
                animation.low_limit = 0;
                show3 = render_value(animation);
                show4 = colordodge(show1, show2);
                float rad = sinf(PI / 2 +
                                 distance[x][y] / 14); // better radial filter?!
                /*
                pixel.red    = show1;
                pixel.green  = show1 * 0.3;
                pixel.blue   = show2-show1;
                */
                pixel.red = rad * ((show1 + show2) + show3);
                pixel.green = (((show2 + show3) * 0.8) - 90) * rad;
                pixel.blue = show4 * 0.2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, PI, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Module_Experiment9()
void animartrix_detail::ANIMartRIX::Module_Experiment9 () inline
Definition at line 3922 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.03; // master speed 0.031
        float w = 0.3;
        timings.ratio[0] = 0.1; // speed ratios for the oscillators, higher
                                // values = faster transitions
        timings.ratio[1] = 0.011;
        timings.ratio[2] = 0.013;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        timings.ratio[5] = 0.38 * w;
        timings.ratio[6] = 0.0003;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + move.radial[1];
                animation.z = 5;
                animation.scale_x = 0.001;
                animation.scale_y = 0.1;
                animation.scale_z = 0.1;
                animation.offset_y = -10 * move.linear[0];
                animation.offset_x = 20;
                animation.offset_z = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                pixel.red = 10 * show1;
                pixel.green = 0;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
multiply()
float animartrix_detail::ANIMartRIX::multiply (float & a, float & b) inline
Definition at line 219 of file animartrix_detail.hpp.
{ return a * b / 255.f; }
References a, and b.
Referenced by Complex_Kaleido_3().
Parametric_Water()
void animartrix_detail::ANIMartRIX::Parametric_Water () inline
Definition at line 3317 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.003; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.15; // wave speed
        timings.ratio[6] = 0.41;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 4;
                float f = 10 + 2 * move.directional[0];
                animation.dist = (f + move.directional[0]) *
                                 sinf(-move.radial[5] + move.radial[0] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = (f + move.directional[1]) *
                                 sinf(-move.radial[5] + move.radial[1] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[1];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = (f + move.directional[2]) *
                                 sinf(-move.radial[5] + move.radial[2] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5000;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show4 = render_value(animation);
                animation.dist = (f + move.directional[3]) *
                                 sinf(-move.radial[5] + move.radial[3] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 2000;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[3];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show5 = render_value(animation);
                show6 = screen(show4, show5);
                show7 = screen(show2, show3);
                float radius = 40; // radius of a radial brightness filter
                float radial = (radius - distance[x][y]) / radius;
                // pixel.red    = show6;
                // pixel.blue = show7;
                pixel.red = pixel.blue - 40;
                pixel.green = 0;
                pixel.blue = (0.3 * show6 + 0.7 * show7) * radial;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show2, show3, show4, show5, show6, show7, timings, x, y, and animartrix_detail::render_parameters::z.
pnoise()
float animartrix_detail::ANIMartRIX::pnoise (float x, float y, float z) inline
Definition at line 260 of file animartrix_detail.hpp.
{
        int X = (int)floorf(x) & 255, /* FIND UNIT CUBE THAT */
            Y = (int)floorf(y) & 255, /* CONTAINS POINT.     */
            Z = (int)floorf(z) & 255;
        x -= floorf(x); /* FIND RELATIVE X,Y,Z */
        y -= floorf(y); /* OF POINT IN CUBE.   */
        z -= floorf(z);
        float u = fade(x), /* COMPUTE FADE CURVES */
            v = fade(y),   /* FOR EACH OF X,Y,Z.  */
            w = fade(z);
        int A = P(X) + Y, AA = P(A) + Z,
            AB = P(A + 1) + Z, /* HASH COORDINATES OF */
            B = P(X + 1) + Y, BA = P(B) + Z,
            BB = P(B + 1) + Z; /* THE 8 CUBE CORNERS, */
        return lerp(w,
                    lerp(v,
                         lerp(u, grad(P(AA), x, y, z),        /* AND ADD */
                              grad(P(BA), x - 1, y, z)),      /* BLENDED */
                         lerp(u, grad(P(AB), x, y - 1, z),    /* RESULTS */
                              grad(P(BB), x - 1, y - 1, z))), /* FROM  8 */
                    lerp(v,
                         lerp(u, grad(P(AA + 1), x, y, z - 1),   /* CORNERS */
                              grad(P(BA + 1), x - 1, y, z - 1)), /* OF CUBE */
                         lerp(u, grad(P(AB + 1), x, y - 1, z - 1),
                              grad(P(BB + 1), x - 1, y - 1, z - 1))));
    }
References fade(), grad(), lerp(), P, x, y, and z.
Referenced by calculate_oscillators(), and render_value().
Polar_Waves()
void animartrix_detail::ANIMartRIX::Polar_Waves () inline
Definition at line 1532 of file animartrix_detail.hpp.
                       { // nice one
        get_ready();
        timings.master_speed = 0.5; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = (distance[x][y]);
                animation.angle =
                    polar_theta[x][y] - animation.dist * 0.1 + move.radial[0];
                animation.z = (animation.dist * 1.5) - 10 * move.linear[0];
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_x = move.linear[0];
                float show1 = render_value(animation);
                animation.angle =
                    polar_theta[x][y] - animation.dist * 0.1 + move.radial[1];
                animation.z = (animation.dist * 1.5) - 10 * move.linear[1];
                animation.offset_x = move.linear[1];
                float show2 = render_value(animation);
                animation.angle =
                    polar_theta[x][y] - animation.dist * 0.1 + move.radial[2];
                animation.z = (animation.dist * 1.5) - 10 * move.linear[2];
                animation.offset_x = move.linear[2];
                float show3 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * show1;
                pixel.green = radial * show2;
                pixel.blue = radial * show3;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
render_polar_lookup_table()
void animartrix_detail::ANIMartRIX::render_polar_lookup_table (float cx, float cy) inline
Definition at line 386 of file animartrix_detail.hpp.
{
        polar_theta.resize(num_x, fl::HeapVector<float>(num_y, 0.0f));
        distance.resize(num_x, fl::HeapVector<float>(num_y, 0.0f));
        for (int xx = 0; xx < num_x; xx++) {
            for (int yy = 0; yy < num_y; yy++) {
                float dx = xx - cx;
                float dy = yy - cy;
                distance[xx][yy] = hypotf(dx, dy);
                polar_theta[xx][yy] = atan2f(dy, dx);
            }
        }
    }
References distance, num_x, num_y, polar_theta, and fl::HeapVector< T >::resize().
Referenced by init().
render_value()
float animartrix_detail::ANIMartRIX::render_value (render_parameters & animation) inline
Definition at line 350 of file animartrix_detail.hpp.
{
        // convert polar coordinates back to cartesian ones
        float newx = (animation.offset_x + animation.center_x -
                      (cosf(animation.angle) * animation.dist)) *
                     animation.scale_x;
        float newy = (animation.offset_y + animation.center_y -
                      (sinf(animation.angle) * animation.dist)) *
                     animation.scale_y;
        float newz = (animation.offset_z + animation.z) * animation.scale_z;
        // render noisevalue at this new cartesian point
        float raw_noise_field_value = pnoise(newx, newy, newz);
        // A) enhance histogram (improve contrast) by setting the black and
        // white point (low & high_limit) B) scale the result to a 0-255 range
        // (assuming you want 8 bit color depth per rgb chanel) Here happens the
        // contrast boosting & the brightness mapping
        if (raw_noise_field_value < animation.low_limit)
            raw_noise_field_value = animation.low_limit;
        if (raw_noise_field_value > animation.high_limit)
            raw_noise_field_value = animation.high_limit;
        float scaled_noise_value =
            map_float(raw_noise_field_value, animation.low_limit,
                      animation.high_limit, 0, 255);
        return scaled_noise_value;
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::render_parameters::center_x, animartrix_detail::render_parameters::center_y, animartrix_detail::render_parameters::dist, animartrix_detail::render_parameters::high_limit, animartrix_detail::render_parameters::low_limit, map_float(), animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pnoise(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, and animartrix_detail::render_parameters::z.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
report_performance()
void animartrix_detail::ANIMartRIX::report_performance () inline
Definition at line 482 of file animartrix_detail.hpp.
{
        float calc = b - a;                      // waiting time
        float push = c - b;                      // rendering time
        float total = c - a;                     // time per frame
        int fps = 1000000 / total;               // frames per second
        int kpps = (fps * num_x * num_y) / 1000; // kilopixel per second
        ANIMARTRIX_PRINT(fps);
        ANIMARTRIX_PRINT(" fps  ");
        ANIMARTRIX_PRINT(kpps);
        ANIMARTRIX_PRINT(" kpps @");
        ANIMARTRIX_PRINT(num_x * num_y);
        ANIMARTRIX_PRINT(" LEDs  ");
        ANIMARTRIX_PRINT(round(total));
        ANIMARTRIX_PRINT(" s per frame  waiting: ");
        ANIMARTRIX_PRINT(round((calc * 100) / total));
        ANIMARTRIX_PRINT("%  rendering: ");
        ANIMARTRIX_PRINT(round((push * 100) / total));
        ANIMARTRIX_PRINT("%  (");
        ANIMARTRIX_PRINT(round(calc));
        ANIMARTRIX_PRINT(" + ");
        ANIMARTRIX_PRINT(round(push));
        ANIMARTRIX_PRINT(" s)  Core-temp: ");
        // TODO ANIMARTRIX_PRINT( tempmonGetTemp() );
        //Serial.println(" C");
        ANIMARTRIX_PRINT(" C\n");
    }
References a, ANIMARTRIX_PRINT, b, c, num_x, num_y, and round.
RGB_Blobs()
void animartrix_detail::ANIMartRIX::RGB_Blobs () inline
Definition at line 1584 of file animartrix_detail.hpp.
                     { // nice one
        get_ready();
        timings.master_speed = 0.2; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + move.radial[0] +
                                  move.noise_angle[0] + move.noise_angle[3];
                animation.z = (sqrtf(animation.dist)); // - 10 * move.linear[0];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 10;
                animation.offset_x = 10 * move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[1] +
                                  move.noise_angle[1] + move.noise_angle[4];
                animation.offset_x = 11 * move.linear[1];
                animation.offset_z = 100;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[2] +
                                  move.noise_angle[2] + move.noise_angle[5];
                animation.offset_x = 12 * move.linear[2];
                animation.offset_z = 300;
                float show3 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * show1;
                pixel.green = radial * show2;
                pixel.blue = radial * show3;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
RGB_Blobs2()
void animartrix_detail::ANIMartRIX::RGB_Blobs2 () inline
Definition at line 1640 of file animartrix_detail.hpp.
                      { // nice one
        get_ready();
        timings.master_speed = 0.12; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + move.radial[0] +
                                  move.noise_angle[0] + move.noise_angle[3] +
                                  move.noise_angle[1];
                animation.z = (sqrtf(animation.dist)); // - 10 * move.linear[0];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 10;
                animation.offset_x = 10 * move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[1] +
                                  move.noise_angle[1] + move.noise_angle[4] +
                                  move.noise_angle[2];
                animation.offset_x = 11 * move.linear[1];
                animation.offset_z = 100;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[2] +
                                  move.noise_angle[2] + move.noise_angle[5] +
                                  move.noise_angle[3];
                animation.offset_x = 12 * move.linear[2];
                animation.offset_z = 300;
                float show3 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 - show3);
                pixel.green = radial * (show2 - show1);
                pixel.blue = radial * (show3 - show2);
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
RGB_Blobs3()
void animartrix_detail::ANIMartRIX::RGB_Blobs3 () inline
Definition at line 1699 of file animartrix_detail.hpp.
                      { // nice one
        get_ready();
        timings.master_speed = 0.12; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] + move.noise_angle[4];
                animation.angle = polar_theta[x][y] + move.radial[0] +
                                  move.noise_angle[0] + move.noise_angle[3] +
                                  move.noise_angle[1];
                animation.z = (sqrtf(animation.dist)); // - 10 * move.linear[0];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 10;
                animation.offset_x = 10 * move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[1] +
                                  move.noise_angle[1] + move.noise_angle[4] +
                                  move.noise_angle[2];
                animation.offset_x = 11 * move.linear[1];
                animation.offset_z = 100;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[2] +
                                  move.noise_angle[2] + move.noise_angle[5] +
                                  move.noise_angle[3];
                animation.offset_x = 12 * move.linear[2];
                animation.offset_z = 300;
                float show3 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 + show3) * 0.5 * animation.dist / 5;
                pixel.green = radial * (show2 + show1) * 0.5 * y / 15;
                pixel.blue = radial * (show3 + show2) * 0.5 * x / 15;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
RGB_Blobs4()
void animartrix_detail::ANIMartRIX::RGB_Blobs4 () inline
Definition at line 1758 of file animartrix_detail.hpp.
                      { // nice one
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] + move.noise_angle[4];
                animation.angle = polar_theta[x][y] + move.radial[0] +
                                  move.noise_angle[0] + move.noise_angle[3] +
                                  move.noise_angle[1];
                animation.z = 3 + sqrtf(animation.dist);
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 10;
                animation.offset_x = 50 * move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[1] +
                                  move.noise_angle[1] + move.noise_angle[4] +
                                  move.noise_angle[2];
                animation.offset_x = 50 * move.linear[1];
                animation.offset_z = 100;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[2] +
                                  move.noise_angle[2] + move.noise_angle[5] +
                                  move.noise_angle[3];
                animation.offset_x = 50 * move.linear[2];
                animation.offset_z = 300;
                float show3 = render_value(animation);
                float radius = 23; // radius of a radial brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 + show3) * 0.5 * animation.dist / 5;
                pixel.green = radial * (show2 + show1) * 0.5 * y / 15;
                pixel.blue = radial * (show3 + show2) * 0.5 * x / 15;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
RGB_Blobs5()
void animartrix_detail::ANIMartRIX::RGB_Blobs5 () inline
Definition at line 1816 of file animartrix_detail.hpp.
                      { // nice one
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] + move.noise_angle[4];
                animation.angle = polar_theta[x][y] + move.radial[0] +
                                  move.noise_angle[0] + move.noise_angle[3] +
                                  move.noise_angle[1];
                animation.z = 3 + sqrtf(animation.dist);
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 10;
                animation.offset_x = 50 * move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[1] +
                                  move.noise_angle[1] + move.noise_angle[4] +
                                  move.noise_angle[2];
                animation.offset_x = 50 * move.linear[1];
                animation.offset_z = 100;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + move.radial[2] +
                                  move.noise_angle[2] + move.noise_angle[5] +
                                  move.noise_angle[3];
                animation.offset_x = 50 * move.linear[2];
                animation.offset_z = 300;
                float show3 = render_value(animation);
                float radius = 23; // radius of a radial brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * (show1 + show3) * 0.5 * animation.dist / 5;
                pixel.green = radial * (show2 + show1) * 0.5 * y / 15;
                pixel.blue = radial * (show3 + show2) * 0.5 * x / 15;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
rgb_sanity_check()
rgb animartrix_detail::ANIMartRIX::rgb_sanity_check (rgb & pixel) inline
Definition at line 437 of file animartrix_detail.hpp.
{
        // rescue data if possible, return absolute value
        // if (pixel.red < 0)     pixel.red = fabsf(pixel.red);
        // if (pixel.green < 0) pixel.green = fabsf(pixel.green);
        // if (pixel.blue < 0)   pixel.blue = fabsf(pixel.blue);
        // Can never be negative colour
        if (pixel.red < 0)
            pixel.red = 0;
        if (pixel.green < 0)
            pixel.green = 0;
        if (pixel.blue < 0)
            pixel.blue = 0;
        // discard everything above the valid 8 bit colordepth 0-255 range
        if (pixel.red > 255)
            pixel.red = 255;
        if (pixel.green > 255)
            pixel.green = 255;
        if (pixel.blue > 255)
            pixel.blue = 255;
        return pixel;
    }
References animartrix_detail::rgb::blue, animartrix_detail::rgb::green, pixel, and animartrix_detail::rgb::red.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
Rings()
void animartrix_detail::ANIMartRIX::Rings () inline
Definition at line 635 of file animartrix_detail.hpp.
                 {
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 1;        // higher values = faster transitions
        timings.ratio[1] = 1.1;
        timings.ratio[2] = 1.2;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.angle = 5;
                animation.scale_x = 0.2;
                animation.scale_y = 0.2;
                animation.scale_z = 1;
                animation.dist = distance[x][y];
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                float show1 = render_value(animation);
                // describe and render animation layers
                animation.angle = 10;
                animation.dist = distance[x][y];
                animation.offset_y = -move.linear[1];
                float show2 = render_value(animation);
                // describe and render animation layers
                animation.angle = 12;
                animation.dist = distance[x][y];
                animation.offset_y = -move.linear[2];
                float show3 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = show2 / 4;
                pixel.blue = show3 / 4;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, pixel, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, timings, x, and y.
Rotating_Blob()
void animartrix_detail::ANIMartRIX::Rotating_Blob () inline
Definition at line 513 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 0.1;      // higher values = faster transitions
        timings.ratio[1] = 0.03;
        timings.ratio[2] = 0.03;
        timings.ratio[3] = 0.03;
        timings.offset[1] = 10;
        timings.offset[2] = 20;
        timings.offset[3] = 30;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_x = 0;
                animation.offset_y = 0;
                animation.offset_z = 100;
                animation.angle = polar_theta[x][y] + move.radial[0];
                animation.dist = distance[x][y];
                animation.z = move.linear[0];
                animation.low_limit = -1;
                float show1 = render_value(animation);
                animation.angle =
                    polar_theta[x][y] - move.radial[1] + show1 / 512.0;
                animation.dist = distance[x][y] * show1 / 255.0;
                animation.low_limit = 0;
                animation.z = move.linear[1];
                float show2 = render_value(animation);
                animation.angle =
                    polar_theta[x][y] - move.radial[2] + show1 / 512.0;
                animation.dist = distance[x][y] * show1 / 220.0;
                animation.z = move.linear[2];
                float show3 = render_value(animation);
                animation.angle =
                    polar_theta[x][y] - move.radial[3] + show1 / 512.0;
                animation.dist = distance[x][y] * show1 / 200.0;
                animation.z = move.linear[3];
                float show4 = render_value(animation);
                // colormapping
                pixel.red = (show2 + show4) / 2;
                pixel.green = show3 / 6;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
run_default_oscillators()
void animartrix_detail::ANIMartRIX::run_default_oscillators (float master_speed = 0.005) inline
Definition at line 317 of file animartrix_detail.hpp.
{
        timings.master_speed = master_speed;
        timings.ratio[0] = 1; // speed ratios for the oscillators, higher values
                              // = faster transitions
        timings.ratio[1] = 2;
        timings.ratio[2] = 3;
        timings.ratio[3] = 4;
        timings.ratio[4] = 5;
        timings.ratio[5] = 6;
        timings.ratio[6] = 7;
        timings.ratio[7] = 8;
        timings.ratio[8] = 9;
        timings.ratio[9] = 10;
        timings.offset[0] = 000;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        timings.offset[7] = 700;
        timings.offset[8] = 800;
        timings.offset[9] = 900;
        calculate_oscillators(timings);
    }
References calculate_oscillators(), animartrix_detail::oscillators::master_speed, animartrix_detail::oscillators::offset, animartrix_detail::oscillators::ratio, and timings.
Referenced by Hot_Blob(), Slow_Fade(), Zoom(), and Zoom2().
Scaledemo1()
void animartrix_detail::ANIMartRIX::Scaledemo1 () inline
Definition at line 1121 of file animartrix_detail.hpp.
                      {
        get_ready();
        timings.master_speed = 0.000001; // speed ratios for the oscillators
        timings.ratio[0] = 0.4;         // higher values = faster transitions
        timings.ratio[1] = 0.32;
        timings.ratio[2] = 0.10;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.6;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.dist = 0.3 * distance[x][y] * 0.8;
                animation.angle = 3 * polar_theta[x][y] + move.radial[2];
                animation.scale_x = 0.1 + (move.noise_angle[0]) / 10;
                animation.scale_y =
                    0.1 + (move.noise_angle[1]) /
                              10; // + (move.directional[1] + 2)/100;
                animation.scale_z = 0.01;
                animation.offset_y = 0;
                animation.offset_x = 0;
                animation.offset_z = 100 * move.linear[0];
                animation.z = 30;
                float show1 = render_value(animation);
                animation.angle = 3;
                float show2 = render_value(animation);
                float dist = 1; //(10-distance[x][y])/ 10;
                pixel.red = show1 * dist;
                pixel.green = (show1 - show2) * dist * 0.3;
                pixel.blue = (show2 - show1) * dist;
                if (distance[x][y] > 16) {
                    pixel.red = 0;
                    pixel.green = 0;
                    pixel.blue = 0;
                }
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
screen()
float animartrix_detail::ANIMartRIX::screen (float & a, float & b) inline
Definition at line 235 of file animartrix_detail.hpp.
{
        return (1 - (1 - a / 255.f) * (1 - b / 255.f)) * 255.f;
    }
References a, and b.
Referenced by Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Parametric_Water(), SM10(), SM5(), SM6(), SM8(), and SM9().
setPixelColorInternal()
virtual void animartrix_detail::ANIMartRIX::setPixelColorInternal (int x, int y, rgb pixel) pure virtual
Implemented in fl::FastLEDANIMartRIX.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
setSpeedFactor()
void animartrix_detail::ANIMartRIX::setSpeedFactor (float speed) inline
Set the Speed Factor 0.1 to 10 - 1 for original speed.
Parameters
speed
Definition at line 213 of file animartrix_detail.hpp.
{ this->speed_factor = speed; }
References speed.
setTime()
void animartrix_detail::ANIMartRIX::setTime (uint32_t t) inline
Definition at line 183 of file animartrix_detail.hpp.
{ currentTime = t; }
References currentTime.
Slow_Fade()
void animartrix_detail::ANIMartRIX::Slow_Fade () inline
Definition at line 1481 of file animartrix_detail.hpp.
                     { // nice one
        get_ready();
        run_default_oscillators();
        timings.master_speed = 0.00005;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist =
                    sqrtf(distance[x][y]) * 0.7 * (move.directional[0] + 1.5);
                animation.angle =
                    polar_theta[x][y] - move.radial[0] + distance[x][y] / 5;
                animation.scale_x = 0.11;
                animation.scale_y = 0.11;
                animation.offset_y = -50 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = move.linear[0];
                animation.low_limit = -0.1;
                animation.high_limit = 1;
                float show1 = render_value(animation);
                animation.dist = animation.dist * 1.1;
                animation.angle += move.noise_angle[0] / 10;
                float show2 = render_value(animation);
                animation.dist = animation.dist * 1.1;
                animation.angle += move.noise_angle[1] / 10;
                float show3 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * show1;
                pixel.green = radial * (show1 - show2) / 6;
                pixel.blue = radial * (show1 - show3) / 5;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::render_parameters::high_limit, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), run_default_oscillators(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
SM1()
void animartrix_detail::ANIMartRIX::SM1 () inline
Definition at line 1957 of file animartrix_detail.hpp.
               { // nice one
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.0025; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[1] = 0.0027;
        timings.ratio[2] = 0.0031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x / 2; x++) {
            for (int y = 0; y < num_y / 2; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 5 * move.noise_angle[0];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 50 * move.linear[0];
                animation.offset_x = 150 * move.directional[0];
                animation.offset_y = 150 * move.directional[1];
                float show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 4 * move.noise_angle[1];
                animation.z = 15;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_z = 50 * move.linear[1];
                animation.offset_x = 150 * move.directional[1];
                animation.offset_y = 150 * move.directional[2];
                float show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 5 * move.noise_angle[2];
                animation.z = 25;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = 50 * move.linear[2];
                animation.offset_x = 150 * move.directional[2];
                animation.offset_y = 150 * move.directional[3];
                float show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 5 * move.noise_angle[3];
                animation.z = 35;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_z = 50 * move.linear[3];
                animation.offset_x = 150 * move.directional[3];
                animation.offset_y = 150 * move.directional[4];
                float show4 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 5 * move.noise_angle[4];
                animation.z = 45;
                animation.scale_x = 0.2;
                animation.scale_y = 0.2;
                animation.offset_z = 50 * move.linear[4];
                animation.offset_x = 150 * move.directional[4];
                animation.offset_y = 150 * move.directional[5];
                float show5 = render_value(animation);
                pixel.red = show1 + show2;
                pixel.green = show3 + show4;
                pixel.blue = show5;
                pixel = rgb_sanity_check(pixel);
                // leds[xyMap(x, y)] = CRGB(pixel.red, pixel.green, pixel.blue);
                setPixelColorInternal(x, y, pixel);
                setPixelColorInternal((num_x - 1) - x, y, pixel);
                setPixelColorInternal((num_x - 1) - x, (num_y - 1) - y, pixel);
                setPixelColorInternal(x, (num_y - 1) - y, pixel);
            }
        }
        // show_frame();
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, show5, timings, x, y, and animartrix_detail::render_parameters::z.
SM10()
void animartrix_detail::ANIMartRIX::SM10 () inline
Definition at line 2609 of file animartrix_detail.hpp.
                {
        get_ready();
        timings.master_speed = 0.006; // 0.006
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float scale = 0.6;
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.09 * scale;
                animation.scale_y = 0.09 * scale;
                animation.offset_y = -30 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = -1;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.09 * scale;
                animation.scale_y = 0.09 * scale;
                animation.offset_y = -30 * move.linear[1];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = -1;
                show2 = render_value(animation);
                animation.dist = distance[x][y]; // + show1/64;
                animation.angle = polar_theta[x][y] + 2 + (show1 / 255) * PI;
                animation.z = 5;
                animation.scale_x = 0.09 * scale;
                animation.scale_y = 0.09 * scale;
                animation.offset_y = -10 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 2 + (show2 / 255) * PI;
                ;
                animation.z = 5;
                animation.scale_x = 0.09 * scale;
                animation.scale_y = 0.09 * scale;
                animation.offset_y = -20 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                show5 = screen(show4, show3);
                show6 = colordodge(show5, show3);
                // float linear1 = y / 32.f;
                // float linear2 = (32-y) / 32.f;
                pixel.red = (show5 + show6) / 2;
                pixel.green = (show5 - 50) + (show6 / 16);
                pixel.blue = 0; // show6;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, PI, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), scale, animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
SM2()
void animartrix_detail::ANIMartRIX::SM2 () inline
Definition at line 2043 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.03; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] * (move.directional[0]);
                animation.angle = polar_theta[x][y] + move.radial[0];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 5 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[1];
                animation.angle = polar_theta[x][y] + move.radial[1];
                animation.z = 50;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 5 * move.linear[1];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[2];
                animation.angle = polar_theta[x][y] + move.radial[2];
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 5 * move.linear[2];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show3 = render_value(animation);
                pixel.red = show1;
                pixel.green = show2;
                pixel.blue = show3;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
        // show_frame();
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
SM3()
void animartrix_detail::ANIMartRIX::SM3 () inline
Definition at line 2105 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.offset_y = -20 * move.linear[0];
                ;
                animation.low_limit = -1;
                animation.high_limit = 1;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.offset_y = -20 * move.linear[0];
                ;
                animation.low_limit = -1;
                animation.high_limit = 1;
                show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 500 + show1 / 20;
                animation.offset_y = -4 * move.linear[0] + show2 / 20;
                animation.low_limit = 0;
                animation.high_limit = 1;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 500 + show1 / 18;
                animation.offset_y = -4 * move.linear[0] + show2 / 18;
                animation.low_limit = 0;
                animation.high_limit = 1;
                show4 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 500 + show1 / 19;
                animation.offset_y = -4 * move.linear[0] + show2 / 19;
                animation.low_limit = 0.3;
                animation.high_limit = 1;
                show5 = render_value(animation);
                pixel.red = show4;
                pixel.green = show3;
                pixel.blue = show5;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::render_parameters::high_limit, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, show5, timings, x, y, and animartrix_detail::render_parameters::z.
SM4()
void animartrix_detail::ANIMartRIX::SM4 () inline
Definition at line 2198 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.02; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0033; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0036;
        timings.ratio[5] = 0.0039;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.offset_y = -20 * move.linear[0];
                ;
                animation.low_limit = 0;
                animation.high_limit = 1;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.offset_y = -40 * move.linear[0];
                ;
                animation.low_limit = 0;
                animation.high_limit = 1;
                show2 = render_value(animation);
                pixel.red = add(show2, show1);
                pixel.green = 0;
                pixel.blue = colordodge(show2, show1);
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References add(), animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::render_parameters::high_limit, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
SM5()
void animartrix_detail::ANIMartRIX::SM5 () inline
Definition at line 2255 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.03; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y] * (move.directional[0]);
                animation.angle = polar_theta[x][y] + move.radial[0];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 5 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[1];
                animation.angle = polar_theta[x][y] + move.radial[1];
                animation.z = 50;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 5 * move.linear[1];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[2];
                animation.angle = polar_theta[x][y] + move.radial[2];
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 5 * move.linear[2];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show3 = render_value(animation);
                animation.dist = distance[x][y] * (move.directional[3]);
                animation.angle = polar_theta[x][y] + move.radial[3];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 5 * move.linear[3];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show4 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[4];
                animation.angle = polar_theta[x][y] + move.radial[4];
                animation.z = 50;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 5 * move.linear[4];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show5 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[5];
                animation.angle = polar_theta[x][y] + move.radial[5];
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 5 * move.linear[5];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show6 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                pixel.red = radial * add(show1, show4);
                pixel.green = radial * colordodge(show2, show5);
                pixel.blue = radial * screen(show3, show6);
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References add(), animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
SM6()
void animartrix_detail::ANIMartRIX::SM6 () inline
Definition at line 2350 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.03; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.7; // zoom factor
                animation.dist = distance[x][y] * (move.directional[0]) * s;
                animation.angle = polar_theta[x][y] + move.radial[0];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 5 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[1] * s;
                animation.angle = polar_theta[x][y] + move.radial[1];
                animation.z = 50;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 5 * move.linear[1];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show2 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[2] * s;
                animation.angle = polar_theta[x][y] + move.radial[2];
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 5 * move.linear[2];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show3 = render_value(animation);
                animation.dist = distance[x][y] * (move.directional[3]) * s;
                animation.angle = polar_theta[x][y] + move.radial[3];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_z = 5 * move.linear[3];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show4 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[4] * s;
                animation.angle = polar_theta[x][y] + move.radial[4];
                animation.z = 50;
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.offset_z = 5 * move.linear[4];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show5 = render_value(animation);
                animation.dist = distance[x][y] * move.directional[5] * s;
                animation.angle = polar_theta[x][y] + move.radial[5];
                animation.z = 500;
                animation.scale_x = 0.05;
                animation.scale_y = 0.05;
                animation.offset_z = 5 * move.linear[5];
                animation.offset_x = 0;
                animation.offset_y = 0;
                float show6 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - distance[x][y]) / distance[x][y];
                show7 = screen(show1, show4);
                show8 = colordodge(show2, show5);
                show9 = screen(show3, show6);
                pixel.red = radial * (show7 + show8);
                pixel.green = 0;
                pixel.blue = radial * show9;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::modulators::radial, radial_filter_radius, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, show7, show8, show9, timings, x, y, and animartrix_detail::render_parameters::z.
SM8()
void animartrix_detail::ANIMartRIX::SM8 () inline
Definition at line 2451 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.005; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.01; // original Reddit post had no radial movement!
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // float s = 0.7; // zoom factor
                animation.dist = distance[x][y];
                animation.angle = 2;
                animation.z = 5;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_z = 0;
                animation.offset_y = 50 * move.linear[0];
                animation.offset_x = 0;
                animation.low_limit = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 2;
                animation.z = 150;
                animation.offset_x = -50 * move.linear[0];
                float show2 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 1;
                animation.z = 550;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_x = 0;
                animation.offset_y = -50 * move.linear[1];
                float show4 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = 1;
                animation.z = 1250;
                animation.scale_x = 0.15;
                animation.scale_y = 0.15;
                animation.offset_x = 0;
                animation.offset_y = 50 * move.linear[1];
                float show5 = render_value(animation);
                // float radius = radial_filter_radius;   // radius of a radial
                // brightness filter float radial =
                // (radius-distance[x][y])/distance[x][y];
                show3 = add(show1, show2);
                show6 = screen(show4, show5);
                // show9 = screen(show3, show6);
                pixel.red = show3;
                pixel.green = 0;
                pixel.blue = show6;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References add(), animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
SM9()
void animartrix_detail::ANIMartRIX::SM9 () inline
Definition at line 2527 of file animartrix_detail.hpp.
               {
        get_ready();
        timings.master_speed = 0.005; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.0053; // speed ratios for the oscillators, higher
                                   // values = faster transitions
        timings.ratio[4] = 0.0056;
        timings.ratio[5] = 0.0059;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_y = -30 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = -1;
                show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.z = 50;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_y = -30 * move.linear[1];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = -1;
                show2 = render_value(animation);
                animation.dist = distance[x][y]; // + show1/64;
                animation.angle = polar_theta[x][y] + 2 + (show1 / 255) * PI;
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_y = -10 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y] + 2 + (show2 / 255) * PI;
                ;
                animation.z = 5;
                animation.scale_x = 0.09;
                animation.scale_y = 0.09;
                animation.offset_y = -20 * move.linear[0];
                animation.offset_z = 0;
                animation.offset_x = 0;
                animation.low_limit = 0;
                show4 = render_value(animation);
                show5 = screen(show4, show3);
                show6 = colordodge(show5, show3);
                float linear1 = y / 32.f;
                float linear2 = (32 - y) / 32.f;
                pixel.red = show5 * linear1;
                pixel.green = 0;
                pixel.blue = show6 * linear2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), colordodge(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, PI, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, screen(), setPixelColorInternal(), show1, show2, show3, show4, show5, show6, timings, x, y, and animartrix_detail::render_parameters::z.
Spiralus()
void animartrix_detail::ANIMartRIX::Spiralus () inline
Definition at line 1256 of file animartrix_detail.hpp.
                    {
        get_ready();
        timings.master_speed = 0.0011; // speed ratios for the oscillators
        timings.ratio[0] = 1.5;        // higher values = faster transitions
        timings.ratio[1] = 2.3;
        timings.ratio[2] = 3;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.2;
        timings.ratio[5] = 0.03;
        timings.ratio[6] = 0.025;
        timings.ratio[7] = 0.021;
        timings.ratio[8] = 0.027;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 2 * polar_theta[x][y] + move.noise_angle[5] +
                                  move.directional[3] * move.noise_angle[6] *
                                      animation.dist / 10;
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.02;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = move.linear[1];
                float show1 = render_value(animation);
                animation.angle = 2 * polar_theta[x][y] + move.noise_angle[7] +
                                  move.directional[5] * move.noise_angle[8] *
                                      animation.dist / 10;
                animation.offset_y = -move.linear[1];
                animation.z = move.linear[2];
                float show2 = render_value(animation);
                animation.angle = 2 * polar_theta[x][y] + move.noise_angle[6] +
                                  move.directional[6] * move.noise_angle[7] *
                                      animation.dist / 10;
                animation.offset_y = move.linear[2];
                animation.z = move.linear[0];
                float show3 = render_value(animation);
                float f = 1;
                pixel.red = f * (show1 + show2);
                pixel.green = f * (show1 - show2);
                pixel.blue = f * (show3 - show1);
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
Spiralus2()
void animartrix_detail::ANIMartRIX::Spiralus2 () inline
Definition at line 1324 of file animartrix_detail.hpp.
                     {
        get_ready();
        timings.master_speed = 0.0015; // speed ratios for the oscillators
        timings.ratio[0] = 1.5;        // higher values = faster transitions
        timings.ratio[1] = 2.3;
        timings.ratio[2] = 3;
        timings.ratio[3] = 0.05;
        timings.ratio[4] = 0.2;
        timings.ratio[5] = 0.05;
        timings.ratio[6] = 0.055;
        timings.ratio[7] = 0.06;
        timings.ratio[8] = 0.027;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = 5 * polar_theta[x][y] + move.noise_angle[5] +
                                  move.directional[3] * move.noise_angle[6] *
                                      animation.dist / 10;
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.02;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = move.linear[1];
                float show1 = render_value(animation);
                animation.angle = 6 * polar_theta[x][y] + move.noise_angle[7] +
                                  move.directional[5] * move.noise_angle[8] *
                                      animation.dist / 10;
                animation.offset_y = -move.linear[1];
                animation.z = move.linear[2];
                float show2 = render_value(animation);
                animation.angle = 6 * polar_theta[x][y] + move.noise_angle[6] +
                                  move.directional[6] * move.noise_angle[7] *
                                      animation.dist / 10;
                animation.offset_y = move.linear[2];
                animation.z = move.linear[0];
                animation.dist = distance[x][y] * 0.8;
                float show3 = render_value(animation);
                float f = 1; //(24-distance[x][y])/24;
                pixel.red = f * (show1 + show2);
                pixel.green = f * (show1 - show2);
                pixel.blue = f * (show3 - show1);
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, timings, x, y, and animartrix_detail::render_parameters::z.
subtract()
float animartrix_detail::ANIMartRIX::subtract (float & a, float & b) inline
Definition at line 217 of file animartrix_detail.hpp.
{ return a - b; }
References a, and b.
Referenced by Complex_Kaleido_3().
Water()
void animartrix_detail::ANIMartRIX::Water () inline
Definition at line 3224 of file animartrix_detail.hpp.
                 {
        get_ready();
        timings.master_speed = 0.037; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.031;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.1;
        timings.ratio[6] = 0.41;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist =
                    distance[x][y] +
                    4 * sinf(move.directional[5] * PI + (float)x / 2) +
                    4 * cosf(move.directional[6] * PI + float(y) / 2);
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.06;
                animation.scale_y = 0.06;
                animation.offset_z = -10 * move.linear[0];
                animation.offset_y = 10;
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist = (10 + move.directional[0]) *
                                 sinf(-move.radial[5] + move.radial[0] +
                                      (distance[x][y] / (3)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = (10 + move.directional[1]) *
                                 sinf(-move.radial[5] + move.radial[1] +
                                      (distance[x][y] / (3)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[1];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = (10 + move.directional[2]) *
                                 sinf(-move.radial[5] + move.radial[2] +
                                      (distance[x][y] / (3)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show4 = render_value(animation);
                // float radius = radial_filter_radius;   // radius of a radial
                // brightness filter float radial =
                // (radius-distance[x][y])/distance[x][y];
                // pixel.red    = show2;
                pixel.blue = (0.7 * show2 + 0.6 * show3 + 0.5 * show4);
                pixel.red = pixel.blue - 40;
                pixel.green = 0;
                // pixel.red     = radial*show3;
                // pixel.green     = 0.9*radial*show4;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::modulators::directional, animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, PI, pixel, polar_theta, animartrix_detail::modulators::radial, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Waves()
void animartrix_detail::ANIMartRIX::Waves () inline
Definition at line 690 of file animartrix_detail.hpp.
                 {
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 2;        // higher values = faster transitions
        timings.ratio[1] = 2.1;
        timings.ratio[2] = 1.2;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.scale_z = 0.1;
                animation.dist = distance[x][y];
                animation.offset_y = 0;
                animation.offset_x = 0;
                animation.z = 2 * distance[x][y] - move.linear[0];
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y];
                animation.dist = distance[x][y];
                animation.z = 2 * distance[x][y] - move.linear[1];
                float show2 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = 0;
                pixel.blue = show2;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, timings, x, y, and animartrix_detail::render_parameters::z.
xyMap()
virtual uint16_t animartrix_detail::ANIMartRIX::xyMap (uint16_t x, uint16_t y) pure virtual
Implemented in fl::FastLEDANIMartRIX.
Yves()
void animartrix_detail::ANIMartRIX::Yves () inline
Definition at line 1178 of file animartrix_detail.hpp.
                {
        get_ready();
        a = micros(); // for time measurement in report_performance()
        timings.master_speed = 0.001; // speed ratios for the oscillators
        timings.ratio[0] = 3;         // higher values = faster transitions
        timings.ratio[1] = 2;
        timings.ratio[2] = 1;
        timings.ratio[3] = 0.13;
        timings.ratio[4] = 0.15;
        timings.ratio[5] = 0.03;
        timings.ratio[6] = 0.025;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle =
                    polar_theta[x][y] + 2 * PI + move.noise_angle[5];
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.08;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    polar_theta[x][y] + 2 * PI + move.noise_angle[6];
                ;
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.08;
                animation.offset_y = -move.linear[1];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + show1 / 100 +
                                  move.noise_angle[3] + move.noise_angle[4];
                animation.dist = distance[x][y] + show2 / 50;
                animation.offset_y = -move.linear[2];
                animation.offset_y += show1 / 100;
                animation.offset_x += show2 / 100;
                float show3 = render_value(animation);
                animation.offset_y = 0;
                animation.offset_x = 0;
                float show4 = render_value(animation);
                pixel.red = show3;
                pixel.green = show3 * show4 / 255;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References a, animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::oscillators::master_speed, move, animartrix_detail::modulators::noise_angle, num_x, num_y, animartrix_detail::oscillators::offset, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, PI, pixel, polar_theta, animartrix_detail::oscillators::ratio, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, animartrix_detail::render_parameters::scale_z, setPixelColorInternal(), show1, show2, show3, show4, timings, x, y, and animartrix_detail::render_parameters::z.
Zoom()
void animartrix_detail::ANIMartRIX::Zoom () inline
Definition at line 1444 of file animartrix_detail.hpp.
                { // nice one
        get_ready();
        run_default_oscillators();
        timings.master_speed = 0.003;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = (distance[x][y] * distance[x][y]) / 2;
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.005;
                animation.scale_y = 0.005;
                animation.offset_y = -10 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                animation.low_limit = 0;
                float show1 = render_value(animation);
                float linear = 1; //(y+1)/(num_y-1.f);
                pixel.red = show1 * linear;
                pixel.green = 0;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), run_default_oscillators(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Zoom2()
void animartrix_detail::ANIMartRIX::Zoom2 () inline
Definition at line 3538 of file animartrix_detail.hpp.
                 { // nice one
        get_ready();
        run_default_oscillators();
        timings.master_speed = 0.003;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = (distance[x][y] * distance[x][y]) / 2;
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.005;
                animation.scale_y = 0.005;
                animation.offset_y = -10 * move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0.1 * move.linear[0];
                animation.z = 0;
                animation.low_limit = 0;
                float show1 = render_value(animation);
                // float linear = 1;//(y+1)/(num_y-1.f);
                pixel.red = show1;
                pixel.green = 0;
                pixel.blue = 40 - show1;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References animartrix_detail::render_parameters::angle, animation, animartrix_detail::rgb::blue, calculate_oscillators(), animartrix_detail::render_parameters::dist, distance, get_ready(), animartrix_detail::rgb::green, animartrix_detail::modulators::linear, animartrix_detail::render_parameters::low_limit, animartrix_detail::oscillators::master_speed, move, num_x, num_y, animartrix_detail::render_parameters::offset_x, animartrix_detail::render_parameters::offset_y, animartrix_detail::render_parameters::offset_z, pixel, polar_theta, animartrix_detail::rgb::red, render_value(), rgb_sanity_check(), run_default_oscillators(), animartrix_detail::render_parameters::scale_x, animartrix_detail::render_parameters::scale_y, setPixelColorInternal(), show1, timings, x, y, and animartrix_detail::render_parameters::z.
Member Data Documentation
a
unsigned long animartrix_detail::ANIMartRIX::a
Definition at line 170 of file animartrix_detail.hpp.
Referenced by add(), colorburn(), colordodge(), get_ready(), lerp(), Module_Experiment10(), multiply(), report_performance(), screen(), subtract(), and Yves().
animation
render_parameters animartrix_detail::ANIMartRIX::animation
Definition at line 160 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), render_value(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
b
unsigned long animartrix_detail::ANIMartRIX::b
Definition at line 170 of file animartrix_detail.hpp.
Referenced by add(), colorburn(), colordodge(), lerp(), logOutput(), multiply(), report_performance(), screen(), and subtract().
c
unsigned long animartrix_detail::ANIMartRIX::c
Definition at line 170 of file animartrix_detail.hpp.
Referenced by logFrame(), and report_performance().
currentTime
uint32_t animartrix_detail::ANIMartRIX::currentTime = 0
Definition at line 182 of file animartrix_detail.hpp.
Referenced by getTime(), and setTime().
distance
fl::HeapVector<fl::HeapVector<float> > animartrix_detail::ANIMartRIX::distance
Definition at line 168 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), render_polar_lookup_table(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
move
modulators animartrix_detail::ANIMartRIX::move
Definition at line 162 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), calculate_oscillators(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
num_x
int animartrix_detail::ANIMartRIX::num_x
Definition at line 151 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), render_polar_lookup_table(), report_performance(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
num_y
int animartrix_detail::ANIMartRIX::num_y
Definition at line 152 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), render_polar_lookup_table(), report_performance(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
pixel
rgb animartrix_detail::ANIMartRIX::pixel
Definition at line 163 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), rgb_sanity_check(), Rings(), Rotating_Blob(), Scaledemo1(), fl::FastLEDANIMartRIX::setPixelColor(), fl::FastLEDANIMartRIX::setPixelColorInternal(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
polar_theta
fl::HeapVector<fl::HeapVector<float> > animartrix_detail::ANIMartRIX::polar_theta
Definition at line 166 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), render_polar_lookup_table(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
radial_filter_radius
float animartrix_detail::ANIMartRIX::radial_filter_radius = 23.0
Definition at line 156 of file animartrix_detail.hpp.
Referenced by Caleido3(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Hot_Blob(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), Slow_Fade(), SM5(), and SM6().
serpentine
bool animartrix_detail::ANIMartRIX::serpentine
Definition at line 158 of file animartrix_detail.hpp.
show0
float animartrix_detail::ANIMartRIX::show0
Definition at line 172 of file animartrix_detail.hpp.
show1
float animartrix_detail::ANIMartRIX::show1
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
show2
float animartrix_detail::ANIMartRIX::show2
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment10(), Module_Experiment4(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), and Yves().
show3
float animartrix_detail::ANIMartRIX::show3
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Hot_Blob(), Lava1(), Module_Experiment10(), Module_Experiment4(), Module_Experiment8(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), and Yves().
show4
float animartrix_detail::ANIMartRIX::show4
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Hot_Blob(), Module_Experiment10(), Module_Experiment8(), Parametric_Water(), Rotating_Blob(), SM1(), SM10(), SM3(), SM5(), SM6(), SM8(), SM9(), Water(), and Yves().
show5
float animartrix_detail::ANIMartRIX::show5
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Parametric_Water(), SM1(), SM10(), SM3(), SM5(), SM6(), SM8(), and SM9().
show6
float animartrix_detail::ANIMartRIX::show6
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Parametric_Water(), SM10(), SM5(), SM6(), SM8(), and SM9().
show7
float animartrix_detail::ANIMartRIX::show7
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Complex_Kaleido_3(), Parametric_Water(), and SM6().
show8
float animartrix_detail::ANIMartRIX::show8
Definition at line 172 of file animartrix_detail.hpp.
Referenced by Complex_Kaleido_3(), and SM6().
show9
float animartrix_detail::ANIMartRIX::show9
Definition at line 172 of file animartrix_detail.hpp.
Referenced by SM6().
speed_factor
float animartrix_detail::ANIMartRIX::speed_factor = 1
Definition at line 154 of file animartrix_detail.hpp.
Referenced by calculate_oscillators().
timings
oscillators animartrix_detail::ANIMartRIX::timings
Definition at line 161 of file animartrix_detail.hpp.
Referenced by Big_Caleido(), calculate_oscillators(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), init(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), run_default_oscillators(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/2d/animartrix_detail.hpp