FastLED: /home/runner/work/FastLED/FastLED/examples/Fire2012/Fire2012.ino File Reference
Fire2012.ino File Reference
Detailed Description
Simple one-dimensional fire animation.
Definition in file Fire2012.ino.
#include <FastLED.h>
Macros
#define BRIGHTNESS 200
#define CHIPSET WS2811
#define COLOR_ORDER GRB
#define COOLING 55
#define FRAMES_PER_SECOND 60
#define LED_PIN 5
#define NUM_LEDS 30
#define SPARKING 120
Functions
void Fire2012 ()
void loop ()
void setup ()
Variables
bool gReverseDirection = false
CRGB leds [NUM_LEDS]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 200
Definition at line 12 of file Fire2012.ino.
CHIPSET
#define CHIPSET WS2811
Definition at line 9 of file Fire2012.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 8 of file Fire2012.ino.
COOLING
#define COOLING 55
Examples
Fire2012.ino, and Fire2012WithPalette.ino.
Definition at line 68 of file Fire2012.ino.
Referenced by Fire2012(), and Fire2012WithPalette().
FRAMES_PER_SECOND
#define FRAMES_PER_SECOND 60
Definition at line 13 of file Fire2012.ino.
LED_PIN
#define LED_PIN 5
Definition at line 7 of file Fire2012.ino.
NUM_LEDS
#define NUM_LEDS 30
Definition at line 10 of file Fire2012.ino.
SPARKING
#define SPARKING 120
Examples
Fire2012.ino, and Fire2012WithPalette.ino.
Definition at line 73 of file Fire2012.ino.
Referenced by Fire2012(), and Fire2012WithPalette().
Function Documentation
Fire2012()
void Fire2012 ()
Examples
Fire2012.ino.
Definition at line 76 of file Fire2012.ino.
{
// Array of temperature readings at each simulation cell
  static uint8_t heat[NUM_LEDS];
  // Step 1.  Cool down every cell a little
    for( int i = 0; i < NUM_LEDS; i++) {
      heat[i] = qsub8( heat[i],  random8(0, ((COOLING * 10) / NUM_LEDS) + 2));
    }
    // Step 2.  Heat from each cell drifts 'up' and diffuses a little
    for( int k= NUM_LEDS - 1; k >= 2; k--) {
      heat[k] = (heat[k - 1] + heat[k - 2] + heat[k - 2] ) / 3;
    }
    // Step 3.  Randomly ignite new 'sparks' of heat near the bottom
    if( random8() < SPARKING ) {
      int y = random8(7);
      heat[y] = qadd8( heat[y], random8(160,255) );
    }
    // Step 4.  Map from heat cells to LED colors
    for( int j = 0; j < NUM_LEDS; j++) {
      CRGB color = HeatColor( heat[j]);
      int pixelnumber;
      if( gReverseDirection ) {
        pixelnumber = (NUM_LEDS-1) - j;
      } else {
        pixelnumber = j;
      }
      leds[pixelnumber] = color;
    }
}
References COOLING, gReverseDirection, heat, HeatColor(), leds, NUM_LEDS, qadd8(), qsub8(), random8(), SPARKING, and y.
Referenced by loop().
loop()
void loop ()
Definition at line 25 of file Fire2012.ino.
{
  // Add entropy to random number generator; we use a lot of it.
  // random16_add_entropy( random());
  Fire2012(); // run simulation frame
  FastLED.show(); // display this frame
  FastLED.delay(1000 / FRAMES_PER_SECOND);
}
References CFastLED::delay(), FastLED, Fire2012(), FRAMES_PER_SECOND, and CFastLED::show().
setup()
void setup ()
Definition at line 19 of file Fire2012.ino.
             {
  delay(3000); // sanity delay
  FastLED.addLeds<CHIPSET, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );
  FastLED.setBrightness( BRIGHTNESS );
}
References CFastLED::addLeds(), BRIGHTNESS, CHIPSET, COLOR_ORDER, FastLED, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), and TypicalLEDStrip.
Variable Documentation
gReverseDirection
bool gReverseDirection = false
Examples
Fire2012.ino, and Fire2012WithPalette.ino.
Definition at line 15 of file Fire2012.ino.
Referenced by Fire2012(), and Fire2012WithPalette().
leds
CRGB leds[NUM_LEDS]
Definition at line 17 of file Fire2012.ino.