FastLED: Selectable Class Reference
Selectable Class Reference abstract
Detailed Description
Abstract class for "selectable" things.
Definition at line 34 of file fastpin.h.
#include <fastpin.h>
Public Member Functions
virtual ~Selectable ()
virtual bool isSelected ()=0
Check if this object is currently selected.
virtual void release ()=0
Release this object.
virtual void select ()=0
Select this object.
Constructor & Destructor Documentation
~Selectable()
virtual Selectable::~Selectable () inline virtual
Definition at line 37 of file fastpin.h.
{}
Member Function Documentation
isSelected()
virtual bool Selectable::isSelected () pure virtual
Check if this object is currently selected.
Implemented in Pin.
release()
virtual void Selectable::release () pure virtual
Release this object.
Implemented in Pin.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release().
select()
virtual void Selectable::select () pure virtual
Select this object.
Implemented in Pin.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fastpin.h