FastLED: Clockless Chipsets
Clockless Chipsets
LED Chipset Controllers
Detailed Description
These chipsets have only a single data line.
The clockless chipset controllers use the same base class and the same protocol, but with varying timing periods.
These controllers have 3 control points in their cycle for each bit:
At T=0        : the line is raised hi to start a bit
At T=T1       : the line is dropped low to transmit a zero bit
At T=T1+T2    : the line is dropped low to transmit a one bit
At T=T1+T2+T3 : the cycle is concluded (next bit can be sent)
The units used for T1, T2, and T3 is nanoseconds.
For 8MHz/16MHz/24MHz frequencies, these values are also guaranteed to be integral multiples of an 8MHz clock (125ns increments).
Note
The base class, ClocklessController, is platform-specific.
Classes
class APA104< DATA_PIN, RGB_ORDER >
APA104 controller class.
class APA106< DATA_PIN, RGB_ORDER >
APA106 controller class.
class DMXSERIAL< RGB_ORDER >
DMX512 based LED controller class, using the DMXSerial library.
class DMXSerialController< RGB_ORDER >
DMX512 based LED controller class, using the DMXSerial library.
class DMXSIMPLE< DATA_PIN, RGB_ORDER >
DMX512 based LED controller class, using the DmxSimple library.
class DMXSimpleController< DATA_PIN, RGB_ORDER >
DMX512 based LED controller class, using the DmxSimple library.
class DP1903Controller400Khz< DATA_PIN, RGB_ORDER >
DP1903 controller class @ 400 KHz.
class DP1903Controller800Khz< DATA_PIN, RGB_ORDER >
DP1903 controller class @ 800 KHz.
class GE8822< DATA_PIN, RGB_ORDER >
GE8822 controller class.
class GE8822Controller800Khz< DATA_PIN, RGB_ORDER >
GE8822 controller class.
class GS1903< DATA_PIN, RGB_ORDER >
GS1903 controller class.
class GW6205< DATA_PIN, RGB_ORDER >
GW6205 controller class.
class GW6205_400< DATA_PIN, RGB_ORDER >
GW6205_400 controller class.
class GW6205Controller400Khz< DATA_PIN, RGB_ORDER >
GW6205 controller class @ 400 KHz.
class GW6205Controller800Khz< DATA_PIN, RGB_ORDER >
UCS1904 controller class @ 800 KHz.
class LPD1886< DATA_PIN, RGB_ORDER >
LPD1886 controller class.
class LPD1886_8BIT< DATA_PIN, RGB_ORDER >
LPD1886_8BIT controller class.
class LPD1886Controller1250Khz< DATA_PIN, RGB_ORDER >
LPD1886 controller class.
class LPD1886Controller1250Khz_8bit< DATA_PIN, RGB_ORDER >
LPD1886 controller class.
class NEOPIXEL< DATA_PIN >
LED controller for WS2812 LEDs with GRB color order.
class PL9823< DATA_PIN, RGB_ORDER >
PL9823 controller class.
class PL9823Controller< DATA_PIN, RGB_ORDER >
PL9823 controller class.
class SK6812< DATA_PIN, RGB_ORDER >
SK6812 controller class.
class SK6812Controller< DATA_PIN, RGB_ORDER >
SK6812 controller class.
class SK6822< DATA_PIN, RGB_ORDER >
SK6822 controller class.
class SK6822Controller< DATA_PIN, RGB_ORDER >
SK6822 controller class.
class SM16703< DATA_PIN, RGB_ORDER >
SM16703 controller class.
class SM16703Controller< DATA_PIN, RGB_ORDER >
SM16703 controller class.
class TM1803< DATA_PIN, RGB_ORDER >
TM1803 controller class.
class TM1803Controller400Khz< DATA_PIN, RGB_ORDER >
TM1803 controller class.
class TM1804< DATA_PIN, RGB_ORDER >
TM1804 controller class.
class TM1809< DATA_PIN, RGB_ORDER >
TM1809 controller class.
class TM1809Controller800Khz< DATA_PIN, RGB_ORDER >
TM1809 controller class.
class TM1812< DATA_PIN, RGB_ORDER >
TM1812 controller class.
class TM1829< DATA_PIN, RGB_ORDER >
TM1829 controller class.
class TM1829Controller800Khz< DATA_PIN, RGB_ORDER >
TM1829 controller class.
class UCS1903< DATA_PIN, RGB_ORDER >
UCS1903 controller class.
class UCS1903B< DATA_PIN, RGB_ORDER >
UCS1903B controller class.
class UCS1903BController800Khz< DATA_PIN, RGB_ORDER >
UCS1903B controller class.
class UCS1903Controller400Khz< DATA_PIN, RGB_ORDER >
UCS1903 controller class @ 400 KHz.
class UCS1904< DATA_PIN, RGB_ORDER >
UCS1904 controller class.
class UCS1904Controller800Khz< DATA_PIN, RGB_ORDER >
UCS1904 controller class.
class UCS1912< DATA_PIN, RGB_ORDER >
UCS1912 controller class.
class UCS1912Controller< DATA_PIN, RGB_ORDER >
class UCS2903< DATA_PIN, RGB_ORDER >
UCS2903 controller class.
class UCS2903Controller< DATA_PIN, RGB_ORDER >
UCS2903 controller class.
class WS2811< DATA_PIN, RGB_ORDER >
WS2811 controller class.
class WS2811_400< DATA_PIN, RGB_ORDER >
WS2811_400 controller class.
class WS2811Controller400Khz< DATA_PIN, RGB_ORDER >
WS2811 controller class @ 400 KHz.
class WS2811Controller800Khz< DATA_PIN, RGB_ORDER >
WS2811 controller class @ 800 KHz.
class WS2812< DATA_PIN, RGB_ORDER >
WS2812 controller class.
class WS2812B< DATA_PIN, RGB_ORDER >
WS2812B controller class.
class WS2812Controller800Khz< DATA_PIN, RGB_ORDER >
WS2812 controller class @ 800 KHz.
class WS2813< DATA_PIN, RGB_ORDER >
WS2813 controller class.
class WS2813Controller< DATA_PIN, RGB_ORDER >
WS2813 controller class.
class WS2815< DATA_PIN, RGB_ORDER >
WS2815 controller class.
class WS2815Controller< DATA_PIN, RGB_ORDER >
WS2815 controller class @ 400 KHz.
class WS2816< DATA_PIN, RGB_ORDER >
WS2816 controller class.
class WS2852< DATA_PIN, RGB_ORDER >
WS2852 controller class.
Macros
#define FMUL (CLOCKLESS_FREQUENCY/8000000)
Frequency multiplier for each clockless data interval.
#define HAS_DMX_SERIAL
Flag set when the DMXSerial library is included.
#define HAS_DMX_SIMPLE
Flag set when the DmxSimple library is included.
Class Documentation
APA104
class APA104
APA106
class APA106
DMXSERIAL
class DMXSERIAL
Additional Inherited Members
Public Member Functions inherited from DMXSerialController< RGB_ORDER >
virtual void init ()
Initialize the LED controller.
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
DMXSerialController
class DMXSerialController
Public Member Functions
virtual void init ()
Initialize the LED controller.
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Function Documentation
init()
template<EOrder RGB_ORDER = RGB> virtual void DMXSerialController< RGB_ORDER >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 67 of file dmx.h.
{ DMXSerial.init(DMXController); }
showPixels()
template<EOrder RGB_ORDER = RGB> virtual void DMXSerialController< RGB_ORDER >::showPixels (PixelController< RGB_ORDER > & pixels) inline virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 70 of file dmx.h.
{
        int iChannel = 1;
        while(pixels.has(1)) {
            DMXSerial.write(iChannel++, pixels.loadAndScale0());
            DMXSerial.write(iChannel++, pixels.loadAndScale1());
            DMXSerial.write(iChannel++, pixels.loadAndScale2());
            pixels.advanceData();
            pixels.stepDithering();
        }
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
DMXSIMPLE
class DMXSIMPLE
Additional Inherited Members
Public Member Functions inherited from DMXSimpleController< DATA_PIN, RGB_ORDER >
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
static const int LANES_VALUE = LANES
The number of lanes for this controller.
static const uint32_t MASK_VALUE = MASK
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE = RGB_ORDER
The RGB ordering for this controller.
Protected Member Functions inherited from DMXSimpleController< DATA_PIN, RGB_ORDER >
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, LANES, MASK >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
DMXSimpleController
class DMXSimpleController
Public Member Functions
virtual void init ()
Initialize the LED controller.
Public Member Functions inherited from CPixelLEDController< RGB >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
virtual void showPixels (PixelController< RGB_ORDER, 1, 0xFFFFFFFF > &pixels)=0
Send the LED data to the strip.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Protected Member Functions
virtual void showPixels (PixelController< RGB_ORDER > &pixels)
Send the LED data to the strip.
Protected Member Functions inherited from CPixelLEDController< RGB >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from CPixelLEDController< RGB >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Function Documentation
init()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = RGB> virtual void DMXSimpleController< DATA_PIN, RGB_ORDER >::init () inline virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 31 of file dmx.h.
{ DmxSimple.usePin(DATA_PIN); }
References DATA_PIN.
showPixels()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = RGB> virtual void DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 35 of file dmx.h.
{
        int iChannel = 1;
        while(pixels.has(1)) {
            DmxSimple.write(iChannel++, pixels.loadAndScale0());
            DmxSimple.write(iChannel++, pixels.loadAndScale1());
            DmxSimple.write(iChannel++, pixels.loadAndScale2());
            pixels.advanceData();
            pixels.stepDithering();
        }
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
DP1903Controller400Khz
class DP1903Controller400Khz
DP1903Controller800Khz
class DP1903Controller800Khz
GE8822
class GE8822
GE8822Controller800Khz
class GE8822Controller800Khz
GS1903
class GS1903
GW6205
class GW6205
GW6205_400
class GW6205_400
GW6205Controller400Khz
class GW6205Controller400Khz
GW6205Controller800Khz
class GW6205Controller800Khz
LPD1886
class LPD1886
LPD1886_8BIT
class LPD1886_8BIT
LPD1886Controller1250Khz
class LPD1886Controller1250Khz
LPD1886Controller1250Khz_8bit
class LPD1886Controller1250Khz_8bit
NEOPIXEL
class NEOPIXEL
PL9823
class PL9823
PL9823Controller
class PL9823Controller
SK6812
class SK6812
SK6812Controller
class SK6812Controller
SK6822
class SK6822
SK6822Controller
class SK6822Controller
SM16703
class SM16703
SM16703Controller
class SM16703Controller
TM1803
class TM1803
TM1803Controller400Khz
class TM1803Controller400Khz
TM1804
class TM1804
TM1809
class TM1809
TM1809Controller800Khz
class TM1809Controller800Khz
TM1812
class TM1812
TM1829
class TM1829
TM1829Controller800Khz
class TM1829Controller800Khz
UCS1903
class UCS1903
UCS1903B
class UCS1903B
UCS1903BController800Khz
class UCS1903BController800Khz
UCS1903Controller400Khz
class UCS1903Controller400Khz
UCS1904
class UCS1904
UCS1904Controller800Khz
class UCS1904Controller800Khz
UCS1912
class UCS1912
UCS1912Controller
class UCS1912Controller
UCS2903
class UCS2903
UCS2903Controller
class UCS2903Controller
WS2811
class WS2811
WS2811_400
class WS2811_400
WS2811Controller400Khz
class WS2811Controller400Khz
WS2811Controller800Khz
class WS2811Controller800Khz
WS2812
class WS2812
WS2812B
class WS2812B
WS2812Controller800Khz
class WS2812Controller800Khz
WS2813
class WS2813
WS2813Controller
class WS2813Controller
WS2815
class WS2815
WS2815Controller
class WS2815Controller
WS2816
class WS2816
Additional Inherited Members
Public Types inherited from WS2816Controller< DATA_PIN, RGB_ORDER >
typedef WS2812Controller800Khz< DATA_PIN, RGB > ControllerBaseT
Public Member Functions inherited from WS2816Controller< DATA_PIN, RGB_ORDER >
WS2816Controller ()
~WS2816Controller ()
virtual void * beginShowLeds (int size) override
virtual void endShowLeds (void *data) override
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels) override
Send the LED data to the strip.
Public Member Functions inherited from CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Static Public Attributes inherited from WS2816Controller< DATA_PIN, RGB_ORDER >
static const int LANES
static const uint32_t MASK
Static Public Attributes inherited from CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Protected Member Functions inherited from CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
WS2852
class WS2852
Macro Definition Documentation
FMUL
#define FMUL (CLOCKLESS_FREQUENCY/8000000)
Frequency multiplier for each clockless data interval.
See also
Notes in Clockless Chipsets
Definition at line 770 of file chipsets.h.
HAS_DMX_SERIAL
#define HAS_DMX_SERIAL
Flag set when the DMXSerial library is included.
Definition at line 55 of file dmx.h.
HAS_DMX_SIMPLE
#define HAS_DMX_SIMPLE
Flag set when the DmxSimple library is included.
Definition at line 18 of file dmx.h.