FastLED: /home/runner/work/FastLED/FastLED/examples/Fire2012WithPalette/Fire2012WithPalette.ino File Reference
Fire2012WithPalette.ino File Reference
Detailed Description
Simple one-dimensional fire animation with a programmable color palette.
Definition in file Fire2012WithPalette.ino.
#include <FastLED.h>
Macros
#define BRIGHTNESS 200
#define CHIPSET WS2811
#define COLOR_ORDER GRB
#define COOLING 55
#define FRAMES_PER_SECOND 60
#define LED_PIN 5
#define NUM_LEDS 30
#define SPARKING 120
Functions
void Fire2012WithPalette ()
void loop ()
void setup ()
Variables
CRGBPalette16 gPal
bool gReverseDirection = false
CRGB leds [NUM_LEDS]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 200
Definition at line 12 of file Fire2012WithPalette.ino.
CHIPSET
#define CHIPSET WS2811
Definition at line 9 of file Fire2012WithPalette.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 8 of file Fire2012WithPalette.ino.
COOLING
#define COOLING 55
Definition at line 52 of file Fire2012WithPalette.ino.
FRAMES_PER_SECOND
#define FRAMES_PER_SECOND 60
Definition at line 13 of file Fire2012WithPalette.ino.
LED_PIN
#define LED_PIN 5
Definition at line 7 of file Fire2012WithPalette.ino.
NUM_LEDS
#define NUM_LEDS 30
Definition at line 10 of file Fire2012WithPalette.ino.
SPARKING
#define SPARKING 120
Definition at line 57 of file Fire2012WithPalette.ino.
Function Documentation
Fire2012WithPalette()
void Fire2012WithPalette ()
Examples
Fire2012WithPalette.ino.
Definition at line 60 of file Fire2012WithPalette.ino.
{
// Array of temperature readings at each simulation cell
  static uint8_t heat[NUM_LEDS];
  // Step 1.  Cool down every cell a little
    for( int i = 0; i < NUM_LEDS; i++) {
      heat[i] = qsub8( heat[i],  random8(0, ((COOLING * 10) / NUM_LEDS) + 2));
    }
    // Step 2.  Heat from each cell drifts 'up' and diffuses a little
    for( int k= NUM_LEDS - 1; k >= 2; k--) {
      heat[k] = (heat[k - 1] + heat[k - 2] + heat[k - 2] ) / 3;
    }
    // Step 3.  Randomly ignite new 'sparks' of heat near the bottom
    if( random8() < SPARKING ) {
      int y = random8(7);
      heat[y] = qadd8( heat[y], random8(160,255) );
    }
    // Step 4.  Map from heat cells to LED colors
    for( int j = 0; j < NUM_LEDS; j++) {
      // Scale the heat value from 0-255 down to 0-240
      // for best results with color palettes.
      uint8_t colorindex = scale8( heat[j], 240);
      CRGB color = ColorFromPalette( gPal, colorindex);
      int pixelnumber;
      if( gReverseDirection ) {
        pixelnumber = (NUM_LEDS-1) - j;
      } else {
        pixelnumber = j;
      }
      leds[pixelnumber] = color;
    }
}
References ColorFromPalette(), COOLING, gPal, gReverseDirection, heat, leds, NUM_LEDS, qadd8(), qsub8(), random8(), scale8(), SPARKING, and y.
Referenced by loop().
loop()
void loop ()
Definition at line 145 of file Fire2012WithPalette.ino.
{
  // Add entropy to random number generator; we use a lot of it.
  random16_add_entropy( random());
  // Fourth, the most sophisticated: this one sets up a new palette every
  // time through the loop, based on a hue that changes every time.
  // The palette is a gradient from black, to a dark color based on the hue,
  // to a light color based on the hue, to white.
  //
  //   static uint8_t hue = 0;
  //   hue++;
  //   CRGB darkcolor  = CHSV(hue,255,192); // pure hue, three-quarters brightness
  //   CRGB lightcolor = CHSV(hue,128,255); // half 'whitened', full brightness
  //   gPal = CRGBPalette16( CRGB::Black, darkcolor, lightcolor, CRGB::White);
  Fire2012WithPalette(); // run simulation frame, using palette colors
  FastLED.show(); // display this frame
  FastLED.delay(1000 / FRAMES_PER_SECOND);
}
References CFastLED::delay(), FastLED, Fire2012WithPalette(), FRAMES_PER_SECOND, random16_add_entropy(), and CFastLED::show().
setup()
void setup ()
Definition at line 124 of file Fire2012WithPalette.ino.
             {
  delay(3000); // sanity delay
  FastLED.addLeds<CHIPSET, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );
  FastLED.setBrightness( BRIGHTNESS );
  // This first palette is the basic 'black body radiation' colors,
  // which run from black to red to bright yellow to white.
  gPal = HeatColors_p;
  // These are other ways to set up the color palette for the 'fire'.
  // First, a gradient from black to red to yellow to white -- similar to HeatColors_p
  //   gPal = CRGBPalette16( CRGB::Black, CRGB::Red, CRGB::Yellow, CRGB::White);
  // Second, this palette is like the heat colors, but blue/aqua instead of red/yellow
  //   gPal = CRGBPalette16( CRGB::Black, CRGB::Blue, CRGB::Aqua,  CRGB::White);
  // Third, here's a simpler, three-step gradient, from black to red to white
  //   gPal = CRGBPalette16( CRGB::Black, CRGB::Red, CRGB::White);
}
References CFastLED::addLeds(), BRIGHTNESS, CHIPSET, COLOR_ORDER, FastLED, gPal, HeatColors_p, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), and TypicalLEDStrip.
Variable Documentation
gPal
CRGBPalette16 gPal
Examples
Fire2012WithPalette.ino.
Definition at line 19 of file Fire2012WithPalette.ino.
Referenced by Fire2012WithPalette(), and setup().
gReverseDirection
bool gReverseDirection = false
Definition at line 15 of file Fire2012WithPalette.ino.
leds
CRGB leds[NUM_LEDS]
Definition at line 17 of file Fire2012WithPalette.ino.