FastLED: fl::DemoReel100 Class Reference
fl::DemoReel100 Class Reference
Detailed Description
Definition at line 22 of file demoreel100.h.
#include <demoreel100.h>
Public Member Functions
DemoReel100 (uint16_t num_leds)
void draw (DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Member Functions
void addGlitter (fract8 chanceOfGlitter, CRGB *leds)
void bpm (CRGB *leds)
void confetti (CRGB *leds)
void juggle (CRGB *leds)
void nextPattern ()
void rainbow (CRGB *leds)
void rainbowWithGlitter (CRGB *leds)
void runPattern (CRGB *leds)
void sinelon (CRGB *leds)
Private Attributes
uint8_t current_pattern_number = 0
uint8_t hue = 0
unsigned long start_time = 0
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
DemoReel100()
fl::DemoReel100::DemoReel100 (uint16_t num_leds) inline
Definition at line 24 of file demoreel100.h.
: Fx1d(num_leds) {}
Member Function Documentation
addGlitter()
void fl::DemoReel100::addGlitter (fract8 chanceOfGlitter, CRGB * leds) inline private
Definition at line 92 of file demoreel100.h.
{
        if (random8() < chanceOfGlitter) {
            leds[random16(mNumLeds)] += CRGB::White;
        }
    }
References leds, fl::Fx::mNumLeds, random16(), random8(), and CRGB::White.
Referenced by rainbowWithGlitter().
bpm()
void fl::DemoReel100::bpm (CRGB * leds) inline private
Definition at line 112 of file demoreel100.h.
{
        // colored stripes pulsing at a defined Beats-Per-Minute (BPM)
        uint8_t BeatsPerMinute = 62;
        CRGBPalette16 palette = PartyColors_p;
        uint8_t beat = beatsin8(BeatsPerMinute, 64, 255);
        for (uint16_t i = 0; i < mNumLeds; i++) {
            leds[i] =
                ColorFromPalette(palette, hue + (i * 2), beat - hue + (i * 10));
        }
    }
References beatsin8(), ColorFromPalette(), hue, leds, fl::Fx::mNumLeds, and PartyColors_p.
confetti()
void fl::DemoReel100::confetti (CRGB * leds) inline private
Definition at line 98 of file demoreel100.h.
{
        // random colored speckles that blink in and fade smoothly
        fadeToBlackBy(leds, mNumLeds, 10);
        int pos = random16(mNumLeds);
        leds[pos] += CHSV(hue + random8(64), 200, 255);
    }
References fadeToBlackBy(), hue, leds, fl::Fx::mNumLeds, pos, random16(), and random8().
draw()
void fl::DemoReel100::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 26 of file demoreel100.h.
{
        CRGB *leds = context.leds;
        if (leds == nullptr || mNumLeds == 0) {
            return;
        }
        if (start_time == 0) {
            start_time = millis();
        }
        // Call the current pattern function once, updating the 'leds' array
        runPattern(leds);
        // do some periodic updates
        EVERY_N_MILLISECONDS(20) {
            hue++;
        } // slowly cycle the "base color" through the rainbow
        EVERY_N_SECONDS(10) { nextPattern(); } // change patterns periodically
    }
References EVERY_N_MILLISECONDS, EVERY_N_SECONDS, hue, fl::_DrawContext::leds, leds, fl::Fx::mNumLeds, nextPattern(), runPattern(), and start_time.
fxName()
fl::Str fl::DemoReel100::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 45 of file demoreel100.h.
{ return "DemoReel100"; }
juggle()
void fl::DemoReel100::juggle (CRGB * leds) inline private
Definition at line 123 of file demoreel100.h.
{
        // eight colored dots, weaving in and out of sync with each other
        fadeToBlackBy(leds, mNumLeds, 20);
        uint8_t dothue = 0;
        for (uint16_t i = 0; i < 8; i++) {
            leds[beatsin16(i + 7, 0, mNumLeds - 1)] |= CHSV(dothue, 200, 255);
            dothue += 32;
        }
    }
References beatsin16(), fadeToBlackBy(), leds, and fl::Fx::mNumLeds.
nextPattern()
void fl::DemoReel100::nextPattern () inline private
Definition at line 52 of file demoreel100.h.
                       {
        // add one to the current pattern number, and wrap around at the end
        current_pattern_number =
            (current_pattern_number + 1) % 6; // 6 is the number of patterns
    }
References current_pattern_number.
Referenced by draw().
rainbow()
void fl::DemoReel100::rainbow (CRGB * leds) inline private
Definition at line 81 of file demoreel100.h.
{
        // FastLED's built-in rainbow generator
        fill_rainbow(leds, mNumLeds, hue, 7);
    }
References fill_rainbow(), hue, leds, and fl::Fx::mNumLeds.
rainbowWithGlitter()
void fl::DemoReel100::rainbowWithGlitter (CRGB * leds) inline private
Definition at line 86 of file demoreel100.h.
{
        // built-in FastLED rainbow, plus some random sparkly glitter
        rainbow(leds);
        addGlitter(80, leds);
    }
References addGlitter(), leds, and rainbow().
runPattern()
void fl::DemoReel100::runPattern (CRGB * leds) inline private
Definition at line 58 of file demoreel100.h.
{
        switch (current_pattern_number) {
        case 0:
            rainbow(leds);
            break;
        case 1:
            rainbowWithGlitter(leds);
            break;
        case 2:
            confetti(leds);
            break;
        case 3:
            sinelon(leds);
            break;
        case 4:
            juggle(leds);
            break;
        case 5:
            bpm(leds);
            break;
        }
    }
References bpm(), confetti(), current_pattern_number, juggle(), leds, rainbow(), rainbowWithGlitter(), and sinelon().
Referenced by draw().
sinelon()
void fl::DemoReel100::sinelon (CRGB * leds) inline private
Definition at line 105 of file demoreel100.h.
{
        // a colored dot sweeping back and forth, with fading trails
        fadeToBlackBy(leds, mNumLeds, 20);
        int pos = beatsin16(13, 0, mNumLeds - 1);
        leds[pos] += CHSV(hue, 255, 192);
    }
References beatsin16(), fadeToBlackBy(), hue, leds, fl::Fx::mNumLeds, and pos.
Member Data Documentation
current_pattern_number
uint8_t fl::DemoReel100::current_pattern_number = 0 private
Definition at line 48 of file demoreel100.h.
Referenced by nextPattern(), and runPattern().
hue
uint8_t fl::DemoReel100::hue = 0 private
Definition at line 49 of file demoreel100.h.
Referenced by bpm(), confetti(), draw(), rainbow(), and sinelon().
start_time
unsigned long fl::DemoReel100::start_time = 0 private
Definition at line 50 of file demoreel100.h.
Referenced by draw().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/1d/demoreel100.h