FastLED: ColorHSV Struct Reference
ColorHSV Struct Reference
Detailed Description
Definition at line 56 of file color.h.
#include <color.h>
Public Member Functions
ColorHSV ()
ColorHSV (const Color3i &color)
ColorHSV (const ColorHSV &other)
ColorHSV (float h, float s, float v)
void FromRGB (const Color3i &rgb)
bool operator!= (const ColorHSV &other) const
ColorHSV & operator= (const Color3i &color)
bool operator== (const ColorHSV &other) const
template<typename PrintStream >
void Print (PrintStream *stream)
void Set (const ColorHSV &other)
void Set (float h, float s, float v)
Color3i ToRGB () const
Public Attributes
float h_
float s_
float v_
Constructor & Destructor Documentation
ColorHSV() [1/4]
ColorHSV::ColorHSV () inline
Definition at line 57 of file color.h.
: h_(0), s_(0), v_(0) {}
ColorHSV() [2/4]
ColorHSV::ColorHSV (float h, float s, float v) inline
Definition at line 58 of file color.h.
{
    Set(h,s,v);
  }
References Set().
ColorHSV() [3/4]
ColorHSV::ColorHSV (const Color3i & color) inline explicit
Definition at line 61 of file color.h.
{
    FromRGB(color);
  }
References FromRGB().
ColorHSV() [4/4]
ColorHSV::ColorHSV (const ColorHSV & other) inline
Definition at line 68 of file color.h.
{
    Set(other);
  }
References Set().
Member Function Documentation
FromRGB()
void ColorHSV::FromRGB (const Color3i & rgb)
Definition at line 101 of file color.cpp.
{
  typedef double FloatT;
  FloatT r = (FloatT) rgb.r_/255.f;
  FloatT g = (FloatT) rgb.g_/255.f;
  FloatT b = (FloatT) rgb.b_/255.f;
  FloatT max_rgb = max(r, max(g, b));
  FloatT min_rgb = min(r, min(g, b));
  v_ = max_rgb;
  FloatT d = max_rgb - min_rgb;
  s_ = max_rgb == 0 ? 0 : d / max_rgb;
  if (max_rgb == min_rgb) {
    h_ = 0; // achromatic
  } else {
    if (max_rgb == r) {
      h_ = (g - b) / d + (g < b ? 6 : 0);
    } else if (max_rgb == g) {
      h_ = (b - r) / d + 2;
    } else if (max_rgb == b) {
      h_ = (r - g) / d + 4;
    }
    h_ /= 6;
  }
}
References Color3i::b_, Color3i::g_, h_, Color3i::r_, s_, and v_.
Referenced by ColorHSV(), and operator=().
operator!=()
bool ColorHSV::operator!= (const ColorHSV & other) const inline
Definition at line 91 of file color.h.
{
    return !(*this == other);
  }
operator=()
ColorHSV & ColorHSV::operator= (const Color3i & color) inline
Definition at line 64 of file color.h.
{
    FromRGB(color);
    return *this;
  }
References FromRGB().
operator==()
bool ColorHSV::operator== (const ColorHSV & other) const inline
Definition at line 88 of file color.h.
{
    return h_ == other.h_ && s_ == other.s_ && v_ == other.v_;
  }
References h_, s_, and v_.
Print()
template<typename PrintStream > void ColorHSV::Print (PrintStream * stream) inline
Definition at line 81 of file color.h.
{
      stream->print("HSV:\t");
    stream->print(h_); stream->print(",\t");
    stream->print(s_); stream->print(",\t");
    stream->print(v_); stream->print("\n");
  }
References h_, s_, and v_.
Set() [1/2]
void ColorHSV::Set (const ColorHSV & other) inline
Definition at line 71 of file color.h.
{
      Set(other.h_, other.s_, other.v_);
  }
References h_, s_, Set(), and v_.
Referenced by ColorHSV(), ColorHSV(), and Set().
Set() [2/2]
void ColorHSV::Set (float h, float s, float v) inline
Definition at line 74 of file color.h.
{
    h_ = h;
    s_ = s;
    v_ = v;
  }
References h_, s_, and v_.
ToRGB()
Color3i ColorHSV::ToRGB () const
Definition at line 128 of file color.cpp.
{
  typedef double FloatT;
  FloatT r = 0;
  FloatT g = 0;
  FloatT b = 0;
  int i = int(h_ * 6);
  FloatT f = h_ * 6.0 - static_cast<FloatT>(i);
  FloatT p = v_ * (1.0 - s_);
  FloatT q = v_ * (1.0 - f * s_);
  FloatT t = v_ * (1.0 - (1.0 - f) * s_);
  switch(i % 6){
    case 0: r = v_, g = t, b = p; break;
    case 1: r = q, g = v_, b = p; break;
    case 2: r = p, g = v_, b = t; break;
    case 3: r = p, g = q, b = v_; break;
    case 4: r = t, g = p, b = v_; break;
    case 5: r = v_, g = p, b = q; break;
  }
  return Color3i(round(r * 255), round(g * 255), round(b * 255));
}
References h_, p, round, s_, and v_.
Referenced by Painter::Paint(), Painter::PaintBrightSurprise(), Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), and Painter::VegasVisualizer().
Member Data Documentation
h_
float ColorHSV::h_
Definition at line 98 of file color.h.
Referenced by FromRGB(), operator==(), Print(), Set(), Set(), and ToRGB().
s_
float ColorHSV::s_
Definition at line 98 of file color.h.
Referenced by anonymous_namespace{Painter.cpp}::CalcSaturation(), FromRGB(), operator==(), Painter::Paint(), Print(), Set(), Set(), and ToRGB().
v_
float ColorHSV::v_
Definition at line 98 of file color.h.
Referenced by anonymous_namespace{Painter.cpp}::CalcLuminance(), anonymous_namespace{Painter.cpp}::CalcSaturation(), FromRGB(), operator==(), Painter::Paint(), Painter::PaintBrightSurprise(), Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), Print(), SelectColor(), Set(), Set(), Key::SetOn(), ToRGB(), and Painter::VegasVisualizer().
The documentation for this struct was generated from the following files:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/color.h
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/color.cpp