FastLED: fl::CircularBuffer< T > Class Template Reference
fl::CircularBuffer< T > Class Template Reference
Detailed Description
template<typename T>
class fl::CircularBuffer< T >
Definition at line 12 of file circular_buffer.h.
#include <circular_buffer.h>
Public Member Functions
CircularBuffer (const CircularBuffer &)=delete
CircularBuffer (size_t capacity)
T & back ()
const T & back () const
size_t capacity () const
void clear ()
bool empty () const
T & front ()
const T & front () const
bool full () const
CircularBuffer & operator= (const CircularBuffer &)=delete
T & operator[] (size_t index)
const T & operator[] (size_t index) const
bool pop_back (T *dst=nullptr)
bool pop_front (T *dst=nullptr)
bool push_back (const T &value)
bool push_front (const T &value)
size_t size () const
Private Member Functions
size_t decrement (size_t index) const
size_t increment (size_t index) const
Private Attributes
fl::scoped_array< T > mBuffer
size_t mCapacity
size_t mHead
size_t mTail
Constructor & Destructor Documentation
CircularBuffer() [1/2]
template<typename T > fl::CircularBuffer< T >::CircularBuffer (size_t capacity) inline
Definition at line 14 of file circular_buffer.h.
        : mCapacity(capacity + 1), mHead(0), mTail(0) { // Extra space for distinguishing full/empty
        mBuffer.reset(new T[mCapacity]);
    }
References fl::CircularBuffer< T >::mBuffer, and fl::CircularBuffer< T >::mCapacity.
CircularBuffer() [2/2]
template<typename T > fl::CircularBuffer< T >::CircularBuffer (const CircularBuffer< T > &) delete
Member Function Documentation
back() [1/2]
template<typename T > T & fl::CircularBuffer< T >::back () inline
Definition at line 70 of file circular_buffer.h.
              {
        return mBuffer[(mHead + mCapacity - 1) % mCapacity];
    }
References fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mCapacity, and fl::CircularBuffer< T >::mHead.
back() [2/2]
template<typename T > const T & fl::CircularBuffer< T >::back () const inline
Definition at line 74 of file circular_buffer.h.
{
        return mBuffer[(mHead + mCapacity - 1) % mCapacity];
    }
References fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mCapacity, and fl::CircularBuffer< T >::mHead.
capacity()
template<typename T > size_t fl::CircularBuffer< T >::capacity () const inline
Definition at line 90 of file circular_buffer.h.
{
        return mCapacity - 1;
    }
References fl::CircularBuffer< T >::mCapacity.
Referenced by fl::ByteStreamMemory::write().
clear()
template<typename T > void fl::CircularBuffer< T >::clear () inline
Definition at line 102 of file circular_buffer.h.
                 {
        mHead = mTail = 0;
    }
References fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
Referenced by fl::ByteStreamMemory::clear().
decrement()
template<typename T > size_t fl::CircularBuffer< T >::decrement (size_t index) const inline private
Definition at line 111 of file circular_buffer.h.
{
        return (index + mCapacity - 1) % mCapacity;
    }
References fl::CircularBuffer< T >::mCapacity.
Referenced by fl::CircularBuffer< T >::pop_back(), and fl::CircularBuffer< T >::push_front().
empty()
template<typename T > bool fl::CircularBuffer< T >::empty () const inline
Definition at line 94 of file circular_buffer.h.
                       {
        return mHead == mTail;
    }
References fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
Referenced by fl::CircularBuffer< T >::pop_back(), and fl::CircularBuffer< T >::pop_front().
front() [1/2]
template<typename T > T & fl::CircularBuffer< T >::front () inline
Definition at line 62 of file circular_buffer.h.
               {
        return mBuffer[mTail];
    }
References fl::CircularBuffer< T >::mBuffer, and fl::CircularBuffer< T >::mTail.
front() [2/2]
template<typename T > const T & fl::CircularBuffer< T >::front () const inline
Definition at line 66 of file circular_buffer.h.
{
        return mBuffer[mTail];
    }
References fl::CircularBuffer< T >::mBuffer, and fl::CircularBuffer< T >::mTail.
full()
template<typename T > bool fl::CircularBuffer< T >::full () const inline
Definition at line 98 of file circular_buffer.h.
                      {
        return increment(mHead) == mTail;
    }
References fl::CircularBuffer< T >::increment(), fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
Referenced by fl::CircularBuffer< T >::push_back(), fl::CircularBuffer< T >::push_front(), and fl::ByteStreamMemory::write().
increment()
template<typename T > size_t fl::CircularBuffer< T >::increment (size_t index) const inline private
Definition at line 107 of file circular_buffer.h.
{
        return (index + 1) % mCapacity;
    }
References fl::CircularBuffer< T >::mCapacity.
Referenced by fl::CircularBuffer< T >::full(), fl::CircularBuffer< T >::pop_front(), and fl::CircularBuffer< T >::push_back().
operator=()
template<typename T > CircularBuffer & fl::CircularBuffer< T >::operator= (const CircularBuffer< T > &) delete
operator[]() [1/2]
template<typename T > T & fl::CircularBuffer< T >::operator[] (size_t index) inline
Definition at line 78 of file circular_buffer.h.
{
        return mBuffer[(mTail + index) % mCapacity];
    }
References fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mCapacity, and fl::CircularBuffer< T >::mTail.
operator[]() [2/2]
template<typename T > const T & fl::CircularBuffer< T >::operator[] (size_t index) const inline
Definition at line 82 of file circular_buffer.h.
{
        return mBuffer[(mTail + index) % mCapacity];
    }
References fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mCapacity, and fl::CircularBuffer< T >::mTail.
pop_back()
template<typename T > bool fl::CircularBuffer< T >::pop_back (T * dst = nullptr) inline
Definition at line 51 of file circular_buffer.h.
{
        if (empty()) {
            return false;
        }
        mHead = decrement(mHead);
        if (dst) {
            *dst = mBuffer[mHead];
        }
        return true;
    }
References fl::CircularBuffer< T >::decrement(), fl::CircularBuffer< T >::empty(), fl::CircularBuffer< T >::mBuffer, and fl::CircularBuffer< T >::mHead.
pop_front()
template<typename T > bool fl::CircularBuffer< T >::pop_front (T * dst = nullptr) inline
Definition at line 31 of file circular_buffer.h.
{
        if (empty()) {
            return false;
        }
        if (dst) {
            *dst = mBuffer[mTail];
        }
        mTail = increment(mTail);
        return true;
    }
References fl::CircularBuffer< T >::empty(), fl::CircularBuffer< T >::increment(), fl::CircularBuffer< T >::mBuffer, and fl::CircularBuffer< T >::mTail.
Referenced by fl::ByteStreamMemory::read().
push_back()
template<typename T > bool fl::CircularBuffer< T >::push_back (const T & value) inline
Definition at line 22 of file circular_buffer.h.
{
        if (full()) {
            mTail = increment(mTail); // Overwrite the oldest element
        }
        mBuffer[mHead] = value;
        mHead = increment(mHead);
        return true;
    }
References fl::CircularBuffer< T >::full(), fl::CircularBuffer< T >::increment(), fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
Referenced by fl::ByteStreamMemory::write().
push_front()
template<typename T > bool fl::CircularBuffer< T >::push_front (const T & value) inline
Definition at line 42 of file circular_buffer.h.
{
        if (full()) {
            mHead = decrement(mHead); // Overwrite the oldest element
        }
        mTail = decrement(mTail);
        mBuffer[mTail] = value;
        return true;
    }
References fl::CircularBuffer< T >::decrement(), fl::CircularBuffer< T >::full(), fl::CircularBuffer< T >::mBuffer, fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
size()
template<typename T > size_t fl::CircularBuffer< T >::size () const inline
Definition at line 86 of file circular_buffer.h.
{
        return (mHead + mCapacity - mTail) % mCapacity;
    }
References fl::CircularBuffer< T >::mCapacity, fl::CircularBuffer< T >::mHead, and fl::CircularBuffer< T >::mTail.
Referenced by fl::ByteStreamMemory::available(), fl::ByteStreamMemory::read(), and fl::ByteStreamMemory::write().
Member Data Documentation
mBuffer
template<typename T > fl::scoped_array<T> fl::CircularBuffer< T >::mBuffer private
Definition at line 115 of file circular_buffer.h.
Referenced by fl::CircularBuffer< T >::CircularBuffer(), fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::front(), fl::CircularBuffer< T >::front(), fl::CircularBuffer< T >::operator[](), fl::CircularBuffer< T >::operator[](), fl::CircularBuffer< T >::pop_back(), fl::CircularBuffer< T >::pop_front(), fl::CircularBuffer< T >::push_back(), and fl::CircularBuffer< T >::push_front().
mCapacity
template<typename T > size_t fl::CircularBuffer< T >::mCapacity private
Definition at line 116 of file circular_buffer.h.
Referenced by fl::CircularBuffer< T >::CircularBuffer(), fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::capacity(), fl::CircularBuffer< T >::decrement(), fl::CircularBuffer< T >::increment(), fl::CircularBuffer< T >::operator[](), fl::CircularBuffer< T >::operator[](), and fl::CircularBuffer< T >::size().
mHead
template<typename T > size_t fl::CircularBuffer< T >::mHead private
Definition at line 117 of file circular_buffer.h.
Referenced by fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::back(), fl::CircularBuffer< T >::clear(), fl::CircularBuffer< T >::empty(), fl::CircularBuffer< T >::full(), fl::CircularBuffer< T >::pop_back(), fl::CircularBuffer< T >::push_back(), fl::CircularBuffer< T >::push_front(), and fl::CircularBuffer< T >::size().
mTail
template<typename T > size_t fl::CircularBuffer< T >::mTail private
Definition at line 118 of file circular_buffer.h.
Referenced by fl::CircularBuffer< T >::clear(), fl::CircularBuffer< T >::empty(), fl::CircularBuffer< T >::front(), fl::CircularBuffer< T >::front(), fl::CircularBuffer< T >::full(), fl::CircularBuffer< T >::operator[](), fl::CircularBuffer< T >::operator[](), fl::CircularBuffer< T >::pop_front(), fl::CircularBuffer< T >::push_back(), fl::CircularBuffer< T >::push_front(), and fl::CircularBuffer< T >::size().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/circular_buffer.h