FastLED: Fast Random Number Generators
Fast Random Number Generators
Fast Math Functions
Detailed Description
Fast 8-bit and 16-bit unsigned random number generators.
Significantly faster than Arduino random(), but also somewhat less random. You can add entropy.
Pseudo-random number generation follows the form:
X(n+1) = (2053 * X(n)) + 13849)
uint16_t rand16seed
Seed for the random number generator functions.
LIB8STATIC uint8_t random8 ()
Generate an 8-bit random number.
LIB8STATIC uint16_t random16 ()
Generate a 16-bit random number.
LIB8STATIC uint8_t random8 (uint8_t lim)
Generate an 8-bit random number between 0 and lim.
LIB8STATIC uint8_t random8 (uint8_t min, uint8_t lim)
Generate an 8-bit random number in the given range.
LIB8STATIC uint16_t random16 (uint16_t lim)
Generate an 16-bit random number between 0 and lim.
LIB8STATIC uint16_t random16 (uint16_t min, uint16_t lim)
Generate an 16-bit random number in the given range.
LIB8STATIC void random16_set_seed (uint16_t seed)
Set the 16-bit seed used for the random number generator.
LIB8STATIC uint16_t random16_get_seed ()
Get the current seed value for the random number generator.
LIB8STATIC void random16_add_entropy (uint16_t entropy)
Add entropy into the random number generator.
#define FASTLED_RAND16_2053 ((uint16_t)(2053))
Multiplier value for pseudo-random number generation.
#define FASTLED_RAND16_13849 ((uint16_t)(13849))
Increment value for pseudo-random number generation.
#define APPLY_FASTLED_RAND16_2053(x)
Multiplies a value by the pseudo-random multiplier.
Macro Definition Documentation
APPLY_FASTLED_RAND16_2053
#define APPLY_FASTLED_RAND16_2053 (x)
Value:
(x * FASTLED_RAND16_2053)
Multiplies a value by the pseudo-random multiplier.
Definition at line 36 of file random8.h.
Referenced by random16(), and random8().
FASTLED_RAND16_13849
#define FASTLED_RAND16_13849 ((uint16_t)(13849))
Increment value for pseudo-random number generation.
Definition at line 29 of file random8.h.
Referenced by random16(), and random8().
FASTLED_RAND16_2053
#define FASTLED_RAND16_2053 ((uint16_t)(2053))
Multiplier value for pseudo-random number generation.
Definition at line 27 of file random8.h.
Function Documentation
random16() [1/3]
LIB8STATIC uint16_t random16 ()
Generate a 16-bit random number.
Returns
random 16-bit number, in the range 0-65535
Examples
DemoReel100.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, and SmartMatrix.ino.
Definition at line 54 of file random8.h.
{
    rand16seed = APPLY_FASTLED_RAND16_2053(rand16seed) + FASTLED_RAND16_13849;
    return rand16seed;
}
References APPLY_FASTLED_RAND16_2053, FASTLED_RAND16_13849, and rand16seed.
Referenced by fl::NoisePalette::NoisePalette(), addGlitter(), fl::DemoReel100::addGlitter(), confetti(), fl::DemoReel100::confetti(), loop(), random16(), random16(), and setup().
random16() [2/3]
LIB8STATIC uint16_t random16 (uint16_t lim)
Generate an 16-bit random number between 0 and lim.
Parameters
lim the upper bound for the result, exclusive
Definition at line 78 of file random8.h.
{
    uint16_t r = random16();
    uint32_t p = (uint32_t)lim * (uint32_t)r;
    r = p >> 16;
    return r;
}
References p, and random16().
random16() [3/3]
LIB8STATIC uint16_t random16 (uint16_t min, uint16_t lim)
Generate an 16-bit random number in the given range.
Parameters
min the lower bound for the random number, inclusive
lim the upper bound for the random number, exclusive
Definition at line 88 of file random8.h.
{
    uint16_t delta = lim - min;
    uint16_t r = random16(delta) + min;
    return r;
}
References random16().
random16_add_entropy()
LIB8STATIC void random16_add_entropy (uint16_t entropy)
Add entropy into the random number generator.
Examples
Fire2012WithPalette.ino, and NoisePlayground.ino.
Definition at line 101 of file random8.h.
{
    rand16seed += entropy;
}
References rand16seed.
Referenced by loop(), and setup().
random16_get_seed()
LIB8STATIC uint16_t random16_get_seed ()
Get the current seed value for the random number generator.
Definition at line 98 of file random8.h.
{ return rand16seed; }
References rand16seed.
random16_set_seed()
LIB8STATIC void random16_set_seed (uint16_t seed)
Set the 16-bit seed used for the random number generator.
Examples
NoisePlayground.ino.
Definition at line 95 of file random8.h.
{ rand16seed = seed; }
References rand16seed.
Referenced by setup().
random8() [1/3]
LIB8STATIC uint8_t random8 ()
Generate an 8-bit random number.
Returns
random 8-bit number, in the range 0-255
Examples
ColorPalette.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, and NoisePlusPalette.ino.
Definition at line 44 of file random8.h.
{
    rand16seed = APPLY_FASTLED_RAND16_2053(rand16seed) + FASTLED_RAND16_13849;
    // return the sum of the high and low bytes, for better
    //  mixing and non-sequential correlation
    return (uint8_t)(((uint8_t)(rand16seed & 0xFF)) +
                     ((uint8_t)(rand16seed >> 8)));
}
References APPLY_FASTLED_RAND16_2053, FASTLED_RAND16_13849, and rand16seed.
Referenced by addGlitter(), fl::DemoReel100::addGlitter(), fl::NoisePalette::changeToRandomPalette(), confetti(), fl::DemoReel100::confetti(), fl::Fire2012::draw(), Fire2012(), Fire2012WithPalette(), random8(), random8(), fl::NoisePalette::SetupRandomPalette(), SetupRandomPalette(), and SetupTotallyRandomPalette().
random8() [2/3]
LIB8STATIC uint8_t random8 (uint8_t lim)
Generate an 8-bit random number between 0 and lim.
Parameters
lim the upper bound for the result, exclusive
Definition at line 61 of file random8.h.
{
    uint8_t r = random8();
    r = (r * lim) >> 8;
    return r;
}
References random8().
random8() [3/3]
LIB8STATIC uint8_t random8 (uint8_t min, uint8_t lim)
Generate an 8-bit random number in the given range.
Parameters
min the lower bound for the random number, inclusive
lim the upper bound for the random number, exclusive
Definition at line 70 of file random8.h.
{
    uint8_t delta = lim - min;
    uint8_t r = random8(delta) + min;
    return r;
}
References random8().
Variable Documentation
rand16seed
uint16_t rand16seed extern
Seed for the random number generator functions.
Definition at line 17 of file lib8tion.cpp.
Referenced by random16(), random16_add_entropy(), random16_get_seed(), random16_set_seed(), and random8().