FastLED: fl::Video Class Reference
fl::Video Class Reference
Detailed Description
Definition at line 30 of file video.h.
#include <video.h>
Public Member Functions
Video ()
Video (const Video &)
Video (size_t pixelsPerFrame, float fps=30.0f, size_t frameHistoryCount=DefaultFrameHistoryCount())
~Video ()
bool begin (fl::FileHandlePtr h)
bool beginStream (fl::ByteStreamPtr s)
void draw (DrawContext context) override
bool draw (uint32_t now, CRGB *leds)
bool draw (uint32_t now, Frame *frame)
int32_t durationMicros () const
void end ()
Str error () const
bool finished ()
Str fxName () const override
operator bool () const
Video & operator= (const Video &)
void pause (uint32_t now) override
size_t pixelsPerFrame () const
void resume (uint32_t now) override
bool rewind ()
void setError (const Str &error)
void setFade (uint32_t fadeInTime, uint32_t fadeOutTime)
void setTimeScale (float timeScale)
float timeScale () const
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Static Public Member Functions
static size_t DefaultFrameHistoryCount ()
Private Attributes
Str mError
bool mFinished = false
VideoImplPtr mImpl
Str mName
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
Video() [1/3]
fl::Video::Video ()
Definition at line 28 of file video.cpp.
            : Fx1d(0) {
}
Video() [2/3]
fl::Video::Video (size_t pixelsPerFrame, float fps = 30.0f, size_t frameHistoryCount = DefaultFrameHistoryCount())
Definition at line 31 of file video.cpp.
                                                                        : Fx1d(pixelsPerFrame) {
    mImpl = VideoImplPtr::New(pixelsPerFrame, fps, frame_history_count);
}
References mImpl, and pixelsPerFrame().
~Video()
fl::Video::~Video () default
Video() [3/3]
fl::Video::Video (const Video &) default
Member Function Documentation
begin()
bool fl::Video::begin (fl::FileHandlePtr h)
beginStream()
bool fl::Video::beginStream (fl::ByteStreamPtr s)
DefaultFrameHistoryCount()
static size_t fl::Video::DefaultFrameHistoryCount () inline static
Definition at line 32 of file video.h.
{
        #ifdef __AVR__
        return 1;
        #else
        return 2;  // Allow interpolation by default.
        #endif
    }
draw() [1/3]
void fl::Video::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 98 of file video.cpp.
{
    if (!mImpl) {
        FASTLED_WARN_IF(!mError.empty(), mError.c_str());
        return;
    }
    mImpl->draw(context.now, context.leds);
}
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::empty(), FASTLED_WARN_IF, fl::_DrawContext::leds, mError, mImpl, and fl::_DrawContext::now.
Referenced by loop().
draw() [2/3]
bool fl::Video::draw (uint32_t now, CRGB * leds)
Definition at line 85 of file video.cpp.
{
    if (!mImpl) {
        FASTLED_WARN_IF(!mError.empty(), mError.c_str());
        return false;
    }
    bool ok = mImpl->draw(now, leds);
    if (!ok) {
        // Interpret not being able to draw as a finished signal.
        mFinished = true;
    }
    return ok;
}
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::empty(), FASTLED_WARN_IF, leds, mError, mFinished, and mImpl.
draw() [3/3]
bool fl::Video::draw (uint32_t now, Frame * frame)
Definition at line 117 of file video.cpp.
{
    if (!mImpl) {
        return false;
    }
    return mImpl->draw(now, frame);
}
References mImpl.
durationMicros()
int32_t fl::Video::durationMicros () const
Definition at line 106 of file video.cpp.
{
    if (!mImpl) {
        return -1;
    }
    return mImpl->durationMicros();
}
References mImpl.
end()
void fl::Video::end ()
Definition at line 124 of file video.cpp.
                {
    if (mImpl) {
        mImpl->end();
    }
}
References mImpl.
error()
Str fl::Video::error () const
Definition at line 144 of file video.cpp.
                       {
    return mError;
}
References mError.
Referenced by setError().
finished()
bool fl::Video::finished ()
Definition at line 155 of file video.cpp.
                     {
    if (!mImpl) {
        return true;
    }
    return mFinished;
}
References mFinished, and mImpl.
fxName()
Str fl::Video::fxName () const override virtual
Implements fl::Fx.
Definition at line 113 of file video.cpp.
{
    return "Video";
}
operator bool()
fl::Video::operator bool () const inline
Definition at line 73 of file video.h.
{ return mImpl.get(); }
References mImpl.
operator=()
Video & fl::Video::operator= (const Video &) default
pause()
void fl::Video::pause (uint32_t now) override virtual
Reimplemented from fl::Fx.
Definition at line 39 of file video.cpp.
{
    mImpl->pause(now);
}
References mImpl.
pixelsPerFrame()
size_t fl::Video::pixelsPerFrame () const
Definition at line 148 of file video.cpp.
{
    if (!mImpl) {
        return 0;
    }
    return mImpl->pixelsPerFrame();
}
References mImpl.
Referenced by Video().
resume()
void fl::Video::resume (uint32_t now) override virtual
Reimplemented from fl::Fx.
Definition at line 43 of file video.cpp.
{
    mImpl->resume(now);
}
References mImpl.
rewind()
bool fl::Video::rewind ()
Definition at line 162 of file video.cpp.
                   {
    if (!mImpl) {
        return false;
    }
    return mImpl->rewind();
}
References mImpl.
setError()
void fl::Video::setError (const Str & error) inline
Definition at line 65 of file video.h.
{ mError = error; }
References error(), and mError.
setFade()
void fl::Video::setFade (uint32_t fadeInTime, uint32_t fadeOutTime)
Definition at line 35 of file video.cpp.
{
    mImpl->setFade(fadeInTime, fadeOutTime);
}
References mImpl.
setTimeScale()
void fl::Video::setTimeScale (float timeScale)
Definition at line 130 of file video.cpp.
{
    if (!mImpl) {
        return;
    }
    mImpl->setTimeScale(timeScale);
}
References mImpl, and timeScale().
Referenced by loop().
timeScale()
float fl::Video::timeScale () const
Definition at line 137 of file video.cpp.
{
    if (!mImpl) {
        return 1.0f;
    }
    return mImpl->timeScale();
}
References mImpl.
Referenced by setTimeScale().
Member Data Documentation
mError
Str fl::Video::mError private
Definition at line 77 of file video.h.
Referenced by draw(), draw(), error(), and setError().
mFinished
bool fl::Video::mFinished = false private
Definition at line 75 of file video.h.
Referenced by draw(), and finished().
mImpl
VideoImplPtr fl::Video::mImpl private
Definition at line 76 of file video.h.
Referenced by Video(), draw(), draw(), draw(), durationMicros(), end(), finished(), operator bool(), pause(), pixelsPerFrame(), resume(), rewind(), setFade(), setTimeScale(), and timeScale().
mName
Str fl::Video::mName private
Definition at line 78 of file video.h.
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/video.h
/home/runner/work/FastLED/FastLED/src/fx/video.cpp