FastLED: Basic Math Operations
Basic Math Operations
Fast Math Functions
Detailed Description
Fast, efficient 8-bit math functions specifically designed for high-performance LED programming.
Because of the AVR (Arduino) and ARM assembly language implementations provided, using these functions often results in smaller and faster code than the equivalent program using plain "C" arithmetic and logic.
LIB8STATIC_ALWAYS_INLINE uint8_t qadd8 (uint8_t i, uint8_t j)
Add one byte to another, saturating at 0xFF.
LIB8STATIC_ALWAYS_INLINE int8_t qadd7 (int8_t i, int8_t j)
Add one byte to another, saturating at 0x7F and -0x80.
LIB8STATIC_ALWAYS_INLINE uint8_t qsub8 (uint8_t i, uint8_t j)
Subtract one byte from another, saturating at 0x00.
LIB8STATIC_ALWAYS_INLINE uint8_t add8 (uint8_t i, uint8_t j)
Add one byte to another, with 8-bit result.
LIB8STATIC_ALWAYS_INLINE uint16_t add8to16 (uint8_t i, uint16_t j)
Add one byte to two bytes, with 16-bit result.
LIB8STATIC_ALWAYS_INLINE uint8_t sub8 (uint8_t i, uint8_t j)
Subtract one byte from another, 8-bit result.
LIB8STATIC_ALWAYS_INLINE uint8_t avg8 (uint8_t i, uint8_t j)
Calculate an integer average of two unsigned 8-bit integer values (uint8_t), rounded down.
LIB8STATIC_ALWAYS_INLINE uint16_t avg16 (uint16_t i, uint16_t j)
Calculate an integer average of two unsigned 16-bit integer values (uint16_t), rounded down.
LIB8STATIC_ALWAYS_INLINE uint8_t avg8r (uint8_t i, uint8_t j)
Calculate an integer average of two unsigned 8-bit integer values (uint8_t), rounded up.
LIB8STATIC_ALWAYS_INLINE uint16_t avg16r (uint16_t i, uint16_t j)
Calculate an integer average of two unsigned 16-bit integer values (uint16_t), rounded up.
LIB8STATIC_ALWAYS_INLINE int8_t avg7 (int8_t i, int8_t j)
Calculate an integer average of two signed 7-bit integers (int8_t).
LIB8STATIC_ALWAYS_INLINE int16_t avg15 (int16_t i, int16_t j)
Calculate an integer average of two signed 15-bit integers (int16_t).
LIB8STATIC_ALWAYS_INLINE uint8_t mod8 (uint8_t a, uint8_t m)
Calculate the remainder of one unsigned 8-bit value divided by anoter, aka A % M.
LIB8STATIC uint8_t addmod8 (uint8_t a, uint8_t b, uint8_t m)
Add two numbers, and calculate the modulo of the sum and a third number, M.
LIB8STATIC uint8_t submod8 (uint8_t a, uint8_t b, uint8_t m)
Subtract two numbers, and calculate the modulo of the difference and a third number, M.
LIB8STATIC_ALWAYS_INLINE uint8_t mul8 (uint8_t i, uint8_t j)
8x8 bit multiplication, with 8-bit result.
LIB8STATIC_ALWAYS_INLINE uint8_t qmul8 (uint8_t i, uint8_t j)
8x8 bit multiplication with 8-bit result, saturating at 0xFF.
LIB8STATIC_ALWAYS_INLINE int8_t abs8 (int8_t i)
Take the absolute value of a signed 8-bit uint8_t.
LIB8STATIC uint8_t sqrt16 (uint16_t x)
Square root for 16-bit integers.
LIB8STATIC_ALWAYS_INLINE uint8_t sqrt8 (uint8_t x)
LIB8STATIC uint8_t blend8 (uint8_t a, uint8_t b, uint8_t amountOfB)
Blend a variable proportion (0-255) of one byte to another.
Function Documentation
abs8()
LIB8STATIC_ALWAYS_INLINE int8_t abs8 (int8_t i)
Take the absolute value of a signed 8-bit uint8_t.
Definition at line 500 of file math8.h.
{
#if ABS8_C == 1
    if (i < 0)
        i = -i;
    return i;
#elif ABS8_AVRASM == 1
    asm volatile(
        /* First, check the high bit, and prepare to skip if it's clear */
        "sbrc %0, 7 \n"
        /* Negate the value */
        "neg %0     \n"
        : "+r"(i)
        : "r"(i));
    return i;
#else
#error "No implementation for abs8 available."
#endif
}
add8()
LIB8STATIC_ALWAYS_INLINE uint8_t add8 (uint8_t i, uint8_t j)
Add one byte to another, with 8-bit result.
Note
This does not saturate and may overflow!
Parameters
i first byte to add
j second byte to add
Returns
the sum of i + j, 8-bit
Definition at line 135 of file math8.h.
{
#if ADD8_C == 1
    int t = i + j;
    return t;
#elif ADD8_AVRASM == 1
    // Add j to i, period.
    asm volatile("add %0, %1" : "+r"(i) : "r"(j));
    return i;
#else
#error "No implementation for add8 available."
#endif
}
add8to16()
LIB8STATIC_ALWAYS_INLINE uint16_t add8to16 (uint8_t i, uint16_t j)
Add one byte to two bytes, with 16-bit result.
Note
This does not saturate and may overflow!
Parameters
i first value to add, 8-bit
j second value to add, 16-bit
Returns
the sum of i + j, 16-bit
Definition at line 153 of file math8.h.
{
#if ADD8_C == 1
    uint16_t t = i + j;
    return t;
#elif ADD8_AVRASM == 1
    // Add i(one byte) to j(two bytes)
    asm volatile("add %A[j], %[i]              \n\t"
                 "adc %B[j], __zero_reg__      \n\t"
                 : [j] "+r"(j)
                 : [i] "r"(i));
    return i;
#else
#error "No implementation for add8to16 available."
#endif
}
addmod8()
LIB8STATIC uint8_t addmod8 (uint8_t a, uint8_t b, uint8_t m)
Add two numbers, and calculate the modulo of the sum and a third number, M.
In other words, it returns (A+B) % M. It is designed as a compact mechanism for incrementing a "mode" switch and wrapping around back to "mode 0" when the switch goes past the end of the available range. e.g. if you have seven modes, this switches to the next one and wraps around if needed:
mode = addmod8(mode, 1, 7);
Parameters
a dividend byte
b value to add to the dividend
m divisor byte
Returns
remainder of (a + b) / m
See also
mod8() for notes on performance.
Examples
TwinkleFox.ino.
Definition at line 392 of file math8.h.
{
#if defined(__AVR__)
    asm volatile("       add %[a],%[b]    \n\t"
                 "L_%=:  sub %[a],%[m]    \n\t"
                 "       brcc L_%=        \n\t"
                 "       add %[a],%[m]    \n\t"
                 : [a] "+r"(a)
                 : [b] "r"(b), [m] "r"(m));
#else
    a += b;
    while (a >= m)
        a -= m;
#endif
    return a;
}
Referenced by chooseNextColorPalette(), and fl::TwinkleFox::chooseNextColorPalette().
avg15()
LIB8STATIC_ALWAYS_INLINE int16_t avg15 (int16_t i, int16_t j)
Calculate an integer average of two signed 15-bit integers (int16_t).
If the first argument is even, result is rounded down. If the first argument is odd, result is rounded up.
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded
Definition at line 328 of file math8.h.
{
#if AVG15_C == 1
    return (i >> 1) + (j >> 1) + (i & 0x1);
#elif AVG15_AVRASM == 1
    asm volatile(
        /* first divide j by 2, throwing away lowest bit */
        "asr %B[j]          \n\t"
        "ror %A[j]          \n\t"
        /* now divide i by 2, with lowest bit going into C */
        "asr %B[i]          \n\t"
        "ror %A[i]          \n\t"
        /* add j + C to i */
        "adc %A[i], %A[j]   \n\t"
        "adc %B[i], %B[j]   \n\t"
        : [i] "+r"(i)
        : [j] "r"(j));
    return i;
#else
#error "No implementation for avg15 available."
#endif
}
avg16()
LIB8STATIC_ALWAYS_INLINE uint16_t avg16 (uint16_t i, uint16_t j)
Calculate an integer average of two unsigned 16-bit integer values (uint16_t), rounded down.
Fractional results are rounded down, e.g. avg16(20,41) = 30
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded down
Definition at line 216 of file math8.h.
{
#if AVG16_C == 1
    return (uint32_t)((uint32_t)(i) + (uint32_t)(j)) >> 1;
#elif AVG16_AVRASM == 1
    asm volatile(
        /* First, add jLo (heh) to iLo, 9th bit overflows into C flag */
        "add %A[i], %A[j]    \n\t"
        /* Now, add C + jHi to iHi, 17th bit overflows into C flag */
        "adc %B[i], %B[j]    \n\t"
        /* Divide iHi by two, moving C flag into high 16th bit, old 9th bit now
           in
           C */
        "ror %B[i]        \n\t"
        /* Divide iLo by two, moving C flag into high 8th bit */
        "ror %A[i]        \n\t"
        : [i] "+r"(i)
        : [j] "r"(j));
    return i;
#else
#error "No implementation for avg16 available."
#endif
}
avg16r()
LIB8STATIC_ALWAYS_INLINE uint16_t avg16r (uint16_t i, uint16_t j)
Calculate an integer average of two unsigned 16-bit integer values (uint16_t), rounded up.
Fractional results are rounded up, e.g. avg16r(20,41) = 31
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded up
Definition at line 271 of file math8.h.
{
#if AVG16R_C == 1
    return (uint32_t)((uint32_t)(i) + (uint32_t)(j) + 1) >> 1;
#elif AVG16R_AVRASM == 1
    asm volatile(
        /* First, add jLo (heh) to iLo, 9th bit overflows into C flag */
        "add %A[i], %A[j]    \n\t"
        /* Now, add C + jHi to iHi, 17th bit overflows into C flag */
        "adc %B[i], %B[j]    \n\t"
        /* Divide iHi by two, moving C flag into high 16th bit, old 9th bit now
           in
           C */
        "ror %B[i]        \n\t"
        /* Divide iLo by two, moving C flag into high 8th bit, old 1st bit now
           in
           C */
        "ror %A[i]        \n\t"
        /* Add C flag */
        "adc %A[i], __zero_reg__\n\t"
        "adc %B[i], __zero_reg__\n\t"
        : [i] "+r"(i)
        : [j] "r"(j));
    return i;
#else
#error "No implementation for avg16r available."
#endif
}
avg7()
LIB8STATIC_ALWAYS_INLINE int8_t avg7 (int8_t i, int8_t j)
Calculate an integer average of two signed 7-bit integers (int8_t).
If the first argument is even, result is rounded down. If the first argument is odd, result is rounded up.
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded
Definition at line 306 of file math8.h.
{
#if AVG7_C == 1
    return (i >> 1) + (j >> 1) + (i & 0x1);
#elif AVG7_AVRASM == 1
    asm volatile("asr %1        \n\t"
                 "asr %0        \n\t"
                 "adc %0, %1    \n\t"
                 : "+r"(i)
                 : "r"(j));
    return i;
#else
#error "No implementation for avg7 available."
#endif
}
Referenced by grad8(), grad8(), and grad8().
avg8()
LIB8STATIC_ALWAYS_INLINE uint8_t avg8 (uint8_t i, uint8_t j)
Calculate an integer average of two unsigned 8-bit integer values (uint8_t), rounded down.
Fractional results are rounded down, e.g. avg8(20,41) = 30
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded down
Definition at line 193 of file math8.h.
{
#if AVG8_C == 1
    return (i + j) >> 1;
#elif AVG8_AVRASM == 1
    asm volatile(
        /* First, add j to i, 9th bit overflows into C flag */
        "add %0, %1    \n\t"
        /* Divide by two, moving C flag into high 8th bit */
        "ror %0        \n\t"
        : "+r"(i)
        : "r"(j));
    return i;
#else
#error "No implementation for avg8 available."
#endif
}
avg8r()
LIB8STATIC_ALWAYS_INLINE uint8_t avg8r (uint8_t i, uint8_t j)
Calculate an integer average of two unsigned 8-bit integer values (uint8_t), rounded up.
Fractional results are rounded up, e.g. avg8r(20,41) = 31
Parameters
i first value to average
j second value to average
Returns
mean average of i and j, rounded up
Definition at line 245 of file math8.h.
{
#if AVG8R_C == 1
    return (i + j + 1) >> 1;
#elif AVG8R_AVRASM == 1
    asm volatile(
        /* First, add j to i, 9th bit overflows into C flag */
        "add %0, %1          \n\t"
        /* Divide by two, moving C flag into high 8th bit, old 1st bit now in C
         */
        "ror %0              \n\t"
        /* Add C flag */
        "adc %0, __zero_reg__\n\t"
        : "+r"(i)
        : "r"(j));
    return i;
#else
#error "No implementation for avg8r available."
#endif
}
blend8()
LIB8STATIC uint8_t blend8 (uint8_t a, uint8_t b, uint8_t amountOfB)
Blend a variable proportion (0-255) of one byte to another.
Parameters
a the starting byte value
b the byte value to blend toward
amountOfB the proportion (0-255) of b to blend
Returns
a byte value between a and b, inclusive
Definition at line 667 of file math8.h.
{
    // This version loses precision in the integer math
    // and can actually return results outside of the range
    // from a to b.  Its use is not recommended.
    uint8_t result;
    uint8_t amountOfA = 255 - amountOfB;
    result = scale8_LEAVING_R1_DIRTY(a, amountOfA) +
             scale8_LEAVING_R1_DIRTY(b, amountOfB);
    cleanup_R1();
    return result;
}
References cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
Referenced by CRGB::blend(), and nblend().
mod8()
LIB8STATIC_ALWAYS_INLINE uint8_t mod8 (uint8_t a, uint8_t m)
Calculate the remainder of one unsigned 8-bit value divided by anoter, aka A % M.
Implemented by repeated subtraction, which is very compact, and very fast if A is "probably" less than M. If A is a large multiple of M, the loop has to execute multiple times. However, even in that case, the loop is only two instructions long on AVR, i.e., quick.
Parameters
a dividend byte
m divisor byte
Returns
remainder of a / m (i.e. a % m)
Definition at line 361 of file math8.h.
{
#if defined(__AVR__)
    asm volatile("L_%=:  sub %[a],%[m]    \n\t"
                 "       brcc L_%=        \n\t"
                 "       add %[a],%[m]    \n\t"
                 : [a] "+r"(a)
                 : [m] "r"(m));
#else
    while (a >= m)
        a -= m;
#endif
    return a;
}
mul8()
LIB8STATIC_ALWAYS_INLINE uint8_t mul8 (uint8_t i, uint8_t j)
8x8 bit multiplication, with 8-bit result.
Parameters
i first byte to multiply
j second byte to multiply
Returns
the product of i * j
Note
This does not saturate and may overflow!
Definition at line 446 of file math8.h.
{
#if MUL8_C == 1
    return ((int)i * (int)(j)) & 0xFF;
#elif MUL8_AVRASM == 1
    asm volatile(
        /* Multiply 8-bit i * 8-bit j, giving 16-bit r1,r0 */
        "mul %0, %1          \n\t"
        /* Extract the LOW 8-bits (r0) */
        "mov %0, r0          \n\t"
        /* Restore r1 to "0"; it's expected to always be that */
        "clr __zero_reg__    \n\t"
        : "+r"(i)
        : "r"(j)
        : "r0", "r1");
    return i;
#else
#error "No implementation for mul8 available."
#endif
}
qadd7()
LIB8STATIC_ALWAYS_INLINE int8_t qadd7 (int8_t i, int8_t j)
Add one byte to another, saturating at 0x7F and -0x80.
Parameters
i first byte to add
j second byte to add
Returns
the sum of i + j, capped at 0x7F and -0x80
Definition at line 64 of file math8.h.
{
#if QADD7_C == 1
    int16_t t = i + j;
    if (t > 127)
        t = 127;
    else if (t < -128)
        t = -128;
    return t;
#elif QADD7_AVRASM == 1
    asm volatile(
        /* First, add j to i, conditioning the V and C flags */
        "add %0, %1    \n\t"
        /* Now test the V flag.
        If V is clear, we branch to end.
        If V is set, we go ahead and load 0x7F into i.
        */
        "brvc L_%=     \n\t"
        "ldi %0, 0x7F  \n\t"
        /* When both numbers are negative, C is set.
        Adding it to make result negative. */
        "adc %0, __zero_reg__\n\t"
        "L_%=: "
        : "+d"(i) // r16-r31, restricted by ldi
        : "r"(j));
    return i;
#elif QADD7_ARM_DSP_ASM == 1
    asm volatile("qadd8 %0, %0, %1" : "+r"(i) : "r"(j));
    return i;
#else
#error "No implementation for qadd7 available."
#endif
}
qadd8()
LIB8STATIC_ALWAYS_INLINE uint8_t qadd8 (uint8_t i, uint8_t j)
Add one byte to another, saturating at 0xFF.
Parameters
i first byte to add
j second byte to add
Returns
the sum of i + j, capped at 0xFF
Examples
Fire2012.ino, Fire2012WithPalette.ino, NoisePlusPalette.ino, and Pacifica.ino.
Definition at line 31 of file math8.h.
{
#if QADD8_C == 1
    unsigned int t = i + j;
    if (t > 255)
        t = 255;
    return t;
#elif QADD8_AVRASM == 1
    asm volatile(
        /* First, add j to i, conditioning the C flag */
        "add %0, %1    \n\t"
        /* Now test the C flag.
        If C is clear, we branch around a load of 0xFF into i.
        If C is set, we go ahead and load 0xFF into i.
        */
        "brcc L_%=     \n\t"
        "ldi %0, 0xFF  \n\t"
        "L_%=: "
        : "+d"(i) // r16-r31, restricted by ldi
        : "r"(j));
    return i;
#elif QADD8_ARM_DSP_ASM == 1
    asm volatile("uqadd8 %0, %0, %1" : "+r"(i) : "r"(j));
    return i;
#else
#error "No implementation for qadd8 available."
#endif
}
Referenced by CRGB::addToRGB(), PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::dither(), fl::Fire2012::draw(), fill_raw_2dnoise16into8(), fill_raw_noise8(), fillnoise8(), fl::NoisePalette::fillnoise8(), Fire2012(), Fire2012WithPalette(), inoise8(), inoise8(), inoise8(), operator+(), CRGB::operator+=(), fl::Pacifica::pacifica_add_whitecaps(), pacifica_add_whitecaps(), rgb2hsv_approximate(), and wu_water().
qmul8()
LIB8STATIC_ALWAYS_INLINE uint8_t qmul8 (uint8_t i, uint8_t j)
8x8 bit multiplication with 8-bit result, saturating at 0xFF.
Parameters
i first byte to multiply
j second byte to multiply
Returns
the product of i * j, capping at 0xFF
Definition at line 470 of file math8.h.
{
#if QMUL8_C == 1
    unsigned p = (unsigned)i * (unsigned)j;
    if (p > 255)
        p = 255;
    return p;
#elif QMUL8_AVRASM == 1
    asm volatile(
        /* Multiply 8-bit i * 8-bit j, giving 16-bit r1,r0 */
        "  mul %0, %1          \n\t"
        /* Extract the LOW 8-bits (r0) */
        "  mov %0, r0          \n\t"
        /* If high byte of result is zero, all is well. */
        "  tst r1              \n\t"
        "  breq Lnospill_%=    \n\t"
        /* If high byte of result > 0, saturate to 0xFF */
        "  ldi %0, 0xFF         \n\t"
        "Lnospill_%=:          \n\t"
        /* Restore r1 to "0"; it's expected to always be that */
        "  clr __zero_reg__    \n\t"
        : "+d"(i) // r16-r31, restricted by ldi
        : "r"(j)
        : "r0", "r1");
    return i;
#else
#error "No implementation for qmul8 available."
#endif
}
References p.
Referenced by operator*(), and CRGB::operator*=().
qsub8()
LIB8STATIC_ALWAYS_INLINE uint8_t qsub8 (uint8_t i, uint8_t j)
Subtract one byte from another, saturating at 0x00.
Parameters
i byte to subtract from
j byte to subtract
Returns
i - j with a floor of 0
Examples
Fire2012.ino, Fire2012WithPalette.ino, NoisePlusPalette.ino, and TwinkleFox.ino.
Definition at line 103 of file math8.h.
{
#if QSUB8_C == 1
    int t = i - j;
    if (t < 0)
        t = 0;
    return t;
#elif QSUB8_AVRASM == 1
    asm volatile(
        /* First, subtract j from i, conditioning the C flag */
        "sub %0, %1    \n\t"
        /* Now test the C flag.
        If C is clear, we branch around a load of 0x00 into i.
        If C is set, we go ahead and load 0x00 into i.
        */
        "brcc L_%=     \n\t"
        "ldi %0, 0x00  \n\t"
        "L_%=: "
        : "+d"(i) // r16-r31, restricted by ldi
        : "r"(j));
    return i;
#else
#error "No implementation for qsub8 available."
#endif
}
Referenced by coolLikeIncandescent(), fl::TwinkleFox::coolLikeIncandescentFunction(), fl::Fire2012::draw(), fillnoise8(), fl::NoisePalette::fillnoise8(), Fire2012(), Fire2012WithPalette(), operator-(), CRGB::operator-=(), rgb2hsv_approximate(), and CRGB::subtractFromRGB().
sqrt16()
LIB8STATIC uint8_t sqrt16 (uint16_t x)
Square root for 16-bit integers.
About three times faster and five times smaller than Arduino's general sqrt on AVR.
Definition at line 524 of file math8.h.
{
    if (x <= 1) {
        return x;
    }
    uint8_t low = 1; // lower bound
    uint8_t hi, mid;
    if (x > 7904) {
        hi = 255;
    } else {
        hi = (x >> 5) + 8; // initial estimate for upper bound
    }
    do {
        mid = (low + hi) >> 1;
        if ((uint16_t)(mid * mid) > x) {
            hi = mid - 1;
        } else {
            if (mid == 255) {
                return 255;
            }
            low = mid + 1;
        }
    } while (hi >= low);
    return low - 1;
}
References x.
Referenced by rgb2hsv_approximate(), and sqrt8().
sqrt8()
LIB8STATIC_ALWAYS_INLINE uint8_t sqrt8 (uint8_t x)
Definition at line 553 of file math8.h.
{
    return sqrt16(map8_to_16(x));
}
References map8_to_16(), sqrt16(), and x.
sub8()
LIB8STATIC_ALWAYS_INLINE uint8_t sub8 (uint8_t i, uint8_t j)
Subtract one byte from another, 8-bit result.
Note
This does not saturate and may overflow!
Parameters
i byte to subtract from
j byte to subtract
Returns
i - j
Definition at line 174 of file math8.h.
{
#if SUB8_C == 1
    int t = i - j;
    return t;
#elif SUB8_AVRASM == 1
    // Subtract j from i, period.
    asm volatile("sub %0, %1" : "+r"(i) : "r"(j));
    return i;
#else
#error "No implementation for sub8 available."
#endif
}
submod8()
LIB8STATIC uint8_t submod8 (uint8_t a, uint8_t b, uint8_t m)
Subtract two numbers, and calculate the modulo of the difference and a third number, M.
In other words, it returns (A-B) % M. It is designed as a compact mechanism for decrementing a "mode" switch and wrapping around back to "mode 0" when the switch goes past the start of the available range. e.g. if you have seven modes, this switches to the previous one and wraps around if needed:
mode = submod8(mode, 1, 7);
Parameters
a dividend byte
b value to subtract from the dividend
m divisor byte
Returns
remainder of (a - b) / m
See also
mod8() for notes on performance.
Definition at line 425 of file math8.h.
{
#if defined(__AVR__)
    asm volatile("       sub %[a],%[b]    \n\t"
                 "L_%=:  sub %[a],%[m]    \n\t"
                 "       brcc L_%=        \n\t"
                 "       add %[a],%[m]    \n\t"
                 : [a] "+r"(a)
                 : [b] "r"(b), [m] "r"(m));
#else
    a -= b;
    while (a >= m)
        a -= m;
#endif
    return a;
}