FastLED: fl::anonymous_namespace{allocator.cpp} Namespace Reference
fl::anonymous_namespace{allocator.cpp} Namespace Reference
Functions
void * DefaultAlloc (size_t size)
void DefaultFree (void *ptr)
Variables
void *(* Alloc)(size_t) = DefaultAlloc
void(* Free)(void *) = DefaultFree
Function Documentation
DefaultAlloc()
void * fl::anonymous_namespace{allocator.cpp}::DefaultAlloc (size_t size)
Definition at line 29 of file allocator.cpp.
{ return malloc(size); }
References DefaultAlloc().
Referenced by DefaultAlloc().
DefaultFree()
void fl::anonymous_namespace{allocator.cpp}::DefaultFree (void * ptr)
Definition at line 30 of file allocator.cpp.
{ free(ptr); }
References DefaultFree().
Referenced by DefaultFree().
Variable Documentation
Alloc
void *(* fl::anonymous_namespace{allocator.cpp}::Alloc) (size_t) (size_t) = DefaultAlloc
Definition at line 33 of file allocator.cpp.
Free
void(* fl::anonymous_namespace{allocator.cpp}::Free) (void *) (void *) = DefaultFree
Definition at line 34 of file allocator.cpp.