FastLED: /home/runner/work/FastLED/FastLED/src/hsv2rgb.cpp File Reference
hsv2rgb.cpp File Reference
Detailed Description
Functions to convert from the HSV colorspace to the RGB colorspace.
Definition in file hsv2rgb.cpp.
#include <stdint.h>
#include "FastLED.h"
Macros
#define APPLY_DIMMING(X)
Apply dimming compensation to values.
#define FASTLED_INTERNAL
Disables pragma messages and warnings.
#define FIXFRAC8(N, D)
Convert a fractional input into a constant.
#define FORCE_REFERENCE(var)
Force a variable reference to avoid compiler over-optimization.
#define HSV_SECTION_3 (0x40)
Divide the color wheel into four sections, 64 elements each.
#define HSV_SECTION_6 (0x20)
Divide the color wheel into eight sections, 32 elements each.
Functions
void hsv2rgb_rainbow (const CHSV &hsv, CRGB &rgb)
void hsv2rgb_rainbow (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
void hsv2rgb_raw (const struct CHSV &hsv, struct CRGB &rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
void hsv2rgb_raw (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
void hsv2rgb_raw_avr (const struct CHSV &hsv, struct CRGB &rgb)
HSV to RGB implementation in raw C, for the AVR platform only.
void hsv2rgb_raw_C (const struct CHSV &hsv, struct CRGB &rgb)
HSV to RGB implementation in raw C, platform independent.
void hsv2rgb_spectrum (const struct CHSV &hsv, CRGB &rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
void hsv2rgb_spectrum (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
CHSV rgb2hsv_approximate (const CRGB &rgb)
Recover approximate HSV values from RGB.
Macro Definition Documentation
APPLY_DIMMING
#define APPLY_DIMMING (X)
Value:
(X)
Apply dimming compensation to values.
Definition at line 31 of file hsv2rgb.cpp.
Referenced by hsv2rgb_raw_C().
FASTLED_INTERNAL
#define FASTLED_INTERNAL
Disables pragma messages and warnings.
Definition at line 5 of file hsv2rgb.cpp.
FIXFRAC8
#define FIXFRAC8 (N, D)
Value:
(((N)*256)/(D))
Convert a fractional input into a constant.
Definition at line 499 of file hsv2rgb.cpp.
Referenced by rgb2hsv_approximate().
FORCE_REFERENCE
#define FORCE_REFERENCE (var)
Value:
asm volatile("" : : "r" (var))
Force a variable reference to avoid compiler over-optimization.
Sometimes the compiler will do clever things to reduce code size that result in a net slowdown, if it thinks that a variable is not used in a certain location. This macro does its best to convince the compiler that the variable is used in this location, to help control code motion and de-duplication that would result in a slowdown.
Definition at line 241 of file hsv2rgb.cpp.
Referenced by hsv2rgb_rainbow().
HSV_SECTION_3
#define HSV_SECTION_3 (0x40)
Divide the color wheel into four sections, 64 elements each.
Todo
I believe this is mis-named, and should be HSV_SECTION_4
Definition at line 39 of file hsv2rgb.cpp.
Referenced by hsv2rgb_raw_C().
HSV_SECTION_6
#define HSV_SECTION_6 (0x20)
Divide the color wheel into eight sections, 32 elements each.
Todo
Unused. Remove?
Definition at line 35 of file hsv2rgb.cpp.
Function Documentation
hsv2rgb_rainbow()
void hsv2rgb_rainbow (const CHSV & hsv, CRGB & rgb)
Definition at line 251 of file hsv2rgb.cpp.
{
    // Yellow has a higher inherent brightness than
    // any other color; 'pure' yellow is perceived to
    // be 93% as bright as white.  In order to make
    // yellow appear the correct relative brightness,
    // it has to be rendered brighter than all other
    // colors.
    // Level Y1 is a moderate boost, the default.
    // Level Y2 is a strong boost.
    const uint8_t Y1 = 1;
    const uint8_t Y2 = 0;
    // G2: Whether to divide all greens by two.
    // Depends GREATLY on your particular LEDs
    const uint8_t G2 = 0;
    // Gscale: what to scale green down by.
    // Depends GREATLY on your particular LEDs
    const uint8_t Gscale = 0;
    uint8_t hue = hsv.hue;
    uint8_t sat = hsv.sat;
    uint8_t val = hsv.val;
    uint8_t offset = hue & 0x1F; // 0..31
    // offset8 = offset * 8
    uint8_t offset8 = offset;
    {
#if defined(__AVR__)
        // Left to its own devices, gcc turns "x <<= 3" into a loop
        // It's much faster and smaller to just do three single-bit shifts
        // So this business is to force that.
        offset8 <<= 1;
        asm volatile("");
        offset8 <<= 1;
        asm volatile("");
        offset8 <<= 1;
#else
        // On ARM and other non-AVR platforms, we just shift 3.
        offset8 <<= 3;
#endif
    }
    uint8_t third = scale8( offset8, (256 / 3)); // max = 85
    uint8_t r, g, b;
    if( ! (hue & 0x80) ) {
        // 0XX
        if( ! (hue & 0x40) ) {
            // 00X
            //section 0-1
            if( ! (hue & 0x20) ) {
                // 000
                //case 0: // R -> O
                r = K255 - third;
                g = third;
                b = 0;
                FORCE_REFERENCE(b);
            } else {
                // 001
                //case 1: // O -> Y
                if( Y1 ) {
                    r = K171;
                    g = K85 + third ;
                    b = 0;
                    FORCE_REFERENCE(b);
                }
                if( Y2 ) {
                    r = K170 + third;
                    //uint8_t twothirds = (third << 1);
                    uint8_t twothirds = scale8( offset8, ((256 * 2) / 3)); // max=170
                    g = K85 + twothirds;
                    b = 0;
                    FORCE_REFERENCE(b);
                }
            }
        } else {
            //01X
            // section 2-3
            if( !  (hue & 0x20) ) {
                // 010
                //case 2: // Y -> G
                if( Y1 ) {
                    //uint8_t twothirds = (third << 1);
                    uint8_t twothirds = scale8( offset8, ((256 * 2) / 3)); // max=170
                    r = K171 - twothirds;
                    g = K170 + third;
                    b = 0;
                    FORCE_REFERENCE(b);
                }
                if( Y2 ) {
                    r = K255 - offset8;
                    g = K255;
                    b = 0;
                    FORCE_REFERENCE(b);
                }
            } else {
                // 011
                // case 3: // G -> A
                r = 0;
                FORCE_REFERENCE(r);
                g = K255 - third;
                b = third;
            }
        }
    } else {
        // section 4-7
        // 1XX
        if( ! (hue & 0x40) ) {
            // 10X
            if( ! ( hue & 0x20) ) {
                // 100
                //case 4: // A -> B
                r = 0;
                FORCE_REFERENCE(r);
                //uint8_t twothirds = (third << 1);
                uint8_t twothirds = scale8( offset8, ((256 * 2) / 3)); // max=170
                g = K171 - twothirds; //K170?
                b = K85  + twothirds;
            } else {
                // 101
                //case 5: // B -> P
                r = third;
                g = 0;
                FORCE_REFERENCE(g);
                b = K255 - third;
            }
        } else {
            if( !  (hue & 0x20)  ) {
                // 110
                //case 6: // P -- K
                r = K85 + third;
                g = 0;
                FORCE_REFERENCE(g);
                b = K171 - third;
            } else {
                // 111
                //case 7: // K -> R
                r = K170 + third;
                g = 0;
                FORCE_REFERENCE(g);
                b = K85 - third;
            }
        }
    }
    // This is one of the good places to scale the green down,
    // although the client can scale green down as well.
    if( G2 ) g = g >> 1;
    if( Gscale ) g = scale8_video_LEAVING_R1_DIRTY( g, Gscale);
    // Scale down colors if we're desaturated at all
    // and add the brightness_floor to r, g, and b.
    if( sat != 255 ) {
        if( sat == 0) {
            r = 255; b = 255; g = 255;
        } else {
            uint8_t desat = 255 - sat;
            desat = scale8_video( desat, desat);
            uint8_t satscale = 255 - desat;
            //satscale = sat; // uncomment to revert to pre-2021 saturation behavior
            //nscale8x3_video( r, g, b, sat);
#if (FASTLED_SCALE8_FIXED==1)
            r = scale8_LEAVING_R1_DIRTY( r, satscale);
            asm volatile("");  // Fixes jumping red pixel: https://github.com/FastLED/FastLED/pull/943
            g = scale8_LEAVING_R1_DIRTY( g, satscale);
            asm volatile("");
            b = scale8_LEAVING_R1_DIRTY( b, satscale);
            asm volatile("");
            cleanup_R1();
#else
            if( r ) r = scale8( r, satscale) + 1;
            if( g ) g = scale8( g, satscale) + 1;
            if( b ) b = scale8( b, satscale) + 1;
#endif
            uint8_t brightness_floor = desat;
            r += brightness_floor;
            g += brightness_floor;
            b += brightness_floor;
        }
    }
    // Now scale everything down if we're at value < 255.
    if( val != 255 ) {
        val = scale8_video_LEAVING_R1_DIRTY( val, val);
        if( val == 0 ) {
            r=0; g=0; b=0;
        } else {
            // nscale8x3_video( r, g, b, val);
#if (FASTLED_SCALE8_FIXED==1)
            r = scale8_LEAVING_R1_DIRTY( r, val);
            asm volatile("");  // Fixes jumping red pixel: https://github.com/FastLED/FastLED/pull/943
            g = scale8_LEAVING_R1_DIRTY( g, val);
            asm volatile("");
            b = scale8_LEAVING_R1_DIRTY( b, val);
            asm volatile("");
            cleanup_R1();
#else
            if( r ) r = scale8( r, val) + 1;
            if( g ) g = scale8( g, val) + 1;
            if( b ) b = scale8( b, val) + 1;
#endif
        }
    }
    // Here we have the old AVR "missing std X+n" problem again
    // It turns out that fixing it winds up costing more than
    // not fixing it.
    // To paraphrase Dr Bronner, profile! profile! profile!
    //asm volatile(  ""  :  :  : "r26", "r27" );
    //asm volatile (" movw r30, r26 \n" : : : "r30", "r31");
    rgb.r = r;
    rgb.g = g;
    rgb.b = b;
}
References cleanup_R1(), FORCE_REFERENCE, scale8(), scale8_LEAVING_R1_DIRTY(), scale8_video(), and scale8_video_LEAVING_R1_DIRTY().
Referenced by hsv2rgb_rainbow().
hsv2rgb_raw_avr()
void hsv2rgb_raw_avr (const struct CHSV & hsv, struct CRGB & rgb)
HSV to RGB implementation in raw C, for the AVR platform only.
hsv2rgb_raw_C()
void hsv2rgb_raw_C (const struct CHSV & hsv, struct CRGB & rgb)
HSV to RGB implementation in raw C, platform independent.
Definition at line 41 of file hsv2rgb.cpp.
{
    // Convert hue, saturation and brightness ( HSV/HSB ) to RGB
    // "Dimming" is used on saturation and brightness to make
    // the output more visually linear.
    // Apply dimming curves
    uint8_t value = APPLY_DIMMING( hsv.val);  // cppcheck-suppress selfAssignment
    uint8_t saturation = hsv.sat;
    // The brightness floor is minimum number that all of
    // R, G, and B will be set to.
    uint8_t invsat = APPLY_DIMMING( 255 - saturation);  // cppcheck-suppress selfAssignment
    uint8_t brightness_floor = (value * invsat) / 256;
    // The color amplitude is the maximum amount of R, G, and B
    // that will be added on top of the brightness_floor to
    // create the specific hue desired.
    uint8_t color_amplitude = value - brightness_floor;
    // Figure out which section of the hue wheel we're in,
    // and how far offset we are withing that section
    uint8_t section = hsv.hue / HSV_SECTION_3; // 0..2
    uint8_t offset = hsv.hue % HSV_SECTION_3;  // 0..63
    uint8_t rampup = offset; // 0..63
    uint8_t rampdown = (HSV_SECTION_3 - 1) - offset; // 63..0
    // We now scale rampup and rampdown to a 0-255 range -- at least
    // in theory, but here's where architecture-specific decsions
    // come in to play:
    // To scale them up to 0-255, we'd want to multiply by 4.
    // But in the very next step, we multiply the ramps by other
    // values and then divide the resulting product by 256.
    // So which is faster?
    //   ((ramp * 4) * othervalue) / 256
    // or
    //   ((ramp    ) * othervalue) /  64
    // It depends on your processor architecture.
    // On 8-bit AVR, the "/ 256" is just a one-cycle register move,
    // but the "/ 64" might be a multicycle shift process. So on AVR
    // it's faster do multiply the ramp values by four, and then
    // divide by 256.
    // On ARM, the "/ 256" and "/ 64" are one cycle each, so it's
    // faster to NOT multiply the ramp values by four, and just to
    // divide the resulting product by 64 (instead of 256).
    // Moral of the story: trust your profiler, not your insticts.
    // Since there's an AVR assembly version elsewhere, we'll
    // assume what we're on an architecture where any number of
    // bit shifts has roughly the same cost, and we'll remove the
    // redundant math at the source level:
    //  // scale up to 255 range
    //  //rampup *= 4; // 0..252
    //  //rampdown *= 4; // 0..252
    // compute color-amplitude-scaled-down versions of rampup and rampdown
    uint8_t rampup_amp_adj   = (rampup   * color_amplitude) / (256 / 4);
    uint8_t rampdown_amp_adj = (rampdown * color_amplitude) / (256 / 4);
    // add brightness_floor offset to everything
    uint8_t rampup_adj_with_floor   = rampup_amp_adj   + brightness_floor;
    uint8_t rampdown_adj_with_floor = rampdown_amp_adj + brightness_floor;
    if( section ) {
        if( section == 1) {
            // section 1: 0x40..0x7F
            rgb.r = brightness_floor;
            rgb.g = rampdown_adj_with_floor;
            rgb.b = rampup_adj_with_floor;
        } else {
            // section 2; 0x80..0xBF
            rgb.r = rampup_adj_with_floor;
            rgb.g = brightness_floor;
            rgb.b = rampdown_adj_with_floor;
        }
    } else {
        // section 0: 0x00..0x3F
        rgb.r = rampdown_adj_with_floor;
        rgb.g = rampup_adj_with_floor;
        rgb.b = brightness_floor;
    }
}
References APPLY_DIMMING, and HSV_SECTION_3.
Referenced by hsv2rgb_raw().