FastLED: REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER > Class Template Reference
REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER > Class Template Reference
Detailed Description
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER>
class REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >
A skeletal implementation of hardware SPI support.
Fill in the necessary code for init, waiting, and writing. The rest of the method implementations should provide a starting point, even if they're not the most efficient to start with
Definition at line 16 of file fastspi_ref.h.
#include <fastspi_ref.h>
Public Member Functions
void init ()
initialize the SPI subssytem
void release ()
release the CS select
SAMHArdwareSPIOutput (Selectable *pSelect)
Constructor with selectable.
SAMHardwareSPIOutput ()
Default Constructor.
void select ()
latch the CS select
void setSelect (Selectable *pSelect)
set the object representing the selectable
template<class D >
void writeBytes (FASTLED_REGISTER uint8_t *data, int len)
A full cycle of writing a value for len bytes, including select, release, and waiting.
void writeBytes (FASTLED_REGISTER uint8_t *data, int len)
A full cycle of writing a value for len bytes, including select, release, and waiting.
void writeBytesValue (uint8_t value, int len)
A full cycle of writing a value for len bytes, including select, release, and waiting.
template<uint8_t FLAGS, class D , EOrder RGB_ORDER>
void writePixels (PixelController< RGB_ORDER > pixels, void *context=NULL)
write a block of uint8_ts out in groups of three.
Static Public Member Functions
static void waitFully ()
wait until all queued up data has been written
template<uint8_t BIT>
static void writeBit (uint8_t b)
write a single bit out, which bit from the passed in byte is determined by template parameter
static void writeByte (uint8_t b)
write a byte out via SPI (returns immediately on writing register)
static void writeBytesValueRaw (uint8_t value, int len)
A raw set of writing byte values, assumes setup/init/waiting done elsewhere.
static void writeWord (uint16_t w)
write a word out via SPI (returns immediately on writing register)
Private Attributes
Selectable * m_pSelect
Member Function Documentation
init()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::init () inline
initialize the SPI subssytem
Definition at line 30 of file fastspi_ref.h.
{ /* TODO */ }
release()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release () inline
release the CS select
Definition at line 36 of file fastspi_ref.h.
{ if(m_pSelect != NULL) { m_pSelect->release(); } }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::m_pSelect, and Selectable::release().
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValue(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
SAMHArdwareSPIOutput()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::SAMHArdwareSPIOutput (Selectable * pSelect) inline
Constructor with selectable.
Definition at line 24 of file fastspi_ref.h.
{ m_pSelect = pSelect; }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::m_pSelect.
SAMHardwareSPIOutput()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::SAMHardwareSPIOutput () inline
Default Constructor.
Definition at line 21 of file fastspi_ref.h.
{ m_pSelect = NULL; }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::m_pSelect.
select()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select () inline
latch the CS select
Definition at line 33 of file fastspi_ref.h.
{ if(m_pSelect != NULL) { m_pSelect->select(); } }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::m_pSelect, and Selectable::select().
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValue(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
setSelect()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::setSelect (Selectable * pSelect) inline
set the object representing the selectable
Definition at line 27 of file fastspi_ref.h.
{ /* TODO */ }
waitFully()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> static void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::waitFully () inline static
wait until all queued up data has been written
Definition at line 39 of file fastspi_ref.h.
{ /* TODO */ }
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes().
writeBit()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> template<uint8_t BIT> static void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBit (uint8_t b) inline static
write a single bit out, which bit from the passed in byte is determined by template parameter
Definition at line 74 of file fastspi_ref.h.
{ /* TODO */ }
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
writeByte()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> static void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeByte (uint8_t b) inline static
write a byte out via SPI (returns immediately on writing register)
Definition at line 42 of file fastspi_ref.h.
{ /* TODO */ }
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValueRaw(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
writeBytes() [1/2]
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> template<class D > void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes (FASTLED_REGISTER uint8_t * data, int len) inline
A full cycle of writing a value for len bytes, including select, release, and waiting.
Definition at line 58 of file fastspi_ref.h.
{
        uint8_t *end = data + len;
        select();
        // could be optimized to write 16bit words out instead of 8bit bytes
        while(data != end) {
            writeByte(D::adjust(*data++));
        }
        D::postBlock(len);
        waitFully();
        release();
    }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::waitFully(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeByte().
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes().
writeBytes() [2/2]
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes (FASTLED_REGISTER uint8_t * data, int len) inline
A full cycle of writing a value for len bytes, including select, release, and waiting.
Definition at line 71 of file fastspi_ref.h.
{ writeBytes<DATA_NOP>(data, len); }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytes().
writeBytesValue()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValue (uint8_t value, int len) inline
A full cycle of writing a value for len bytes, including select, release, and waiting.
Definition at line 53 of file fastspi_ref.h.
{
        select(); writeBytesValueRaw(value, len); release();
    }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValueRaw().
writeBytesValueRaw()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> static void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValueRaw (uint8_t value, int len) inline static
A raw set of writing byte values, assumes setup/init/waiting done elsewhere.
Definition at line 48 of file fastspi_ref.h.
{
        while(len--) { writeByte(value); }
    }
References REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeByte().
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBytesValue().
writePixels()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> template<uint8_t FLAGS, class D , EOrder RGB_ORDER> void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels (PixelController< RGB_ORDER > pixels, void * context = NULL) inline
write a block of uint8_ts out in groups of three.
len is the total number of uint8_ts to write out. The template parameters indicate how many uint8_ts to skip at the beginning and/or end of each grouping
Definition at line 78 of file fastspi_ref.h.
{
        select();
        while(data != end) {
            if(FLAGS & FLAG_START_BIT) {
                writeBit<0>(1);
            }
            writeByte(D::adjust(pixels.loadAndScale0()));
            writeByte(D::adjust(pixels.loadAndScale1()));
            writeByte(D::adjust(pixels.loadAndScale2()));
            pixels.advanceData();
            pixels.stepDithering();
            data += (3+skip);
        }
        D::postBlock(len);
        release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), FLAG_START_BIT, PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeBit(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeByte().
writeWord()
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> static void REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writeWord (uint16_t w) inline static
write a word out via SPI (returns immediately on writing register)
Definition at line 45 of file fastspi_ref.h.
{ /* TODO */ }
Member Data Documentation
m_pSelect
template<uint8_t _DATA_PIN, uint8_t _CLOCK_PIN, uint32_t _SPI_CLOCK_DIVIDER> Selectable* REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::m_pSelect private
Definition at line 17 of file fastspi_ref.h.
Referenced by REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::release(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::SAMHArdwareSPIOutput(), REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::SAMHardwareSPIOutput(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::select().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fastspi_ref.h