FastLED: /home/runner/work/FastLED/FastLED/examples/SmartMatrix/SmartMatrix.ino File Reference
SmartMatrix.ino File Reference
Detailed Description
Demonstrates how to use FastLED with the SmartMatrix library.
Definition in file SmartMatrix.ino.
#include <SmartMatrix.h>
#include <FastLED.h>
Macros
#define kMatrixHeight 32
#define kMatrixWidth 32
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Functions
void fillnoise8 ()
void loop ()
void setup ()
uint16_t XY (uint8_t x, uint8_t y)
Variables
const bool kMatrixSerpentineLayout = false
CRGB leds [kMatrixWidth *kMatrixHeight]
uint8_t noise [kMatrixWidth][kMatrixHeight]
uint16_t scale = 31
uint16_t speed = 20
static uint16_t x
static uint16_t y
static uint16_t z
Macro Definition Documentation
kMatrixHeight
#define kMatrixHeight 32
Examples
Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, SmartMatrix.ino, and XYMatrix.ino.
Definition at line 14 of file SmartMatrix.ino.
Referenced by DrawOneFrame(), fillnoise8(), loop(), mapNoiseToLEDsUsingPalette(), XY(), and XYsafe().
kMatrixWidth
#define kMatrixWidth 32
Examples
Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, SmartMatrix.ino, and XYMatrix.ino.
Definition at line 13 of file SmartMatrix.ino.
Referenced by DrawOneFrame(), fillnoise8(), loop(), mapNoiseToLEDsUsingPalette(), XY(), and XYsafe().
NUM_LEDS
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Definition at line 17 of file SmartMatrix.ino.
Function Documentation
fillnoise8()
void fillnoise8 ()
Definition at line 93 of file SmartMatrix.ino.
                  {
  for(int i = 0; i < kMatrixWidth; i++) {
    int ioffset = scale * i;
    for(int j = 0; j < kMatrixHeight; j++) {
      int joffset = scale * j;
      noise[i][j] = inoise8(x + ioffset,y + joffset,z);
    }
  }
  z += speed;
}
References inoise8(), kMatrixHeight, kMatrixWidth, noise, scale, speed, x, y, and z.
loop()
void loop ()
Definition at line 105 of file SmartMatrix.ino.
            {
  static uint8_t circlex = 0;
  static uint8_t circley = 0;
  static uint8_t ihue=0;
  fillnoise8();
  for(int i = 0; i < kMatrixWidth; i++) {
    for(int j = 0; j < kMatrixHeight; j++) {
      // We use the value at the (i,j) coordinate in the noise
      // array for our brightness, and the flipped value from (j,i)
      // for our pixel's hue.
      leds[XY(i,j)] = CHSV(noise[j][i],255,noise[i][j]);
      // You can also explore other ways to constrain the hue used, like below
      // leds[XY(i,j)] = CHSV(ihue + (noise[j][i]>>2),255,noise[i][j]);
    }
  }
  ihue+=1;
  // N.B. this requires SmartMatrix modified w/triple buffering support
  pSmartMatrix->fillCircle(circlex % 32,circley % 32,6,CRGB(CHSV(ihue+128,255,255)));
  circlex += random16(2);
  circley += random16(2);
  FastLED.show();
  // delay(10);
}
References FastLED, fillnoise8(), kMatrixHeight, kMatrixWidth, leds, noise, pSmartMatrix, random16(), CFastLED::show(), and XY().
setup()
void setup ()
Definition at line 70 of file SmartMatrix.ino.
             {
  // uncomment the following lines if you want to see FPS count information
  // Serial.begin(38400);
  // Serial.println("resetting!");
  delay(3000);
  FastLED.addLeds<SMART_MATRIX>(leds,NUM_LEDS);
  FastLED.setBrightness(96);
  // Initialize our coordinates to some random values
  x = random16();
  y = random16();
  z = random16();
  // Show off smart matrix scrolling text
  pSmartMatrix->setScrollMode(wrapForward);
  pSmartMatrix->setScrollColor({0xff, 0xff, 0xff});
  pSmartMatrix->setScrollSpeed(15);
  pSmartMatrix->setScrollFont(font6x10);
  pSmartMatrix->scrollText("Smart Matrix & FastLED", -1);
  pSmartMatrix->setScrollOffsetFromEdge(10);
}
References CFastLED::addLeds(), FastLED, leds, NUM_LEDS, pSmartMatrix, random16(), CFastLED::setBrightness(), SMART_MATRIX, x, y, and z.
XY()
uint16_t XY (uint8_t x, uint8_t y)
Definition at line 22 of file SmartMatrix.ino.
{
  uint16_t i;
  if( kMatrixSerpentineLayout == false) {
    i = (y * kMatrixWidth) + x;
  }
  if( kMatrixSerpentineLayout == true) {
    if( y & 0x01) {
      // Odd rows run backwards
      uint8_t reverseX = (kMatrixWidth - 1) - x;
      i = (y * kMatrixWidth) + reverseX;
    } else {
      // Even rows run forwards
      i = (y * kMatrixWidth) + x;
    }
  }
  return i;
}
References kMatrixSerpentineLayout, kMatrixWidth, x, and y.
Variable Documentation
kMatrixSerpentineLayout
const bool kMatrixSerpentineLayout = false
Definition at line 15 of file SmartMatrix.ino.
leds
CRGB leds[kMatrixWidth *kMatrixHeight]
Definition at line 19 of file SmartMatrix.ino.
noise
uint8_t noise[kMatrixWidth][kMatrixHeight]
Definition at line 68 of file SmartMatrix.ino.
scale
uint16_t scale = 31
Definition at line 65 of file SmartMatrix.ino.
speed
uint16_t speed = 20
Definition at line 54 of file SmartMatrix.ino.
x
uint16_t x static
Definition at line 45 of file SmartMatrix.ino.
y
uint16_t y static
Definition at line 46 of file SmartMatrix.ino.
z
uint16_t z static
Definition at line 47 of file SmartMatrix.ino.