FastLED: Pixel Data Types (CRGB/CHSV)
Pixel Data Types (CRGB/CHSV)
Detailed Description
Structs that hold pixel color data
Classes
struct CHSV
Representation of an HSV pixel (hue, saturation, value (aka brightness)).
union CHSV.__unnamed1__
struct CHSV.__unnamed1__.__unnamed3__
union CHSV.__unnamed1__.__unnamed3__.__unnamed5__
union CHSV.__unnamed1__.__unnamed3__.__unnamed7__
union CHSV.__unnamed1__.__unnamed3__.__unnamed9__
struct CRGB
Representation of an RGB pixel (Red, Green, Blue)
union CRGB.__unnamed15__
struct CRGB.__unnamed15__.__unnamed17__
union CRGB.__unnamed15__.__unnamed17__.__unnamed19__
union CRGB.__unnamed15__.__unnamed17__.__unnamed21__
union CRGB.__unnamed15__.__unnamed17__.__unnamed23__
Enumerations
enum HSVHue {
HUE_RED = 0 , HUE_ORANGE = 32 , HUE_YELLOW = 64 , HUE_GREEN = 96 ,
HUE_AQUA = 128 , HUE_BLUE = 160 , HUE_PURPLE = 192 , HUE_PINK = 224
}
Pre-defined hue values for CHSV objects.
Functions
void hsv2rgb_rainbow (const struct CHSV &hsv, struct CRGB &rgb)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
FASTLED_FORCE_INLINE bool operator!= (const CHSV &lhs, const CHSV &rhs)
Check if two CHSV objects do not have the same color data.
FASTLED_FORCE_INLINE bool operator!= (const CRGB &lhs, const CRGB &rhs)
Check if two CRGB objects do not have the same color data.
FASTLED_FORCE_INLINE CRGB operator% (const CRGB &p1, uint8_t d)
Scale using CRGB::nscale8_video()
FASTLED_FORCE_INLINE CRGB operator& (const CRGB &p1, const CRGB &p2)
Combine two CRGB objects, taking the smallest value of each channel.
FASTLED_FORCE_INLINE CRGB operator* (const CRGB &p1, uint8_t d)
Multiply each of the channels by a constant, saturating each channel at 0xFF.
FASTLED_FORCE_INLINE CRGB operator+ (const CRGB &p1, const CRGB &p2)
Add one CRGB to another, saturating at 0xFF for each channel.
FASTLED_FORCE_INLINE CRGB operator- (const CRGB &p1, const CRGB &p2)
Subtract one CRGB from another, saturating at 0x00 for each channel.
FASTLED_FORCE_INLINE CRGB operator/ (const CRGB &p1, uint8_t d)
Divide each of the channels by a constant.
FASTLED_FORCE_INLINE bool operator< (const CRGB &lhs, const CRGB &rhs)
Check if the sum of the color channels in one CRGB object is less than another.
FASTLED_FORCE_INLINE bool operator<= (const CRGB &lhs, const CRGB &rhs)
Check if the sum of the color channels in one CRGB object is less than or equal to another.
FASTLED_FORCE_INLINE bool operator== (const CHSV &lhs, const CHSV &rhs)
Check if two CHSV objects have the same color data.
FASTLED_FORCE_INLINE bool operator== (const CRGB &lhs, const CRGB &rhs)
Check if two CRGB objects have the same color data.
FASTLED_FORCE_INLINE bool operator> (const CRGB &lhs, const CRGB &rhs)
Check if the sum of the color channels in one CRGB object is greater than another.
FASTLED_FORCE_INLINE bool operator>= (const CRGB &lhs, const CRGB &rhs)
Check if the sum of the color channels in one CRGB object is greater than or equal to another.
FASTLED_FORCE_INLINE CRGB operator| (const CRGB &p1, const CRGB &p2)
Combine two CRGB objects, taking the largest value of each channel.
Class Documentation
CHSV
struct CHSV
Public Member Functions
constexpr CHSV ()
Default constructor.
constexpr CHSV (const CHSV &rhs) noexcept
Allow copy construction.
constexpr CHSV (uint8_t ih, uint8_t is, uint8_t iv)
Allow construction from hue, saturation, and value.
CHSV & operator= (const CHSV &rhs)=default
Allow copy construction.
uint8_t & operator[] (uint8_t x)
Array access operator to index into the CHSV object.
const uint8_t & operator[] (uint8_t x) const
Array access operator to index into the CHSV object.
CHSV & setHSV (uint8_t ih, uint8_t is, uint8_t iv)
Assign new HSV values.
Public Attributes
union {
struct {
union {
uint8_t h
Color hue.
uint8_t hue
Color hue.
}
union {
uint8_t s
Color saturation.
uint8_t sat
Color saturation.
uint8_t saturation
Color saturation.
}
union {
uint8_t v
Color value (brightness).
uint8_t val
Color value (brightness).
uint8_t value
Color value (brightness).
}
}
uint8_t raw [3]
Access the hue, saturation, and value data as an array.
};
Constructor & Destructor Documentation
CHSV() [1/3]
CHSV::CHSV () inline constexpr
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 65 of file chsv.h.
: h(0), s(0), v(0) { }
CHSV() [2/3]
CHSV::CHSV (uint8_t ih, uint8_t is, uint8_t iv) inline constexpr
Allow construction from hue, saturation, and value.
Parameters
ih input hue
is input saturation
iv input value
Definition at line 71 of file chsv.h.
        : h(ih), s(is), v(iv)
    {
    }
CHSV() [3/3]
CHSV::CHSV (const CHSV & rhs) inline constexpr noexcept
Allow copy construction.
Definition at line 77 of file chsv.h.
: h(rhs.h), s(rhs.s), v(rhs.v) { }
Member Function Documentation
operator=()
CHSV & CHSV::operator= (const CHSV & rhs) inline default
Allow copy construction.
operator[]() [1/2]
uint8_t & CHSV::operator[] (uint8_t x) inline
Array access operator to index into the CHSV object.
Parameters
x the index to retrieve (0-2)
Returns
the CHSV::raw value for the given index
Definition at line 52 of file chsv.h.
    {
        return raw[x];
    }
References x.
operator[]() [2/2]
const uint8_t & CHSV::operator[] (uint8_t x) const inline
Array access operator to index into the CHSV object.
Parameters
x the index to retrieve (0-2)
Returns
the CHSV::raw value for the given index
Definition at line 58 of file chsv.h.
    {
        return raw[x];
    }
References x.
setHSV()
CHSV & CHSV::setHSV (uint8_t ih, uint8_t is, uint8_t iv) inline
Assign new HSV values.
Parameters
ih input hue
is input saturation
iv input value
Returns
reference to the CHSV object
Definition at line 87 of file chsv.h.
    {
        h = ih;
        s = is;
        v = iv;
        return *this;
    }
Member Data Documentation
[union]
union { ... } CHSV
CHSV.__unnamed1__
union CHSV.__unnamed1__
Class Members
struct CHSV.__unnamed1__.__unnamed3__ __unnamed__
uint8_t raw[3] Access the hue, saturation, and value data as an array.
Where:
raw[0] is the hue
raw[1] is the saturation
raw[2] is the value
CHSV.__unnamed1__.__unnamed3__
struct CHSV.__unnamed1__.__unnamed3__
Class Members
union CHSV.__unnamed1__.__unnamed3__.__unnamed5__ __unnamed__
union CHSV.__unnamed1__.__unnamed3__.__unnamed7__ __unnamed__
union CHSV.__unnamed1__.__unnamed3__.__unnamed9__ __unnamed__
CHSV.__unnamed1__.__unnamed3__.__unnamed5__
union CHSV.__unnamed1__.__unnamed3__.__unnamed5__
Class Members
uint8_t h
uint8_t hue Color hue.
This is an 8-bit value representing an angle around the color wheel. Where 0 is 0, and 255 is 358.
CHSV.__unnamed1__.__unnamed3__.__unnamed7__
union CHSV.__unnamed1__.__unnamed3__.__unnamed7__
Class Members
uint8_t s
uint8_t sat
uint8_t saturation Color saturation.
This is an 8-bit value representing a percentage.
CHSV.__unnamed1__.__unnamed3__.__unnamed9__
union CHSV.__unnamed1__.__unnamed3__.__unnamed9__
Class Members
uint8_t v
uint8_t val
uint8_t value Color value (brightness).
This is an 8-bit value representing a percentage.
CRGB
struct CRGB
Public Types
enum HTMLColorCode {
AliceBlue =0xF0F8FF , Amethyst =0x9966CC , AntiqueWhite =0xFAEBD7 , Aqua =0x00FFFF ,
Aquamarine =0x7FFFD4 , Azure =0xF0FFFF , Beige =0xF5F5DC , Bisque =0xFFE4C4 ,
Black =0x000000 , BlanchedAlmond =0xFFEBCD , Blue =0x0000FF , BlueViolet =0x8A2BE2 ,
Brown =0xA52A2A , BurlyWood =0xDEB887 , CadetBlue =0x5F9EA0 , Chartreuse =0x7FFF00 ,
Chocolate =0xD2691E , Coral =0xFF7F50 , CornflowerBlue =0x6495ED , Cornsilk =0xFFF8DC ,
Crimson =0xDC143C , Cyan =0x00FFFF , DarkBlue =0x00008B , DarkCyan =0x008B8B ,
DarkGoldenrod =0xB8860B , DarkGray =0xA9A9A9 , DarkGrey =0xA9A9A9 , DarkGreen =0x006400 ,
DarkKhaki =0xBDB76B , DarkMagenta =0x8B008B , DarkOliveGreen =0x556B2F , DarkOrange =0xFF8C00 ,
DarkOrchid =0x9932CC , DarkRed =0x8B0000 , DarkSalmon =0xE9967A , DarkSeaGreen =0x8FBC8F ,
DarkSlateBlue =0x483D8B , DarkSlateGray =0x2F4F4F , DarkSlateGrey =0x2F4F4F , DarkTurquoise =0x00CED1 ,
DarkViolet =0x9400D3 , DeepPink =0xFF1493 , DeepSkyBlue =0x00BFFF , DimGray =0x696969 ,
DimGrey =0x696969 , DodgerBlue =0x1E90FF , FireBrick =0xB22222 , FloralWhite =0xFFFAF0 ,
ForestGreen =0x228B22 , Fuchsia =0xFF00FF , Gainsboro =0xDCDCDC , GhostWhite =0xF8F8FF ,
Gold =0xFFD700 , Goldenrod =0xDAA520 , Gray =0x808080 , Grey =0x808080 ,
Green =0x008000 , GreenYellow =0xADFF2F , Honeydew =0xF0FFF0 , HotPink =0xFF69B4 ,
IndianRed =0xCD5C5C , Indigo =0x4B0082 , Ivory =0xFFFFF0 , Khaki =0xF0E68C ,
Lavender =0xE6E6FA , LavenderBlush =0xFFF0F5 , LawnGreen =0x7CFC00 , LemonChiffon =0xFFFACD ,
LightBlue =0xADD8E6 , LightCoral =0xF08080 , LightCyan =0xE0FFFF , LightGoldenrodYellow =0xFAFAD2 ,
LightGreen =0x90EE90 , LightGrey =0xD3D3D3 , LightPink =0xFFB6C1 , LightSalmon =0xFFA07A ,
LightSeaGreen =0x20B2AA , LightSkyBlue =0x87CEFA , LightSlateGray =0x778899 , LightSlateGrey =0x778899 ,
LightSteelBlue =0xB0C4DE , LightYellow =0xFFFFE0 , Lime =0x00FF00 , LimeGreen =0x32CD32 ,
Linen =0xFAF0E6 , Magenta =0xFF00FF , Maroon =0x800000 , MediumAquamarine =0x66CDAA ,
MediumBlue =0x0000CD , MediumOrchid =0xBA55D3 , MediumPurple =0x9370DB , MediumSeaGreen =0x3CB371 ,
MediumSlateBlue =0x7B68EE , MediumSpringGreen =0x00FA9A , MediumTurquoise =0x48D1CC , MediumVioletRed =0xC71585 ,
MidnightBlue =0x191970 , MintCream =0xF5FFFA , MistyRose =0xFFE4E1 , Moccasin =0xFFE4B5 ,
NavajoWhite =0xFFDEAD , Navy =0x000080 , OldLace =0xFDF5E6 , Olive =0x808000 ,
OliveDrab =0x6B8E23 , Orange =0xFFA500 , OrangeRed =0xFF4500 , Orchid =0xDA70D6 ,
PaleGoldenrod =0xEEE8AA , PaleGreen =0x98FB98 , PaleTurquoise =0xAFEEEE , PaleVioletRed =0xDB7093 ,
PapayaWhip =0xFFEFD5 , PeachPuff =0xFFDAB9 , Peru =0xCD853F , Pink =0xFFC0CB ,
Plaid =0xCC5533 , Plum =0xDDA0DD , PowderBlue =0xB0E0E6 , Purple =0x800080 ,
Red =0xFF0000 , RosyBrown =0xBC8F8F , RoyalBlue =0x4169E1 , SaddleBrown =0x8B4513 ,
Salmon =0xFA8072 , SandyBrown =0xF4A460 , SeaGreen =0x2E8B57 , Seashell =0xFFF5EE ,
Sienna =0xA0522D , Silver =0xC0C0C0 , SkyBlue =0x87CEEB , SlateBlue =0x6A5ACD ,
SlateGray =0x708090 , SlateGrey =0x708090 , Snow =0xFFFAFA , SpringGreen =0x00FF7F ,
SteelBlue =0x4682B4 , Tan =0xD2B48C , Teal =0x008080 , Thistle =0xD8BFD8 ,
Tomato =0xFF6347 , Turquoise =0x40E0D0 , Violet =0xEE82EE , Wheat =0xF5DEB3 ,
White =0xFFFFFF , WhiteSmoke =0xF5F5F5 , Yellow =0xFFFF00 , YellowGreen =0x9ACD32 ,
FairyLight =0xFFE42D , FairyLightNCC =0xFF9D2A
}
Predefined RGB colors.
Public Member Functions
FASTLED_FORCE_INLINE CRGB ()=default
Default constructor.
constexpr CRGB (ColorTemperature colorcode) noexcept
Allow construction from a ColorTemperature enum.
FASTLED_FORCE_INLINE CRGB (const CHSV &rhs)
Allow construction from a CHSV color.
FASTLED_FORCE_INLINE CRGB (const CRGB &rhs)=default
Allow copy construction.
constexpr CRGB (LEDColorCorrection colorcode) noexcept
Allow construction from a LEDColorCorrection enum.
constexpr CRGB (uint32_t colorcode) noexcept
Allow construction from 32-bit (really 24-bit) bit 0xRRGGBB color code.
constexpr CRGB (uint8_t ir, uint8_t ig, uint8_t ib) noexcept
Allow construction from red, green, and blue.
FASTLED_FORCE_INLINE CRGB & addToRGB (uint8_t d)
Add a constant to each channel, saturating at 0xFF.
constexpr uint32_t as_uint32_t () const noexcept
FASTLED_FORCE_INLINE CRGB & fadeLightBy (uint8_t fadefactor)
fadeLightBy is a synonym for nscale8_video(), as a fade instead of a scale
FASTLED_FORCE_INLINE CRGB & fadeToBlackBy (uint8_t fadefactor)
fadeToBlackBy is a synonym for nscale8(), as a fade instead of a scale
FASTLED_FORCE_INLINE uint8_t getAverageLight () const
Get the average of the R, G, and B values.
FASTLED_FORCE_INLINE uint8_t getLuma () const
Get the "luma" of a CRGB object.
FASTLED_FORCE_INLINE uint8_t getParity ()
Returns 0 or 1, depending on the lowest bit of the sum of the color components.
FASTLED_FORCE_INLINE CRGB lerp16 (const CRGB &other, fract16 frac) const
Return a new CRGB object after performing a linear interpolation between this object and the passed in object.
FASTLED_FORCE_INLINE CRGB lerp8 (const CRGB &other, fract8 frac) const
Return a new CRGB object after performing a linear interpolation between this object and the passed in object.
FASTLED_FORCE_INLINE void maximizeBrightness (uint8_t limit=255)
Maximize the brightness of this CRGB object.
FASTLED_FORCE_INLINE CRGB & nscale8 (const CRGB &scaledown)
Scale down a RGB to N/256ths of its current brightness, using "plain math" dimming rules.
CRGB & nscale8 (uint8_t scaledown)
Scale down a RGB to N/256ths of its current brightness, using "plain math" dimming rules.
constexpr CRGB nscale8_constexpr (const CRGB scaledown) const
FASTLED_FORCE_INLINE CRGB & nscale8_video (uint8_t scaledown)
Scale down a RGB to N/256ths of it's current brightness using "video" dimming rules.
constexpr operator bool () const
This allows testing a CRGB for zero-ness.
operator rgb24 () const
Convert to an rgb24 object, used with the SmartMatrix library.
constexpr operator uint32_t () const
Converts a CRGB to a 32-bit color having an alpha of 255.
FASTLED_FORCE_INLINE CRGB & operator%= (uint8_t scaledown)
%= is a synonym for nscale8_video().
FASTLED_FORCE_INLINE CRGB & operator&= (const CRGB &rhs)
"and" operator brings each channel down to the lower of the two values
FASTLED_FORCE_INLINE CRGB & operator&= (uint8_t d)
"and" operator brings each channel down to the lower of the two values
FASTLED_FORCE_INLINE CRGB & operator*= (uint8_t d)
Multiply each of the channels by a constant, saturating each channel at 0xFF.
FASTLED_FORCE_INLINE CRGB & operator++ ()
Add a constant of '1' from each channel, saturating at 0xFF.
FASTLED_FORCE_INLINE CRGB operator++ (int)
Add a constant of '1' from each channel, saturating at 0xFF.
FASTLED_FORCE_INLINE CRGB & operator+= (const CRGB &rhs)
Add one CRGB to another, saturating at 0xFF for each channel.
constexpr CRGB operator- () const
Invert each channel.
FASTLED_FORCE_INLINE CRGB & operator-- ()
Subtract a constant of '1' from each channel, saturating at 0x00.
FASTLED_FORCE_INLINE CRGB operator-- (int)
Subtract a constant of '1' from each channel, saturating at 0x00.
FASTLED_FORCE_INLINE CRGB & operator-= (const CRGB &rhs)
Subtract one CRGB from another, saturating at 0x00 for each channel.
FASTLED_FORCE_INLINE CRGB & operator/= (uint8_t d)
Divide each of the channels by a constant.
FASTLED_FORCE_INLINE CRGB & operator= (const CHSV &rhs)
Allow assignment from HSV color.
FASTLED_FORCE_INLINE CRGB & operator= (const CRGB &rhs)=default
Allow assignment from one RGB struct to another.
FASTLED_FORCE_INLINE CRGB & operator= (const uint32_t colorcode)
Allow assignment from 32-bit (really 24-bit) 0xRRGGBB color code.
FASTLED_FORCE_INLINE CRGB & operator>>= (uint8_t d)
Right shift each of the channels by a constant.
FASTLED_FORCE_INLINE uint8_t & operator[] (uint8_t x)
Array access operator to index into the CRGB object.
FASTLED_FORCE_INLINE const uint8_t & operator[] (uint8_t x) const
Array access operator to index into the CRGB object.
FASTLED_FORCE_INLINE CRGB & operator|= (const CRGB &rhs)
"or" operator brings each channel up to the higher of the two values
FASTLED_FORCE_INLINE CRGB & operator|= (uint8_t d)
"or" operator brings each channel up to the higher of the two values
FASTLED_FORCE_INLINE CRGB scale8 (const CRGB &scaledown) const
Return a CRGB object that is a scaled down version of this object.
FASTLED_FORCE_INLINE CRGB scale8 (uint8_t scaledown) const
Return a CRGB object that is a scaled down version of this object.
FASTLED_FORCE_INLINE CRGB & setColorCode (uint32_t colorcode)
Allow assignment from 32-bit (really 24-bit) 0xRRGGBB color code.
FASTLED_FORCE_INLINE CRGB & setHSV (uint8_t hue, uint8_t sat, uint8_t val)
Allow assignment from hue, saturation, and value.
FASTLED_FORCE_INLINE CRGB & setHue (uint8_t hue)
Allow assignment from just a hue.
FASTLED_FORCE_INLINE void setParity (uint8_t parity)
Adjusts the color in the smallest way possible so that the parity of the coloris now the desired value.
FASTLED_FORCE_INLINE CRGB & setRGB (uint8_t nr, uint8_t ng, uint8_t nb)
Allow assignment from red, green, and blue.
FASTLED_FORCE_INLINE CRGB & subtractFromRGB (uint8_t d)
Subtract a constant from each channel, saturating at 0x00.
fl::Str toString () const
Static Public Member Functions
static CRGB blend (const CRGB &p1, const CRGB &p2, fract8 amountOfP2)
static CRGB computeAdjustment (uint8_t scale, const CRGB &colorCorrection, const CRGB &colorTemperature)
Calculates the combined color adjustment to the LEDs at a given scale, color correction, and color temperature.
Public Attributes
union {
struct {
union {
uint8_t r
Red channel value.
uint8_t red
Red channel value.
}
union {
uint8_t g
Green channel value.
uint8_t green
Green channel value.
}
union {
uint8_t b
Blue channel value.
uint8_t blue
Blue channel value.
}
}
uint8_t raw [3]
Access the red, green, and blue data as an array.
};
Member Enumeration Documentation
HTMLColorCode
enum CRGB::HTMLColorCode
Predefined RGB colors.
Enumerator
AliceBlue
<div style='background:#F0F8FF;width:4em;height:4em;'></div>
Amethyst
<div style='background:#9966CC;width:4em;height:4em;'></div>
AntiqueWhite
<div style='background:#FAEBD7;width:4em;height:4em;'></div>
Aqua
<div style='background:#00FFFF;width:4em;height:4em;'></div>
Aquamarine
<div style='background:#7FFFD4;width:4em;height:4em;'></div>
Azure
<div style='background:#F0FFFF;width:4em;height:4em;'></div>
Beige
<div style='background:#F5F5DC;width:4em;height:4em;'></div>
Bisque
<div style='background:#FFE4C4;width:4em;height:4em;'></div>
Black
<div style='background:#000000;width:4em;height:4em;'></div>
BlanchedAlmond
<div style='background:#FFEBCD;width:4em;height:4em;'></div>
Blue
<div style='background:#0000FF;width:4em;height:4em;'></div>
BlueViolet
<div style='background:#8A2BE2;width:4em;height:4em;'></div>
Brown
<div style='background:#A52A2A;width:4em;height:4em;'></div>
BurlyWood
<div style='background:#DEB887;width:4em;height:4em;'></div>
CadetBlue
<div style='background:#5F9EA0;width:4em;height:4em;'></div>
Chartreuse
<div style='background:#7FFF00;width:4em;height:4em;'></div>
Chocolate
<div style='background:#D2691E;width:4em;height:4em;'></div>
Coral
<div style='background:#FF7F50;width:4em;height:4em;'></div>
CornflowerBlue
<div style='background:#6495ED;width:4em;height:4em;'></div>
Cornsilk
<div style='background:#FFF8DC;width:4em;height:4em;'></div>
Crimson
<div style='background:#DC143C;width:4em;height:4em;'></div>
Cyan
<div style='background:#00FFFF;width:4em;height:4em;'></div>
DarkBlue
<div style='background:#00008B;width:4em;height:4em;'></div>
DarkCyan
<div style='background:#008B8B;width:4em;height:4em;'></div>
DarkGoldenrod
<div style='background:#B8860B;width:4em;height:4em;'></div>
DarkGray
<div style='background:#A9A9A9;width:4em;height:4em;'></div>
DarkGrey
<div style='background:#A9A9A9;width:4em;height:4em;'></div>
DarkGreen
<div style='background:#006400;width:4em;height:4em;'></div>
DarkKhaki
<div style='background:#BDB76B;width:4em;height:4em;'></div>
DarkMagenta
<div style='background:#8B008B;width:4em;height:4em;'></div>
DarkOliveGreen
<div style='background:#556B2F;width:4em;height:4em;'></div>
DarkOrange
<div style='background:#FF8C00;width:4em;height:4em;'></div>
DarkOrchid
<div style='background:#9932CC;width:4em;height:4em;'></div>
DarkRed
<div style='background:#8B0000;width:4em;height:4em;'></div>
DarkSalmon
<div style='background:#E9967A;width:4em;height:4em;'></div>
DarkSeaGreen
<div style='background:#8FBC8F;width:4em;height:4em;'></div>
DarkSlateBlue
<div style='background:#483D8B;width:4em;height:4em;'></div>
DarkSlateGray
<div style='background:#2F4F4F;width:4em;height:4em;'></div>
DarkSlateGrey
<div style='background:#2F4F4F;width:4em;height:4em;'></div>
DarkTurquoise
<div style='background:#00CED1;width:4em;height:4em;'></div>
DarkViolet
<div style='background:#9400D3;width:4em;height:4em;'></div>
DeepPink
<div style='background:#FF1493;width:4em;height:4em;'></div>
DeepSkyBlue
<div style='background:#00BFFF;width:4em;height:4em;'></div>
DimGray
<div style='background:#696969;width:4em;height:4em;'></div>
DimGrey
<div style='background:#696969;width:4em;height:4em;'></div>
DodgerBlue
<div style='background:#1E90FF;width:4em;height:4em;'></div>
FireBrick
<div style='background:#B22222;width:4em;height:4em;'></div>
FloralWhite
<div style='background:#FFFAF0;width:4em;height:4em;'></div>
ForestGreen
<div style='background:#228B22;width:4em;height:4em;'></div>
Fuchsia
<div style='background:#FF00FF;width:4em;height:4em;'></div>
Gainsboro
<div style='background:#DCDCDC;width:4em;height:4em;'></div>
GhostWhite
<div style='background:#F8F8FF;width:4em;height:4em;'></div>
Gold
<div style='background:#FFD700;width:4em;height:4em;'></div>
Goldenrod
<div style='background:#DAA520;width:4em;height:4em;'></div>
Gray
<div style='background:#808080;width:4em;height:4em;'></div>
Grey
<div style='background:#808080;width:4em;height:4em;'></div>
Green
<div style='background:#008000;width:4em;height:4em;'></div>
GreenYellow
<div style='background:#ADFF2F;width:4em;height:4em;'></div>
Honeydew
<div style='background:#F0FFF0;width:4em;height:4em;'></div>
HotPink
<div style='background:#FF69B4;width:4em;height:4em;'></div>
IndianRed
<div style='background:#CD5C5C;width:4em;height:4em;'></div>
Indigo
<div style='background:#4B0082;width:4em;height:4em;'></div>
Ivory
<div style='background:#FFFFF0;width:4em;height:4em;'></div>
Khaki
<div style='background:#F0E68C;width:4em;height:4em;'></div>
Lavender
<div style='background:#E6E6FA;width:4em;height:4em;'></div>
LavenderBlush
<div style='background:#FFF0F5;width:4em;height:4em;'></div>
LawnGreen
<div style='background:#7CFC00;width:4em;height:4em;'></div>
LemonChiffon
<div style='background:#FFFACD;width:4em;height:4em;'></div>
LightBlue
<div style='background:#ADD8E6;width:4em;height:4em;'></div>
LightCoral
<div style='background:#F08080;width:4em;height:4em;'></div>
LightCyan
<div style='background:#E0FFFF;width:4em;height:4em;'></div>
LightGoldenrodYellow
<div style='background:#FAFAD2;width:4em;height:4em;'></div>
LightGreen
<div style='background:#90EE90;width:4em;height:4em;'></div>
LightGrey
<div style='background:#D3D3D3;width:4em;height:4em;'></div>
LightPink
<div style='background:#FFB6C1;width:4em;height:4em;'></div>
LightSalmon
<div style='background:#FFA07A;width:4em;height:4em;'></div>
LightSeaGreen
<div style='background:#20B2AA;width:4em;height:4em;'></div>
LightSkyBlue
<div style='background:#87CEFA;width:4em;height:4em;'></div>
LightSlateGray
<div style='background:#778899;width:4em;height:4em;'></div>
LightSlateGrey
<div style='background:#778899;width:4em;height:4em;'></div>
LightSteelBlue
<div style='background:#B0C4DE;width:4em;height:4em;'></div>
LightYellow
<div style='background:#FFFFE0;width:4em;height:4em;'></div>
Lime
<div style='background:#00FF00;width:4em;height:4em;'></div>
LimeGreen
<div style='background:#32CD32;width:4em;height:4em;'></div>
Linen
<div style='background:#FAF0E6;width:4em;height:4em;'></div>
Magenta
<div style='background:#FF00FF;width:4em;height:4em;'></div>
Maroon
<div style='background:#800000;width:4em;height:4em;'></div>
MediumAquamarine
<div style='background:#66CDAA;width:4em;height:4em;'></div>
MediumBlue
<div style='background:#0000CD;width:4em;height:4em;'></div>
MediumOrchid
<div style='background:#BA55D3;width:4em;height:4em;'></div>
MediumPurple
<div style='background:#9370DB;width:4em;height:4em;'></div>
MediumSeaGreen
<div style='background:#3CB371;width:4em;height:4em;'></div>
MediumSlateBlue
<div style='background:#7B68EE;width:4em;height:4em;'></div>
MediumSpringGreen
<div style='background:#00FA9A;width:4em;height:4em;'></div>
MediumTurquoise
<div style='background:#48D1CC;width:4em;height:4em;'></div>
MediumVioletRed
<div style='background:#C71585;width:4em;height:4em;'></div>
MidnightBlue
<div style='background:#191970;width:4em;height:4em;'></div>
MintCream
<div style='background:#F5FFFA;width:4em;height:4em;'></div>
MistyRose
<div style='background:#FFE4E1;width:4em;height:4em;'></div>
Moccasin
<div style='background:#FFE4B5;width:4em;height:4em;'></div>
NavajoWhite
<div style='background:#FFDEAD;width:4em;height:4em;'></div>
Navy
<div style='background:#000080;width:4em;height:4em;'></div>
OldLace
<div style='background:#FDF5E6;width:4em;height:4em;'></div>
Olive
<div style='background:#808000;width:4em;height:4em;'></div>
OliveDrab
<div style='background:#6B8E23;width:4em;height:4em;'></div>
Orange
<div style='background:#FFA500;width:4em;height:4em;'></div>
OrangeRed
<div style='background:#FF4500;width:4em;height:4em;'></div>
Orchid
<div style='background:#DA70D6;width:4em;height:4em;'></div>
PaleGoldenrod
<div style='background:#EEE8AA;width:4em;height:4em;'></div>
PaleGreen
<div style='background:#98FB98;width:4em;height:4em;'></div>
PaleTurquoise
<div style='background:#AFEEEE;width:4em;height:4em;'></div>
PaleVioletRed
<div style='background:#DB7093;width:4em;height:4em;'></div>
PapayaWhip
<div style='background:#FFEFD5;width:4em;height:4em;'></div>
PeachPuff
<div style='background:#FFDAB9;width:4em;height:4em;'></div>
Peru
<div style='background:#CD853F;width:4em;height:4em;'></div>
Pink
<div style='background:#FFC0CB;width:4em;height:4em;'></div>
Plaid
<div style='background:#CC5533;width:4em;height:4em;'></div>
Plum
<div style='background:#DDA0DD;width:4em;height:4em;'></div>
PowderBlue
<div style='background:#B0E0E6;width:4em;height:4em;'></div>
Purple
<div style='background:#800080;width:4em;height:4em;'></div>
Red
<div style='background:#FF0000;width:4em;height:4em;'></div>
RosyBrown
<div style='background:#BC8F8F;width:4em;height:4em;'></div>
RoyalBlue
<div style='background:#4169E1;width:4em;height:4em;'></div>
SaddleBrown
<div style='background:#8B4513;width:4em;height:4em;'></div>
Salmon
<div style='background:#FA8072;width:4em;height:4em;'></div>
SandyBrown
<div style='background:#F4A460;width:4em;height:4em;'></div>
SeaGreen
<div style='background:#2E8B57;width:4em;height:4em;'></div>
Seashell
<div style='background:#FFF5EE;width:4em;height:4em;'></div>
Sienna
<div style='background:#A0522D;width:4em;height:4em;'></div>
Silver
<div style='background:#C0C0C0;width:4em;height:4em;'></div>
SkyBlue
<div style='background:#87CEEB;width:4em;height:4em;'></div>
SlateBlue
<div style='background:#6A5ACD;width:4em;height:4em;'></div>
SlateGray
<div style='background:#708090;width:4em;height:4em;'></div>
SlateGrey
<div style='background:#708090;width:4em;height:4em;'></div>
Snow
<div style='background:#FFFAFA;width:4em;height:4em;'></div>
SpringGreen
<div style='background:#00FF7F;width:4em;height:4em;'></div>
SteelBlue
<div style='background:#4682B4;width:4em;height:4em;'></div>
Tan
<div style='background:#D2B48C;width:4em;height:4em;'></div>
Teal
<div style='background:#008080;width:4em;height:4em;'></div>
Thistle
<div style='background:#D8BFD8;width:4em;height:4em;'></div>
Tomato
<div style='background:#FF6347;width:4em;height:4em;'></div>
Turquoise
<div style='background:#40E0D0;width:4em;height:4em;'></div>
Violet
<div style='background:#EE82EE;width:4em;height:4em;'></div>
Wheat
<div style='background:#F5DEB3;width:4em;height:4em;'></div>
White
<div style='background:#FFFFFF;width:4em;height:4em;'></div>
WhiteSmoke
<div style='background:#F5F5F5;width:4em;height:4em;'></div>
Yellow
<div style='background:#FFFF00;width:4em;height:4em;'></div>
YellowGreen
<div style='background:#9ACD32;width:4em;height:4em;'></div>
FairyLight
<div style='background:#FFE42D;width:4em;height:4em;'></div>
FairyLightNCC
<div style='background:#FFE42D;width:4em;height:4em;'></div>
Definition at line 487 of file crgb.h.
                 {
        AliceBlue=0xF0F8FF,
        Amethyst=0x9966CC,
        AntiqueWhite=0xFAEBD7,
        Aqua=0x00FFFF,
        Aquamarine=0x7FFFD4,
        Azure=0xF0FFFF,
        Beige=0xF5F5DC,
        Bisque=0xFFE4C4,
        Black=0x000000,
        BlanchedAlmond=0xFFEBCD,
        Blue=0x0000FF,
        BlueViolet=0x8A2BE2,
        Brown=0xA52A2A,
        BurlyWood=0xDEB887,
        CadetBlue=0x5F9EA0,
        Chartreuse=0x7FFF00,
        Chocolate=0xD2691E,
        Coral=0xFF7F50,
        CornflowerBlue=0x6495ED,
        Cornsilk=0xFFF8DC,
        Crimson=0xDC143C,
        Cyan=0x00FFFF,
        DarkBlue=0x00008B,
        DarkCyan=0x008B8B,
        DarkGoldenrod=0xB8860B,
        DarkGray=0xA9A9A9,
        DarkGrey=0xA9A9A9,
        DarkGreen=0x006400,
        DarkKhaki=0xBDB76B,
        DarkMagenta=0x8B008B,
        DarkOliveGreen=0x556B2F,
        DarkOrange=0xFF8C00,
        DarkOrchid=0x9932CC,
        DarkRed=0x8B0000,
        DarkSalmon=0xE9967A,
        DarkSeaGreen=0x8FBC8F,
        DarkSlateBlue=0x483D8B,
        DarkSlateGray=0x2F4F4F,
        DarkSlateGrey=0x2F4F4F,
        DarkTurquoise=0x00CED1,
        DarkViolet=0x9400D3,
        DeepPink=0xFF1493,
        DeepSkyBlue=0x00BFFF,
        DimGray=0x696969,
        DimGrey=0x696969,
        DodgerBlue=0x1E90FF,
        FireBrick=0xB22222,
        FloralWhite=0xFFFAF0,
        ForestGreen=0x228B22,
        Fuchsia=0xFF00FF,
        Gainsboro=0xDCDCDC,
        GhostWhite=0xF8F8FF,
        Gold=0xFFD700,
        Goldenrod=0xDAA520,
        Gray=0x808080,
        Grey=0x808080,
        Green=0x008000,
        GreenYellow=0xADFF2F,
        Honeydew=0xF0FFF0,
        HotPink=0xFF69B4,
        IndianRed=0xCD5C5C,
        Indigo=0x4B0082,
        Ivory=0xFFFFF0,
        Khaki=0xF0E68C,
        Lavender=0xE6E6FA,
        LavenderBlush=0xFFF0F5,
        LawnGreen=0x7CFC00,
        LemonChiffon=0xFFFACD,
        LightBlue=0xADD8E6,
        LightCoral=0xF08080,
        LightCyan=0xE0FFFF,
        LightGoldenrodYellow=0xFAFAD2,
        LightGreen=0x90EE90,
        LightGrey=0xD3D3D3,
        LightPink=0xFFB6C1,
        LightSalmon=0xFFA07A,
        LightSeaGreen=0x20B2AA,
        LightSkyBlue=0x87CEFA,
        LightSlateGray=0x778899,
        LightSlateGrey=0x778899,
        LightSteelBlue=0xB0C4DE,
        LightYellow=0xFFFFE0,
        Lime=0x00FF00,
        LimeGreen=0x32CD32,
        Linen=0xFAF0E6,
        Magenta=0xFF00FF,
        Maroon=0x800000,
        MediumAquamarine=0x66CDAA,
        MediumBlue=0x0000CD,
        MediumOrchid=0xBA55D3,
        MediumPurple=0x9370DB,
        MediumSeaGreen=0x3CB371,
        MediumSlateBlue=0x7B68EE,
        MediumSpringGreen=0x00FA9A,
        MediumTurquoise=0x48D1CC,
        MediumVioletRed=0xC71585,
        MidnightBlue=0x191970,
        MintCream=0xF5FFFA,
        MistyRose=0xFFE4E1,
        Moccasin=0xFFE4B5,
        NavajoWhite=0xFFDEAD,
        Navy=0x000080,
        OldLace=0xFDF5E6,
        Olive=0x808000,
        OliveDrab=0x6B8E23,
        Orange=0xFFA500,
        OrangeRed=0xFF4500,
        Orchid=0xDA70D6,
        PaleGoldenrod=0xEEE8AA,
        PaleGreen=0x98FB98,
        PaleTurquoise=0xAFEEEE,
        PaleVioletRed=0xDB7093,
        PapayaWhip=0xFFEFD5,
        PeachPuff=0xFFDAB9,
        Peru=0xCD853F,
        Pink=0xFFC0CB,
        Plaid=0xCC5533,
        Plum=0xDDA0DD,
        PowderBlue=0xB0E0E6,
        Purple=0x800080,
        Red=0xFF0000,
        RosyBrown=0xBC8F8F,
        RoyalBlue=0x4169E1,
        SaddleBrown=0x8B4513,
        Salmon=0xFA8072,
        SandyBrown=0xF4A460,
        SeaGreen=0x2E8B57,
        Seashell=0xFFF5EE,
        Sienna=0xA0522D,
        Silver=0xC0C0C0,
        SkyBlue=0x87CEEB,
        SlateBlue=0x6A5ACD,
        SlateGray=0x708090,
        SlateGrey=0x708090,
        Snow=0xFFFAFA,
        SpringGreen=0x00FF7F,
        SteelBlue=0x4682B4,
        Tan=0xD2B48C,
        Teal=0x008080,
        Thistle=0xD8BFD8,
        Tomato=0xFF6347,
        Turquoise=0x40E0D0,
        Violet=0xEE82EE,
        Wheat=0xF5DEB3,
        White=0xFFFFFF,
        WhiteSmoke=0xF5F5F5,
        Yellow=0xFFFF00,
        YellowGreen=0x9ACD32,
        // LED RGB color that roughly approximates
        // the color of incandescent fairy lights,
        // assuming that you're using FastLED
        // color correction on your LEDs (recommended).
        FairyLight=0xFFE42D,
        // If you are using no color correction, use this
        FairyLightNCC=0xFF9D2A
    } HTMLColorCode;
Constructor & Destructor Documentation
CRGB() [1/7]
FASTLED_FORCE_INLINE CRGB::CRGB () default
Default constructor.
Warning
Default values are UNITIALIZED!
Referenced by blend(), computeAdjustment(), nscale8_constexpr(), and operator-().
CRGB() [2/7]
CRGB::CRGB (uint8_t ir, uint8_t ig, uint8_t ib) inline constexpr noexcept
Allow construction from red, green, and blue.
Parameters
ir input red value
ig input green value
ib input blue value
Definition at line 104 of file crgb.h.
        : r(ir), g(ig), b(ib)
    {
    }
CRGB() [3/7]
CRGB::CRGB (uint32_t colorcode) inline constexpr noexcept
Allow construction from 32-bit (really 24-bit) bit 0xRRGGBB color code.
Parameters
colorcode a packed 24 bit color code
Definition at line 111 of file crgb.h.
    : r((colorcode >> 16) & 0xFF), g((colorcode >> 8) & 0xFF), b((colorcode >> 0) & 0xFF)
    {
    }
CRGB() [4/7]
CRGB::CRGB (LEDColorCorrection colorcode) inline constexpr noexcept
Allow construction from a LEDColorCorrection enum.
Parameters
colorcode an LEDColorCorrect enumeration value
Definition at line 125 of file crgb.h.
    : r((colorcode >> 16) & 0xFF), g((colorcode >> 8) & 0xFF), b((colorcode >> 0) & 0xFF)
    {
    }
CRGB() [5/7]
CRGB::CRGB (ColorTemperature colorcode) inline constexpr noexcept
Allow construction from a ColorTemperature enum.
Parameters
colorcode an ColorTemperature enumeration value
Definition at line 132 of file crgb.h.
    : r((colorcode >> 16) & 0xFF), g((colorcode >> 8) & 0xFF), b((colorcode >> 0) & 0xFF)
    {
    }
CRGB() [6/7]
FASTLED_FORCE_INLINE CRGB::CRGB (const CRGB & rhs) default
Allow copy construction.
CRGB() [7/7]
FASTLED_FORCE_INLINE CRGB::CRGB (const CHSV & rhs) inline
Allow construction from a CHSV color.
Definition at line 141 of file crgb.h.
    {
        hsv2rgb_rainbow( rhs, *this);
    }
References hsv2rgb_rainbow().
Member Function Documentation
addToRGB()
FASTLED_FORCE_INLINE CRGB & CRGB::addToRGB (uint8_t d)
Add a constant to each channel, saturating at 0xFF.
Note
This is NOT an operator+= overload because the compiler can't usefully decide when it's being passed a 32-bit constant (e.g. CRGB::Red) and an 8-bit one (CRGB::Blue)
Definition at line 31 of file crgb.hpp.
{
    r = qadd8( r, d);
    g = qadd8( g, d);
    b = qadd8( b, d);
    return *this;
}
References qadd8().
Referenced by operator++().
as_uint32_t()
uint32_t CRGB::as_uint32_t () const inline constexpr noexcept
Definition at line 116 of file crgb.h.
{
        return uint32_t(0xff000000) |
               (uint32_t{r} << 16) |
               (uint32_t{g} << 8) |
               uint32_t{b};
    }
blend()
CRGB CRGB::blend (const CRGB & p1, const CRGB & p2, fract8 amountOfP2) static
Definition at line 50 of file crgb.cpp.
{
    return CRGB(
        blend8(p1.r, p2.r, amountOfP2),
        blend8(p1.g, p2.g, amountOfP2),
        blend8(p1.b, p2.b, amountOfP2)
    );
}
References CRGB(), and blend8().
Referenced by fl::FxCompositor::draw(), and fl::Frame::interpolate().
computeAdjustment()
CRGB CRGB::computeAdjustment (uint8_t scale, const CRGB & colorCorrection, const CRGB & colorTemperature) static
Calculates the combined color adjustment to the LEDs at a given scale, color correction, and color temperature.
Parameters
scale the scale value for the RGB data (i.e. brightness)
colorCorrection color correction to apply
colorTemperature color temperature to apply
Returns
a CRGB object representing the adjustment, including color correction and color temperature
Definition at line 25 of file crgb.cpp.
{
    #if defined(NO_CORRECTION) && (NO_CORRECTION==1)
            return CRGB(scale,scale,scale);
    #else
            CRGB adj(0,0,0);
            if(scale > 0) {
                for(uint8_t i = 0; i < 3; ++i) {
                    uint8_t cc = colorCorrection.raw[i];
                    uint8_t ct = colorTemperature.raw[i];
                    if(cc > 0 && ct > 0) {
                        // Optimized for AVR size. This function is only called very infrequently so size
                        // matters more than speed.
                        uint32_t work = (((uint16_t)cc)+1);
                        work *= (((uint16_t)ct)+1);
                        work *= scale;
                        work /= 0x10000L;
                        adj.raw[i] = work & 0xFF;
                    }
                }
            }
            return adj;
    #endif
}
References CRGB(), and scale.
Referenced by CLEDController::getAdjustment().
fadeLightBy()
FASTLED_FORCE_INLINE CRGB & CRGB::fadeLightBy (uint8_t fadefactor)
fadeLightBy is a synonym for nscale8_video(), as a fade instead of a scale
Parameters
fadefactor the amount to fade, sent to nscale8_video() as (255 - fadefactor)
Definition at line 90 of file crgb.hpp.
{
    nscale8x3_video( r, g, b, 255 - fadefactor);
    return *this;
}
References nscale8x3_video().
fadeToBlackBy()
CRGB & CRGB::fadeToBlackBy (uint8_t fadefactor) inline
fadeToBlackBy is a synonym for nscale8(), as a fade instead of a scale
Parameters
fadefactor the amount to fade, sent to nscale8() as (255 - fadefactor)
Examples
RGBSetDemo.ino.
Definition at line 146 of file crgb.hpp.
{
    nscale8x3( r, g, b, 255 - fadefactor);
    return *this;
}
References nscale8x3().
Referenced by loop().
getAverageLight()
FASTLED_FORCE_INLINE uint8_t CRGB::getAverageLight () const
Get the average of the R, G, and B values.
Examples
Pacifica.ino, and TwinkleFox.ino.
Definition at line 163 of file crgb.hpp.
{
#if FASTLED_SCALE8_FIXED == 1
    const uint8_t eightyfive = 85;
#else
    const uint8_t eightyfive = 86;
#endif
    uint8_t avg = scale8_LEAVING_R1_DIRTY( r, eightyfive) + \
    scale8_LEAVING_R1_DIRTY( g, eightyfive) + \
    scale8_LEAVING_R1_DIRTY( b, eightyfive);
    cleanup_R1();
    return avg;
}
References cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
Referenced by fl::TwinkleFox::drawTwinkleFox(), drawTwinkles(), fl::Pacifica::pacifica_add_whitecaps(), and pacifica_add_whitecaps().
getLuma()
FASTLED_FORCE_INLINE uint8_t CRGB::getLuma () const
Get the "luma" of a CRGB object.
In other words, roughly how much light the CRGB pixel is putting out (from 0 to 255).
Definition at line 152 of file crgb.hpp.
{
    //Y' = 0.2126 R' + 0.7152 G' + 0.0722 B'
    //     54            183       18 (!)
    uint8_t luma = scale8_LEAVING_R1_DIRTY( r, 54) + \
    scale8_LEAVING_R1_DIRTY( g, 183) + \
    scale8_LEAVING_R1_DIRTY( b, 18);
    cleanup_R1();
    return luma;
}
References cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
getParity()
FASTLED_FORCE_INLINE uint8_t CRGB::getParity () inline
Returns 0 or 1, depending on the lowest bit of the sum of the color components.
Definition at line 411 of file crgb.h.
    {
        uint8_t sum = r + g + b;
        return (sum & 0x01);
    }
Referenced by setParity().
lerp16()
FASTLED_FORCE_INLINE CRGB CRGB::lerp16 (const CRGB & other, fract16 frac) const
Return a new CRGB object after performing a linear interpolation between this object and the passed in object.
Definition at line 187 of file crgb.hpp.
{
    CRGB ret;
    ret.r = lerp16by16(r<<8,other.r<<8,frac)>>8;
    ret.g = lerp16by16(g<<8,other.g<<8,frac)>>8;
    ret.b = lerp16by16(b<<8,other.b<<8,frac)>>8;
    return ret;
}
References lerp16by16().
lerp8()
FASTLED_FORCE_INLINE CRGB CRGB::lerp8 (const CRGB & other, fract8 frac) const
Return a new CRGB object after performing a linear interpolation between this object and the passed in object.
Definition at line 176 of file crgb.hpp.
{
    CRGB ret;
    ret.r = lerp8by8(r,other.r,frac);
    ret.g = lerp8by8(g,other.g,frac);
    ret.b = lerp8by8(b,other.b,frac);
    return ret;
}
References lerp8by8().
maximizeBrightness()
FASTLED_FORCE_INLINE void CRGB::maximizeBrightness (uint8_t limit = 255) inline
Maximize the brightness of this CRGB object.
This makes the individual color channels as bright as possible while keeping the same value differences between channels.
Note
This does not keep the same ratios between channels, just the same difference in absolute values.
Definition at line 384 of file crgb.h.
{
        uint8_t max = red;
        if( green > max) max = green;
        if( blue > max) max = blue;
        // stop div/0 when color is black
        if(max > 0) {
            uint16_t factor = ((uint16_t)(limit) * 256) / max;
            red =   (red   * factor) / 256;
            green = (green * factor) / 256;
            blue =  (blue  * factor) / 256;
        }
    }
nscale8() [1/2]
FASTLED_FORCE_INLINE CRGB & CRGB::nscale8 (const CRGB & scaledown)
Scale down a RGB to N/256ths of its current brightness, using "plain math" dimming rules.
"Plain math" dimming rules means that the low light levels may dim all the way to 100% black.
See also
scale8
Definition at line 122 of file crgb.hpp.
{
    r = FUNCTION_SCALE8(r, scaledown.r);
    g = FUNCTION_SCALE8(g, scaledown.g);
    b = FUNCTION_SCALE8(b, scaledown.b);
    return *this;
}
References FUNCTION_SCALE8.
nscale8() [2/2]
CRGB & CRGB::nscale8 (uint8_t scaledown)
Scale down a RGB to N/256ths of its current brightness, using "plain math" dimming rules.
"Plain math" dimming rules means that the low light levels may dim all the way to 100% black.
See also
nscale8x3
Examples
Cylon.ino.
Definition at line 58 of file crgb.cpp.
{
    nscale8x3( r, g, b, scaledown);
    return *this;
}
References nscale8x3().
Referenced by blur1d(), blurColumns(), blurRows(), fl::Cylon::draw(), fadeall(), fill_2dnoise8(), Fire2023(), map_data_into_colors_through_palette(), and nscale8().
nscale8_constexpr()
CRGB CRGB::nscale8_constexpr (const CRGB scaledown) const constexpr
Definition at line 112 of file crgb.hpp.
{
    return CRGB(
        scale8_constexpr(r, scaledown.r),
        scale8_constexpr(g, scaledown.g),
        scale8_constexpr(b, scaledown.b)
    );
}
References CRGB(), and scale8_constexpr().
nscale8_video()
FASTLED_FORCE_INLINE CRGB & CRGB::nscale8_video (uint8_t scaledown)
Scale down a RGB to N/256ths of it's current brightness using "video" dimming rules.
"Video" dimming rules means that unless the scale factor is ZERO each channel is guaranteed NOT to dim down to zero. If it's already nonzero, it'll stay nonzero, even if that means the hue shifts a little at low brightness levels.
See also
nscale8x3_video
Examples
TwinkleFox.ino.
Definition at line 78 of file crgb.hpp.
{
    nscale8x3_video( r, g, b, scaledown);
    return *this;
}
References nscale8x3_video().
Referenced by fl::TwinkleFox::drawTwinkleFox(), drawTwinkles(), map_data_into_colors_through_palette(), nscale8_video(), and operator%().
operator bool()
CRGB::operator bool () const inline explicit constexpr
This allows testing a CRGB for zero-ness.
Definition at line 338 of file crgb.h.
    {
        return r || g || b;
    }
operator rgb24()
CRGB::operator rgb24 () const inline
Convert to an rgb24 object, used with the SmartMatrix library.
See also
https://github.com/pixelmatix/SmartMatrix
Definition at line 361 of file crgb.h.
{
        rgb24 ret;
        ret.red = r;
        ret.green = g;
        ret.blue = b;
        return ret;
    }
operator uint32_t()
CRGB::operator uint32_t () const inline explicit constexpr
Converts a CRGB to a 32-bit color having an alpha of 255.
Definition at line 344 of file crgb.h.
    {
        return uint32_t(0xff000000) |
               (uint32_t{r} << 16) |
               (uint32_t{g} << 8) |
               uint32_t{b};
    }
operator%=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator%= (uint8_t scaledown)
%= is a synonym for nscale8_video().
Think of it is scaling down by "a percentage"
Definition at line 84 of file crgb.hpp.
{
    nscale8x3_video( r, g, b, scaledown);
    return *this;
}
References nscale8x3_video().
operator&=() [1/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator&= (const CRGB & rhs) inline
"and" operator brings each channel down to the lower of the two values
Definition at line 320 of file crgb.h.
    {
        if( rhs.r < r) r = rhs.r;
        if( rhs.g < g) g = rhs.g;
        if( rhs.b < b) b = rhs.b;
        return *this;
    }
operator&=() [2/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator&= (uint8_t d) inline
"and" operator brings each channel down to the lower of the two values
Definition at line 329 of file crgb.h.
    {
        if( d < r) r = d;
        if( d < g) g = d;
        if( d < b) b = d;
        return *this;
    }
operator*=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator*= (uint8_t d)
Multiply each of the channels by a constant, saturating each channel at 0xFF.
Definition at line 70 of file crgb.hpp.
{
    r = qmul8( r, d);
    g = qmul8( g, d);
    b = qmul8( b, d);
    return *this;
}
References qmul8().
operator++() [1/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator++ ()
Add a constant of '1' from each channel, saturating at 0xFF.
Definition at line 48 of file crgb.hpp.
{
    addToRGB(1);
    return *this;
}
References addToRGB().
operator++() [2/2]
FASTLED_FORCE_INLINE CRGB CRGB::operator++ (int)
Add a constant of '1' from each channel, saturating at 0xFF.
Definition at line 55 of file crgb.hpp.
{
    CRGB retval(*this);
    ++(*this);
    return retval;
}
operator+=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator+= (const CRGB & rhs)
Add one CRGB to another, saturating at 0xFF for each channel.
Definition at line 23 of file crgb.hpp.
{
    r = qadd8( r, rhs.r);
    g = qadd8( g, rhs.g);
    b = qadd8( b, rhs.b);
    return *this;
}
References qadd8().
operator-()
CRGB CRGB::operator- () const inline constexpr
Invert each channel.
Definition at line 353 of file crgb.h.
    {
        return CRGB(255 - r, 255 - g, 255 - b);
    }
References CRGB().
operator--() [1/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator-- ()
Subtract a constant of '1' from each channel, saturating at 0x00.
Definition at line 97 of file crgb.hpp.
{
    subtractFromRGB(1);
    return *this;
}
References subtractFromRGB().
operator--() [2/2]
FASTLED_FORCE_INLINE CRGB CRGB::operator-- (int)
Subtract a constant of '1' from each channel, saturating at 0x00.
Definition at line 104 of file crgb.hpp.
{
    CRGB retval(*this);
    --(*this);
    return retval;
}
operator-=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator-= (const CRGB & rhs)
Subtract one CRGB from another, saturating at 0x00 for each channel.
Definition at line 39 of file crgb.hpp.
{
    r = qsub8( r, rhs.r);
    g = qsub8( g, rhs.g);
    b = qsub8( b, rhs.b);
    return *this;
}
References qsub8().
operator/=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator/= (uint8_t d) inline
Divide each of the channels by a constant.
Definition at line 239 of file crgb.h.
    {
        r /= d;
        g /= d;
        b /= d;
        return *this;
    }
operator=() [1/3]
FASTLED_FORCE_INLINE CRGB & CRGB::operator= (const CHSV & rhs) inline
Allow assignment from HSV color.
Definition at line 191 of file crgb.h.
    {
        hsv2rgb_rainbow( rhs, *this);
        return *this;
    }
References hsv2rgb_rainbow().
operator=() [2/3]
FASTLED_FORCE_INLINE CRGB & CRGB::operator= (const CRGB & rhs) default
Allow assignment from one RGB struct to another.
operator=() [3/3]
FASTLED_FORCE_INLINE CRGB & CRGB::operator= (const uint32_t colorcode) inline
Allow assignment from 32-bit (really 24-bit) 0xRRGGBB color code.
Parameters
colorcode a packed 24 bit color code
Definition at line 151 of file crgb.h.
    {
        r = (colorcode >> 16) & 0xFF;
        g = (colorcode >>  8) & 0xFF;
        b = (colorcode >>  0) & 0xFF;
        return *this;
    }
operator>>=()
FASTLED_FORCE_INLINE CRGB & CRGB::operator>>= (uint8_t d) inline
Right shift each of the channels by a constant.
Definition at line 248 of file crgb.h.
    {
        r >>= d;
        g >>= d;
        b >>= d;
        return *this;
    }
operator[]() [1/2]
FASTLED_FORCE_INLINE uint8_t & CRGB::operator[] (uint8_t x) inline
Array access operator to index into the CRGB object.
Parameters
x the index to retrieve (0-2)
Returns
the CRGB::raw value for the given index
Definition at line 83 of file crgb.h.
    {
        return raw[x];
    }
References x.
operator[]() [2/2]
FASTLED_FORCE_INLINE const uint8_t & CRGB::operator[] (uint8_t x) const inline
Array access operator to index into the CRGB object.
Parameters
x the index to retrieve (0-2)
Returns
the CRGB::raw value for the given index
Definition at line 91 of file crgb.h.
    {
        return raw[x];
    }
References x.
operator|=() [1/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator|= (const CRGB & rhs) inline
"or" operator brings each channel up to the higher of the two values
Definition at line 302 of file crgb.h.
    {
        if( rhs.r > r) r = rhs.r;
        if( rhs.g > g) g = rhs.g;
        if( rhs.b > b) b = rhs.b;
        return *this;
    }
operator|=() [2/2]
FASTLED_FORCE_INLINE CRGB & CRGB::operator|= (uint8_t d) inline
"or" operator brings each channel up to the higher of the two values
Definition at line 311 of file crgb.h.
    {
        if( d > r) r = d;
        if( d > g) g = d;
        if( d > b) b = d;
        return *this;
    }
scale8() [1/2]
FASTLED_FORCE_INLINE CRGB CRGB::scale8 (const CRGB & scaledown) const
Return a CRGB object that is a scaled down version of this object.
Definition at line 137 of file crgb.hpp.
{
    CRGB out;
    out.r = FUNCTION_SCALE8(r, scaledown.r);
    out.g = FUNCTION_SCALE8(g, scaledown.g);
    out.b = FUNCTION_SCALE8(b, scaledown.b);
    return out;
}
References FUNCTION_SCALE8.
scale8() [2/2]
FASTLED_FORCE_INLINE CRGB CRGB::scale8 (uint8_t scaledown) const
Return a CRGB object that is a scaled down version of this object.
Definition at line 130 of file crgb.hpp.
{
    CRGB out = *this;
    nscale8x3( out.r, out.g, out.b, scaledown);
    return out;
}
References nscale8x3().
setColorCode()
FASTLED_FORCE_INLINE CRGB & CRGB::setColorCode (uint32_t colorcode) inline
Allow assignment from 32-bit (really 24-bit) 0xRRGGBB color code.
Parameters
colorcode a packed 24 bit color code
Definition at line 199 of file crgb.h.
    {
        r = (colorcode >> 16) & 0xFF;
        g = (colorcode >>  8) & 0xFF;
        b = (colorcode >>  0) & 0xFF;
        return *this;
    }
setHSV()
FASTLED_FORCE_INLINE CRGB & CRGB::setHSV (uint8_t hue, uint8_t sat, uint8_t val) inline
Allow assignment from hue, saturation, and value.
Parameters
hue color hue
sat color saturation
val color value (brightness)
Definition at line 175 of file crgb.h.
    {
        hsv2rgb_rainbow( CHSV(hue, sat, val), *this);
        return *this;
    }
References hsv2rgb_rainbow().
setHue()
FASTLED_FORCE_INLINE CRGB & CRGB::setHue (uint8_t hue) inline
Allow assignment from just a hue.
Saturation and value (brightness) are set automatically to max.
Parameters
hue color hue
Definition at line 184 of file crgb.h.
    {
        hsv2rgb_rainbow( CHSV(hue, 255, 255), *this);
        return *this;
    }
References hsv2rgb_rainbow().
setParity()
FASTLED_FORCE_INLINE void CRGB::setParity (uint8_t parity) inline
Adjusts the color in the smallest way possible so that the parity of the coloris now the desired value.
This allows you to "hide" one bit of information in the color.
Ideally, we find one color channel which already has data in it, and modify just that channel by one. We don't want to light up a channel that's black if we can avoid it, and if the pixel is 'grayscale', (meaning that R==G==B), we modify all three channels at once, to preserve the neutral hue.
There's no such thing as a free lunch; in many cases this "hidden bit" may actually be visible, but this code makes reasonable efforts to hide it as much as is reasonably possible.
Also, an effort is made to make it such that repeatedly setting the parity to different values will not cause the color to "drift". Toggling the parity twice should generally result in the original color again.
Definition at line 439 of file crgb.h.
    {
        uint8_t curparity = getParity();
        if( parity == curparity) return;
        if( parity ) {
            // going 'up'
            if( (b > 0) && (b < 255)) {
                if( r == g && g == b) {
                    ++r;
                    ++g;
                }
                ++b;
            } else if( (r > 0) && (r < 255)) {
                ++r;
            } else if( (g > 0) && (g < 255)) {
                ++g;
            } else {
                if( r == g && g == b) {
                    r ^= 0x01;
                    g ^= 0x01;
                }
                b ^= 0x01;
            }
        } else {
            // going 'down'
            if( b > 1) {
                if( r == g && g == b) {
                    --r;
                    --g;
                }
                --b;
            } else if( g > 1) {
                --g;
            } else if( r > 1) {
                --r;
            } else {
                if( r == g && g == b) {
                    r ^= 0x01;
                    g ^= 0x01;
                }
                b ^= 0x01;
            }
        }
    }
References getParity().
setRGB()
FASTLED_FORCE_INLINE CRGB & CRGB::setRGB (uint8_t nr, uint8_t ng, uint8_t nb) inline
Allow assignment from red, green, and blue.
Parameters
nr new red value
ng new green value
nb new blue value
Definition at line 163 of file crgb.h.
    {
        r = nr;
        g = ng;
        b = nb;
        return *this;
    }
subtractFromRGB()
FASTLED_FORCE_INLINE CRGB & CRGB::subtractFromRGB (uint8_t d)
Subtract a constant from each channel, saturating at 0x00.
Note
This is NOT an operator+= overload because the compiler can't usefully decide when it's being passed a 32-bit constant (e.g. CRGB::Red) and an 8-bit one (CRGB::Blue)
Definition at line 62 of file crgb.hpp.
{
    r = qsub8( r, d);
    g = qsub8( g, d);
    b = qsub8( b, d);
    return *this;
}
References qsub8().
Referenced by operator--().
toString()
fl::Str CRGB::toString () const
Definition at line 13 of file crgb.cpp.
{
    fl::Str out;
    out.append("CRGB(");
    out.append(int16_t(r));
    out.append(",");
    out.append(int16_t(g));
    out.append(",");
    out.append(int16_t(b));
    out.append(")");
    return out;
}
References fl::Str::append().
Member Data Documentation
[union]
union { ... } CRGB
CRGB.__unnamed15__
union CRGB.__unnamed15__
Class Members
struct CRGB.__unnamed15__.__unnamed17__ __unnamed__
uint8_t raw[3] Access the red, green, and blue data as an array.
Where:
raw[0] is the red value
raw[1] is the green value
raw[2] is the blue value
CRGB.__unnamed15__.__unnamed17__
struct CRGB.__unnamed15__.__unnamed17__
Class Members
union CRGB.__unnamed15__.__unnamed17__.__unnamed19__ __unnamed__
union CRGB.__unnamed15__.__unnamed17__.__unnamed21__ __unnamed__
union CRGB.__unnamed15__.__unnamed17__.__unnamed23__ __unnamed__
CRGB.__unnamed15__.__unnamed17__.__unnamed19__
union CRGB.__unnamed15__.__unnamed17__.__unnamed19__
Class Members
uint8_t r Red channel value.
uint8_t red
CRGB.__unnamed15__.__unnamed17__.__unnamed21__
union CRGB.__unnamed15__.__unnamed17__.__unnamed21__
Class Members
uint8_t g Green channel value.
uint8_t green
CRGB.__unnamed15__.__unnamed17__.__unnamed23__
union CRGB.__unnamed15__.__unnamed17__.__unnamed23__
Class Members
uint8_t b Blue channel value.
uint8_t blue
Enumeration Type Documentation
HSVHue
enum HSVHue
Pre-defined hue values for CHSV objects.
Enumerator
HUE_RED
Red (0)
HUE_ORANGE
Orange (45)
HUE_YELLOW
Yellow (90)
HUE_GREEN
Green (135)
HUE_AQUA
Aqua (180)
HUE_BLUE
Blue (225)
HUE_PURPLE
Purple (270)
HUE_PINK
Pink (315)
Definition at line 97 of file chsv.h.
             {
    HUE_RED = 0,
    HUE_ORANGE = 32,
    HUE_YELLOW = 64,
    HUE_GREEN = 96,
    HUE_AQUA = 128,
    HUE_BLUE = 160,
    HUE_PURPLE = 192,
    HUE_PINK = 224
} HSVHue;
Function Documentation
hsv2rgb_rainbow()
void hsv2rgb_rainbow (const struct CHSV & hsv, struct CRGB & rgb)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
Convert an HSV value to RGB using a visually balanced rainbow. This "rainbow" yields better yellow and orange than a straight mathematical "spectrum".
Parameters
hsv CHSV struct to convert to RGB. Max hue supported is HUE_MAX_RAINBOW
rgb CRGB struct to store the result of the conversion (will be modified)
Referenced by CRGB::CRGB(), CRGB::operator=(), CRGB::setHSV(), and CRGB::setHue().
operator!=() [1/2]
FASTLED_FORCE_INLINE bool operator!= (const CHSV & lhs, const CHSV & rhs)
Check if two CHSV objects do not have the same color data.
Definition at line 669 of file crgb.h.
{
    return !(lhs == rhs);
}
operator!=() [2/2]
FASTLED_FORCE_INLINE bool operator!= (const CRGB & lhs, const CRGB & rhs)
Check if two CRGB objects do not have the same color data.
Definition at line 657 of file crgb.h.
{
    return !(lhs == rhs);
}
operator%()
FASTLED_FORCE_INLINE CRGB operator% (const CRGB & p1, uint8_t d)
Scale using CRGB::nscale8_video()
Definition at line 224 of file crgb.hpp.
{
    CRGB retval( p1);
    retval.nscale8_video( d);
    return retval;
}
References CRGB::nscale8_video().
operator&()
FASTLED_FORCE_INLINE CRGB operator& (const CRGB & p1, const CRGB & p2)
Combine two CRGB objects, taking the smallest value of each channel.
Definition at line 720 of file crgb.h.
{
    return CRGB( p1.r < p2.r ? p1.r : p2.r,
                 p1.g < p2.g ? p1.g : p2.g,
                 p1.b < p2.b ? p1.b : p2.b);
}
operator*()
FASTLED_FORCE_INLINE CRGB operator* (const CRGB & p1, uint8_t d)
Multiply each of the channels by a constant, saturating each channel at 0xFF.
Definition at line 216 of file crgb.hpp.
{
    return CRGB( qmul8( p1.r, d),
                 qmul8( p1.g, d),
                 qmul8( p1.b, d));
}
References qmul8().
operator+()
FASTLED_FORCE_INLINE CRGB operator+ (const CRGB & p1, const CRGB & p2)
Add one CRGB to another, saturating at 0xFF for each channel.
Definition at line 200 of file crgb.hpp.
{
    return CRGB( qadd8( p1.r, p2.r),
                 qadd8( p1.g, p2.g),
                 qadd8( p1.b, p2.b));
}
References qadd8().
operator-()
FASTLED_FORCE_INLINE CRGB operator- (const CRGB & p1, const CRGB & p2)
Subtract one CRGB from another, saturating at 0x00 for each channel.
Definition at line 208 of file crgb.hpp.
{
    return CRGB( qsub8( p1.r, p2.r),
                 qsub8( p1.g, p2.g),
                 qsub8( p1.b, p2.b));
}
References qsub8().
operator/()
FASTLED_FORCE_INLINE CRGB operator/ (const CRGB & p1, uint8_t d)
Divide each of the channels by a constant.
Definition at line 713 of file crgb.h.
{
    return CRGB( p1.r/d, p1.g/d, p1.b/d);
}
operator<()
FASTLED_FORCE_INLINE bool operator< (const CRGB & lhs, const CRGB & rhs)
Check if the sum of the color channels in one CRGB object is less than another.
Definition at line 675 of file crgb.h.
{
    uint16_t sl, sr;
    sl = lhs.r + lhs.g + lhs.b;
    sr = rhs.r + rhs.g + rhs.b;
    return sl < sr;
}
operator<=()
FASTLED_FORCE_INLINE bool operator<= (const CRGB & lhs, const CRGB & rhs)
Check if the sum of the color channels in one CRGB object is less than or equal to another.
Definition at line 702 of file crgb.h.
{
    uint16_t sl, sr;
    sl = lhs.r + lhs.g + lhs.b;
    sr = rhs.r + rhs.g + rhs.b;
    return sl <= sr;
}
operator==() [1/2]
FASTLED_FORCE_INLINE bool operator== (const CHSV & lhs, const CHSV & rhs)
Check if two CHSV objects have the same color data.
Definition at line 663 of file crgb.h.
{
    return (lhs.h == rhs.h) && (lhs.s == rhs.s) && (lhs.v == rhs.v);
}
operator==() [2/2]
FASTLED_FORCE_INLINE bool operator== (const CRGB & lhs, const CRGB & rhs)
Check if two CRGB objects have the same color data.
Definition at line 651 of file crgb.h.
{
    return (lhs.r == rhs.r) && (lhs.g == rhs.g) && (lhs.b == rhs.b);
}
operator>()
FASTLED_FORCE_INLINE bool operator> (const CRGB & lhs, const CRGB & rhs)
Check if the sum of the color channels in one CRGB object is greater than another.
Definition at line 684 of file crgb.h.
{
    uint16_t sl, sr;
    sl = lhs.r + lhs.g + lhs.b;
    sr = rhs.r + rhs.g + rhs.b;
    return sl > sr;
}
operator>=()
FASTLED_FORCE_INLINE bool operator>= (const CRGB & lhs, const CRGB & rhs)
Check if the sum of the color channels in one CRGB object is greater than or equal to another.
Definition at line 693 of file crgb.h.
{
    uint16_t sl, sr;
    sl = lhs.r + lhs.g + lhs.b;
    sr = rhs.r + rhs.g + rhs.b;
    return sl >= sr;
}
operator|()
FASTLED_FORCE_INLINE CRGB operator| (const CRGB & p1, const CRGB & p2)
Combine two CRGB objects, taking the largest value of each channel.
Definition at line 728 of file crgb.h.
{
    return CRGB( p1.r > p2.r ? p1.r : p2.r,
                 p1.g > p2.g ? p1.g : p2.g,
                 p1.b > p2.b ? p1.b : p2.b);
}