FastLED: Color3i Struct Reference
Color3i Struct Reference
Detailed Description
Definition at line 8 of file color.h.
#include <color.h>
Public Member Functions
Color3i ()
Color3i (const Color3i &other)
Color3i (uint8_t r, uint8_t g, uint8_t b)
void Add (const Color3i &color)
uint8_t * At (int rgb_index)
const uint8_t * At (int rgb_index) const
void Fill (uint8_t val)
uint8_t Get (int rgb_index) const
void Interpolate (const Color3i &other_color, float t)
uint8_t MaxRGB () const
void Mul (const Color3i &other_color)
void Mul (uint8_t val)
void Mulf (float scale)
template<typename PrintStream >
void Print (PrintStream *stream) const
void Set (const Color3i &c)
void Set (int rgb_index, uint8_t val)
void Set (uint8_t r, uint8_t g, uint8_t b)
void Sub (const Color3i &color)
Static Public Member Functions
static Color3i Black ()
static Color3i Blue ()
static Color3i Cyan ()
static Color3i Green ()
static Color3i Orange ()
static Color3i Red ()
static Color3i White ()
static Color3i Yellow ()
Public Attributes
uint8_t b_
uint8_t g_
uint8_t r_
Constructor & Destructor Documentation
Color3i() [1/3]
Color3i::Color3i (uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 17 of file color.h.
{ Set(r,g,b); }
References Set().
Color3i() [2/3]
Color3i::Color3i () inline
Definition at line 18 of file color.h.
{ Set(0xff, 0xff, 0xff); }
References Set().
Referenced by Black(), Blue(), Cyan(), Green(), Mul(), Orange(), Red(), White(), and Yellow().
Color3i() [3/3]
Color3i::Color3i (const Color3i & other) inline
Definition at line 19 of file color.h.
{ Set(other); }
References Set().
Member Function Documentation
Add()
void Color3i::Add (const Color3i & color)
Definition at line 43 of file color.cpp.
{
  if ((255 - r_) < color.r_) r_ = 255;
  else                       r_ += color.r_;
  if ((255 - g_) < color.g_) g_ = 255;
  else                       g_ += color.g_;
  if ((255 - b_) < color.b_) b_ = 255;
  else                       b_ += color.b_;
}
References b_, g_, and r_.
Referenced by FrameBufferBase::ApplyBlendAdd(), and Interpolate().
At() [1/2]
uint8_t * Color3i::At (int rgb_index)
Definition at line 81 of file color.cpp.
{
  switch(rgb_index) {
    case 0: return &r_;
    case 1: return &g_;
    case 2: return &b_;
  }
  return NULL;
}
References b_, g_, and r_.
Referenced by Get(), and Set().
At() [2/2]
const uint8_t * Color3i::At (int rgb_index) const
Definition at line 91 of file color.cpp.
{
  switch(rgb_index) {
    case 0: return &r_;
    case 1: return &g_;
    case 2: return &b_;
  }
  return NULL;
}
References b_, g_, and r_.
Black()
static Color3i Color3i::Black () inline static
Definition at line 9 of file color.h.
{ return Color3i(0x0, 0x0, 0x0); }
References Color3i().
Referenced by Painter::PaintVuMidNotesFade(), Painter::PaintVuNotes(), Painter::PaintVuSpaceInvaders(), and Painter::VegasVisualizer().
Blue()
static Color3i Color3i::Blue () inline static
Definition at line 16 of file color.h.
{ return Color3i(0x00, 0x00, 0xff); }
References Color3i().
Cyan()
static Color3i Color3i::Cyan () inline static
Definition at line 15 of file color.h.
{ return Color3i(0x00, 0xff, 0xff); }
References Color3i().
Fill()
void Color3i::Fill (uint8_t val) inline
Definition at line 32 of file color.h.
{ Set(val, val, val); }
References Set().
Get()
uint8_t Color3i::Get (int rgb_index) const
Definition at line 53 of file color.cpp.
{
  const uint8_t* rgb = At(rgb_index);
  return rgb ? *rgb : 0;
}
References At().
Green()
static Color3i Color3i::Green () inline static
Definition at line 14 of file color.h.
{ return Color3i(0x00, 0xff, 0x00); }
References Color3i().
Interpolate()
void Color3i::Interpolate (const Color3i & other_color, float t)
Definition at line 67 of file color.cpp.
{
  if (0.0f >= t) {
    Set(other_color);
  } else if (1.0f <= t) {
    return;
  }
  Color3i new_color = other_color;
  new_color.Mul(1.0f - t);
  this->Mul(t);
  this->Add(new_color);
}
References Add(), Mul(), and Set().
MaxRGB()
uint8_t Color3i::MaxRGB () const inline
Definition at line 33 of file color.h.
{
    uint8_t max_r_g = r_ > g_ ? r_ : g_;
    return max_r_g > b_ ? max_r_g : b_;
  }
References b_, g_, and r_.
Mul() [1/2]
void Color3i::Mul (const Color3i & other_color)
Definition at line 10 of file color.cpp.
{
  int r = r_;
  int g = g_;
  int b = b_;
  r = r * int(other_color.r_) / 255;
  g = g * int(other_color.g_) / 255;
  b = b * int(other_color.b_) / 255;
  Set(r, g, b);
}
References b_, g_, r_, and Set().
Referenced by FrameBufferBase::ApplyBlendMultiply(), Interpolate(), and Mul().
Mul() [2/2]
void Color3i::Mul (uint8_t val) inline
Definition at line 25 of file color.h.
{
    Mul(Color3i(val, val, val));
  }
References Color3i(), and Mul().
Mulf()
void Color3i::Mulf (float scale)
Definition at line 22 of file color.cpp.
{
  const int s = static_cast<int>(scale * 255.0f);
  int r = static_cast<int>(r_) * s / 255;
  int g = static_cast<int>(g_) * s / 255;
  int b = static_cast<int>(b_) * s / 255;
  Set(r, g, b);
}
References b_, g_, r_, scale, and Set().
Orange()
static Color3i Color3i::Orange () inline static
Definition at line 12 of file color.h.
{ return Color3i(0xff, 0xff / 2,00); }
References Color3i().
Print()
template<typename PrintStream > void Color3i::Print (PrintStream * stream) const inline
Definition at line 39 of file color.h.
{
      stream->print("RGB:\t");
    stream->print(r_); stream->print(",\t");
    stream->print(g_); stream->print(",\t");
    stream->print(b_);
    stream->print("\n");
  }
References b_, g_, and r_.
Red()
static Color3i Color3i::Red () inline static
Definition at line 11 of file color.h.
{ return Color3i(0xff, 0x00, 0x00); }
References Color3i().
Set() [1/3]
void Color3i::Set (const Color3i & c) inline
Definition at line 22 of file color.h.
{ Set(c.r_, c.g_, c.b_); }
References b_, g_, r_, and Set().
Referenced by Set().
Set() [2/3]
void Color3i::Set (int rgb_index, uint8_t val)
Definition at line 59 of file color.cpp.
{
  uint8_t* rgb = At(rgb_index);
  if (rgb) {
    *rgb = val;
  }
}
References At().
Set() [3/3]
void Color3i::Set (uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 21 of file color.h.
{ r_ = r; g_ = g; b_ = b; }
References b_, g_, and r_.
Referenced by Color3i(), Color3i(), Color3i(), Fill(), Interpolate(), Mul(), and Mulf().
Sub()
void Color3i::Sub (const Color3i & color)
Definition at line 33 of file color.cpp.
{
  if (r_ < color.r_) r_ = 0;
  else               r_ -= color.r_;
  if (g_ < color.g_) g_ = 0;
  else               g_ -= color.g_;
  if (b_ < color.b_) b_ = 0;
  else               b_ -= color.b_;
}
References b_, g_, and r_.
Referenced by FrameBufferBase::ApplyBlendSubtract().
White()
static Color3i Color3i::White () inline static
Definition at line 10 of file color.h.
{ return Color3i(0xff, 0xff, 0xff); }
References Color3i().
Yellow()
static Color3i Color3i::Yellow () inline static
Definition at line 13 of file color.h.
{ return Color3i(0xff, 0xff,00); }
References Color3i().
Member Data Documentation
b_
uint8_t Color3i::b_
Definition at line 52 of file color.h.
Referenced by Add(), At(), At(), LedRopeTCL::DrawRepeat(), ColorHSV::FromRGB(), MaxRGB(), Mul(), Mulf(), Painter::PaintBrightSurprise(), Print(), LedRopeTCL::RawDrawPixel(), Set(), Set(), and Sub().
g_
uint8_t Color3i::g_
Definition at line 52 of file color.h.
Referenced by Add(), At(), At(), LedRopeTCL::DrawRepeat(), ColorHSV::FromRGB(), MaxRGB(), Mul(), Mulf(), Painter::PaintBrightSurprise(), Print(), LedRopeTCL::RawDrawPixel(), Set(), Set(), and Sub().
r_
uint8_t Color3i::r_
Definition at line 52 of file color.h.
Referenced by Add(), At(), At(), LedRopeTCL::DrawRepeat(), ColorHSV::FromRGB(), MaxRGB(), Mul(), Mulf(), Painter::PaintBrightSurprise(), Print(), LedRopeTCL::RawDrawPixel(), Set(), Set(), and Sub().
The documentation for this struct was generated from the following files:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/color.h
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/shared/color.cpp