FastLED: /home/runner/work/FastLED/FastLED/examples/FxAnimartrix/FxAnimartrix.ino File Reference
FxAnimartrix.ino File Reference
#include <stdio.h>
#include <string>
#include <FastLED.h>
#include "fl/json.h"
#include "fl/slice.h"
#include "fx/fx_engine.h"
#include "fx/2d/animartrix.hpp"
#include "fl/ui.h"
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define FIRST_ANIMATION POLAR_WAVES
#define LED_PIN 3
#define MATRIX_HEIGHT 22
#define MATRIX_WIDTH 22
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Functions
void loop ()
void setup ()
Variables
Animartrix animartrix (xyMap, FIRST_ANIMATION)
UISlider brightness ("Brightness", 255, 0, 255)
UIDescription description ("Demo of the Animatrix effects. @author of fx is StefanPetrick")
FxEngine fxEngine (NUM_LEDS)
UINumberField fxIndex ("Animartrix - index", 0, 0, NUM_ANIMATIONS - 1)
CRGB leds [NUM_LEDS]
UISlider timeSpeed ("Time Speed", 1, -10, 10,.1)
UITitle title ("Animartrix")
XYMap xyMap = XYMap::constructRectangularGrid(MATRIX_WIDTH, MATRIX_HEIGHT)
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 27 of file FxAnimartrix.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 28 of file FxAnimartrix.ino.
Referenced by setup().
FIRST_ANIMATION
#define FIRST_ANIMATION POLAR_WAVES
Definition at line 35 of file FxAnimartrix.ino.
LED_PIN
#define LED_PIN 3
Definition at line 26 of file FxAnimartrix.ino.
Referenced by setup().
MATRIX_HEIGHT
#define MATRIX_HEIGHT 22
Examples
FxEngine.ino.
Definition at line 31 of file FxAnimartrix.ino.
MATRIX_WIDTH
#define MATRIX_WIDTH 22
Examples
FxEngine.ino.
Definition at line 30 of file FxAnimartrix.ino.
NUM_LEDS
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Definition at line 33 of file FxAnimartrix.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 60 of file FxAnimartrix.ino.
            {
    FastLED.setBrightness(brightness);
    fxEngine.setSpeed(timeSpeed);
    static int lastFxIndex = -1;
    if (fxIndex.value() != lastFxIndex) {
        lastFxIndex = fxIndex;
        animartrix.fxSet(fxIndex);
    }
    fxEngine.draw(millis(), leds);
    FastLED.show();
}
References animartrix, brightness, fl::FxEngine::draw(), FastLED, fxEngine, fxIndex, fl::Animartrix::fxSet(), leds, CFastLED::setBrightness(), fl::FxEngine::setSpeed(), CFastLED::show(), timeSpeed, and fl::UINumberField::value().
setup()
void setup ()
Definition at line 52 of file FxAnimartrix.ino.
             {
    FastLED.addLeds<WS2811, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setCorrection(TypicalLEDStrip)
        .setScreenMap(xyMap);
    FastLED.setBrightness(brightness);
    fxEngine.addFx(animartrix);
}
References fl::FxEngine::addFx(), CFastLED::addLeds(), animartrix, brightness, COLOR_ORDER, FastLED, fxEngine, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), TypicalLEDStrip, and xyMap.
Variable Documentation
animartrix
Animartrix animartrix(xyMap, FIRST_ANIMATION) (xyMap , FIRST_ANIMATION)
Referenced by loop(), and setup().
brightness
UISlider brightness("Brightness", 255, 0, 255) ("Brightness" , 255 , 0 , 255)
Examples
ColorPalette.ino.
Referenced by applyGamma_video(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callShow(), WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callShow(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), fill_palette(), fill_palette_circular(), FillLEDsFromPaletteColors(), fl::five_bit_bitshift(), CLEDController::getAdjustmentData(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), KeyboardState::HandleNoteOn(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), loop(), map_data_into_colors_through_palette(), MyColorFromPaletteExtended(), SelectColor(), setup(), CPixelLEDController< RGB_ORDER, LANES, MASK >::show(), CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor(), CLEDController::showColorInternal(), CLEDController::showColorInternal(), CLEDController::showInternal(), CLEDController::showLeds(), CLEDController::showLedsInternal(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().
description
UIDescription description("Demo of the Animatrix effects. @author of fx is StefanPetrick") ("Demo of the Animatrix effects. @author of fx is StefanPetrick")
fxEngine
FxEngine fxEngine(NUM_LEDS) (NUM_LEDS)
Examples
FxEngine.ino.
Referenced by loop(), and setup().
fxIndex
UINumberField fxIndex("Animartrix - index", 0, 0, NUM_ANIMATIONS - 1) ("Animartrix - index" , 0 , 0 , NUM_ANIMATIONS - 1)
Referenced by loop().
leds
CRGB leds[NUM_LEDS]
Definition at line 38 of file FxAnimartrix.ino.
Referenced by loop(), and setup().
timeSpeed
UISlider timeSpeed("Time Speed", 1, -10, 10,.1) ("Time Speed" , 1 , - 10, 10 , . 1)
Referenced by loop().
title
UITitle title("Animartrix") ("Animartrix")
xyMap
XYMap xyMap = XYMap::constructRectangularGrid(MATRIX_WIDTH, MATRIX_HEIGHT)
Examples
FxEngine.ino.
Definition at line 39 of file FxAnimartrix.ino.
Referenced by fl::NoisePalette::NoisePalette(), fl::bilinearExpand(), fl::bilinearExpandArbitrary(), fl::bilinearExpandArbitraryFloat(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), blurColumns(), blurRows(), fl::FastLEDANIMartRIX::setPixelColor(), setup(), and fl::Fx2d::setXYMap().