FastLED: fl::NoisePalette Class Reference
fl::NoisePalette Class Reference
Detailed Description
Examples
FxEngine.ino.
Definition at line 21 of file noisepalette.h.
#include <noisepalette.h>
Public Member Functions
NoisePalette (XYMap xyMap, float fps=60.f)
uint8_t changeToRandomPalette ()
void draw (DrawContext context) override
Str fxName () const override
uint8_t getPalettePreset () const
uint8_t getPalettePresetCount () const
bool hasFixedFrameRate (float *fps) const override
void mapNoiseToLEDsUsingPalette (CRGB *leds)
void setPalette (const CRGBPalette16 &palette, uint16_t speed, uint16_t scale, bool colorLoop)
void setPalettePreset (int paletteIndex)
void setScale (uint16_t scale)
void setSpeed (uint16_t speed)
Public Member Functions inherited from fl::Fx2d
Fx2d (const XYMap &xyMap)
uint16_t getHeight () const
uint16_t getWidth () const
XYMap & getXYMap ()
const XYMap & getXYMap () const
void setXYMap (const XYMap &xyMap)
uint16_t xyMap (uint16_t x, uint16_t y) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Member Functions
void fillnoise8 ()
void SetupBlackAndWhiteStripedPalette ()
void SetupPurpleAndGreenPalette ()
void SetupRandomPalette ()
uint16_t XY (uint8_t x, uint8_t y) const
Private Attributes
bool colorLoop = 0
CRGBPalette16 currentPalette
int currentPaletteIndex = 0
uint16_t height
float mFps = 60.f
uint16_t mX
uint16_t mY
uint16_t mZ
fl::scoped_array< uint8_t > noise
uint16_t scale = 0
uint16_t speed = 0
uint16_t width
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx2d
XYMap mXyMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
NoisePalette()
fl::NoisePalette::NoisePalette (XYMap xyMap, float fps = 60.f)
Definition at line 19 of file noisepalette.cpp.
    : Fx2d(xyMap), speed(0), scale(0), colorLoop(1), mFps(fps) {
    // currentPalette = PartyColors_p;
    static_assert(sizeof(currentPalette) == sizeof(CRGBPalette16),
                  "Palette size mismatch");
    currentPalette = PartyColors_p;
    width = xyMap.getWidth();
    height = xyMap.getHeight();
    // Initialize our coordinates to some random values
    mX = random16();
    mY = random16();
    mZ = random16();
    setPalettePreset(0);
    // Allocate memory for the noise array using scoped_ptr
    noise = scoped_array<uint8_t>(new uint8_t[width * height]);
}
References currentPalette, height, mX, mY, mZ, noise, PartyColors_p, random16(), setPalettePreset(), width, and xyMap.
Member Function Documentation
changeToRandomPalette()
uint8_t fl::NoisePalette::changeToRandomPalette ()
Definition at line 184 of file noisepalette.cpp.
{
    while (true) {
        uint8_t new_idx = random8() % 12;
        if (new_idx == currentPaletteIndex) {
            continue;
        }
        currentPaletteIndex = new_idx;
        setPalettePreset(currentPaletteIndex);
        return currentPaletteIndex;
    }
}
References currentPaletteIndex, random8(), and setPalettePreset().
Referenced by loop().
draw()
void fl::NoisePalette::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 33 of file noisepalette.h.
{
        fillnoise8();
        mapNoiseToLEDsUsingPalette(context.leds);
    }
References fillnoise8(), fl::_DrawContext::leds, and mapNoiseToLEDsUsingPalette().
Referenced by loop().
fillnoise8()
void fl::NoisePalette::fillnoise8 () private
Definition at line 142 of file noisepalette.cpp.
{
    // If we're running at a low "speed", some 8-bit artifacts become
    // visible from frame-to-frame.  In order to reduce this, we can do some
    // fast data-smoothing. The amount of data smoothing we're doing depends
    // on "speed".
    uint8_t dataSmoothing = 0;
    if (speed < 50) {
        dataSmoothing = 200 - (speed * 4);
    }
    for (uint16_t i = 0; i < width; i++) {
        int ioffset = scale * i;
        for (uint16_t j = 0; j < height; j++) {
            int joffset = scale * j;
            uint8_t data = inoise8(mX + ioffset, mY + joffset, mZ);
            // The range of the inoise8 function is roughly 16-238.
            // These two operations expand those values out to roughly
            // 0..255 You can comment them out if you want the raw noise
            // data.
            data = qsub8(data, 16);
            data = qadd8(data, scale8(data, 39));
            if (dataSmoothing) {
                uint8_t olddata = noise.get()[i * height + j];
                uint8_t newdata = scale8(olddata, dataSmoothing) +
                                  scale8(data, 256 - dataSmoothing);
                data = newdata;
            }
            noise.get()[i * height + j] = data;
        }
    }
    mZ += speed;
    // apply slow drift to X and Y, just for visual variation.
    mX += speed / 8;
    mY -= speed / 16;
}
References fl::scoped_array< T, Deleter >::get(), height, inoise8(), mX, mY, mZ, noise, qadd8(), qsub8(), scale, scale8(), speed, and width.
Referenced by draw().
fxName()
Str fl::NoisePalette::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 38 of file noisepalette.h.
{ return "NoisePalette"; }
getPalettePreset()
uint8_t fl::NoisePalette::getPalettePreset () const inline
Definition at line 46 of file noisepalette.h.
{ return currentPaletteIndex; }
References currentPaletteIndex.
getPalettePresetCount()
uint8_t fl::NoisePalette::getPalettePresetCount () const inline
Definition at line 45 of file noisepalette.h.
{ return 12; }
hasFixedFrameRate()
bool fl::NoisePalette::hasFixedFrameRate (float * fps) const inline override virtual
Reimplemented from fl::Fx.
Definition at line 26 of file noisepalette.h.
{
        *fps = mFps;
        return true;
    }
References mFps.
mapNoiseToLEDsUsingPalette()
void fl::NoisePalette::mapNoiseToLEDsUsingPalette (CRGB * leds)
Definition at line 109 of file noisepalette.cpp.
{
    static uint8_t ihue = 0;
    for (uint16_t i = 0; i < width; i++) {
        for (uint16_t j = 0; j < height; j++) {
            // We use the value at the (i,j) coordinate in the noise
            // array for our brightness, and the flipped value from (j,i)
            // for our pixel's index into the color palette.
            uint8_t index = noise.get()[i * height + j];
            uint8_t bri = noise.get()[j * width + i];
            // if this palette is a 'loop', add a slowly-changing base value
            if (colorLoop) {
                index += ihue;
            }
            // brighten up, as the color palette itself often contains the
            // light/dark dynamic range desired
            if (bri > 127) {
                bri = 255;
            } else {
                bri = dim8_raw(bri * 2);
            }
            CRGB color = ColorFromPalette(currentPalette, index, bri);
            leds[XY(i, j)] = color;
        }
    }
    ihue += 1;
}
References ColorFromPalette(), colorLoop, currentPalette, dim8_raw(), fl::scoped_array< T, Deleter >::get(), height, leds, noise, width, and XY().
setPalette()
void fl::NoisePalette::setPalette (const CRGBPalette16 & palette, uint16_t speed, uint16_t scale, bool colorLoop) inline
Definition at line 48 of file noisepalette.h.
{
        currentPalette = palette;
        this->speed = speed;
        this->scale = scale;
        this->colorLoop = colorLoop;
    }
References colorLoop, currentPalette, scale, and speed.
setPalettePreset()
void fl::NoisePalette::setPalettePreset (int paletteIndex)
Definition at line 39 of file noisepalette.cpp.
{
    currentPaletteIndex = paletteIndex % 12; // Ensure the index wraps around
    switch (currentPaletteIndex) {
    case 0:
        currentPalette = RainbowColors_p;
        speed = 20;
        scale = 30;
        colorLoop = 1;
        break;
    case 1:
        SetupPurpleAndGreenPalette();
        speed = 10;
        scale = 50;
        colorLoop = 1;
        break;
    case 2:
        SetupBlackAndWhiteStripedPalette();
        speed = 20;
        scale = 30;
        colorLoop = 1;
        break;
    case 3:
        currentPalette = ForestColors_p;
        speed = 8;
        scale = 120;
        colorLoop = 0;
        break;
    case 4:
        currentPalette = CloudColors_p;
        speed = 4;
        scale = 30;
        colorLoop = 0;
        break;
    case 5:
        currentPalette = LavaColors_p;
        speed = 8;
        scale = 50;
        colorLoop = 0;
        break;
    case 6:
        currentPalette = OceanColors_p;
        speed = 20;
        scale = 90;
        colorLoop = 0;
        break;
    case 7:
        currentPalette = PartyColors_p;
        speed = 20;
        scale = 30;
        colorLoop = 1;
        break;
    case 8:
    case 9:
    case 10:
        SetupRandomPalette();
        speed = 20 + (currentPaletteIndex - 8) * 5;
        scale = 20 + (currentPaletteIndex - 8) * 5;
        colorLoop = 1;
        break;
    case 11:
        currentPalette = RainbowStripeColors_p;
        speed = 2;
        scale = 20;
        colorLoop = 1;
        break;
    default:
        break;
    }
}
References CloudColors_p, colorLoop, currentPalette, currentPaletteIndex, ForestColors_p, LavaColors_p, OceanColors_p, PartyColors_p, RainbowColors_p, RainbowStripeColors_p, scale, SetupBlackAndWhiteStripedPalette(), SetupPurpleAndGreenPalette(), SetupRandomPalette(), and speed.
Referenced by NoisePalette(), changeToRandomPalette(), and setup().
setScale()
void fl::NoisePalette::setScale (uint16_t scale) inline
Definition at line 56 of file noisepalette.h.
{ this->scale = scale; }
References scale.
Referenced by loop(), and setup().
setSpeed()
void fl::NoisePalette::setSpeed (uint16_t speed) inline
Definition at line 55 of file noisepalette.h.
{ this->speed = speed; }
References speed.
Referenced by loop(), and setup().
SetupBlackAndWhiteStripedPalette()
void fl::NoisePalette::SetupBlackAndWhiteStripedPalette () inline private
Definition at line 83 of file noisepalette.h.
{
        fill_solid(currentPalette, 16, CRGB::Black);
        currentPalette[0] = CRGB::White;
        currentPalette[4] = CRGB::White;
        currentPalette[8] = CRGB::White;
        currentPalette[12] = CRGB::White;
    }
References CRGB::Black, currentPalette, fill_solid(), and CRGB::White.
Referenced by setPalettePreset().
SetupPurpleAndGreenPalette()
void fl::NoisePalette::SetupPurpleAndGreenPalette () inline private
Definition at line 91 of file noisepalette.h.
{
        CRGB purple = CHSV(HUE_PURPLE, 255, 255);
        CRGB green = CHSV(HUE_GREEN, 255, 255);
        CRGB black = CRGB::Black;
        currentPalette = CRGBPalette16(
            green, green, black, black, purple, purple, black, black, green,
            green, black, black, purple, purple, black, black);
    }
References CRGB::Black, currentPalette, HUE_GREEN, and HUE_PURPLE.
Referenced by setPalettePreset().
SetupRandomPalette()
void fl::NoisePalette::SetupRandomPalette () inline private
Definition at line 73 of file noisepalette.h.
{
        CRGBPalette16 newPalette;
        do {
            newPalette = CRGBPalette16(
                CHSV(random8(), 255, 32), CHSV(random8(), 255, 255),
                CHSV(random8(), 128, 255), CHSV(random8(), 255, 255));
        } while (newPalette == currentPalette);
        currentPalette = newPalette;
    }
References currentPalette, and random8().
Referenced by setPalettePreset().
XY()
uint16_t fl::NoisePalette::XY (uint8_t x, uint8_t y) const inline private
Definition at line 71 of file noisepalette.h.
{ return mXyMap.mapToIndex(x, y); }
References fl::XYMap::mapToIndex(), fl::Fx2d::mXyMap, x, and y.
Referenced by mapNoiseToLEDsUsingPalette().
Member Data Documentation
colorLoop
bool fl::NoisePalette::colorLoop = 0 private
Definition at line 65 of file noisepalette.h.
Referenced by mapNoiseToLEDsUsingPalette(), setPalette(), and setPalettePreset().
currentPalette
CRGBPalette16 fl::NoisePalette::currentPalette private
Definition at line 64 of file noisepalette.h.
Referenced by NoisePalette(), mapNoiseToLEDsUsingPalette(), setPalette(), setPalettePreset(), SetupBlackAndWhiteStripedPalette(), SetupPurpleAndGreenPalette(), and SetupRandomPalette().
currentPaletteIndex
int fl::NoisePalette::currentPaletteIndex = 0 private
Definition at line 66 of file noisepalette.h.
Referenced by changeToRandomPalette(), getPalettePreset(), and setPalettePreset().
height
uint16_t fl::NoisePalette::height private
Definition at line 60 of file noisepalette.h.
Referenced by NoisePalette(), fillnoise8(), and mapNoiseToLEDsUsingPalette().
mFps
float fl::NoisePalette::mFps = 60.f private
Definition at line 67 of file noisepalette.h.
Referenced by hasFixedFrameRate().
mX
uint16_t fl::NoisePalette::mX private
Definition at line 59 of file noisepalette.h.
Referenced by NoisePalette(), and fillnoise8().
mY
uint16_t fl::NoisePalette::mY private
Definition at line 59 of file noisepalette.h.
Referenced by NoisePalette(), and fillnoise8().
mZ
uint16_t fl::NoisePalette::mZ private
Definition at line 59 of file noisepalette.h.
Referenced by NoisePalette(), and fillnoise8().
noise
fl::scoped_array<uint8_t> fl::NoisePalette::noise private
Definition at line 63 of file noisepalette.h.
Referenced by NoisePalette(), fillnoise8(), and mapNoiseToLEDsUsingPalette().
scale
uint16_t fl::NoisePalette::scale = 0 private
Definition at line 62 of file noisepalette.h.
Referenced by fillnoise8(), setPalette(), setPalettePreset(), and setScale().
speed
uint16_t fl::NoisePalette::speed = 0 private
Definition at line 61 of file noisepalette.h.
Referenced by fillnoise8(), setPalette(), setPalettePreset(), and setSpeed().
width
uint16_t fl::NoisePalette::width private
Definition at line 60 of file noisepalette.h.
Referenced by NoisePalette(), fillnoise8(), and mapNoiseToLEDsUsingPalette().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/2d/noisepalette.h
/home/runner/work/FastLED/FastLED/src/fx/2d/noisepalette.cpp