FastLED: PixelController< RGB_ORDER, LANES, MASK > Struct Template Reference
PixelController< RGB_ORDER, LANES, MASK > Struct Template Reference
Detailed Description
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF>
struct PixelController< RGB_ORDER, LANES, MASK >
Pixel controller class.
This is the class that we use to centralize pixel access in a block of data, including support for things like RGB reordering, scaling, dithering, skipping (for ARGB data), and eventually, we will centralize 8/12/16 conversions here as well.
Template Parameters
RGB_ORDER the rgb ordering for the LEDs (e.g. what order red, green, and blue data is written out in)
LANES how many parallel lanes of output to write
MASK bitmask for the output lanes
Definition at line 71 of file pixel_controller.h.
#include <pixel_controller.h>
Public Types
enum { kLanes = LANES , kMask = MASK }
Public Member Functions
PixelController (const CRGB &d, int len, ColorAdjustment color_adjustment, EDitherMode dither)
Constructor.
PixelController (const CRGB *d, int len, ColorAdjustment color_adjustment, EDitherMode dither)
Constructor.
PixelController (const PixelController &other)
Copy constructor.
template<EOrder RGB_ORDER_OTHER>
PixelController (const PixelController< RGB_ORDER_OTHER, LANES, MASK > &other)
PixelController (const uint8_t *d, int len, ColorAdjustment color_adjustment, EDitherMode dither, bool advance, uint8_t skip)
Constructor.
FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale0 ()
non-template alias of advanceAndLoadAndScale<0>()
FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale0 (int lane)
non-template alias of advanceAndLoadAndScale<0>()
FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale0 (int lane, uint8_t scale)
non-template alias of advanceAndLoadAndScale<0>()
FASTLED_FORCE_INLINE int advanceBy ()
Get the amount to advance the pointer by.
FASTLED_FORCE_INLINE void advanceData ()
Advance the data pointer forward, adjust position counter.
FASTLED_FORCE_INLINE PixelIterator as_iterator (const Rgbw &rgbw)
template<typename PixelControllerT >
void copy (const PixelControllerT &other)
void disableColorAdjustment ()
void enable_dithering (EDitherMode dither)
Toggle dithering enable If dithering is set to enabled, this will re-init the dithering values (init_binary_dithering()).
FASTLED_FORCE_INLINE uint8_t getScale0 ()
non-template alias of getscale<0>()
FASTLED_FORCE_INLINE uint8_t getScale1 ()
non-template alias of getscale<1>()
FASTLED_FORCE_INLINE uint8_t getScale2 ()
non-template alias of getscale<2>()
FASTLED_FORCE_INLINE bool has (int n)
Do we have n pixels left to process?
void init_binary_dithering ()
Set up the values for binary dithering.
void initOffsets (int len)
Initialize the PixelController::mOffsets array based on the length of the strip.
FASTLED_FORCE_INLINE int lanes ()
Get the number of lanes of the Controller.
FASTLED_FORCE_INLINE uint8_t loadAndScale0 ()
non-template alias of loadAndScale<0>()
FASTLED_FORCE_INLINE uint8_t loadAndScale0 (int lane)
non-template alias of loadAndScale<0>()
FASTLED_FORCE_INLINE uint8_t loadAndScale0 (int lane, uint8_t scale)
non-template alias of loadAndScale<0>()
FASTLED_FORCE_INLINE uint8_t loadAndScale1 ()
non-template alias of loadAndScale<1>()
FASTLED_FORCE_INLINE uint8_t loadAndScale1 (int lane)
non-template alias of loadAndScale<1>()
FASTLED_FORCE_INLINE uint8_t loadAndScale1 (int lane, uint8_t scale)
non-template alias of loadAndScale<1>()
FASTLED_FORCE_INLINE uint8_t loadAndScale2 ()
non-template alias of loadAndScale<2>()
FASTLED_FORCE_INLINE uint8_t loadAndScale2 (int lane)
non-template alias of loadAndScale<2>()
FASTLED_FORCE_INLINE uint8_t loadAndScale2 (int lane, uint8_t scale)
non-template alias of loadAndScale<2>()
FASTLED_FORCE_INLINE void loadAndScale_APA102_HD (uint8_t *b0_out, uint8_t *b1_out, uint8_t *b2_out, uint8_t *brightness_out)
FASTLED_FORCE_INLINE void loadAndScale_WS2816_HD (uint16_t *s0_out, uint16_t *s1_out, uint16_t *s2_out)
FASTLED_FORCE_INLINE void loadAndScaleRGB (uint8_t *b0_out, uint8_t *b1_out, uint8_t *b2_out)
FASTLED_FORCE_INLINE void loadAndScaleRGBW (Rgbw rgbw, uint8_t *b0_out, uint8_t *b1_out, uint8_t *b2_out, uint8_t *b3_out)
FASTLED_FORCE_INLINE void preStepFirstByteDithering ()
Some chipsets pre-cycle the first byte, which means we want to cycle byte 0's dithering separately.
FASTLED_FORCE_INLINE int size ()
Get the length of the LED strip.
FASTLED_FORCE_INLINE uint8_t stepAdvanceAndLoadAndScale0 ()
stepDithering() and advanceAndLoadAndScale0()
FASTLED_FORCE_INLINE uint8_t stepAdvanceAndLoadAndScale0 (int lane)
stepDithering() and advanceAndLoadAndScale0()
FASTLED_FORCE_INLINE uint8_t stepAdvanceAndLoadAndScale0 (int lane, uint8_t scale)
stepDithering() and advanceAndLoadAndScale0()
FASTLED_FORCE_INLINE void stepDithering ()
Step the dithering forward.
Static Public Member Functions
Template'd static functions for output
These functions are used for retrieving LED data for the LED chipset output controllers.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadByte (PixelController &pc)
Read a byte of LED data.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadByte (PixelController &pc, int lane)
Read a byte of LED data for parallel output.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t dither (PixelController &pc, uint8_t b)
Calculate a dither value using the per-channel dither data.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t dither (PixelController &, uint8_t b, uint8_t d)
Calculate a dither value.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t scale (PixelController &pc, uint8_t b)
Scale a value using the per-channel scale data.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t scale (PixelController &, uint8_t b, uint8_t scale)
Scale a value.
Composite shortcut functions for loading, dithering, and scaling
These composite functions will load color data, dither it, and scale it all at once so that it's ready for the output controller to send to the LEDs.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadAndScale (PixelController &pc)
Loads, dithers, and scales a single byte for a given output slot, using class dither and scale values.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadAndScale (PixelController &pc, int lane)
Loads, dithers, and scales a single byte for a given output slot and lane, using class dither and scale values.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadAndScale (PixelController &pc, int lane, uint8_t d, uint8_t scale)
Loads, dithers, and scales a single byte for a given output slot and lane.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t loadAndScale (PixelController &pc, int lane, uint8_t scale)
Loads and scales a single byte for a given output slot and lane.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale (PixelController &pc)
A version of loadAndScale() that advances the output data pointer.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale (PixelController &pc, int lane)
A version of loadAndScale() that advances the output data pointer.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t advanceAndLoadAndScale (PixelController &pc, int lane, uint8_t scale)
A version of loadAndScale() that advances the output data pointer without dithering.
Data retrieval functions
These functions retrieve channel-specific data from the class, arranged in output order.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t getd (PixelController &pc)
Gets the dithering data for the provided output slot.
template<int SLOT>
static FASTLED_FORCE_INLINE uint8_t getscale (PixelController &pc)
Gets the scale data for the provided output slot.
Public Attributes
uint8_t d [3]
values for the scaled dither signal
uint8_t e [3]
values for the unscaled dither signal
int8_t mAdvance
how many bytes to advance the pointer by each time. For CRGB this is 3.
ColorAdjustment mColorAdjustment
const uint8_t * mData
pointer to the underlying LED data
int mLen
number of LEDs in the data for one lane
int mLenRemaining
counter for the number of LEDs left to process
int mOffsets [LANES]
the number of bytes to offset each lane from the starting pointer
Member Enumeration Documentation
anonymous enum
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> anonymous enum
Enumerator
kLanes
kMask
Definition at line 81 of file pixel_controller.h.
         {
        kLanes = LANES,
        kMask = MASK
    };
Constructor & Destructor Documentation
PixelController() [1/5]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const PixelController< RGB_ORDER, LANES, MASK > & other) inline
Copy constructor.
Parameters
other the object to copy
Definition at line 99 of file pixel_controller.h.
{
        copy(other);
    }
References PixelController< RGB_ORDER, LANES, MASK >::copy().
PixelController() [2/5]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<EOrder RGB_ORDER_OTHER> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const PixelController< RGB_ORDER_OTHER, LANES, MASK > & other) inline
Definition at line 104 of file pixel_controller.h.
{
        copy(other);
    }
References PixelController< RGB_ORDER, LANES, MASK >::copy().
PixelController() [3/5]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const uint8_t * d, int len, ColorAdjustment color_adjustment, EDitherMode dither, bool advance, uint8_t skip) inline
Constructor.
Parameters
d pointer to LED data
len length of the LED data
color_adjustment LED scale values
dither dither setting for the LEDs
advance whether the pointer (d) should advance per LED
skip if the pointer is advancing, how many bytes to skip in addition to 3
Definition at line 142 of file pixel_controller.h.
                : mData(d), mLen(len), mLenRemaining(len), mColorAdjustment(color_adjustment) {
        enable_dithering(dither);
        mData += skip;
        mAdvance = (advance) ? 3+skip : 0;
        initOffsets(len);
    }
References PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::initOffsets(), PixelController< RGB_ORDER, LANES, MASK >::mAdvance, and PixelController< RGB_ORDER, LANES, MASK >::mData.
PixelController() [4/5]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const CRGB * d, int len, ColorAdjustment color_adjustment, EDitherMode dither) inline
Constructor.
Parameters
d pointer to LED data
len length of the LED data
color_adjustment LED scale values
dither dither setting for the LEDs
Definition at line 157 of file pixel_controller.h.
                : mData((const uint8_t*)d), mLen(len), mLenRemaining(len), mColorAdjustment(color_adjustment) {
        enable_dithering(dither);
        mAdvance = 3;
        initOffsets(len);
    }
References PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::initOffsets(), and PixelController< RGB_ORDER, LANES, MASK >::mAdvance.
PixelController() [5/5]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const CRGB & d, int len, ColorAdjustment color_adjustment, EDitherMode dither) inline
Constructor.
Parameters
d pointer to LED data
len length of the LED data
color_adjustment LED scale values
dither dither setting for the LEDs
Definition at line 171 of file pixel_controller.h.
                : mData((const uint8_t*)&d), mLen(len), mLenRemaining(len), mColorAdjustment(color_adjustment) {
        enable_dithering(dither);
        mAdvance = 0;
        initOffsets(len);
    }
References PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::initOffsets(), and PixelController< RGB_ORDER, LANES, MASK >::mAdvance.
Member Function Documentation
advanceAndLoadAndScale() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc) inline static
A version of loadAndScale() that advances the output data pointer.
Parameters
pc reference to the pixel controller
Definition at line 405 of file pixel_controller.h.
{ pc.advanceData(); return pc.loadAndScale<SLOT>(pc); }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0(), and PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0().
advanceAndLoadAndScale() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane) inline static
A version of loadAndScale() that advances the output data pointer.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
Definition at line 410 of file pixel_controller.h.
{ pc.advanceData(); return pc.loadAndScale<SLOT>(pc, lane); }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
advanceAndLoadAndScale() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane, uint8_t scale) inline static
A version of loadAndScale() that advances the output data pointer without dithering.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
scale the scale data for the byte
Definition at line 416 of file pixel_controller.h.
{ pc.advanceData(); return pc.loadAndScale<SLOT>(pc, lane, scale); }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and scale.
advanceAndLoadAndScale0() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0 () inline
non-template alias of advanceAndLoadAndScale<0>()
Definition at line 463 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale().
advanceAndLoadAndScale0() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0 (int lane) inline
non-template alias of advanceAndLoadAndScale<0>()
Definition at line 455 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale().
advanceAndLoadAndScale0() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0 (int lane, uint8_t scale) inline
non-template alias of advanceAndLoadAndScale<0>()
Definition at line 449 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), and scale.
advanceBy()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE int PixelController< RGB_ORDER, LANES, MASK >::advanceBy () inline
Get the amount to advance the pointer by.
Returns
PixelController::mAdvance
Definition at line 308 of file pixel_controller.h.
{ return mAdvance; }
References PixelController< RGB_ORDER, LANES, MASK >::mAdvance.
advanceData()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::advanceData () inline
Advance the data pointer forward, adjust position counter.
Definition at line 311 of file pixel_controller.h.
{ mData += mAdvance; --mLenRemaining;}
References PixelController< RGB_ORDER, LANES, MASK >::mAdvance, PixelController< RGB_ORDER, LANES, MASK >::mData, and PixelController< RGB_ORDER, LANES, MASK >::mLenRemaining.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels(), WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
as_iterator()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE PixelIterator PixelController< RGB_ORDER, LANES, MASK >::as_iterator (const Rgbw & rgbw) inline
Definition at line 86 of file pixel_controller.h.
{
        return PixelIterator(this, rgbw);
    }
References rgbw.
copy()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<typename PixelControllerT > void PixelController< RGB_ORDER, LANES, MASK >::copy (const PixelControllerT & other) inline
Definition at line 109 of file pixel_controller.h.
{
        static_assert(int(kLanes) == int(PixelControllerT::kLanes), "PixelController lanes must match or mOffsets will be wrong");
        static_assert(int(kMask) == int(PixelControllerT::kMask), "PixelController mask must match or else one or the other controls different lanes");
        d[0] = other.d[0];
        d[1] = other.d[1];
        d[2] = other.d[2];
        e[0] = other.e[0];
        e[1] = other.e[1];
        e[2] = other.e[2];
        mData = other.mData;
        mColorAdjustment = other.mColorAdjustment;
        mAdvance = other.mAdvance;
        mLenRemaining = mLen = other.mLen;
        for(int i = 0; i < LANES; ++i) { mOffsets[i] = other.mOffsets[i]; }
    }
References PixelController< RGB_ORDER, LANES, MASK >::d, PixelController< RGB_ORDER, LANES, MASK >::e, PixelController< RGB_ORDER, LANES, MASK >::kLanes, PixelController< RGB_ORDER, LANES, MASK >::kMask, PixelController< RGB_ORDER, LANES, MASK >::mAdvance, PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, PixelController< RGB_ORDER, LANES, MASK >::mData, PixelController< RGB_ORDER, LANES, MASK >::mLen, PixelController< RGB_ORDER, LANES, MASK >::mLenRemaining, and PixelController< RGB_ORDER, LANES, MASK >::mOffsets.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), and PixelController< RGB_ORDER, LANES, MASK >::PixelController().
disableColorAdjustment()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> void PixelController< RGB_ORDER, LANES, MASK >::disableColorAdjustment () inline
Definition at line 90 of file pixel_controller.h.
{
        #if FASTLED_HD_COLOR_MIXING
        mColorAdjustment.premixed = CRGB(mColorAdjustment.brightness, mColorAdjustment.brightness, mColorAdjustment.brightness);
        mColorAdjustment.color = CRGB(0xff, 0xff, 0xff);
        #endif
    }
References PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, and ColorAdjustment::premixed.
dither() [1/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::dither (PixelController< RGB_ORDER, LANES, MASK > & , uint8_t b, uint8_t d) inline static
Calculate a dither value.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
b the color byte to dither
d dither data
Definition at line 354 of file pixel_controller.h.
{ return b ? qadd8(b,d) : 0; }
References PixelController< RGB_ORDER, LANES, MASK >::d, and qadd8().
dither() [2/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::dither (PixelController< RGB_ORDER, LANES, MASK > & pc, uint8_t b) inline static
Calculate a dither value using the per-channel dither data.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
b the color byte to dither
See also
PixelController::d
Definition at line 348 of file pixel_controller.h.
{ return b ? qadd8(b, pc.d[RO(SLOT)]) : 0; }
References PixelController< RGB_ORDER, LANES, MASK >::d, qadd8(), and RO.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
enable_dithering()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> void PixelController< RGB_ORDER, LANES, MASK >::enable_dithering (EDitherMode dither) inline
Toggle dithering enable If dithering is set to enabled, this will re-init the dithering values (init_binary_dithering()).
Otherwise it will clear the stored dithering data.
Parameters
dither the dither setting
Definition at line 291 of file pixel_controller.h.
{
        switch(dither) {
            case BINARY_DITHER: init_binary_dithering(); break;
            default: d[0]=d[1]=d[2]=e[0]=e[1]=e[2]=0; break;
        }
    }
References BINARY_DITHER, PixelController< RGB_ORDER, LANES, MASK >::d, PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::e, and PixelController< RGB_ORDER, LANES, MASK >::init_binary_dithering().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), and PixelController< RGB_ORDER, LANES, MASK >::PixelController().
getd()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::getd (PixelController< RGB_ORDER, LANES, MASK > & pc) inline static
Gets the dithering data for the provided output slot.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
Returns
dithering data for the given channel
See also
PixelController::d
Definition at line 431 of file pixel_controller.h.
{ return pc.d[RO(SLOT)]; }
References PixelController< RGB_ORDER, LANES, MASK >::d, and RO.
getscale()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::getscale (PixelController< RGB_ORDER, LANES, MASK > & pc) inline static
Gets the scale data for the provided output slot.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
Returns
scale data for the given channel
See also
PixelController::mScale
Definition at line 438 of file pixel_controller.h.
{ return pc.mColorAdjustment.premixed.raw[RO(SLOT)]; }
References PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, ColorAdjustment::premixed, and RO.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::getScale0(), PixelController< RGB_ORDER, LANES, MASK >::getScale1(), and PixelController< RGB_ORDER, LANES, MASK >::getScale2().
getScale0()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::getScale0 () inline
non-template alias of getscale<0>()
Definition at line 466 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::getscale().
getScale1()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::getScale1 () inline
non-template alias of getscale<1>()
Definition at line 467 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::getscale().
getScale2()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::getScale2 () inline
non-template alias of getscale<2>()
Definition at line 468 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::getscale().
has()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE bool PixelController< RGB_ORDER, LANES, MASK >::has (int n) inline
Do we have n pixels left to process?
Parameters
n the number to check against
Returns
'true' if there are more than n pixels left to process
Definition at line 282 of file pixel_controller.h.
{
        return mLenRemaining >= n;
    }
References PixelController< RGB_ORDER, LANES, MASK >::mLenRemaining.
Referenced by DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels(), WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
init_binary_dithering()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> void PixelController< RGB_ORDER, LANES, MASK >::init_binary_dithering () inline
Set up the values for binary dithering.
Definition at line 226 of file pixel_controller.h.
{
#if !defined(NO_DITHERING) || (NO_DITHERING != 1)
        // R is the digther signal 'counter'.
        static uint8_t R = 0;
        ++R;
        // R is wrapped around at 2^ditherBits,
        // so if ditherBits is 2, R will cycle through (0,1,2,3)
        uint8_t ditherBits = VIRTUAL_BITS;
        R &= (0x01 << ditherBits) - 1;
        // Q is the "unscaled dither signal" itself.
        // It's initialized to the reversed bits of R.
        // If 'ditherBits' is 2, Q here will cycle through (0,128,64,192)
        uint8_t Q = 0;
        // Reverse bits in a byte
        {
            if(R & 0x01) { Q |= 0x80; }
            if(R & 0x02) { Q |= 0x40; }
            if(R & 0x04) { Q |= 0x20; }
            if(R & 0x08) { Q |= 0x10; }
            if(R & 0x10) { Q |= 0x08; }
            if(R & 0x20) { Q |= 0x04; }
            if(R & 0x40) { Q |= 0x02; }
            if(R & 0x80) { Q |= 0x01; }
        }
        // Now we adjust Q to fall in the center of each range,
        // instead of at the start of the range.
        // If ditherBits is 2, Q will be (0, 128, 64, 192) at first,
        // and this adjustment makes it (31, 159, 95, 223).
        if( ditherBits < 8) {
            Q += 0x01 << (7 - ditherBits);
        }
        // D and E form the "scaled dither signal"
        // which is added to pixel values to affect the
        // actual dithering.
        // Setup the initial D and E values
        for(int i = 0; i < 3; ++i) {
                uint8_t s = mColorAdjustment.premixed.raw[i];
                e[i] = s ? (256/s) + 1 : 0;
                d[i] = scale8(Q, e[i]);
#if (FASTLED_SCALE8_FIXED == 1)
                if(d[i]) (--d[i]);
#endif
                if(e[i]) --e[i];
        }
#endif
    }
References PixelController< RGB_ORDER, LANES, MASK >::d, PixelController< RGB_ORDER, LANES, MASK >::e, PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, ColorAdjustment::premixed, scale8(), and VIRTUAL_BITS.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::enable_dithering().
initOffsets()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> void PixelController< RGB_ORDER, LANES, MASK >::initOffsets (int len) inline
Initialize the PixelController::mOffsets array based on the length of the strip.
Parameters
len the number of LEDs in one lane of the strip
Definition at line 127 of file pixel_controller.h.
{
        int nOffset = 0;
        for(int i = 0; i < LANES; ++i) {
            mOffsets[i] = nOffset;
            if((1<<i) & MASK) { nOffset += (len * mAdvance); }
        }
    }
References PixelController< RGB_ORDER, LANES, MASK >::mAdvance, and PixelController< RGB_ORDER, LANES, MASK >::mOffsets.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), and PixelController< RGB_ORDER, LANES, MASK >::PixelController().
lanes()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE int PixelController< RGB_ORDER, LANES, MASK >::lanes () inline
Get the number of lanes of the Controller.
Returns
LANES from template
Definition at line 304 of file pixel_controller.h.
{ return LANES; }
loadAndScale() [1/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc) inline static
Loads, dithers, and scales a single byte for a given output slot, using class dither and scale values.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
Definition at line 379 of file pixel_controller.h.
{ return scale<SLOT>(pc, pc.dither<SLOT>(pc, pc.loadByte<SLOT>(pc))); }
References PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::loadByte(), and scale.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2().
loadAndScale() [2/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane) inline static
Loads, dithers, and scales a single byte for a given output slot and lane, using class dither and scale values.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
Definition at line 385 of file pixel_controller.h.
{ return scale<SLOT>(pc, pc.dither<SLOT>(pc, pc.loadByte<SLOT>(pc, lane))); }
References PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::loadByte(), and scale.
loadAndScale() [3/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane, uint8_t d, uint8_t scale) inline static
Loads, dithers, and scales a single byte for a given output slot and lane.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
d the dither data for the byte
scale the scale data for the byte
Definition at line 393 of file pixel_controller.h.
{ return scale8(pc.dither<SLOT>(pc, pc.loadByte<SLOT>(pc, lane), d), scale); }
References PixelController< RGB_ORDER, LANES, MASK >::d, PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::loadByte(), scale, and scale8().
loadAndScale() [4/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane, uint8_t scale) inline static
Loads and scales a single byte for a given output slot and lane.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
scale the scale data for the byte
Definition at line 400 of file pixel_controller.h.
{ return scale8(pc.loadByte<SLOT>(pc, lane), scale); }
References PixelController< RGB_ORDER, LANES, MASK >::loadByte(), scale, and scale8().
loadAndScale0() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0 () inline
non-template alias of loadAndScale<0>()
Definition at line 460 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW().
loadAndScale0() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0 (int lane) inline
non-template alias of loadAndScale<0>()
Definition at line 452 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
loadAndScale0() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0 (int lane, uint8_t scale) inline
non-template alias of loadAndScale<0>()
Definition at line 446 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and scale.
Referenced by DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
loadAndScale1() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1 () inline
non-template alias of loadAndScale<1>()
Definition at line 461 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW().
loadAndScale1() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1 (int lane) inline
non-template alias of loadAndScale<1>()
Definition at line 453 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
loadAndScale1() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1 (int lane, uint8_t scale) inline
non-template alias of loadAndScale<1>()
Definition at line 447 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and scale.
Referenced by DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
loadAndScale2() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2 () inline
non-template alias of loadAndScale<2>()
Definition at line 462 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW().
loadAndScale2() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2 (int lane) inline
non-template alias of loadAndScale<2>()
Definition at line 454 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
loadAndScale2() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2 (int lane, uint8_t scale) inline
non-template alias of loadAndScale<2>()
Definition at line 448 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and scale.
Referenced by DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
loadAndScale_APA102_HD()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD (uint8_t * b0_out, uint8_t * b1_out, uint8_t * b2_out, uint8_t * brightness_out) inline
Definition at line 483 of file pixel_controller.h.
{
        CRGB rgb = CRGB(mData[0], mData[1], mData[2]);
        uint8_t brightness = 0;
        if (rgb) {
            #if FASTLED_HD_COLOR_MIXING
            brightness = mColorAdjustment.brightness;
            CRGB scale = mColorAdjustment.color;
            #else
            brightness = 255;
            CRGB scale = mColorAdjustment.premixed;
            #endif
            fl::five_bit_hd_gamma_bitshift(
                rgb,
                scale,
                brightness,
                &rgb,
                &brightness);
        }
        const uint8_t b0_index = RGB_BYTE0(RGB_ORDER);
        const uint8_t b1_index = RGB_BYTE1(RGB_ORDER);
        const uint8_t b2_index = RGB_BYTE2(RGB_ORDER);
        *b0_out = rgb.raw[b0_index];
        *b1_out = rgb.raw[b1_index];
        *b2_out = rgb.raw[b2_index];
        *brightness_out = brightness;
    }
References brightness, fl::five_bit_hd_gamma_bitshift(), PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, PixelController< RGB_ORDER, LANES, MASK >::mData, ColorAdjustment::premixed, RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, and scale.
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
loadAndScale_WS2816_HD()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD (uint16_t * s0_out, uint16_t * s1_out, uint16_t * s2_out) inline
Definition at line 521 of file pixel_controller.h.
{
        // Note that the WS2816 has a 4 bit gamma correction built in. To improve things this algorithm may
        // change in the future with a partial gamma correction that is completed by the chipset gamma
        // correction.
        uint16_t r16 = map8_to_16(mData[0]);
        uint16_t g16 = map8_to_16(mData[1]);
        uint16_t b16 = map8_to_16(mData[2]);
        if (r16 || g16 || b16) {
    #if FASTLED_HD_COLOR_MIXING
            uint8_t brightness = mColorAdjustment.brightness;
            CRGB scale = mColorAdjustment.color;
    #else
            uint8_t brightness = 255;
            CRGB scale = mColorAdjustment.premixed;
    #endif
            if (scale[0] != 255) {
                r16 = scale16by8(r16, scale[0]);
            }
            if (scale[1] != 255) {
                g16 = scale16by8(g16, scale[1]);
            }
            if (scale[2] != 255) {
                b16 = scale16by8(b16, scale[2]);
            }
            if (brightness != 255) {
                r16 = scale16by8(r16, brightness);
                g16 = scale16by8(g16, brightness);
                b16 = scale16by8(b16, brightness);
            }
        }
        uint16_t rgb16[3] = {r16, g16, b16};
        const uint8_t s0_index = RGB_BYTE0(RGB_ORDER);
        const uint8_t s1_index = RGB_BYTE1(RGB_ORDER);
        const uint8_t s2_index = RGB_BYTE2(RGB_ORDER);
        *s0_out = rgb16[s0_index];
        *s1_out = rgb16[s1_index];
        *s2_out = rgb16[s2_index];
    }
References brightness, map8_to_16(), PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, PixelController< RGB_ORDER, LANES, MASK >::mData, ColorAdjustment::premixed, RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, scale, and scale16by8().
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().
loadAndScaleRGB()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB (uint8_t * b0_out, uint8_t * b1_out, uint8_t * b2_out) inline
Definition at line 512 of file pixel_controller.h.
{
        *b0_out = loadAndScale0();
        *b1_out = loadAndScale1();
        *b2_out = loadAndScale2();
    }
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault().
loadAndScaleRGBW()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW (Rgbw rgbw, uint8_t * b0_out, uint8_t * b1_out, uint8_t * b2_out, uint8_t * b3_out) inline
Definition at line 560 of file pixel_controller.h.
{
#ifdef __AVR__
        // Don't do RGBW conversion for AVR, just set the W pixel to black.
        uint8_t out[4] = {
            // Get the pixels in native order.
            loadAndScale0(),
            loadAndScale1(),
            loadAndScale2(),
            0,
        };
        EOrderW w_placement = rgbw.w_placement;
        // Apply w-component insertion.
        rgbw_partial_reorder(
            w_placement, out[0], out[1], out[2],
            0, // Pre-ordered RGB data with a 0 white component.
            b0_out, b1_out, b2_out, b3_out);
#else
        const uint8_t b0_index = RGB_BYTE0(RGB_ORDER);  // Needed to re-order RGB back into led native order.
        const uint8_t b1_index = RGB_BYTE1(RGB_ORDER);
        const uint8_t b2_index = RGB_BYTE2(RGB_ORDER);
        // Get the naive RGB data order in r,g,b order.
        CRGB rgb(mData[0], mData[1], mData[2]);
        uint8_t w = 0;
        rgb_2_rgbw(rgbw.rgbw_mode,
                   rgbw.white_color_temp,
                   rgb.r, rgb.g, rgb.b,  // Input colors
                   mColorAdjustment.premixed.r, mColorAdjustment.premixed.g, mColorAdjustment.premixed.b,  // How these colors are scaled for color balance.
                   &rgb.r, &rgb.g, &rgb.b, &w);
        // Now finish the ordering so that the output is in the native led order for all of RGBW.
        rgbw_partial_reorder(
            rgbw.w_placement,
            rgb.raw[b0_index],  // in-place re-ordering for the RGB data.
            rgb.raw[b1_index],
            rgb.raw[b2_index],
            w,  // The white component is not ordered in this call.
            b0_out, b1_out, b2_out, b3_out);  // RGBW data now in total native led order.
#endif
    }
References PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, PixelController< RGB_ORDER, LANES, MASK >::mData, ColorAdjustment::premixed, rgb_2_rgbw(), RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, rgbw, Rgbw::rgbw_mode, rgbw_partial_reorder(), Rgbw::w_placement, and Rgbw::white_color_temp.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
loadByte() [1/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadByte (PixelController< RGB_ORDER, LANES, MASK > & pc) inline static
Read a byte of LED data.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
Definition at line 335 of file pixel_controller.h.
{ return pc.mData[RO(SLOT)]; }
References PixelController< RGB_ORDER, LANES, MASK >::mData, and RO.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), and PixelController< RGB_ORDER, LANES, MASK >::loadAndScale().
loadByte() [2/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadByte (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane) inline static
Read a byte of LED data for parallel output.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
Definition at line 341 of file pixel_controller.h.
{ return pc.mData[pc.mOffsets[lane] + RO(SLOT)]; }
References PixelController< RGB_ORDER, LANES, MASK >::mData, PixelController< RGB_ORDER, LANES, MASK >::mOffsets, and RO.
preStepFirstByteDithering()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::preStepFirstByteDithering () inline
Some chipsets pre-cycle the first byte, which means we want to cycle byte 0's dithering separately.
Definition at line 324 of file pixel_controller.h.
{
        d[RO(0)] = e[RO(0)] - d[RO(0)];
    }
References PixelController< RGB_ORDER, LANES, MASK >::d, PixelController< RGB_ORDER, LANES, MASK >::e, and RO.
scale() [1/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::scale (PixelController< RGB_ORDER, LANES, MASK > & , uint8_t b, uint8_t scale) inline static
Scale a value.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
b the byte to scale
scale the scale value
Definition at line 367 of file pixel_controller.h.
{ return scale8(b, scale); }
References scale, and scale8().
scale() [2/2]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::scale (PixelController< RGB_ORDER, LANES, MASK > & pc, uint8_t b) inline static
Scale a value using the per-channel scale data.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
b the color byte to scale
See also
PixelController::mScale
Definition at line 361 of file pixel_controller.h.
{ return scale8(b, pc.mColorAdjustment.premixed.raw[RO(SLOT)]); }
References PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment, ColorAdjustment::premixed, RO, and scale8().
size()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE int PixelController< RGB_ORDER, LANES, MASK >::size () inline
Get the length of the LED strip.
Returns
PixelController::mLen
Definition at line 300 of file pixel_controller.h.
{ return mLen; }
References PixelController< RGB_ORDER, LANES, MASK >::mLen.
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels(), WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift().
stepAdvanceAndLoadAndScale0() [1/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0 () inline
stepDithering() and advanceAndLoadAndScale0()
Definition at line 464 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
stepAdvanceAndLoadAndScale0() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0 (int lane) inline
stepDithering() and advanceAndLoadAndScale0()
Definition at line 456 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
stepAdvanceAndLoadAndScale0() [3/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0 (int lane, uint8_t scale) inline
stepDithering() and advanceAndLoadAndScale0()
Definition at line 450 of file pixel_controller.h.
References PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), scale, and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
stepDithering()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::stepDithering () inline
Step the dithering forward.
Note
If updating here, be sure to update the asm version in clockless_trinket.h!
Definition at line 315 of file pixel_controller.h.
{
            // IF UPDATING HERE, BE SURE TO UPDATE THE ASM VERSION IN
            // clockless_trinket.h!
            d[0] = e[0] - d[0];
            d[1] = e[1] - d[1];
            d[2] = e[2] - d[2];
    }
References PixelController< RGB_ORDER, LANES, MASK >::d, and PixelController< RGB_ORDER, LANES, MASK >::e.
Referenced by DMXSerialController< RGB_ORDER >::showPixels(), DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels(), WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and REFHardwareSPIOutput< _DATA_PIN, _CLOCK_PIN, _SPI_CLOCK_DIVIDER >::writePixels().
Member Data Documentation
d
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> uint8_t PixelController< RGB_ORDER, LANES, MASK >::d[3]
values for the scaled dither signal
See also
init_binary_dithering()
Definition at line 75 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::getd(), PixelController< RGB_ORDER, LANES, MASK >::init_binary_dithering(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::preStepFirstByteDithering(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
e
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> uint8_t PixelController< RGB_ORDER, LANES, MASK >::e[3]
values for the unscaled dither signal
See also
init_binary_dithering()
Definition at line 76 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::enable_dithering(), PixelController< RGB_ORDER, LANES, MASK >::init_binary_dithering(), PixelController< RGB_ORDER, LANES, MASK >::preStepFirstByteDithering(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
mAdvance
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> int8_t PixelController< RGB_ORDER, LANES, MASK >::mAdvance
how many bytes to advance the pointer by each time. For CRGB this is 3.
Definition at line 77 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::advanceBy(), PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::initOffsets(), and CPixelLEDController< RGB_ORDER, LANES, MASK >::show().
mColorAdjustment
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> ColorAdjustment PixelController< RGB_ORDER, LANES, MASK >::mColorAdjustment
Definition at line 79 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::disableColorAdjustment(), PixelController< RGB_ORDER, LANES, MASK >::getscale(), PixelController< RGB_ORDER, LANES, MASK >::init_binary_dithering(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), and PixelController< RGB_ORDER, LANES, MASK >::scale().
mData
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> const uint8_t* PixelController< RGB_ORDER, LANES, MASK >::mData
pointer to the underlying LED data
Definition at line 72 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::PixelController(), PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), PixelController< RGB_ORDER, LANES, MASK >::loadByte(), and PixelController< RGB_ORDER, LANES, MASK >::loadByte().
mLen
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> int PixelController< RGB_ORDER, LANES, MASK >::mLen
number of LEDs in the data for one lane
Definition at line 73 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::size(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
mLenRemaining
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> int PixelController< RGB_ORDER, LANES, MASK >::mLenRemaining
counter for the number of LEDs left to process
Definition at line 74 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::copy(), and PixelController< RGB_ORDER, LANES, MASK >::has().
mOffsets
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> int PixelController< RGB_ORDER, LANES, MASK >::mOffsets[LANES]
the number of bytes to offset each lane from the starting pointer
See also
initOffsets()
Definition at line 78 of file pixel_controller.h.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::copy(), PixelController< RGB_ORDER, LANES, MASK >::initOffsets(), and PixelController< RGB_ORDER, LANES, MASK >::loadByte().
The documentation for this struct was generated from the following file:
/home/runner/work/FastLED/FastLED/src/pixel_controller.h