FastLED: AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > Class Template Reference
AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED > Class Template Reference
Detailed Description
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED>
class AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >
Software SPI (aka bit-banging) support Includes aggressive optimizations for when the clock and data pin are on the same port.
Template Parameters
DATA_PIN pin number of the SPI data pin.
CLOCK_PIN pin number of the SPI clock pin.
SPI_SPEED speed of the bus. Determines the delay times between pin writes.
Note
Although this is named with the "AVR" prefix, this will work on any platform. Theoretically.
Todo
Replace the select pin definition with a set of pins, to allow using mux hardware for routing in the future.
Definition at line 24 of file fastspi_bitbang.h.
#include <fastspi_bitbang.h>
Public Member Functions
AVRSoftwareSPIOutput ()
Default constructor.
AVRSoftwareSPIOutput (Selectable *pSelect)
Constructor with selectable for SPI chip select.
void init ()
Set the clock/data pins to output and make sure the chip select is released.
void release ()
Release the SPI chip select line.
void select ()
Select the SPI output (chip select)
void setSelect (Selectable *pSelect)
Set the pointer for the SPI chip select.
template<class D >
void writeBytes (FASTLED_REGISTER uint8_t *data, int len)
Write an array of data to the SPI interface.
void writeBytes (FASTLED_REGISTER uint8_t *data, int len)
Write an array of data to the SPI interface.
void writeBytesValue (uint8_t value, int len)
Write multiple bytes of the given value over SPI.
template<uint8_t FLAGS, class D , EOrder RGB_ORDER>
void writePixels (PixelController< RGB_ORDER > pixels, void *context=NULL)
Write LED pixel data to the SPI interface.
Static Public Member Functions
static void stop ()
Stop the SPI output.
static void wait ()
Wait until the SPI subsystem is ready for more data to write.
static void waitFully ()
Wait until the SPI subsystem is ready for more data to write.
template<uint8_t BIT>
static void writeBit (uint8_t b)
Write the BIT'th bit out via SPI, setting the data pin then strobing the clock.
static void writeByte (uint8_t b)
Write a single byte over SPI.
static void writeByteNoWait (uint8_t b)
Write a single byte over SPI without waiting.
static void writeBytePostWait (uint8_t b)
Write a single byte over SPI and wait afterwards.
static void writeBytesValueRaw (uint8_t value, int len)
Write multiple bytes of the given value over SPI, without selecting the interface.
static void writeWord (uint16_t w)
Write a word (two bytes) over SPI.
Private Types
typedef FastPin< CLOCK_PIN >::port_ptr_t clock_ptr_t
typedef FastPin< CLOCK_PIN >::port_t clock_t
typedef FastPin< DATA_PIN >::port_ptr_t data_ptr_t
typedef FastPin< DATA_PIN >::port_t data_t
Static Private Member Functions
template<uint8_t BIT>
static FASTLED_FORCE_INLINE void writeBit (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin)
Write the BIT'th bit out via SPI, setting the data pin then strobing the clock, using the passed in pin registers to accelerate access if needed.
template<uint8_t BIT>
static FASTLED_FORCE_INLINE void writeBit (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock)
The version of writeBit() to use when clock and data are on separate pins with precomputed values for setting the clock and data pins.
template<uint8_t BIT>
static FASTLED_FORCE_INLINE void writeBit (uint8_t b, data_ptr_t clockdatapin, data_t datahiclockhi, data_t dataloclockhi, data_t datahiclocklo, data_t dataloclocklo)
The version of writeBit() to use when clock and data are on the same port with precomputed values for the various combinations.
static void writeByte (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin)
writeByte() implementation with data/clock registers passed in.
static void writeByte (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock)
writeByte() implementation with not just registers passed in, but pre-baked values for said registers for data hi/lo and clock hi/lo values.
static void writeByte (uint8_t b, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock)
writeByte() implementation with the data register passed in and prebaked values for data hi w/clock hi and low and data lo w/clock hi and lo.
Private Attributes
Selectable * m_pSelect
SPI chip select.
Member Typedef Documentation
clock_ptr_t
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> FastPin<CLOCK_PIN>::port_ptr_t AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::clock_ptr_t private
Definition at line 28 of file fastspi_bitbang.h.
clock_t
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> FastPin<CLOCK_PIN>::port_t AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::clock_t private
Definition at line 33 of file fastspi_bitbang.h.
data_ptr_t
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> FastPin<DATA_PIN>::port_ptr_t AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::data_ptr_t private
Definition at line 27 of file fastspi_bitbang.h.
data_t
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> FastPin<DATA_PIN>::port_t AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::data_t private
Definition at line 32 of file fastspi_bitbang.h.
Constructor & Destructor Documentation
AVRSoftwareSPIOutput() [1/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::AVRSoftwareSPIOutput () inline
Default constructor.
Definition at line 38 of file fastspi_bitbang.h.
{ m_pSelect = NULL; }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect.
AVRSoftwareSPIOutput() [2/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::AVRSoftwareSPIOutput (Selectable * pSelect) inline
Constructor with selectable for SPI chip select.
Definition at line 40 of file fastspi_bitbang.h.
{ m_pSelect = pSelect; }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect.
Member Function Documentation
init()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init () inline
Set the clock/data pins to output and make sure the chip select is released.
Definition at line 47 of file fastspi_bitbang.h.
                {
        // set the pins to output and make sure the select is released (which apparently means hi?  This is a bit
        // confusing to me)
        FastPin<DATA_PIN>::setOutput();
        FastPin<CLOCK_PIN>::setOutput();
        release();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), and FastPin< PIN >::setOutput().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::init(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init(), and WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::init().
release()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release () inline
Release the SPI chip select line.
Definition at line 240 of file fastspi_bitbang.h.
{ if(m_pSelect != NULL) { m_pSelect->release(); } } // FastPin<SELECT_PIN>::lo(); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect, and Selectable::release().
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::init(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValue(), SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
select()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select () inline
Select the SPI output (chip select)
Todo
Research whether this really means 'hi' or 'lo'.
Todo
Move select responsibility out of the SPI classes entirely, make it up to the caller to remember to lock/select the line?
Definition at line 237 of file fastspi_bitbang.h.
{ if(m_pSelect != NULL) { m_pSelect->select(); } } // FastPin<SELECT_PIN>::hi(); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect, and Selectable::select().
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValue(), SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
setSelect()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::setSelect (Selectable * pSelect) inline
Set the pointer for the SPI chip select.
Parameters
pSelect pointer to chip select control
Definition at line 44 of file fastspi_bitbang.h.
{ m_pSelect = pSelect; }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect.
stop()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::stop () inline static
Stop the SPI output.
Pretty much a NOP with software, as there's no registers to kick
Definition at line 57 of file fastspi_bitbang.h.
{ }
wait()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::wait () inline static
Wait until the SPI subsystem is ready for more data to write.
A NOP when bitbanging.
Definition at line 61 of file fastspi_bitbang.h.
{ }
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytePostWait().
waitFully()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::waitFully () inline static
Wait until the SPI subsystem is ready for more data to write.
A NOP when bitbanging.
Definition at line 63 of file fastspi_bitbang.h.
{ wait(); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::wait().
Referenced by LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), and SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader().
writeBit() [1/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<uint8_t BIT> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit (uint8_t b) inline static
Write the BIT'th bit out via SPI, setting the data pin then strobing the clock.
Template Parameters
BIT the bit index in the byte
Parameters
b the byte to read the bit from
Definition at line 151 of file fastspi_bitbang.h.
{
        //cli();
        if(b & (1 << BIT)) {
            FastPin<DATA_PIN>::hi();
#ifdef ESP32
            // try to ensure we never have adjacent write opcodes to the same register
            FastPin<CLOCK_PIN>::lo();
            FastPin<CLOCK_PIN>::hi(); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::toggle(); CLOCK_LO_DELAY;
#else
            FastPin<CLOCK_PIN>::hi(); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::lo(); CLOCK_LO_DELAY;
#endif
        } else {
            FastPin<DATA_PIN>::lo();
            FastPin<CLOCK_PIN>::hi(); CLOCK_HI_DELAY;
#ifdef ESP32
            // try to ensure we never have adjacent write opcodes to the same register
            FastPin<CLOCK_PIN>::toggle(); CLOCK_HI_DELAY;
#else
            FastPin<CLOCK_PIN>::lo(); CLOCK_LO_DELAY;
#endif
        }
        //sei();
    }
References CLOCK_HI_DELAY, CLOCK_LO_DELAY, FastPin< PIN >::hi(), FastPin< PIN >::lo(), and FastPin< PIN >::toggle().
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels().
writeBit() [2/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<uint8_t BIT> static FASTLED_FORCE_INLINE void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin) inline static private
Write the BIT'th bit out via SPI, setting the data pin then strobing the clock, using the passed in pin registers to accelerate access if needed.
Definition at line 179 of file fastspi_bitbang.h.
{
        if(b & (1 << BIT)) {
            FastPin<DATA_PIN>::hi(datapin);
            FastPin<CLOCK_PIN>::hi(clockpin); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::lo(clockpin); CLOCK_LO_DELAY;
        } else {
            FastPin<DATA_PIN>::lo(datapin);
            FastPin<CLOCK_PIN>::hi(clockpin); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::lo(clockpin); CLOCK_LO_DELAY;
        }
    }
References CLOCK_HI_DELAY, CLOCK_LO_DELAY, FastPin< PIN >::hi(), and FastPin< PIN >::lo().
writeBit() [3/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<uint8_t BIT> static FASTLED_FORCE_INLINE void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock) inline static private
The version of writeBit() to use when clock and data are on separate pins with precomputed values for setting the clock and data pins.
Definition at line 194 of file fastspi_bitbang.h.
{
        // // only need to explicitly set clock hi if clock and data are on different ports
        if(b & (1 << BIT)) {
            FastPin<DATA_PIN>::fastset(datapin, hival);
            FastPin<CLOCK_PIN>::fastset(clockpin, hiclock); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::fastset(clockpin, loclock); CLOCK_LO_DELAY;
        } else {
            // FL_NOP;
            FastPin<DATA_PIN>::fastset(datapin, loval);
            FastPin<CLOCK_PIN>::fastset(clockpin, hiclock); CLOCK_HI_DELAY;
            FastPin<CLOCK_PIN>::fastset(clockpin, loclock); CLOCK_LO_DELAY;
        }
    }
References CLOCK_HI_DELAY, CLOCK_LO_DELAY, and FastPin< PIN >::fastset().
writeBit() [4/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<uint8_t BIT> static FASTLED_FORCE_INLINE void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit (uint8_t b, data_ptr_t clockdatapin, data_t datahiclockhi, data_t dataloclockhi, data_t datahiclocklo, data_t dataloclocklo) inline static private
The version of writeBit() to use when clock and data are on the same port with precomputed values for the various combinations.
Definition at line 211 of file fastspi_bitbang.h.
{
#if 0
        writeBit<BIT>(b);
#else
        if(b & (1 << BIT)) {
            FastPin<DATA_PIN>::fastset(clockdatapin, datahiclocklo);
            FastPin<DATA_PIN>::fastset(clockdatapin, datahiclockhi); CLOCK_HI_DELAY;
            FastPin<DATA_PIN>::fastset(clockdatapin, datahiclocklo); CLOCK_LO_DELAY;
        } else {
            // FL_NOP;
            FastPin<DATA_PIN>::fastset(clockdatapin, dataloclocklo);
            FastPin<DATA_PIN>::fastset(clockdatapin, dataloclockhi); CLOCK_HI_DELAY;
            FastPin<DATA_PIN>::fastset(clockdatapin, dataloclocklo); CLOCK_LO_DELAY;
        }
#endif
    }
References CLOCK_HI_DELAY, CLOCK_LO_DELAY, FastPin< PIN >::fastset(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
writeByte() [1/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte (uint8_t b) inline static
Write a single byte over SPI.
Naive implelentation, simply calls writeBit() on the 8 bits in the byte.
Definition at line 75 of file fastspi_bitbang.h.
{
        writeBit<7>(b);
        writeBit<6>(b);
        writeBit<5>(b);
        writeBit<4>(b);
        writeBit<3>(b);
        writeBit<2>(b);
        writeBit<1>(b);
        writeBit<0>(b);
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::endBoundary(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::endBoundary(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels(), LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::startBoundary(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::write2Bytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByteNoWait(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytePostWait(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw(), SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeHeader(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeLed(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord().
writeByte() [2/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin) inline static private
writeByte() implementation with data/clock registers passed in.
Definition at line 88 of file fastspi_bitbang.h.
{
        writeBit<7>(b, clockpin, datapin);
        writeBit<6>(b, clockpin, datapin);
        writeBit<5>(b, clockpin, datapin);
        writeBit<4>(b, clockpin, datapin);
        writeBit<3>(b, clockpin, datapin);
        writeBit<2>(b, clockpin, datapin);
        writeBit<1>(b, clockpin, datapin);
        writeBit<0>(b, clockpin, datapin);
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
writeByte() [3/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte (uint8_t b, clock_ptr_t clockpin, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock) inline static private
writeByte() implementation with not just registers passed in, but pre-baked values for said registers for data hi/lo and clock hi/lo values.
Note
Weird things will happen if this method is called in cases where the data and clock pins are on the same port! Don't do that!
Definition at line 119 of file fastspi_bitbang.h.
{
        writeBit<7>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<6>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<5>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<4>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<3>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<2>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<1>(b, clockpin, datapin, hival, loval, hiclock, loclock);
        writeBit<0>(b, clockpin, datapin, hival, loval, hiclock, loclock);
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
writeByte() [4/4]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte (uint8_t b, data_ptr_t datapin, data_t hival, data_t loval, clock_t hiclock, clock_t loclock) inline static private
writeByte() implementation with the data register passed in and prebaked values for data hi w/clock hi and low and data lo w/clock hi and lo.
This is to be used when clock and data are on the same GPIO register, can get close to getting a bit out the door in 2 clock cycles!
Definition at line 102 of file fastspi_bitbang.h.
{
        writeBit<7>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<6>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<5>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<4>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<3>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<2>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<1>(b, datapin, hival, loval, hiclock, loclock);
        writeBit<0>(b, datapin, hival, loval, hiclock, loclock);
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit().
writeByteNoWait()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByteNoWait (uint8_t b) inline static
Write a single byte over SPI without waiting.
Definition at line 66 of file fastspi_bitbang.h.
{ writeByte(b); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
writeBytePostWait()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytePostWait (uint8_t b) inline static
Write a single byte over SPI and wait afterwards.
Definition at line 68 of file fastspi_bitbang.h.
{ writeByte(b); wait(); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::wait(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
writeBytes() [1/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<class D > void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes (FASTLED_REGISTER uint8_t * data, int len) inline
Write an array of data to the SPI interface.
Template Parameters
D Per-byte modifier class, e.g. DATA_NOP
Parameters
data pointer to data to write
len number of bytes to write
Todo
Need to type this better so that explicit casts into the call aren't required.
Definition at line 296 of file fastspi_bitbang.h.
{
        select();
#ifdef FAST_SPI_INTERRUPTS_WRITE_PINS
        uint8_t *end = data + len;
        while(data != end) {
            writeByte(D::adjust(*data++));
        }
#else
        FASTLED_REGISTER clock_ptr_t clockpin = FastPin<CLOCK_PIN>::port();
        FASTLED_REGISTER data_ptr_t datapin = FastPin<DATA_PIN>::port();
        if(FastPin<DATA_PIN>::port() != FastPin<CLOCK_PIN>::port()) {
            // If data and clock are on different ports, then writing a bit will consist of writing the value foor
            // the bit (hi or low) to the data pin port, and then two writes to the clock port to strobe the clock line
            FASTLED_REGISTER data_t datahi = FastPin<DATA_PIN>::hival();
            FASTLED_REGISTER data_t datalo = FastPin<DATA_PIN>::loval();
            FASTLED_REGISTER clock_t clockhi = FastPin<CLOCK_PIN>::hival();
            FASTLED_REGISTER clock_t clocklo = FastPin<CLOCK_PIN>::loval();
            uint8_t *end = data + len;
            while(data != end) {
                writeByte(D::adjust(*data++), clockpin, datapin, datahi, datalo, clockhi, clocklo);
            }
        } else {
            // FastPin<CLOCK_PIN>::hi();
            // If data and clock are on the same port then we can combine setting the data and clock pins
            FASTLED_REGISTER data_t datahi_clockhi = FastPin<DATA_PIN>::hival() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clockhi = FastPin<DATA_PIN>::loval() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datahi_clocklo = FastPin<DATA_PIN>::hival() & ~FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clocklo = FastPin<DATA_PIN>::loval() & ~FastPin<CLOCK_PIN>::mask();
            uint8_t *end = data + len;
            while(data != end) {
                writeByte(D::adjust(*data++), datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
            }
            // FastPin<CLOCK_PIN>::lo();
        }
#endif
        D::postBlock(len);
        release();
    }
References FASTLED_REGISTER, FastPin< PIN >::hival(), FastPin< PIN >::loval(), FastPin< PIN >::mask(), FastPin< PIN >::port(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes().
writeBytes() [2/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes (FASTLED_REGISTER uint8_t * data, int len) inline
Write an array of data to the SPI interface.
Parameters
data pointer to data to write
len number of bytes to write
Definition at line 343 of file fastspi_bitbang.h.
{ writeBytes<DATA_NOP>(data, len); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes().
writeBytesValue()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValue (uint8_t value, int len) inline
Write multiple bytes of the given value over SPI.
Useful for quickly flushing, say, a line of 0's down the line.
Parameters
value the value to write to the bus
len how many copies of the value to write
Definition at line 246 of file fastspi_bitbang.h.
{
        select();
        writeBytesValueRaw(value, len);
        release();
    }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw().
writeBytesValueRaw()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw (uint8_t value, int len) inline static
Write multiple bytes of the given value over SPI, without selecting the interface.
Useful for quickly flushing, say, a line of 0's down the line.
Parameters
value the value to write to the bus
len how many copies of the value to write
Definition at line 254 of file fastspi_bitbang.h.
{
#ifdef FAST_SPI_INTERRUPTS_WRITE_PINS
        // TODO: Weird things may happen if software bitbanging SPI output and other pins on the output reigsters are being twiddled.  Need
        // to allow specifying whether or not exclusive i/o access is allowed during this process, and if i/o access is not allowed fall
        // back to the degenerative code below
        while(len--) {
            writeByte(value);
        }
#else
        FASTLED_REGISTER data_ptr_t datapin = FastPin<DATA_PIN>::port();
        if(FastPin<DATA_PIN>::port() != FastPin<CLOCK_PIN>::port()) {
            // If data and clock are on different ports, then writing a bit will consist of writing the value foor
            // the bit (hi or low) to the data pin port, and then two writes to the clock port to strobe the clock line
            FASTLED_REGISTER clock_ptr_t clockpin = FastPin<CLOCK_PIN>::port();
            FASTLED_REGISTER data_t datahi = FastPin<DATA_PIN>::hival();
            FASTLED_REGISTER data_t datalo = FastPin<DATA_PIN>::loval();
            FASTLED_REGISTER clock_t clockhi = FastPin<CLOCK_PIN>::hival();
            FASTLED_REGISTER clock_t clocklo = FastPin<CLOCK_PIN>::loval();
            while(len--) {
                writeByte(value, clockpin, datapin, datahi, datalo, clockhi, clocklo);
            }
        } else {
            // If data and clock are on the same port then we can combine setting the data and clock pins
            FASTLED_REGISTER data_t datahi_clockhi = FastPin<DATA_PIN>::hival() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clockhi = FastPin<DATA_PIN>::loval() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datahi_clocklo = FastPin<DATA_PIN>::hival() & ~FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clocklo = FastPin<DATA_PIN>::loval() & ~FastPin<CLOCK_PIN>::mask();
            while(len--) {
                writeByte(value, datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
            }
        }
#endif
    }
References FASTLED_REGISTER, FastPin< PIN >::hival(), FastPin< PIN >::loval(), FastPin< PIN >::mask(), FastPin< PIN >::port(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806_ADJUST::postBlock(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValue().
writePixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<uint8_t FLAGS, class D , EOrder RGB_ORDER> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writePixels (PixelController< RGB_ORDER > pixels, void * context = NULL) inline
Write LED pixel data to the SPI interface.
Data is written in groups of three, re-ordered per the RGB_ORDER.
Template Parameters
FLAGS Option flags, such as FLAG_START_BIT
D Per-byte modifier class, e.g. DATA_NOP
RGB_ORDER the rgb ordering for the LED data (e.g. what order red, green, and blue data is written out in)
Parameters
pixels a PixelController with the LED data and modifier options
Definition at line 352 of file fastspi_bitbang.h.
{
        FASTLED_UNUSED(context);
        select();
        int len = pixels.mLen;
#ifdef FAST_SPI_INTERRUPTS_WRITE_PINS
        // If interrupts or other things may be generating output while we're working on things, then we need
        // to use this block
        while(pixels.has(1)) {
            if(FLAGS & FLAG_START_BIT) {
                writeBit<0>(1);
            }
            writeByte(D::adjust(pixels.loadAndScale0()));
            writeByte(D::adjust(pixels.loadAndScale1()));
            writeByte(D::adjust(pixels.loadAndScale2()));
            pixels.advanceData();
            pixels.stepDithering();
        }
#else
        // If we can guaruntee that no one else will be writing data while we are running (namely, changing the values of the PORT/PDOR pins)
        // then we can use a bunch of optimizations in here
        FASTLED_REGISTER data_ptr_t datapin = FastPin<DATA_PIN>::port();
        if(FastPin<DATA_PIN>::port() != FastPin<CLOCK_PIN>::port()) {
            FASTLED_REGISTER clock_ptr_t clockpin = FastPin<CLOCK_PIN>::port();
            // If data and clock are on different ports, then writing a bit will consist of writing the value foor
            // the bit (hi or low) to the data pin port, and then two writes to the clock port to strobe the clock line
            FASTLED_REGISTER data_t datahi = FastPin<DATA_PIN>::hival();
            FASTLED_REGISTER data_t datalo = FastPin<DATA_PIN>::loval();
            FASTLED_REGISTER clock_t clockhi = FastPin<CLOCK_PIN>::hival();
            FASTLED_REGISTER clock_t clocklo = FastPin<CLOCK_PIN>::loval();
            while(pixels.has(1)) {
                if(FLAGS & FLAG_START_BIT) {
                    writeBit<0>(1, clockpin, datapin, datahi, datalo, clockhi, clocklo);
                }
                writeByte(D::adjust(pixels.loadAndScale0()), clockpin, datapin, datahi, datalo, clockhi, clocklo);
                writeByte(D::adjust(pixels.loadAndScale1()), clockpin, datapin, datahi, datalo, clockhi, clocklo);
                writeByte(D::adjust(pixels.loadAndScale2()), clockpin, datapin, datahi, datalo, clockhi, clocklo);
                pixels.advanceData();
                pixels.stepDithering();
            }
        } else {
            // If data and clock are on the same port then we can combine setting the data and clock pins
            FASTLED_REGISTER data_t datahi_clockhi = FastPin<DATA_PIN>::hival() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clockhi = FastPin<DATA_PIN>::loval() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datahi_clocklo = FastPin<DATA_PIN>::hival() & ~FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clocklo = FastPin<DATA_PIN>::loval() & ~FastPin<CLOCK_PIN>::mask();
            while(pixels.has(1)) {
                if(FLAGS & FLAG_START_BIT) {
                    writeBit<0>(1, datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
                }
                writeByte(D::adjust(pixels.loadAndScale0()), datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
                writeByte(D::adjust(pixels.loadAndScale1()), datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
                writeByte(D::adjust(pixels.loadAndScale2()), datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
                pixels.advanceData();
                pixels.stepDithering();
            }
        }
#endif
        D::postBlock(len);
        release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), FASTLED_REGISTER, FASTLED_UNUSED, FLAG_START_BIT, PixelController< RGB_ORDER, LANES, MASK >::has(), FastPin< PIN >::hival(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), FastPin< PIN >::loval(), FastPin< PIN >::mask(), PixelController< RGB_ORDER, LANES, MASK >::mLen, FastPin< PIN >::port(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), PixelController< RGB_ORDER, LANES, MASK >::stepDithering(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBit(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
writeWord()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeWord (uint16_t w) inline static
Write a word (two bytes) over SPI.
Definition at line 71 of file fastspi_bitbang.h.
{ writeByte(w>>8); writeByte(w&0xFF); }
References AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeByte().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::startBoundary(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::write2Bytes(), P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::writeBoundary(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().
Member Data Documentation
m_pSelect
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> Selectable* AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::m_pSelect private
SPI chip select.
Definition at line 34 of file fastspi_bitbang.h.
Referenced by AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::AVRSoftwareSPIOutput(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::AVRSoftwareSPIOutput(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::release(), AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::select(), and AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::setSelect().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fastspi_bitbang.h