FastLED: /home/runner/work/FastLED/FastLED/examples/Chromancer/ripple.h File Reference
ripple.h File Reference
#include "FastLED.h"
#include "mapping.h"
Classes
class Ripple
Enumerations
enum rippleBehavior {
weaksauce = 0 , feisty = 1 , angry = 2 , alwaysTurnsRight = 3 ,
alwaysTurnsLeft = 4
}
enum rippleState { dead , withinNode , travelingUpwards , travelingDownwards }
Functions
float fmap (float x, float in_min, float in_max, float out_min, float out_max)
Enumeration Type Documentation
rippleBehavior
enum rippleBehavior
Enumerator
weaksauce
feisty
angry
alwaysTurnsRight
alwaysTurnsLeft
Definition at line 23 of file ripple.h.
                    {
  weaksauce = 0,
  feisty = 1,
  angry = 2,
  alwaysTurnsRight = 3,
  alwaysTurnsLeft = 4
};
rippleState
enum rippleState
Enumerator
dead
withinNode
travelingUpwards
travelingDownwards
Definition at line 16 of file ripple.h.
                 {
  dead,
  withinNode,  // Ripple isn't drawn as it passes through a node to keep the speed consistent
  travelingUpwards,
  travelingDownwards
};
Function Documentation
fmap()
float fmap (float x, float in_min, float in_max, float out_min, float out_max)
Definition at line 31 of file ripple.h.
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
References x.
Referenced by Ripple::advance(), loop(), net_init(), and Ripple::renderLed().