FastLED: /home/runner/work/FastLED/FastLED/src/rgbw.h File Reference
rgbw.h File Reference
Detailed Description
Functions for red, green, blue, white (RGBW) output.
Definition in file rgbw.h.
#include <stdint.h>
#include "fl/force_inline.h"
#include "fl/namespace.h"
#include "eorder.h"
Classes
struct Rgbw
struct RgbwDefault
struct RgbwInvalid
struct RgbwWhiteIsOff
Typedefs
typedef void(* rgb_2_rgbw_function) (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Enumerations
enum { kRGBWDefaultColorTemp = 6000 }
enum RGBW_MODE {
kRGBWInvalid , kRGBWNullWhitePixel , kRGBWExactColors , kRGBWBoostedWhite ,
kRGBWMaxBrightness , kRGBWUserFunction
}
Functions
FASTLED_FORCE_INLINE void rgb_2_rgbw (RGBW_MODE mode, uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Converts RGB to RGBW using one of the functions.
template<RGBW_MODE MODE>
FASTLED_FORCE_INLINE void rgb_2_rgbw (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
void rgb_2_rgbw_exact (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Converts RGB to RGBW using a color transfer method from saturated color channels to white.
void rgb_2_rgbw_max_brightness (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
The minimum brigthness of the RGB channels is used to set the W channel.
void rgb_2_rgbw_null_white_pixel (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Converts RGB to RGBW with the W channel set to black, always.
void rgb_2_rgbw_user_function (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
void rgb_2_rgbw_white_boosted (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Converts RGB to RGBW with a boosted white channel.
void rgbw_partial_reorder (EOrderW w_placement, uint8_t b0, uint8_t b1, uint8_t b2, uint8_t w, uint8_t *out_b0, uint8_t *out_b1, uint8_t *out_b2, uint8_t *out_b3)
void set_rgb_2_rgbw_function (rgb_2_rgbw_function func)
Typedef Documentation
rgb_2_rgbw_function
typedef void(* rgb_2_rgbw_function) (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t *out_r, uint8_t *out_g, uint8_t *out_b, uint8_t *out_w)
Definition at line 86 of file rgbw.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
kRGBWDefaultColorTemp
Definition at line 24 of file rgbw.h.
     {
    kRGBWDefaultColorTemp = 6000,
};
RGBW_MODE
enum RGBW_MODE
Enumerator
kRGBWInvalid
kRGBWNullWhitePixel
kRGBWExactColors
kRGBWBoostedWhite
kRGBWMaxBrightness
kRGBWUserFunction
Definition at line 15 of file rgbw.h.
               {
    kRGBWInvalid,
    kRGBWNullWhitePixel,
    kRGBWExactColors,
    kRGBWBoostedWhite,
    kRGBWMaxBrightness,
    kRGBWUserFunction
};
Function Documentation
rgb_2_rgbw() [1/2]
FASTLED_FORCE_INLINE void rgb_2_rgbw (RGBW_MODE mode, uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Converts RGB to RGBW using one of the functions.
Dynamic version of the rgb_w_rgbw function with less chance for the compiler to optimize.
Definition at line 150 of file rgbw.h.
{
    switch (mode) {
    case kRGBWInvalid:
    case kRGBWNullWhitePixel:
        rgb_2_rgbw_null_white_pixel(w_color_temperature, r, g, b, r_scale,
                                    g_scale, b_scale, out_r, out_g, out_b,
                                    out_w);
        return;
    case kRGBWExactColors:
        rgb_2_rgbw_exact(w_color_temperature, r, g, b, r_scale, g_scale,
                         b_scale, out_r, out_g, out_b, out_w);
        return;
    case kRGBWBoostedWhite:
        rgb_2_rgbw_white_boosted(w_color_temperature, r, g, b, r_scale, g_scale,
                                 b_scale, out_r, out_g, out_b, out_w);
        return;
    case kRGBWMaxBrightness:
        rgb_2_rgbw_max_brightness(w_color_temperature, r, g, b, r_scale,
                                  g_scale, b_scale, out_r, out_g, out_b, out_w);
        return;
    case kRGBWUserFunction:
        rgb_2_rgbw_user_function(w_color_temperature, r, g, b, r_scale, g_scale,
                                 b_scale, out_r, out_g, out_b, out_w);
        return;
    }
    rgb_2_rgbw_null_white_pixel(w_color_temperature, r, g, b, r_scale, g_scale,
                                b_scale, out_r, out_g, out_b, out_w);
}
References kRGBWBoostedWhite, kRGBWExactColors, kRGBWInvalid, kRGBWMaxBrightness, kRGBWNullWhitePixel, kRGBWUserFunction, rgb_2_rgbw_exact(), rgb_2_rgbw_max_brightness(), rgb_2_rgbw_null_white_pixel(), rgb_2_rgbw_user_function(), and rgb_2_rgbw_white_boosted().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), and rgb_2_rgbw().
rgb_2_rgbw() [2/2]
template<RGBW_MODE MODE> FASTLED_FORCE_INLINE void rgb_2_rgbw (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Definition at line 185 of file rgbw.h.
{
    // We trust that the compiler will inline all of this.
    rgb_2_rgbw(MODE, w_color_temperature, r, g, b, r_scale, g_scale, b_scale,
               out_r, out_g, out_b, out_w);
}
References rgb_2_rgbw().
rgb_2_rgbw_exact()
void rgb_2_rgbw_exact (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Converts RGB to RGBW using a color transfer method from saturated color channels to white.
This is designed to produce the most accurate white point for a given color temperature and reduces power usage of the chip since a white led is much more efficient than three color channels of the same power mixing together. However the pixel will never achieve full brightness since the white channel is 3x more efficient than the color channels mixed together, so in this mode the max brightness of a given pixel is reduced.
RGB(255, 255, 255) -> RGBW(0, 0, 0, 85)
RGB(255, 0, 0) -> RGBW(255, 0, 0, 0)
Definition at line 40 of file rgbw.cpp.
{
    (void)w_color_temperature;
    r = scale8(r, r_scale);
    g = scale8(g, g_scale);
    b = scale8(b, b_scale);
    uint8_t min_component = min3(r, g, b);
    *out_r = r - min_component;
    *out_g = g - min_component;
    *out_b = b - min_component;
    *out_w = min_component;
}
References anonymous_namespace{rgbw.cpp}::min3(), and scale8().
Referenced by rgb_2_rgbw(), and set_rgb_2_rgbw_function().
rgb_2_rgbw_max_brightness()
void rgb_2_rgbw_max_brightness (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
The minimum brigthness of the RGB channels is used to set the W channel.
This will allow the max brightness of the led chipset to be used. However the leds will appear over-desaturated in this mode.
RGB(255, 255, 255) -> RGBW(255, 255, 255, 255)
RGB(1, 0, 0) -> RGBW(1, 0, 0, 1)
Definition at line 55 of file rgbw.cpp.
{
    (void)w_color_temperature;
    *out_r = scale8(r, r_scale);
    *out_g = scale8(g, g_scale);
    *out_b = scale8(b, b_scale);
    *out_w = min3(r, g, b);
}
References anonymous_namespace{rgbw.cpp}::min3(), and scale8().
Referenced by rgb_2_rgbw().
rgb_2_rgbw_null_white_pixel()
void rgb_2_rgbw_null_white_pixel (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Converts RGB to RGBW with the W channel set to black, always.
RGB(255, 255, 255) -> RGBW(255, 255, 255, 0)
Definition at line 66 of file rgbw.cpp.
{
    (void)w_color_temperature;
    *out_r = scale8(r, r_scale);
    *out_g = scale8(g, g_scale);
    *out_b = scale8(b, b_scale);
    *out_w = 0;
}
References scale8().
Referenced by rgb_2_rgbw().
rgb_2_rgbw_user_function()
void rgb_2_rgbw_user_function (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Definition at line 125 of file rgbw.cpp.
{
    g_user_function(w_color_temperature, r, g, b, r_scale, g_scale, b_scale,
                    out_r, out_g, out_b, out_w);
}
References g_user_function.
Referenced by rgb_2_rgbw().
rgb_2_rgbw_white_boosted()
void rgb_2_rgbw_white_boosted (uint16_t w_color_temperature, uint8_t r, uint8_t g, uint8_t b, uint8_t r_scale, uint8_t g_scale, uint8_t b_scale, uint8_t * out_r, uint8_t * out_g, uint8_t * out_b, uint8_t * out_w)
Converts RGB to RGBW with a boosted white channel.
Definition at line 78 of file rgbw.cpp.
{
    (void)w_color_temperature;
    r = scale8(r, r_scale);
    g = scale8(g, g_scale);
    b = scale8(b, b_scale);
    uint8_t min_component = min3(r, g, b);
    uint8_t w;
    bool is_min = true;
    if (min_component <= 84) {
        w = 3 * min_component;
    } else {
        w = 255;
        is_min = false;
    }
    uint8_t r_prime;
    uint8_t g_prime;
    uint8_t b_prime;
    if (is_min) {
        r_prime = r - min_component;
        g_prime = g - min_component;
        b_prime = b - min_component;
    } else {
        uint8_t w3 = divide_by_3(w);
        r_prime = r - w3;
        g_prime = g - w3;
        b_prime = b - w3;
    }
    *out_r = r_prime;
    *out_g = g_prime;
    *out_b = b_prime;
    *out_w = w;
}
References anonymous_namespace{rgbw.cpp}::divide_by_3(), anonymous_namespace{rgbw.cpp}::min3(), and scale8().
Referenced by rgb_2_rgbw().
rgbw_partial_reorder()
void rgbw_partial_reorder (EOrderW w_placement, uint8_t b0, uint8_t b1, uint8_t b2, uint8_t w, uint8_t * out_b0, uint8_t * out_b1, uint8_t * out_b2, uint8_t * out_b3)
Definition at line 133 of file rgbw.cpp.
{
    uint8_t out[4] = {b0, b1, b2, 0};
    switch (w_placement) {
    // unrolled loop for speed.
    case W3:
        out[3] = w;
        break;
    case W2:
        out[3] = out[2];  // memmove and copy.
        out[2] = w;
        break;
    case W1:
        out[3] = out[2];
        out[2] = out[1];
        out[1] = w;
        break;
    case W0:
        out[3] = out[2];
        out[2] = out[1];
        out[1] = out[0];
        out[0] = w;
        break;
    }
    *out_b0 = out[0];
    *out_b1 = out[1];
    *out_b2 = out[2];
    *out_b3 = out[3];
}
References W0, W1, W2, and W3.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW().
set_rgb_2_rgbw_function()
void set_rgb_2_rgbw_function (rgb_2_rgbw_function func)
Definition at line 117 of file rgbw.cpp.
{
    if (func == nullptr) {
        g_user_function = rgb_2_rgbw_exact;
        return;
    }
    g_user_function = func;
}
References g_user_function, and rgb_2_rgbw_exact().