FastLED: /home/runner/work/FastLED/FastLED/examples/wasm/wasm.ino File Reference
wasm.ino File Reference
Detailed Description
Demonstrates an advanced ino file with multiple effects and UI elements.
Author
Zach Vorhies
This sketch is fully compatible with the FastLED web compiler. To use it do the following:
Install Fastled: pip install fastled
cd into this examples page.
Run the FastLED web compiler at root: fastled
When the compiler is done a web page will open.
Definition in file wasm.ino.
#include <stdio.h>
#include <string>
#include <FastLED.h>
#include "fx/2d/noisepalette.h"
#include "fl/json.h"
#include "fl/slice.h"
#include "fx/fx_engine.h"
#include "fx/2d/animartrix.hpp"
#include "fl/ui.h"
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define GRID_SERPENTINE false
#define LED_PIN 3
#define MATRIX_HEIGHT 100
#define MATRIX_WIDTH 100
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
#define SCALE 20
#define SPEED 30
Functions
UIDescription description ("This example combines two features of FastLED to produce a remarkable range of effects from a relatively small amount of code. This example combines FastLED's color palette lookup functions with FastLED's Perlin noise generator, and the combination is extremely powerful")
void loop ()
void setup ()
Variables
Animartrix animartrix (xyMap, POLAR_WAVES)
UISlider brightness ("Brightness", 255, 0, 255)
UIButton changeFx ("Switch between Noise & Animartrix")
UIButton changePalette ("Noise - Next Palette")
UICheckbox changePallete ("Noise - Auto Palette", true)
UISlider changePalletTime ("Noise - Time until next random Palette", 5, 1, 100)
FxEngine fxEngine (NUM_LEDS)
UINumberField fxIndex ("Animartrix - index", 0, 0, NUM_ANIMATIONS)
UICheckbox isOff ("Off", false)
CRGB leds [NUM_LEDS]
NoisePalette noisePalette = NoisePalette(xyMap)
UISlider scale ("Noise - Scale", 20, 1, 100)
UISlider speed ("Noise - Speed", 15, 1, 50)
UISlider timeSpeed ("Time Speed", 1, -10, 10,.1)
UITitle title ("FastLED Wasm Demo")
XYMap xyMap = XYMap::constructRectangularGrid(MATRIX_WIDTH, MATRIX_HEIGHT)
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 28 of file wasm.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 29 of file wasm.ino.
Referenced by setup().
GRID_SERPENTINE
#define GRID_SERPENTINE false
Definition at line 33 of file wasm.ino.
LED_PIN
#define LED_PIN 3
Definition at line 27 of file wasm.ino.
Referenced by setup().
MATRIX_HEIGHT
#define MATRIX_HEIGHT 100
Definition at line 32 of file wasm.ino.
MATRIX_WIDTH
#define MATRIX_WIDTH 100
Definition at line 31 of file wasm.ino.
NUM_LEDS
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Definition at line 35 of file wasm.ino.
Referenced by setup().
SCALE
#define SCALE 20
Definition at line 66 of file wasm.ino.
SPEED
#define SPEED 30
Definition at line 72 of file wasm.ino.
Function Documentation
description()
UIDescription description ("This example combines two features of FastLED to produce a remarkable range of effects from a relatively small amount of code. This example combines FastLED's color palette lookup functions with FastLED's Perlin noise generator, and the combination is extremely powerful")
loop()
void loop ()
Definition at line 110 of file wasm.ino.
            {
    FastLED.setBrightness(!isOff ? brightness.as<uint8_t>() : 0);
    noisePalette.setSpeed(speed);
    noisePalette.setScale(scale);
    fxEngine.setSpeed(timeSpeed);
    if (changeFx) {
        fxEngine.nextFx();
    }
    static int frame = 0;
    EVERY_N_MILLISECONDS_DYNAMIC(changePalletTime.as<int>() * 1000) {
        if (changePallete) {
            noisePalette.changeToRandomPalette();
        }
    }
    if (changePalette) {
        noisePalette.changeToRandomPalette();
    }
    static int lastFxIndex = -1;
    if (fxIndex.value() != lastFxIndex) {
        lastFxIndex = fxIndex;
        animartrix.fxSet(fxIndex);
    }
    fxEngine.draw(millis(), leds);
    FastLED.show();
    frame++;
}
References animartrix, fl::UISlider::as(), brightness, changeFx, changePalette, changePallete, changePalletTime, fl::NoisePalette::changeToRandomPalette(), fl::FxEngine::draw(), EVERY_N_MILLISECONDS_DYNAMIC, FastLED, fxEngine, fxIndex, fl::Animartrix::fxSet(), isOff, leds, fl::FxEngine::nextFx(), noisePalette, scale, CFastLED::setBrightness(), fl::NoisePalette::setScale(), fl::FxEngine::setSpeed(), fl::NoisePalette::setSpeed(), CFastLED::show(), speed, timeSpeed, and fl::UINumberField::value().
setup()
void setup ()
Definition at line 95 of file wasm.ino.
             {
    Serial.begin(115200);
    Serial.println("Sketch setup");
    FastLED.addLeds<WS2811, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setCorrection(TypicalLEDStrip)
        .setScreenMap(xyMap);
    Serial.println("FastLED setup done");
    FastLED.setBrightness(brightness);
    //noisePalette.setSpeed(speed);
    noisePalette.setScale(scale);
    fxEngine.addFx(animartrix);
    fxEngine.addFx(noisePalette);
    Serial.println("Sketch setup done");
}
References fl::FxEngine::addFx(), CFastLED::addLeds(), animartrix, brightness, COLOR_ORDER, FastLED, fxEngine, LED_PIN, leds, noisePalette, NUM_LEDS, scale, CFastLED::setBrightness(), fl::NoisePalette::setScale(), TypicalLEDStrip, and xyMap.
Variable Documentation
animartrix
Animartrix animartrix(xyMap, POLAR_WAVES) (xyMap , POLAR_WAVES)
Referenced by loop(), and setup().
brightness
UISlider brightness("Brightness", 255, 0, 255) ("Brightness" , 255 , 0 , 255)
Referenced by loop(), and setup().
changeFx
UIButton changeFx("Switch between Noise & Animartrix") ("Switch between Noise & Animartrix")
Referenced by loop().
changePalette
UIButton changePalette("Noise - Next Palette") ("Noise - Next Palette")
Referenced by loop().
changePallete
UICheckbox changePallete("Noise - Auto Palette", true) ("Noise - Auto Palette" , true)
Referenced by loop().
changePalletTime
UISlider changePalletTime("Noise - Time until next random Palette", 5, 1, 100) ("Noise - Time until next random Palette" , 5 , 1 , 100)
Referenced by loop().
fxEngine
FxEngine fxEngine(NUM_LEDS) (NUM_LEDS)
Referenced by loop(), and setup().
fxIndex
UINumberField fxIndex("Animartrix - index", 0, 0, NUM_ANIMATIONS) ("Animartrix - index" , 0 , 0 , NUM_ANIMATIONS)
Referenced by loop().
isOff
UICheckbox isOff("Off", false) ("Off" , false)
Referenced by loop().
leds
CRGB leds[NUM_LEDS]
Definition at line 74 of file wasm.ino.
Referenced by loop(), and setup().
noisePalette
NoisePalette noisePalette = NoisePalette(xyMap)
Definition at line 76 of file wasm.ino.
Referenced by loop(), and setup().
scale
UISlider scale("Noise - Scale", 20, 1, 100) ("Noise - Scale" , 20 , 1 , 100)
Referenced by loop(), and setup().
speed
UISlider speed("Noise - Speed", 15, 1, 50) ("Noise - Speed" , 15 , 1 , 50)
Referenced by loop().
timeSpeed
UISlider timeSpeed("Time Speed", 1, -10, 10,.1) ("Time Speed" , 1 , - 10, 10 , . 1)
Referenced by loop().
title
UITitle title("FastLED Wasm Demo") ("FastLED Wasm Demo")
xyMap
XYMap xyMap = XYMap::constructRectangularGrid(MATRIX_WIDTH, MATRIX_HEIGHT)
Definition at line 75 of file wasm.ino.
Referenced by setup().