FastLED: Palette Color Functions
Palette Color Functions
Color Palettes
Detailed Description
Functions to retrieve smooth color data from palettes
Enumerations
enum TBlendType { NOBLEND =0 , LINEARBLEND =1 , LINEARBLEND_NOWRAP =2 }
Color interpolation options for palette.
Functions
CHSV ColorFromPalette (const CHSVPalette16 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CHSV ColorFromPalette (const CHSVPalette256 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=NOBLEND)
Get a color from a palette.
CHSV ColorFromPalette (const CHSVPalette32 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CRGB ColorFromPalette (const CRGBPalette16 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CRGB ColorFromPalette (const CRGBPalette256 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=NOBLEND)
Get a color from a palette.
CRGB ColorFromPalette (const CRGBPalette32 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CRGB ColorFromPalette (const TProgmemRGBPalette16 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CRGB ColorFromPalette (const TProgmemRGBPalette32 &pal, uint8_t index, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Get a color from a palette.
CRGB ColorFromPaletteExtended (const CRGBPalette16 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Same as ColorFromPalette, but with uint16_t index to give greater precision.
CRGB ColorFromPaletteExtended (const CRGBPalette256 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPaletteExtended (const CRGBPalette32 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Same as ColorFromPalette, but higher precision.
template<typename PALETTE >
void fill_palette (CRGB *L, uint16_t N, uint8_t startIndex, uint8_t incIndex, const PALETTE &pal, uint8_t brightness=255, TBlendType blendType=LINEARBLEND)
Fill a range of LEDs with a sequence of entries from a palette.
template<typename PALETTE >
void fill_palette_circular (CRGB *L, uint16_t N, uint8_t startIndex, const PALETTE &pal, uint8_t brightness=255, TBlendType blendType=LINEARBLEND, bool reversed=false)
Fill a range of LEDs with a sequence of entries from a palette, so that the entire palette smoothly covers the range of LEDs.
template<typename PALETTE >
void map_data_into_colors_through_palette (uint8_t *dataArray, uint16_t dataCount, CRGB *targetColorArray, const PALETTE &pal, uint8_t brightness=255, uint8_t opacity=255, TBlendType blendType=LINEARBLEND)
Maps an array of palette color indexes into an array of LED colors.
void nblendPaletteTowardPalette (CRGBPalette16 &currentPalette, CRGBPalette16 &targetPalette, uint8_t maxChanges=24)
Alter one palette by making it slightly more like a "target palette".
Enumeration Type Documentation
TBlendType
enum TBlendType
Color interpolation options for palette.
Enumerator
NOBLEND
No interpolation between palette entries.
LINEARBLEND
Linear interpolation between palette entries, with wrap-around from end to the beginning again.
LINEARBLEND_NOWRAP
Linear interpolation between palette entries, but no wrap-around.
Definition at line 1991 of file colorutils.h.
             {
    NOBLEND=0,
    LINEARBLEND=1,
    LINEARBLEND_NOWRAP=2
} TBlendType;
Function Documentation
ColorFromPalette() [1/8]
CHSV ColorFromPalette (const CHSVPalette16 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 1113 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 239);  // Blend range is affected by lo4 blend of values, remap to avoid wrapping
   }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    //  CRGB rgb1 = pal[ hi4];
    const CHSV* entry = &(pal[0]) + hi4;
    uint8_t hue1   = entry->hue;
    uint8_t sat1   = entry->sat;
    uint8_t val1   = entry->val;
    uint8_t blend = lo4 && (blendType != NOBLEND);
    if( blend ) {
        if( hi4 == 15 ) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        uint8_t hue2  = entry->hue;
        uint8_t sat2  = entry->sat;
        uint8_t val2  = entry->val;
        // Now some special casing for blending to or from
        // either black or white.  Black and white don't have
        // proper 'hue' of their own, so when ramping from
        // something else to/from black/white, we set the 'hue'
        // of the black/white color to be the same as the hue
        // of the other color, so that you get the expected
        // brightness or saturation ramp, with hue staying
        // constant:
        // If we are starting from white (sat=0)
        // or black (val=0), adopt the target hue.
        if( sat1 == 0 || val1 == 0) {
            hue1 = hue2;
        }
        // If we are ending at white (sat=0)
        // or black (val=0), adopt the starting hue.
        if( sat2 == 0 || val2 == 0) {
            hue2 = hue1;
        }
        sat1  = scale8_LEAVING_R1_DIRTY( sat1, f1);
        val1  = scale8_LEAVING_R1_DIRTY( val1, f1);
        sat2  = scale8_LEAVING_R1_DIRTY( sat2, f2);
        val2  = scale8_LEAVING_R1_DIRTY( val2, f2);
        //    cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        sat1  += sat2;
        val1  += val2;
        uint8_t deltaHue = (uint8_t)(hue2 - hue1);
        if( deltaHue & 0x80 ) {
          // go backwards
          hue1 -= scale8( 256 - deltaHue, f2);
        } else {
          // go forwards
          hue1 += scale8( deltaHue, f2);
        }
        cleanup_R1();
    }
    if( brightness != 255) {
        val1 = scale8_video( val1, brightness);
    }
    return CHSV( hue1, sat1, val1);
}
References blend(), brightness, cleanup_R1(), LINEARBLEND_NOWRAP, lsrX4(), map8(), NOBLEND, scale8(), scale8_LEAVING_R1_DIRTY(), and scale8_video().
ColorFromPalette() [2/8]
CHSV ColorFromPalette (const CHSVPalette256 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = NOBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 1294 of file colorutils.cpp.
{
    CHSV hsv = *( &(pal[0]) + index );
    if( brightness != 255) {
        hsv.value = scale8_video( hsv.value, brightness);
    }
    return hsv;
}
References brightness, and scale8_video().
ColorFromPalette() [3/8]
CHSV ColorFromPalette (const CHSVPalette32 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 1201 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 247);  // Blend range is affected by lo3 blend of values, remap to avoid wrapping
   }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    uint8_t hi5XsizeofCHSV = hi5 * sizeof(CHSV);
    const CHSV* entry = (CHSV*)( (uint8_t*)(&(pal[0])) + hi5XsizeofCHSV);
    uint8_t hue1   = entry->hue;
    uint8_t sat1   = entry->sat;
    uint8_t val1   = entry->val;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if( blend ) {
        if( hi5 == 31 ) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t hue2  = entry->hue;
        uint8_t sat2  = entry->sat;
        uint8_t val2  = entry->val;
        // Now some special casing for blending to or from
        // either black or white.  Black and white don't have
        // proper 'hue' of their own, so when ramping from
        // something else to/from black/white, we set the 'hue'
        // of the black/white color to be the same as the hue
        // of the other color, so that you get the expected
        // brightness or saturation ramp, with hue staying
        // constant:
        // If we are starting from white (sat=0)
        // or black (val=0), adopt the target hue.
        if( sat1 == 0 || val1 == 0) {
            hue1 = hue2;
        }
        // If we are ending at white (sat=0)
        // or black (val=0), adopt the starting hue.
        if( sat2 == 0 || val2 == 0) {
            hue2 = hue1;
        }
        sat1  = scale8_LEAVING_R1_DIRTY( sat1, f1);
        val1  = scale8_LEAVING_R1_DIRTY( val1, f1);
        sat2  = scale8_LEAVING_R1_DIRTY( sat2, f2);
        val2  = scale8_LEAVING_R1_DIRTY( val2, f2);
        //    cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        sat1  += sat2;
        val1  += val2;
        uint8_t deltaHue = (uint8_t)(hue2 - hue1);
        if( deltaHue & 0x80 ) {
            // go backwards
            hue1 -= scale8( 256 - deltaHue, f2);
        } else {
            // go forwards
            hue1 += scale8( deltaHue, f2);
        }
        cleanup_R1();
    }
    if( brightness != 255) {
        val1 = scale8_video( val1, brightness);
    }
    return CHSV( hue1, sat1, val1);
}
References blend(), brightness, cleanup_R1(), LINEARBLEND_NOWRAP, map8(), NOBLEND, scale8(), scale8_LEAVING_R1_DIRTY(), and scale8_video().
ColorFromPalette() [4/8]
CRGB ColorFromPalette (const CRGBPalette16 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 644 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 239);  // Blend range is affected by lo4 blend of values, remap to avoid wrapping
   }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    // const CRGB* entry = &(pal[0]) + hi4;
    // since hi4 is always 0..15, hi4 * sizeof(CRGB) can be a single-byte value,
    // instead of the two byte 'int' that avr-gcc defaults to.
    // So, we multiply hi4 X sizeof(CRGB), giving hi4XsizeofCRGB;
    uint8_t hi4XsizeofCRGB = hi4 * sizeof(CRGB);
    // We then add that to a base array pointer.
    const CRGB* entry = (CRGB*)( (uint8_t*)(&(pal[0])) + hi4XsizeofCRGB);
    uint8_t blend = lo4 && (blendType != NOBLEND);
    uint8_t red1   = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1  = entry->blue;
    if( blend ) {
        if( hi4 == 15 ) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        //    rgb1.nscale8(f1);
        uint8_t red2   = entry->red;
        red1   = scale8_LEAVING_R1_DIRTY( red1,   f1);
        red2   = scale8_LEAVING_R1_DIRTY( red2,   f2);
        red1   += red2;
        uint8_t green2 = entry->green;
        green1 = scale8_LEAVING_R1_DIRTY( green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY( green2, f2);
        green1 += green2;
        uint8_t blue2  = entry->blue;
        blue1  = scale8_LEAVING_R1_DIRTY( blue1,  f1);
        blue2  = scale8_LEAVING_R1_DIRTY( blue2,  f2);
        blue1  += blue2;
        cleanup_R1();
    }
    if( brightness != 255) {
        if( brightness ) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full scale8_video logic;
            // we can just to scale8 and then add one (unless scale8 fixed) to all nonzero inputs.
            if( red1 )   {
                red1 = scale8_LEAVING_R1_DIRTY( red1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++red1;
#endif
            }
            if( green1 ) {
                green1 = scale8_LEAVING_R1_DIRTY( green1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++green1;
#endif
            }
            if( blue1 )  {
                blue1 = scale8_LEAVING_R1_DIRTY( blue1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB( red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), LINEARBLEND_NOWRAP, lsrX4(), map8(), NOBLEND, and scale8_LEAVING_R1_DIRTY().
Referenced by bpm(), fl::DemoReel100::bpm(), computeOneTwinkle(), fl::TwinkleFox::computeOneTwinkle(), fl::Fire2012::draw(), fill_palette(), fill_palette_circular(), FillLEDsFromPaletteColors(), Fire2012WithPalette(), Fire2023(), map_data_into_colors_through_palette(), fl::NoisePalette::mapNoiseToLEDsUsingPalette(), mapNoiseToLEDsUsingPalette(), fl::Pacifica::pacifica_one_layer(), pacifica_one_layer(), UpscalePalette(), UpscalePalette(), UpscalePalette(), and UpscalePalette().
ColorFromPalette() [5/8]
CRGB ColorFromPalette (const CRGBPalette256 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = NOBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 1046 of file colorutils.cpp.
{
    const CRGB* entry = &(pal[0]) + index;
    uint8_t red   = entry->red;
    uint8_t green = entry->green;
    uint8_t blue  = entry->blue;
    if( brightness != 255) {
        ++brightness; // adjust for rounding
        red   = scale8_video_LEAVING_R1_DIRTY( red,   brightness);
        green = scale8_video_LEAVING_R1_DIRTY( green, brightness);
        blue  = scale8_video_LEAVING_R1_DIRTY( blue,  brightness);
        cleanup_R1();
    }
    return CRGB( red, green, blue);
}
References brightness, cleanup_R1(), and scale8_video_LEAVING_R1_DIRTY().
ColorFromPalette() [6/8]
CRGB ColorFromPalette (const CRGBPalette32 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 862 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 247);  // Blend range is affected by lo3 blend of values, remap to avoid wrapping
   }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    // const CRGB* entry = &(pal[0]) + hi5;
    // since hi5 is always 0..31, hi4 * sizeof(CRGB) can be a single-byte value,
    // instead of the two byte 'int' that avr-gcc defaults to.
    // So, we multiply hi5 X sizeof(CRGB), giving hi5XsizeofCRGB;
    uint8_t hi5XsizeofCRGB = hi5 * sizeof(CRGB);
    // We then add that to a base array pointer.
    const CRGB* entry = (CRGB*)( (uint8_t*)(&(pal[0])) + hi5XsizeofCRGB);
    uint8_t red1   = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1  = entry->blue;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if( blend ) {
        if( hi5 == 31 ) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t red2   = entry->red;
        red1   = scale8_LEAVING_R1_DIRTY( red1,   f1);
        red2   = scale8_LEAVING_R1_DIRTY( red2,   f2);
        red1   += red2;
        uint8_t green2 = entry->green;
        green1 = scale8_LEAVING_R1_DIRTY( green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY( green2, f2);
        green1 += green2;
        uint8_t blue2  = entry->blue;
        blue1  = scale8_LEAVING_R1_DIRTY( blue1,  f1);
        blue2  = scale8_LEAVING_R1_DIRTY( blue2,  f2);
        blue1  += blue2;
        cleanup_R1();
    }
    if( brightness != 255) {
        if( brightness ) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full scale8_video logic;
            // we can just to scale8 and then add one (unless scale8 fixed) to all nonzero inputs.
            if( red1 )   {
                red1 = scale8_LEAVING_R1_DIRTY( red1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++red1;
#endif
            }
            if( green1 ) {
                green1 = scale8_LEAVING_R1_DIRTY( green1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++green1;
#endif
            }
            if( blue1 )  {
                blue1 = scale8_LEAVING_R1_DIRTY( blue1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB( red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), LINEARBLEND_NOWRAP, map8(), NOBLEND, and scale8_LEAVING_R1_DIRTY().
ColorFromPalette() [7/8]
CRGB ColorFromPalette (const TProgmemRGBPalette16 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 779 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 239);  // Blend range is affected by lo4 blend of values, remap to avoid wrapping
   }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    CRGB entry(FL_PGM_READ_DWORD_NEAR( &(pal[0]) + hi4 ));
    uint8_t red1   = entry.red;
    uint8_t green1 = entry.green;
    uint8_t blue1  = entry.blue;
    uint8_t blend = lo4 && (blendType != NOBLEND);
    if( blend ) {
        if( hi4 == 15 ) {
            entry =   FL_PGM_READ_DWORD_NEAR( &(pal[0]) );
        } else {
            entry =   FL_PGM_READ_DWORD_NEAR( &(pal[1]) + hi4 );
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        uint8_t red2   = entry.red;
        red1   = scale8_LEAVING_R1_DIRTY( red1,   f1);
        red2   = scale8_LEAVING_R1_DIRTY( red2,   f2);
        red1   += red2;
        uint8_t green2 = entry.green;
        green1 = scale8_LEAVING_R1_DIRTY( green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY( green2, f2);
        green1 += green2;
        uint8_t blue2  = entry.blue;
        blue1  = scale8_LEAVING_R1_DIRTY( blue1,  f1);
        blue2  = scale8_LEAVING_R1_DIRTY( blue2,  f2);
        blue1  += blue2;
        cleanup_R1();
    }
    if( brightness != 255) {
        if( brightness ) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full scale8_video logic;
            // we can just to scale8 and then add one (unless scale8 fixed) to all nonzero inputs.
            if( red1 )   {
                red1 = scale8_LEAVING_R1_DIRTY( red1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++red1;
#endif
            }
            if( green1 ) {
                green1 = scale8_LEAVING_R1_DIRTY( green1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++green1;
#endif
            }
            if( blue1 )  {
                blue1 = scale8_LEAVING_R1_DIRTY( blue1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB( red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), FL_PGM_READ_DWORD_NEAR, LINEARBLEND_NOWRAP, lsrX4(), map8(), NOBLEND, and scale8_LEAVING_R1_DIRTY().
ColorFromPalette() [8/8]
CRGB ColorFromPalette (const TProgmemRGBPalette32 & pal, uint8_t index, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Get a color from a palette.
These are the main functions for getting and using palette colors. Regardless of the number of entries in the base palette, this function will interpolate between entries to turn the discrete colors into a smooth gradient.
Parameters
pal the palette to retrieve the color from
index the position in the palette to retrieve the color for (0-255)
brightness optional brightness value to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 957 of file colorutils.cpp.
{
   if ( blendType == LINEARBLEND_NOWRAP) {
     index = map8(index, 0, 247);  // Blend range is affected by lo3 blend of values, remap to avoid wrapping
   }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    CRGB entry(FL_PGM_READ_DWORD_NEAR( &(pal[0]) + hi5));
    uint8_t red1   = entry.red;
    uint8_t green1 = entry.green;
    uint8_t blue1  = entry.blue;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if( blend ) {
        if( hi5 == 31 ) {
            entry =   FL_PGM_READ_DWORD_NEAR( &(pal[0]) );
        } else {
            entry =   FL_PGM_READ_DWORD_NEAR( &(pal[1]) + hi5 );
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t red2   = entry.red;
        red1   = scale8_LEAVING_R1_DIRTY( red1,   f1);
        red2   = scale8_LEAVING_R1_DIRTY( red2,   f2);
        red1   += red2;
        uint8_t green2 = entry.green;
        green1 = scale8_LEAVING_R1_DIRTY( green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY( green2, f2);
        green1 += green2;
        uint8_t blue2  = entry.blue;
        blue1  = scale8_LEAVING_R1_DIRTY( blue1,  f1);
        blue2  = scale8_LEAVING_R1_DIRTY( blue2,  f2);
        blue1  += blue2;
        cleanup_R1();
    }
    if( brightness != 255) {
        if( brightness ) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full scale8_video logic;
            // we can just to scale8 and then add one (unless scale8 fixed) to all nonzero inputs.
            if( red1 )   {
                red1 = scale8_LEAVING_R1_DIRTY( red1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++red1;
#endif
            }
            if( green1 ) {
                green1 = scale8_LEAVING_R1_DIRTY( green1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++green1;
#endif
            }
            if( blue1 )  {
                blue1 = scale8_LEAVING_R1_DIRTY( blue1, brightness);
#if !(FASTLED_SCALE8_FIXED==1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB( red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), FL_PGM_READ_DWORD_NEAR, LINEARBLEND_NOWRAP, map8(), NOBLEND, and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [1/3]
CRGB ColorFromPaletteExtended (const CRGBPalette16 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Same as ColorFromPalette, but with uint16_t index to give greater precision.
Author
https://github.com/generalelectrix
See also
https://github.com/FastLED/FastLED/pull/202
https://wokwi.com/projects/285170662915441160
https://wokwi.com/projects/407831886158110721
Definition at line 733 of file colorutils.cpp.
{
  // Extract the four most significant bits of the index as a palette index.
  uint8_t index_4bit = index >> 12;
  // Calculate the 8-bit offset from the palette index.
  uint8_t offset = (uint8_t)(index >> 4);
  // Get the palette entry from the 4-bit index
  const CRGB* entry = &(pal[0]) + index_4bit;
  uint8_t red1   = entry->red;
  uint8_t green1 = entry->green;
  uint8_t blue1  = entry->blue;
  uint8_t blend = offset && (blendType != NOBLEND);
  if (blend) {
    if (index_4bit == 15) {
      entry = &(pal[0]);
    } else {
      entry++;
    }
    // Calculate the scaling factor and scaled values for the lower palette value.
    uint8_t f1 = 255 - offset;
    red1   = scale8_LEAVING_R1_DIRTY(red1,   f1);
    green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
    blue1  = scale8_LEAVING_R1_DIRTY(blue1,  f1);
    // Calculate the scaled values for the neighbouring palette value.
    uint8_t red2   = entry->red;
    uint8_t green2 = entry->green;
    uint8_t blue2  = entry->blue;
    red2   = scale8_LEAVING_R1_DIRTY(red2,   offset);
    green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
    blue2  = scale8_LEAVING_R1_DIRTY(blue2,  offset);
    cleanup_R1();
    // These sums can't overflow, so no qadd8 needed.
    red1   += red2;
    green1 += green2;
    blue1  += blue2;
  }
  if (brightness != 255) {
    // nscale8x3_video(red1, green1, blue1, brightness);
    nscale8x3(red1, green1, blue1, brightness);
  }
  return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), NOBLEND, nscale8x3(), and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [2/3]
CRGB ColorFromPaletteExtended (const CRGBPalette256 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Definition at line 1065 of file colorutils.cpp.
{
  // Extract the eight most significant bits of the index as a palette index.
  uint8_t index_8bit = index >> 8;
  // Calculate the 8-bit offset from the palette index.
  uint8_t offset = index & 0xff;
  // Get the palette entry from the 8-bit index
  const CRGB* entry = &(pal[0]) + index_8bit;
  uint8_t red1   = entry->red;
  uint8_t green1 = entry->green;
  uint8_t blue1  = entry->blue;
  uint8_t blend = offset && (blendType != NOBLEND);
  if (blend) {
    if (index_8bit == 255) {
      entry = &(pal[0]);
    } else {
      entry++;
    }
    // Calculate the scaling factor and scaled values for the lower palette value.
    uint8_t f1 = 255 - offset;
    red1   = scale8_LEAVING_R1_DIRTY(red1,   f1);
    green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
    blue1  = scale8_LEAVING_R1_DIRTY(blue1,  f1);
    // Calculate the scaled values for the neighbouring palette value.
    uint8_t red2   = entry->red;
    uint8_t green2 = entry->green;
    uint8_t blue2  = entry->blue;
    red2   = scale8_LEAVING_R1_DIRTY(red2,   offset);
    green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
    blue2  = scale8_LEAVING_R1_DIRTY(blue2,  offset);
    cleanup_R1();
    // These sums can't overflow, so no qadd8 needed.
    red1   += red2;
    green1 += green2;
    blue1  += blue2;
  }
  if (brightness != 255) {
    // nscale8x3_video(red1, green1, blue1, brightness);
    nscale8x3(red1, green1, blue1, brightness);
  }
  return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), NOBLEND, nscale8x3(), and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [3/3]
CRGB ColorFromPaletteExtended (const CRGBPalette32 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Same as ColorFromPalette, but higher precision.
Will eventually become the default.
Author
https://github.com/generalelectrix
See also
https://github.com/FastLED/FastLED/pull/202#issuecomment-631333384
https://wokwi.com/projects/285170662915441160
Definition at line 599 of file colorutils.cpp.
{
  // Extract the five most significant bits of the index as a palette index.
  uint8_t index_5bit = (index >> 11);
  // Calculate the 8-bit offset from the palette index.
  uint8_t offset = (uint8_t)(index >> 3);
  // Get the palette entry from the 5-bit index
  const CRGB* entry = &(pal[0]) + index_5bit;
  uint8_t red1   = entry->red;
  uint8_t green1 = entry->green;
  uint8_t blue1  = entry->blue;
  uint8_t blend = offset && (blendType != NOBLEND);
  if (blend) {
    if (index_5bit == 31) {
      entry = &(pal[0]);
    } else {
      entry++;
    }
    // Calculate the scaling factor and scaled values for the lower palette value.
    uint8_t f1 = 255 - offset;
    red1   = scale8_LEAVING_R1_DIRTY(red1,   f1);
    green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
    blue1  = scale8_LEAVING_R1_DIRTY(blue1,  f1);
    // Calculate the scaled values for the neighbouring palette value.
    uint8_t red2   = entry->red;
    uint8_t green2 = entry->green;
    uint8_t blue2  = entry->blue;
    red2   = scale8_LEAVING_R1_DIRTY(red2,   offset);
    green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
    blue2  = scale8_LEAVING_R1_DIRTY(blue2,  offset);
    cleanup_R1();
    // These sums can't overflow, so no qadd8 needed.
    red1   += red2;
    green1 += green2;
    blue1  += blue2;
  }
  if (brightness != 255) {
    nscale8x3_video(red1, green1, blue1, brightness);
  }
  return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), NOBLEND, nscale8x3_video(), and scale8_LEAVING_R1_DIRTY().
fill_palette()
template<typename PALETTE > void fill_palette (CRGB * L, uint16_t N, uint8_t startIndex, uint8_t incIndex, const PALETTE & pal, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND)
Fill a range of LEDs with a sequence of entries from a palette.
Template Parameters
PALETTE the type of the palette used (auto-deduced)
Parameters
L pointer to the LED array to fill
N number of LEDs to fill in the array
startIndex the starting color index in the palette
incIndex how much to increment the palette color index per LED
pal the color palette to pull colors from
brightness brightness value used to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 2094 of file colorutils.h.
{
    uint8_t colorIndex = startIndex;
    for( uint16_t i = 0; i < N; ++i) {
        L[i] = ColorFromPalette( pal, colorIndex, brightness, blendType);
        colorIndex += incIndex;
    }
}
References brightness, and ColorFromPalette().
fill_palette_circular()
template<typename PALETTE > void fill_palette_circular (CRGB * L, uint16_t N, uint8_t startIndex, const PALETTE & pal, uint8_t brightness = 255, TBlendType blendType = LINEARBLEND, bool reversed = false)
Fill a range of LEDs with a sequence of entries from a palette, so that the entire palette smoothly covers the range of LEDs.
Template Parameters
PALETTE the type of the palette used (auto-deduced)
Parameters
L pointer to the LED array to fill
N number of LEDs to fill in the array
startIndex the starting color index in the palette
pal the color palette to pull colors from
brightness brightness value used to scale the resulting color
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
reversed whether to progress through the palette backwards
Definition at line 2117 of file colorutils.h.
{
    if (N == 0) return;  // avoiding div/0
    const uint16_t colorChange = 65535 / N;              // color change for each LED, * 256 for precision
    uint16_t colorIndex = ((uint16_t) startIndex) << 8;  // offset for color index, with precision (*256)
   for (uint16_t i = 0; i < N; ++i) {
        L[i] = ColorFromPalette(pal, (colorIndex >> 8), brightness, blendType);
        if (reversed) colorIndex -= colorChange;
        else colorIndex += colorChange;
    }
}
References brightness, and ColorFromPalette().
map_data_into_colors_through_palette()
template<typename PALETTE > void map_data_into_colors_through_palette (uint8_t * dataArray, uint16_t dataCount, CRGB * targetColorArray, const PALETTE & pal, uint8_t brightness = 255, uint8_t opacity = 255, TBlendType blendType = LINEARBLEND)
Maps an array of palette color indexes into an array of LED colors.
This function provides an easy way to create lightweight color patterns that can be deployed using any palette.
Parameters
dataArray the source array, containing color indexes for the palette
dataCount the number of data elements in the array
targetColorArray the LED array to store the resulting colors into. Must be at least as long as dataCount.
pal the color palette to pull colors from
brightness optional brightness value used to scale the resulting color
opacity optional opacity value for the new color. If this is 255 (default), the new colors will be written to the array directly. Otherwise the existing LED data will be scaled down using CRGB::nscale8_video() and then new colors will be added on top. A higher value means that the new colors will be more visible.
blendType whether to take the palette entries directly (NOBLEND) or blend linearly between palette entries (LINEARBLEND)
Definition at line 2152 of file colorutils.h.
{
    for( uint16_t i = 0; i < dataCount; ++i) {
        uint8_t d = dataArray[i];
        CRGB rgb = ColorFromPalette( pal, d, brightness, blendType);
        if( opacity == 255 ) {
            targetColorArray[i] = rgb;
        } else {
            targetColorArray[i].nscale8( 256 - opacity);
            rgb.nscale8_video( opacity);
            targetColorArray[i] += rgb;
        }
    }
}
References brightness, ColorFromPalette(), CRGB::nscale8(), and CRGB::nscale8_video().
nblendPaletteTowardPalette()
void nblendPaletteTowardPalette (CRGBPalette16 & currentPalette, CRGBPalette16 & targetPalette, uint8_t maxChanges = 24)
Alter one palette by making it slightly more like a "target palette".
Used for palette cross-fades.
It does this by comparing each of the R, G, and B channels of each entry in the current palette to the corresponding entry in the target palette and making small adjustments:
If the CRGB::red channel is too low, it will be increased.
If the CRGB::red channel is too high, it will be slightly reduced.
...and so on and so forth for the CRGB::green and CRGB::blue channels.
Additionally, there are two significant visual improvements to this algorithm implemented here. First is this:
When increasing a channel, it is stepped up by ONE.
When decreasing a channel, it is stepped down by TWO.
Due to the way the eye perceives light, and the way colors are represented in RGB, this produces a more uniform apparent brightness when cross-fading between most palette colors.
The second visual tweak is limiting the number of changes that will be made to the palette at once. If all the palette entries are changed at once, it can give a muddled appearance. However, if only a few palette entries are changed at once, you get a visually smoother transition: in the middle of the cross-fade your current palette will actually contain some colors from the old palette, a few blended colors, and some colors from the new palette.
Parameters
currentPalette the palette to modify
targetPalette the palette to move towards
maxChanges the maximum number of possible palette changes to make to the color channels per call. The limit is 48 (16 color entries times 3 channels each). The default is 24, meaning that only half of the palette entries can be changed per call.
Warning
The palette passed as currentPalette will be modified! Be sure to make a copy beforehand if needed.
Todo
Shouldn't the targetPalette be const?
Definition at line 1365 of file colorutils.cpp.
{
    uint8_t* p1;
    uint8_t* p2;
    uint8_t  changes = 0;
    p1 = (uint8_t*)current.entries;
    p2 = (uint8_t*)target.entries;
    const uint8_t totalChannels = sizeof(CRGBPalette16);
    for( uint8_t i = 0; i < totalChannels; ++i) {
        // if the values are equal, no changes are needed
        if( p1[i] == p2[i] ) { continue; }
        // if the current value is less than the target, increase it by one
        if( p1[i] < p2[i] ) { ++p1[i]; ++changes; }
        // if the current value is greater than the target,
        // increase it by one (or two if it's still greater).
        if( p1[i] > p2[i] ) {
            --p1[i]; ++changes;
            if( p1[i] > p2[i] ) { --p1[i]; }
        }
        // if we've hit the maximum number of changes, exit
        if( changes >= maxChanges) { break; }
    }
}
References CRGBPalette16::entries.
Referenced by fl::TwinkleFox::draw(), and loop().