FastLED: fl::ScaleUp Class Reference
fl::ScaleUp Class Reference
Detailed Description
Definition at line 43 of file scale_up.h.
#include <scale_up.h>
Public Member Functions
ScaleUp (XYMap xymap, Fx2dPtr fx)
void draw (DrawContext context) override
void expand (const CRGB *input, CRGB *output, uint16_t width, uint16_t height, XYMap mXyMap)
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx2d
Fx2d (const XYMap &xyMap)
uint16_t getHeight () const
uint16_t getWidth () const
XYMap & getXYMap ()
const XYMap & getXYMap () const
void setXYMap (const XYMap &xyMap)
uint16_t xyMap (uint16_t x, uint16_t y) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Member Functions
void noExpand (const CRGB *input, CRGB *output, uint16_t width, uint16_t height)
Private Attributes
Fx2dPtr mDelegate
fl::scoped_array< CRGB > mSurface
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx2d
XYMap mXyMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
ScaleUp()
fl::ScaleUp::ScaleUp (XYMap xymap, Fx2dPtr fx)
Definition at line 38 of file scale_up.cpp.
                                        : Fx2d(xymap), mDelegate(fx) {
    // Turn off re-mapping of the delegate's XYMap, since bilinearExpand needs
    // to work in screen coordinates. The final mapping will for this class will
    // still be performed.
    mDelegate->getXYMap().setRectangularGrid();
}
References fl::Fx2d::getXYMap(), and mDelegate.
Member Function Documentation
draw()
void fl::ScaleUp::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 45 of file scale_up.cpp.
{
    if (!mSurface) {
        mSurface.reset(new CRGB[mDelegate->getNumLeds()]);
    }
    DrawContext delegateContext = context;
    delegateContext.leds = mSurface.get();
    mDelegate->draw(delegateContext);
    uint16_t in_w = mDelegate->getWidth();
    uint16_t in_h = mDelegate->getHeight();
    uint16_t out_w = getWidth();
    uint16_t out_h = getHeight();
    ;
    if (in_w == out_w && in_h == out_h) {
        noExpand(mSurface.get(), context.leds, in_w, in_h);
    } else {
        expand(mSurface.get(), context.leds, in_w, in_h, mXyMap);
    }
}
References expand(), fl::scoped_array< T, Deleter >::get(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::_DrawContext::leds, mDelegate, mSurface, fl::Fx2d::mXyMap, noExpand(), and fl::scoped_array< T, Deleter >::reset().
expand()
void fl::ScaleUp::expand (const CRGB * input, CRGB * output, uint16_t width, uint16_t height, XYMap mXyMap)
Definition at line 65 of file scale_up.cpp.
{
#if FASTLED_SCALE_UP == FASTLED_SCALE_UP_ALWAYS_POWER_OF_2
    bilinearExpandPowerOf2(input, output, width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_HIGH_PRECISION
    bilinearExpandArbitrary(input, output, width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_DECIDE_AT_RUNTIME
    bilinearExpand(input, output, width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_FORCE_FLOATING_POINT
    bilinearExpandFloat(input, output, width, height, mXyMap);
#else
#error "Invalid FASTLED_SCALE_UP"
#endif
}
References fl::bilinearExpand(), fl::bilinearExpandArbitrary(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), and fl::Fx2d::mXyMap.
Referenced by draw().
fxName()
fl::Str fl::ScaleUp::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 51 of file scale_up.h.
{ return "scale_up"; }
noExpand()
void fl::ScaleUp::noExpand (const CRGB * input, CRGB * output, uint16_t width, uint16_t height) private
Definition at line 80 of file scale_up.cpp.
{
    uint16_t n = mXyMap.getTotal();
    for (uint16_t w = 0; w < width; w++) {
        for (uint16_t h = 0; h < height; h++) {
            uint16_t idx = mXyMap.mapToIndex(w, h);
            if (idx < n) {
                output[idx] = input[w * height + h];
            }
        }
    }
}
References fl::XYMap::getTotal(), fl::XYMap::mapToIndex(), and fl::Fx2d::mXyMap.
Referenced by draw().
Member Data Documentation
mDelegate
Fx2dPtr fl::ScaleUp::mDelegate private
Definition at line 57 of file scale_up.h.
Referenced by ScaleUp(), and draw().
mSurface
fl::scoped_array<CRGB> fl::ScaleUp::mSurface private
Definition at line 58 of file scale_up.h.
Referenced by draw().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/2d/scale_up.h
/home/runner/work/FastLED/FastLED/src/fx/2d/scale_up.cpp