FastLED: /home/runner/work/FastLED/FastLED/examples/RGBW/RGBW.ino File Reference
RGBW.ino File Reference
#include <FastLED.h>
Macros
#define DATA_PIN 3
#define NUM_LEDS 10
#define TIME_FACTOR_HUE 60
#define TIME_FACTOR_SAT 100
#define TIME_FACTOR_VAL 100
Functions
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Macro Definition Documentation
DATA_PIN
#define DATA_PIN 3
Definition at line 12 of file RGBW.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 10
Definition at line 6 of file RGBW.ino.
Referenced by loop(), and setup().
TIME_FACTOR_HUE
#define TIME_FACTOR_HUE 60
Definition at line 18 of file RGBW.ino.
Referenced by loop().
TIME_FACTOR_SAT
#define TIME_FACTOR_SAT 100
Definition at line 19 of file RGBW.ino.
Referenced by loop().
TIME_FACTOR_VAL
#define TIME_FACTOR_VAL 100
Definition at line 20 of file RGBW.ino.
Referenced by loop().
Function Documentation
loop()
void loop ()
Definition at line 29 of file RGBW.ino.
            {
    uint32_t ms = millis();
    for(int i = 0; i < NUM_LEDS; i++) {
        // Use different noise functions for each LED and each color component
        uint8_t hue = inoise16(ms * TIME_FACTOR_HUE, i * 1000, 0) >> 8;
        uint8_t sat = inoise16(ms * TIME_FACTOR_SAT, i * 2000, 1000) >> 8;
        uint8_t val = inoise16(ms * TIME_FACTOR_VAL, i * 3000, 2000) >> 8;
        // Map the noise to full range for saturation and value
        sat = map(sat, 0, 255, 30, 255);
        val = map(val, 0, 255, 100, 255);
        leds[i] = CHSV(hue, sat, val);
    }
    FastLED.show();
    // Small delay to control the overall speed of the animation
    //FastLED.delay(1);
}
References FastLED, inoise16(), leds, NUM_LEDS, CFastLED::show(), TIME_FACTOR_HUE, TIME_FACTOR_SAT, and TIME_FACTOR_VAL.
setup()
void setup ()
Definition at line 22 of file RGBW.ino.
             {
    Serial.begin(115200);
    FastLED.addLeds<WS2812, DATA_PIN, GRB>(leds, NUM_LEDS).setRgbw(RgbwDefault());
    FastLED.setBrightness(128);  // Set global brightness to 50%
    delay(2000);  // If something ever goes wrong this delay will allow upload.
}
References CFastLED::addLeds(), DATA_PIN, FastLED, GRB, leds, NUM_LEDS, and CFastLED::setBrightness().
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 15 of file RGBW.ino.
Referenced by loop(), and setup().