FastLED: HSV to RGB Conversion Functions
HSV to RGB Conversion Functions
Detailed Description
Functions to convert from the HSV colorspace to the RGB colorspace.
These basically fall into two groups: spectra, and rainbows. pectra and rainbows are not the same thing. Wikipedia has a good llustration that shows a "spectrum" and a "rainbow" side by side:
Source: http://en.wikipedia.org/wiki/Rainbow#Number_of_colours_in_spectrum_or_rainbow
Among other differences, you'll see that a "rainbow" has much more yellow than a plain spectrum. "Classic" LED color washes are spectrum based, and usually show very little yellow.
Take a look Wikipedia's page on HSV color space, with pseudocode for conversion to RGB color space: http://en.wikipedia.org/wiki/HSL_and_HSV
Note that their conversion algorithm, which is (naturally) very popular is in the "maximum brightness at any given hue" style, vs. the "uniform brightness for all hues" style.
You can't have both; either purple is the same brightness as red, e.g:
   red = 0xFF0000
purple = 0x800080
Where you have the same "total light" output. OR purple is "as bright as it can be", e.g.:
   red = 0xFF0000
purple = 0xFF00FF
Where purple is much brighter than red.
The colorspace conversions here try to keep the apparent brightness constant even as the hue varies.
Adafruit's "Wheel" function, discussed here is also of the "constant apparent brightness" variety.
Todo
Provide the "maximum brightness no matter what" variation.
See also
Some good, clear Arduino C code from Kasper Kamperman, which in turn was based on Windows C code from "nico80"
Macros
#define HUE_MAX 191
Max hue accepted for the hsv2rgb_raw() function.
#define HUE_MAX_RAINBOW 255
Max hue accepted for the hsv2rgb_rainbow() function.
#define HUE_MAX_SPECTRUM 255
Max hue accepted for the hsv2rgb_spectrum() function.
Functions
void hsv2rgb_rainbow (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
void hsv2rgb_raw (const struct CHSV &hsv, struct CRGB &rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
void hsv2rgb_raw (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
CRGB hsv2rgb_spectrum (const struct CHSV &hsv)
Inline version of hsv2rgb_spectrum which returns a CRGB object.
void hsv2rgb_spectrum (const struct CHSV &hsv, struct CRGB &rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
void hsv2rgb_spectrum (const struct CHSV *phsv, struct CRGB *prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
CHSV rgb2hsv_approximate (const CRGB &rgb)
Recover approximate HSV values from RGB.
Macro Definition Documentation
HUE_MAX
#define HUE_MAX 191
Max hue accepted for the hsv2rgb_raw() function.
Definition at line 125 of file hsv2rgb.h.
HUE_MAX_RAINBOW
#define HUE_MAX_RAINBOW 255
Max hue accepted for the hsv2rgb_rainbow() function.
Definition at line 73 of file hsv2rgb.h.
HUE_MAX_SPECTRUM
#define HUE_MAX_SPECTRUM 255
Max hue accepted for the hsv2rgb_spectrum() function.
Definition at line 104 of file hsv2rgb.h.
Function Documentation
hsv2rgb_rainbow()
void hsv2rgb_rainbow (const struct CHSV * phsv, struct CRGB * prgb, int numLeds)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
See also
hsv2rgb_rainbow(const struct CHSV&, struct CRGB&)
Parameters
phsv CHSV array to convert to RGB. Max hue supported is HUE_MAX_RAINBOW
prgb CRGB array to store the result of the conversion (will be modified)
numLeds the number of array values to process
Definition at line 485 of file hsv2rgb.cpp.
{
    for(int i = 0; i < numLeds; ++i) {
        hsv2rgb_rainbow(phsv[i], prgb[i]);
    }
}
References hsv2rgb_rainbow().
hsv2rgb_raw() [1/2]
void hsv2rgb_raw (const struct CHSV & hsv, struct CRGB & rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
See also
hsv2rgb_spectrum(const struct CHSV&, struct CRGB&)
Note
The hue is limited to the range 0-191 (HUE_MAX). This results in a slightly faster conversion speed at the expense of color balance.
Parameters
hsv CHSV struct to convert to RGB. Max hue supported is HUE_MAX
rgb CRGB struct to store the result of the conversion (will be modified)
Definition at line 23 of file hsv2rgb.cpp.
{
    hsv2rgb_raw_C( hsv, rgb);
}
References hsv2rgb_raw_C().
Referenced by hsv2rgb_raw(), and hsv2rgb_spectrum().
hsv2rgb_raw() [2/2]
void hsv2rgb_raw (const struct CHSV * phsv, struct CRGB * prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
See also
hsv2rgb_raw(const struct CHSV&, struct CRGB&)
Parameters
phsv CHSV array to convert to RGB. Max hue supported is HUE_MAX
prgb CRGB array to store the result of the conversion (will be modified)
numLeds the number of array values to process
Definition at line 479 of file hsv2rgb.cpp.
{
    for(int i = 0; i < numLeds; ++i) {
        hsv2rgb_raw(phsv[i], prgb[i]);
    }
}
References hsv2rgb_raw().
hsv2rgb_spectrum() [1/3]
CRGB hsv2rgb_spectrum (const struct CHSV & hsv) inline
Inline version of hsv2rgb_spectrum which returns a CRGB object.
Definition at line 90 of file hsv2rgb.h.
{
    CRGB rgb;
    hsv2rgb_spectrum(hsv, rgb);
    return rgb;
}
References hsv2rgb_spectrum().
hsv2rgb_spectrum() [2/3]
void hsv2rgb_spectrum (const struct CHSV & hsv, struct CRGB & rgb)
Convert an HSV value to RGB using a mathematically straight spectrum.
This "spectrum" will have more green and blue than a "rainbow", and less yellow and orange.
Note
This function wraps hsv2rgb_raw() and rescales the hue value to fit the smaller range.
Parameters
hsv CHSV struct to convert to RGB. Max hue supported is HUE_MAX_SPECTRUM
rgb CRGB struct to store the result of the conversion (will be modified)
Definition at line 226 of file hsv2rgb.cpp.
{
    CHSV hsv2(hsv);
    hsv2.hue = scale8( hsv2.hue, 191);
    hsv2rgb_raw(hsv2, rgb);
}
References hsv2rgb_raw(), and scale8().
Referenced by hsv2rgb_spectrum(), and hsv2rgb_spectrum().
hsv2rgb_spectrum() [3/3]
void hsv2rgb_spectrum (const struct CHSV * phsv, struct CRGB * prgb, int numLeds)
Convert an HSV value to RGB using a mathematically straight spectrum.
See also
hsv2rgb_spectrum(const struct CHSV&, struct CRGB&)
Parameters
phsv CHSV array to convert to RGB. Max hue supported is HUE_MAX_SPECTRUM
prgb CRGB array to store the result of the conversion (will be modified)
numLeds the number of array values to process
Definition at line 491 of file hsv2rgb.cpp.
{
    for(int i = 0; i < numLeds; ++i) {
        hsv2rgb_spectrum(phsv[i], prgb[i]);
    }
}
References hsv2rgb_spectrum().
rgb2hsv_approximate()
CHSV rgb2hsv_approximate (const CRGB & rgb)
Recover approximate HSV values from RGB.
These values are approximate, not exact. Why is this "only" an approximation? Because not all RGB colors have HSV equivalents! For example, there is no HSV value that will ever convert to RGB(255,255,0) using the code provided in this library. So if you try to convert RGB(255,255,0) "back" to HSV, you'll necessarily get only an approximation. Emphasis has been placed on getting the "hue" as close as usefully possible, but even that's a bit of a challenge. The 8-bit HSV and 8-bit RGB color spaces are not a "bijection".
Nevertheless, this function does a pretty good job, particularly at recovering the 'hue' from fully saturated RGB colors that originally came from HSV rainbow colors. So if you start with CHSV(hue_in,255,255), and convert that to RGB, and then convert it back to HSV using this function, the resulting output hue will either exactly the same, or very close (+/-1). The more desaturated the original RGB color is, the rougher the approximation, and the less accurate the results.
Note
This function is a long-term work in progress; expect results to change slightly over time as this function is refined and improved.
Note
This function is most accurate when the input is an RGB color that came from a fully-saturated HSV color to start with. E.g. CHSV(hue, 255, 255) -> CRGB -> CHSV will give best results.
Note
This function is not nearly as fast as HSV-to-RGB. It is provided for those situations when the need for this function cannot be avoided, or when extremely high performance is not needed.
See also
https://en.wikipedia.org/wiki/Bijection
Parameters
rgb an RGB value to convert
Returns
the approximate HSV equivalent of the RGB value
Definition at line 504 of file hsv2rgb.cpp.
{
    uint8_t r = rgb.r;
    uint8_t g = rgb.g;
    uint8_t b = rgb.b;
    uint8_t h, s, v;
    // find desaturation
    uint8_t desat = 255;
    if( r < desat) desat = r;
    if( g < desat) desat = g;
    if( b < desat) desat = b;
    // remove saturation from all channels
    r -= desat;
    g -= desat;
    b -= desat;
    //Serial.print("desat="); Serial.print(desat); Serial.println("");
    //uint8_t orig_desat = sqrt16( desat * 256);
    //Serial.print("orig_desat="); Serial.print(orig_desat); Serial.println("");
    // saturation is opposite of desaturation
    s = 255 - desat;
    //Serial.print("s.1="); Serial.print(s); Serial.println("");
    if( s != 255 ) {
        // undo 'dimming' of saturation
        s = 255 - sqrt16( (255-s) * 256);
    }
    // without lib8tion: float ... ew ... sqrt... double ew, or rather, ew ^ 0.5
    // if( s != 255 ) s = (255 - (256.0 * sqrt( (float)(255-s) / 256.0)));
    //Serial.print("s.2="); Serial.print(s); Serial.println("");
    // at least one channel is now zero
    // if all three channels are zero, we had a
    // shade of gray.
    if( (r + g + b) == 0) {
        // we pick hue zero for no special reason
        return CHSV( 0, 0, 255 - s);
    }
    // scale all channels up to compensate for desaturation
    if( s < 255) {
        if( s == 0) s = 1;
        uint32_t scaleup = 65535 / (s);
        r = ((uint32_t)(r) * scaleup) / 256;
        g = ((uint32_t)(g) * scaleup) / 256;
        b = ((uint32_t)(b) * scaleup) / 256;
    }
    //Serial.print("r.2="); Serial.print(r); Serial.println("");
    //Serial.print("g.2="); Serial.print(g); Serial.println("");
    //Serial.print("b.2="); Serial.print(b); Serial.println("");
    uint16_t total = r + g + b;
    //Serial.print("total="); Serial.print(total); Serial.println("");
    // scale all channels up to compensate for low values
    if( total < 255) {
        if( total == 0) total = 1;
        uint32_t scaleup = 65535 / (total);
        r = ((uint32_t)(r) * scaleup) / 256;
        g = ((uint32_t)(g) * scaleup) / 256;
        b = ((uint32_t)(b) * scaleup) / 256;
    }
    //Serial.print("r.3="); Serial.print(r); Serial.println("");
    //Serial.print("g.3="); Serial.print(g); Serial.println("");
    //Serial.print("b.3="); Serial.print(b); Serial.println("");
    if( total > 255 ) {
        v = 255;
    } else {
        v = qadd8(desat,total);
        // undo 'dimming' of brightness
        if( v != 255) v = sqrt16( v * 256);
        // without lib8tion: float ... ew ... sqrt... double ew, or rather, ew ^ 0.5
        // if( v != 255) v = (256.0 * sqrt( (float)(v) / 256.0));
    }
    //Serial.print("v="); Serial.print(v); Serial.println("");
#if 0
    //#else
    if( v != 255) {
        // this part could probably use refinement/rethinking,
        // (but it doesn't overflow & wrap anymore)
        uint16_t s16;
        s16 = (s * 256);
        s16 /= v;
        //Serial.print("s16="); Serial.print(s16); Serial.println("");
        if( s16 < 256) {
            s = s16;
        } else {
            s = 255; // clamp to prevent overflow
        }
    }
#endif
    //Serial.print("s.3="); Serial.print(s); Serial.println("");
    // since this wasn't a pure shade of gray,
    // the interesting question is what hue is it
    // start with which channel is highest
    // (ties don't matter)
    uint8_t highest = r;
    if( g > highest) highest = g;
    if( b > highest) highest = b;
    if( highest == r ) {
        // Red is highest.
        // Hue could be Purple/Pink-Red,Red-Orange,Orange-Yellow
        if( g == 0 ) {
            // if green is zero, we're in Purple/Pink-Red
            h = (HUE_PURPLE + HUE_PINK) / 2;
            h += scale8( qsub8(r, 128), FIXFRAC8(48,128));
        } else if ( (r - g) > g) {
            // if R-G > G then we're in Red-Orange
            h = HUE_RED;
            h += scale8( g, FIXFRAC8(32,85));
        } else {
            // R-G < G, we're in Orange-Yellow
            h = HUE_ORANGE;
            h += scale8( qsub8((g - 85) + (171 - r), 4), FIXFRAC8(32,85)); //221
        }
    } else if ( highest == g) {
        // Green is highest
        // Hue could be Yellow-Green, Green-Aqua
        if( b == 0) {
            // if Blue is zero, we're in Yellow-Green
            //   G = 171..255
            //   R = 171..  0
            h = HUE_YELLOW;
            uint8_t radj = scale8( qsub8(171,r),   47); //171..0 -> 0..171 -> 0..31
            uint8_t gadj = scale8( qsub8(g,171),   96); //171..255 -> 0..84 -> 0..31;
            uint8_t rgadj = radj + gadj;
            uint8_t hueadv = rgadj / 2;
            h += hueadv;
            //h += scale8( qadd8( 4, qadd8((g - 128), (128 - r))),
            //             FIXFRAC8(32,255)); //
        } else {
            // if Blue is nonzero we're in Green-Aqua
            if( (g-b) > b) {
                h = HUE_GREEN;
                h += scale8( b, FIXFRAC8(32,85));
            } else {
                h = HUE_AQUA;
                h += scale8( qsub8(b, 85), FIXFRAC8(8,42));
            }
        }
    } else /* highest == b */ {
        // Blue is highest
        // Hue could be Aqua/Blue-Blue, Blue-Purple, Purple-Pink
        if( r == 0) {
            // if red is zero, we're in Aqua/Blue-Blue
            h = HUE_AQUA + ((HUE_BLUE - HUE_AQUA) / 4);
            h += scale8( qsub8(b, 128), FIXFRAC8(24,128));
        } else if ( (b-r) > r) {
            // B-R > R, we're in Blue-Purple
            h = HUE_BLUE;
            h += scale8( r, FIXFRAC8(32,85));
        } else {
            // B-R < R, we're in Purple-Pink
            h = HUE_PURPLE;
            h += scale8( qsub8(r, 85), FIXFRAC8(32,85));
        }
    }
    h += 1;
    return CHSV( h, s, v);
}
References FIXFRAC8, HUE_AQUA, HUE_BLUE, HUE_GREEN, HUE_ORANGE, HUE_PINK, HUE_PURPLE, HUE_RED, HUE_YELLOW, qadd8(), qsub8(), scale8(), and sqrt16().