FastLED: fl::LUT< T > Class Template Reference
fl::LUT< T > Class Template Reference
Detailed Description
template<typename T>
class fl::LUT< T >
Definition at line 41 of file lut.h.
#include <lut.h>
Public Member Functions
LUT (uint32_t length)
LUT (uint32_t length, T *data)
~LUT ()
T * getData () const
const T & operator[] (uint16_t index) const
const T & operator[] (uint32_t index) const
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Attributes
T * data = nullptr
uint32_t length
fl::scoped_ptr< T > mDataHandle
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
LUT() [1/2]
template<typename T > fl::LUT< T >::LUT (uint32_t length) inline
Definition at line 43 of file lut.h.
                         : length(length) {
        T* ptr = LargeBlockAllocator<T>::Alloc(length);
        mDataHandle.reset(ptr);
        data = ptr;
    }
References fl::LargeBlockAllocator< T >::Alloc(), fl::LUT< T >::data, fl::LUT< T >::length, and fl::LUT< T >::mDataHandle.
LUT() [2/2]
template<typename T > fl::LUT< T >::LUT (uint32_t length, T * data) inline
Definition at line 49 of file lut.h.
                                  : length(length) {
        this->data = data;
    }
References fl::LUT< T >::data.
~LUT()
template<typename T > fl::LUT< T >::~LUT () inline
Definition at line 52 of file lut.h.
           {
        LargeBlockAllocator<T>::Free(mDataHandle.release());
        data = mDataHandle.get();
    }
References fl::LUT< T >::data, fl::LargeBlockAllocator< T >::Free(), and fl::LUT< T >::mDataHandle.
Member Function Documentation
getData()
template<typename T > T * fl::LUT< T >::getData () const inline
Definition at line 65 of file lut.h.
                       {
        return data;
    }
References fl::LUT< T >::data.
Referenced by fl::ScreenMap::ScreenMap(), fl::ScreenMap::ScreenMap(), fl::ScreenMap::operator[](), and fl::ScreenMap::set().
operator[]() [1/2]
template<typename T > const T & fl::LUT< T >::operator[] (uint16_t index) const inline
Definition at line 61 of file lut.h.
{
        return data[index];
    }
References fl::LUT< T >::data.
operator[]() [2/2]
template<typename T > const T & fl::LUT< T >::operator[] (uint32_t index) const inline
Definition at line 57 of file lut.h.
{
        return data[index];
    }
References fl::LUT< T >::data.
Member Data Documentation
data
template<typename T > T* fl::LUT< T >::data = nullptr private
Definition at line 70 of file lut.h.
Referenced by fl::LUT< T >::LUT(), fl::LUT< T >::LUT(), fl::LUT< T >::~LUT(), fl::LUT< T >::getData(), fl::LUT< T >::operator[](), and fl::LUT< T >::operator[]().
length
template<typename T > uint32_t fl::LUT< T >::length private
Definition at line 71 of file lut.h.
Referenced by fl::LUT< T >::LUT().
mDataHandle
template<typename T > fl::scoped_ptr<T> fl::LUT< T >::mDataHandle private
Definition at line 69 of file lut.h.
Referenced by fl::LUT< T >::LUT(), and fl::LUT< T >::~LUT().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/lut.h