FastLED: /home/runner/work/FastLED/FastLED/examples/WasmScreenCoords/WasmScreenCoords.ino File Reference
WasmScreenCoords.ino File Reference
Detailed Description
Simple test for screen coordinates in the web compiled version of FastLED.
Author
Zach Vorhies
This sketch is fully compatible with the FastLED web compiler. To use it do the following:
Install Fastled: pip install fastled
cd into this examples page.
Run the FastLED web compiler at root: fastled
Definition in file WasmScreenCoords.ino.
#include <stdio.h>
#include <string>
#include <vector>
#include <FastLED.h>
#include "fl/json.h"
#include "fl/slice.h"
#include "fl/screenmap.h"
#include "fl/math_macros.h"
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define LED_PIN 3
#define NUM_LEDS 256
Functions
void loop ()
void make_map (int stepx, int stepy, int num, std::vector< pair_xy_float > *_map)
void setup ()
Variables
CRGB leds [NUM_LEDS]
CRGB leds2 [NUM_LEDS]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 25 of file WasmScreenCoords.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 26 of file WasmScreenCoords.ino.
Referenced by setup().
LED_PIN
#define LED_PIN 3
Definition at line 24 of file WasmScreenCoords.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 256
Definition at line 27 of file WasmScreenCoords.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 67 of file WasmScreenCoords.ino.
            {
    FastLED.show();
}
References FastLED, and CFastLED::show().
make_map()
void make_map (int stepx, int stepy, int num, std::vector< pair_xy_float > * _map)
Definition at line 33 of file WasmScreenCoords.ino.
{
    float x = 0;
    float y = 0;
    std::vector<pair_xy_float>& map = *_map;
    for (int16_t i = 0; i < num; i++) {
        map.push_back(pair_xy_float{x, y});
        x += stepx;
        y += stepy;
    }
}
References x, and y.
Referenced by setup().
setup()
void setup ()
Definition at line 44 of file WasmScreenCoords.ino.
             {
    for (CRGB& c : leds) {
        c = CRGB::Blue;
    }
    for (CRGB& c : leds2) {
        c = CRGB::Red;
    }
    FastLED.setBrightness(255);
    std::vector<pair_xy_float> map;
    make_map(1, 1, NUM_LEDS, &map);
    ScreenMap screenmap = ScreenMap(map.data(), map.size());
    std::vector<pair_xy_float> map2;
    make_map(-1, -1, NUM_LEDS, &map2);
    ScreenMap screenmap2 = ScreenMap(map2.data(), map2.size());
    FastLED.addLeds<WS2811, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setScreenMap(screenmap);
    FastLED.addLeds<WS2811, LED_PIN+1, COLOR_ORDER>(leds2, NUM_LEDS)
        .setScreenMap(screenmap2);
}
References CFastLED::addLeds(), CRGB::Blue, COLOR_ORDER, FastLED, LED_PIN, leds, leds2, make_map(), NUM_LEDS, CRGB::Red, and CFastLED::setBrightness().
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 29 of file WasmScreenCoords.ino.
Referenced by setup().
leds2
CRGB leds2[NUM_LEDS]
Definition at line 30 of file WasmScreenCoords.ino.
Referenced by setup().