FastLED: fl::Animartrix Class Reference
fl::Animartrix Class Reference
Detailed Description
Definition at line 84 of file animartrix.hpp.
#include <animartrix.hpp>
Public Member Functions
Animartrix (const Animartrix &)=delete
Animartrix (XYMap xyMap, AnimartrixAnim which_animation)
void draw (DrawContext context) override
int fxGet () const
Str fxName () const override
void fxNext (int fx=1)
int fxNum () const
void fxSet (int fx)
Public Member Functions inherited from fl::Fx2d
Fx2d (const XYMap &xyMap)
uint16_t getHeight () const
uint16_t getWidth () const
XYMap & getXYMap ()
const XYMap & getXYMap () const
void setXYMap (const XYMap &xyMap)
uint16_t xyMap (uint16_t x, uint16_t y) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Static Private Member Functions
static const char * getAnimationName (AnimartrixAnim animation)
Private Attributes
AnimartrixAnim current_animation = RGB_BLOBS5
fl::scoped_ptr< FastLEDANIMartRIX > impl
CRGB * leds = nullptr
AnimartrixAnim prev_animation = NUM_ANIMATIONS
Friends
void AnimartrixLoop (Animartrix &self, uint32_t now)
class FastLEDANIMartRIX
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx2d
XYMap mXyMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
Animartrix() [1/2]
fl::Animartrix::Animartrix (XYMap xyMap, AnimartrixAnim which_animation) inline
Definition at line 86 of file animartrix.hpp.
                                                            : Fx2d(xyMap) {
        // Note: Swapping out height and width.
        this->current_animation = which_animation;
        mXyMap.convertToLookUpTable();
    }
References fl::XYMap::convertToLookUpTable(), current_animation, and fl::Fx2d::mXyMap.
Animartrix() [2/2]
fl::Animartrix::Animartrix (const Animartrix &) delete
Member Function Documentation
draw()
void fl::Animartrix::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 252 of file animartrix.hpp.
{
    this->leds = ctx.leds;
    AnimartrixLoop(*this, ctx.now);
    this->leds = nullptr;
}
References AnimartrixLoop, fl::_DrawContext::leds, leds, and fl::_DrawContext::now.
fxGet()
int fl::Animartrix::fxGet () const inline
Definition at line 96 of file animartrix.hpp.
{ return static_cast<int>(current_animation); }
References current_animation.
Referenced by fxNext(), and fxSet().
fxName()
Str fl::Animartrix::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 97 of file animartrix.hpp.
{
        return "Animartrix:";
    }
fxNext()
void fl::Animartrix::fxNext (int fx = 1) inline
Definition at line 100 of file animartrix.hpp.
{ fxSet(fxGet() + fx); }
References fxGet(), and fxSet().
fxNum()
int fl::Animartrix::fxNum () const inline
Definition at line 94 of file animartrix.hpp.
{ return NUM_ANIMATIONS; }
References fl::NUM_ANIMATIONS.
fxSet()
void fl::Animartrix::fxSet (int fx)
Definition at line 149 of file animartrix.hpp.
{
    int curr = fxGet();
    if (fx < 0) {
        fx = curr + fx;
        if (fx < 0) {
            fx = NUM_ANIMATIONS - 1;
        }
    }
    fx = fx % NUM_ANIMATIONS;
    current_animation = static_cast<AnimartrixAnim>(fx);
    FASTLED_DBG("Setting animation to " << getAnimationName(current_animation));
}
References current_animation, FASTLED_DBG, fxGet(), getAnimationName(), and fl::NUM_ANIMATIONS.
Referenced by fxNext(), and loop().
getAnimationName()
const char * fl::Animartrix::getAnimationName (AnimartrixAnim animation) static private
Definition at line 242 of file animartrix.hpp.
{
    for (const auto& entry : ANIMATION_TABLE) {
        if (entry.anim == animation) {
            return entry.name;
        }
    }
    FASTLED_DBG("Animation not found for " << int(animation));
    return "UNKNOWN";
}
References fl::ANIMATION_TABLE, and FASTLED_DBG.
Referenced by fxSet().
Friends And Related Symbol Documentation
AnimartrixLoop
void AnimartrixLoop (Animartrix & self, uint32_t now) friend
Definition at line 162 of file animartrix.hpp.
{
    if (self.prev_animation != self.current_animation) {
        if (self.impl) {
            // Re-initialize object.
            self.impl->init(self.getWidth(), self.getHeight());
        }
        self.prev_animation = self.current_animation;
    }
    if (!self.impl) {
        self.impl.reset(new FastLEDANIMartRIX(&self));
    }
    self.impl->setTime(now);
    self.impl->loop();
}
Referenced by draw().
FastLEDANIMartRIX
friend class FastLEDANIMartRIX friend
Definition at line 104 of file animartrix.hpp.
Member Data Documentation
current_animation
AnimartrixAnim fl::Animartrix::current_animation = RGB_BLOBS5 private
Definition at line 109 of file animartrix.hpp.
Referenced by Animartrix(), fxGet(), fxSet(), and fl::FastLEDANIMartRIX::loop().
impl
fl::scoped_ptr<FastLEDANIMartRIX> fl::Animartrix::impl private
Definition at line 107 of file animartrix.hpp.
leds
CRGB* fl::Animartrix::leds = nullptr private
Definition at line 108 of file animartrix.hpp.
Referenced by draw(), and fl::FastLEDANIMartRIX::setPixelColor().
prev_animation
AnimartrixAnim fl::Animartrix::prev_animation = NUM_ANIMATIONS private
Definition at line 106 of file animartrix.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/2d/animartrix.hpp