FastLED: /home/runner/work/FastLED/FastLED/examples/Apa102HD/Apa102HD.ino File Reference
Apa102HD.ino File Reference
Detailed Description
Example showing how to use the APA102HD gamma correction.
Example showing how to use the APA102HD gamma correction with user override.
     In this example we compare two strips of LEDs.
     One strip is in HD mode, the other is in software gamma mode.
     Each strip is a linear ramp of brightnesses, from 0 to 255.
     Showcasing all the different brightnesses.
     Why do we love gamma correction? Gamma correction more closely
     matches how humans see light. Led values are measured in fractions
     of max power output (1/255, 2/255, etc.), while humans see light
     in a logarithmic way. Gamma correction converts to this eye friendly
     curve. Gamma correction wants a LED with a high bit depth. The APA102
     gives us the standard 3 components (red, green, blue) with 8 bits each, it
     *also* has a 5 bit brightness component. This gives us a total of 13 bits,
     which allows us to achieve a higher dynamic range. This means deeper fades.
     Example:
       CRGB leds[NUM_LEDS] = {0};
       void setup() {
         FastLED.addLeds<
           APA102HD, // <--- This selects HD mode.
           STRIP_0_DATA_PIN,
           STRIP_0_CLOCK_PIN,
           RGB
         >(leds, NUM_LEDS);
       }
Definition in file Apa102HD.ino.
#include <Arduino.h>
#include <FastLED.h>
#include <lib8tion.h>
Macros
#define NUM_LEDS 20
#define STRIP_0_CLOCK_PIN 2
#define STRIP_0_DATA_PIN 1
#define STRIP_1_CLOCK_PIN 4
#define STRIP_1_DATA_PIN 3
Functions
void loop ()
void setup ()
CRGB software_gamma (const CRGB &in)
uint8_t wrap_8bit (int i)
Variables
CRGB leds [NUM_LEDS] = {0}
CRGB leds_hd [NUM_LEDS] = {0}
Macro Definition Documentation
NUM_LEDS
#define NUM_LEDS 20
Definition at line 35 of file Apa102HD.ino.
Referenced by loop(), and setup().
STRIP_0_CLOCK_PIN
#define STRIP_0_CLOCK_PIN 2
Definition at line 39 of file Apa102HD.ino.
Referenced by setup().
STRIP_0_DATA_PIN
#define STRIP_0_DATA_PIN 1
Definition at line 38 of file Apa102HD.ino.
Referenced by setup().
STRIP_1_CLOCK_PIN
#define STRIP_1_CLOCK_PIN 4
Definition at line 41 of file Apa102HD.ino.
Referenced by setup().
STRIP_1_DATA_PIN
#define STRIP_1_DATA_PIN 3
Definition at line 40 of file Apa102HD.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 75 of file Apa102HD.ino.
            {
    // Draw a a linear ramp of brightnesses to showcase the difference between
    // the HD and non-HD mode.
    for (int i = 0; i < NUM_LEDS; i++) {
        uint8_t brightness = map(i, 0, NUM_LEDS - 1, 0, 255);
        CRGB c(brightness, brightness, brightness);  // Just make a shade of white.
        leds_hd[i] = c;  // The APA102HD leds do their own gamma correction.
        CRGB c_gamma_corrected = software_gamma(c);
        leds[i] = c_gamma_corrected;  // Set the software gamma corrected
                                      // values to the other strip.
    }
    FastLED.show();  // All leds are now written out.
    delay(8);  // Wait 8 milliseconds until the next frame.
}
References brightness, FastLED, leds, leds_hd, NUM_LEDS, CFastLED::show(), and software_gamma().
setup()
void setup ()
Definition at line 59 of file Apa102HD.ino.
             {
    delay(500); // power-up safety delay
    // Two strips of LEDs, one in HD mode, one in software gamma mode.
    FastLED.addLeds<APA102HD, STRIP_0_DATA_PIN, STRIP_0_CLOCK_PIN, RGB>(leds_hd, NUM_LEDS);
    FastLED.addLeds<APA102,   STRIP_1_DATA_PIN, STRIP_1_CLOCK_PIN, RGB>(leds, NUM_LEDS);
}
References CFastLED::addLeds(), APA102, APA102HD, FastLED, leds, leds_hd, NUM_LEDS, RGB, STRIP_0_CLOCK_PIN, STRIP_0_DATA_PIN, STRIP_1_CLOCK_PIN, and STRIP_1_DATA_PIN.
software_gamma()
CRGB software_gamma (const CRGB & in)
Definition at line 50 of file Apa102HD.ino.
{
    CRGB out;
    // dim8_raw are the old gamma correction functions.
    out.r = dim8_raw(in.r);
    out.g = dim8_raw(in.g);
    out.b = dim8_raw(in.b);
    return out;
}
References dim8_raw().
Referenced by loop().
wrap_8bit()
uint8_t wrap_8bit (int i)
Definition at line 66 of file Apa102HD.ino.
{
    // Module % operator here wraps a large "i" so that it is
    // always in [0, 255] range when returned. For example, if
    // "i" is 256, then this will return 0. If "i" is 257
    // then this will return 1. No matter how big the "i" is, the
    // output range will always be [0, 255]
    return i % 256;
}
Variable Documentation
leds
CRGB leds[NUM_LEDS] = {0}
Definition at line 45 of file Apa102HD.ino.
{0};     // Software gamma mode.
Referenced by loop(), and setup().
leds_hd
CRGB leds_hd[NUM_LEDS] = {0}
Definition at line 44 of file Apa102HD.ino.
{0};  // HD mode implies gamma.
Referenced by loop(), and setup().