FastLED: fl::TimeScale Class Reference
fl::TimeScale Class Reference
Detailed Description
Definition at line 26 of file time.h.
#include <time.h>
Public Member Functions
TimeScale (uint32_t realTimeNow, float initialTimeScale=1.0f)
~TimeScale ()
void pause (uint32_t now)
void reset (uint32_t realTimeNow) override
void resume (uint32_t now)
float scale () const
void setScale (float timeScale)
uint32_t time () const override
uint32_t update (uint32_t timeNow) override
Public Member Functions inherited from fl::TimeFunction
virtual ~TimeFunction ()
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Member Functions
void applyExact (uint32_t timeNow)
Private Attributes
uint32_t mLastRealTime = 0
uint32_t mPauseTime = 0
uint32_t mRelativeTime = 0
uint32_t mStartTime = 0
float mTimeScale = 1.0f
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
TimeScale()
fl::TimeScale::TimeScale (uint32_t realTimeNow, float initialTimeScale = 1.0f)
Definition at line 12 of file time.cpp.
    : mLastRealTime(realTimeNow),
      mStartTime(realTimeNow),
      mTimeScale(initialTimeScale) {}
~TimeScale()
fl::TimeScale::~TimeScale ()
Definition at line 17 of file time.cpp.
{}
Member Function Documentation
applyExact()
void fl::TimeScale::applyExact (uint32_t timeNow) private
Definition at line 68 of file time.cpp.
{
    uint32_t elapsedRealTime = timeNow - mLastRealTime;
    mLastRealTime = timeNow;
    int32_t diff = static_cast<int32_t>(elapsedRealTime * mTimeScale);
    if (diff == 0) {
        return;
    }
    if (diff >= 0) {
        mRelativeTime += diff;
        return;
    }
    // diff < 0
    uint32_t abs_diff = -diff;
    if (abs_diff > mRelativeTime) {
        // Protection against rollover.
        mRelativeTime = 0;
        mLastRealTime = timeNow;
        return;
    }
    mLastRealTime = timeNow;
    mRelativeTime -= abs_diff;
}
References mLastRealTime, mRelativeTime, and mTimeScale.
Referenced by update().
pause()
void fl::TimeScale::pause (uint32_t now)
Definition at line 27 of file time.cpp.
{
    if (mPauseTime) {
        FASTLED_WARN("TimeScale::pause: already paused");
        return;
    }
    mPauseTime = now;
}
References FASTLED_WARN, and mPauseTime.
reset()
void fl::TimeScale::reset (uint32_t realTimeNow) override virtual
Implements fl::TimeFunction.
Definition at line 62 of file time.cpp.
{
    mLastRealTime = realTimeNow;
    mStartTime = realTimeNow;
    mRelativeTime = 0;
}
References mLastRealTime, mRelativeTime, and mStartTime.
Referenced by resume().
resume()
void fl::TimeScale::resume (uint32_t now)
Definition at line 34 of file time.cpp.
{
    if (mLastRealTime == 0) {
        reset(now);
        return;
    }
    uint32_t diff = now - mPauseTime;
    mStartTime += diff;
    mLastRealTime += diff;
    mPauseTime = 0;
}
References mLastRealTime, mPauseTime, mStartTime, and reset().
scale()
float fl::TimeScale::scale () const
Definition at line 23 of file time.cpp.
{
    return mTimeScale;
}
References mTimeScale.
setScale()
void fl::TimeScale::setScale (float timeScale)
Definition at line 19 of file time.cpp.
{
    mTimeScale = timeScale;
}
References mTimeScale.
Referenced by fl::FxEngine::setSpeed().
time()
uint32_t fl::TimeScale::time () const override virtual
Implements fl::TimeFunction.
Definition at line 58 of file time.cpp.
{
    return mRelativeTime;
}
References mRelativeTime.
Referenced by fl::FxEngine::draw(), and update().
update()
uint32_t fl::TimeScale::update (uint32_t timeNow) override virtual
Implements fl::TimeFunction.
Definition at line 45 of file time.cpp.
{
    //DBG("TimeScale::update: timeNow: " << timeNow << " mLastRealTime: " << mLastRealTime
    //<< " mRelativeTime: " << mRelativeTime << " mTimeScale: " << mTimeScale);
    if (mLastRealTime > timeNow) {
        DBG("TimeScale::applyExact: mLastRealTime > timeNow: " << mLastRealTime << " > " << timeNow);
    }
    applyExact(timeNow);
    return time();
}
References applyExact(), DBG, mLastRealTime, and time().
Referenced by fl::FxEngine::draw().
Member Data Documentation
mLastRealTime
uint32_t fl::TimeScale::mLastRealTime = 0 private
Definition at line 39 of file time.h.
Referenced by applyExact(), reset(), resume(), and update().
mPauseTime
uint32_t fl::TimeScale::mPauseTime = 0 private
Definition at line 43 of file time.h.
Referenced by pause(), and resume().
mRelativeTime
uint32_t fl::TimeScale::mRelativeTime = 0 private
Definition at line 41 of file time.h.
Referenced by applyExact(), reset(), and time().
mStartTime
uint32_t fl::TimeScale::mStartTime = 0 private
Definition at line 40 of file time.h.
Referenced by reset(), and resume().
mTimeScale
float fl::TimeScale::mTimeScale = 1.0f private
Definition at line 42 of file time.h.
Referenced by applyExact(), scale(), and setScale().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/time.h
/home/runner/work/FastLED/FastLED/src/fx/time.cpp