FastLED: fl::WeakPtr< T > Class Template Reference
fl::WeakPtr< T > Class Template Reference
Detailed Description
template<typename T>
class fl::WeakPtr< T >
Definition at line 274 of file ptr.h.
#include <ptr.h>
Public Member Functions
WeakPtr ()
WeakPtr (const Ptr< T > &ptr)
template<typename U >
WeakPtr (const Ptr< U > &ptr)
WeakPtr (const WeakPtr &other)
template<typename U >
WeakPtr (const WeakPtr< U > &other)
WeakPtr (WeakPtr &&other) noexcept
~WeakPtr ()
bool expired () const
Ptr< T > lock () const
operator bool () const
bool operator! () const
bool operator!= (const T *other) const
bool operator!= (const WeakPtr &other) const
WeakPtr & operator= (const WeakPtr &other)
bool operator== (const Ptr< T > &other) const
bool operator== (const T *other) const
bool operator== (const WeakPtr &other) const
bool operator== (T *other) const
void reset ()
Public Attributes
Ptr< WeakReferent > mWeakPtr
Constructor & Destructor Documentation
WeakPtr() [1/6]
template<typename T > fl::WeakPtr< T >::WeakPtr () inline
Definition at line 276 of file ptr.h.
: mWeakPtr() {}
WeakPtr() [2/6]
template<typename T > fl::WeakPtr< T >::WeakPtr (const Ptr< T > & ptr) inline
Definition at line 278 of file ptr.h.
{
        if (ptr) {
            WeakPtr weakRefNoCreate = ptr.weakRefNoCreate();
            bool expired = weakRefNoCreate.expired();
            if (expired) {
                Ptr<WeakReferent> weakRefNoCreate = Ptr<WeakReferent>::New();
                ptr->setWeakPtr(weakRefNoCreate);
                weakRefNoCreate->setReferent(ptr.get());
            }
            mWeakPtr = ptr->mWeakPtr;
        }
    }
References fl::WeakPtr< T >::expired(), fl::Ptr< T >::get(), fl::WeakPtr< T >::mWeakPtr, fl::PtrTraits< T >::New(), and fl::Ptr< T >::weakRefNoCreate().
WeakPtr() [3/6]
template<typename T > template<typename U > fl::WeakPtr< T >::WeakPtr (const Ptr< U > & ptr) inline
Definition at line 291 of file ptr.h.
                                                     : mWeakPtr(ptr->mWeakPtr) {
        if (ptr) {
            WeakPtr weakRefNoCreate = ptr.weakRefNoCreate();
            bool expired = weakRefNoCreate.expired();
            if (expired) {
                Ptr<WeakReferent> weakRefNoCreate = Ptr<WeakReferent>::New();
                ptr->setWeakPtr(weakRefNoCreate);
                weakRefNoCreate->setReferent(ptr.get());
            }
            mWeakPtr = ptr->mWeakPtr;
        }
    }
References fl::WeakPtr< T >::expired(), fl::Ptr< T >::get(), fl::WeakPtr< T >::mWeakPtr, fl::PtrTraits< T >::New(), and fl::Ptr< T >::weakRefNoCreate().
WeakPtr() [4/6]
template<typename T > fl::WeakPtr< T >::WeakPtr (const WeakPtr< T > & other) inline
Definition at line 304 of file ptr.h.
: mWeakPtr(other.mWeakPtr) {}
WeakPtr() [5/6]
template<typename T > template<typename U > fl::WeakPtr< T >::WeakPtr (const WeakPtr< U > & other) inline
Definition at line 307 of file ptr.h.
: mWeakPtr(other.mWeakPtr) {}
WeakPtr() [6/6]
template<typename T > fl::WeakPtr< T >::WeakPtr (WeakPtr< T > && other) inline noexcept
Definition at line 309 of file ptr.h.
: mWeakPtr(other.mWeakPtr) {}
~WeakPtr()
template<typename T > fl::WeakPtr< T >::~WeakPtr () inline
Definition at line 311 of file ptr.h.
{ reset(); }
References fl::WeakPtr< T >::reset().
Member Function Documentation
expired()
template<typename T > bool fl::WeakPtr< T >::expired () const inline
Definition at line 367 of file ptr.h.
{
        if (!mWeakPtr) {
            return true;
        }
        if (!mWeakPtr->getReferent()) {
            return true;
        }
        return false;
    }
References fl::WeakPtr< T >::mWeakPtr.
Referenced by fl::WeakPtr< T >::WeakPtr(), and fl::WeakPtr< T >::WeakPtr().
lock()
template<typename T > Ptr< T > fl::WeakPtr< T >::lock () const inline
Definition at line 354 of file ptr.h.
{
        if (!mWeakPtr) {
            return Ptr<T>();
        }
        T* out = static_cast<T*>(mWeakPtr->getReferent());
        if (out->ref_count() == 0) {
            // This is a static object, so the refcount is 0.
            return Ptr<T>::NoTracking(*out);
        }
        // This is a heap object, so we need to ref it.
        return Ptr<T>::TakeOwnership(static_cast<T *>(out));
    }
References fl::WeakPtr< T >::mWeakPtr, fl::Ptr< T >::NoTracking(), and fl::Ptr< T >::TakeOwnership().
Referenced by fl::WeakPtr< T >::operator==().
operator bool()
template<typename T > fl::WeakPtr< T >::operator bool () const inline
Definition at line 313 of file ptr.h.
{ return mWeakPtr && mWeakPtr->getReferent(); }
References fl::WeakPtr< T >::mWeakPtr.
operator!()
template<typename T > bool fl::WeakPtr< T >::operator! () const inline
Definition at line 315 of file ptr.h.
{
        bool ok = *this;
        return !ok;
    }
operator!=() [1/2]
template<typename T > bool fl::WeakPtr< T >::operator!= (const T * other) const inline
Definition at line 344 of file ptr.h.
{
        bool equal = *this == other;
        return !equal;
    }
operator!=() [2/2]
template<typename T > bool fl::WeakPtr< T >::operator!= (const WeakPtr< T > & other) const inline
Definition at line 324 of file ptr.h.
{
        return !(mWeakPtr != other.mWeakPtr);
    }
References fl::WeakPtr< T >::mWeakPtr.
operator=()
template<typename T > WeakPtr & fl::WeakPtr< T >::operator= (const WeakPtr< T > & other) inline
Definition at line 349 of file ptr.h.
{
        this->mWeakPtr = other.mWeakPtr;
        return *this;
    }
References fl::WeakPtr< T >::mWeakPtr.
operator==() [1/4]
template<typename T > bool fl::WeakPtr< T >::operator== (const Ptr< T > & other) const inline
Definition at line 337 of file ptr.h.
{
        if (!mWeakPtr) {
            return !other;
        }
        return mWeakPtr->getReferent() == other.get();
    }
References fl::Ptr< T >::get(), and fl::WeakPtr< T >::mWeakPtr.
operator==() [2/4]
template<typename T > bool fl::WeakPtr< T >::operator== (const T * other) const inline
Definition at line 328 of file ptr.h.
{ return lock().get() == other; }
References fl::WeakPtr< T >::lock().
operator==() [3/4]
template<typename T > bool fl::WeakPtr< T >::operator== (const WeakPtr< T > & other) const inline
Definition at line 320 of file ptr.h.
{
        return mWeakPtr == other.mWeakPtr;
    }
References fl::WeakPtr< T >::mWeakPtr.
operator==() [4/4]
template<typename T > bool fl::WeakPtr< T >::operator== (T * other) const inline
Definition at line 330 of file ptr.h.
{
        if (!mWeakPtr) {
            return other == nullptr;
        }
        return mWeakPtr->getReferent() == other;
    }
References fl::WeakPtr< T >::mWeakPtr.
reset()
template<typename T > void fl::WeakPtr< T >::reset () inline
Definition at line 377 of file ptr.h.
                 {
        if (mWeakPtr) {
            mWeakPtr.reset();
        }
    }
References fl::WeakPtr< T >::mWeakPtr.
Referenced by fl::WeakPtr< T >::~WeakPtr().
Member Data Documentation
mWeakPtr
template<typename T > Ptr<WeakReferent> fl::WeakPtr< T >::mWeakPtr
Definition at line 382 of file ptr.h.
Referenced by fl::WeakPtr< T >::WeakPtr(), fl::WeakPtr< T >::WeakPtr(), fl::WeakPtr< T >::expired(), fl::WeakPtr< T >::lock(), fl::WeakPtr< T >::operator bool(), fl::WeakPtr< T >::operator!=(), fl::WeakPtr< T >::operator=(), fl::WeakPtr< T >::operator==(), fl::WeakPtr< T >::operator==(), fl::WeakPtr< T >::operator==(), fl::WeakPtr< T >::reset(), and fl::Ptr< T >::weakRefNoCreate().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ptr.h