FastLED: /home/runner/work/FastLED/FastLED/examples/FxSdCard/FxSdCard.ino File Reference
FxSdCard.ino File Reference
#include "FastLED.h"
#include "Arduino.h"
#include "fx/2d/noisepalette.h"
#include "fx/fx_engine.h"
#include "fx/video.h"
#include "fl/file_system.h"
#include "fl/ui.h"
#include "fl/screenmap.h"
Macros
#define CHIP_SELECT_PIN 5
#define COLOR_ORDER GRB
#define FPS 60
#define IS_SERPINTINE true
#define LED_PIN 2
#define LED_TYPE WS2811
#define MATRIX_HEIGHT 32
#define MATRIX_WIDTH 32
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
#define NUM_VIDEO_FRAMES 2
Functions
void loop ()
void setup ()
Variables
UIDescription description ("Video data is streamed off of a SD card and displayed on a LED strip. The video data is mapped to the LED strip using a ScreenMap.")
FileSystem filesystem
bool gError = false
CRGB leds [NUM_LEDS]
ScreenMap screenMap
UITitle title ("SDCard Demo - Mapped Video")
Video video
Video video2
UISlider videoSpeed ("Video Speed", 1.0f, -1, 2.0f, 0.01f)
UINumberField whichVideo ("Which Video", 0, 0, 1)
Macro Definition Documentation
CHIP_SELECT_PIN
#define CHIP_SELECT_PIN 5
Definition at line 42 of file FxSdCard.ino.
Referenced by setup().
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 40 of file FxSdCard.ino.
Referenced by setup().
FPS
#define FPS 60
Definition at line 41 of file FxSdCard.ino.
Referenced by setup().
IS_SERPINTINE
#define IS_SERPINTINE true
Definition at line 52 of file FxSdCard.ino.
LED_PIN
#define LED_PIN 2
Definition at line 38 of file FxSdCard.ino.
Referenced by setup().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 39 of file FxSdCard.ino.
Referenced by setup().
MATRIX_HEIGHT
#define MATRIX_HEIGHT 32
Definition at line 47 of file FxSdCard.ino.
MATRIX_WIDTH
#define MATRIX_WIDTH 32
Definition at line 46 of file FxSdCard.ino.
NUM_LEDS
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Definition at line 51 of file FxSdCard.ino.
Referenced by setup().
NUM_VIDEO_FRAMES
#define NUM_VIDEO_FRAMES 2
Definition at line 48 of file FxSdCard.ino.
Function Documentation
loop()
void loop ()
Definition at line 111 of file FxSdCard.ino.
            {
    static bool s_first = true;
    if (s_first) {
      s_first = false;
      Serial.println("First loop.");
    }
    if (gError) {
      EVERY_N_SECONDS(1) {
        FASTLED_WARN("No loop because an error occured.");
      }
      return;
    }
    Video& vid = !bool(whichVideo.value()) ? video : video2;
    vid.setTimeScale(videoSpeed);
    uint32_t now = millis();
    vid.draw(now, leds);
    FastLED.show();
}
References fl::Video::draw(), EVERY_N_SECONDS, FastLED, FASTLED_WARN, gError, leds, fl::Video::setTimeScale(), CFastLED::show(), fl::UINumberField::value(), video, video2, videoSpeed, and whichVideo.
setup()
void setup ()
Definition at line 72 of file FxSdCard.ino.
             {
    Serial.begin(115200);
    Serial.println("Sketch setup");
    if (!filesystem.beginSd(CHIP_SELECT_PIN)) {
        Serial.println("Failed to initialize file system.");
    }
    // Note that data/ is a special directory used by our wasm compiler. Any data
    // is placed in it will be included in the files.json file which the browser will
    // use to stream the file asynchroniously in during the runtime. For a real sd card
    // just place all this in the /data/ directory of the SD card to get matching
    // behavior.
    video = filesystem.openVideo("data/video.rgb", NUM_LEDS, FPS, 2);
    if (!video) {
      FASTLED_WARN("Failed to instantiate video");
      gError = true;
      return;
    }
    video2 = filesystem.openVideo("data/color_line_bubbles.rgb", NUM_LEDS, FPS, 2);
    if (!video2) {
      FASTLED_WARN("Failed to instantiate video2");
      gError = true;
      return;
    }
    ScreenMap screenMap;
    bool ok = filesystem.readScreenMap("data/screenmap.json", "strip1", &screenMap);
    if (!ok) {
      Serial.println("Failed to read screen map");
      gError = true;
      return;
    }
    FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setCorrection(TypicalLEDStrip)
        .setScreenMap(screenMap);
    FastLED.setBrightness(96);
    Serial.println("FastLED setup done");
}
References CFastLED::addLeds(), fl::FileSystem::beginSd(), CHIP_SELECT_PIN, COLOR_ORDER, FastLED, FASTLED_WARN, filesystem, FPS, gError, LED_PIN, LED_TYPE, leds, NUM_LEDS, fl::FileSystem::openVideo(), fl::FileSystem::readScreenMap(), screenMap, CFastLED::setBrightness(), CLEDController::setScreenMap(), TypicalLEDStrip, video, and video2.
Variable Documentation
description
UIDescription description("Video data is streamed off of a SD card and displayed on a LED strip. The video data is mapped to the LED strip using a ScreenMap.") ("Video data is streamed off of a SD card and displayed on a LED strip. The video data is mapped to the LED strip using a ScreenMap.")
filesystem
FileSystem filesystem
Definition at line 62 of file FxSdCard.ino.
Referenced by setup().
gError
bool gError = false
Definition at line 70 of file FxSdCard.ino.
Referenced by loop(), and setup().
leds
CRGB leds[NUM_LEDS]
Definition at line 59 of file FxSdCard.ino.
Referenced by loop(), and setup().
screenMap
ScreenMap screenMap
Definition at line 60 of file FxSdCard.ino.
Referenced by fl::ScreenMap::Circle(), and setup().
title
UITitle title("SDCard Demo - Mapped Video") ("SDCard Demo - Mapped Video")
video
Video video
Definition at line 63 of file FxSdCard.ino.
Referenced by loop(), fl::FileSystem::openVideo(), and setup().
video2
Video video2
Definition at line 64 of file FxSdCard.ino.
Referenced by loop(), and setup().
videoSpeed
UISlider videoSpeed("Video Speed", 1.0f, -1, 2.0f, 0.01f) ("Video Speed" , 1. 0f, - 1, 2. 0f, 0. 01f)
Referenced by loop().
whichVideo
UINumberField whichVideo("Which Video", 0, 0, 1) ("Which Video" , 0 , 0 , 1)
Referenced by loop().