FastLED: fl::HeapVector< T > Class Template Reference
fl::HeapVector< T > Class Template Reference
Detailed Description
template<typename T>
class fl::HeapVector< T >
Definition at line 216 of file vector.h.
#include <vector.h>
Public Types
typedef const T * const_iterator
typedef T * iterator
Public Member Functions
HeapVector (const HeapVector< T > &other)
HeapVector (size_t size=0, const T &value=T())
~HeapVector ()
void assign (const T *values, size_t count)
void assign (const_iterator begin, const_iterator end)
T & back ()
const T & back () const
iterator begin ()
const_iterator begin () const
size_t capacity () const
void clear ()
T * data ()
const T * data () const
bool empty () const
iterator end ()
const_iterator end () const
void ensure_size (size_t n)
void erase (const T &value)
bool erase (iterator pos, T *out_value=nullptr)
iterator find (const T &value)
const_iterator find (const T &value) const
template<typename Predicate >
iterator find_if (Predicate pred)
T & front ()
const T & front () const
bool full () const
bool has (const T &value) const
bool insert (iterator pos, const T &value)
bool operator!= (const HeapVector< T > &other) const
HeapVector & operator= (const HeapVector< T > &other)
bool operator== (const HeapVector< T > &other) const
T & operator[] (size_t index)
const T & operator[] (size_t index) const
void pop_back ()
void push_back (const T &value)
void reserve (size_t n)
void resize (size_t n)
void resize (size_t n, const T &value)
size_t size () const
void swap (HeapVector< T > &other)
void swap (iterator a, iterator b)
Private Attributes
fl::scoped_array< T > mArray
size_t mCapacity = 0
size_t mSize = 0
Member Typedef Documentation
const_iterator
template<typename T > const T* fl::HeapVector< T >::const_iterator
Definition at line 225 of file vector.h.
iterator
template<typename T > T* fl::HeapVector< T >::iterator
Definition at line 224 of file vector.h.
Constructor & Destructor Documentation
HeapVector() [1/2]
template<typename T > fl::HeapVector< T >::HeapVector (size_t size = 0, const T & value = T()) inline
Definition at line 228 of file vector.h.
                                                     : mCapacity(size) {
        mArray.reset(new T[mCapacity]);
        for (size_t i = 0; i < size; ++i) {
            mArray[i] = value;
        }
        mSize = size;
    }
References fl::HeapVector< T >::mArray, fl::HeapVector< T >::mCapacity, fl::HeapVector< T >::mSize, and fl::HeapVector< T >::size().
HeapVector() [2/2]
template<typename T > fl::HeapVector< T >::HeapVector (const HeapVector< T > & other) inline
Definition at line 235 of file vector.h.
                                          : mSize(other.size()) {
        assign(other.begin(), other.end());
    }
References fl::HeapVector< T >::assign(), fl::HeapVector< T >::begin(), and fl::HeapVector< T >::end().
~HeapVector()
template<typename T > fl::HeapVector< T >::~HeapVector () inline
Definition at line 246 of file vector.h.
                  {
        clear();
    }
References fl::HeapVector< T >::clear().
Member Function Documentation
assign() [1/2]
template<typename T > void fl::HeapVector< T >::assign (const T * values, size_t count) inline
Definition at line 453 of file vector.h.
{
        assign(values, values + count);
    }
References fl::HeapVector< T >::assign().
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::assign(), and fl::HeapVector< T >::operator=().
assign() [2/2]
template<typename T > void fl::HeapVector< T >::assign (const_iterator begin, const_iterator end) inline
Definition at line 457 of file vector.h.
{
        clear();
        reserve(end - begin);
        for (const_iterator it = begin; it != end; ++it) {
            push_back(*it);
        }
    }
References fl::HeapVector< T >::begin(), fl::HeapVector< T >::clear(), fl::HeapVector< T >::end(), fl::HeapVector< T >::push_back(), and fl::HeapVector< T >::reserve().
back() [1/2]
template<typename T > T & fl::HeapVector< T >::back () inline
Definition at line 352 of file vector.h.
              {
        return mArray[mSize - 1];
    }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::erase().
back() [2/2]
template<typename T > const T & fl::HeapVector< T >::back () const inline
Definition at line 356 of file vector.h.
{
        return mArray[mSize - 1];
    }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mSize.
begin() [1/2]
template<typename T > iterator fl::HeapVector< T >::begin () inline
Definition at line 338 of file vector.h.
{ return &mArray[0]; }
References fl::HeapVector< T >::mArray.
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::assign(), fl::HeapVector< T >::find(), fl::HeapVector< T >::find(), fl::HeapVector< T >::find_if(), fl::RectangularDrawBuffer::getMaxBytesInStrip(), fl::HeapVector< T >::insert(), fl::RectangularDrawBuffer::onQueuingDone(), and fl::HeapVector< T >::operator=().
begin() [2/2]
template<typename T > const_iterator fl::HeapVector< T >::begin () const inline
Definition at line 339 of file vector.h.
{ return &mArray[0]; }
References fl::HeapVector< T >::mArray.
capacity()
template<typename T > size_t fl::HeapVector< T >::capacity () const inline
Definition at line 311 of file vector.h.
{
        return mCapacity;
    }
References fl::HeapVector< T >::mCapacity.
clear()
template<typename T > void fl::HeapVector< T >::clear () inline
Definition at line 331 of file vector.h.
                 {
        while (mSize > 0) {
            pop_back();
        }
    }
References fl::HeapVector< T >::mSize, and fl::HeapVector< T >::pop_back().
Referenced by fl::HeapVector< T >::~HeapVector(), fl::HeapVector< T >::assign(), fl::RectangularDrawBuffer::onQueuingStart(), and LedRopeTCL::RawBeginDraw().
data() [1/2]
template<typename T > T * fl::HeapVector< T >::data () inline
Definition at line 465 of file vector.h.
              {
        return mArray.get();
    }
References fl::HeapVector< T >::mArray.
Referenced by makeScreenMap(), and LedRopeTCL::RawCommitDraw().
data() [2/2]
template<typename T > const T * fl::HeapVector< T >::data () const inline
Definition at line 469 of file vector.h.
{
        return mArray.get();
    }
References fl::HeapVector< T >::mArray.
empty()
template<typename T > bool fl::HeapVector< T >::empty () const inline
Definition at line 307 of file vector.h.
                       {
        return mSize == 0;
    }
References fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::erase().
end() [1/2]
template<typename T > iterator fl::HeapVector< T >::end () inline
Definition at line 340 of file vector.h.
{ return &mArray[mSize]; }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::assign(), fl::HeapVector< T >::erase(), fl::HeapVector< T >::erase(), fl::HeapVector< T >::find(), fl::HeapVector< T >::find(), fl::HeapVector< T >::find_if(), fl::RectangularDrawBuffer::getMaxBytesInStrip(), fl::HeapVector< T >::has(), fl::HeapVector< T >::insert(), fl::RectangularDrawBuffer::onQueuingDone(), and fl::HeapVector< T >::operator=().
end() [2/2]
template<typename T > const_iterator fl::HeapVector< T >::end () const inline
Definition at line 341 of file vector.h.
{ return &mArray[mSize]; }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mSize.
ensure_size()
template<typename T > void fl::HeapVector< T >::ensure_size (size_t n) inline
Definition at line 250 of file vector.h.
{
        if (n > mCapacity) {
            size_t new_capacity = (3*mCapacity) / 2;
            if (new_capacity < n) {
                new_capacity = n;
            }
            fl::scoped_array<T> new_array(new T[new_capacity]);
            for (size_t i = 0; i < mSize; ++i) {
                new_array[i] = mArray[i];
            }
            // mArray = std::move(new_array);
            mArray.reset();
            mArray.reset(new_array.release());
            mCapacity = new_capacity;
        }
    }
References fl::HeapVector< T >::mArray, fl::HeapVector< T >::mCapacity, fl::HeapVector< T >::mSize, and fl::scoped_array< T, Deleter >::release().
Referenced by fl::HeapVector< T >::push_back(), and fl::HeapVector< T >::reserve().
erase() [1/2]
template<typename T > void fl::HeapVector< T >::erase (const T & value) inline
Definition at line 409 of file vector.h.
{
        iterator it = find(value);
        if (it != end()) {
            erase(it);
        }
    }
References fl::HeapVector< T >::end(), fl::HeapVector< T >::erase(), and fl::HeapVector< T >::find().
erase() [2/2]
template<typename T > bool fl::HeapVector< T >::erase (iterator pos, T * out_value = nullptr) inline
Definition at line 393 of file vector.h.
{
        if (pos == end() || empty()) {
            return false;
        }
        if (out_value) {
            *out_value = *pos;
        }
        while (pos != end() - 1) {
            *pos = *(pos + 1);
            ++pos;
        }
        back() = T();
        --mSize;
        return true;
    }
References fl::HeapVector< T >::back(), fl::HeapVector< T >::empty(), fl::HeapVector< T >::end(), fl::HeapVector< T >::mSize, and pos.
Referenced by fl::HeapVector< T >::erase().
find() [1/2]
template<typename T > iterator fl::HeapVector< T >::find (const T & value) inline
Definition at line 361 of file vector.h.
{
        for (iterator it = begin(); it != end(); ++it) {
            if (*it == value) {
                return it;
            }
        }
        return end();
    }
References fl::HeapVector< T >::begin(), and fl::HeapVector< T >::end().
Referenced by fl::HeapVector< T >::erase(), and fl::HeapVector< T >::has().
find() [2/2]
template<typename T > const_iterator fl::HeapVector< T >::find (const T & value) const inline
Definition at line 370 of file vector.h.
{
        for (const_iterator it = begin(); it != end(); ++it) {
            if (*it == value) {
                return it;
            }
        }
        return end();
    }
References fl::HeapVector< T >::begin(), and fl::HeapVector< T >::end().
find_if()
template<typename T > template<typename Predicate > iterator fl::HeapVector< T >::find_if (Predicate pred) inline
Definition at line 380 of file vector.h.
{
        for (iterator it = begin(); it != end(); ++it) {
            if (pred(*it)) {
                return it;
            }
        }
        return end();
    }
References fl::HeapVector< T >::begin(), and fl::HeapVector< T >::end().
front() [1/2]
template<typename T > T & fl::HeapVector< T >::front () inline
Definition at line 344 of file vector.h.
               {
        return mArray[0];
    }
References fl::HeapVector< T >::mArray.
front() [2/2]
template<typename T > const T & fl::HeapVector< T >::front () const inline
Definition at line 348 of file vector.h.
{
        return mArray[0];
    }
References fl::HeapVector< T >::mArray.
full()
template<typename T > bool fl::HeapVector< T >::full () const inline
Definition at line 435 of file vector.h.
                      {
        return mSize >= mCapacity;
    }
References fl::HeapVector< T >::mCapacity, and fl::HeapVector< T >::mSize.
has()
template<typename T > bool fl::HeapVector< T >::has (const T & value) const inline
Definition at line 389 of file vector.h.
{
        return find(value) != end();
    }
References fl::HeapVector< T >::end(), and fl::HeapVector< T >::find().
insert()
template<typename T > bool fl::HeapVector< T >::insert (iterator pos, const T & value) inline
Definition at line 439 of file vector.h.
{
        // TODO: Introduce mMaxSize (and move it from SortedVector to here)
        // push back and swap into place.
        size_t target_idx = pos - begin();
        push_back(value);
        auto last = end() - 1;
        for (size_t curr_idx = last - begin(); curr_idx > target_idx; --curr_idx) {
            auto first = begin() + curr_idx - 1;
            auto second = begin() + curr_idx;
            swap(first, second);
        }
        return true;
    }
References fl::HeapVector< T >::begin(), fl::HeapVector< T >::end(), pos, fl::HeapVector< T >::push_back(), and fl::HeapVector< T >::swap().
operator!=()
template<typename T > bool fl::HeapVector< T >::operator!= (const HeapVector< T > & other) const inline
Definition at line 485 of file vector.h.
{
        return !(*this == other);
    }
operator=()
template<typename T > HeapVector & fl::HeapVector< T >::operator= (const HeapVector< T > & other) inline
Definition at line 238 of file vector.h.
                                                      { // cppcheck-suppress operatorEqVarError
        if (this != &other) {
            assign(other.begin(), other.end());
        }
        return *this;
    }
References fl::HeapVector< T >::assign(), fl::HeapVector< T >::begin(), and fl::HeapVector< T >::end().
operator==()
template<typename T > bool fl::HeapVector< T >::operator== (const HeapVector< T > & other) const inline
Definition at line 473 of file vector.h.
{
        if (size() != other.size()) {
            return false;
        }
        for (size_t i = 0; i < size(); ++i) {
            if (mArray[i] != other.mArray[i]) {
                return false;
            }
        }
        return true;
    }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::size().
operator[]() [1/2]
template<typename T > T & fl::HeapVector< T >::operator[] (size_t index) inline
Definition at line 294 of file vector.h.
{
        return mArray[index];
    }
References fl::HeapVector< T >::mArray.
operator[]() [2/2]
template<typename T > const T & fl::HeapVector< T >::operator[] (size_t index) const inline
Definition at line 298 of file vector.h.
{
        return mArray[index];
    }
References fl::HeapVector< T >::mArray.
pop_back()
template<typename T > void fl::HeapVector< T >::pop_back () inline
Definition at line 324 of file vector.h.
                    {
        if (mSize > 0) {
            --mSize;
            mArray[mSize] = T();
        }
    }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::clear().
push_back()
template<typename T > void fl::HeapVector< T >::push_back (const T & value) inline
Definition at line 316 of file vector.h.
{
        ensure_size(mSize + 1);
        if (mSize < mCapacity) {
            mArray[mSize] = value;
            ++mSize;
        }
    }
References fl::HeapVector< T >::ensure_size(), fl::HeapVector< T >::mArray, fl::HeapVector< T >::mCapacity, and fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::assign(), fl::HeapVector< T >::insert(), makeScreenMap(), fl::RectangularDrawBuffer::queue(), and LedRopeTCL::RawDrawPixel().
reserve()
template<typename T > void fl::HeapVector< T >::reserve (size_t n) inline
Definition at line 267 of file vector.h.
{
        if (n > mCapacity) {
            ensure_size(n);
        }
    }
References fl::HeapVector< T >::ensure_size(), and fl::HeapVector< T >::mCapacity.
Referenced by LedRopeTCL::LedRopeTCL(), and fl::HeapVector< T >::assign().
resize() [1/2]
template<typename T > void fl::HeapVector< T >::resize (size_t n) inline
Definition at line 273 of file vector.h.
{
        if (mSize == n) {
            return;
        }
        HeapVector<T> temp(n);
        for (size_t i = 0; i < n && i < mSize; ++i) {
            temp.mArray[i] = mArray[i];
        }
        swap(temp);
    }
References fl::HeapVector< T >::mArray, fl::HeapVector< T >::mSize, and fl::HeapVector< T >::swap().
Referenced by animartrix_detail::ANIMartRIX::render_polar_lookup_table().
resize() [2/2]
template<typename T > void fl::HeapVector< T >::resize (size_t n, const T & value) inline
Definition at line 284 of file vector.h.
{
        mArray.reset();
        mArray.reset(new T[n]);
        for (size_t i = 0; i < n; ++i) {
            mArray[i] = value;
        }
        mCapacity = n;
    }
References fl::HeapVector< T >::mArray, and fl::HeapVector< T >::mCapacity.
size()
template<typename T > size_t fl::HeapVector< T >::size () const inline
Definition at line 303 of file vector.h.
{
        return mSize;
    }
References fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::HeapVector(), fl::RectangularDrawBuffer::getBlockInfo(), fl::RectangularDrawBuffer::getTotalBytes(), makeScreenMap(), fl::HeapVector< T >::operator==(), LedRopeTCL::RawCommitDraw(), and LedRopeTCL::RawDrawPixel().
swap() [1/2]
template<typename T > void fl::HeapVector< T >::swap (HeapVector< T > & other) inline
Definition at line 416 of file vector.h.
{
        T* temp = mArray.release();
        size_t temp_size = mSize;
        size_t temp_capacity = mCapacity;
        T* temp2 = other.mArray.release();
        mArray.reset(temp2);
        other.mArray.reset(temp);
        mSize = other.mSize;
        mCapacity = other.mCapacity;
        other.mSize = temp_size;
        other.mCapacity = temp_capacity;
    }
References fl::HeapVector< T >::mArray, fl::HeapVector< T >::mCapacity, and fl::HeapVector< T >::mSize.
Referenced by fl::HeapVector< T >::insert(), fl::RectangularDrawBuffer::onQueuingStart(), and fl::HeapVector< T >::resize().
swap() [2/2]
template<typename T > void fl::HeapVector< T >::swap (iterator a, iterator b) inline
Definition at line 429 of file vector.h.
{
        T temp = *a;
        *a = *b;
        *b = temp;
    }
Member Data Documentation
mArray
template<typename T > fl::scoped_array<T> fl::HeapVector< T >::mArray private
Definition at line 218 of file vector.h.
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::back(), fl::HeapVector< T >::back(), fl::HeapVector< T >::begin(), fl::HeapVector< T >::begin(), fl::HeapVector< T >::data(), fl::HeapVector< T >::data(), fl::HeapVector< T >::end(), fl::HeapVector< T >::end(), fl::HeapVector< T >::ensure_size(), fl::HeapVector< T >::front(), fl::HeapVector< T >::front(), fl::HeapVector< T >::operator==(), fl::HeapVector< T >::operator[](), fl::HeapVector< T >::operator[](), fl::HeapVector< T >::pop_back(), fl::HeapVector< T >::push_back(), fl::HeapVector< T >::resize(), fl::HeapVector< T >::resize(), and fl::HeapVector< T >::swap().
mCapacity
template<typename T > size_t fl::HeapVector< T >::mCapacity = 0 private
Definition at line 220 of file vector.h.
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::capacity(), fl::HeapVector< T >::ensure_size(), fl::HeapVector< T >::full(), fl::HeapVector< T >::push_back(), fl::HeapVector< T >::reserve(), fl::HeapVector< T >::resize(), and fl::HeapVector< T >::swap().
mSize
template<typename T > size_t fl::HeapVector< T >::mSize = 0 private
Definition at line 221 of file vector.h.
Referenced by fl::HeapVector< T >::HeapVector(), fl::HeapVector< T >::back(), fl::HeapVector< T >::back(), fl::HeapVector< T >::clear(), fl::HeapVector< T >::empty(), fl::HeapVector< T >::end(), fl::HeapVector< T >::end(), fl::HeapVector< T >::ensure_size(), fl::HeapVector< T >::erase(), fl::HeapVector< T >::full(), fl::HeapVector< T >::pop_back(), fl::HeapVector< T >::push_back(), fl::HeapVector< T >::resize(), fl::HeapVector< T >::size(), and fl::HeapVector< T >::swap().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/vector.h