FastLED: /home/runner/work/FastLED/FastLED/examples/Pride2015/Pride2015.ino File Reference
Pride2015.ino File Reference
Detailed Description
Animated, ever-changing rainbows.
Definition in file Pride2015.ino.
#include "FastLED.h"
Macros
#define BRIGHTNESS 255
#define COLOR_ORDER GRB
#define DATA_PIN 3
#define LED_TYPE WS2811
#define NUM_LEDS 200
Functions
void loop ()
void pride ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 255
Definition at line 20 of file Pride2015.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 18 of file Pride2015.ino.
DATA_PIN
#define DATA_PIN 3
Definition at line 15 of file Pride2015.ino.
LED_TYPE
#define LED_TYPE WS2811
Definition at line 17 of file Pride2015.ino.
NUM_LEDS
#define NUM_LEDS 200
Definition at line 19 of file Pride2015.ino.
Function Documentation
loop()
void loop ()
Definition at line 38 of file Pride2015.ino.
{
  pride();
  FastLED.show();
}
References FastLED, pride, and CFastLED::show().
pride()
void pride ()
Definition at line 47 of file Pride2015.ino.
{
  static uint16_t sPseudotime = 0;
  static uint16_t sLastMillis = 0;
  static uint16_t sHue16 = 0;
  uint8_t sat8 = beatsin88( 87, 220, 250);
  uint8_t brightdepth = beatsin88( 341, 96, 224);
  uint16_t brightnessthetainc16 = beatsin88( 203, (25 * 256), (40 * 256));
  uint8_t msmultiplier = beatsin88(147, 23, 60);
  uint16_t hue16 = sHue16;//gHue * 256;
  uint16_t hueinc16 = beatsin88(113, 1, 3000);
  uint16_t ms = millis();
  uint16_t deltams = ms - sLastMillis ;
  sLastMillis  = ms;
  sPseudotime += deltams * msmultiplier;
  sHue16 += deltams * beatsin88( 400, 5,9);
  uint16_t brightnesstheta16 = sPseudotime;
  for( uint16_t i = 0 ; i < NUM_LEDS; i++) {
    hue16 += hueinc16;
    uint8_t hue8 = hue16 / 256;
    brightnesstheta16  += brightnessthetainc16;
    uint16_t b16 = sin16( brightnesstheta16  ) + 32768;
    uint16_t bri16 = (uint32_t)((uint32_t)b16 * (uint32_t)b16) / 65536;
    uint8_t bri8 = (uint32_t)(((uint32_t)bri16) * brightdepth) / 65536;
    bri8 += (255 - brightdepth);
    CRGB newcolor = CHSV( hue8, sat8, bri8);
    uint16_t pixelnumber = i;
    pixelnumber = (NUM_LEDS-1) - pixelnumber;
    nblend( leds[pixelnumber], newcolor, 64);
  }
}
References beatsin88(), leds, nblend(), NUM_LEDS, and sin16.
setup()
void setup ()
Definition at line 25 of file Pride2015.ino.
             {
  delay(3000); // 3 second delay for recovery
  // tell FastLED about the LED strip configuration
  FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS)
    .setCorrection(TypicalLEDStrip)
    .setDither(BRIGHTNESS < 255);
  // set master brightness control
  FastLED.setBrightness(BRIGHTNESS);
}
References CFastLED::addLeds(), BRIGHTNESS, COLOR_ORDER, DATA_PIN, FastLED, LED_TYPE, leds, NUM_LEDS, CFastLED::setBrightness(), CLEDController::setDither(), and TypicalLEDStrip.
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 22 of file Pride2015.ino.