FastLED: fl::XYMap Class Reference
fl::XYMap Class Reference
Detailed Description
Examples
FxEngine.ino.
Definition at line 38 of file xymap.h.
#include <xymap.h>
Public Types
enum XyMapType { kSerpentine = 0 , kLineByLine , kFunction , kLookUpTable }
Public Member Functions
XYMap (const XYMap &other)=default
XYMap (uint16_t width, uint16_t height, bool is_serpentine=true, uint16_t offset=0)
void convertToLookUpTable ()
uint16_t getHeight () const
uint16_t getTotal () const
XyMapType getType () const
uint16_t getWidth () const
void mapPixels (const CRGB *input, CRGB *output) const
uint16_t mapToIndex (int x, int y) const
uint16_t mapToIndex (uint16_t x, uint16_t y) const
uint16_t operator() (uint16_t x, uint16_t y) const
XYMap & operator= (const XYMap &other)=default
void setRectangularGrid ()
fl::ScreenMap toScreenMap () const
Static Public Member Functions
static XYMap constructRectangularGrid (uint16_t width, uint16_t height, uint16_t offset=0)
static XYMap constructWithLookUpTable (uint16_t width, uint16_t height, const uint16_t *lookUpTable, uint16_t offset=0)
static XYMap constructWithUserFunction (uint16_t width, uint16_t height, XYFunction xyFunction, uint16_t offset=0)
Private Member Functions
XYMap (uint16_t width, uint16_t height, XyMapType type)
Private Attributes
uint16_t height
fl::LUT16Ptr mLookUpTable
uint16_t mOffset = 0
XyMapType type
uint16_t width
XYFunction xyFunction = nullptr
Member Enumeration Documentation
XyMapType
enum fl::XYMap::XyMapType
Enumerator
kSerpentine
kLineByLine
kFunction
kLookUpTable
Definition at line 40 of file xymap.h.
{ kSerpentine = 0, kLineByLine, kFunction, kLookUpTable };
Constructor & Destructor Documentation
XYMap() [1/3]
fl::XYMap::XYMap (uint16_t width, uint16_t height, bool is_serpentine = true, uint16_t offset = 0)
Definition at line 63 of file xymap.cpp.
    : type(is_serpentine ? kSerpentine : kLineByLine),
      width(width), height(height), mOffset(offset) {}
XYMap() [2/3]
fl::XYMap::XYMap (const XYMap & other) default
XYMap() [3/3]
fl::XYMap::XYMap (uint16_t width, uint16_t height, XyMapType type) private
Definition at line 149 of file xymap.cpp.
    : type(type), width(width), height(height), mOffset(0) {}
Member Function Documentation
constructRectangularGrid()
XYMap fl::XYMap::constructRectangularGrid (uint16_t width, uint16_t height, uint16_t offset = 0) static
Definition at line 43 of file xymap.cpp.
{
    XYMap out(width, height, kLineByLine);
    out.mOffset = offset;
    return out;
}
References height, kLineByLine, mOffset, and width.
Referenced by CLEDController::setScreenMap().
constructWithLookUpTable()
XYMap fl::XYMap::constructWithLookUpTable (uint16_t width, uint16_t height, const uint16_t * lookUpTable, uint16_t offset = 0) static
Definition at line 51 of file xymap.cpp.
{
    XYMap out(width, height, kLookUpTable);
    out.mLookUpTable = LUT16Ptr::New(width * height);
    memcpy(out.mLookUpTable->getData(), lookUpTable,
           width * height * sizeof(uint16_t));
    out.mOffset = offset;
    return out;
}
References height, kLookUpTable, mLookUpTable, mOffset, and width.
constructWithUserFunction()
XYMap fl::XYMap::constructWithUserFunction (uint16_t width, uint16_t height, XYFunction xyFunction, uint16_t offset = 0) static
Definition at line 33 of file xymap.cpp.
{
    XYMap out(width, height, kFunction);
    out.xyFunction = xyFunction;
    out.mOffset = offset;
    return out;
}
References height, kFunction, mOffset, width, and xyFunction.
Referenced by blur2d().
convertToLookUpTable()
void fl::XYMap::convertToLookUpTable ()
Definition at line 81 of file xymap.cpp.
{
    if (type == kLookUpTable) {
        return;
    }
    mLookUpTable = LUT16Ptr::New(width * height);
    uint16_t *data = mLookUpTable->getData();
    for (uint16_t y = 0; y < height; y++) {
        for (uint16_t x = 0; x < width; x++) {
            data[y * width + x] = mapToIndex(x, y);
        }
    }
    type = kLookUpTable;
    xyFunction = nullptr;
}
References height, kLookUpTable, mapToIndex(), mLookUpTable, type, width, x, xyFunction, and y.
Referenced by fl::Animartrix::Animartrix().
getHeight()
uint16_t fl::XYMap::getHeight () const
Definition at line 137 of file xymap.cpp.
{ return height; }
References height.
Referenced by fl::bilinearExpand(), fl::bilinearExpandArbitrary(), fl::bilinearExpandArbitraryFloat(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), and fl::Fx2d::getHeight().
getTotal()
uint16_t fl::XYMap::getTotal () const
Definition at line 141 of file xymap.cpp.
{ return width * height; }
References height, and width.
Referenced by fl::bilinearExpandArbitrary(), fl::bilinearExpandArbitraryFloat(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), fl::RedSquare::draw(), and fl::ScaleUp::noExpand().
getType()
XYMap::XyMapType fl::XYMap::getType () const
Definition at line 145 of file xymap.cpp.
{ return type; }
References type.
getWidth()
uint16_t fl::XYMap::getWidth () const
Definition at line 133 of file xymap.cpp.
{ return width; }
References width.
Referenced by fl::bilinearExpand(), fl::bilinearExpandArbitrary(), fl::bilinearExpandArbitraryFloat(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), and fl::Fx2d::getWidth().
mapPixels()
void fl::XYMap::mapPixels (const CRGB * input, CRGB * output) const
Definition at line 69 of file xymap.cpp.
{
    uint16_t pos = 0;
    for (uint16_t y = 0; y < height; y++) {
        for (uint16_t x = 0; x < width; x++) {
            uint16_t i = pos++;
            output[i] = input[mapToIndex(x, y)];
        }
    }
}
References height, mapToIndex(), pos, width, x, and y.
mapToIndex() [1/2]
uint16_t fl::XYMap::mapToIndex (int x, int y) const inline
Definition at line 74 of file xymap.h.
{
        if (x < 0) { x = 0; }
        else if (uint16_t(x) >= width) { x = width - 1; }
        if (y < 0) { y = 0; }
        else if (uint16_t(y) >= height) { y = height - 1; }
        return mapToIndex((uint16_t)x, (uint16_t)y);
    }
References height, mapToIndex(), width, x, and y.
mapToIndex() [2/2]
uint16_t fl::XYMap::mapToIndex (uint16_t x, uint16_t y) const
Definition at line 106 of file xymap.cpp.
{
    uint16_t index;
    switch (type) {
    case kSerpentine:
        x = x % width;
        y = y % height;
        index = xy_serpentine(x, y, width, height);
        break;
    case kLineByLine:
        index = xy_line_by_line(x, y, width, height);
        break;
    case kFunction:
        x = x % width;
        y = y % height;
        index = xyFunction(x, y, width, height);
        break;
    case kLookUpTable:
        index = mLookUpTable->getData()[y * width + x];
        break;
    default:
        return 0;
    }
    return index + mOffset;
}
References height, kFunction, kLineByLine, kLookUpTable, kSerpentine, mLookUpTable, mOffset, type, width, x, fl::xy_line_by_line(), fl::xy_serpentine(), xyFunction, and y.
Referenced by fl::bilinearExpandArbitrary(), fl::bilinearExpandArbitraryFloat(), fl::bilinearExpandFloat(), fl::bilinearExpandPowerOf2(), blurColumns(), blurRows(), convertToLookUpTable(), fl::RedSquare::draw(), mapPixels(), mapToIndex(), fl::ScaleUp::noExpand(), operator()(), toScreenMap(), fl::NoisePalette::XY(), XY(), and fl::Fx2d::xyMap().
operator()()
uint16_t fl::XYMap::operator() (uint16_t x, uint16_t y) const inline
Definition at line 69 of file xymap.h.
{
        return mapToIndex(x, y);
    }
References mapToIndex(), x, and y.
operator=()
XYMap & fl::XYMap::operator= (const XYMap & other) default
setRectangularGrid()
void fl::XYMap::setRectangularGrid ()
Definition at line 98 of file xymap.cpp.
{
    type = kLineByLine;
    xyFunction = nullptr;
    mLookUpTable.reset();
}
References kLineByLine, mLookUpTable, type, and xyFunction.
toScreenMap()
ScreenMap fl::XYMap::toScreenMap () const
Definition at line 15 of file xymap.cpp.
{
    const uint16_t length = width * height;
    ScreenMap out(length);
    for (uint16_t w = 0; w < width; w++) {
        for (uint16_t h = 0; h < height; h++) {
            uint16_t index = mapToIndex(w, h);
            pair_xy_float p = {
                static_cast<float>(w),
                static_cast<float>(h)
            };
            out.set(index, p);
        }
    }
    return out;
}
References height, mapToIndex(), p, fl::ScreenMap::set(), and width.
Member Data Documentation
height
uint16_t fl::XYMap::height private
Definition at line 92 of file xymap.h.
Referenced by constructRectangularGrid(), constructWithLookUpTable(), constructWithUserFunction(), convertToLookUpTable(), getHeight(), getTotal(), mapPixels(), mapToIndex(), mapToIndex(), and toScreenMap().
mLookUpTable
fl::LUT16Ptr fl::XYMap::mLookUpTable private
Definition at line 94 of file xymap.h.
Referenced by constructWithLookUpTable(), convertToLookUpTable(), mapToIndex(), and setRectangularGrid().
mOffset
uint16_t fl::XYMap::mOffset = 0 private
Definition at line 95 of file xymap.h.
Referenced by constructRectangularGrid(), constructWithLookUpTable(), constructWithUserFunction(), and mapToIndex().
type
XyMapType fl::XYMap::type private
Definition at line 90 of file xymap.h.
Referenced by convertToLookUpTable(), getType(), mapToIndex(), and setRectangularGrid().
width
uint16_t fl::XYMap::width private
Definition at line 91 of file xymap.h.
Referenced by constructRectangularGrid(), constructWithLookUpTable(), constructWithUserFunction(), convertToLookUpTable(), getTotal(), getWidth(), mapPixels(), mapToIndex(), mapToIndex(), and toScreenMap().
xyFunction
XYFunction fl::XYMap::xyFunction = nullptr private
Definition at line 93 of file xymap.h.
Referenced by constructWithUserFunction(), convertToLookUpTable(), mapToIndex(), and setRectangularGrid().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/xymap.h
/home/runner/work/FastLED/FastLED/src/fl/xymap.cpp