FastLED: /home/runner/work/FastLED/FastLED/examples/FxTwinkleFox/FxTwinkleFox.ino File Reference
FxTwinkleFox.ino File Reference
#include "FastLED.h"
#include "fx/1d/twinklefox.h"
Macros
#define COLOR_ORDER GRB
#define DATA_PIN 3
#define LED_TYPE WS2811
#define MAX_MA 4000
#define NUM_LEDS 100
#define VOLTS 12
Functions
void loop ()
void setup ()
Variables
CRGBArray< NUM_LEDS > leds
TwinkleFox twinkleFox (NUM_LEDS)
Macro Definition Documentation
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 8 of file FxTwinkleFox.ino.
Referenced by setup().
DATA_PIN
#define DATA_PIN 3
Definition at line 9 of file FxTwinkleFox.ino.
Referenced by setup().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 7 of file FxTwinkleFox.ino.
Referenced by setup().
MAX_MA
#define MAX_MA 4000
Examples
TwinkleFox.ino.
Definition at line 11 of file FxTwinkleFox.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 100
Definition at line 6 of file FxTwinkleFox.ino.
Referenced by setup().
VOLTS
#define VOLTS 12
Examples
TwinkleFox.ino.
Definition at line 10 of file FxTwinkleFox.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 24 of file FxTwinkleFox.ino.
            {
  EVERY_N_SECONDS(SECONDS_PER_PALETTE) {
    twinkleFox.chooseNextColorPalette(twinkleFox.targetPalette);
  }
  twinkleFox.draw(Fx::DrawContext(millis(), leds));
  FastLED.show();
}
References fl::TwinkleFox::chooseNextColorPalette(), fl::TwinkleFox::draw(), EVERY_N_SECONDS, FastLED, leds, SECONDS_PER_PALETTE, CFastLED::show(), fl::TwinkleFox::targetPalette, and twinkleFox.
setup()
void setup ()
Definition at line 16 of file FxTwinkleFox.ino.
             {
  delay(3000); // safety startup delay
  FastLED.setMaxPowerInVoltsAndMilliamps(VOLTS, MAX_MA);
  FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, NUM_LEDS)
    .setCorrection(TypicalLEDStrip)
    .setRgbw();
}
References CFastLED::addLeds(), COLOR_ORDER, DATA_PIN, FastLED, LED_TYPE, leds, MAX_MA, NUM_LEDS, CFastLED::setMaxPowerInVoltsAndMilliamps(), CLEDController::setRgbw(), TypicalLEDStrip, and VOLTS.
Variable Documentation
leds
CRGBArray<NUM_LEDS> leds
Definition at line 13 of file FxTwinkleFox.ino.
Referenced by loop(), and setup().
twinkleFox
TwinkleFox twinkleFox(NUM_LEDS) (NUM_LEDS)
Referenced by loop().