FastLED: fl::Fire2012 Class Reference
fl::Fire2012 Class Reference
Detailed Description
Definition at line 49 of file fire2012.h.
#include <fire2012.h>
Public Member Functions
Fire2012 (uint16_t num_leds, uint8_t cooling=55, uint8_t sparking=120, bool reverse_direction=false, const CRGBPalette16 &palette=(const CRGBPalette16 &) HeatColors_p)
~Fire2012 ()
void draw (DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx1d
Fx1d (uint16_t numLeds)
void setXmap (const XMap &xMap)
uint16_t xyMap (uint16_t x) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Attributes
uint8_t cooling
fl::scoped_array< uint8_t > heat
CRGBPalette16 palette
bool reverse_direction
uint8_t sparking
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx1d
XMap mXMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
Fire2012()
fl::Fire2012::Fire2012 (uint16_t num_leds, uint8_t cooling = 55, uint8_t sparking = 120, bool reverse_direction = false, const CRGBPalette16 & palette = (const CRGBPalette16&)HeatColors_p) inline
Definition at line 51 of file fire2012.h.
        : Fx1d(num_leds), cooling(cooling), sparking(sparking),
          reverse_direction(reverse_direction), palette(palette) {
        heat.reset(new uint8_t[num_leds]()); // Initialize to zero
    }
References heat, and fl::scoped_array< T, Deleter >::reset().
~Fire2012()
fl::Fire2012::~Fire2012 () inline
Definition at line 59 of file fire2012.h.
{}
Member Function Documentation
draw()
void fl::Fire2012::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 61 of file fire2012.h.
{
        CRGB *leds = context.leds;
        if (leds == nullptr) {
            return;
        }
        // Step 1.  Cool down every cell a little
        for (uint16_t i = 0; i < mNumLeds; i++) {
            heat[i] =
                qsub8(heat[i], random8(0, ((cooling * 10) / mNumLeds) + 2));
        }
        // Step 2.  Heat from each cell drifts 'up' and diffuses a little
        for (uint16_t k = mNumLeds - 1; k >= 2; k--) {
            heat[k] = (heat[k - 1] + heat[k - 2] + heat[k - 2]) / 3;
        }
        // Step 3.  Randomly ignite new 'sparks' of heat near the bottom
        if (random8() < sparking) {
            int y = random8(7);
            heat[y] = qadd8(heat[y], random8(160, 255));
        }
        // Step 4.  Map from heat cells to LED colors
        for (uint16_t j = 0; j < mNumLeds; j++) {
            // Scale the heat value from 0-255 down to 0-240
            // for best results with color palettes.
            uint8_t colorindex = scale8(heat[j], 240);
            CRGB color = ColorFromPalette(palette, colorindex);
            int pixelnumber;
            if (reverse_direction) {
                pixelnumber = (mNumLeds - 1) - j;
            } else {
                pixelnumber = j;
            }
            leds[pixelnumber] = color;
        }
    }
References ColorFromPalette(), cooling, heat, fl::_DrawContext::leds, leds, fl::Fx::mNumLeds, palette, qadd8(), qsub8(), random8(), reverse_direction, scale8(), sparking, and y.
fxName()
fl::Str fl::Fire2012::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 100 of file fire2012.h.
{ return "Fire2012"; }
Member Data Documentation
cooling
uint8_t fl::Fire2012::cooling private
Definition at line 104 of file fire2012.h.
Referenced by draw().
heat
fl::scoped_array<uint8_t> fl::Fire2012::heat private
Definition at line 103 of file fire2012.h.
Referenced by Fire2012(), and draw().
palette
CRGBPalette16 fl::Fire2012::palette private
Definition at line 107 of file fire2012.h.
Referenced by draw().
reverse_direction
bool fl::Fire2012::reverse_direction private
Definition at line 106 of file fire2012.h.
Referenced by draw().
sparking
uint8_t fl::Fire2012::sparking private
Definition at line 105 of file fire2012.h.
Referenced by draw().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/1d/fire2012.h