FastLED: LED Chipset Controllers
LED Chipset Controllers
Detailed Description
Implementations of CLEDController classes for various led chipsets.
Topics
Clocked Chipsets
Nominally SPI based, these chipsets have a data and a clock line.
Clockless Chipsets
These chipsets have only a single data line.
Classes
class RGBWEmulatedController< CONTROLLER, RGB_ORDER >
class RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT
class WS2816Controller< DATA_PIN, RGB_ORDER >
class WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT
Class Documentation
RGBWEmulatedController
class RGBWEmulatedController
Public Types
typedef CONTROLLER ControllerBaseT
Public Member Functions
RGBWEmulatedController (const Rgbw &rgbw=RgbwDefault())
~RGBWEmulatedController ()
virtual void * beginShowLeds (int size) override
virtual void endShowLeds (void *data) override
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels) override
Send the LED data to the strip.
Public Member Functions inherited from CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Attributes
static const int LANES = CONTROLLER::LANES_VALUE
static const uint32_t MASK = CONTROLLER::MASK_VALUE
Static Public Attributes inherited from CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Private Member Functions
void ensureBuffer (int32_t num_leds)
void init () override
Initialize the LED controller.
Private Attributes
ControllerT mController
int32_t mNumRGBLeds = 0
int32_t mNumRGBWLeds = 0
CRGB * mRGBWPixels = nullptr
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Protected Member Functions inherited from CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
ControllerBaseT
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> CONTROLLER RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerBaseT
Definition at line 121 of file chipsets.h.
Constructor & Destructor Documentation
RGBWEmulatedController()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> RGBWEmulatedController< CONTROLLER, RGB_ORDER >::RGBWEmulatedController (const Rgbw & rgbw = RgbwDefault()) inline
Definition at line 138 of file chipsets.h.
{
        this->setRgbw(rgbw);
    };
References rgbw, and CLEDController::setRgbw().
~RGBWEmulatedController()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> RGBWEmulatedController< CONTROLLER, RGB_ORDER >::~RGBWEmulatedController () inline
Definition at line 141 of file chipsets.h.
{ delete[] mRGBWPixels; }
References RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mRGBWPixels.
Member Function Documentation
beginShowLeds()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> virtual void * RGBWEmulatedController< CONTROLLER, RGB_ORDER >::beginShowLeds (int size) inline override virtual
Reimplemented from CLEDController.
Definition at line 143 of file chipsets.h.
{
        return mController.callBeginShowLeds(Rgbw::size_as_rgb(size));
    }
References RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callBeginShowLeds(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController, and Rgbw::size_as_rgb().
endShowLeds()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> virtual void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::endShowLeds (void * data) inline override virtual
Reimplemented from CLEDController.
Definition at line 147 of file chipsets.h.
{
        return mController.callEndShowLeds(data);
    }
References RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callEndShowLeds(), and RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController.
ensureBuffer()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ensureBuffer (int32_t num_leds) inline private
Definition at line 188 of file chipsets.h.
{
        if (num_leds != mNumRGBLeds) {
            mNumRGBLeds = num_leds;
            // The delegate controller expects the raw pixel byte data in multiples of 3.
            // In the case of src data not a multiple of 3, then we need to
            // add pad bytes so that the delegate controller doesn't walk off the end
            // of the array and invoke a buffer overflow panic.
            uint32_t new_size = Rgbw::size_as_rgb(num_leds);
            delete[] mRGBWPixels;
            mRGBWPixels = new CRGB[new_size];
            // showPixels may never clear the last two pixels.
            for (uint32_t i = 0; i < new_size; i++) {
                mRGBWPixels[i] = CRGB(0, 0, 0);
            }
            mController.setLeds(mRGBWPixels, new_size);
        }
    }
References RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController, RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mNumRGBLeds, RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mRGBWPixels, and Rgbw::size_as_rgb().
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
init()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::init () inline override private virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 183 of file chipsets.h.
{
        mController.init();
        mController.setEnabled(false);
    }
References RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController.
showPixels()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> virtual void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels (PixelController< RGB_ORDER, LANES, MASK > & pixels) inline override virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Implements CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >.
Definition at line 151 of file chipsets.h.
{
        // Ensure buffer is large enough
        ensureBuffer(pixels.size());
        Rgbw rgbw = this->getRgbw();
        uint8_t *data = reinterpret_cast<uint8_t *>(mRGBWPixels);
        while (pixels.has(1)) {
            pixels.stepDithering();
            pixels.loadAndScaleRGBW(rgbw, data, data + 1, data + 2, data + 3);
            data += 4;
            pixels.advanceData();
        }
        // Force the device controller to a state where it passes data through
        // unmodified: color correction, color temperature, dither, and brightness
        // (passed as an argument to show()).  Temporarily enable the controller,
        // show the LEDs, and disable it again.
        //
        // The device controller is in the global controller list, so if we
        // don't keep it disabled, it will refresh again with unknown brightness,
        // temperature, etc.
        mController.setCorrection(CRGB(255, 255, 255));
        mController.setTemperature(CRGB(255, 255, 255));
        mController.setDither(DISABLE_DITHER);
        mController.setEnabled(true);
        mController.callShow(mRGBWPixels, Rgbw::size_as_rgb(pixels.size()), 255);
        mController.setEnabled(false);
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callShow(), DISABLE_DITHER, RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ensureBuffer(), CLEDController::getRgbw(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController, RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mRGBWPixels, rgbw, PixelController< RGB_ORDER, LANES, MASK >::size(), Rgbw::size_as_rgb(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
Member Data Documentation
LANES
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> const int RGBWEmulatedController< CONTROLLER, RGB_ORDER >::LANES = CONTROLLER::LANES_VALUE static
Definition at line 132 of file chipsets.h.
MASK
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> const uint32_t RGBWEmulatedController< CONTROLLER, RGB_ORDER >::MASK = CONTROLLER::MASK_VALUE static
Definition at line 133 of file chipsets.h.
mController
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> ControllerT RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mController private
Definition at line 210 of file chipsets.h.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::beginShowLeds(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::endShowLeds(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ensureBuffer(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::init(), and RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
mNumRGBLeds
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> int32_t RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mNumRGBLeds = 0 private
Definition at line 208 of file chipsets.h.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ensureBuffer().
mNumRGBWLeds
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> int32_t RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mNumRGBWLeds = 0 private
Definition at line 209 of file chipsets.h.
mRGBWPixels
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> CRGB* RGBWEmulatedController< CONTROLLER, RGB_ORDER >::mRGBWPixels = nullptr private
Definition at line 207 of file chipsets.h.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::~RGBWEmulatedController(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ensureBuffer(), and RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
RGBWEmulatedController::ControllerT
class RGBWEmulatedController::ControllerT
Private Member Functions
void * callBeginShowLeds (int size)
void callEndShowLeds (void *data)
void callShow (CRGB *data, int nLeds, uint8_t brightness)
Friends
class RGBWEmulatedController< CONTROLLER, RGB_ORDER >
Member Function Documentation
callBeginShowLeds()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> void * RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callBeginShowLeds (int size) inline private
Definition at line 124 of file chipsets.h.
{ return ControllerBaseT::beginShowLeds(size); }
References CLEDController::size().
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::beginShowLeds().
callEndShowLeds()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callEndShowLeds (void * data) inline private
Definition at line 128 of file chipsets.h.
{ ControllerBaseT::endShowLeds(data); }
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::endShowLeds().
callShow()
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callShow (CRGB * data, int nLeds, uint8_t brightness) inline private
Definition at line 125 of file chipsets.h.
{
            ControllerBaseT::show(data, nLeds, brightness);
        }
References brightness.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
Friends And Related Symbol Documentation
RGBWEmulatedController< CONTROLLER, RGB_ORDER >
template<typename CONTROLLER , EOrder RGB_ORDER = GRB> friend class RGBWEmulatedController< CONTROLLER, RGB_ORDER > friend
Definition at line 210 of file chipsets.h.
WS2816Controller
class WS2816Controller
Public Types
typedef WS2812Controller800Khz< DATA_PIN, RGB > ControllerBaseT
Public Member Functions
WS2816Controller ()
~WS2816Controller ()
virtual void * beginShowLeds (int size) override
virtual void endShowLeds (void *data) override
virtual void showPixels (PixelController< RGB_ORDER, LANES, MASK > &pixels) override
Send the LED data to the strip.
Public Member Functions inherited from CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
CPixelLEDController ()
int lanes () override
Get the number of lanes of the Controller.
Public Member Functions inherited from CLEDController
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Attributes
static const int LANES = ControllerT::LANES_VALUE
static const uint32_t MASK = ControllerT::MASK_VALUE
Static Public Attributes inherited from CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
static const int LANES_VALUE
The number of lanes for this controller.
static const uint32_t MASK_VALUE
The mask for the lanes for this controller.
static const EOrder RGB_ORDER_VALUE
The RGB ordering for this controller.
Private Member Functions
void ensureBuffer (int size_8bit)
void init () override
Initialize the LED controller.
Private Attributes
ControllerT mController
CRGB * mData = 0
Additional Inherited Members
Static Public Member Functions inherited from CLEDController
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes inherited from CLEDController
Rgbw mRgbMode = RgbwInvalid::value()
Protected Member Functions inherited from CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness) override
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness) override
Set all the LEDs on the controller to a given color.
Protected Attributes inherited from CLEDController
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes inherited from CLEDController
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Member Typedef Documentation
ControllerBaseT
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> WS2812Controller800Khz<DATA_PIN, RGB> WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerBaseT
Definition at line 1136 of file chipsets.h.
Constructor & Destructor Documentation
WS2816Controller()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> WS2816Controller< DATA_PIN, RGB_ORDER >::WS2816Controller () inline
Definition at line 1149 of file chipsets.h.
{}
~WS2816Controller()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> WS2816Controller< DATA_PIN, RGB_ORDER >::~WS2816Controller () inline
Definition at line 1150 of file chipsets.h.
{
        mController.setLeds(nullptr, 0);
        delete [] mData;
    }
References WS2816Controller< DATA_PIN, RGB_ORDER >::mController, and WS2816Controller< DATA_PIN, RGB_ORDER >::mData.
Member Function Documentation
beginShowLeds()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> virtual void * WS2816Controller< DATA_PIN, RGB_ORDER >::beginShowLeds (int size) inline override virtual
Reimplemented from CLEDController.
Definition at line 1155 of file chipsets.h.
{
        mController.setEnabled(true);
        void *result = mController.callBeginShowLeds(2 * size);
        mController.setEnabled(false);
        return result;
    }
References WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callBeginShowLeds(), WS2816Controller< DATA_PIN, RGB_ORDER >::mController, and CLEDController::size().
endShowLeds()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> virtual void WS2816Controller< DATA_PIN, RGB_ORDER >::endShowLeds (void * data) inline override virtual
Reimplemented from CLEDController.
Definition at line 1162 of file chipsets.h.
{
        mController.setEnabled(true);
        mController.callEndShowLeds(data);
        mController.setEnabled(false);
    }
References WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callEndShowLeds(), and WS2816Controller< DATA_PIN, RGB_ORDER >::mController.
ensureBuffer()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> void WS2816Controller< DATA_PIN, RGB_ORDER >::ensureBuffer (int size_8bit) inline private
Definition at line 1214 of file chipsets.h.
{
        int size_16bit = 2 * size_8bit;
        if (mController.size() != size_16bit) {
            delete [] mData;
            CRGB *new_leds = new CRGB[size_16bit];
            mData = new_leds;
            mController.setLeds(new_leds, size_16bit);
        }
    }
References WS2816Controller< DATA_PIN, RGB_ORDER >::mController, and WS2816Controller< DATA_PIN, RGB_ORDER >::mData.
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().
init()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> void WS2816Controller< DATA_PIN, RGB_ORDER >::init () inline override private virtual
Initialize the LED controller.
Implements CLEDController.
Definition at line 1209 of file chipsets.h.
{
        mController.init();
        mController.setEnabled(false);
    }
References WS2816Controller< DATA_PIN, RGB_ORDER >::mController.
showPixels()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> virtual void WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels (PixelController< RGB_ORDER, LANES, MASK > & pixels) inline override virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Implements CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >.
Definition at line 1168 of file chipsets.h.
{
        // Ensure buffer is large enough
        ensureBuffer(pixels.size());
        // expand and copy all the pixels
        size_t out_index = 0;
        while (pixels.has(1)) {
            pixels.stepDithering();
            uint16_t s0, s1, s2;
            pixels.loadAndScale_WS2816_HD(&s0, &s1, &s2);
            uint8_t b0_hi = s0 >> 8;
            uint8_t b0_lo = s0 & 0xFF;
            uint8_t b1_hi = s1 >> 8;
            uint8_t b1_lo = s1 & 0xFF;
            uint8_t b2_hi = s2 >> 8;
            uint8_t b2_lo = s2 & 0xFF;
            mData[out_index] = CRGB(b0_hi, b0_lo, b1_hi);
            mData[out_index + 1] = CRGB(b1_lo, b2_hi, b2_lo);
            pixels.advanceData();
            out_index += 2;
        }
        // ensure device controller won't modify color values
        mController.setCorrection(CRGB(255, 255, 255));
        mController.setTemperature(CRGB(255, 255, 255));
        mController.setDither(DISABLE_DITHER);
        // output the data stream
        mController.setEnabled(true);
#ifdef BOUNCE_SUBCLASS
        mController.callShow(mData, 2 * pixels.size(), 255);
#else
        mController.show(mData, 2 * pixels.size(), 255);
#endif
        mController.setEnabled(false);
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callShow(), DISABLE_DITHER, WS2816Controller< DATA_PIN, RGB_ORDER >::ensureBuffer(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), WS2816Controller< DATA_PIN, RGB_ORDER >::mController, WS2816Controller< DATA_PIN, RGB_ORDER >::mData, PixelController< RGB_ORDER, LANES, MASK >::size(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().
Member Data Documentation
LANES
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> const int WS2816Controller< DATA_PIN, RGB_ORDER >::LANES = ControllerT::LANES_VALUE static
Definition at line 1146 of file chipsets.h.
MASK
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> const uint32_t WS2816Controller< DATA_PIN, RGB_ORDER >::MASK = ControllerT::MASK_VALUE static
Definition at line 1147 of file chipsets.h.
mController
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> ControllerT WS2816Controller< DATA_PIN, RGB_ORDER >::mController private
Definition at line 1225 of file chipsets.h.
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::~WS2816Controller(), WS2816Controller< DATA_PIN, RGB_ORDER >::beginShowLeds(), WS2816Controller< DATA_PIN, RGB_ORDER >::endShowLeds(), WS2816Controller< DATA_PIN, RGB_ORDER >::ensureBuffer(), WS2816Controller< DATA_PIN, RGB_ORDER >::init(), and WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().
mData
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> CRGB* WS2816Controller< DATA_PIN, RGB_ORDER >::mData = 0 private
Definition at line 1224 of file chipsets.h.
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::~WS2816Controller(), WS2816Controller< DATA_PIN, RGB_ORDER >::ensureBuffer(), and WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().
WS2816Controller::ControllerT
class WS2816Controller::ControllerT
Private Member Functions
void * callBeginShowLeds (int size)
void callEndShowLeds (void *data)
void callShow (CRGB *data, int nLeds, uint8_t brightness)
Friends
class WS2816Controller< DATA_PIN, RGB_ORDER >
Member Function Documentation
callBeginShowLeds()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> void * WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callBeginShowLeds (int size) inline private
Definition at line 1139 of file chipsets.h.
{ return ControllerBaseT::beginShowLeds(size); }
References CLEDController::size().
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::beginShowLeds().
callEndShowLeds()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> void WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callEndShowLeds (void * data) inline private
Definition at line 1143 of file chipsets.h.
{ ControllerBaseT::endShowLeds(data); }
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::endShowLeds().
callShow()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> void WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callShow (CRGB * data, int nLeds, uint8_t brightness) inline private
Definition at line 1140 of file chipsets.h.
{
            ControllerBaseT::show(data, nLeds, brightness);
        }
References brightness.
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().
Friends And Related Symbol Documentation
WS2816Controller< DATA_PIN, RGB_ORDER >
template<uint8_t DATA_PIN, EOrder RGB_ORDER = GRB> friend class WS2816Controller< DATA_PIN, RGB_ORDER > friend
Definition at line 1225 of file chipsets.h.