FastLED: Palette Upscaling Functions
Palette Upscaling Functions
Color Palettes
Detailed Description
Functions to upscale palettes from one type to another.
Functions
void UpscalePalette (const class CHSVPalette16 &srcpal16, class CHSVPalette256 &destpal256)
Convert a 16-entry palette to a 256-entry palette.
void UpscalePalette (const class CHSVPalette16 &srcpal16, class CHSVPalette32 &destpal32)
Convert a 16-entry palette to a 32-entry palette.
void UpscalePalette (const class CHSVPalette32 &srcpal32, class CHSVPalette256 &destpal256)
Convert a 32-entry palette to a 256-entry palette.
void UpscalePalette (const class CRGBPalette16 &srcpal16, class CRGBPalette256 &destpal256)
Convert a 16-entry palette to a 256-entry palette.
void UpscalePalette (const class CRGBPalette16 &srcpal16, class CRGBPalette32 &destpal32)
Convert a 16-entry palette to a 32-entry palette.
void UpscalePalette (const class CRGBPalette32 &srcpal32, class CRGBPalette256 &destpal256)
Convert a 32-entry palette to a 256-entry palette.
Function Documentation
UpscalePalette() [1/6]
void UpscalePalette (const class CHSVPalette16 & srcpal16, class CHSVPalette256 & destpal256)
Convert a 16-entry palette to a 256-entry palette.
Parameters
srcpal16 the source palette to upscale
destpal256 the destination palette for the upscaled data
Definition at line 1313 of file colorutils.cpp.
{
    for( int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette( srcpal16, i);
    }
}
References ColorFromPalette().
UpscalePalette() [2/6]
void UpscalePalette (const class CHSVPalette16 & srcpal16, class CHSVPalette32 & destpal32)
Convert a 16-entry palette to a 32-entry palette.
Parameters
srcpal16 the source palette to upscale
destpal32 the destination palette for the upscaled data
Definition at line 1330 of file colorutils.cpp.
{
    for( uint8_t i = 0; i < 16; ++i) {
        uint8_t j = i * 2;
        destpal32[j+0] = srcpal16[i];
        destpal32[j+1] = srcpal16[i];
    }
}
UpscalePalette() [3/6]
void UpscalePalette (const class CHSVPalette32 & srcpal32, class CHSVPalette256 & destpal256)
Convert a 32-entry palette to a 256-entry palette.
Parameters
srcpal32 the source palette to upscale
destpal256 the destination palette for the upscaled data
Definition at line 1346 of file colorutils.cpp.
{
    for( int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette( srcpal32, i);
    }
}
References ColorFromPalette().
UpscalePalette() [4/6]
void UpscalePalette (const class CRGBPalette16 & srcpal16, class CRGBPalette256 & destpal256)
Convert a 16-entry palette to a 256-entry palette.
Parameters
srcpal16 the source palette to upscale
destpal256 the destination palette for the upscaled data
Definition at line 1306 of file colorutils.cpp.
{
    for( int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette( srcpal16, i);
    }
}
References ColorFromPalette().
Referenced by CHSVPalette256::CHSVPalette256(), CRGBPalette256::CRGBPalette256(), CRGBPalette32::CRGBPalette32(), CHSVPalette256::operator=(), CRGBPalette256::operator=(), and CRGBPalette32::operator=().
UpscalePalette() [5/6]
void UpscalePalette (const class CRGBPalette16 & srcpal16, class CRGBPalette32 & destpal32)
Convert a 16-entry palette to a 32-entry palette.
Parameters
srcpal16 the source palette to upscale
destpal32 the destination palette for the upscaled data
Definition at line 1321 of file colorutils.cpp.
{
    for( uint8_t i = 0; i < 16; ++i) {
        uint8_t j = i * 2;
        destpal32[j+0] = srcpal16[i];
        destpal32[j+1] = srcpal16[i];
    }
}
UpscalePalette() [6/6]
void UpscalePalette (const class CRGBPalette32 & srcpal32, class CRGBPalette256 & destpal256)
Convert a 32-entry palette to a 256-entry palette.
Parameters
srcpal32 the source palette to upscale
destpal256 the destination palette for the upscaled data
Definition at line 1339 of file colorutils.cpp.
{
    for( int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette( srcpal32, i);
    }
}
References ColorFromPalette().