FastLED: /home/runner/work/FastLED/FastLED/examples/Pintest/Pintest.ino File Reference
Pintest.ino File Reference
Detailed Description
Checks available pin outputs (for debugging)
Definition in file Pintest.ino.
#include <FastLED.h>
Functions
template<uint8_t _PORT>
const char * _GetPinPort (void *ptr)
template<>
const char * _GetPinPort<-1 > (void *ptr)
template<uint8_t PIN>
void CheckPin ()
template<>
void CheckPin< 255 > ()
const char * GetPinPort (void *ptr)
const char * getPort (void *portRef)
void loop ()
template<uint8_t PIN>
void PrintPins ()
template<>
void PrintPins< 0 > ()
void setup ()
Variables
int counter = 0
char fullstrBuffer [64]
static uint8_t pcount = 0
Function Documentation
_GetPinPort()
template<uint8_t _PORT> const char * _GetPinPort (void * ptr)
Examples
Pintest.ino.
Definition at line 123 of file Pintest.ino.
{
    if (__FL_PORT_INFO<_PORT>::hasPort() && (ptr == (void*)__FL_PORT_INFO<_PORT>::portAddr())) {
        return __FL_PORT_INFO<_PORT>::portName();
    } else {
        return _GetPinPort<_PORT - 1>(ptr);
    }
}
References _GetPinPort(), and __FL_PORT_INFO< port >::portName().
Referenced by _GetPinPort(), and GetPinPort().
_GetPinPort<-1 >()
template<> const char * _GetPinPort<-1 > (void * ptr)
Definition at line 130 of file Pintest.ino.
{
    return NULL;
}
CheckPin()
template<uint8_t PIN> void CheckPin ()
Examples
Pintest.ino.
Definition at line 96 of file Pintest.ino.
{
    CheckPin<PIN - 1>();
    void *systemThinksPortIs = (void*)portOutputRegister(digitalPinToPort(PIN));
    RwReg systemThinksMaskIs = digitalPinToBitMask(PIN);
    Serial.print("Pin "); Serial.print(PIN); Serial.print(": Port ");
    if(systemThinksPortIs == (void*)FastPin<PIN>::port()) {
        Serial.print("valid & mask ");
    } else {
        Serial.print("invalid, is "); Serial.print(getPort((void*)FastPin<PIN>::port())); Serial.print(" should be ");
        Serial.print(getPort((void*)systemThinksPortIs));
        Serial.print(" & mask ");
    }
    if(systemThinksMaskIs == FastPin<PIN>::mask()) {
        Serial.println("valid.");
    } else {
        Serial.print("invalid, is "); Serial.print(FastPin<PIN>::mask()); Serial.print(" should be "); Serial.println(systemThinksMaskIs);
    }
}
References CheckPin(), getPort(), and PIN.
Referenced by CheckPin(), and loop().
CheckPin< 255 >()
template<> void CheckPin< 255 > ()
Examples
Pintest.ino.
Definition at line 120 of file Pintest.ino.
{}
GetPinPort()
const char * GetPinPort (void * ptr)
Examples
Pintest.ino.
Definition at line 134 of file Pintest.ino.
{
    return _GetPinPort<'Z'>(ptr);
}
References _GetPinPort().
Referenced by PrintPins(), and PrintPins< 0 >().
getPort()
const char * getPort (void * portRef)
Examples
Pintest.ino.
Definition at line 9 of file Pintest.ino.
{
// AVR port checks
#ifdef PORTA
    if(portRef == (void*)&PORTA) { return "PORTA"; }
#endif
#ifdef PORTB
    if(portRef == (void*)&PORTB) { return "PORTB"; }
#endif
#ifdef PORTC
    if(portRef == (void*)&PORTC) { return "PORTC"; }
#endif
#ifdef PORTD
    if(portRef == (void*)&PORTD) { return "PORTD"; }
#endif
#ifdef PORTE
    if(portRef == (void*)&PORTE) { return "PORTE"; }
#endif
#ifdef PORTF
    if(portRef == (void*)&PORTF) { return "PORTF"; }
#endif
#ifdef PORTG
    if(portRef == (void*)&PORTG) { return "PORTG"; }
#endif
#ifdef PORTH
    if(portRef == (void*)&PORTH) { return "PORTH"; }
#endif
#ifdef PORTI
    if(portRef == (void*)&PORTI) { return "PORTI"; }
#endif
#ifdef PORTJ
    if(portRef == (void*)&PORTJ) { return "PORTJ"; }
#endif
#ifdef PORTK
    if(portRef == (void*)&PORTK) { return "PORTK"; }
#endif
#ifdef PORTL
    if(portRef == (void*)&PORTL) { return "PORTL"; }
#endif
// Teensy 3.x port checks
#ifdef GPIO_A_PDOR
    if(portRef == (void*)&GPIO_A_PDOR) { return "GPIO_A_PDOR"; }
#endif
#ifdef GPIO_B_PDOR
    if(portRef == (void*)&GPIO_B_PDOR) { return "GPIO_B_PDOR"; }
#endif
#ifdef GPIO_C_PDOR
    if(portRef == (void*)&GPIO_C_PDOR) { return "GPIO_C_PDOR"; }
#endif
#ifdef GPIO_D_PDOR
    if(portRef == (void*)&GPIO_D_PDOR) { return "GPIO_D_PDOR"; }
#endif
#ifdef GPIO_E_PDOR
    if(portRef == (void*)&GPIO_E_PDOR) { return "GPIO_E_PDOR"; }
#endif
#ifdef REG_PIO_A_ODSR
    if(portRef == (void*)&REG_PIO_A_ODSR) { return "REG_PIO_A_ODSR"; }
#endif
#ifdef REG_PIO_B_ODSR
    if(portRef == (void*)&REG_PIO_B_ODSR) { return "REG_PIO_B_ODSR"; }
#endif
#ifdef REG_PIO_C_ODSR
    if(portRef == (void*)&REG_PIO_C_ODSR) { return "REG_PIO_C_ODSR"; }
#endif
#ifdef REG_PIO_D_ODSR
    if(portRef == (void*)&REG_PIO_D_ODSR) { return "REG_PIO_D_ODSR"; }
#endif
// Teensy 4 port checks
#ifdef GPIO1_DR
    if(portRef == (void*)&GPIO1_DR) { return "GPIO1_DR"; }
#endif
#ifdef GPIO2_DR
if(portRef == (void*)&GPIO2_DR) { return "GPIO21_DR"; }
#endif
#ifdef GPIO3_DR
if(portRef == (void*)&GPIO3_DR) { return "GPIO3_DR"; }
#endif
#ifdef GPIO4_DR
if(portRef == (void*)&GPIO4_DR) { return "GPIO4_DR"; }
#endif
  String unknown_str = "Unknown: " + String((size_t)portRef, HEX);
    strncpy(fullstrBuffer, unknown_str.c_str(), unknown_str.length());
    fullstrBuffer[sizeof(fullstrBuffer)-1] = '\0';
    return fullstrBuffer;
}
References fullstrBuffer.
Referenced by CheckPin().
loop()
void loop ()
Definition at line 188 of file Pintest.ino.
            {
    Serial.println(counter);
#ifdef MAX_PIN
    CheckPin<MAX_PIN>();
#endif
    Serial.println("-----");
#ifdef NUM_DIGITAL_PINS
    PrintPins<NUM_DIGITAL_PINS>();
#endif
    Serial.println("------");
    delay(100000);
}
References CheckPin(), counter, and PrintPins().
PrintPins()
template<uint8_t PIN> void PrintPins ()
Examples
Pintest.ino.
Definition at line 141 of file Pintest.ino.
{
    PrintPins<PIN - 1>();
    RwReg *systemThinksPortIs = portOutputRegister(digitalPinToPort(PIN));
    RwReg systemThinksMaskIs = digitalPinToBitMask(PIN);
    int maskBit = 0;
    while(systemThinksMaskIs > 1) { systemThinksMaskIs >>= 1; maskBit++; }
    const char *pinport = GetPinPort((void*)systemThinksPortIs);
    if (pinport) {
        Serial.print("__FL_DEFPIN("); Serial.print(PIN);
        Serial.print(","); Serial.print(maskBit);
        Serial.print(","); Serial.print(pinport);
        Serial.print("); ");
        pcount++;
        if(pcount == 4) { pcount = 0; Serial.println(""); }
    } else {
        // Serial.print("Not found for pin "); Serial.println(PIN);
    }
}
References GetPinPort(), pcount, PIN, and PrintPins().
Referenced by loop(), and PrintPins().
PrintPins< 0 >()
template<> void PrintPins< 0 > ()
Examples
Pintest.ino.
Definition at line 163 of file Pintest.ino.
{
    RwReg *systemThinksPortIs = portOutputRegister(digitalPinToPort(0));
    RwReg systemThinksMaskIs = digitalPinToBitMask(0);
    int maskBit = 0;
    while(systemThinksMaskIs > 1) { systemThinksMaskIs >>= 1; maskBit++; }
    const char *pinport = GetPinPort((void*)systemThinksPortIs);
    if (pinport) {
        Serial.print("__FL_DEFPIN("); Serial.print(0);
        Serial.print(","); Serial.print(maskBit);
        Serial.print(","); Serial.print(pinport);
        Serial.print("); ");
        pcount++;
        if(pcount == 4) { pcount = 0; Serial.println(""); }
    }
}
References GetPinPort(), and pcount.
setup()
void setup ()
Definition at line 182 of file Pintest.ino.
             {
    delay(5000);
    Serial.begin(38400);
    Serial.println("resetting!");
}
Variable Documentation
counter
int counter = 0
Examples
Pintest.ino.
Definition at line 181 of file Pintest.ino.
Referenced by loop().
fullstrBuffer
char fullstrBuffer[64]
Examples
Pintest.ino.
Definition at line 7 of file Pintest.ino.
Referenced by getPort().
pcount
uint8_t pcount = 0 static
Examples
Pintest.ino.
Definition at line 138 of file Pintest.ino.
Referenced by PrintPins(), and PrintPins< 0 >().