FastLED: fl::UINumberField Class Reference
fl::UINumberField Class Reference
Detailed Description
Definition at line 113 of file ui.h.
#include <ui.h>
Public Member Functions
UINumberField (const char *name, double value, double min=0, double max=100)
~UINumberField ()
operator double () const
operator int () const
UINumberField & operator= (double value)
UINumberField & operator= (int value)
void setValue (double value)
double value () const
Private Attributes
double mMax
double mMin
double mValue
Constructor & Destructor Documentation
UINumberField()
fl::UINumberField::UINumberField (const char * name, double value, double min = 0, double max = 100) inline
Definition at line 115 of file ui.h.
      : mValue(value), mMin(MIN(min, max)), mMax(MAX(min, max)) {
        FASTLED_UNUSED(name);
    }
References FASTLED_UNUSED.
~UINumberField()
fl::UINumberField::~UINumberField () inline
Definition at line 119 of file ui.h.
{}
Member Function Documentation
operator double()
fl::UINumberField::operator double () const inline
Definition at line 122 of file ui.h.
{ return mValue; }
References mValue.
operator int()
fl::UINumberField::operator int () const inline
Definition at line 123 of file ui.h.
{ return static_cast<int>(mValue); }
References mValue.
operator=() [1/2]
UINumberField & fl::UINumberField::operator= (double value) inline
Definition at line 124 of file ui.h.
{ setValue(value); return *this; }
References setValue(), and value().
operator=() [2/2]
UINumberField & fl::UINumberField::operator= (int value) inline
Definition at line 125 of file ui.h.
{ setValue(static_cast<double>(value)); return *this; }
References setValue(), and value().
setValue()
void fl::UINumberField::setValue (double value) inline
Definition at line 121 of file ui.h.
{ mValue = MAX(mMin, MIN(mMax, value)); }
References MAX, MIN, mMax, mMin, mValue, and value().
Referenced by operator=(), and operator=().
value()
double fl::UINumberField::value () const inline
Definition at line 120 of file ui.h.
{ return mValue; }
References mValue.
Referenced by loop(), operator=(), operator=(), and setValue().
Member Data Documentation
mMax
double fl::UINumberField::mMax private
Definition at line 129 of file ui.h.
Referenced by setValue().
mMin
double fl::UINumberField::mMin private
Definition at line 128 of file ui.h.
Referenced by setValue().
mValue
double fl::UINumberField::mValue private
Definition at line 127 of file ui.h.
Referenced by operator double(), operator int(), setValue(), and value().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ui.h