FastLED: Dimming and Brightening Functions
Dimming and Brightening Functions
Fast Math Functions
Detailed Description
Functions to dim or brighten data.
The eye does not respond in a linear way to light. High speed PWM'd LEDs at 50% duty cycle appear far brighter then the "half as bright" you might expect.
If you want your midpoint brightness LEDs (128) to appear half as bright as "full" brightness (255), you have to apply a "dimming function".
Note
These are approximations of gamma correction with a gamma value of 2.0.
See also
Gamma Adjustment Functions
Functions
LIB8STATIC uint8_t brighten8_lin (uint8_t x)
Brighten a value (inverse of dim8_lin())
LIB8STATIC uint8_t brighten8_raw (uint8_t x)
Brighten a value (inverse of dim8_raw())
LIB8STATIC uint8_t brighten8_video (uint8_t x)
Brighten a value (inverse of dim8_video())
uint8_t brightness_bitshifter16 (uint8_t *brightness_src, uint16_t *brightness_dst, uint8_t max_shifts, uint8_t steps=2)
uint8_t brightness_bitshifter8 (uint8_t *brightness_src, uint8_t *brightness_dst, uint8_t max_shifts)
LIB8STATIC uint8_t dim8_lin (uint8_t x)
Linear version of the dimming function that halves for values < 128.
LIB8STATIC uint8_t dim8_raw (uint8_t x)
Adjust a scaling value for dimming.
LIB8STATIC uint8_t dim8_video (uint8_t x)
Adjust a scaling value for dimming for video (value will never go below 1)
Function Documentation
brighten8_lin()
LIB8STATIC uint8_t brighten8_lin (uint8_t x)
Brighten a value (inverse of dim8_lin())
Definition at line 733 of file scale8.h.
{
    uint8_t ix = 255 - x;
    if (ix & 0x80) {
        ix = scale8(ix, ix);
    } else {
        ix += 1;
        ix /= 2;
    }
    return 255 - ix;
}
References scale8(), and x.
brighten8_raw()
LIB8STATIC uint8_t brighten8_raw (uint8_t x)
Brighten a value (inverse of dim8_raw())
Definition at line 721 of file scale8.h.
{
    uint8_t ix = 255 - x;
    return 255 - scale8(ix, ix);
}
References scale8(), and x.
brighten8_video()
LIB8STATIC uint8_t brighten8_video (uint8_t x)
Brighten a value (inverse of dim8_video())
Definition at line 727 of file scale8.h.
{
    uint8_t ix = 255 - x;
    return 255 - scale8_video(ix, ix);
}
References scale8_video(), and x.
brightness_bitshifter16()
uint8_t brightness_bitshifter16 (uint8_t * brightness_src, uint16_t * brightness_dst, uint8_t max_shifts, uint8_t steps = 2) inline
Definition at line 43 of file brightness_bitshifter.h.
{
    uint8_t src = *brightness_src;
    if (*brightness_dst == 0 || src == 0) {
        return 0;
    }
    uint16_t overflow_mask = 0b1000000000000000;
    for (uint8_t i = 1; i < steps; i++) {
        overflow_mask >>= 1;
        overflow_mask |= 0b1000000000000000;
    }
    const uint8_t underflow_mask = 0x1;
    // Steal brightness from brightness_src and give it to brightness_dst.
    // After this function concludes the multiplication of brightness_dst and brightness_src will remain
    // constant.
    uint16_t curr = *brightness_dst;
    uint8_t shifts = 0;
    for (uint8_t i = 0; i < max_shifts; i++) {
        if (src & underflow_mask) {
            break;
        }
        if (curr & overflow_mask) {
            // next shift will overflow
            break;
        }
        curr <<= steps;
        src >>= 1;
        shifts++;
    }
    // write out the output values.
    *brightness_dst = curr;
    *brightness_src = src;
    return shifts;
}
Referenced by fl::five_bit_bitshift().
brightness_bitshifter8()
uint8_t brightness_bitshifter8 (uint8_t * brightness_src, uint8_t * brightness_dst, uint8_t max_shifts) inline
Definition at line 14 of file brightness_bitshifter.h.
{
    uint8_t src = *brightness_src;
    if (*brightness_dst == 0 || src == 0) {
        return 0;
    }
    // Steal brightness from brightness_src and give it to brightness_dst.
    // After this function concludes the multiplication of brightness_dst and brightness_src will remain
    // constant.
    // This algorithm is a little difficult to follow and I don't understand why it works that well,
    // however I did work it out manually and has something to do with how numbers respond to bitshifts.
    uint8_t curr = *brightness_dst;
    uint8_t shifts = 0;
    for (uint8_t i = 0; i < max_shifts && src > 1; i++) {
        if (curr & 0b10000000) {
            // next shift will overflow
            break;
        }
        curr <<= 1;
        src >>= 1;
        shifts++;
    }
    // write out the output values.
    *brightness_dst = curr;
    *brightness_src = src;
    return shifts;
}
Referenced by fl::five_bit_bitshift().
dim8_lin()
LIB8STATIC uint8_t dim8_lin (uint8_t x)
Linear version of the dimming function that halves for values < 128.
Definition at line 710 of file scale8.h.
{
    if (x & 0x80) {
        x = scale8(x, x);
    } else {
        x += 1;
        x /= 2;
    }
    return x;
}
References scale8(), and x.
dim8_raw()
LIB8STATIC uint8_t dim8_raw (uint8_t x)
Adjust a scaling value for dimming.
See also
scale8()
Examples
NoisePlusPalette.ino.
Definition at line 703 of file scale8.h.
{ return scale8(x, x); }
References scale8(), and x.
Referenced by fl::NoisePalette::mapNoiseToLEDsUsingPalette(), mapNoiseToLEDsUsingPalette(), and software_gamma().
dim8_video()
LIB8STATIC uint8_t dim8_video (uint8_t x)
Adjust a scaling value for dimming for video (value will never go below 1)
See also
scale8_video()
Definition at line 707 of file scale8.h.
{ return scale8_video(x, x); }
References scale8_video(), and x.