FastLED: /home/runner/work/FastLED/FastLED/examples/ColorTemperature/ColorTemperature.ino File Reference
ColorTemperature.ino File Reference
Detailed Description
Demonstrates how to use ColorTemperature based color correction.
Definition in file ColorTemperature.ino.
#include <FastLED.h>
Macros
#define BLACKTIME 3
#define BRIGHTNESS 128
#define CHIPSET WS2811
#define COLOR_ORDER GRB
#define DISPLAYTIME 20
#define LED_PIN 3
#define NUM_LEDS 60
#define TEMPERATURE_1 Tungsten100W
#define TEMPERATURE_2 OvercastSky
Functions
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Macro Definition Documentation
BLACKTIME
#define BLACKTIME 3
Examples
ColorTemperature.ino.
Definition at line 54 of file ColorTemperature.ino.
Referenced by loop().
BRIGHTNESS
#define BRIGHTNESS 128
Definition at line 15 of file ColorTemperature.ino.
CHIPSET
#define CHIPSET WS2811
Examples
ColorTemperature.ino, Fire2012.ino, Fire2012WithPalette.ino, and XYMatrix.ino.
Definition at line 11 of file ColorTemperature.ino.
Referenced by CFastLED::addLeds(), and setup().
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 12 of file ColorTemperature.ino.
DISPLAYTIME
#define DISPLAYTIME 20
Examples
ColorTemperature.ino.
Definition at line 52 of file ColorTemperature.ino.
Referenced by loop().
LED_PIN
#define LED_PIN 3
Definition at line 7 of file ColorTemperature.ino.
NUM_LEDS
#define NUM_LEDS 60
Definition at line 10 of file ColorTemperature.ino.
TEMPERATURE_1
#define TEMPERATURE_1 Tungsten100W
Examples
ColorTemperature.ino.
Definition at line 48 of file ColorTemperature.ino.
Referenced by loop().
TEMPERATURE_2
#define TEMPERATURE_2 OvercastSky
Examples
ColorTemperature.ino.
Definition at line 49 of file ColorTemperature.ino.
Referenced by loop().
Function Documentation
loop()
void loop ()
Definition at line 56 of file ColorTemperature.ino.
{
  // draw a generic, no-name rainbow
  static uint8_t starthue = 0;
  fill_rainbow( leds + 5, NUM_LEDS - 5, --starthue, 20);
  // Choose which 'color temperature' profile to enable.
  uint8_t secs = (millis() / 1000) % (DISPLAYTIME * 2);
  if( secs < DISPLAYTIME) {
    FastLED.setTemperature( TEMPERATURE_1 ); // first temperature
    leds[0] = TEMPERATURE_1; // show indicator pixel
  } else {
    FastLED.setTemperature( TEMPERATURE_2 ); // second temperature
    leds[0] = TEMPERATURE_2; // show indicator pixel
  }
  // Black out the LEDs for a few secnds between color changes
  // to let the eyes and brains adjust
  if( (secs % DISPLAYTIME) < BLACKTIME) {
    memset8( leds, 0, NUM_LEDS * sizeof(CRGB));
  }
  FastLED.show();
  FastLED.delay(8);
}
References BLACKTIME, CFastLED::delay(), DISPLAYTIME, FastLED, fill_rainbow(), leds, memset8(), NUM_LEDS, CFastLED::setTemperature(), CFastLED::show(), TEMPERATURE_1, and TEMPERATURE_2.
setup()
void setup ()
Definition at line 82 of file ColorTemperature.ino.
             {
  delay( 3000 ); // power-up safety delay
  // It's important to set the color correction for your LED strip here,
  // so that colors can be more accurately rendered through the 'temperature' profiles
  FastLED.addLeds<CHIPSET, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalSMD5050 );
  FastLED.setBrightness( BRIGHTNESS );
}
References CFastLED::addLeds(), BRIGHTNESS, CHIPSET, COLOR_ORDER, FastLED, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), and TypicalSMD5050.
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 13 of file ColorTemperature.ino.