FastLED: fl::FxCompositor Class Reference
fl::FxCompositor Class Reference
Detailed Description
Definition at line 22 of file fx_compositor.h.
#include <fx_compositor.h>
Public Member Functions
FxCompositor (uint32_t numLeds)
void completeTransition ()
void draw (uint32_t now, uint32_t warpedTime, CRGB *finalBuffer)
void startTransition (uint32_t now, uint32_t duration, fl::Ptr< Fx > nextFx)
Private Member Functions
void swapLayers ()
Private Attributes
FxLayerPtr mLayers [2]
const uint32_t mNumLeds
Transition mTransition
Constructor & Destructor Documentation
FxCompositor()
fl::FxCompositor::FxCompositor (uint32_t numLeds) inline
Definition at line 24 of file fx_compositor.h.
                                   : mNumLeds(numLeds) {
        mLayers[0] = FxLayerPtr::New();
        mLayers[1] = FxLayerPtr::New();
    }
References mLayers.
Member Function Documentation
completeTransition()
void fl::FxCompositor::completeTransition () inline
Definition at line 39 of file fx_compositor.h.
{
        if (mLayers[1]->getFx()) {
            swapLayers();
            mLayers[1]->release();
        }
        mTransition.end();
    }
References fl::Transition::end(), mLayers, mTransition, and swapLayers().
Referenced by draw(), and startTransition().
draw()
void fl::FxCompositor::draw (uint32_t now, uint32_t warpedTime, CRGB * finalBuffer) inline
Definition at line 61 of file fx_compositor.h.
{
    if (!mLayers[0]->getFx()) {
        return;
    }
    mLayers[0]->draw(warpedTime);
    uint8_t progress = mTransition.getProgress(now);
    if (!progress) {
        memcpy(finalBuffer, mLayers[0]->getSurface(), sizeof(CRGB) * mNumLeds);
        return;
    }
    mLayers[1]->draw(warpedTime);
    const CRGB* surface0 = mLayers[0]->getSurface();
    const CRGB* surface1 = mLayers[1]->getSurface();
    for (uint32_t i = 0; i < mNumLeds; i++) {
        const CRGB& p0 = surface0[i];
        const CRGB& p1 = surface1[i];
        CRGB out = CRGB::blend(p0, p1, progress);
        finalBuffer[i] = out;
    }
    if (progress == 255) {
        completeTransition();
    }
}
References CRGB::blend(), completeTransition(), fl::Transition::getProgress(), mLayers, mNumLeds, and mTransition.
Referenced by fl::FxEngine::draw().
startTransition()
void fl::FxCompositor::startTransition (uint32_t now, uint32_t duration, fl::Ptr< Fx > nextFx) inline
Definition at line 29 of file fx_compositor.h.
{
        completeTransition();
        if (duration == 0) {
            mLayers[0]->setFx(nextFx);
            return;
        }
        mLayers[1]->setFx(nextFx);
        mTransition.start(now, duration);
    }
References completeTransition(), mLayers, mTransition, and fl::Transition::start().
Referenced by fl::FxEngine::addFx(), and fl::FxEngine::draw().
swapLayers()
void fl::FxCompositor::swapLayers () inline private
Definition at line 50 of file fx_compositor.h.
                      {
        FxLayerPtr tmp = mLayers[0];
        mLayers[0] = mLayers[1];
        mLayers[1] = tmp;
    }
References mLayers.
Referenced by completeTransition().
Member Data Documentation
mLayers
FxLayerPtr fl::FxCompositor::mLayers[2] private
Definition at line 56 of file fx_compositor.h.
Referenced by FxCompositor(), completeTransition(), draw(), startTransition(), and swapLayers().
mNumLeds
const uint32_t fl::FxCompositor::mNumLeds private
Definition at line 57 of file fx_compositor.h.
Referenced by draw().
mTransition
Transition fl::FxCompositor::mTransition private
Definition at line 58 of file fx_compositor.h.
Referenced by completeTransition(), draw(), and startTransition().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/detail/fx_compositor.h