FastLED: /home/runner/work/FastLED/FastLED/examples/Overclock/Overclock.ino File Reference
Overclock.ino File Reference
Detailed Description
Demonstrates how to overclock a FastLED setup.
Definition in file Overclock.ino.
#include "fx/2d/noisepalette.h"
#include "fx/fx.h"
#include <FastLED.h>
Macros
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define FASTLED_OVERCLOCK 1.1
#define GRID_SERPENTINE 1
#define LED_PIN 3
#define LED_TYPE WS2811
#define MATRIX_HEIGHT 22
#define MATRIX_WIDTH 22
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
#define SCALE 20
#define SPEED 30
Functions
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
NoisePalette noisePalette (xyMap)
XYMap xyMap (MATRIX_WIDTH, MATRIX_HEIGHT, GRID_SERPENTINE)
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 24 of file Overclock.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 26 of file Overclock.ino.
Referenced by setup().
FASTLED_OVERCLOCK
#define FASTLED_OVERCLOCK 1.1
Definition at line 15 of file Overclock.ino.
GRID_SERPENTINE
#define GRID_SERPENTINE 1
Definition at line 30 of file Overclock.ino.
LED_PIN
#define LED_PIN 3
Definition at line 23 of file Overclock.ino.
Referenced by setup().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 25 of file Overclock.ino.
Referenced by setup().
MATRIX_HEIGHT
#define MATRIX_HEIGHT 22
Definition at line 29 of file Overclock.ino.
MATRIX_WIDTH
#define MATRIX_WIDTH 22
Definition at line 28 of file Overclock.ino.
NUM_LEDS
#define NUM_LEDS (MATRIX_WIDTH * MATRIX_HEIGHT)
Definition at line 32 of file Overclock.ino.
Referenced by setup().
SCALE
#define SCALE 20
Examples
FxEngine.ino.
Definition at line 63 of file Overclock.ino.
Referenced by setup().
SPEED
#define SPEED 30
Examples
FxEngine.ino.
Definition at line 69 of file Overclock.ino.
Referenced by setup().
Function Documentation
loop()
void loop ()
Definition at line 85 of file Overclock.ino.
            {
    EVERY_N_MILLISECONDS(5000) { noisePalette.changeToRandomPalette(); }
    noisePalette.draw(Fx::DrawContext(millis(), leds));
    FastLED.show();
}
References fl::NoisePalette::changeToRandomPalette(), fl::NoisePalette::draw(), EVERY_N_MILLISECONDS, FastLED, leds, noisePalette, and CFastLED::show().
setup()
void setup ()
Definition at line 76 of file Overclock.ino.
             {
    delay(1000); // sanity delay
    FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
        .setCorrection(TypicalLEDStrip).setScreenMap(xyMap);
    FastLED.setBrightness(96);
    noisePalette.setSpeed(SPEED);
    noisePalette.setScale(SCALE);
}
References CFastLED::addLeds(), COLOR_ORDER, FastLED, LED_PIN, LED_TYPE, leds, noisePalette, NUM_LEDS, SCALE, CFastLED::setBrightness(), fl::NoisePalette::setScale(), CLEDController::setScreenMap(), fl::NoisePalette::setSpeed(), SPEED, TypicalLEDStrip, and xyMap.
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 71 of file Overclock.ino.
Referenced by loop(), and setup().
noisePalette
NoisePalette noisePalette(xyMap) (xyMap)
Referenced by loop(), and setup().
xyMap
XYMap xyMap(MATRIX_WIDTH, MATRIX_HEIGHT, GRID_SERPENTINE) (MATRIX_WIDTH , MATRIX_HEIGHT , GRID_SERPENTINE)
Referenced by setup().