FastLED: /home/runner/work/FastLED/FastLED/examples/FxNoiseRing/FxNoiseRing.ino File Reference
FxNoiseRing.ino File Reference
#include <Arduino.h>
#include <stdio.h>
#include "fl/json.h"
#include "fl/math_macros.h"
#include "fl/warn.h"
#include "noisegen.h"
#include "fl/screenmap.h"
#include "fl/slice.h"
#include "fl/ui.h"
#include "FastLED.h"
#include "sensors/pir.h"
#include "timer.h"
Macros
#define COLOR_ORDER GRB
#define LED_PIN 2
#define NUM_LEDS 250
#define PIN_PIR 0
#define PIR_FALLING_TIME 1000
#define PIR_LATCH_MS 60000
#define PIR_RISING_TIME 1000
Functions
void draw (uint32_t now)
void handleSerialDither ()
void loop ()
void setup ()
Variables
UISlider brightness ("Brightness", 1, 0, 1)
CLEDController * controller = nullptr
float current_brightness = 0
CRGB leds [NUM_LEDS]
PirAdvanced pir (PIN_PIR, PIR_LATCH_MS, PIR_RISING_TIME, PIR_FALLING_TIME)
UISlider scale ("Scale", 4,.1, 4,.1)
UISlider timeBitshift ("Time Bitshift", 5, 0, 16, 1)
Timer timer
UISlider timescale ("Time Scale", 1,.1, 10,.1)
UICheckbox useDither ("Use Binary Dither", true)
Macro Definition Documentation
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 29 of file FxNoiseRing.ino.
Referenced by setup().
LED_PIN
#define LED_PIN 2
Definition at line 28 of file FxNoiseRing.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 250
Definition at line 30 of file FxNoiseRing.ino.
Referenced by draw(), and setup().
PIN_PIR
#define PIN_PIR 0
Definition at line 31 of file FxNoiseRing.ino.
PIR_FALLING_TIME
#define PIR_FALLING_TIME 1000
Definition at line 35 of file FxNoiseRing.ino.
PIR_LATCH_MS
#define PIR_LATCH_MS 60000
Definition at line 33 of file FxNoiseRing.ino.
PIR_RISING_TIME
#define PIR_RISING_TIME 1000
Definition at line 34 of file FxNoiseRing.ino.
Function Documentation
draw()
void draw (uint32_t now)
Definition at line 77 of file FxNoiseRing.ino.
{
    double angle_offset = double(now) / 32000.0 * 2 * M_PI;
    now = (now << timeBitshift.as<int>()) * timescale.as<double>();
    // go in circular formation and set the leds
    for (int i = 0; i < NUM_LEDS; i++) {
        float angle = i * 2 * M_PI / NUM_LEDS + angle_offset;
        float x = cos(angle);
        float y = sin(angle);
        x *= 0xffff * scale.as<double>();
        y *= 0xffff * scale.as<double>();
        uint16_t noise = inoise16(x, y, now);
        uint16_t noise2 = inoise16(x, y, 0xfff + now);
        uint16_t noise3 = inoise16(x, y, 0xffff + now);
        noise3 = noise3 >> 8;
        int16_t noise4 = map(noise3, 0, 255, -64, 255);
        if (noise4 < 0) {
            noise4 = 0;
        }
        leds[i] = CHSV(noise >> 8, MAX(128, noise2 >> 8), noise4);
    }
}
References fl::UISlider::as(), inoise16(), leds, MAX, noise, noise2, NUM_LEDS, scale, timeBitshift, timescale, x, and y.
Referenced by loop().
handleSerialDither()
void handleSerialDither ()
Definition at line 53 of file FxNoiseRing.ino.
{
    if (Serial.available()) {
        char input = Serial.read();
        if (input == '0') {
            useDither = false;
        } else if (input == '1') {
            useDither = true;
        } else {
            FASTLED_WARN("Invalid dither input. Use 0 or 1");
        }
    }
}
References FASTLED_WARN, and useDither.
Referenced by loop().
loop()
void loop ()
Definition at line 99 of file FxNoiseRing.ino.
            {
    handleSerialDither();  // Add this line at start of loop()
    controller->setDither(useDither ? BINARY_DITHER : DISABLE_DITHER);
    EVERY_N_SECONDS(1) {
        FASTLED_WARN("loop");
    }
    uint8_t bri = pir.transition(millis());
    FastLED.setBrightness(bri * brightness.as<float>());
    draw(millis());
    FastLED.show();
}
References fl::UISlider::as(), BINARY_DITHER, brightness, controller, DISABLE_DITHER, draw(), EVERY_N_SECONDS, FastLED, FASTLED_WARN, handleSerialDither(), pir, CFastLED::setBrightness(), CLEDController::setDither(), CFastLED::show(), fl::PirAdvanced::transition(), and useDither.
setup()
void setup ()
Definition at line 66 of file FxNoiseRing.ino.
             {
    Serial.begin(115200);
    ScreenMap xyMap = ScreenMap::Circle(NUM_LEDS, 2.0, 2.0);
    controller = &FastLED.addLeds<WS2811, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
                .setCorrection(TypicalLEDStrip)
                .setDither(DISABLE_DITHER)
                .setScreenMap(xyMap);
    FastLED.setBrightness(brightness);
    pir.activate(millis());  // Activate the PIR sensor on startup.
}
References fl::PirAdvanced::activate(), CFastLED::addLeds(), brightness, fl::ScreenMap::Circle(), COLOR_ORDER, controller, DISABLE_DITHER, FastLED, LED_PIN, leds, NUM_LEDS, pir, CFastLED::setBrightness(), TypicalLEDStrip, and xyMap.
Variable Documentation
brightness
UISlider brightness("Brightness", 1, 0, 1) ("Brightness" , 1 , 0 , 1)
Referenced by loop(), and setup().
controller
CLEDController* controller = nullptr
Definition at line 51 of file FxNoiseRing.ino.
Referenced by CFastLED::addLeds(), loop(), and setup().
current_brightness
float current_brightness = 0
Definition at line 49 of file FxNoiseRing.ino.
leds
CRGB leds[NUM_LEDS]
Definition at line 39 of file FxNoiseRing.ino.
Referenced by draw(), and setup().
pir
PirAdvanced pir(PIN_PIR, PIR_LATCH_MS, PIR_RISING_TIME, PIR_FALLING_TIME) (PIN_PIR , PIR_LATCH_MS , PIR_RISING_TIME , PIR_FALLING_TIME)
Referenced by loop(), and setup().
scale
UISlider scale("Scale", 4,.1, 4,.1) ("Scale" , 4 , . 1, 4 , . 1)
Examples
Noise.ino, NoisePlusPalette.ino, and SmartMatrix.ino.
Referenced by DATA_NOP::adjust(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale0(), ChangePaletteAndSettingsPeriodically(), CRGB::computeAdjustment(), draw(), fill_noise16(), fill_noise8(), fill_raw_noise16into8(), fill_raw_noise8(), fillnoise8(), CLEDController::getAdjustment(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), Color3i::Mulf(), nscale8(), nscale8_LEAVING_R1_DIRTY(), nscale8_video(), nscale8_video_LEAVING_R1_DIRTY(), nscale8x2(), nscale8x2_video(), nscale8x3(), nscale8x3_constexpr(), nscale8x3_video(), PixelController< RGB_ORDER, LANES, MASK >::scale(), scale16(), scale16by8(), scale8(), scale8_constexpr(), scale8_LEAVING_R1_DIRTY(), scale8_video(), scale8_video_LEAVING_R1_DIRTY(), MidiInterface< Transport, _Settings, _Platform >::sendPitchBend(), CFastLED::setBrightness(), fl::FxEngine::setSpeed(), CFastLED::show(), CFastLED::showColor(), animartrix_detail::ANIMartRIX::SM10(), and PixelController< RGB_ORDER, LANES, MASK >::stepAdvanceAndLoadAndScale0().
timeBitshift
UISlider timeBitshift("Time Bitshift", 5, 0, 16, 1) ("Time Bitshift" , 5 , 0 , 16 , 1)
Referenced by draw().
timer
Timer timer
Definition at line 48 of file FxNoiseRing.ino.
timescale
UISlider timescale("Time Scale", 1,.1, 10,.1) ("Time Scale" , 1 , . 1, 10 , . 1)
Referenced by draw().
useDither
UICheckbox useDither("Use Binary Dither", true) ("Use Binary Dither" , true)
Referenced by handleSerialDither(), and loop().