FastLED: Noise Fill Functions
Noise Fill Functions
Noise Functions
Detailed Description
Functions to fill a buffer with noise data.
Raw Fill Functions
Fill a 1D or 2D array with generated noise.
void fill_raw_noise8 (uint8_t *pData, uint8_t num_points, uint8_t octaves, uint16_t x, int scalex, uint16_t time)
Fill a 1D 8-bit buffer with noise, using inoise8()
void fill_raw_noise16into8 (uint8_t *pData, uint8_t num_points, uint8_t octaves, uint32_t x, int scalex, uint32_t time)
Fill a 1D 8-bit buffer with noise, using inoise16()
void fill_raw_2dnoise8 (uint8_t *pData, int width, int height, uint8_t octaves, q44 freq44, fract8 amplitude, int skip, uint16_t x, int16_t scalex, uint16_t y, int16_t scaley, uint16_t time)
Fill a 2D 8-bit buffer with noise, using inoise8()
void fill_raw_2dnoise8 (uint8_t *pData, int width, int height, uint8_t octaves, uint16_t x, int scalex, uint16_t y, int scaley, uint16_t time)
void fill_raw_2dnoise8 (uint8_t *pData, int width, int height, uint8_t octaves, uint16_t x, int16_t scalex, uint16_t y, int16_t scaley, uint16_t time)
Fill a 2D 8-bit buffer with noise, using inoise8()
void fill_raw_2dnoise16into8 (uint8_t *pData, int width, int height, uint8_t octaves, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 8-bit buffer with noise, using inoise16()
void fill_raw_2dnoise16 (uint16_t *pData, int width, int height, uint8_t octaves, q88 freq88, fract16 amplitude, int skip, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 16-bit buffer with noise, using inoise16()
void fill_raw_2dnoise16into8 (uint8_t *pData, int width, int height, uint8_t octaves, q44 freq44, fract8 amplitude, int skip, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 8-bit buffer with noise, using inoise16()
Fill Functions
Fill an LED array with colors based on noise.
Colors are calculated using noisemaps, randomly selecting hue and value (brightness) points with full saturation (255).
void fill_noise8 (CRGB *leds, int num_leds, uint8_t octaves, uint16_t x, int scale, uint8_t hue_octaves, uint16_t hue_x, int hue_scale, uint16_t time)
Fill an LED array with random colors, using 8-bit noise.
void fill_noise16 (CRGB *leds, int num_leds, uint8_t octaves, uint16_t x, int scale, uint8_t hue_octaves, uint16_t hue_x, int hue_scale, uint16_t time, uint8_t hue_shift=0)
Fill an LED array with random colors, using 16-bit noise.
void fill_2dnoise8 (CRGB *leds, int width, int height, bool serpentine, uint8_t octaves, uint16_t x, int xscale, uint16_t y, int yscale, uint16_t time, uint8_t hue_octaves, uint16_t hue_x, int hue_xscale, uint16_t hue_y, uint16_t hue_yscale, uint16_t hue_time, bool blend)
Fill an LED matrix with random colors, using 8-bit noise.
void fill_2dnoise16 (CRGB *leds, int width, int height, bool serpentine, uint8_t octaves, uint32_t x, int xscale, uint32_t y, int yscale, uint32_t time, uint8_t hue_octaves, uint16_t hue_x, int hue_xscale, uint16_t hue_y, uint16_t hue_yscale, uint16_t hue_time, bool blend, uint16_t hue_shift=0)
Fill an LED matrix with random colors, using 16-bit noise.
Function Documentation
fill_2dnoise16()
void fill_2dnoise16 (CRGB * leds, int width, int height, bool serpentine, uint8_t octaves, uint32_t x, int xscale, uint32_t y, int yscale, uint32_t time, uint8_t hue_octaves, uint16_t hue_x, int hue_xscale, uint16_t hue_y, uint16_t hue_yscale, uint16_t hue_time, bool blend, uint16_t hue_shift = 0)
Fill an LED matrix with random colors, using 16-bit noise.
Parameters
leds pointer to LED array
width the width of the LED matrix
height the height of the LED matrix
serpentine whether the matrix is laid out in a serpentine pattern (alternating left/right directions per row)
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
xscale the scale (distance) between x points when filling in value (brightness) noise
y y-axis coordinate on noise map for value (brightness) noise
yscale the scale (distance) between y points when filling in value (brightness) noise
time the time position for the value (brightness) noise field
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_xscale the scale (distance) between x points when filling in color hue noise
hue_y y-axis coordinate on noise map for color hue noise.
hue_yscale the scale (distance) between y points when filling in color hue noise
hue_time the time position for the color hue noise field
blend if true, will blend the newly generated LED values into the array. If false, will overwrite the array values directly.
hue_shift how much to shift the final hues by for every LED
Definition at line 869 of file noise.cpp.
{
  VARIABLE_LENGTH_ARRAY(uint8_t, V, height*width);
  VARIABLE_LENGTH_ARRAY(uint8_t, H, height*width);
  memset(V,0,height*width);
  memset(H,0,height*width);
  fill_raw_2dnoise16into8((uint8_t*)V,width,height,octaves,q44(2,0),171,1,x,xscale,y,yscale,time);
  // fill_raw_2dnoise16into8((uint8_t*)V,width,height,octaves,x,xscale,y,yscale,time);
  // fill_raw_2dnoise8((uint8_t*)V,width,height,hue_octaves,x,xscale,y,yscale,time);
  fill_raw_2dnoise8((uint8_t*)H,width,height,hue_octaves,hue_x,hue_xscale,hue_y,hue_yscale,hue_time);
  int w1 = width-1;
  int h1 = height-1;
  hue_shift >>= 8;
  for(int i = 0; i < height; ++i) {
    int wb = i*width;
    for(int j = 0; j < width; ++j) {
      CRGB led(CHSV(hue_shift + (H[(h1-i)*width + (w1-j)]), 196, V[i*width + j]));
      int pos = j;
      if(serpentine && (i & 0x1)) {
        pos = w1-j;
      }
      if(blend) {
        leds[wb+pos] >>= 1; leds[wb+pos] += (led>>=1);
      } else {
        leds[wb+pos] = led;
      }
    }
  }
}
References blend(), fill_raw_2dnoise16into8(), fill_raw_2dnoise8(), hue_octaves, hue_time, leds, octaves, pos, VARIABLE_LENGTH_ARRAY, x, xscale, y, and yscale.
Referenced by loop().
fill_2dnoise8()
void fill_2dnoise8 (CRGB * leds, int width, int height, bool serpentine, uint8_t octaves, uint16_t x, int xscale, uint16_t y, int yscale, uint16_t time, uint8_t hue_octaves, uint16_t hue_x, int hue_xscale, uint16_t hue_y, uint16_t hue_yscale, uint16_t hue_time, bool blend)
Fill an LED matrix with random colors, using 8-bit noise.
Parameters
leds pointer to LED array
width the width of the LED matrix
height the height of the LED matrix
serpentine whether the matrix is laid out in a serpentine pattern (alternating left/right directions per row)
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
xscale the scale (distance) between x points when filling in value (brightness) noise
y y-axis coordinate on noise map for value (brightness) noise
yscale the scale (distance) between y points when filling in value (brightness) noise
time the time position for the value (brightness) noise field
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_xscale the scale (distance) between x points when filling in color hue noise
hue_y y-axis coordinate on noise map for color hue noise.
hue_yscale the scale (distance) between y points when filling in color hue noise
hue_time the time position for the color hue noise field
blend if true, will blend the newly generated LED values into the array. If false, will overwrite the array values directly.
Definition at line 829 of file noise.cpp.
{
  const size_t array_size = (size_t)height * width;
  if (array_size <= 0) return;
  VARIABLE_LENGTH_ARRAY(uint8_t, V, array_size);
  VARIABLE_LENGTH_ARRAY(uint8_t, H, array_size);
  memset(V,0,height*width);
  memset(H,0,height*width);
  fill_raw_2dnoise8((uint8_t*)V,width,height,octaves,x,xscale,y,yscale,time);
  fill_raw_2dnoise8((uint8_t*)H,width,height,hue_octaves,hue_x,hue_xscale,hue_y,hue_yscale,hue_time);
  int w1 = width-1;
  int h1 = height-1;
  for(int i = 0; i < height; ++i) {
    int wb = i*width;
    for(int j = 0; j < width; ++j) {
      CRGB led(CHSV(H[(h1-i)*width + (w1-j)], 255, V[i*width + j]));
      int pos = j;
      if(serpentine && (i & 0x1)) {
        pos = w1-j;
      }
      if(blend) {
        // Safer blending to avoid potential undefined behavior
        CRGB temp = leds[wb+pos];
        temp.nscale8(128); // Scale by 50%
        led.nscale8(128);
        leds[wb+pos] = temp + led;
      } else {
        leds[wb+pos] = led;
      }
    }
  }
}
References blend(), fill_raw_2dnoise8(), hue_octaves, hue_time, leds, CRGB::nscale8(), octaves, pos, VARIABLE_LENGTH_ARRAY, x, xscale, y, and yscale.
fill_noise16()
void fill_noise16 (CRGB * leds, int num_leds, uint8_t octaves, uint16_t x, int scale, uint8_t hue_octaves, uint16_t hue_x, int hue_scale, uint16_t time, uint8_t hue_shift = 0)
Fill an LED array with random colors, using 16-bit noise.
Parameters
leds pointer to LED array
num_leds the number of LEDs to fill
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
scale the scale (distance) between x points when filling in value (brightness) noise
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_scale the scale (distance) between x points when filling in color hue noise
time the time position for the noise field
hue_shift how much to shift the final hues by for every LED
Definition at line 803 of file noise.cpp.
{
    if (num_leds <= 0) return;
    for (int j = 0; j < num_leds; j += 255) {
        const int LedsRemaining = num_leds - j;
        const int LedsPer = LedsRemaining > 255 ? 255 : LedsRemaining;  // limit to 255 max
        if (LedsPer <= 0) continue;
        VARIABLE_LENGTH_ARRAY(uint8_t, V, LedsPer);
        VARIABLE_LENGTH_ARRAY(uint8_t, H, LedsPer);
        memset(V, 0, LedsPer);
        memset(H, 0, LedsPer);
        fill_raw_noise16into8(V, LedsPer, octaves, x, scale, time);
        fill_raw_noise8(H, LedsPer, hue_octaves, hue_x, hue_scale, time);
        for (int i = 0; i < LedsPer; ++i) {
            leds[i + j] = CHSV(H[i] + hue_shift, 255, V[i]);
        }
    }
}
References fill_raw_noise16into8(), fill_raw_noise8(), hue_octaves, hue_scale, leds, octaves, scale, VARIABLE_LENGTH_ARRAY, and x.
fill_noise8()
void fill_noise8 (CRGB * leds, int num_leds, uint8_t octaves, uint16_t x, int scale, uint8_t hue_octaves, uint16_t hue_x, int hue_scale, uint16_t time)
Fill an LED array with random colors, using 8-bit noise.
Parameters
leds pointer to LED array
num_leds the number of LEDs to fill
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
scale the scale (distance) between x points when filling in value (brightness) noise
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_scale the scale (distance) between x points when filling in color hue noise
time the time position for the noise field
Definition at line 776 of file noise.cpp.
{
    if (num_leds <= 0) return;
    for (int j = 0; j < num_leds; j += 255) {
        const int LedsRemaining = num_leds - j;
        const int LedsPer = LedsRemaining > 255 ? 255 : LedsRemaining;  // limit to 255 max
        if (LedsPer <= 0) continue;
        VARIABLE_LENGTH_ARRAY(uint8_t, V, LedsPer);
        VARIABLE_LENGTH_ARRAY(uint8_t, H, LedsPer);
        memset(V, 0, LedsPer);
        memset(H, 0, LedsPer);
        fill_raw_noise8(V, LedsPer, octaves, x, scale, time);
        fill_raw_noise8(H, LedsPer, hue_octaves, hue_x, hue_scale, time);
        for (int i = 0; i < LedsPer; ++i) {
            leds[i + j] = CHSV(H[i], 255, V[i]);
        }
    }
}
References fill_raw_noise8(), hue_octaves, hue_scale, leds, octaves, scale, VARIABLE_LENGTH_ARRAY, and x.
fill_raw_2dnoise16()
void fill_raw_2dnoise16 (uint16_t * pData, int width, int height, uint8_t octaves, q88 freq88, fract16 amplitude, int skip, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 16-bit buffer with noise, using inoise16()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
freq88 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
Definition at line 701 of file noise.cpp.
{
  if(octaves > 1) {
    fill_raw_2dnoise16(pData, width, height, octaves-1, freq88, amplitude, skip, x *freq88 , scalex *freq88, y * freq88, scaley * freq88, time);
  } else {
    // amplitude is always 255 on the lowest level
    amplitude=65535;
  }
  scalex *= skip;
  scaley *= skip;
  fract16 invamp = 65535-amplitude;
  for(int i = 0; i < height; i+=skip, y+=scaley) {
    uint16_t *pRow = pData + (i*width);
    for(int j = 0,xx=x; j < width; j+=skip, xx+=scalex) {
      uint16_t noise_base = inoise16(xx,y,time);
      noise_base = (0x8000 & noise_base) ? noise_base - (32767) : 32767 - noise_base;
      noise_base = scale16(noise_base<<1, amplitude);
      if(skip==1) {
        pRow[j] = scale16(pRow[j],invamp) + noise_base;
      } else {
        for(int ii = i; ii<(i+skip) && ii<height; ++ii) {
          uint16_t *pRow = pData + (ii*width);
          for(int jj=j; jj<(j+skip) && jj<width; ++jj) {
            pRow[jj] = scale16(pRow[jj],invamp) + noise_base;
          }
        }
      }
    }
  }
}
References fill_raw_2dnoise16(), inoise16(), octaves, scale16(), x, and y.
Referenced by fill_raw_2dnoise16().
fill_raw_2dnoise16into8() [1/2]
void fill_raw_2dnoise16into8 (uint8_t * pData, int width, int height, uint8_t octaves, q44 freq44, fract8 amplitude, int skip, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 8-bit buffer with noise, using inoise16()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
Definition at line 739 of file noise.cpp.
{
  if(octaves > 1) {
    fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
  } else {
    // amplitude is always 255 on the lowest level
    amplitude=255;
  }
  scalex *= skip;
  scaley *= skip;
  uint32_t xx;
  fract8 invamp = 255-amplitude;
  for(int i = 0; i < height; i+=skip, y+=scaley) {
    uint8_t *pRow = pData + (i*width);
    xx = x;
    for(int j = 0; j < width; j+=skip, xx+=scalex) {
      uint16_t noise_base = inoise16(xx,y,time);
      noise_base = (0x8000 & noise_base) ? noise_base - (32767) : 32767 - noise_base;
      noise_base = scale8(noise_base>>7,amplitude);
      if(skip==1) {
        pRow[j] = qadd8(scale8(pRow[j],invamp),noise_base);
      } else {
        for(int ii = i; ii<(i+skip) && ii<height; ++ii) {
          uint8_t *pRow = pData + (ii*width);
          for(int jj=j; jj<(j+skip) && jj<width; ++jj) {
            pRow[jj] = scale8(pRow[jj],invamp) + noise_base;
          }
        }
      }
    }
  }
}
References fill_raw_2dnoise16into8(), inoise16(), octaves, qadd8(), scale8(), x, and y.
Referenced by fill_2dnoise16(), fill_raw_2dnoise16into8(), and fill_raw_2dnoise16into8().
fill_raw_2dnoise16into8() [2/2]
void fill_raw_2dnoise16into8 (uint8_t * pData, int width, int height, uint8_t octaves, uint32_t x, int32_t scalex, uint32_t y, int32_t scaley, uint32_t time)
Fill a 2D 8-bit buffer with noise, using inoise16()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
fill_raw_2dnoise8() [1/3]
void fill_raw_2dnoise8 (uint8_t * pData, int width, int height, uint8_t octaves, q44 freq44, fract8 amplitude, int skip, uint16_t x, int16_t scalex, uint16_t y, int16_t scaley, uint16_t time)
Fill a 2D 8-bit buffer with noise, using inoise8()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
Todo
Why isn't this declared in the header (noise.h)?
Definition at line 663 of file noise.cpp.
{
  if(octaves > 1) {
    fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
  } else {
    // amplitude is always 255 on the lowest level
    amplitude=255;
  }
  scalex *= skip;
  scaley *= skip;
  fract8 invamp = 255-amplitude;
  uint16_t xx = x;
  for(int i = 0; i < height; ++i, y+=scaley) {
    uint8_t *pRow = pData + (i*width);
    xx = x;
    for(int j = 0; j < width; ++j, xx+=scalex) {
      uint8_t noise_base = inoise8(xx,y,time);
      noise_base = (0x80 & noise_base) ? (noise_base - 127) : (127 - noise_base);
      noise_base = scale8(noise_base<<1,amplitude);
      if(skip == 1) {
        pRow[j] = scale8(pRow[j],invamp) + noise_base;
      } else {
        for(int ii = i; ii<(i+skip) && ii<height; ++ii) {
          uint8_t *pRow = pData + (ii*width);
          for(int jj=j; jj<(j+skip) && jj<width; ++jj) {
            pRow[jj] = scale8(pRow[jj],invamp) + noise_base;
          }
        }
      }
    }
  }
}
References fill_raw_2dnoise8(), inoise8(), octaves, scale8(), x, and y.
Referenced by fill_2dnoise16(), fill_2dnoise8(), fill_raw_2dnoise8(), and fill_raw_2dnoise8().
fill_raw_2dnoise8() [2/3]
void fill_raw_2dnoise8 (uint8_t * pData, int width, int height, uint8_t octaves, uint16_t x, int scalex, uint16_t y, int scaley, uint16_t time)
Definition at line 697 of file noise.cpp.
{
  fill_raw_2dnoise8(pData, width, height, octaves, q44(2,0), 128, 1, x, scalex, y, scaley, time);
}
References fill_raw_2dnoise8(), octaves, x, and y.
fill_raw_2dnoise8() [3/3]
void fill_raw_2dnoise8 (uint8_t * pData, int width, int height, uint8_t octaves, uint16_t x, int16_t scalex, uint16_t y, int16_t scaley, uint16_t time)
Fill a 2D 8-bit buffer with noise, using inoise8()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
fill_raw_noise16into8()
void fill_raw_noise16into8 (uint8_t * pData, uint8_t num_points, uint8_t octaves, uint32_t x, int scalex, uint32_t time)
Fill a 1D 8-bit buffer with noise, using inoise16()
Parameters
pData the array of data to fill with noise values
num_points the number of points of noise to compute
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
time the time position for the noise field
Definition at line 633 of file noise.cpp.
{
  uint32_t _xx = x;
  uint32_t scx = scale;
  for(int o = 0; o < octaves; ++o) {
    for(int i = 0,xx=_xx; i < num_points; ++i, xx+=scx) {
      uint32_t accum = (inoise16(xx,time))>>o;
      accum += (pData[i]<<8);
      if(accum > 65535) { accum = 65535; }
      pData[i] = accum>>8;
    }
    _xx <<= 1;
    scx <<= 1;
  }
}
References inoise16(), octaves, scale, and x.
Referenced by fill_noise16().
fill_raw_noise8()
void fill_raw_noise8 (uint8_t * pData, uint8_t num_points, uint8_t octaves, uint16_t x, int scalex, uint16_t time)
Fill a 1D 8-bit buffer with noise, using inoise8()
Parameters
pData the array of data to fill with noise values
num_points the number of points of noise to compute
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
time the time position for the noise field
Definition at line 620 of file noise.cpp.
{
  uint32_t _xx = x;
  uint32_t scx = scale;
  for(int o = 0; o < octaves; ++o) {
    for(int i = 0,xx=_xx; i < num_points; ++i, xx+=scx) {
          pData[i] = qadd8(pData[i],inoise8(xx,time)>>o);
    }
    _xx <<= 1;
    scx <<= 1;
  }
}
References inoise8(), octaves, qadd8(), scale, and x.
Referenced by fill_noise16(), and fill_noise8().