FastLED: fl::Frame Class Reference
fl::Frame Class Reference
Detailed Description
Definition at line 18 of file frame.h.
#include <frame.h>
Public Member Functions
Frame (int pixels_per_frame)
~Frame () override
void copy (const Frame &other)
void draw (CRGB *leds) const
void interpolate (const Frame &frame1, const Frame &frame2, uint8_t amountOfFrame2)
CRGB * rgb ()
const CRGB * rgb () const
size_t size () const
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Static Public Member Functions
static void interpolate (const Frame &frame1, const Frame &frame2, uint8_t amountofFrame2, CRGB *pixels)
Private Attributes
const size_t mPixelsCount
fl::scoped_array< CRGB > mRgb
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
Frame()
fl::Frame::Frame (int pixels_per_frame) explicit
Definition at line 15 of file frame.cpp.
    : mPixelsCount(pixels_count), mRgb() {
    mRgb.reset(reinterpret_cast<CRGB *>(LargeBlockAllocate(pixels_count * sizeof(CRGB))));
    memset(mRgb.get(), 0, pixels_count * sizeof(CRGB));
}
References fl::scoped_array< T, Deleter >::get(), fl::LargeBlockAllocate(), mRgb, and fl::scoped_array< T, Deleter >::reset().
~Frame()
fl::Frame::~Frame () override
Definition at line 21 of file frame.cpp.
              {
    if (mRgb) {
        LargeBlockDeallocate(mRgb.release());
    }
}
References fl::LargeBlockDeallocate(), mRgb, and fl::scoped_array< T, Deleter >::release().
Member Function Documentation
copy()
void fl::Frame::copy (const Frame & other) inline
Definition at line 38 of file frame.h.
{
    memcpy(mRgb.get(), other.mRgb.get(), other.mPixelsCount * sizeof(CRGB));
}
References fl::scoped_array< T, Deleter >::get(), mPixelsCount, and mRgb.
draw()
void fl::Frame::draw (CRGB * leds) const
Definition at line 27 of file frame.cpp.
{
    if (mRgb) {
        memcpy(leds, mRgb.get(), mPixelsCount * sizeof(CRGB));
    }
}
References fl::scoped_array< T, Deleter >::get(), leds, mPixelsCount, and mRgb.
Referenced by fl::FrameInterpolator::draw().
interpolate() [1/2]
void fl::Frame::interpolate (const Frame & frame1, const Frame & frame2, uint8_t amountOfFrame2)
Definition at line 53 of file frame.cpp.
{
    if (frame1.size() != frame2.size() || frame1.size() != mPixelsCount) {
        FASTLED_DBG("Frames must have the same size");
        return;  // Frames must have the same size
    }
    interpolate(frame1, frame2, amountOfFrame2, mRgb.get());
}
References FASTLED_DBG, fl::scoped_array< T, Deleter >::get(), interpolate(), mPixelsCount, mRgb, and size().
Referenced by fl::FrameInterpolator::draw(), and interpolate().
interpolate() [2/2]
void fl::Frame::interpolate (const Frame & frame1, const Frame & frame2, uint8_t amountofFrame2, CRGB * pixels) static
Definition at line 34 of file frame.cpp.
{
    if (frame1.size() != frame2.size()) {
        return;  // Frames must have the same size
    }
    const CRGB* rgbFirst = frame1.rgb();
    const CRGB* rgbSecond = frame2.rgb();
    if (!rgbFirst || !rgbSecond) {
        // Error, why are we getting null pointers?
        return;
    }
    for (size_t i = 0; i < frame2.size(); ++i) {
        pixels[i] = CRGB::blend(rgbFirst[i], rgbSecond[i], amountofFrame2);
    }
    // We will eventually do something with alpha.
}
References CRGB::blend(), rgb(), and size().
rgb() [1/2]
CRGB * fl::Frame::rgb () inline
Definition at line 25 of file frame.h.
{ return mRgb.get(); }
References fl::scoped_array< T, Deleter >::get(), and mRgb.
Referenced by fl::FrameInterpolator::draw(), interpolate(), fl::PixelStream::readFrame(), and fl::PixelStream::readFrameAt().
rgb() [2/2]
const CRGB * fl::Frame::rgb () const inline
Definition at line 26 of file frame.h.
{ return mRgb.get(); }
References fl::scoped_array< T, Deleter >::get(), and mRgb.
size()
size_t fl::Frame::size () const inline
Definition at line 27 of file frame.h.
{ return mPixelsCount; }
References mPixelsCount.
Referenced by interpolate(), and interpolate().
Member Data Documentation
mPixelsCount
const size_t fl::Frame::mPixelsCount private
Definition at line 33 of file frame.h.
Referenced by copy(), draw(), interpolate(), and size().
mRgb
fl::scoped_array<CRGB> fl::Frame::mRgb private
Definition at line 34 of file frame.h.
Referenced by Frame(), ~Frame(), copy(), draw(), interpolate(), rgb(), and rgb().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/frame.h
/home/runner/work/FastLED/FastLED/src/fx/frame.cpp