FastLED: fl::ByteStreamMemory Class Reference
fl::ByteStreamMemory Class Reference
Detailed Description
Definition at line 16 of file bytestreammemory.h.
#include <bytestreammemory.h>
Public Member Functions
ByteStreamMemory (uint32_t size_buffer)
~ByteStreamMemory () override
bool available (size_t n) const override
void clear ()
const char * path () const override
size_t read (uint8_t *dst, size_t bytesToRead) override
size_t write (const uint8_t *src, size_t n)
size_t writeCRGB (const CRGB *src, size_t n)
Public Member Functions inherited from fl::ByteStream
virtual ~ByteStream ()
virtual void close ()
size_t readCRGB (CRGB *dst, size_t n)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Attributes
CircularBuffer< uint8_t > mReadBuffer
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
ByteStreamMemory()
fl::ByteStreamMemory::ByteStreamMemory (uint32_t size_buffer)
Definition at line 12 of file bytestreammemory.cpp.
    : mReadBuffer(size_buffer) {}
~ByteStreamMemory()
fl::ByteStreamMemory::~ByteStreamMemory () override default
Member Function Documentation
available()
bool fl::ByteStreamMemory::available (size_t n) const override virtual
Implements fl::ByteStream.
Definition at line 17 of file bytestreammemory.cpp.
{
    return mReadBuffer.size() >= n;
}
References mReadBuffer, and fl::CircularBuffer< T >::size().
Referenced by read().
clear()
void fl::ByteStreamMemory::clear () inline
Definition at line 22 of file bytestreammemory.h.
                 {
        mReadBuffer.clear();
    }
References fl::CircularBuffer< T >::clear(), and mReadBuffer.
path()
const char * fl::ByteStreamMemory::path () const inline override virtual
Implements fl::ByteStream.
Definition at line 25 of file bytestreammemory.h.
{ return "ByteStreamMemory"; }
read()
size_t fl::ByteStreamMemory::read (uint8_t * dst, size_t bytesToRead) override virtual
Implements fl::ByteStream.
Definition at line 21 of file bytestreammemory.cpp.
{
    if (!available(bytesToRead) || dst == nullptr) {
        FASTLED_WARN("ByteStreamMemory::read: !available(bytesToRead): " << bytesToRead << " mReadBuffer.size(): " << mReadBuffer.size());
        return 0;
    }
    size_t actualBytesToRead = MIN(bytesToRead, mReadBuffer.size());
    size_t bytesRead = 0;
    while (bytesRead < actualBytesToRead) {
        uint8_t& b = dst[bytesRead];
        mReadBuffer.pop_front(&b);
        bytesRead++;
    }
    if (bytesRead == 0) {
        FASTLED_WARN("ByteStreamMemory::read: bytesRead == 0");
    }
    return bytesRead;
}
References available(), FASTLED_WARN, MIN, mReadBuffer, fl::CircularBuffer< T >::pop_front(), and fl::CircularBuffer< T >::size().
write()
size_t fl::ByteStreamMemory::write (const uint8_t * src, size_t n)
Definition at line 43 of file bytestreammemory.cpp.
{
    if (src == nullptr || mReadBuffer.capacity() == 0) {
        FASTLED_WARN_IF(src == nullptr, "ByteStreamMemory::write: src == nullptr");
        FASTLED_WARN_IF(mReadBuffer.capacity() == 0, "ByteStreamMemory::write: mReadBuffer.capacity() == 0");
        return 0;
    }
    size_t written = 0;
    for (size_t i = 0; i < n; ++i) {
        if (mReadBuffer.full()) {
            FASTLED_WARN("ByteStreamMemory::write: mReadBuffer.full(): " << mReadBuffer.size());
            break;
        }
        mReadBuffer.push_back(src[i]);
        ++written;
    }
    return written;
}
References fl::CircularBuffer< T >::capacity(), FASTLED_WARN, FASTLED_WARN_IF, fl::CircularBuffer< T >::full(), mReadBuffer, fl::CircularBuffer< T >::push_back(), and fl::CircularBuffer< T >::size().
Referenced by writeCRGB().
writeCRGB()
size_t fl::ByteStreamMemory::writeCRGB (const CRGB * src, size_t n)
Definition at line 62 of file bytestreammemory.cpp.
{
    size_t bytes_written = write(reinterpret_cast<const uint8_t*>(src), n * 3);
    size_t pixels_written = bytes_written / 3;
    return pixels_written;
}
References write().
Member Data Documentation
mReadBuffer
CircularBuffer<uint8_t> fl::ByteStreamMemory::mReadBuffer private
Definition at line 30 of file bytestreammemory.h.
Referenced by available(), clear(), read(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/bytestreammemory.h
/home/runner/work/FastLED/FastLED/src/fl/bytestreammemory.cpp