FastLED: /home/runner/work/FastLED/FastLED/examples/TwinkleFox/TwinkleFox.ino File Reference
TwinkleFox.ino File Reference
Detailed Description
Twinkling "holiday" lights that fade in and out.
Definition in file TwinkleFox.ino.
#include "FastLED.h"
Macros
#define AUTO_SELECT_BACKGROUND_COLOR 0
#define C9_Blue 0x070758
#define C9_Green 0x046002
#define C9_Orange 0x902C02
#define C9_Red 0xB80400
#define C9_White 0x606820
#define COLOR_ORDER GRB
#define COOL_LIKE_INCANDESCENT 1
#define DATA_PIN 3
#define HALFFAIRY ((CRGB::FairyLight & 0xFEFEFE) / 2)
#define Holly_Green 0x00580c
#define Holly_Red 0xB00402
#define Ice_Blue1 0x0C1040
#define Ice_Blue2 0x182080
#define Ice_Blue3 0x5080C0
#define LED_TYPE WS2811
#define MAX_MA 4000
#define NUM_LEDS 100
#define QUARTERFAIRY ((CRGB::FairyLight & 0xFCFCFC) / 4)
#define SECONDS_PER_PALETTE 30
#define TWINKLE_DENSITY 5
#define TWINKLE_SPEED 4
#define VOLTS 12
Functions
uint8_t attackDecayWave8 (uint8_t i)
void chooseNextColorPalette (CRGBPalette16 &pal)
CRGB computeOneTwinkle (uint32_t ms, uint8_t salt)
void coolLikeIncandescent (CRGB &c, uint8_t phase)
void drawTwinkles (CRGBSet &L)
void loop ()
void setup ()
Variables
const TProgmemRGBPalette16 * ActivePaletteList []
const TProgmemRGBPalette16 BlueWhite_p
const TProgmemRGBPalette16 FairyLight_p
CRGB gBackgroundColor = CRGB::Black
CRGBPalette16 gCurrentPalette
CRGBPalette16 gTargetPalette
const TProgmemRGBPalette16 Holly_p
const TProgmemRGBPalette16 Ice_p
CRGBArray< NUM_LEDS > leds
const TProgmemRGBPalette16 RedGreenWhite_p
const TProgmemRGBPalette16 RedWhite_p
const TProgmemRGBPalette16 RetroC9_p
const TProgmemRGBPalette16 Snow_p
Macro Definition Documentation
AUTO_SELECT_BACKGROUND_COLOR
#define AUTO_SELECT_BACKGROUND_COLOR 0
Definition at line 105 of file TwinkleFox.ino.
C9_Blue
#define C9_Blue 0x070758
Examples
TwinkleFox.ino.
Definition at line 336 of file TwinkleFox.ino.
C9_Green
#define C9_Green 0x046002
Examples
TwinkleFox.ino.
Definition at line 335 of file TwinkleFox.ino.
C9_Orange
#define C9_Orange 0x902C02
Examples
TwinkleFox.ino.
Definition at line 334 of file TwinkleFox.ino.
C9_Red
#define C9_Red 0xB80400
Examples
TwinkleFox.ino.
Definition at line 333 of file TwinkleFox.ino.
C9_White
#define C9_White 0x606820
Examples
TwinkleFox.ino.
Definition at line 337 of file TwinkleFox.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 10 of file TwinkleFox.ino.
COOL_LIKE_INCANDESCENT
#define COOL_LIKE_INCANDESCENT 1
Definition at line 110 of file TwinkleFox.ino.
DATA_PIN
#define DATA_PIN 3
Definition at line 11 of file TwinkleFox.ino.
HALFFAIRY
#define HALFFAIRY ((CRGB::FairyLight & 0xFEFEFE) / 2)
Examples
TwinkleFox.ino.
Definition at line 316 of file TwinkleFox.ino.
Holly_Green
#define Holly_Green 0x00580c
Examples
TwinkleFox.ino.
Definition at line 290 of file TwinkleFox.ino.
Holly_Red
#define Holly_Red 0xB00402
Examples
TwinkleFox.ino.
Definition at line 291 of file TwinkleFox.ino.
Ice_Blue1
#define Ice_Blue1 0x0C1040
Examples
TwinkleFox.ino.
Definition at line 347 of file TwinkleFox.ino.
Ice_Blue2
#define Ice_Blue2 0x182080
Examples
TwinkleFox.ino.
Definition at line 348 of file TwinkleFox.ino.
Ice_Blue3
#define Ice_Blue3 0x5080C0
Examples
TwinkleFox.ino.
Definition at line 349 of file TwinkleFox.ino.
LED_TYPE
#define LED_TYPE WS2811
Definition at line 9 of file TwinkleFox.ino.
MAX_MA
#define MAX_MA 4000
Definition at line 14 of file TwinkleFox.ino.
NUM_LEDS
#define NUM_LEDS 100
Definition at line 8 of file TwinkleFox.ino.
QUARTERFAIRY
#define QUARTERFAIRY ((CRGB::FairyLight & 0xFCFCFC) / 4)
Examples
TwinkleFox.ino.
Definition at line 317 of file TwinkleFox.ino.
SECONDS_PER_PALETTE
#define SECONDS_PER_PALETTE 30
Definition at line 89 of file TwinkleFox.ino.
TWINKLE_DENSITY
#define TWINKLE_DENSITY 5
Definition at line 86 of file TwinkleFox.ino.
TWINKLE_SPEED
#define TWINKLE_SPEED 4
Definition at line 81 of file TwinkleFox.ino.
VOLTS
#define VOLTS 12
Definition at line 13 of file TwinkleFox.ino.
Function Documentation
attackDecayWave8()
uint8_t attackDecayWave8 (uint8_t i)
Examples
TwinkleFox.ino.
Definition at line 259 of file TwinkleFox.ino.
{
  if( i < 86) {
    return i * 3;
  } else {
    i -= 86;
    return 255 - (i + (i/2));
  }
}
Referenced by computeOneTwinkle().
chooseNextColorPalette()
void chooseNextColorPalette (CRGBPalette16 & pal)
Examples
TwinkleFox.ino.
Definition at line 376 of file TwinkleFox.ino.
{
  const uint8_t numberOfPalettes = sizeof(ActivePaletteList) / sizeof(ActivePaletteList[0]);
  static uint8_t whichPalette = -1;
  whichPalette = addmod8( whichPalette, 1, numberOfPalettes);
  pal = *(ActivePaletteList[whichPalette]);
}
References ActivePaletteList, and addmod8().
Referenced by loop(), and setup().
computeOneTwinkle()
CRGB computeOneTwinkle (uint32_t ms, uint8_t salt)
Examples
TwinkleFox.ino.
Definition at line 221 of file TwinkleFox.ino.
{
  uint16_t ticks = ms >> (8-TWINKLE_SPEED);
  uint8_t fastcycle8 = ticks;
  uint16_t slowcycle16 = (ticks >> 8) + salt;
  slowcycle16 += sin8( slowcycle16);
  slowcycle16 =  (slowcycle16 * 2053) + 1384;
  uint8_t slowcycle8 = (slowcycle16 & 0xFF) + (slowcycle16 >> 8);
  uint8_t bright = 0;
  if( ((slowcycle8 & 0x0E)/2) < TWINKLE_DENSITY) {
    bright = attackDecayWave8( fastcycle8);
  }
  uint8_t hue = slowcycle8 - salt;
  CRGB c;
  if( bright > 0) {
    c = ColorFromPalette( gCurrentPalette, hue, bright, NOBLEND);
    if( COOL_LIKE_INCANDESCENT == 1 ) {
      coolLikeIncandescent( c, fastcycle8);
    }
  } else {
    c = CRGB::Black;
  }
  return c;
}
References attackDecayWave8(), CRGB::Black, ColorFromPalette(), COOL_LIKE_INCANDESCENT, coolLikeIncandescent(), gCurrentPalette, NOBLEND, sin8, TWINKLE_DENSITY, and TWINKLE_SPEED.
Referenced by drawTwinkles().
coolLikeIncandescent()
void coolLikeIncandescent (CRGB & c, uint8_t phase)
Examples
TwinkleFox.ino.
Definition at line 272 of file TwinkleFox.ino.
{
  if( phase < 128) return;
  uint8_t cooling = (phase - 128) >> 4;
  c.g = qsub8( c.g, cooling);
  c.b = qsub8( c.b, cooling * 2);
}
References qsub8().
Referenced by computeOneTwinkle().
drawTwinkles()
void drawTwinkles (CRGBSet & L)
Examples
TwinkleFox.ino.
Definition at line 147 of file TwinkleFox.ino.
{
  // "PRNG16" is the pseudorandom number generator
  // It MUST be reset to the same starting value each time
  // this function is called, so that the sequence of 'random'
  // numbers that it generates is (paradoxically) stable.
  uint16_t PRNG16 = 11337;
  uint32_t clock32 = millis();
  // Set up the background color, "bg".
  // if AUTO_SELECT_BACKGROUND_COLOR == 1, and the first two colors of
  // the current palette are identical, then a deeply faded version of
  // that color is used for the background color
  CRGB bg;
  if( (AUTO_SELECT_BACKGROUND_COLOR == 1) &&
      (gCurrentPalette[0] == gCurrentPalette[1] )) {
    bg = gCurrentPalette[0];
    uint8_t bglight = bg.getAverageLight();
    if( bglight > 64) {
      bg.nscale8_video( 16); // very bright, so scale to 1/16th
    } else if( bglight > 16) {
      bg.nscale8_video( 64); // not that bright, so scale to 1/4th
    } else {
      bg.nscale8_video( 86); // dim, scale to 1/3rd.
    }
  } else {
    bg = gBackgroundColor; // just use the explicitly defined background color
  }
  uint8_t backgroundBrightness = bg.getAverageLight();
  for( CRGB& pixel: L) {
    PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384; // next 'random' number
    uint16_t myclockoffset16= PRNG16; // use that number as clock offset
    PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384; // next 'random' number
    // use that number as clock speed adjustment factor (in 8ths, from 8/8ths to 23/8ths)
    uint8_t myspeedmultiplierQ5_3 =  ((((PRNG16 & 0xFF)>>4) + (PRNG16 & 0x0F)) & 0x0F) + 0x08;
    uint32_t myclock30 = (uint32_t)((clock32 * myspeedmultiplierQ5_3) >> 3) + myclockoffset16;
    uint8_t  myunique8 = PRNG16 >> 8; // get 'salt' value for this pixel
    // We now have the adjusted 'clock' for this pixel, now we call
    // the function that computes what color the pixel should be based
    // on the "brightness = f( time )" idea.
    CRGB c = computeOneTwinkle( myclock30, myunique8);
    uint8_t cbright = c.getAverageLight();
    int16_t deltabright = cbright - backgroundBrightness;
    if( deltabright >= 32 || (!bg)) {
      // If the new pixel is significantly brighter than the background color,
      // use the new color.
      pixel = c;
    } else if( deltabright > 0 ) {
      // If the new pixel is just slightly brighter than the background color,
      // mix a blend of the new color and the background color
      pixel = blend( bg, c, deltabright * 8);
    } else {
      // if the new pixel is not at all brighter than the background color,
      // just use the background color.
      pixel = bg;
    }
  }
}
References AUTO_SELECT_BACKGROUND_COLOR, blend(), computeOneTwinkle(), gBackgroundColor, gCurrentPalette, CRGB::getAverageLight(), and CRGB::nscale8_video().
Referenced by loop().
loop()
void loop ()
Definition at line 126 of file TwinkleFox.ino.
{
  EVERY_N_SECONDS( SECONDS_PER_PALETTE ) {
    chooseNextColorPalette( gTargetPalette );
  }
  EVERY_N_MILLISECONDS( 10 ) {
    nblendPaletteTowardPalette( gCurrentPalette, gTargetPalette, 12);
  }
  drawTwinkles( leds);
  FastLED.show();
}
References chooseNextColorPalette(), drawTwinkles(), EVERY_N_MILLISECONDS, EVERY_N_SECONDS, FastLED, gCurrentPalette, gTargetPalette, leds, nblendPaletteTowardPalette(), SECONDS_PER_PALETTE, and CFastLED::show().
setup()
void setup ()
Definition at line 116 of file TwinkleFox.ino.
             {
  delay( 3000 ); //safety startup delay
  FastLED.setMaxPowerInVoltsAndMilliamps( VOLTS, MAX_MA);
  FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS)
    .setCorrection(TypicalLEDStrip);
  chooseNextColorPalette(gTargetPalette);
}
References CFastLED::addLeds(), chooseNextColorPalette(), COLOR_ORDER, DATA_PIN, FastLED, gTargetPalette, LED_TYPE, leds, MAX_MA, NUM_LEDS, CFastLED::setMaxPowerInVoltsAndMilliamps(), TypicalLEDStrip, and VOLTS.
Variable Documentation
ActivePaletteList
const TProgmemRGBPalette16* ActivePaletteList[]
Initial value:
= {
  &RetroC9_p,
  &BlueWhite_p,
  &RainbowColors_p,
  &FairyLight_p,
  &RedGreenWhite_p,
  &PartyColors_p,
  &RedWhite_p,
  &Snow_p,
  &Holly_p,
  &Ice_p
}
Examples
TwinkleFox.ino.
Definition at line 361 of file TwinkleFox.ino.
{
  &RetroC9_p,
  &BlueWhite_p,
  &RainbowColors_p,
  &FairyLight_p,
  &RedGreenWhite_p,
  &PartyColors_p,
  &RedWhite_p,
  &Snow_p,
  &Holly_p,
  &Ice_p
};
Referenced by chooseNextColorPalette().
BlueWhite_p
const TProgmemRGBPalette16 BlueWhite_p
Initial value:
=
{  CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Gray, CRGB::Gray, CRGB::Gray }
Examples
TwinkleFox.ino.
Definition at line 309 of file TwinkleFox.ino.
{  CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
   CRGB::Blue, CRGB::Gray, CRGB::Gray, CRGB::Gray };
FairyLight_p
const TProgmemRGBPalette16 FairyLight_p
Initial value:
=
{  CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight,
   HALFFAIRY,        HALFFAIRY,        CRGB::FairyLight, CRGB::FairyLight,
   QUARTERFAIRY,     QUARTERFAIRY,     CRGB::FairyLight, CRGB::FairyLight,
   CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight }
Examples
TwinkleFox.ino.
Definition at line 318 of file TwinkleFox.ino.
{  CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight,
   HALFFAIRY,        HALFFAIRY,        CRGB::FairyLight, CRGB::FairyLight,
   QUARTERFAIRY,     QUARTERFAIRY,     CRGB::FairyLight, CRGB::FairyLight,
   CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight, CRGB::FairyLight };
gBackgroundColor
CRGB gBackgroundColor = CRGB::Black
Examples
TwinkleFox.ino.
Definition at line 97 of file TwinkleFox.ino.
Referenced by drawTwinkles().
gCurrentPalette
CRGBPalette16 gCurrentPalette
Examples
TwinkleFox.ino.
Definition at line 113 of file TwinkleFox.ino.
Referenced by computeOneTwinkle(), drawTwinkles(), and loop().
gTargetPalette
CRGBPalette16 gTargetPalette
Examples
TwinkleFox.ino.
Definition at line 114 of file TwinkleFox.ino.
Referenced by loop(), and setup().
Holly_p
const TProgmemRGBPalette16 Holly_p
Initial value:
=
{  Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Red
}
Examples
TwinkleFox.ino.
Definition at line 292 of file TwinkleFox.ino.
{  Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Green,
   Holly_Green, Holly_Green, Holly_Green, Holly_Red
};
Ice_p
const TProgmemRGBPalette16 Ice_p
Initial value:
=
{
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue2, Ice_Blue2, Ice_Blue2, Ice_Blue3
}
Examples
TwinkleFox.ino.
Definition at line 350 of file TwinkleFox.ino.
{
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue1, Ice_Blue1, Ice_Blue1, Ice_Blue1,
  Ice_Blue2, Ice_Blue2, Ice_Blue2, Ice_Blue3
};
leds
CRGBArray<NUM_LEDS> leds
Definition at line 76 of file TwinkleFox.ino.
RedGreenWhite_p
const TProgmemRGBPalette16 RedGreenWhite_p
Initial value:
=
{  CRGB::Red, CRGB::Red, CRGB::Red, CRGB::Red,
   CRGB::Red, CRGB::Red, CRGB::Red, CRGB::Red,
   CRGB::Red, CRGB::Red, CRGB::Gray, CRGB::Gray,
   CRGB::Green, CRGB::Green, CRGB::Green, CRGB::Green }
Examples
TwinkleFox.ino.
Definition at line 283 of file TwinkleFox.ino.
{  CRGB::Red, CRGB::Red, CRGB::Red, CRGB::Red,
   CRGB::Red, CRGB::Red, CRGB::Red, CRGB::Red,
   CRGB::Red, CRGB::Red, CRGB::Gray, CRGB::Gray,
   CRGB::Green, CRGB::Green, CRGB::Green, CRGB::Green };
RedWhite_p
const TProgmemRGBPalette16 RedWhite_p
Initial value:
=
{  CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red,
   CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray,
   CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red,
   CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray }
Examples
TwinkleFox.ino.
Definition at line 301 of file TwinkleFox.ino.
{  CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red,
   CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray,
   CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red,
   CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray };
RetroC9_p
const TProgmemRGBPalette16 RetroC9_p
Initial value:
=
{  C9_Red,    C9_Orange, C9_Red,    C9_Orange,
   C9_Orange, C9_Red,    C9_Orange, C9_Red,
   C9_Green,  C9_Green,  C9_Green,  C9_Green,
   C9_Blue,   C9_Blue,   C9_Blue,
   C9_White
}
Examples
TwinkleFox.ino.
Definition at line 338 of file TwinkleFox.ino.
{  C9_Red,    C9_Orange, C9_Red,    C9_Orange,
   C9_Orange, C9_Red,    C9_Orange, C9_Red,
   C9_Green,  C9_Green,  C9_Green,  C9_Green,
   C9_Blue,   C9_Blue,   C9_Blue,
   C9_White
};
Snow_p
const TProgmemRGBPalette16 Snow_p
Initial value:
=
{  0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0xE0F0FF }
Examples
TwinkleFox.ino.
Definition at line 325 of file TwinkleFox.ino.
{  0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0x304048,
   0x304048, 0x304048, 0x304048, 0xE0F0FF };