FastLED: fl::StrStream Class Reference
fl::StrStream Class Reference
Detailed Description
Definition at line 37 of file strstream.h.
#include <strstream.h>
Public Member Functions
StrStream ()=default
StrStream (const Str &str)
const char * c_str () const
StrStream & operator<< (char c)
StrStream & operator<< (const char *str)
StrStream & operator<< (const CRGB &rgb)
StrStream & operator<< (const Str &str)
StrStream & operator<< (int16_t n)
StrStream & operator<< (int32_t n)
template<typename T >
StrStream & operator<< (T n)
StrStream & operator<< (uint16_t n)
StrStream & operator<< (uint32_t n)
StrStream & operator<< (uint8_t n)
StrStream & operator= (char c)
StrStream & operator= (const char *str)
StrStream & operator= (const CRGB &rgb)
StrStream & operator= (const Str &str)
StrStream & operator= (uint16_t n)
StrStream & operator= (uint8_t n)
void setTreatCharAsInt (bool treatCharAsInt)
const Str & str () const
Private Attributes
Str mStr
bool mTreatCharAsInt = true
Constructor & Destructor Documentation
StrStream() [1/2]
fl::StrStream::StrStream () default
StrStream() [2/2]
fl::StrStream::StrStream (const Str & str) inline
Definition at line 40 of file strstream.h.
: mStr(str) {}
Member Function Documentation
c_str()
const char * fl::StrStream::c_str () const inline
Definition at line 47 of file strstream.h.
{ return mStr.c_str(); }
References fl::StrN< SIZE >::c_str(), and mStr.
operator<<() [1/10]
StrStream & fl::StrStream::operator<< (char c) inline
Definition at line 89 of file strstream.h.
{
        if (mTreatCharAsInt) {
            StrStreamHelper<int>::append(mStr, c);
        } else {
            StrStreamHelper<char>::append(mStr, c);
        }
        return *this;
    }
References fl::StrStreamHelper< T >::append(), mStr, and mTreatCharAsInt.
operator<<() [2/10]
StrStream & fl::StrStream::operator<< (const char * str) inline
Definition at line 84 of file strstream.h.
{
        mStr.append(str);
        return *this;
    }
References fl::Str::append(), mStr, and str().
operator<<() [3/10]
StrStream & fl::StrStream::operator<< (const CRGB & rgb) inline
Definition at line 49 of file strstream.h.
{
        mStr.append("CRGB(");
        mStr.append(rgb.r);
        mStr.append(",");
        mStr.append(rgb.g);
        mStr.append(",");
        mStr.append(rgb.b);
        mStr.append(")");
        return *this;
    }
References fl::Str::append(), and mStr.
operator<<() [4/10]
StrStream & fl::StrStream::operator<< (const Str & str) inline
Definition at line 79 of file strstream.h.
{
        mStr.append(str);
        return *this;
    }
References fl::Str::append(), mStr, and str().
operator<<() [5/10]
StrStream & fl::StrStream::operator<< (int16_t n) inline
Definition at line 125 of file strstream.h.
{
        mStr.append(n);
        return *this;
    }
References fl::Str::append(), and mStr.
operator<<() [6/10]
StrStream & fl::StrStream::operator<< (int32_t n) inline
Definition at line 135 of file strstream.h.
{
        mStr.append(n);
        return *this;
    }
References fl::Str::append(), and mStr.
operator<<() [7/10]
template<typename T > StrStream & fl::StrStream::operator<< (T n) inline
Definition at line 106 of file strstream.h.
{
        StrStreamHelper<T>::append(mStr, n);
        return *this;
    }
References fl::StrStreamHelper< T >::append(), and mStr.
operator<<() [8/10]
StrStream & fl::StrStream::operator<< (uint16_t n) inline
Definition at line 120 of file strstream.h.
{
        mStr.append(n);
        return *this;
    }
References fl::Str::append(), and mStr.
operator<<() [9/10]
StrStream & fl::StrStream::operator<< (uint32_t n) inline
Definition at line 130 of file strstream.h.
{
        mStr.append(uint32_t(n));
        return *this;
    }
References fl::Str::append(), and mStr.
operator<<() [10/10]
StrStream & fl::StrStream::operator<< (uint8_t n) inline
Definition at line 111 of file strstream.h.
{
        if (mTreatCharAsInt) {
            mStr.append(uint16_t(n));
        } else {
            mStr.append(n);
        }
        return *this;
    }
References fl::Str::append(), mStr, and mTreatCharAsInt.
operator=() [1/6]
StrStream & fl::StrStream::operator= (char c) inline
Definition at line 72 of file strstream.h.
{
        mStr.clear();
        (*this) << c;
        return *this;
    }
References fl::StrN< SIZE >::clear(), and mStr.
operator=() [2/6]
StrStream & fl::StrStream::operator= (const char * str) inline
Definition at line 146 of file strstream.h.
{
        mStr = str;
        return *this;
    }
References mStr, and str().
operator=() [3/6]
StrStream & fl::StrStream::operator= (const CRGB & rgb) inline
Definition at line 152 of file strstream.h.
{
        mStr.clear();
        (*this) << rgb;
        return *this;
    }
References fl::StrN< SIZE >::clear(), and mStr.
operator=() [4/6]
StrStream & fl::StrStream::operator= (const Str & str) inline
Definition at line 141 of file strstream.h.
{
        mStr = str;
        return *this;
    }
References mStr, and str().
operator=() [5/6]
StrStream & fl::StrStream::operator= (uint16_t n) inline
Definition at line 60 of file strstream.h.
{
        mStr.clear();
        (*this) << n;
        return *this;
    }
References fl::StrN< SIZE >::clear(), and mStr.
operator=() [6/6]
StrStream & fl::StrStream::operator= (uint8_t n) inline
Definition at line 66 of file strstream.h.
{
        mStr.clear();
        (*this) << n;
        return *this;
    }
References fl::StrN< SIZE >::clear(), and mStr.
setTreatCharAsInt()
void fl::StrStream::setTreatCharAsInt (bool treatCharAsInt) inline
Definition at line 42 of file strstream.h.
{
        mTreatCharAsInt = treatCharAsInt;
    }
References mTreatCharAsInt.
str()
const Str & fl::StrStream::str () const inline
Definition at line 46 of file strstream.h.
{ return mStr; }
References mStr.
Referenced by fl::anonymous_namespace{pir.cpp}::getButtonName(), operator<<(), operator<<(), operator=(), and operator=().
Member Data Documentation
mStr
Str fl::StrStream::mStr private
Definition at line 160 of file strstream.h.
Referenced by c_str(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and str().
mTreatCharAsInt
bool fl::StrStream::mTreatCharAsInt = true private
Definition at line 161 of file strstream.h.
Referenced by operator<<(), operator<<(), and setTreatCharAsInt().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/strstream.h