FastLED: /home/runner/work/FastLED/FastLED/examples/Blur2d/Blur2d.ino File Reference
Blur2d.ino File Reference
#include "fl/ui.h"
#include "fl/xymap.h"
#include <FastLED.h>
Macros
#define BLUR_AMOUNT 172
#define BRIGHTNESS 255
#define DATA_PIN 2
#define HEIGHT 22
#define NUM_LEDS (WIDTH * HEIGHT)
#define SERPENTINE true
#define WIDTH 22
Functions
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
uint8_t pos = 0
bool toggle = false
XYMap xymap (WIDTH, HEIGHT, SERPENTINE)
Macro Definition Documentation
BLUR_AMOUNT
#define BLUR_AMOUNT 172
Definition at line 13 of file Blur2d.ino.
Referenced by loop().
BRIGHTNESS
#define BRIGHTNESS 255
Definition at line 15 of file Blur2d.ino.
Referenced by setup().
DATA_PIN
#define DATA_PIN 2
Definition at line 14 of file Blur2d.ino.
Referenced by setup().
HEIGHT
#define HEIGHT 22
Definition at line 10 of file Blur2d.ino.
Referenced by loop().
NUM_LEDS
#define NUM_LEDS (WIDTH * HEIGHT)
Definition at line 12 of file Blur2d.ino.
Referenced by setup().
SERPENTINE
#define SERPENTINE true
Definition at line 16 of file Blur2d.ino.
WIDTH
#define WIDTH 22
Definition at line 9 of file Blur2d.ino.
Referenced by loop().
Function Documentation
loop()
void loop ()
Definition at line 29 of file Blur2d.ino.
            {
    static int x = random(WIDTH);
    static int y = random(HEIGHT);
    static CRGB c = CRGB(0, 0, 0);
    blur2d(leds, WIDTH, HEIGHT, BLUR_AMOUNT, xymap);
    EVERY_N_MILLISECONDS(1000) {
        x = random(WIDTH);
        y = random(HEIGHT);
        uint8_t r = random(255);
        uint8_t g = random(255);
        uint8_t b = random(255);
        c = CRGB(r, g, b);
    }
    leds[xymap(x, y)] = c;
    FastLED.show();
    delay(20);
}
References blur2d(), BLUR_AMOUNT, EVERY_N_MILLISECONDS, FastLED, HEIGHT, leds, CFastLED::show(), WIDTH, x, xymap, and y.
setup()
void setup ()
Definition at line 23 of file Blur2d.ino.
             {
    FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS)
      .setScreenMap(xymap);  // Necessary when using the FastLED web compiler to display properly on a web page.
    FastLED.setBrightness(BRIGHTNESS);
}
References CFastLED::addLeds(), BRIGHTNESS, DATA_PIN, FastLED, GRB, leds, NUM_LEDS, CFastLED::setBrightness(), and xymap.
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 18 of file Blur2d.ino.
Referenced by loop(), and setup().
pos
uint8_t pos = 0
Definition at line 19 of file Blur2d.ino.
toggle
bool toggle = false
Definition at line 20 of file Blur2d.ino.
xymap
XYMap xymap(WIDTH, HEIGHT, SERPENTINE) (WIDTH , HEIGHT , SERPENTINE)
Referenced by blur2d(), loop(), fl::EngineEvents::onCanvasUiSet(), and setup().