FastLED: anonymous_namespace{rgbw.cpp} Namespace Reference
anonymous_namespace{rgbw.cpp} Namespace Reference
Functions
uint8_t divide_by_3 (uint8_t x)
uint8_t min3 (uint8_t a, uint8_t b, uint8_t c)
Function Documentation
divide_by_3()
uint8_t anonymous_namespace{rgbw.cpp}::divide_by_3 (uint8_t x) inline
Definition at line 31 of file rgbw.cpp.
{
    uint16_t y = (uint16_t(x) * 85) >> 8;
    return static_cast<uint8_t>(y);
}
References x, and y.
Referenced by rgb_2_rgbw_white_boosted().
min3()
uint8_t anonymous_namespace{rgbw.cpp}::min3 (uint8_t a, uint8_t b, uint8_t c) inline
Definition at line 15 of file rgbw.cpp.
{
    if (a < b) {
        if (a < c) {
            return a;
        } else {
            return c;
        }
    } else {
        if (b < c) {
            return b;
        } else {
            return c;
        }
    }
}
Referenced by rgb_2_rgbw_exact(), rgb_2_rgbw_max_brightness(), and rgb_2_rgbw_white_boosted().