FastLED: fl::Pixels Class Reference
fl::Pixels Class Reference
Detailed Description
Definition at line 141 of file ___pixeltypes.h.
#include <___pixeltypes.h>
Public Member Functions
Pixels ()
Pixels (const Pixels &rhs)
Pixels (int *sizes, int num_strips)
Pixels (int *sizes, int num_strips, leddirection direction)
Pixels (int num_led_per_strip, int num_strips)
Pixels (int size, Pixel *ledpoi)
Pixels (int size, Pixel *ledpoi, leddirection direction)
void __Pixels (int *sizes, int num_strips, leddirection direction, Pixels *pib)
void __Pixels (int size, Pixel *ledpoi, leddirection direction, Pixels *pib)
void clear ()
void copy (Pixels ori)
void copy (Pixels ori, leddirection dir)
Pixels createSubset (int start, int length)
Pixels createSubset (int start, int length, leddirection direction)
Pixels createSubset (int start, leddirection direction)
int * getLengths ()
int getNumStrip ()
uint8_t * getPixels ()
Pixels getStrip (int num_strip)
Pixels getStrip (int num_strip, leddirection direction)
Pixel & operator[] (int i)
void setMapFunction (int(*fptr)(int i, void *args), void *args, int size)
Private Attributes
leddirection _direction
int _num_strips = 0
size_t _size = 0
int _sizes [16]
void * arguments
Pixel * ledpointer
int(* mapFunction)(int i, void *args)
Pixel offPixel
Constructor & Destructor Documentation
Pixels() [1/7]
fl::Pixels::Pixels () inline
Definition at line 143 of file ___pixeltypes.h.
{}
Referenced by Pixels(), createSubset(), createSubset(), and getStrip().
Pixels() [2/7]
fl::Pixels::Pixels (const Pixels & rhs) inline
Definition at line 144 of file ___pixeltypes.h.
{
        _size = rhs._size;
        _direction = rhs._direction;
        _num_strips = rhs._num_strips;
        for (int i = 0; i < _num_strips; i++) {
            _sizes[i] = rhs._sizes[i];
        }
        ledpointer = rhs.ledpointer;
        mapFunction = rhs.mapFunction;
        // parent=rhs.parent;
    }
References _direction, _num_strips, _size, _sizes, ledpointer, and mapFunction.
Pixels() [3/7]
fl::Pixels::Pixels (int size, Pixel * ledpoi) inline
Definition at line 156 of file ___pixeltypes.h.
{
        Pixels(size, ledpoi, leddirection::FORWARD);
    }
References Pixels(), and fl::FORWARD.
Pixels() [4/7]
fl::Pixels::Pixels (int size, Pixel * ledpoi, leddirection direction) inline
Definition at line 160 of file ___pixeltypes.h.
{
        __Pixels(size, ledpoi, direction, this);
    }
References __Pixels().
Pixels() [5/7]
fl::Pixels::Pixels (int num_led_per_strip, int num_strips) inline
Definition at line 173 of file ___pixeltypes.h.
{
        int sizes[16];
        for (int i = 0; i < num_strips; i++) {
            sizes[i] = num_led_per_strip;
        }
        __Pixels(sizes, num_strips, leddirection::FORWARD, this);
    }
References __Pixels(), and fl::FORWARD.
Pixels() [6/7]
fl::Pixels::Pixels (int * sizes, int num_strips) inline
Definition at line 181 of file ___pixeltypes.h.
{
        __Pixels(sizes, num_strips, leddirection::FORWARD, this);
    }
References __Pixels(), and fl::FORWARD.
Pixels() [7/7]
fl::Pixels::Pixels (int * sizes, int num_strips, leddirection direction) inline
Definition at line 185 of file ___pixeltypes.h.
{
        __Pixels(sizes, num_strips, direction, this);
    }
References __Pixels().
Member Function Documentation
__Pixels() [1/2]
void fl::Pixels::__Pixels (int * sizes, int num_strips, leddirection direction, Pixels * pib) inline
Definition at line 188 of file ___pixeltypes.h.
{
        int size = 0;
        for (int i = 0; i < num_strips; i++) {
            size += sizes[i];
            pib->_sizes[i] = sizes[i];
        }
        pib->_num_strips = num_strips;
        ledpointer = (Pixel *)calloc(size, sizeof(Pixel));
        if (ledpointer == NULL) {
            pib->_size = 0;
        } else {
            pib->_size = size;
        }
        pib->_direction = direction;
    }
References _direction, _num_strips, _size, _sizes, and ledpointer.
__Pixels() [2/2]
void fl::Pixels::__Pixels (int size, Pixel * ledpoi, leddirection direction, Pixels * pib) inline
Definition at line 164 of file ___pixeltypes.h.
{
        pib->_size = size;
        pib->ledpointer = ledpoi;
        pib->_num_strips = 0;
        pib->_direction = direction;
        //  pib->nb_child=0;
    }
References _direction, _num_strips, _size, and ledpointer.
Referenced by Pixels(), Pixels(), Pixels(), and Pixels().
clear()
void fl::Pixels::clear () inline
Definition at line 276 of file ___pixeltypes.h.
                 {
        // memset(ledpointer,0,_size*sizeof(Pixel));
    }
copy() [1/2]
void fl::Pixels::copy (Pixels ori) inline
Definition at line 238 of file ___pixeltypes.h.
{ copy(ori, leddirection::FORWARD); }
References copy(), and fl::FORWARD.
Referenced by copy().
copy() [2/2]
void fl::Pixels::copy (Pixels ori, leddirection dir) inline
Definition at line 240 of file ___pixeltypes.h.
{
        leddirection ledd = _direction;
        if (_direction == leddirection::MAP)
            ledd = leddirection::FORWARD;
        for (int i = 0; i < ori._size; i++) {
            if (ledd == dir) {
                (*this)[i] = ori[i];
            } else {
                (*this)[i] = ori[ori._size - i % (ori._size) - 1];
            }
        }
    }
References _direction, _size, fl::FORWARD, and fl::MAP.
createSubset() [1/3]
Pixels fl::Pixels::createSubset (int start, int length) inline
Definition at line 280 of file ___pixeltypes.h.
{
        return createSubset(start, length, leddirection::FORWARD);
    }
References createSubset(), and fl::FORWARD.
Referenced by createSubset().
createSubset() [2/3]
Pixels fl::Pixels::createSubset (int start, int length, leddirection direction) inline
Definition at line 290 of file ___pixeltypes.h.
{
        if (start < 0)
            start = 0;
        if (length <= 0)
            length = 1;
        return Pixels(length, ledpointer + start, direction);
    }
References Pixels(), and ledpointer.
createSubset() [3/3]
Pixels fl::Pixels::createSubset (int start, leddirection direction) inline
Definition at line 284 of file ___pixeltypes.h.
{
        if (start < 0)
            start = 0;
        return Pixels(_size, ledpointer + start, direction);
    }
References Pixels(), _size, and ledpointer.
getLengths()
int * fl::Pixels::getLengths () inline
Definition at line 272 of file ___pixeltypes.h.
{ return _sizes; }
References _sizes.
getNumStrip()
int fl::Pixels::getNumStrip () inline
Definition at line 274 of file ___pixeltypes.h.
{ return _num_strips; }
References _num_strips.
getPixels()
uint8_t * fl::Pixels::getPixels () inline
Definition at line 275 of file ___pixeltypes.h.
{ return (uint8_t *)ledpointer; }
References ledpointer.
getStrip() [1/2]
Pixels fl::Pixels::getStrip (int num_strip) inline
Definition at line 268 of file ___pixeltypes.h.
{
        return getStrip(num_strip, leddirection::FORWARD);
    }
References fl::FORWARD, and getStrip().
getStrip() [2/2]
Pixels fl::Pixels::getStrip (int num_strip, leddirection direction) inline
Definition at line 253 of file ___pixeltypes.h.
{
        if (_num_strips == 0 or _num_strips < num_strip) {
            int d[0];
            return Pixels(d, 1, direction);
        } else {
            uint32_t off = 0;
            for (int i = 0; i < num_strip % _num_strips; i++) {
                off += _sizes[i];
            }
            return Pixels(_sizes[num_strip], ledpointer + off, direction);
        }
    }
References Pixels(), _num_strips, _sizes, and ledpointer.
Referenced by getStrip().
operator[]()
Pixel & fl::Pixels::operator[] (int i) inline
Definition at line 206 of file ___pixeltypes.h.
{
        switch (_direction) {
        case (leddirection::FORWARD):
            return *(ledpointer + i % _size);
            break;
        case (leddirection::BACKWARD):
            return *(ledpointer + (_size - i % (_size)-1));
            break;
        case (leddirection::MAP):
            if (mapFunction) {
                int offset = mapFunction(i, arguments);
                // printf("%d %d\n",i,offset);
                if (offset == _OUT_OF_BOUND) {
                    return offPixel;
                } else
                    return *(ledpointer + (mapFunction(i, arguments) % _size));
            }
            else
                return *(ledpointer);
            break;
        default:
            return *(ledpointer);
            break;
        }
    }
References _direction, _OUT_OF_BOUND, _size, arguments, fl::BACKWARD, fl::FORWARD, ledpointer, fl::MAP, mapFunction, and offPixel.
setMapFunction()
void fl::Pixels::setMapFunction (int(* fptr)(int i, void *args), void * args, int size) inline
Definition at line 309 of file ___pixeltypes.h.
{
        mapFunction = fptr;
        if (arguments == NULL)
            arguments = (void *)malloc(sizeof(size));
        memcpy(arguments, args, size);
    }
References arguments, and mapFunction.
Member Data Documentation
_direction
leddirection fl::Pixels::_direction private
Definition at line 322 of file ___pixeltypes.h.
Referenced by Pixels(), __Pixels(), __Pixels(), copy(), and operator[]().
_num_strips
int fl::Pixels::_num_strips = 0 private
Definition at line 321 of file ___pixeltypes.h.
Referenced by Pixels(), __Pixels(), __Pixels(), getNumStrip(), and getStrip().
_size
size_t fl::Pixels::_size = 0 private
Definition at line 319 of file ___pixeltypes.h.
Referenced by Pixels(), __Pixels(), __Pixels(), copy(), createSubset(), and operator[]().
_sizes
int fl::Pixels::_sizes[16] private
Definition at line 320 of file ___pixeltypes.h.
Referenced by Pixels(), __Pixels(), getLengths(), and getStrip().
arguments
void* fl::Pixels::arguments private
Definition at line 325 of file ___pixeltypes.h.
Referenced by operator[](), and setMapFunction().
ledpointer
Pixel* fl::Pixels::ledpointer private
Definition at line 318 of file ___pixeltypes.h.
Referenced by Pixels(), __Pixels(), __Pixels(), createSubset(), createSubset(), getPixels(), getStrip(), and operator[]().
mapFunction
int(* fl::Pixels::mapFunction) (int i, void *args) private
Definition at line 327 of file ___pixeltypes.h.
Referenced by Pixels(), operator[](), and setMapFunction().
offPixel
Pixel fl::Pixels::offPixel private
Definition at line 331 of file ___pixeltypes.h.
Referenced by operator[]().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/third_party/yves/I2SClockLessLedDriveresp32s3/src/___pixeltypes.h