FastLED: fl::UISlider Class Reference
fl::UISlider Class Reference
Detailed Description
Examples
FxEngine.ino.
Definition at line 42 of file ui.h.
#include <ui.h>
Public Member Functions
UISlider (const char *name, float value=128.0f, float min=1, float max=255, float step=-1.f)
~UISlider ()
template<typename T >
T as () const
operator float () const
operator int () const
operator uint16_t () const
operator uint8_t () const
UISlider & operator= (float value)
UISlider & operator= (int value)
void setValue (float value)
float value () const
Private Attributes
float mMax
float mMin
float mValue
Constructor & Destructor Documentation
UISlider()
fl::UISlider::UISlider (const char * name, float value = 128.0f, float min = 1, float max = 255, float step = -1.f) inline
Definition at line 45 of file ui.h.
      : mValue(value), mMin(MIN(min, max)), mMax(MAX(min, max)) {
        FASTLED_UNUSED(name);
        FASTLED_UNUSED(step);
        if (value < min) { mValue = min; }
        if (value > max) { mValue = max; }
    }
References FASTLED_UNUSED, mValue, and value().
~UISlider()
fl::UISlider::~UISlider () inline
Definition at line 52 of file ui.h.
{}
Member Function Documentation
as()
template<typename T > T fl::UISlider::as () const inline
Definition at line 59 of file ui.h.
{ return static_cast<T>(mValue); }
References mValue.
Referenced by draw(), and loop().
operator float()
fl::UISlider::operator float () const inline
Definition at line 55 of file ui.h.
{ return mValue; }
References mValue.
operator int()
fl::UISlider::operator int () const inline
Definition at line 58 of file ui.h.
{ return static_cast<int>(mValue); }
References mValue.
operator uint16_t()
fl::UISlider::operator uint16_t () const inline
Definition at line 57 of file ui.h.
{ return static_cast<uint16_t>(mValue); }
References mValue.
operator uint8_t()
fl::UISlider::operator uint8_t () const inline
Definition at line 56 of file ui.h.
{ return static_cast<uint8_t>(mValue); }
References mValue.
operator=() [1/2]
UISlider & fl::UISlider::operator= (float value) inline
Definition at line 61 of file ui.h.
{ setValue(value); return *this; }
References setValue(), and value().
operator=() [2/2]
UISlider & fl::UISlider::operator= (int value) inline
Definition at line 62 of file ui.h.
{ setValue(static_cast<float>(value)); return *this; }
References setValue(), and value().
setValue()
void fl::UISlider::setValue (float value) inline
Definition at line 54 of file ui.h.
{ mValue = MAX(mMin, MIN(mMax, value)); }
References MAX, MIN, mMax, mMin, mValue, and value().
Referenced by operator=(), and operator=().
value()
float fl::UISlider::value () const inline
Definition at line 53 of file ui.h.
{ return mValue; }
References mValue.
Referenced by UISlider(), loop(), operator=(), operator=(), and setValue().
Member Data Documentation
mMax
float fl::UISlider::mMax private
Definition at line 66 of file ui.h.
Referenced by setValue().
mMin
float fl::UISlider::mMin private
Definition at line 65 of file ui.h.
Referenced by setValue().
mValue
float fl::UISlider::mValue private
Definition at line 64 of file ui.h.
Referenced by UISlider(), as(), operator float(), operator int(), operator uint16_t(), operator uint8_t(), setValue(), and value().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ui.h