FastLED: Gamma Adjustment Functions
Gamma Adjustment Functions
Detailed Description
Functions for applying gamma adjustments to LED data.
Gamma correction tries to compensate for the non-linear manner in which humans perceive light and color. Gamma correction is applied using the following expression:
output = pow(input / 255.0, gamma) * 255.0;
Larger gamma values result in darker images that have more contrast. Lower gamma values result in lighter images with less contrast.
These functions apply either:
a single gamma adjustment to a single scalar value
a single gamma adjustment to each channel of a CRGB color, or
different gamma adjustments for each channel of a CRGB color
Note that the gamma is specified as a traditional floating point value, e.g., "2.5", and as such these functions should not be called in your innermost pixel loops, or in animations that are extremely low on program storage space. Nevertheless, if you need these functions, here they are.
Furthermore, bear in mind that CRGB LEDs have only eight bits per channel of color resolution, and that very small, subtle shadings may not be visible.
See also
Dimming and Brightening Functions
https://en.wikipedia.org/wiki/Gamma_correction
Functions
CRGB applyGamma_video (const CRGB &orig, float gamma)
Applies a gamma adjustment to a color.
CRGB applyGamma_video (const CRGB &orig, float gammaR, float gammaG, float gammaB)
Applies a gamma adjustment to a color.
uint8_t applyGamma_video (uint8_t brightness, float gamma)
Applies a gamma adjustment to a color channel.
CRGB & napplyGamma_video (CRGB &rgb, float gamma)
Destructively applies a gamma adjustment to a color.
CRGB & napplyGamma_video (CRGB &rgb, float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to a color.
void napplyGamma_video (CRGB *rgbarray, uint16_t count, float gamma)
Destructively applies a gamma adjustment to a color array.
void napplyGamma_video (CRGB *rgbarray, uint16_t count, float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to a color array.
Function Documentation
applyGamma_video() [1/3]
CRGB applyGamma_video (const CRGB & orig, float gamma)
Applies a gamma adjustment to a color.
Parameters
orig the color to apply an adjustment to
gamma the gamma value to apply
Returns
copy of the CRGB object with gamma adjustment applied
Definition at line 1408 of file colorutils.cpp.
{
    CRGB adj;
    adj.r = applyGamma_video( orig.r, gamma);
    adj.g = applyGamma_video( orig.g, gamma);
    adj.b = applyGamma_video( orig.b, gamma);
    return adj;
}
References applyGamma_video().
applyGamma_video() [2/3]
CRGB applyGamma_video (const CRGB & orig, float gammaR, float gammaG, float gammaB)
Applies a gamma adjustment to a color.
Parameters
orig the color to apply an adjustment to
gammaR the gamma value to apply to the CRGB::red channel
gammaG the gamma value to apply to the CRGB::green channel
gammaB the gamma value to apply to the CRGB::blue channel
Returns
copy of the CRGB object with gamma adjustment applied
Definition at line 1417 of file colorutils.cpp.
{
    CRGB adj;
    adj.r = applyGamma_video( orig.r, gammaR);
    adj.g = applyGamma_video( orig.g, gammaG);
    adj.b = applyGamma_video( orig.b, gammaB);
    return adj;
}
References applyGamma_video().
applyGamma_video() [3/3]
uint8_t applyGamma_video (uint8_t brightness, float gamma)
Applies a gamma adjustment to a color channel.
Parameters
brightness the value of the color data
gamma the gamma value to apply
Returns
the color data, adjusted for gamma
Definition at line 1395 of file colorutils.cpp.
{
    float orig;
    float adj;
    orig = (float)(brightness) / (255.0);
    adj =  pow( orig, gamma)   * (255.0);
    uint8_t result = (uint8_t)(adj);
    if( (brightness > 0) && (result == 0)) {
        result = 1; // never gamma-adjust a positive number down to zero
    }
    return result;
}
References brightness.
Referenced by applyGamma_video(), applyGamma_video(), napplyGamma_video(), napplyGamma_video(), napplyGamma_video(), and napplyGamma_video().
napplyGamma_video() [1/4]
CRGB & napplyGamma_video (CRGB & rgb, float gamma)
Destructively applies a gamma adjustment to a color.
Parameters
rgb the color to apply an adjustment to (modified in place)
gamma the gamma value to apply
Definition at line 1426 of file colorutils.cpp.
{
    rgb = applyGamma_video( rgb, gamma);
    return rgb;
}
References applyGamma_video().
napplyGamma_video() [2/4]
CRGB & napplyGamma_video (CRGB & rgb, float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to a color.
Parameters
rgb the color to apply an adjustment to (modified in place)
gammaR the gamma value to apply to the CRGB::red channel
gammaG the gamma value to apply to the CRGB::green channel
gammaB the gamma value to apply to the CRGB::blue channel
Definition at line 1432 of file colorutils.cpp.
{
    rgb = applyGamma_video( rgb, gammaR, gammaG, gammaB);
    return rgb;
}
References applyGamma_video().
napplyGamma_video() [3/4]
void napplyGamma_video (CRGB * rgbarray, uint16_t count, float gamma)
Destructively applies a gamma adjustment to a color array.
Parameters
rgbarray pointer to an LED array to apply an adjustment to (modified in place)
count the number of LEDs to modify
gamma the gamma value to apply
Definition at line 1438 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < count; ++i) {
        rgbarray[i] = applyGamma_video( rgbarray[i], gamma);
    }
}
References applyGamma_video().
napplyGamma_video() [4/4]
void napplyGamma_video (CRGB * rgbarray, uint16_t count, float gammaR, float gammaG, float gammaB)
Destructively applies a gamma adjustment to a color array.
Parameters
rgbarray pointer to an LED array to apply an adjustment to (modified in place)
count the number of LEDs to modify
gammaR the gamma value to apply to the CRGB::red channel
gammaG the gamma value to apply to the CRGB::green channel
gammaB the gamma value to apply to the CRGB::blue channel
Definition at line 1445 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < count; ++i) {
        rgbarray[i] = applyGamma_video( rgbarray[i], gammaR, gammaG, gammaB);
    }
}
References applyGamma_video().