FastLED: fl::ScreenMap Class Reference
fl::ScreenMap Class Reference
Detailed Description
Definition at line 28 of file screenmap.h.
#include <screenmap.h>
Public Member Functions
ScreenMap ()=default
ScreenMap (const pair_xy_float *lut, uint32_t length, float diameter=-1.0)
template<uint32_t N>
ScreenMap (const pair_xy_float(&lut)[N], float diameter=-1.0)
ScreenMap (const ScreenMap &other)
ScreenMap (uint32_t length, float mDiameter=-1.0f)
float getDiameter () const
uint32_t getLength () const
pair_xy_float mapToIndex (uint32_t x) const
ScreenMap & operator= (const ScreenMap &other)
pair_xy_float & operator[] (uint32_t x)
const pair_xy_float & operator[] (uint32_t x) const
void set (uint16_t index, const pair_xy_float &p)
void setDiameter (float diameter)
Static Public Member Functions
static ScreenMap Circle (int numLeds, float cm_between_leds=1.5f, float cm_led_diameter=0.5f)
static bool ParseJson (const char *jsonStrScreenMap, const char *screenMapName, ScreenMap *screenmap, Str *err=nullptr)
static bool ParseJson (const char *jsonStrScreenMap, FixedMap< Str, ScreenMap, 16 > *segmentMaps, Str *err=nullptr)
static void toJson (const FixedMap< Str, ScreenMap, 16 > &, JsonDocument *doc)
static void toJsonStr (const FixedMap< Str, ScreenMap, 16 > &, Str *jsonBuffer)
Static Private Member Functions
static const pair_xy_float & empty ()
Private Attributes
uint32_t length = 0
float mDiameter = -1.0f
LUTXYFLOATPtr mLookUpTable
Constructor & Destructor Documentation
ScreenMap() [1/5]
fl::ScreenMap::ScreenMap () default
Referenced by Circle().
ScreenMap() [2/5]
fl::ScreenMap::ScreenMap (uint32_t length, float mDiameter = -1.0f)
Definition at line 150 of file screenmap.cpp.
    : length(length), mDiameter(mDiameter) {
    mLookUpTable = LUTXYFLOATPtr::New(length);
    LUTXYFLOAT &lut = *mLookUpTable.get();
    pair_xy_float *data = lut.getData();
    for (uint32_t x = 0; x < length; x++) {
        data[x] = {0, 0};
    }
}
References fl::LUT< T >::getData(), length, mLookUpTable, and x.
ScreenMap() [3/5]
fl::ScreenMap::ScreenMap (const pair_xy_float * lut, uint32_t length, float diameter = -1.0)
Definition at line 160 of file screenmap.cpp.
    : length(length), mDiameter(diameter) {
    mLookUpTable = LUTXYFLOATPtr::New(length);
    LUTXYFLOAT &lut16xy = *mLookUpTable.get();
    pair_xy_float *data = lut16xy.getData();
    for (uint32_t x = 0; x < length; x++) {
        data[x] = lut[x];
    }
}
References fl::LUT< T >::getData(), length, mLookUpTable, and x.
ScreenMap() [4/5]
template<uint32_t N> fl::ScreenMap::ScreenMap (const pair_xy_float(&) lut[N], float diameter = -1.0) inline
Definition at line 42 of file screenmap.h.
        : ScreenMap(lut, N, diameter) {}
ScreenMap() [5/5]
fl::ScreenMap::ScreenMap (const ScreenMap & other)
Definition at line 170 of file screenmap.cpp.
{
    mDiameter = other.mDiameter;
    length = other.length;
    mLookUpTable = other.mLookUpTable;
}
References length, mDiameter, and mLookUpTable.
Member Function Documentation
Circle()
ScreenMap fl::ScreenMap::Circle (int numLeds, float cm_between_leds = 1.5f, float cm_led_diameter = 0.5f) static
Definition at line 21 of file screenmap.cpp.
{
    ScreenMap screenMap = ScreenMap(numLeds);
    float circumference = numLeds * cm_between_leds;
    float radius = circumference / (2 * PI);
    for (int i = 0; i < numLeds; i++) {
        float angle = i * 2 * PI / numLeds;
        float x = radius * cos(angle) * 2;
        float y = radius * sin(angle) * 2;
        screenMap[i] = {x, y};
    }
    screenMap.setDiameter(cm_led_diameter);
    return screenMap;
}
References ScreenMap(), PI, screenMap, x, and y.
Referenced by setup().
empty()
const pair_xy_float & fl::ScreenMap::empty () static private
Definition at line 199 of file screenmap.cpp.
{
    static const pair_xy_float s_empty = pair_xy_float(0, 0);
    return s_empty;
}
Referenced by operator[](), and operator[]().
getDiameter()
float fl::ScreenMap::getDiameter () const
Definition at line 197 of file screenmap.cpp.
{ return mDiameter; }
References mDiameter.
getLength()
uint32_t fl::ScreenMap::getLength () const
Definition at line 195 of file screenmap.cpp.
{ return length; }
References length.
Referenced by LedRopeTCL::LedRopeTCL(), and LedRopeTCL::RawDrawPixel().
mapToIndex()
pair_xy_float fl::ScreenMap::mapToIndex (uint32_t x) const
Definition at line 186 of file screenmap.cpp.
{
    if (x >= length || !mLookUpTable) {
        return {0, 0};
    }
    LUTXYFLOAT &lut = *mLookUpTable.get();
    pair_xy_float screen_coords = lut[x];
    return screen_coords;
}
References length, mLookUpTable, and x.
operator=()
ScreenMap & fl::ScreenMap::operator= (const ScreenMap & other)
Definition at line 221 of file screenmap.cpp.
{
    if (this != &other) {
        mDiameter = other.mDiameter;
        length = other.length;
        mLookUpTable = other.mLookUpTable;
    }
    return *this;
}
References length, mDiameter, and mLookUpTable.
operator[]() [1/2]
pair_xy_float & fl::ScreenMap::operator[] (uint32_t x)
Definition at line 212 of file screenmap.cpp.
{
    if (x >= length || !mLookUpTable) {
        return const_cast<pair_xy_float &>(empty()); // better than crashing.
    }
    LUTXYFLOAT &lut = *mLookUpTable.get();
    auto *data = lut.getData();
    return data[x];
}
References empty(), fl::LUT< T >::getData(), length, mLookUpTable, and x.
operator[]() [2/2]
const pair_xy_float & fl::ScreenMap::operator[] (uint32_t x) const
Definition at line 204 of file screenmap.cpp.
{
    if (x >= length || !mLookUpTable) {
        return empty(); // better than crashing.
    }
    LUTXYFLOAT &lut = *mLookUpTable.get();
    return lut[x];
}
References empty(), length, mLookUpTable, and x.
ParseJson() [1/2]
bool fl::ScreenMap::ParseJson (const char * jsonStrScreenMap, const char * screenMapName, ScreenMap * screenmap, Str * err = nullptr) static
Definition at line 80 of file screenmap.cpp.
{
#if !FASTLED_ENABLE_JSON
    if (err) {
        *err = "JSON not enabled";
    }
    return false;
#else
    FixedMap<Str, ScreenMap, 16> segmentMaps;
    bool ok = ParseJson(jsonStrScreenMap, &segmentMaps, err);
    if (!ok) {
        return false;
    }
    if (segmentMaps.size() == 0) {
        return false;
    }
    if (segmentMaps.has(screenMapName)) {
        *screenmap = segmentMaps[screenMapName];
        return true;
    }
    Str _err = "ScreenMap not found: ";
    _err.append(screenMapName);
    if (err) {
        *err = _err;
    }
    FASTLED_WARN(_err.c_str());
    return false;
#endif
}
References fl::Str::append(), fl::StrN< SIZE >::c_str(), FASTLED_WARN, fl::FixedMap< Key, Value, N >::has(), ParseJson(), and fl::FixedMap< Key, Value, N >::size().
ParseJson() [2/2]
bool fl::ScreenMap::ParseJson (const char * jsonStrScreenMap, FixedMap< Str, ScreenMap, 16 > * segmentMaps, Str * err = nullptr) static
Definition at line 37 of file screenmap.cpp.
{
#if !FASTLED_ENABLE_JSON
    if (err) {
        *err = "JSON not enabled";
    }
    return false;
#else
    JsonDocument doc;
    Str _err;
    if (!err) {
        err = &_err;
    }
    bool ok = parseJson(jsonStrScreenMap, &doc, err);
    if (!ok) {
        FASTLED_WARN("Failed to parse json: " << err->c_str());
        return false;
    }
    auto map = doc["map"];
    for (auto kv : map.as<FLArduinoJson::JsonObject>()) {
        auto segment = kv.value();
        auto x = segment["x"];
        auto y = segment["y"];
        auto obj = segment["diameter"];
        float diameter = -1.0f;
        if (obj.is<float>()) {
            float d = obj.as<float>();
            if (d > 0.0f) {
                diameter = d;
            }
        }
        auto n = x.size();
        ScreenMap segment_map(n, diameter);
        for (uint16_t j = 0; j < n; j++) {
            segment_map.set(j, pair_xy_float{x[j], y[j]});
        }
        segmentMaps->insert(kv.key().c_str(), segment_map);
    }
    return true;
#endif
}
References fl::StrN< SIZE >::c_str(), FASTLED_WARN, fl::FixedMap< Key, Value, N >::insert(), fl::parseJson(), set(), x, and y.
Referenced by ParseJson(), fl::FileSystem::readScreenMap(), fl::FileSystem::readScreenMaps(), and setup().
set()
void fl::ScreenMap::set (uint16_t index, const pair_xy_float & p)
Definition at line 176 of file screenmap.cpp.
{
    if (mLookUpTable) {
        LUTXYFLOAT &lut = *mLookUpTable.get();
        auto *data = lut.getData();
        data[index] = p;
    }
}
References fl::LUT< T >::getData(), mLookUpTable, and p.
Referenced by anonymous_namespace{LedRopeTCL.cpp}::init_screenmap(), ParseJson(), and fl::XYMap::toScreenMap().
setDiameter()
void fl::ScreenMap::setDiameter (float diameter)
Definition at line 184 of file screenmap.cpp.
{ mDiameter = diameter; }
References mDiameter.
toJson()
void fl::ScreenMap::toJson (const FixedMap< Str, ScreenMap, 16 > & segmentMaps, JsonDocument * doc) static
Definition at line 111 of file screenmap.cpp.
{
#if !FASTLED_ENABLE_JSON
    return;
#else
    auto &doc = *_doc;
    auto map = doc["map"].to<FLArduinoJson::JsonObject>();
    for (auto kv : segmentMaps) {
        auto segment = map[kv.first].to<FLArduinoJson::JsonObject>();
        auto x_array = segment["x"].to<FLArduinoJson::JsonArray>();
        auto y_array = segment["y"].to<FLArduinoJson::JsonArray>();
        for (uint16_t i = 0; i < kv.second.getLength(); i++) {
            const pair_xy_float &xy = kv.second[i];
            x_array.add(xy.x);
            y_array.add(xy.y);
        }
        float diameter = kv.second.getDiameter();
        if (diameter < 0.0f) {
            diameter = .5f; // 5mm.
        }
        if (diameter > 0.0f) {
            segment["diameter"] = diameter;
        }
    }
#endif
}
References xy().
Referenced by toJsonStr().
toJsonStr()
void fl::ScreenMap::toJsonStr (const FixedMap< Str, ScreenMap, 16 > & segmentMaps, Str * jsonBuffer) static
Definition at line 139 of file screenmap.cpp.
{
#if !FASTLED_ENABLE_JSON
    return;
#else
    JsonDocument doc;
    toJson(segmentMaps, &doc);
    fl::toJson(doc, jsonBuffer);
#endif
}
References toJson(), and fl::toJson().
Member Data Documentation
length
uint32_t fl::ScreenMap::length = 0 private
Definition at line 81 of file screenmap.h.
Referenced by ScreenMap(), ScreenMap(), ScreenMap(), getLength(), mapToIndex(), operator=(), operator[](), and operator[]().
mDiameter
float fl::ScreenMap::mDiameter = -1.0f private
Definition at line 82 of file screenmap.h.
Referenced by ScreenMap(), getDiameter(), operator=(), and setDiameter().
mLookUpTable
LUTXYFLOATPtr fl::ScreenMap::mLookUpTable private
Definition at line 83 of file screenmap.h.
Referenced by ScreenMap(), ScreenMap(), ScreenMap(), mapToIndex(), operator=(), operator[](), operator[](), and set().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/screenmap.h
/home/runner/work/FastLED/FastLED/src/fl/screenmap.cpp