FastLED: fl::DigitalPinImpl Class Reference
fl::DigitalPinImpl Class Reference
Detailed Description
Definition at line 56 of file digital_pin.cpp.
Public Member Functions
DigitalPinImpl (int pin)
~DigitalPinImpl ()=default
bool high ()
void setPinMode (DigitalPin::Mode mode)
void write (bool value)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Public Attributes
Pin mPin
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Constructor & Destructor Documentation
DigitalPinImpl()
fl::DigitalPinImpl::DigitalPinImpl (int pin) inline
Definition at line 58 of file digital_pin.cpp.
: mPin(pin) {}
~DigitalPinImpl()
fl::DigitalPinImpl::~DigitalPinImpl () default
Member Function Documentation
high()
bool fl::DigitalPinImpl::high () inline
Definition at line 72 of file digital_pin.cpp.
{ return mPin.hival(); }
References Pin::hival(), and mPin.
setPinMode()
void fl::DigitalPinImpl::setPinMode (DigitalPin::Mode mode) inline
Definition at line 61 of file digital_pin.cpp.
{
        switch (mode) {
            case DigitalPin::kInput:
                mPin.setInput();
                break;
            case DigitalPin::kOutput:
                mPin.setOutput();
                break;
        }
    }
References fl::DigitalPin::kInput, fl::DigitalPin::kOutput, mPin, Pin::setInput(), and Pin::setOutput().
write()
void fl::DigitalPinImpl::write (bool value) inline
Definition at line 73 of file digital_pin.cpp.
{ value ? mPin.hi(): mPin.lo(); }
References Pin::hi(), Pin::lo(), and mPin.
Member Data Documentation
mPin
Pin fl::DigitalPinImpl::mPin
Definition at line 75 of file digital_pin.cpp.
Referenced by high(), setPinMode(), and write().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/sensors/digital_pin.cpp