FastLED: /home/runner/work/FastLED/FastLED/examples/XYMatrix/XYMatrix.ino File Reference
XYMatrix.ino File Reference
Detailed Description
Demonstrates how to use an XY position helper function with a 2D matrix.
Definition in file XYMatrix.ino.
#include <FastLED.h>
Macros
#define BRIGHTNESS 64
#define CHIPSET WS2811
#define COLOR_ORDER GRB
#define LED_PIN 3
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Functions
void DrawOneFrame (uint8_t startHue8, int8_t yHueDelta8, int8_t xHueDelta8)
CRGB *const leds (leds_plus_safety_pixel+1)
void loop ()
void setup ()
uint16_t XY (uint8_t x, uint8_t y)
uint16_t XYsafe (uint8_t x, uint8_t y)
Variables
const uint8_t kMatrixHeight = 16
const bool kMatrixSerpentineLayout = true
const bool kMatrixVertical = false
const uint8_t kMatrixWidth = 16
CRGB leds_plus_safety_pixel [NUM_LEDS+1]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 64
Definition at line 12 of file XYMatrix.ino.
CHIPSET
#define CHIPSET WS2811
Definition at line 10 of file XYMatrix.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 9 of file XYMatrix.ino.
LED_PIN
#define LED_PIN 3
Definition at line 7 of file XYMatrix.ino.
NUM_LEDS
#define NUM_LEDS (kMatrixWidth * kMatrixHeight)
Definition at line 169 of file XYMatrix.ino.
Function Documentation
DrawOneFrame()
void DrawOneFrame (uint8_t startHue8, int8_t yHueDelta8, int8_t xHueDelta8)
Examples
XYMatrix.ino.
Definition at line 181 of file XYMatrix.ino.
{
  uint8_t lineStartHue = startHue8;
  for( uint8_t y = 0; y < kMatrixHeight; y++) {
    lineStartHue += yHueDelta8;
    uint8_t pixelHue = lineStartHue;
    for( uint8_t x = 0; x < kMatrixWidth; x++) {
      pixelHue += xHueDelta8;
      leds[ XY(x, y)]  = CHSV( pixelHue, 255, 255);
    }
  }
}
References kMatrixHeight, kMatrixWidth, leds, x, XY(), and y.
Referenced by loop().
leds()
CRGB *const leds (leds_plus_safety_pixel+ 1)
loop()
void loop ()
Definition at line 203 of file XYMatrix.ino.
{
    uint32_t ms = millis();
    int32_t yHueDelta32 = ((int32_t)cos16( ms * (27/1) ) * (350 / kMatrixWidth));
    int32_t xHueDelta32 = ((int32_t)cos16( ms * (39/1) ) * (310 / kMatrixHeight));
    DrawOneFrame( ms / 65536, yHueDelta32 / 32768, xHueDelta32 / 32768);
    if( ms < 5000 ) {
      FastLED.setBrightness( scale8( BRIGHTNESS, (ms * 256) / 5000));
    } else {
      FastLED.setBrightness(BRIGHTNESS);
    }
    FastLED.show();
}
References BRIGHTNESS, cos16(), DrawOneFrame(), FastLED, kMatrixHeight, kMatrixWidth, scale8(), CFastLED::setBrightness(), and CFastLED::show().
setup()
void setup ()
Definition at line 195 of file XYMatrix.ino.
             {
  FastLED.addLeds<CHIPSET, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalSMD5050);
  FastLED.setBrightness( BRIGHTNESS );
}
References CFastLED::addLeds(), BRIGHTNESS, CHIPSET, COLOR_ORDER, FastLED, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), and TypicalSMD5050.
XY()
uint16_t XY (uint8_t x, uint8_t y)
Definition at line 92 of file XYMatrix.ino.
{
  uint16_t i;
  if( kMatrixSerpentineLayout == false) {
    if (kMatrixVertical == false) {
      i = (y * kMatrixWidth) + x;
    } else {
      i = kMatrixHeight * (kMatrixWidth - (x+1))+y;
    }
  }
  if( kMatrixSerpentineLayout == true) {
    if (kMatrixVertical == false) {
      if( y & 0x01) {
        // Odd rows run backwards
        uint8_t reverseX = (kMatrixWidth - 1) - x;
        i = (y * kMatrixWidth) + reverseX;
      } else {
        // Even rows run forwards
        i = (y * kMatrixWidth) + x;
      }
    } else { // vertical positioning
      if ( x & 0x01) {
        i = kMatrixHeight * (kMatrixWidth - (x+1))+y;
      } else {
        i = kMatrixHeight * (kMatrixWidth - x) - (y+1);
      }
    }
  }
  return i;
}
References kMatrixHeight, kMatrixSerpentineLayout, kMatrixVertical, kMatrixWidth, x, and y.
XYsafe()
uint16_t XYsafe (uint8_t x, uint8_t y)
Examples
XYMatrix.ino.
Definition at line 173 of file XYMatrix.ino.
{
  if( x >= kMatrixWidth) return -1;
  if( y >= kMatrixHeight) return -1;
  return XY(x,y);
}
References kMatrixHeight, kMatrixWidth, x, XY(), and y.
Variable Documentation
kMatrixHeight
const uint8_t kMatrixHeight = 16
Definition at line 33 of file XYMatrix.ino.
kMatrixSerpentineLayout
const bool kMatrixSerpentineLayout = true
Definition at line 36 of file XYMatrix.ino.
kMatrixVertical
const bool kMatrixVertical = false
Examples
XYMatrix.ino.
Definition at line 37 of file XYMatrix.ino.
Referenced by XY().
kMatrixWidth
const uint8_t kMatrixWidth = 16
Definition at line 32 of file XYMatrix.ino.
leds_plus_safety_pixel
CRGB leds_plus_safety_pixel[NUM_LEDS+1]
Examples
XYMatrix.ino.
Definition at line 170 of file XYMatrix.ino.