FastLED: fl::Str Class Reference
fl::Str Class Reference
Detailed Description
Definition at line 368 of file str.h.
#include <str.h>
Public Member Functions
Str ()
Str (const char *str)
Str (const Str &other)
template<size_t M>
Str (const StrN< M > &other)
Str & append (const char *str)
Str & append (const char *str, size_t len)
Str & append (const int16_t &val)
Str & append (const int32_t &c)
Str & append (const int8_t &c)
Str & append (const StrN &str)
Str & append (const uint16_t &val)
Str & append (const uint32_t &val)
Str & append (const uint8_t &c)
bool operator!= (const Str &other) const
bool operator< (const Str &other) const
bool operator<= (const Str &other) const
Str & operator= (const Str &other)
bool operator== (const Str &other) const
bool operator> (const Str &other) const
bool operator>= (const Str &other) const
Public Member Functions inherited from fl::StrN< FASTLED_STR_INLINED_SIZE >
StrN ()=default
StrN (const char *str)
StrN (const char(&str)[N])
StrN (const StrN &other)
StrN (const StrN< M > &other)
~StrN ()
const char * c_str () const
char * c_str_mutable ()
size_t capacity () const
void clear (bool freeMemory=false)
void copy (const char *str)
void copy (const char *str, size_t len)
void copy (const StrN< M > &other)
bool empty () const
int16_t find (const char &value) const
size_t length () const
bool operator!= (const StrN &other) const
bool operator< (const StrN &other) const
bool operator< (const StrN< M > &other) const
StrN & operator= (const char(&str)[N])
StrN & operator= (const StrN &other)
StrN & operator= (const StrN< M > &other)
bool operator== (const StrN &other) const
char & operator[] (size_t index)
const char & operator[] (size_t index) const
void reserve (size_t newCapacity)
size_t size () const
StrN substring (size_t start, size_t end) const
float toFloat () const
StrN trim () const
size_t write (char c)
size_t write (const char *str, size_t n)
size_t write (const int32_t &val)
size_t write (const int8_t val)
size_t write (const uint16_t &n)
size_t write (const uint32_t &val)
size_t write (const uint8_t *data, size_t n)
size_t write (uint8_t c)
Constructor & Destructor Documentation
Str() [1/4]
fl::Str::Str () inline
Definition at line 370 of file str.h.
: StrN<FASTLED_STR_INLINED_SIZE>() {}
Str() [2/4]
fl::Str::Str (const char * str) inline
Definition at line 371 of file str.h.
: StrN<FASTLED_STR_INLINED_SIZE>(str) {}
Str() [3/4]
fl::Str::Str (const Str & other) inline
Definition at line 372 of file str.h.
: StrN<FASTLED_STR_INLINED_SIZE>(other) {}
Str() [4/4]
template<size_t M> fl::Str::Str (const StrN< M > & other) inline
Definition at line 374 of file str.h.
: StrN<FASTLED_STR_INLINED_SIZE>(other) {}
Member Function Documentation
append() [1/9]
Str & fl::Str::append (const char * str) inline
Definition at line 404 of file str.h.
{ write(str, strlen(str)); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
Referenced by fl::StrStreamHelper< T >::append(), fl::StrStreamHelper< char >::append(), fl::StrStreamHelper< int >::append(), fl::StrStreamHelper< uint8_t >::append(), fl::StrStreamHelper< unsigned int >::append(), fl::VideoFxWrapper::fxName(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::StrStream::operator<<(), fl::ScreenMap::ParseJson(), fl::FileSystem::readScreenMap(), fl::FileSystem::readScreenMaps(), fl::FileSystem::readText(), and CRGB::toString().
append() [2/9]
Str & fl::Str::append (const char * str, size_t len) inline
Definition at line 405 of file str.h.
{ write(str, len); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [3/9]
Str & fl::Str::append (const int16_t & val) inline
Definition at line 413 of file str.h.
{ write(uint32_t(val)); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [4/9]
Str & fl::Str::append (const int32_t & c) inline
Definition at line 415 of file str.h.
{ write(c); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [5/9]
Str & fl::Str::append (const int8_t & c) inline
Definition at line 407 of file str.h.
{
        const char* str = reinterpret_cast<const char*>(&c);
        write(str, 1); return *this;
    }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [6/9]
Str & fl::Str::append (const StrN & str) inline
Definition at line 417 of file str.h.
{ write(str.c_str(), str.size()); return *this; }
References fl::StrN< SIZE >::c_str(), fl::StrN< SIZE >::size(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [7/9]
Str & fl::Str::append (const uint16_t & val) inline
Definition at line 412 of file str.h.
{ write(val); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [8/9]
Str & fl::Str::append (const uint32_t & val) inline
Definition at line 414 of file str.h.
{ write(val); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
append() [9/9]
Str & fl::Str::append (const uint8_t & c) inline
Definition at line 411 of file str.h.
{ write(uint16_t(c)); return *this; }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::write().
operator!=()
bool fl::Str::operator!= (const Str & other) const inline
Definition at line 400 of file str.h.
{
        return strcmp(c_str(), other.c_str()) != 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
operator<()
bool fl::Str::operator< (const Str & other) const inline
Definition at line 388 of file str.h.
{
        return strcmp(c_str(), other.c_str()) < 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
operator<=()
bool fl::Str::operator<= (const Str & other) const inline
Definition at line 392 of file str.h.
{
        return strcmp(c_str(), other.c_str()) <= 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
operator=()
Str & fl::Str::operator= (const Str & other) inline
Definition at line 375 of file str.h.
{
        copy(other);
        return *this;
    }
References fl::StrN< FASTLED_STR_INLINED_SIZE >::copy().
operator==()
bool fl::Str::operator== (const Str & other) const inline
Definition at line 396 of file str.h.
{
        return strcmp(c_str(), other.c_str()) == 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
operator>()
bool fl::Str::operator> (const Str & other) const inline
Definition at line 380 of file str.h.
{
        return strcmp(c_str(), other.c_str()) > 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
operator>=()
bool fl::Str::operator>= (const Str & other) const inline
Definition at line 384 of file str.h.
{
        return strcmp(c_str(), other.c_str()) >= 0;
    }
References fl::StrN< SIZE >::c_str(), and fl::StrN< FASTLED_STR_INLINED_SIZE >::c_str().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/str.h