FastLED: /home/runner/work/FastLED/FastLED/examples/FxFire2012/FxFire2012.ino File Reference
FxFire2012.ino File Reference
#include <FastLED.h>
#include "fx/1d/fire2012.h"
Macros
#define BRIGHTNESS 128
#define CHIPSET WS2811
#define COLOR_ORDER GRB
#define COOLING 55
#define FRAMES_PER_SECOND 30
#define LED_PIN 5
#define NUM_LEDS 30
#define REVERSE_DIRECTION false
#define SPARKING 120
Functions
void loop ()
void setup ()
Variables
Fire2012Ptr fire = Fire2012Ptr::New(NUM_LEDS, COOLING, SPARKING, REVERSE_DIRECTION)
CRGB leds [NUM_LEDS]
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 128
Definition at line 49 of file FxFire2012.ino.
Referenced by setup().
CHIPSET
#define CHIPSET WS2811
Definition at line 46 of file FxFire2012.ino.
Referenced by setup().
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 45 of file FxFire2012.ino.
Referenced by setup().
COOLING
#define COOLING 55
Definition at line 51 of file FxFire2012.ino.
FRAMES_PER_SECOND
#define FRAMES_PER_SECOND 30
Definition at line 50 of file FxFire2012.ino.
Referenced by loop().
LED_PIN
#define LED_PIN 5
Definition at line 44 of file FxFire2012.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 30
Definition at line 47 of file FxFire2012.ino.
Referenced by setup().
REVERSE_DIRECTION
#define REVERSE_DIRECTION false
Definition at line 53 of file FxFire2012.ino.
SPARKING
#define SPARKING 120
Definition at line 52 of file FxFire2012.ino.
Function Documentation
loop()
void loop ()
Definition at line 66 of file FxFire2012.ino.
{
  fire->draw(Fx::DrawContext(millis(), leds)); // run simulation frame
  FastLED.show(millis()); // display this frame
  FastLED.delay(1000 / FRAMES_PER_SECOND);
}
References CFastLED::delay(), FastLED, fire, FRAMES_PER_SECOND, leds, and CFastLED::show().
setup()
void setup ()
Definition at line 58 of file FxFire2012.ino.
             {
  delay(3000); // sanity delay
  FastLED.addLeds<CHIPSET, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS)
    .setCorrection(TypicalLEDStrip)
    .setRgbw();
  FastLED.setBrightness(BRIGHTNESS);
}
References CFastLED::addLeds(), BRIGHTNESS, CHIPSET, COLOR_ORDER, FastLED, LED_PIN, leds, NUM_LEDS, CFastLED::setBrightness(), CLEDController::setRgbw(), and TypicalLEDStrip.
Variable Documentation
fire
Fire2012Ptr fire = Fire2012Ptr::New(NUM_LEDS, COOLING, SPARKING, REVERSE_DIRECTION)
Definition at line 56 of file FxFire2012.ino.
Referenced by loop().
leds
CRGB leds[NUM_LEDS]
Definition at line 55 of file FxFire2012.ino.
Referenced by loop(), and setup().