FastLED: fl::RectangularDrawBuffer Class Reference
fl::RectangularDrawBuffer Class Reference
Detailed Description
Definition at line 33 of file rectangular_draw_buffer.h.
#include <rectangular_draw_buffer.h>
Public Types
typedef fl::HeapVector< DrawItem > DrawList
enum QueueState { IDLE , QUEUEING , QUEUE_DONE }
Public Member Functions
RectangularDrawBuffer ()=default
~RectangularDrawBuffer ()=default
void getBlockInfo (uint32_t *num_strips, uint32_t *bytes_per_strip, uint32_t *total_bytes) const
fl::Slice< uint8_t > getLedsBufferBytesForPin (uint8_t pin, bool clear_first=true)
uint32_t getMaxBytesInStrip () const
uint32_t getTotalBytes () const
bool onQueuingDone ()
bool onQueuingStart ()
void queue (const DrawItem &item)
Public Attributes
scoped_array< uint8_t > mAllLedsBufferUint8
uint32_t mAllLedsBufferUint8Size = 0
DrawList mDrawList
bool mDrawListChangedThisFrame = false
fl::FixedMap< uint8_t, fl::Slice< uint8_t >, 50 > mPinToLedSegment
DrawList mPrevDrawList
QueueState mQueueState = IDLE
Member Typedef Documentation
DrawList
fl::HeapVector<DrawItem> fl::RectangularDrawBuffer::DrawList
Definition at line 35 of file rectangular_draw_buffer.h.
Member Enumeration Documentation
QueueState
enum fl::RectangularDrawBuffer::QueueState
Enumerator
IDLE
QUEUEING
QUEUE_DONE
Definition at line 45 of file rectangular_draw_buffer.h.
{ IDLE, QUEUEING, QUEUE_DONE };
Constructor & Destructor Documentation
RectangularDrawBuffer()
fl::RectangularDrawBuffer::RectangularDrawBuffer () default
~RectangularDrawBuffer()
fl::RectangularDrawBuffer::~RectangularDrawBuffer () default
Member Function Documentation
getBlockInfo()
void fl::RectangularDrawBuffer::getBlockInfo (uint32_t * num_strips, uint32_t * bytes_per_strip, uint32_t * total_bytes) const
Definition at line 92 of file rectangular_draw_buffer.cpp.
{
    *num_strips = mDrawList.size();
    *bytes_per_strip = getMaxBytesInStrip();
    *total_bytes = (*num_strips) * (*bytes_per_strip);
}
References getMaxBytesInStrip(), mDrawList, and fl::HeapVector< T >::size().
Referenced by onQueuingDone().
getLedsBufferBytesForPin()
Slice< uint8_t > fl::RectangularDrawBuffer::getLedsBufferBytesForPin (uint8_t pin, bool clear_first = true)
Definition at line 17 of file rectangular_draw_buffer.cpp.
{
    auto it = mPinToLedSegment.find(pin);
    if (it == mPinToLedSegment.end()) {
        FASTLED_ASSERT(false, "Pin not found in RectangularDrawBuffer");
        return fl::Slice<uint8_t>();
    }
    fl::Slice<uint8_t> slice = it->second;
    if (clear_first) {
        memset(slice.data(), 0, slice.size() * sizeof(slice[0]));
    }
    return slice;
}
References fl::Slice< T >::data(), fl::FixedMap< Key, Value, N >::end(), FASTLED_ASSERT, fl::FixedMap< Key, Value, N >::find(), mPinToLedSegment, and fl::Slice< T >::size().
getMaxBytesInStrip()
uint32_t fl::RectangularDrawBuffer::getMaxBytesInStrip () const
Definition at line 78 of file rectangular_draw_buffer.cpp.
{
    uint32_t max_bytes = 0;
    for (auto it = mDrawList.begin(); it != mDrawList.end(); ++it) {
        max_bytes = MAX(max_bytes, it->mNumBytes);
    }
    return max_bytes;
}
References fl::HeapVector< T >::begin(), fl::HeapVector< T >::end(), MAX, and mDrawList.
Referenced by getBlockInfo(), and getTotalBytes().
getTotalBytes()
uint32_t fl::RectangularDrawBuffer::getTotalBytes () const
Definition at line 86 of file rectangular_draw_buffer.cpp.
{
    uint32_t num_strips = mDrawList.size();
    uint32_t max_bytes = getMaxBytesInStrip();
    return num_strips * max_bytes;
}
References getMaxBytesInStrip(), mDrawList, and fl::HeapVector< T >::size().
onQueuingDone()
bool fl::RectangularDrawBuffer::onQueuingDone ()
Definition at line 48 of file rectangular_draw_buffer.cpp.
{
    if (mQueueState == QUEUE_DONE) {
        return false;
    }
    mQueueState = QUEUE_DONE;
    mDrawListChangedThisFrame = mDrawList != mPrevDrawList;
    // iterator through the current draw objects and calculate the total
    // number of bytes (representing RGB or RGBW) that will be drawn this frame.
    uint32_t total_bytes = 0;
    uint32_t max_bytes_in_strip = 0;
    uint32_t num_strips = 0;
    getBlockInfo(&num_strips, &max_bytes_in_strip, &total_bytes);
    if (total_bytes > mAllLedsBufferUint8Size) {
        uint8_t* old_ptr = mAllLedsBufferUint8.release();
        fl::LargeBlockAllocator<uint8_t>::Free(old_ptr);
        uint8_t* ptr = fl::LargeBlockAllocator<uint8_t>::Alloc(total_bytes);
        mAllLedsBufferUint8.reset(ptr);
    }
    mAllLedsBufferUint8Size = total_bytes;
    uint32_t offset = 0;
    for (auto it = mDrawList.begin(); it != mDrawList.end(); ++it) {
        uint8_t pin = it->mPin;
        Slice<uint8_t> slice(mAllLedsBufferUint8.get() + offset,
                             max_bytes_in_strip);
        mPinToLedSegment[pin] = slice;
        offset += max_bytes_in_strip;
    }
    return true;
}
References fl::LargeBlockAllocator< T >::Alloc(), fl::HeapVector< T >::begin(), fl::HeapVector< T >::end(), fl::LargeBlockAllocator< T >::Free(), fl::scoped_array< T, Deleter >::get(), getBlockInfo(), mAllLedsBufferUint8, mAllLedsBufferUint8Size, mDrawList, mDrawListChangedThisFrame, mPinToLedSegment, mPrevDrawList, mQueueState, QUEUE_DONE, fl::scoped_array< T, Deleter >::release(), and fl::scoped_array< T, Deleter >::reset().
onQueuingStart()
bool fl::RectangularDrawBuffer::onQueuingStart ()
Definition at line 30 of file rectangular_draw_buffer.cpp.
{
    if (mQueueState == QUEUEING) {
        return false;
    }
    mQueueState = QUEUEING;
    mPinToLedSegment.clear();
    mDrawList.swap(mPrevDrawList);
    mDrawList.clear();
    if (mAllLedsBufferUint8Size > 0) {
        memset(mAllLedsBufferUint8.get(), 0, mAllLedsBufferUint8Size);
    }
    return true;
}
References fl::FixedMap< Key, Value, N >::clear(), fl::HeapVector< T >::clear(), fl::scoped_array< T, Deleter >::get(), mAllLedsBufferUint8, mAllLedsBufferUint8Size, mDrawList, mPinToLedSegment, mPrevDrawList, mQueueState, QUEUEING, and fl::HeapVector< T >::swap().
queue()
void fl::RectangularDrawBuffer::queue (const DrawItem & item)
Definition at line 44 of file rectangular_draw_buffer.cpp.
{
    mDrawList.push_back(item);
}
References mDrawList, and fl::HeapVector< T >::push_back().
Member Data Documentation
mAllLedsBufferUint8
scoped_array<uint8_t> fl::RectangularDrawBuffer::mAllLedsBufferUint8
Definition at line 38 of file rectangular_draw_buffer.h.
Referenced by onQueuingDone(), and onQueuingStart().
mAllLedsBufferUint8Size
uint32_t fl::RectangularDrawBuffer::mAllLedsBufferUint8Size = 0
Definition at line 39 of file rectangular_draw_buffer.h.
Referenced by onQueuingDone(), and onQueuingStart().
mDrawList
DrawList fl::RectangularDrawBuffer::mDrawList
Definition at line 41 of file rectangular_draw_buffer.h.
Referenced by getBlockInfo(), getMaxBytesInStrip(), getTotalBytes(), onQueuingDone(), onQueuingStart(), and queue().
mDrawListChangedThisFrame
bool fl::RectangularDrawBuffer::mDrawListChangedThisFrame = false
Definition at line 43 of file rectangular_draw_buffer.h.
Referenced by onQueuingDone().
mPinToLedSegment
fl::FixedMap<uint8_t, fl::Slice<uint8_t>, 50> fl::RectangularDrawBuffer::mPinToLedSegment
Definition at line 40 of file rectangular_draw_buffer.h.
Referenced by getLedsBufferBytesForPin(), onQueuingDone(), and onQueuingStart().
mPrevDrawList
DrawList fl::RectangularDrawBuffer::mPrevDrawList
Definition at line 42 of file rectangular_draw_buffer.h.
Referenced by onQueuingDone(), and onQueuingStart().
mQueueState
QueueState fl::RectangularDrawBuffer::mQueueState = IDLE
Definition at line 46 of file rectangular_draw_buffer.h.
Referenced by onQueuingDone(), and onQueuingStart().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/rectangular_draw_buffer.h
/home/runner/work/FastLED/FastLED/src/fl/rectangular_draw_buffer.cpp