FastLED: CLEDController Class Reference
CLEDController Class Reference abstract
Detailed Description
Base definition for an LED controller.
Pretty much the methods that every LED controller object will make available. If you want to pass LED controllers around to methods, make them references to this type, keeps your code saner. However, most people won't be seeing/using these objects directly at all.
Note
That the methods for eventual checking of background writing of data (I'm looking at you, Teensy 3.0 DMA controller!) are not yet implemented.
Definition at line 36 of file cled_controller.h.
#include <cled_controller.h>
Public Member Functions
CLEDController ()
Create an led controller object, add it to the chain of controllers.
VIRTUAL_IF_NOT_AVR ~CLEDController ()
virtual void * beginShowLeds (int size)
void clearLedDataInternal (int nLeds=-1)
Zero out the LED data managed by this controller.
VIRTUAL_IF_NOT_AVR void clearLeds (int nLeds=-1)
Clear out/zero out the given number of LEDs.
virtual void endShowLeds (void *data)
CRGB getAdjustment (uint8_t scale)
Get the combined brightness/color adjustment for this controller.
ColorAdjustment getAdjustmentData (uint8_t brightness)
CRGB getCorrection ()
Get the correction value used by this controller.
uint8_t getDither ()
Get the dithering option currently set for this controller.
bool getEnabled ()
virtual uint16_t getMaxRefreshRate () const
Gets the maximum possible refresh rate of the strip.
Rgbw getRgbw () const
CRGB getTemperature ()
Get the color temperature, aka white point, for this controller.
virtual void init ()=0
Initialize the LED controller.
virtual int lanes ()
How many Lanes does this controller manage?
CRGB * leds ()
Pointer to the CRGB array for this controller.
CLEDController * next ()
Get the next controller in the linked list after this one.
CRGB & operator[] (int x)
Reference to the n'th LED managed by the controller.
CLEDController & setCorrection (CRGB correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setCorrection (LEDColorCorrection correction)
The color corrction to use for this controller, expressed as a CRGB object.
CLEDController & setDither (uint8_t ditherMode=BINARY_DITHER)
Set the dithering mode for this controller to use.
void setEnabled (bool enabled)
CLEDController & setLeds (CRGB *data, int nLeds)
Set the default array of LEDs to be used by this controller.
CLEDController & setRgbw (const Rgbw &arg=RgbwDefault::value())
CLEDController & setScreenMap (const fl::ScreenMap &map)
CLEDController & setScreenMap (const fl::XYMap &map)
CLEDController & setScreenMap (uint16_t width, uint16_t height)
CLEDController & setTemperature (ColorTemperature temperature)
Set the color temperature, aka white point, for this controller.
CLEDController & setTemperature (CRGB temperature)
Set the color temperature, aka white point, for this controller.
virtual void show (const struct CRGB *data, int nLeds, uint8_t brightness)=0
Write the passed in RGB data out to the LEDs managed by this controller.
virtual void showColor (const CRGB &data, int nLeds, uint8_t brightness)=0
Set all the LEDs to a given color.
void showColorInternal (const struct CRGB &data, int nLeds, uint8_t brightness)
void showColorInternal (const struct CRGB &data, uint8_t brightness)
void showInternal (const struct CRGB *data, int nLeds, uint8_t brightness)
VIRTUAL_IF_NOT_AVR void showLeds (uint8_t brightness)
void showLedsInternal (uint8_t brightness)
Write the data to the LEDs managed by this controller.
virtual int size ()
How many LEDs does this controller manage?
Static Public Member Functions
static CLEDController * head ()
Get the first LED controller in the linked list of controllers.
Public Attributes
Rgbw mRgbMode = RgbwInvalid::value()
Protected Attributes
CRGB m_ColorCorrection
CRGB object representing the color correction to apply to the strip on show()
CRGB m_ColorTemperature
CRGB object representing the color temperature to apply to the strip on show()
CRGB * m_Data
pointer to the LED data used by this controller
EDitherMode m_DitherMode
the current dither mode of the controller
bool m_enabled = true
int m_nLeds
the number of LEDs in the LED data array
CLEDController * m_pNext
pointer to the next LED controller in the linked list
Static Protected Attributes
static CLEDController * m_pHead = NULL
pointer to the first LED controller in the linked list
static CLEDController * m_pTail = NULL
pointer to the last LED controller in the linked list
Friends
class CFastLED
Constructor & Destructor Documentation
CLEDController()
CLEDController::CLEDController ()
Create an led controller object, add it to the chain of controllers.
Definition at line 14 of file cled_controller.cpp.
                               : m_Data(NULL), m_ColorCorrection(UncorrectedColor), m_ColorTemperature(UncorrectedTemperature), m_DitherMode(BINARY_DITHER), m_nLeds(0) {
    m_pNext = NULL;
    if(m_pHead==NULL) { m_pHead = this; }
    if(m_pTail != NULL) { m_pTail->m_pNext = this; }
    m_pTail = this;
}
References m_pHead, m_pNext, and m_pTail.
~CLEDController()
CLEDController::~CLEDController () default
Member Function Documentation
beginShowLeds()
virtual void * CLEDController::beginShowLeds (int size) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >, WS2816Controller< DATA_PIN, RGB_ORDER >, and WS2816Controller< DATA_PIN, RGB_ORDER >.
Definition at line 214 of file cled_controller.h.
{
        FASTLED_UNUSED(size);
        // By default, emit an integer. This integer will, by default, be passed back.
        // If you override beginShowLeds() then
        // you should also override endShowLeds() to match the return state.
        //
        // For async led controllers this should be used as a sync point to block
        // the caller until the leds from the last draw frame have completed drawing.
        // for each controller:
        //   beginShowLeds();
        // for each controller:
        //   showLeds();
        // for each controller:
        //   endShowLeds();
        uintptr_t d = getDither();
        void* out = reinterpret_cast<void*>(d);
        return out;
    }
References FASTLED_UNUSED, getDither(), and size().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().
clearLedDataInternal()
void CLEDController::clearLedDataInternal (int nLeds = -1)
Zero out the LED data managed by this controller.
Definition at line 23 of file cled_controller.cpp.
{
    if(m_Data) {
        nLeds = (nLeds < 0) ? m_nLeds : nLeds;
        nLeds = (nLeds > m_nLeds) ? m_nLeds : nLeds;
        memset((void*)m_Data, 0, sizeof(struct CRGB) * nLeds);
    }
}
References m_Data, and m_nLeds.
Referenced by CFastLED::clearData(), and clearLeds().
clearLeds()
VIRTUAL_IF_NOT_AVR void CLEDController::clearLeds (int nLeds = -1) inline
Clear out/zero out the given number of LEDs.
Parameters
nLeds the number of LEDs to clear
Definition at line 92 of file cled_controller.h.
{
        clearLedDataInternal(nLeds);
        showLeds(0);
    }
References clearLedDataInternal(), and showLeds().
endShowLeds()
virtual void CLEDController::endShowLeds (void * data) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >, WS2816Controller< DATA_PIN, RGB_ORDER >, and WS2816Controller< DATA_PIN, RGB_ORDER >.
Definition at line 233 of file cled_controller.h.
{
        // By default recieves the integer that beginShowLeds() emitted.
        //For async controllers this should be used to signal the controller
        // to begin transmitting the current frame to the leds.
        uintptr_t d = reinterpret_cast<uintptr_t>(data);
        setDither(static_cast<uint8_t>(d));
    }
References setDither().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().
getAdjustment()
CRGB CLEDController::getAdjustment (uint8_t scale) inline
Get the combined brightness/color adjustment for this controller.
Parameters
scale the brightness scale to get the correction for
Returns
a CRGB object representing the total adjustment, including color correction and color temperature
Definition at line 268 of file cled_controller.h.
{
        return CRGB::computeAdjustment(scale, m_ColorCorrection, m_ColorTemperature);
    }
References CRGB::computeAdjustment(), m_ColorCorrection, m_ColorTemperature, and scale.
Referenced by getAdjustmentData().
getAdjustmentData()
ColorAdjustment CLEDController::getAdjustmentData (uint8_t brightness)
Definition at line 32 of file cled_controller.cpp.
{
    // *premixed = getAdjustment(brightness);
    // if (color_correction) {
    //     *color_correction = getAdjustment(255);
    // }
    #if FASTLED_HD_COLOR_MIXING
    ColorAdjustment out = {this->getAdjustment(brightness), this->getAdjustment(255), brightness};
    #else
    ColorAdjustment out = {getAdjustment(brightness)};
    #endif
    return out;
}
References brightness, and getAdjustment().
Referenced by CPixelLEDController< RGB_ORDER, LANES, MASK >::show(), and CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor().
getCorrection()
CRGB CLEDController::getCorrection () inline
Get the correction value used by this controller.
Returns
the current color correction (CLEDController::m_ColorCorrection)
Definition at line 251 of file cled_controller.h.
{ return m_ColorCorrection; }
References m_ColorCorrection.
getDither()
uint8_t CLEDController::getDither () inline
Get the dithering option currently set for this controller.
Returns
the currently set dithering option (CLEDController::m_DitherMode)
Definition at line 212 of file cled_controller.h.
{ return m_DitherMode; }
References m_DitherMode.
Referenced by beginShowLeds(), CPixelLEDController< RGB_ORDER, LANES, MASK >::show(), and CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor().
getEnabled()
bool CLEDController::getEnabled () inline
Definition at line 73 of file cled_controller.h.
{ return m_enabled; }
References m_enabled.
Referenced by CFastLED::show(), and CFastLED::showColor().
getMaxRefreshRate()
virtual uint16_t CLEDController::getMaxRefreshRate () const inline virtual
Gets the maximum possible refresh rate of the strip.
Returns
the maximum refresh rate, in frames per second (FPS)
Definition at line 274 of file cled_controller.h.
{ return 0; }
Referenced by CFastLED::addLeds().
getRgbw()
Rgbw CLEDController::getRgbw () const inline
Definition at line 85 of file cled_controller.h.
{ return mRgbMode; }
References mRgbMode.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().
getTemperature()
CRGB CLEDController::getTemperature () inline
Get the color temperature, aka white point, for this controller.
Returns
the current color temperature (CLEDController::m_ColorTemperature)
Definition at line 263 of file cled_controller.h.
{ return m_ColorTemperature; }
References m_ColorTemperature.
head()
static CLEDController * CLEDController::head () inline static
Get the first LED controller in the linked list of controllers.
Returns
CLEDController::m_pHead
Definition at line 154 of file cled_controller.h.
{ return m_pHead; }
References m_pHead.
Referenced by calculate_max_brightness_for_power_mW(), CFastLED::clearData(), CFastLED::count(), CFastLED::operator[](), CFastLED::setCorrection(), CFastLED::setDither(), CFastLED::setTemperature(), CFastLED::show(), and CFastLED::showColor().
init()
virtual void CLEDController::init () pure virtual
Initialize the LED controller.
Implemented in APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >, APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_BitShift, 0x00000000, 0x00000000 >, APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(12), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >, APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(40), fl::kFiveBitGammaCorrectionMode_Null, 0x00000000, 0x00000000 >, APA102Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(6), fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>, APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, fl::kFiveBitGammaCorrectionMode_BitShift, uint32_t(0x00000000), uint32_t(0x00000000)>, DMXSerialController< RGB_ORDER >, DMXSerialController< RGB_ORDER >, DMXSimpleController< DATA_PIN, RGB_ORDER >, DMXSimpleController< DATA_PIN, RGB_ORDER >, LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >, LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >, P9813Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >, RGBWEmulatedController< CONTROLLER, RGB_ORDER >, SM16716Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >, WS2801Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >, WS2801Controller< DATA_PIN, CLOCK_PIN, RGB, DATA_RATE_MHZ(25) >, WS2816Controller< DATA_PIN, RGB_ORDER >, and WS2816Controller< DATA_PIN, RGB_ORDER >.
Referenced by CFastLED::addLeds().
lanes()
virtual int CLEDController::lanes () inline virtual
How many Lanes does this controller manage?
Returns
1 for a non-Parallel controller
Reimplemented in CPixelLEDController< RGB_ORDER, LANES, MASK >, CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >, CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >, CPixelLEDController< RGB >, and CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >.
Definition at line 178 of file cled_controller.h.
{ return 1; }
leds()
CRGB * CLEDController::leds () inline
Pointer to the CRGB array for this controller.
Returns
CLEDController::m_Data
Definition at line 182 of file cled_controller.h.
{ return m_Data; }
References m_Data.
Referenced by calculate_max_brightness_for_power_mW().
next()
CLEDController * CLEDController::next () inline
Get the next controller in the linked list after this one.
Will return NULL at the end of the linked list.
Returns
CLEDController::m_pNext
Definition at line 158 of file cled_controller.h.
{ return m_pNext; }
References m_pNext.
Referenced by calculate_max_brightness_for_power_mW(), CFastLED::clearData(), CFastLED::count(), CFastLED::operator[](), CFastLED::setCorrection(), CFastLED::setDither(), CFastLED::setTemperature(), CFastLED::show(), and CFastLED::showColor().
operator[]()
CRGB & CLEDController::operator[] (int x) inline
Reference to the n'th LED managed by the controller.
Parameters
x the LED number to retrieve
Returns
reference to CLEDController::m_Data[x]
Definition at line 187 of file cled_controller.h.
{ return m_Data[x]; }
References m_Data, and x.
setCorrection() [1/2]
CLEDController & CLEDController::setCorrection (CRGB correction) inline
The color corrction to use for this controller, expressed as a CRGB object.
Parameters
correction the color correction to set
Returns
a reference to the controller
Definition at line 244 of file cled_controller.h.
{ m_ColorCorrection = correction; return *this; }
References m_ColorCorrection.
Referenced by CFastLED::setCorrection().
setCorrection() [2/2]
CLEDController & CLEDController::setCorrection (LEDColorCorrection correction) inline
The color corrction to use for this controller, expressed as a CRGB object.
Parameters
correction the color correction to set
Returns
a reference to the controller
Definition at line 247 of file cled_controller.h.
{ m_ColorCorrection = correction; return *this; }
References m_ColorCorrection.
setDither()
CLEDController & CLEDController::setDither (uint8_t ditherMode = BINARY_DITHER) inline
Set the dithering mode for this controller to use.
Parameters
ditherMode the dithering mode to set
Returns
a reference to the controller
Examples
Pride2015.ino.
Definition at line 192 of file cled_controller.h.
{ m_DitherMode = ditherMode; return *this; }
References m_DitherMode.
Referenced by endShowLeds(), loop(), CFastLED::setDither(), setup(), CFastLED::show(), and CFastLED::showColor().
setEnabled()
void CLEDController::setEnabled (bool enabled) inline
Definition at line 72 of file cled_controller.h.
{ m_enabled = enabled; }
References m_enabled.
setLeds()
CLEDController & CLEDController::setLeds (CRGB * data, int nLeds) inline
Set the default array of LEDs to be used by this controller.
Parameters
data pointer to the LED data
nLeds the number of LEDs in the LED data
Definition at line 163 of file cled_controller.h.
{
        m_Data = data;
        m_nLeds = nLeds;
        return *this;
    }
References m_Data, and m_nLeds.
Referenced by CFastLED::addLeds().
setRgbw()
CLEDController & CLEDController::setRgbw (const Rgbw & arg = RgbwDefault::value()) inline
Definition at line 65 of file cled_controller.h.
{
        // Note that at this time (Sept 13th, 2024) this is only implemented in the ESP32 driver
        // directly. For an emulated version please see RGBWEmulatedController in chipsets.h
        mRgbMode = arg;
        return *this;  // builder pattern.
    }
References mRgbMode.
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::RGBWEmulatedController(), and setup().
setScreenMap() [1/3]
CLEDController & CLEDController::setScreenMap (const fl::ScreenMap & map) inline
Definition at line 201 of file cled_controller.h.
{
        fl::EngineEvents::onCanvasUiSet(this, map);
        return *this;
    }
References fl::EngineEvents::onCanvasUiSet().
setScreenMap() [2/3]
CLEDController & CLEDController::setScreenMap (const fl::XYMap & map) inline
Examples
FxEngine.ino.
Definition at line 194 of file cled_controller.h.
{
        // EngineEvents::onCanvasUiSet(this, map);
        fl::ScreenMap screenmap = map.toScreenMap();
        fl::EngineEvents::onCanvasUiSet(this, screenmap);
        return *this;
    }
References fl::EngineEvents::onCanvasUiSet().
Referenced by setScreenMap(), and setup().
setScreenMap() [3/3]
CLEDController & CLEDController::setScreenMap (uint16_t width, uint16_t height) inline
Definition at line 206 of file cled_controller.h.
{
        return setScreenMap(fl::XYMap::constructRectangularGrid(width, height));
    }
References fl::XYMap::constructRectangularGrid(), and setScreenMap().
setTemperature() [1/2]
CLEDController & CLEDController::setTemperature (ColorTemperature temperature) inline
Set the color temperature, aka white point, for this controller.
Parameters
temperature the color temperature to set
Returns
a reference to the controller
Definition at line 259 of file cled_controller.h.
{ m_ColorTemperature = temperature; return *this; }
References m_ColorTemperature.
setTemperature() [2/2]
CLEDController & CLEDController::setTemperature (CRGB temperature) inline
Set the color temperature, aka white point, for this controller.
Parameters
temperature the color temperature to set
Returns
a reference to the controller
Definition at line 256 of file cled_controller.h.
{ m_ColorTemperature = temperature; return *this; }
References m_ColorTemperature.
Referenced by CFastLED::setTemperature().
show()
virtual void CLEDController::show (const struct CRGB * data, int nLeds, uint8_t brightness) pure virtual
Write the passed in RGB data out to the LEDs managed by this controller.
Parameters
data the rgb data to write out to the strip
nLeds the number of LEDs being written out
scale the rgb scaling to apply to each led before writing it out
Implemented in CPixelLEDController< RGB_ORDER, LANES, MASK >, CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >, CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >, CPixelLEDController< RGB >, and CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >.
Referenced by showInternal(), and showLedsInternal().
showColor()
virtual void CLEDController::showColor (const CRGB & data, int nLeds, uint8_t brightness) pure virtual
Set all the LEDs to a given color.
Parameters
data the CRGB color to set the LEDs to
nLeds the number of LEDs to set to this color
scale the rgb scaling value for outputting color
Implemented in CPixelLEDController< RGB_ORDER, LANES, MASK >, CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >, CPixelLEDController< GRB, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >, CPixelLEDController< RGB >, and CPixelLEDController< RGB_ORDER, WS2812Controller800Khz< DATA_PIN, RGB >::LANES_VALUE, WS2812Controller800Khz< DATA_PIN, RGB >::MASK_VALUE >.
Referenced by showColorInternal(), and showColorInternal().
showColorInternal() [1/2]
void CLEDController::showColorInternal (const struct CRGB & data, int nLeds, uint8_t brightness) inline
Will scale for color correction and temperature. Can accept LED data not attached to this controller.
Parameters
data the CRGB color to set the LEDs to
nLeds the number of LEDs in the data array
brightness the brightness of the LEDs
See also
showColor(const struct CRGB&, int, CRGB)
Definition at line 126 of file cled_controller.h.
{
        if (m_enabled) {
            showColor(data, nLeds, brightness);
        }
    }
References brightness, m_enabled, and showColor().
Referenced by CFastLED::showColor().
showColorInternal() [2/2]
void CLEDController::showColorInternal (const struct CRGB & data, uint8_t brightness) inline
Parameters
data the CRGB color to set the LEDs to
brightness the brightness of the LEDs
See also
showColor(const struct CRGB&, int, CRGB)
Definition at line 146 of file cled_controller.h.
{
        if (m_enabled) {
            showColor(data, m_nLeds, brightness);
        }
    }
References brightness, m_enabled, m_nLeds, and showColor().
showInternal()
void CLEDController::showInternal (const struct CRGB * data, int nLeds, uint8_t brightness) inline
Will scale for color correction and temperature. Can accept LED data not attached to this controller.
Parameters
data the LED data to write to the strip
nLeds the number of LEDs in the data array
brightness the brightness of the LEDs
See also
show(const struct CRGB*, int, CRGB)
Definition at line 113 of file cled_controller.h.
{
        if (m_enabled) {
           show(data, nLeds,brightness);
        }
    }
References brightness, m_enabled, and show().
showLeds()
VIRTUAL_IF_NOT_AVR void CLEDController::showLeds (uint8_t brightness) inline
Definition at line 98 of file cled_controller.h.
{
        void* data = beginShowLeds(m_nLeds);
        showLedsInternal(brightness);
        endShowLeds(data);
    }
References beginShowLeds(), brightness, endShowLeds(), m_nLeds, and showLedsInternal().
Referenced by clearLeds().
showLedsInternal()
void CLEDController::showLedsInternal (uint8_t brightness) inline
Write the data to the LEDs managed by this controller.
Parameters
brightness the brightness of the LEDs
See also
show(const struct CRGB*, int, uint8_t)
Definition at line 135 of file cled_controller.h.
{
        if (m_enabled) {
            show(m_Data, m_nLeds, brightness);
        }
    }
References brightness, m_Data, m_enabled, m_nLeds, and show().
Referenced by CFastLED::show(), and showLeds().
size()
virtual int CLEDController::size () inline virtual
How many LEDs does this controller manage?
Returns
CLEDController::m_nLeds
Definition at line 174 of file cled_controller.h.
{ return m_nLeds; }
References m_nLeds.
Referenced by beginShowLeds(), WS2816Controller< DATA_PIN, RGB_ORDER >::beginShowLeds(), calculate_max_brightness_for_power_mW(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callBeginShowLeds(), WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callBeginShowLeds(), CFastLED::show(), CFastLED::showColor(), and CFastLED::size().
Friends And Related Symbol Documentation
CFastLED
friend class CFastLED friend
Definition at line 38 of file cled_controller.h.
Member Data Documentation
m_ColorCorrection
CRGB CLEDController::m_ColorCorrection protected
CRGB object representing the color correction to apply to the strip on show()
See also
setCorrection
Definition at line 41 of file cled_controller.h.
Referenced by getAdjustment(), getCorrection(), setCorrection(), and setCorrection().
m_ColorTemperature
CRGB CLEDController::m_ColorTemperature protected
CRGB object representing the color temperature to apply to the strip on show()
See also
setTemperature
Definition at line 42 of file cled_controller.h.
Referenced by getAdjustment(), getTemperature(), setTemperature(), and setTemperature().
m_Data
CRGB* CLEDController::m_Data protected
pointer to the LED data used by this controller
Definition at line 39 of file cled_controller.h.
Referenced by clearLedDataInternal(), leds(), operator[](), setLeds(), and showLedsInternal().
m_DitherMode
EDitherMode CLEDController::m_DitherMode protected
the current dither mode of the controller
Definition at line 43 of file cled_controller.h.
Referenced by getDither(), and setDither().
m_enabled
bool CLEDController::m_enabled = true protected
Definition at line 44 of file cled_controller.h.
Referenced by getEnabled(), setEnabled(), showColorInternal(), showColorInternal(), showInternal(), and showLedsInternal().
m_nLeds
int CLEDController::m_nLeds protected
the number of LEDs in the LED data array
Definition at line 45 of file cled_controller.h.
Referenced by clearLedDataInternal(), setLeds(), showColorInternal(), showLeds(), showLedsInternal(), and size().
m_pHead
CLEDController * CLEDController::m_pHead = NULL static protected
pointer to the first LED controller in the linked list
Definition at line 46 of file cled_controller.h.
Referenced by CLEDController(), and head().
m_pNext
CLEDController* CLEDController::m_pNext protected
pointer to the next LED controller in the linked list
Definition at line 40 of file cled_controller.h.
Referenced by CLEDController(), and next().
m_pTail
CLEDController * CLEDController::m_pTail = NULL static protected
pointer to the last LED controller in the linked list
Definition at line 47 of file cled_controller.h.
Referenced by CLEDController().
mRgbMode
Rgbw CLEDController::mRgbMode = RgbwInvalid::value()
Definition at line 64 of file cled_controller.h.
Referenced by getRgbw(), and setRgbw().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/cled_controller.h
/home/runner/work/FastLED/FastLED/src/cled_controller.cpp
/home/runner/work/FastLED/FastLED/src/FastLED.cpp