FastLED: anonymous_namespace{Painter.cpp} Namespace Reference
anonymous_namespace{Painter.cpp} Namespace Reference
Functions
float CalcLuminance (float time_delta_ms, bool sustain_pedal_on, const Key &key, int key_idx)
float CalcSaturation (float time_delta_ms, const ColorHSV &color, bool key_on)
float LuminanceDecay (float time)
Function Documentation
CalcLuminance()
float anonymous_namespace{Painter.cpp}::CalcLuminance (float time_delta_ms, bool sustain_pedal_on, const Key & key, int key_idx)
Definition at line 38 of file Painter.cpp.
{
  if (key.curr_color_.v_ <= 0.0) {
    return 0.0;
  }
  const bool dampened_key = (key_idx < kFirstNoteNoDamp);
  const float decay_factor = CalcDecayFactor(sustain_pedal_on,
                                             key.on_,
                                             key_idx,
                                             key.velocity_ * (1.f/127.f),  // Normalizing
                                             dampened_key,
                                             time_delta_ms);
  if (key.on_) {
    //const float brigthness_factor = sin(key.orig_color_.v_ * PI / 2.0);
    float brigthness_factor = 0.0f;
    if (kUseLedCurtin) {
      brigthness_factor = sqrt(sqrt(key.orig_color_.v_));
    } else {
      //brigthness_factor = key.orig_color_.v_ * key.orig_color_.v_;
      brigthness_factor = key.orig_color_.v_;
    }
    return LuminanceDecay(decay_factor) * brigthness_factor;
    //return 1.0f;
  } else {
    return decay_factor * key.orig_color_.v_;
  }
}
References CalcDecayFactor(), Key::curr_color_, kFirstNoteNoDamp, kUseLedCurtin, LuminanceDecay(), Key::on_, Key::orig_color_, ColorHSV::v_, and Key::velocity_.
CalcSaturation()
float anonymous_namespace{Painter.cpp}::CalcSaturation (float time_delta_ms, const ColorHSV & color, bool key_on)
Definition at line 73 of file Painter.cpp.
{
  if (color.v_ <= 0.0) {
    return color.s_;
  }
  if (!key_on) {
    return 1.0f;
  }
  static const float kDefaultSaturationTime = 0.05f * 1000.f;
  // At time = 0.0 the saturation_factor will be at 0.0 and then transition to 1.0
  float saturation_factor = mapf(time_delta_ms,
                                 0.0f, kDefaultSaturationTime,
                                 0.0f, 1.0f);
  // As time increases the saturation factor will continue
  // to grow past 1.0. We use min to clamp it back to 1.0.
  saturation_factor = MIN(1.0f, saturation_factor);
  // TODO - make the saturation interpolate between the original
  // color and the unsaturated state.
 return saturation_factor;
}
References mapf(), MIN, ColorHSV::s_, and ColorHSV::v_.
LuminanceDecay()
float anonymous_namespace{Painter.cpp}::LuminanceDecay (float time)
Definition at line 14 of file Painter.cpp.
{
  typedef InterpData<float, float> Datum;
  static const Datum kData[] = {
    Datum(0,  0),
    Datum(1,  0),
    Datum(10, 0),
    Datum(47, 60),
    Datum(120, 100),
    Datum(230, 160),
    Datum(250, 255),
    Datum(254, 255),
    Datum(255, 64),
  };
  const float key = time * 255.f;
  static const int n = sizeof(kData) / sizeof(kData[0]);
  float approx_val = Interp(key, kData, n);
  static const float k = (1.0f / 255.f);
  const float out = approx_val * k;
  return out;
}
References Interp().
Referenced by CalcLuminance().