FastLED: Integer Mapping Functions
Integer Mapping Functions
Fast Math Functions
Detailed Description
Maps a scalar from one integer size to another.
For example, a value representing 40% as an 8-bit unsigned integer would be 102 / 255. Using map8_to_16(uint8_t) to convert that to a 16-bit unsigned integer would give you 26,214 / 65,535, exactly 40% through the larger range.
Functions
LIB8STATIC_ALWAYS_INLINE uint8_t map16_to_8 (uint16_t x)
LIB8STATIC_ALWAYS_INLINE uint16_t map8_to_16 (uint8_t x)
LIB8STATIC_ALWAYS_INLINE uint32_t map8_to_32 (uint8_t x)
Function Documentation
map16_to_8()
LIB8STATIC_ALWAYS_INLINE uint8_t map16_to_8 (uint16_t x)
Definition at line 31 of file intmap.h.
{
    // Tested to be nearly identical to double precision floating point
    // doing this operation.
    if (x == 0) {
        return 0;
    }
    if (x >= 0xff00) {
        return 0xff;
    }
    return uint8_t((x + 128) >> 8);
}
References x.
Referenced by fl::five_bit_bitshift().
map8_to_16()
LIB8STATIC_ALWAYS_INLINE uint16_t map8_to_16 (uint8_t x)
Definition at line 25 of file intmap.h.
{
    return uint16_t(x) * 0x101;
}
References x.
Referenced by fl::five_bit_hd_gamma_function(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), and sqrt8().
map8_to_32()
LIB8STATIC_ALWAYS_INLINE uint32_t map8_to_32 (uint8_t x)
Definition at line 43 of file intmap.h.
{
    return uint32_t(x) * 0x1010101;
}
References x.