FastLED: fl::SortedHeapVector< T, LessThan > Class Template Reference
fl::SortedHeapVector< T, LessThan > Class Template Reference
Detailed Description
template<typename T, typename LessThan>
class fl::SortedHeapVector< T, LessThan >
Definition at line 492 of file vector.h.
#include <vector.h>
Public Types
typedef HeapVector< T >::const_iterator const_iterator
typedef HeapVector< T >::iterator iterator
Public Member Functions
SortedHeapVector (LessThan less=LessThan())
~SortedHeapVector ()
T & back ()
const T & back () const
iterator begin ()
const_iterator begin () const
size_t capacity () const
void clear ()
T * data ()
const T * data () const
bool empty () const
iterator end ()
const_iterator end () const
bool erase (const T &value)
bool erase (iterator pos)
iterator find (const T &value)
const_iterator find (const T &value) const
T & front ()
const T & front () const
bool full () const
bool has (const T &value) const
bool insert (const T &value, InsertResult *result=nullptr)
iterator lower_bound (const T &value)
const_iterator lower_bound (const T &value) const
T & operator[] (size_t index)
const T & operator[] (size_t index) const
void reserve (size_t n)
void setMaxSize (size_t n)
size_t size () const
void swap (SortedHeapVector &other)
Private Attributes
HeapVector< T > mArray
LessThan mLess
size_t mMaxSize = size_t(-1)
Member Typedef Documentation
const_iterator
template<typename T , typename LessThan > HeapVector<T>::const_iterator fl::SortedHeapVector< T, LessThan >::const_iterator
Definition at line 500 of file vector.h.
iterator
template<typename T , typename LessThan > HeapVector<T>::iterator fl::SortedHeapVector< T, LessThan >::iterator
Definition at line 499 of file vector.h.
Constructor & Destructor Documentation
SortedHeapVector()
template<typename T , typename LessThan > fl::SortedHeapVector< T, LessThan >::SortedHeapVector (LessThan less = LessThan()) inline
Definition at line 502 of file vector.h.
: mLess(less) {}
~SortedHeapVector()
template<typename T , typename LessThan > fl::SortedHeapVector< T, LessThan >::~SortedHeapVector () inline
Definition at line 517 of file vector.h.
{
        mArray.clear();
    }
References fl::SortedHeapVector< T, LessThan >::mArray.
Member Function Documentation
back() [1/2]
template<typename T , typename LessThan > T & fl::SortedHeapVector< T, LessThan >::back () inline
Definition at line 627 of file vector.h.
{ return mArray.back(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
back() [2/2]
template<typename T , typename LessThan > const T & fl::SortedHeapVector< T, LessThan >::back () const inline
Definition at line 628 of file vector.h.
{ return mArray.back(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
begin() [1/2]
template<typename T , typename LessThan > iterator fl::SortedHeapVector< T, LessThan >::begin () inline
Definition at line 631 of file vector.h.
{ return mArray.begin(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
begin() [2/2]
template<typename T , typename LessThan > const_iterator fl::SortedHeapVector< T, LessThan >::begin () const inline
Definition at line 632 of file vector.h.
{ return mArray.begin(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
capacity()
template<typename T , typename LessThan > size_t fl::SortedHeapVector< T, LessThan >::capacity () const inline
Definition at line 611 of file vector.h.
{ return mArray.capacity(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
clear()
template<typename T , typename LessThan > void fl::SortedHeapVector< T, LessThan >::clear () inline
Definition at line 612 of file vector.h.
{ mArray.clear(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
data() [1/2]
template<typename T , typename LessThan > T * fl::SortedHeapVector< T, LessThan >::data () inline
Definition at line 637 of file vector.h.
{ return mArray.data(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
data() [2/2]
template<typename T , typename LessThan > const T * fl::SortedHeapVector< T, LessThan >::data () const inline
Definition at line 638 of file vector.h.
{ return mArray.data(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
empty()
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::empty () const inline
Definition at line 610 of file vector.h.
{ return mArray.empty(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
end() [1/2]
template<typename T , typename LessThan > iterator fl::SortedHeapVector< T, LessThan >::end () inline
Definition at line 633 of file vector.h.
{ return mArray.end(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
Referenced by fl::SortedHeapVector< T, LessThan >::erase(), fl::SortedHeapVector< T, LessThan >::find(), fl::SortedHeapVector< T, LessThan >::has(), and fl::SortedHeapVector< T, LessThan >::insert().
end() [2/2]
template<typename T , typename LessThan > const_iterator fl::SortedHeapVector< T, LessThan >::end () const inline
Definition at line 634 of file vector.h.
{ return mArray.end(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
erase() [1/2]
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::erase (const T & value) inline
Definition at line 596 of file vector.h.
{
        iterator it = find(value);
        if (it != end()) {
            return mArray.erase(it);
        }
        return false;
    }
References fl::SortedHeapVector< T, LessThan >::end(), fl::SortedHeapVector< T, LessThan >::find(), and fl::SortedHeapVector< T, LessThan >::mArray.
erase() [2/2]
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::erase (iterator pos) inline
Definition at line 604 of file vector.h.
{
        return mArray.erase(pos);
    }
References fl::SortedHeapVector< T, LessThan >::mArray, and pos.
find() [1/2]
template<typename T , typename LessThan > iterator fl::SortedHeapVector< T, LessThan >::find (const T & value) inline
Definition at line 575 of file vector.h.
{
        iterator pos = lower_bound(value);
        if (pos != end() && !mLess(value, *pos) && !mLess(*pos, value)) {
            return pos;
        }
        return end();
    }
References fl::SortedHeapVector< T, LessThan >::end(), fl::SortedHeapVector< T, LessThan >::lower_bound(), fl::SortedHeapVector< T, LessThan >::mLess, and pos.
Referenced by fl::SortedHeapVector< T, LessThan >::erase(), fl::SortedHeapVector< T, LessThan >::find(), and fl::SortedHeapVector< T, LessThan >::has().
find() [2/2]
template<typename T , typename LessThan > const_iterator fl::SortedHeapVector< T, LessThan >::find (const T & value) const inline
Definition at line 587 of file vector.h.
{
        return const_cast<SortedHeapVector*>(this)->find(value);
    }
References fl::SortedHeapVector< T, LessThan >::find().
front() [1/2]
template<typename T , typename LessThan > T & fl::SortedHeapVector< T, LessThan >::front () inline
Definition at line 624 of file vector.h.
{ return mArray.front(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
front() [2/2]
template<typename T , typename LessThan > const T & fl::SortedHeapVector< T, LessThan >::front () const inline
Definition at line 625 of file vector.h.
{ return mArray.front(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
full()
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::full () const inline
Definition at line 613 of file vector.h.
                      {
        if (mArray.size() >= mMaxSize) {
            return true;
        }
        return mArray.full();
    }
References fl::SortedHeapVector< T, LessThan >::mArray, and fl::SortedHeapVector< T, LessThan >::mMaxSize.
has()
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::has (const T & value) const inline
Definition at line 591 of file vector.h.
{
        return find(value) != end();
    }
References fl::SortedHeapVector< T, LessThan >::end(), and fl::SortedHeapVector< T, LessThan >::find().
insert()
template<typename T , typename LessThan > bool fl::SortedHeapVector< T, LessThan >::insert (const T & value, InsertResult * result = nullptr) inline
Definition at line 526 of file vector.h.
{
        // Find insertion point using binary search
        iterator pos = lower_bound(value);
        if (pos != end() && !mLess(value, *pos) && !mLess(*pos, value)) {
            // return false; // Already inserted.
            if (result) {
                // *result = kExists;
                *result = InsertResult::kExists;
            }
            return false;
        }
        if (mArray.size() >= mMaxSize) {
            // return false;  // Too full
            if (result) {
                *result = InsertResult::kMaxSize;
            }
            return false;
        }
        mArray.insert(pos, value);
        if (result) {
            *result = kInserted;
        }
        return true;
    }
References fl::SortedHeapVector< T, LessThan >::end(), fl::kExists, fl::kInserted, fl::kMaxSize, fl::SortedHeapVector< T, LessThan >::lower_bound(), fl::SortedHeapVector< T, LessThan >::mArray, fl::SortedHeapVector< T, LessThan >::mLess, fl::SortedHeapVector< T, LessThan >::mMaxSize, and pos.
lower_bound() [1/2]
template<typename T , typename LessThan > iterator fl::SortedHeapVector< T, LessThan >::lower_bound (const T & value) inline
Definition at line 554 of file vector.h.
{
        iterator first = mArray.begin();
        iterator last = mArray.end();
        while (first != last) {
            iterator mid = first + (last - first) / 2;
            if (mLess(*mid, value)) {
                first = mid + 1;
            } else {
                last = mid;
            }
        }
        return first;
    }
References fl::SortedHeapVector< T, LessThan >::mArray, and fl::SortedHeapVector< T, LessThan >::mLess.
Referenced by fl::SortedHeapVector< T, LessThan >::find(), fl::SortedHeapVector< T, LessThan >::insert(), and fl::SortedHeapVector< T, LessThan >::lower_bound().
lower_bound() [2/2]
template<typename T , typename LessThan > const_iterator fl::SortedHeapVector< T, LessThan >::lower_bound (const T & value) const inline
Definition at line 570 of file vector.h.
{
        return const_cast<SortedHeapVector*>(this)->lower_bound(value);
    }
References fl::SortedHeapVector< T, LessThan >::lower_bound().
operator[]() [1/2]
template<typename T , typename LessThan > T & fl::SortedHeapVector< T, LessThan >::operator[] (size_t index) inline
Definition at line 621 of file vector.h.
{ return mArray[index]; }
References fl::SortedHeapVector< T, LessThan >::mArray.
operator[]() [2/2]
template<typename T , typename LessThan > const T & fl::SortedHeapVector< T, LessThan >::operator[] (size_t index) const inline
Definition at line 622 of file vector.h.
{ return mArray[index]; }
References fl::SortedHeapVector< T, LessThan >::mArray.
reserve()
template<typename T , typename LessThan > void fl::SortedHeapVector< T, LessThan >::reserve (size_t n) inline
Definition at line 521 of file vector.h.
{
        mArray.reserve(n);
    }
References fl::SortedHeapVector< T, LessThan >::mArray.
setMaxSize()
template<typename T , typename LessThan > void fl::SortedHeapVector< T, LessThan >::setMaxSize (size_t n) inline
Definition at line 504 of file vector.h.
{
        if (mMaxSize == n) {
            return;
        }
        mMaxSize = n;
        const bool needs_adjustment = mArray.size() > mMaxSize;
        if (needs_adjustment) {
            mArray.resize(n);
        } else {
            mArray.reserve(n);
        }
    }
References fl::SortedHeapVector< T, LessThan >::mArray, and fl::SortedHeapVector< T, LessThan >::mMaxSize.
size()
template<typename T , typename LessThan > size_t fl::SortedHeapVector< T, LessThan >::size () const inline
Definition at line 609 of file vector.h.
{ return mArray.size(); }
References fl::SortedHeapVector< T, LessThan >::mArray.
swap()
template<typename T , typename LessThan > void fl::SortedHeapVector< T, LessThan >::swap (SortedHeapVector< T, LessThan > & other) inline
Definition at line 583 of file vector.h.
{
        mArray.swap(other.mArray);
    }
References fl::SortedHeapVector< T, LessThan >::mArray.
Member Data Documentation
mArray
template<typename T , typename LessThan > HeapVector<T> fl::SortedHeapVector< T, LessThan >::mArray private
Definition at line 494 of file vector.h.
Referenced by fl::SortedHeapVector< T, LessThan >::~SortedHeapVector(), fl::SortedHeapVector< T, LessThan >::back(), fl::SortedHeapVector< T, LessThan >::back(), fl::SortedHeapVector< T, LessThan >::begin(), fl::SortedHeapVector< T, LessThan >::begin(), fl::SortedHeapVector< T, LessThan >::capacity(), fl::SortedHeapVector< T, LessThan >::clear(), fl::SortedHeapVector< T, LessThan >::data(), fl::SortedHeapVector< T, LessThan >::data(), fl::SortedHeapVector< T, LessThan >::empty(), fl::SortedHeapVector< T, LessThan >::end(), fl::SortedHeapVector< T, LessThan >::end(), fl::SortedHeapVector< T, LessThan >::erase(), fl::SortedHeapVector< T, LessThan >::erase(), fl::SortedHeapVector< T, LessThan >::front(), fl::SortedHeapVector< T, LessThan >::front(), fl::SortedHeapVector< T, LessThan >::full(), fl::SortedHeapVector< T, LessThan >::insert(), fl::SortedHeapVector< T, LessThan >::lower_bound(), fl::SortedHeapVector< T, LessThan >::operator[](), fl::SortedHeapVector< T, LessThan >::operator[](), fl::SortedHeapVector< T, LessThan >::reserve(), fl::SortedHeapVector< T, LessThan >::setMaxSize(), fl::SortedHeapVector< T, LessThan >::size(), and fl::SortedHeapVector< T, LessThan >::swap().
mLess
template<typename T , typename LessThan > LessThan fl::SortedHeapVector< T, LessThan >::mLess private
Definition at line 495 of file vector.h.
Referenced by fl::SortedHeapVector< T, LessThan >::find(), fl::SortedHeapVector< T, LessThan >::insert(), and fl::SortedHeapVector< T, LessThan >::lower_bound().
mMaxSize
template<typename T , typename LessThan > size_t fl::SortedHeapVector< T, LessThan >::mMaxSize = size_t(-1) private
Definition at line 496 of file vector.h.
Referenced by fl::SortedHeapVector< T, LessThan >::full(), fl::SortedHeapVector< T, LessThan >::insert(), and fl::SortedHeapVector< T, LessThan >::setMaxSize().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/vector.h