FastLED: fl::FrameInterpolator Class Reference
fl::FrameInterpolator Class Reference
Detailed Description
Definition at line 16 of file frame_interpolator.h.
#include <frame_interpolator.h>
Classes
struct Less
Public Types
typedef fl::SortedHeapMap< uint32_t, FramePtr, Less > FrameBuffer
Public Member Functions
FrameInterpolator (size_t nframes, float fpsVideo)
size_t capacity () const
void clear ()
bool draw (uint32_t adjustable_time, CRGB *leds)
bool draw (uint32_t adjustable_time, Frame *dst)
bool empty () const
FramePtr erase (uint32_t frameNum)
bool full () const
FramePtr get (uint32_t frameNum) const
uint32_t get_exact_timestamp_ms (uint32_t frameNumber) const
bool get_newest_frame_number (uint32_t *frameNumber) const
bool get_oldest_frame_number (uint32_t *frameNumber) const
FrameBuffer * getFrames ()
FrameTracker & getFrameTracker ()
bool has (uint32_t frameNum) const
bool insert (uint32_t frameNumber, FramePtr frame)
bool needsFrame (uint32_t now, uint32_t *currentFrameNumber, uint32_t *nextFrameNumber) const
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Private Attributes
FrameBuffer mFrames
FrameTracker mFrameTracker
Additional Inherited Members
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Member Typedef Documentation
FrameBuffer
fl::SortedHeapMap<uint32_t, FramePtr, Less> fl::FrameInterpolator::FrameBuffer
Definition at line 21 of file frame_interpolator.h.
Constructor & Destructor Documentation
FrameInterpolator()
fl::FrameInterpolator::FrameInterpolator (size_t nframes, float fpsVideo)
Definition at line 17 of file frame_interpolator.cpp.
    : mFrameTracker(fps) {
    size_t capacity = MAX(1, nframes);
    mFrames.setMaxSize(capacity);
}
References capacity(), MAX, mFrames, and fl::SortedHeapMap< Key, Value, Less >::setMaxSize().
Member Function Documentation
capacity()
size_t fl::FrameInterpolator::capacity () const inline
Definition at line 67 of file frame_interpolator.h.
{ return mFrames.capacity(); }
References fl::SortedHeapMap< Key, Value, Less >::capacity(), and mFrames.
Referenced by FrameInterpolator().
clear()
void fl::FrameInterpolator::clear () inline
Definition at line 41 of file frame_interpolator.h.
{ mFrames.clear(); }
References fl::SortedHeapMap< Key, Value, Less >::clear(), and mFrames.
draw() [1/2]
bool fl::FrameInterpolator::draw (uint32_t adjustable_time, CRGB * leds)
Definition at line 28 of file frame_interpolator.cpp.
{
    uint32_t frameNumber, nextFrameNumber;
    uint8_t amountOfNextFrame;
    // DBG("now: " << now);
    mFrameTracker.get_interval_frames(now, &frameNumber, &nextFrameNumber, &amountOfNextFrame);
    if (!has(frameNumber)) {
        return false;
    }
    if (has(frameNumber) && !has(nextFrameNumber)) {
        // just paint the current frame
        Frame* frame = get(frameNumber).get();
        frame->draw(leds);
        return true;
    }
    Frame* frame1 = get(frameNumber).get();
    Frame* frame2 = get(nextFrameNumber).get();
    Frame::interpolate(*frame1, *frame2, amountOfNextFrame, leds);
    return true;
}
References fl::Frame::draw(), get(), fl::FrameTracker::get_interval_frames(), has(), fl::Frame::interpolate(), leds, and mFrameTracker.
draw() [2/2]
bool fl::FrameInterpolator::draw (uint32_t adjustable_time, Frame * dst)
Definition at line 23 of file frame_interpolator.cpp.
{
    bool ok = draw(now, dst->rgb());
    return ok;
}
References draw(), and fl::Frame::rgb().
Referenced by draw().
empty()
bool fl::FrameInterpolator::empty () const inline
Definition at line 43 of file frame_interpolator.h.
{ return mFrames.empty(); }
References fl::SortedHeapMap< Key, Value, Less >::empty(), and mFrames.
erase()
FramePtr fl::FrameInterpolator::erase (uint32_t frameNum) inline
Definition at line 47 of file frame_interpolator.h.
{
        FramePtr out;
        auto it = mFrames.find(frameNum);
        if (it == mFrames.end()) {
            return out;
        }
        out = it->second;
        mFrames.erase(it);
        return out;
    }
References fl::SortedHeapMap< Key, Value, Less >::end(), fl::SortedHeapMap< Key, Value, Less >::erase(), fl::SortedHeapMap< Key, Value, Less >::find(), mFrames, and fl::Pair< Key, Value >::second.
full()
bool fl::FrameInterpolator::full () const inline
Definition at line 66 of file frame_interpolator.h.
{ return mFrames.full(); }
References fl::SortedHeapMap< Key, Value, Less >::full(), and mFrames.
get()
FramePtr fl::FrameInterpolator::get (uint32_t frameNum) const inline
Definition at line 58 of file frame_interpolator.h.
{
        auto it = mFrames.find(frameNum);
        if (it != mFrames.end()) {
            return it->second;
        }
        return FramePtr();
    }
References fl::SortedHeapMap< Key, Value, Less >::end(), fl::SortedHeapMap< Key, Value, Less >::find(), and mFrames.
Referenced by draw().
get_exact_timestamp_ms()
uint32_t fl::FrameInterpolator::get_exact_timestamp_ms (uint32_t frameNumber) const inline
Definition at line 96 of file frame_interpolator.h.
{
        return mFrameTracker.get_exact_timestamp_ms(frameNumber);
    }
References fl::FrameTracker::get_exact_timestamp_ms(), and mFrameTracker.
get_newest_frame_number()
bool fl::FrameInterpolator::get_newest_frame_number (uint32_t * frameNumber) const inline
Definition at line 78 of file frame_interpolator.h.
{
        if (mFrames.empty()) {
            return false;
        }
        auto &front = mFrames.back();
        *frameNumber = front.first;
        return true;
    }
References fl::SortedHeapMap< Key, Value, Less >::back(), fl::SortedHeapMap< Key, Value, Less >::empty(), and mFrames.
get_oldest_frame_number()
bool fl::FrameInterpolator::get_oldest_frame_number (uint32_t * frameNumber) const inline
Definition at line 87 of file frame_interpolator.h.
{
        if (mFrames.empty()) {
            return false;
        }
        auto &front = mFrames.front();
        *frameNumber = front.first;
        return true;
    }
References fl::SortedHeapMap< Key, Value, Less >::empty(), fl::SortedHeapMap< Key, Value, Less >::front(), and mFrames.
getFrames()
FrameBuffer * fl::FrameInterpolator::getFrames () inline
Definition at line 69 of file frame_interpolator.h.
{ return &mFrames; }
References mFrames.
getFrameTracker()
FrameTracker & fl::FrameInterpolator::getFrameTracker () inline
Definition at line 100 of file frame_interpolator.h.
{ return mFrameTracker; }
References mFrameTracker.
has()
bool fl::FrameInterpolator::has (uint32_t frameNum) const inline
Definition at line 45 of file frame_interpolator.h.
{ return mFrames.has(frameNum); }
References fl::SortedHeapMap< Key, Value, Less >::has(), and mFrames.
Referenced by draw(), and needsFrame().
insert()
bool fl::FrameInterpolator::insert (uint32_t frameNumber, FramePtr frame) inline
Definition at line 34 of file frame_interpolator.h.
{
        InsertResult result;
        mFrames.insert(frameNumber, frame, &result);
        return result != InsertResult::kMaxSize;
    }
References fl::SortedHeapMap< Key, Value, Less >::insert(), fl::kMaxSize, and mFrames.
needsFrame()
bool fl::FrameInterpolator::needsFrame (uint32_t now, uint32_t * currentFrameNumber, uint32_t * nextFrameNumber) const inline
Definition at line 71 of file frame_interpolator.h.
{
        mFrameTracker.get_interval_frames(now, currentFrameNumber,
                                          nextFrameNumber);
        return !has(*currentFrameNumber) || !has(*nextFrameNumber);
    }
References fl::FrameTracker::get_interval_frames(), has(), and mFrameTracker.
Member Data Documentation
mFrames
FrameBuffer fl::FrameInterpolator::mFrames private
Definition at line 104 of file frame_interpolator.h.
Referenced by FrameInterpolator(), capacity(), clear(), empty(), erase(), full(), get(), get_newest_frame_number(), get_oldest_frame_number(), getFrames(), has(), and insert().
mFrameTracker
FrameTracker fl::FrameInterpolator::mFrameTracker private
Definition at line 105 of file frame_interpolator.h.
Referenced by draw(), get_exact_timestamp_ms(), getFrameTracker(), and needsFrame().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fx/video/frame_interpolator.h
/home/runner/work/FastLED/FastLED/src/fx/video/frame_interpolator.cpp