FastLED: fl::RedSquare Class Reference
fl::RedSquare Class Reference
Detailed Description
Definition at line 13 of file redsquare.h.
#include <redsquare.h>
Classes
struct Math
Public Member Functions
RedSquare (XYMap xymap)
void draw (DrawContext context) override
fl::Str fxName () const override
Public Member Functions inherited from fl::Fx2d
Fx2d (const XYMap &xyMap)
uint16_t getHeight () const
uint16_t getWidth () const
XYMap & getXYMap ()
const XYMap & getXYMap () const
void setXYMap (const XYMap &xyMap)
uint16_t xyMap (uint16_t x, uint16_t y) const
Public Member Functions inherited from fl::Fx
Fx (uint16_t numLeds)
uint16_t getNumLeds () const
virtual bool hasFixedFrameRate (float *fps) const
virtual void pause (uint32_t now)
virtual void resume (uint32_t now)
Public Member Functions inherited from fl::Referent
virtual int ref_count () const
Additional Inherited Members
Public Types inherited from fl::Fx
using DrawContext = _DrawContext
Protected Member Functions inherited from fl::Fx
virtual ~Fx ()
Protected Member Functions inherited from fl::Referent
Referent ()
Referent (const Referent &)
Referent (Referent &&)
virtual ~Referent ()
virtual void destroy ()
Referent & operator= (const Referent &)
Referent & operator= (Referent &&)
virtual void ref ()
virtual void unref ()
Protected Attributes inherited from fl::Fx2d
XYMap mXyMap
Protected Attributes inherited from fl::Fx
uint16_t mNumLeds
Constructor & Destructor Documentation
RedSquare()
fl::RedSquare::RedSquare (XYMap xymap) inline
Definition at line 19 of file redsquare.h.
: Fx2d(xymap) {}
Member Function Documentation
draw()
void fl::RedSquare::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 21 of file redsquare.h.
{
        uint16_t width = getWidth();
        uint16_t height = getHeight();
        uint16_t square_size = Math::min(width, height) / 2;
        uint16_t start_x = (width - square_size) / 2;
        uint16_t start_y = (height - square_size) / 2;
        for (uint16_t x = 0; x < width; x++) {
            for (uint16_t y = 0; y < height; y++) {
                uint16_t idx = mXyMap.mapToIndex(x, y);
                if (idx < mXyMap.getTotal()) {
                    if (x >= start_x && x < start_x + square_size &&
                        y >= start_y && y < start_y + square_size) {
                        context.leds[idx] = CRGB::Red;
                    } else {
                        context.leds[idx] = CRGB::Black;
                    }
                }
            }
        }
    }
References CRGB::Black, fl::Fx2d::getHeight(), fl::XYMap::getTotal(), fl::Fx2d::getWidth(), fl::_DrawContext::leds, fl::XYMap::mapToIndex(), fl::RedSquare::Math::min(), fl::Fx2d::mXyMap, CRGB::Red, x, and y.
fxName()
fl::Str fl::RedSquare::fxName () const inline override virtual
Implements fl::Fx.
Definition at line 43 of file redsquare.h.
{ return "red_square"; }
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fx/2d/redsquare.h