FastLED: Waveform Beat Generators
Waveform Beat Generators
Fast Math Functions
Detailed Description
Waveform generators that reset at a given number of "beats per minute" (BPM).
The standard "beat" functions generate "sawtooth" waves which rise from 0 up to a max value and then reset, continuously repeating that cycle at the specified frequency (BPM).
The "sin" versions function similarly, but create an oscillating sine wave at the specified frequency.
BPM can be supplied two ways. The simpler way of specifying BPM is as a simple 8-bit integer from 1-255, (e.g., "120"). The more sophisticated way of specifying BPM allows for fractional "Q8.8" fixed point number (an accum88) with an 8-bit integer part and an 8-bit fractional part. The easiest way to construct this is to multiply a floating point BPM value (e.g. 120.3) by 256, (e.g. resulting in 30796 in this case), and pass that as the 16-bit BPM argument.
Originally these functions were designed to make an entire animation project pulse. with brightness. For that effect, add this line just above your existing call to "FastLED.show()":
uint8_t bright = beatsin8(60 /*BPM*/, 192 /*dimmest*/, 255 /*brightest*/));
FastLED.setBrightness(bright);
FastLED.show();
The entire animation will now pulse between brightness 192 and 255 once per second.
Warning
Any "BPM88" parameter MUST always be provided in Q8.8 format!
Note
The beat generators need access to a millisecond counter to track elapsed time. See GET_MILLIS for reference. When using the Arduino millis() function, accuracy is a bit better than one part in a thousand.
Functions
LIB8STATIC uint16_t beat16 (accum88 beats_per_minute, uint32_t timebase=0)
Generates a 16-bit "sawtooth" wave at a given BPM.
LIB8STATIC uint8_t beat8 (accum88 beats_per_minute, uint32_t timebase=0)
Generates an 8-bit "sawtooth" wave at a given BPM.
LIB8STATIC uint16_t beat88 (accum88 beats_per_minute_88, uint32_t timebase=0)
Generates a 16-bit "sawtooth" wave at a given BPM, with BPM specified in Q8.8 fixed-point format.
LIB8STATIC uint16_t beatsin16 (accum88 beats_per_minute, uint16_t lowest=0, uint16_t highest=65535, uint32_t timebase=0, uint16_t phase_offset=0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
LIB8STATIC uint8_t beatsin8 (accum88 beats_per_minute, uint8_t lowest=0, uint8_t highest=255, uint32_t timebase=0, uint8_t phase_offset=0)
Generates an 8-bit sine wave at a given BPM that oscillates within a given range.
LIB8STATIC uint16_t beatsin88 (accum88 beats_per_minute_88, uint16_t lowest=0, uint16_t highest=65535, uint32_t timebase=0, uint16_t phase_offset=0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
Function Documentation
beat16()
LIB8STATIC uint16_t beat16 (accum88 beats_per_minute, uint32_t timebase = 0)
Generates a 16-bit "sawtooth" wave at a given BPM.
Parameters
beats_per_minute the frequency of the wave, in decimal
timebase the time offset of the wave from the millis() timer
Examples
Pacifica.ino.
Definition at line 913 of file lib8tion.h.
{
    // Convert simple 8-bit BPM's to full Q8.8 accum88's if needed
    if( beats_per_minute < 256) beats_per_minute <<= 8;
    return beat88(beats_per_minute, timebase);
}
References beat88().
Referenced by beat8(), beatsin16(), fl::Pacifica::draw(), and pacifica_loop().
beat8()
LIB8STATIC uint8_t beat8 (accum88 beats_per_minute, uint32_t timebase = 0)
Generates an 8-bit "sawtooth" wave at a given BPM.
Parameters
beats_per_minute the frequency of the wave, in decimal
timebase the time offset of the wave from the millis() timer
Examples
Pacifica.ino.
Definition at line 923 of file lib8tion.h.
{
    return beat16( beats_per_minute, timebase) >> 8;
}
References beat16().
Referenced by beatsin8(), fl::Pacifica::pacifica_add_whitecaps(), and pacifica_add_whitecaps().
beat88()
LIB8STATIC uint16_t beat88 (accum88 beats_per_minute_88, uint32_t timebase = 0)
Generates a 16-bit "sawtooth" wave at a given BPM, with BPM specified in Q8.8 fixed-point format.
Parameters
beats_per_minute_88 the frequency of the wave, in Q8.8 format
timebase the time offset of the wave from the millis() timer
Warning
The BPM parameter MUST be provided in Q8.8 format! E.g. for 120 BPM it would be 120*256 = 30720. If you just want to specify "120", use beat16() or beat8().
Definition at line 897 of file lib8tion.h.
{
    // BPM is 'beats per minute', or 'beats per 60000ms'.
    // To avoid using the (slower) division operator, we
    // want to convert 'beats per 60000ms' to 'beats per 65536ms',
    // and then use a simple, fast bit-shift to divide by 65536.
    //
    // The ratio 65536:60000 is 279.620266667:256; we'll call it 280:256.
    // The conversion is accurate to about 0.05%, more or less,
    // e.g. if you ask for "120 BPM", you'll get about "119.93".
    return (((GET_MILLIS()) - timebase) * beats_per_minute_88 * 280) >> 16;
}
References GET_MILLIS.
Referenced by beat16(), and beatsin88().
beatsin16()
LIB8STATIC uint16_t beatsin16 (accum88 beats_per_minute, uint16_t lowest = 0, uint16_t highest = 65535, uint32_t timebase = 0, uint16_t phase_offset = 0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute the frequency of the wave, in decimal
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Examples
DemoReel100.ino, and Pacifica.ino.
Definition at line 957 of file lib8tion.h.
{
    uint16_t beat = beat16( beats_per_minute, timebase);
    uint16_t beatsin = (sin16( beat + phase_offset) + 32768);
    uint16_t rangewidth = highest - lowest;
    uint16_t scaledbeat = scale16( beatsin, rangewidth);
    uint16_t result = lowest + scaledbeat;
    return result;
}
References beat16(), scale16(), and sin16.
Referenced by fl::Pacifica::draw(), fl::DemoReel100::juggle(), juggle(), loop(), pacifica_loop(), fl::DemoReel100::sinelon(), and sinelon().
beatsin8()
LIB8STATIC uint8_t beatsin8 (accum88 beats_per_minute, uint8_t lowest = 0, uint8_t highest = 255, uint32_t timebase = 0, uint8_t phase_offset = 0)
Generates an 8-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute the frequency of the wave, in decimal
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Examples
DemoReel100.ino, and Pacifica.ino.
Definition at line 975 of file lib8tion.h.
{
    uint8_t beat = beat8( beats_per_minute, timebase);
    uint8_t beatsin = sin8( beat + phase_offset);
    uint8_t rangewidth = highest - lowest;
    uint8_t scaledbeat = scale8( beatsin, rangewidth);
    uint8_t result = lowest + scaledbeat;
    return result;
}
References beat8(), scale8(), and sin8.
Referenced by bpm(), fl::DemoReel100::bpm(), fl::Pacifica::draw(), loop(), fl::Pacifica::pacifica_add_whitecaps(), pacifica_add_whitecaps(), and pacifica_loop().
beatsin88()
LIB8STATIC uint16_t beatsin88 (accum88 beats_per_minute_88, uint16_t lowest = 0, uint16_t highest = 65535, uint32_t timebase = 0, uint16_t phase_offset = 0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute_88 the frequency of the wave, in Q8.8 format
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Warning
The BPM parameter MUST be provided in Q8.8 format! E.g. for 120 BPM it would be 120*256 = 30720. If you just want to specify "120", use beatsin16() or beatsin8().
Examples
Pacifica.ino, and Pride2015.ino.
Definition at line 939 of file lib8tion.h.
{
    uint16_t beat = beat88( beats_per_minute_88, timebase);
    uint16_t beatsin = (sin16( beat + phase_offset) + 32768);
    uint16_t rangewidth = highest - lowest;
    uint16_t scaledbeat = scale16( beatsin, rangewidth);
    uint16_t result = lowest + scaledbeat;
    return result;
}
References beat88(), scale16(), and sin16.
Referenced by fl::Pacifica::draw(), fl::Pride2015::draw(), pacifica_loop(), and pride().