FastLED: /home/runner/work/FastLED/FastLED/examples/AnalogOutput/AnalogOutput.ino File Reference
AnalogOutput.ino File Reference
Detailed Description
Demonstrates how to use FastLED color functions even without a "pixel-addressible" smart LED strip.
Definition in file AnalogOutput.ino.
#include <FastLED.h>
Macros
#define BLUEPIN 3
#define GREENPIN 6
#define REDPIN 5
Functions
void colorBars ()
void loop ()
void setup ()
void showAnalogRGB (const CRGB &rgb)
Macro Definition Documentation
BLUEPIN
#define BLUEPIN 3
Examples
AnalogOutput.ino.
Definition at line 23 of file AnalogOutput.ino.
Referenced by setup(), and showAnalogRGB().
GREENPIN
#define GREENPIN 6
Examples
AnalogOutput.ino.
Definition at line 22 of file AnalogOutput.ino.
Referenced by setup(), and showAnalogRGB().
REDPIN
#define REDPIN 5
Examples
AnalogOutput.ino.
Definition at line 21 of file AnalogOutput.ino.
Referenced by setup(), and showAnalogRGB().
Function Documentation
colorBars()
void colorBars ()
Examples
AnalogOutput.ino.
Definition at line 42 of file AnalogOutput.ino.
{
  showAnalogRGB( CRGB::Red );   delay(500);
  showAnalogRGB( CRGB::Green ); delay(500);
  showAnalogRGB( CRGB::Blue );  delay(500);
  showAnalogRGB( CRGB::Black ); delay(500);
}
References CRGB::Black, CRGB::Blue, CRGB::Green, CRGB::Red, and showAnalogRGB().
Referenced by setup().
loop()
void loop ()
Examples
AnalogOutput.ino, ArrayOfLedArrays.ino, Blink.ino, BlinkParallel.ino, ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FirstLight.ino, FxEngine.ino, MirroringSample.ino, MultiArrays.ino, MultipleStripsInOneArray.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, OctoWS2811Demo.ino, PJRCSpectrumAnalyzer.ino, Pacifica.ino, ParallelOutputDemo.ino, Pintest.ino, Pride2015.ino, RGBCalibrate.ino, RGBSetDemo.ino, SmartMatrix.ino, TwinkleFox.ino, WS2816.ino, and XYMatrix.ino.
Definition at line 50 of file AnalogOutput.ino.
{
  static uint8_t hue;
  hue = hue + 1;
  // Use FastLED automatic HSV->RGB conversion
  showAnalogRGB( CHSV( hue, 255, 255) );
  delay(20);
}
References showAnalogRGB().
setup()
void setup ()
Examples
AnalogOutput.ino, ArrayOfLedArrays.ino, Blink.ino, BlinkParallel.ino, ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FirstLight.ino, FxEngine.ino, MirroringSample.ino, MultiArrays.ino, MultipleStripsInOneArray.ino, Noise.ino, NoisePlayground.ino, NoisePlusPalette.ino, OctoWS2811Demo.ino, PJRCSpectrumAnalyzer.ino, Pacifica.ino, ParallelOutputDemo.ino, Pintest.ino, Pride2015.ino, RGBCalibrate.ino, RGBSetDemo.ino, SmartMatrix.ino, TwinkleFox.ino, WS2816.ino, and XYMatrix.ino.
Definition at line 61 of file AnalogOutput.ino.
             {
  pinMode(REDPIN,   OUTPUT);
  pinMode(GREENPIN, OUTPUT);
  pinMode(BLUEPIN,  OUTPUT);
  // Flash the "hello" color sequence: R, G, B, black.
  colorBars();
}
References BLUEPIN, colorBars(), GREENPIN, and REDPIN.
showAnalogRGB()
void showAnalogRGB (const CRGB & rgb)
Examples
AnalogOutput.ino.
Definition at line 31 of file AnalogOutput.ino.
{
  analogWrite(REDPIN,   rgb.r );
  analogWrite(GREENPIN, rgb.g );
  analogWrite(BLUEPIN,  rgb.b );
}
References BLUEPIN, GREENPIN, and REDPIN.
Referenced by colorBars(), and loop().