FastLED: Pin Class Reference
Pin Class Reference
Detailed Description
Naive fallback solution for low level pin access.
Definition at line 47 of file fastpin.h.
#include <fastpin.h>
Public Types
typedef volatile RwReg * port_ptr_t
type for a pin read/write register, volatile
typedef RwReg port_t
type for a pin read/write register, non-volatile
Public Member Functions
Pin (int pin)
Constructor.
virtual ~Pin ()
void fastset (FASTLED_REGISTER port_ptr_t port, FASTLED_REGISTER port_t val)
Set the state of a port.
void hi ()
Set the pin state to HIGH
void hi (FASTLED_REGISTER port_ptr_t port)
Set the same pin on another port to HIGH
port_t hival ()
Gets the state of the port with this pin HIGH
virtual bool isSelected () override
Checks if the pin is currently HIGH
void lo ()
Set the pin state to LOW
void lo (FASTLED_REGISTER port_ptr_t port)
Set the same pin on another port to LOW
port_t loval ()
Gets the state of the port with this pin LOW
port_t mask ()
Get the pin mask.
port_ptr_t port ()
Get the output state of the port.
virtual void release () override
Set the pin state to LOW
virtual void select () override
Set the pin state to HIGH
void set (FASTLED_REGISTER port_t val)
Set the state of the output register.
void setInput ()
Set the pin mode as INPUT
void setOutput ()
Set the pin mode as OUTPUT
void strobe ()
Toggle the pin twice to create a short pulse.
void toggle ()
Toggle the pin.
Public Member Functions inherited from Selectable
virtual ~Selectable ()
Private Member Functions
void _init ()
Initialize the class by retrieving the register pointers and bitmask.
Private Attributes
volatile RoReg * mInPort
Input register for the pin.
uint8_t mPin
Arduino digital pin number.
RwReg mPinMask
Bitmask for the pin within its register.
volatile RwReg * mPort
Output register for the pin.
Member Typedef Documentation
port_ptr_t
volatile RwReg* Pin::port_ptr_t
type for a pin read/write register, volatile
Definition at line 69 of file fastpin.h.
port_t
RwReg Pin::port_t
type for a pin read/write register, non-volatile
Definition at line 70 of file fastpin.h.
Constructor & Destructor Documentation
Pin()
Pin::Pin (int pin) inline
Constructor.
Parameters
pin Arduino digital pin number
Definition at line 64 of file fastpin.h.
: mPin(pin) { _init(); }
References _init().
~Pin()
virtual Pin::~Pin () inline virtual
Definition at line 66 of file fastpin.h.
{}  // Shut up the compiler warning, but don't steal bytes from AVR.
Member Function Documentation
_init()
void Pin::_init () inline private
Initialize the class by retrieving the register pointers and bitmask.
Definition at line 55 of file fastpin.h.
                 {
        mPinMask = digitalPinToBitMask(mPin);
        mPort = (volatile RwReg*)portOutputRegister(digitalPinToPort(mPin));
        mInPort = (volatile RoReg*)portInputRegister(digitalPinToPort(mPin));
    }
References mInPort, mPin, mPinMask, and mPort.
Referenced by Pin().
fastset()
void Pin::fastset (FASTLED_REGISTER port_ptr_t port, FASTLED_REGISTER port_t val) inline
Set the state of a port.
Parameters
port the port to modify
val the state to set the port to
Definition at line 103 of file fastpin.h.
{ *port  = val; }
References port().
hi() [1/2]
void Pin::hi () inline
Set the pin state to HIGH
Definition at line 79 of file fastpin.h.
{ *mPort |= mPinMask; }
References mPinMask, and mPort.
Referenced by calculate_max_brightness_for_power_mW(), select(), and fl::DigitalPinImpl::write().
hi() [2/2]
void Pin::hi (FASTLED_REGISTER port_ptr_t port) inline
Set the same pin on another port to HIGH
Parameters
port the port to modify
Definition at line 91 of file fastpin.h.
{ *port |= mPinMask; }
References mPinMask, and port().
hival()
port_t Pin::hival () inline
Gets the state of the port with this pin HIGH
Definition at line 106 of file fastpin.h.
{ return *mPort | mPinMask;  }
References mPinMask, and mPort.
Referenced by fl::DigitalPinImpl::high().
isSelected()
virtual bool Pin::isSelected () inline override virtual
Checks if the pin is currently HIGH
Implements Selectable.
Definition at line 119 of file fastpin.h.
{ return (*mPort & mPinMask) == mPinMask; }
References mPinMask, and mPort.
lo() [1/2]
void Pin::lo () inline
Set the pin state to LOW
Definition at line 81 of file fastpin.h.
{ *mPort &= ~mPinMask; }
References mPort.
Referenced by calculate_max_brightness_for_power_mW(), release(), and fl::DigitalPinImpl::write().
lo() [2/2]
void Pin::lo (FASTLED_REGISTER port_ptr_t port) inline
Set the same pin on another port to LOW
Parameters
port the port to modify
Definition at line 94 of file fastpin.h.
{ *port &= ~mPinMask; }
References port().
loval()
port_t Pin::loval () inline
Gets the state of the port with this pin LOW
Definition at line 108 of file fastpin.h.
{ return *mPort & ~mPinMask; }
References mPort.
mask()
port_t Pin::mask () inline
Get the pin mask.
Definition at line 112 of file fastpin.h.
{ return mPinMask; }
References mPinMask.
port()
port_ptr_t Pin::port () inline
Get the output state of the port.
Definition at line 110 of file fastpin.h.
{ return mPort; }
References mPort.
Referenced by fastset(), hi(), and lo().
release()
virtual void Pin::release () inline override virtual
Set the pin state to LOW
Implements Selectable.
Definition at line 117 of file fastpin.h.
{ lo(); }
References lo().
select()
virtual void Pin::select () inline override virtual
Set the pin state to HIGH
Implements Selectable.
Definition at line 115 of file fastpin.h.
{ hi(); }
References hi().
set()
void Pin::set (FASTLED_REGISTER port_t val) inline
Set the state of the output register.
Parameters
val the state to set the output register to
Note
This function is not limited to the current pin! It modifies the entire register.
Definition at line 98 of file fastpin.h.
{ *mPort = val; }
References mPort.
setInput()
void Pin::setInput () inline
Set the pin mode as INPUT
Definition at line 76 of file fastpin.h.
{ pinMode(mPin, INPUT); }
References mPin.
Referenced by InputPin::InputPin(), and fl::DigitalPinImpl::setPinMode().
setOutput()
void Pin::setOutput () inline
Set the pin mode as OUTPUT
Definition at line 73 of file fastpin.h.
{ pinMode(mPin, OUTPUT); }
References mPin.
Referenced by OutputPin::OutputPin(), and fl::DigitalPinImpl::setPinMode().
strobe()
void Pin::strobe () inline
Toggle the pin twice to create a short pulse.
Definition at line 84 of file fastpin.h.
{ toggle(); toggle(); }
References toggle().
toggle()
void Pin::toggle () inline
Toggle the pin.
If the pin was high, set it low. If was low, set it high.
Definition at line 87 of file fastpin.h.
{ *mInPort = mPinMask; }
References mInPort, and mPinMask.
Referenced by strobe().
Member Data Documentation
mInPort
volatile RoReg* Pin::mInPort private
Input register for the pin.
Definition at line 49 of file fastpin.h.
Referenced by _init(), and toggle().
mPin
uint8_t Pin::mPin private
Arduino digital pin number.
Definition at line 51 of file fastpin.h.
Referenced by _init(), setInput(), and setOutput().
mPinMask
RwReg Pin::mPinMask private
Bitmask for the pin within its register.
Definition at line 50 of file fastpin.h.
Referenced by _init(), hi(), hi(), hival(), isSelected(), mask(), and toggle().
mPort
volatile RwReg* Pin::mPort private
Output register for the pin.
Definition at line 48 of file fastpin.h.
Referenced by _init(), hi(), hival(), isSelected(), lo(), loval(), port(), and set().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fastpin.h