FastLED: fl::FixedMap< Key, Value, N > Class Template Reference
fl::FixedMap< Key, Value, N > Class Template Reference
Detailed Description
template<typename Key, typename Value, size_t N>
class fl::FixedMap< Key, Value, N >
Definition at line 29 of file map.h.
#include <map.h>
Public Types
typedef VectorType::const_iterator const_iterator
typedef VectorType::iterator iterator
using PairKV = fl::Pair<Key, Value>
typedef FixedVector< PairKV, N > VectorType
Public Member Functions
constexpr FixedMap ()=default
iterator begin ()
const_iterator begin () const
constexpr size_t capacity () const
void clear ()
bool contains (const Key &key) const
constexpr bool empty () const
iterator end ()
const_iterator end () const
iterator find (const Key &key)
const_iterator find (const Key &key) const
Value get (const Key &key, bool *has=nullptr) const
bool get (const Key &key, Value *value) const
bool has (const Key &it) const
template<typename Less >
iterator highest (Less less_than=Less())
template<typename Less >
const_iterator highest (Less less_than=Less()) const
Pair< bool, iterator > insert (const Key &key, const Value &value, InsertResult *result=nullptr)
template<typename Less >
iterator lowest (Less less_than=Less())
template<typename Less >
const_iterator lowest (Less less_than=Less()) const
bool next (const Key &key, Key *next_key, bool allow_rollover=false) const
Value & operator[] (const Key &key)
const Value & operator[] (const Key &key) const
bool prev (const Key &key, Key *prev_key, bool allow_rollover=false) const
constexpr size_t size () const
bool update (const Key &key, const Value &value, bool insert_if_missing=true)
Private Attributes
VectorType data
Member Typedef Documentation
const_iterator
template<typename Key , typename Value , size_t N> VectorType::const_iterator fl::FixedMap< Key, Value, N >::const_iterator
Definition at line 35 of file map.h.
iterator
template<typename Key , typename Value , size_t N> VectorType::iterator fl::FixedMap< Key, Value, N >::iterator
Definition at line 34 of file map.h.
PairKV
template<typename Key , typename Value , size_t N> using fl::FixedMap< Key, Value, N >::PairKV = fl::Pair<Key, Value>
Definition at line 31 of file map.h.
VectorType
template<typename Key , typename Value , size_t N> FixedVector<PairKV, N> fl::FixedMap< Key, Value, N >::VectorType
Definition at line 33 of file map.h.
Constructor & Destructor Documentation
FixedMap()
template<typename Key , typename Value , size_t N> fl::FixedMap< Key, Value, N >::FixedMap () constexpr default
Member Function Documentation
begin() [1/2]
template<typename Key , typename Value , size_t N> iterator fl::FixedMap< Key, Value, N >::begin () inline
Definition at line 41 of file map.h.
                     {
        return data.begin();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedMap< Key, Value, N >::data.
Referenced by fl::FixedMap< Key, Value, N >::find(), fl::FixedMap< Key, Value, N >::find(), fl::FixedMap< Key, Value, N >::highest(), fl::FixedMap< Key, Value, N >::highest(), fl::FixedMap< Key, Value, N >::lowest(), fl::FixedMap< Key, Value, N >::lowest(), fl::FixedMap< Key, Value, N >::next(), and fl::FixedMap< Key, Value, N >::prev().
begin() [2/2]
template<typename Key , typename Value , size_t N> const_iterator fl::FixedMap< Key, Value, N >::begin () const inline
Definition at line 47 of file map.h.
{
        return data.begin();
    }
References fl::FixedVector< T, N >::begin(), and fl::FixedMap< Key, Value, N >::data.
capacity()
template<typename Key , typename Value , size_t N> size_t fl::FixedMap< Key, Value, N >::capacity () const inline constexpr
Definition at line 235 of file map.h.
{
        return N;
    }
clear()
template<typename Key , typename Value , size_t N> void fl::FixedMap< Key, Value, N >::clear () inline
Definition at line 240 of file map.h.
                 {
        data.clear();
    }
References fl::FixedVector< T, N >::clear(), and fl::FixedMap< Key, Value, N >::data.
Referenced by fl::RectangularDrawBuffer::onQueuingStart().
contains()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::contains (const Key & key) const inline
Definition at line 248 of file map.h.
{
        return has(key);
    }
References fl::FixedMap< Key, Value, N >::has().
empty()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::empty () const inline constexpr
Definition at line 230 of file map.h.
{
        return data.empty();
    }
References fl::FixedMap< Key, Value, N >::data, and fl::FixedVector< T, N >::empty().
Referenced by fl::FxEngine::addFx(), fl::FxEngine::draw(), fl::FixedMap< Key, Value, N >::next(), and fl::FixedMap< Key, Value, N >::prev().
end() [1/2]
template<typename Key , typename Value , size_t N> iterator fl::FixedMap< Key, Value, N >::end () inline
Definition at line 44 of file map.h.
                   {
        return data.end();
    }
References fl::FixedMap< Key, Value, N >::data, and fl::FixedVector< T, N >::end().
Referenced by fl::FixedMap< Key, Value, N >::find(), fl::FixedMap< Key, Value, N >::find(), fl::FixedMap< Key, Value, N >::get(), fl::FixedMap< Key, Value, N >::get(), fl::RectangularDrawBuffer::getLedsBufferBytesForPin(), fl::FixedMap< Key, Value, N >::has(), fl::FixedMap< Key, Value, N >::highest(), fl::FixedMap< Key, Value, N >::highest(), fl::FixedMap< Key, Value, N >::insert(), fl::FixedMap< Key, Value, N >::lowest(), fl::FixedMap< Key, Value, N >::lowest(), fl::FixedMap< Key, Value, N >::next(), fl::FixedMap< Key, Value, N >::operator[](), fl::FixedMap< Key, Value, N >::operator[](), fl::FixedMap< Key, Value, N >::prev(), and fl::FixedMap< Key, Value, N >::update().
end() [2/2]
template<typename Key , typename Value , size_t N> const_iterator fl::FixedMap< Key, Value, N >::end () const inline
Definition at line 50 of file map.h.
{
        return data.end();
    }
References fl::FixedMap< Key, Value, N >::data, and fl::FixedVector< T, N >::end().
find() [1/2]
template<typename Key , typename Value , size_t N> iterator fl::FixedMap< Key, Value, N >::find (const Key & key) inline
Definition at line 54 of file map.h.
{
        for (auto it = begin(); it != end(); ++it) {
            if (it->first == key) {
                return it;
            }
        }
        return end();
    }
References fl::FixedMap< Key, Value, N >::begin(), and fl::FixedMap< Key, Value, N >::end().
Referenced by fl::FixedMap< Key, Value, N >::get(), fl::FixedMap< Key, Value, N >::get(), fl::RectangularDrawBuffer::getLedsBufferBytesForPin(), fl::FixedMap< Key, Value, N >::has(), fl::FixedMap< Key, Value, N >::insert(), fl::FixedMap< Key, Value, N >::next(), fl::FixedMap< Key, Value, N >::operator[](), fl::FixedMap< Key, Value, N >::operator[](), fl::FixedMap< Key, Value, N >::prev(), and fl::FixedMap< Key, Value, N >::update().
find() [2/2]
template<typename Key , typename Value , size_t N> const_iterator fl::FixedMap< Key, Value, N >::find (const Key & key) const inline
Definition at line 63 of file map.h.
{
        for (auto it = begin(); it != end(); ++it) {
            if (it->first == key) {
                return it;
            }
        }
        return end();
    }
References fl::FixedMap< Key, Value, N >::begin(), and fl::FixedMap< Key, Value, N >::end().
get() [1/2]
template<typename Key , typename Value , size_t N> Value fl::FixedMap< Key, Value, N >::get (const Key & key, bool * has = nullptr) const inline
Definition at line 127 of file map.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            if (has) {
                *has = true;
            }
            return it->second;
        }
        if (has) {
            *has = false;
        }
        return Value();
    }
References fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::find(), and fl::FixedMap< Key, Value, N >::has().
get() [2/2]
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::get (const Key & key, Value * value) const inline
Definition at line 118 of file map.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            *value = it->second;
            return true;
        }
        return false;
    }
References fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::find().
Referenced by fl::FxEngine::draw(), fl::FxEngine::getFx(), fl::FxEngine::removeFx(), and setup().
has()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::has (const Key & it) const inline
Definition at line 244 of file map.h.
{
        return find(it) != end();
    }
References fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::find().
Referenced by fl::FixedMap< Key, Value, N >::contains(), fl::FixedMap< Key, Value, N >::get(), fl::FxEngine::getFx(), fl::ScreenMap::ParseJson(), fl::FxEngine::removeFx(), and fl::FxEngine::setNextFx().
highest() [1/2]
template<typename Key , typename Value , size_t N> template<typename Less > iterator fl::FixedMap< Key, Value, N >::highest (Less less_than = Less()) inline
Definition at line 95 of file map.h.
{
        iterator highest = end();
        for (iterator it = begin(); it != end(); ++it) {
            if (highest == end() || less_than(highest->first, it->first)) {
                highest = it;
            }
        }
        return highest;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::highest().
Referenced by fl::FixedMap< Key, Value, N >::highest(), and fl::FixedMap< Key, Value, N >::highest().
highest() [2/2]
template<typename Key , typename Value , size_t N> template<typename Less > const_iterator fl::FixedMap< Key, Value, N >::highest (Less less_than = Less()) const inline
Definition at line 106 of file map.h.
{
        const_iterator highest = end();
        for (const_iterator it = begin(); it != end(); ++it) {
            if (highest == end() || less_than(highest->first, it->first)) {
                highest = it;
            }
        }
        return highest;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::highest().
insert()
template<typename Key , typename Value , size_t N> Pair< bool, iterator > fl::FixedMap< Key, Value, N >::insert (const Key & key, const Value & value, InsertResult * result = nullptr) inline
Definition at line 141 of file map.h.
{
        iterator it = find(key);
        if (it != end()) {
            if (result) {
                *result = InsertResult::kExists;
            }
            // return false;
            return {false, it};
        }
        if (data.size() < N) {
            data.push_back(PairKV(key, value));
            if (result) {
                *result = InsertResult::kInserted;
            }
            // return true;
            return {true, data.end() - 1};
        }
        if (result) {
            *result = InsertResult::kMaxSize;
        }
        //return false;
        return {false, end()};
    }
References fl::FixedMap< Key, Value, N >::data, fl::FixedMap< Key, Value, N >::end(), fl::FixedVector< T, N >::end(), fl::FixedMap< Key, Value, N >::find(), fl::kExists, fl::kInserted, fl::kMaxSize, fl::FixedVector< T, N >::push_back(), and fl::FixedVector< T, N >::size().
Referenced by fl::FxEngine::addFx(), fl::ScreenMap::ParseJson(), and fl::FixedMap< Key, Value, N >::update().
lowest() [1/2]
template<typename Key , typename Value , size_t N> template<typename Less > iterator fl::FixedMap< Key, Value, N >::lowest (Less less_than = Less()) inline
Definition at line 73 of file map.h.
{
        iterator lowest = end();
        for (iterator it = begin(); it != end(); ++it) {
            if (lowest == end() || less_than(it->first, lowest->first)) {
                lowest = it;
            }
        }
        return lowest;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::lowest().
Referenced by fl::FixedMap< Key, Value, N >::lowest(), and fl::FixedMap< Key, Value, N >::lowest().
lowest() [2/2]
template<typename Key , typename Value , size_t N> template<typename Less > const_iterator fl::FixedMap< Key, Value, N >::lowest (Less less_than = Less()) const inline
Definition at line 84 of file map.h.
{
        const_iterator lowest = end();
        for (const_iterator it = begin(); it != end(); ++it) {
            if (lowest == end() || less_than(it->first, lowest->first)) {
                lowest = it;
            }
        }
        return lowest;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::lowest().
next()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::next (const Key & key, Key * next_key, bool allow_rollover = false) const inline
Definition at line 194 of file map.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            ++it;
            if (it != end()) {
                *next_key = it->first;
                return true;
            } else if (allow_rollover && !empty()) {
                *next_key = begin()->first;
                return true;
            }
        }
        return false;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::empty(), fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::find().
Referenced by fl::FxEngine::nextFx(), and fl::FxEngine::removeFx().
operator[]() [1/2]
template<typename Key , typename Value , size_t N> Value & fl::FixedMap< Key, Value, N >::operator[] (const Key & key) inline
Definition at line 176 of file map.h.
{
        iterator it = find(key);
        if (it != end()) {
            return it->second;
        }
        data.push_back(PairKV(key, Value()));
        return data.back().second;
    }
References fl::FixedVector< T, N >::back(), fl::FixedMap< Key, Value, N >::data, fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::find(), fl::FixedVector< T, N >::push_back(), and fl::Pair< Key, Value >::second.
operator[]() [2/2]
template<typename Key , typename Value , size_t N> const Value & fl::FixedMap< Key, Value, N >::operator[] (const Key & key) const inline
Definition at line 185 of file map.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            return it->second;
        }
        static Value default_value;
        return default_value;
    }
References fl::FixedMap< Key, Value, N >::end(), and fl::FixedMap< Key, Value, N >::find().
prev()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::prev (const Key & key, Key * prev_key, bool allow_rollover = false) const inline
Definition at line 209 of file map.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            if (it != begin()) {
                --it;
                *prev_key = it->first;
                return true;
            } else if (allow_rollover && !empty()) {
                *prev_key = data[data.size() - 1].first;
                return true;
            }
        }
        return false;
    }
References fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::data, fl::FixedMap< Key, Value, N >::empty(), fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::find(), and fl::FixedVector< T, N >::size().
size()
template<typename Key , typename Value , size_t N> size_t fl::FixedMap< Key, Value, N >::size () const inline constexpr
Definition at line 226 of file map.h.
{
        return data.size();
    }
References fl::FixedMap< Key, Value, N >::data, and fl::FixedVector< T, N >::size().
Referenced by fl::ScreenMap::ParseJson(), and setup().
update()
template<typename Key , typename Value , size_t N> bool fl::FixedMap< Key, Value, N >::update (const Key & key, const Value & value, bool insert_if_missing = true) inline
Definition at line 165 of file map.h.
{
        iterator it = find(key);
        if (it != end()) {
            it->second = value;
            return true;
        } else if (insert_if_missing) {
            return insert(key, value).first;
        }
        return false;
    }
References fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::find(), and fl::FixedMap< Key, Value, N >::insert().
Member Data Documentation
data
template<typename Key , typename Value , size_t N> VectorType fl::FixedMap< Key, Value, N >::data private
Definition at line 252 of file map.h.
Referenced by fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::begin(), fl::FixedMap< Key, Value, N >::clear(), fl::FixedMap< Key, Value, N >::empty(), fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::end(), fl::FixedMap< Key, Value, N >::insert(), fl::FixedMap< Key, Value, N >::operator[](), fl::FixedMap< Key, Value, N >::prev(), and fl::FixedMap< Key, Value, N >::size().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/file_system.h
/home/runner/work/FastLED/FastLED/src/fl/map.h