FastLED: /home/runner/work/FastLED/FastLED/examples/Cylon/Cylon.ino File Reference
Cylon.ino File Reference
Detailed Description
An animation that moves a single LED back and forth (Larson Scanner effect)
An animation that moves a single LED back and forth (Larson Scanner effect) using the fx library cylon.
Definition in file Cylon.ino.
#include <FastLED.h>
Macros
#define CLOCK_PIN 13
#define DATA_PIN 2
#define NUM_LEDS 64
Functions
void fadeall ()
void loop ()
void setup ()
Variables
CRGB leds [NUM_LEDS]
Macro Definition Documentation
CLOCK_PIN
#define CLOCK_PIN 13
Definition at line 16 of file Cylon.ino.
DATA_PIN
#define DATA_PIN 2
Definition at line 15 of file Cylon.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 64
Definition at line 10 of file Cylon.ino.
Referenced by fadeall(), loop(), and setup().
Function Documentation
fadeall()
void fadeall ()
Examples
Cylon.ino.
Definition at line 28 of file Cylon.ino.
{ for(int i = 0; i < NUM_LEDS; i++) { leds[i].nscale8(250); } }
References leds, CRGB::nscale8(), and NUM_LEDS.
Referenced by loop().
loop()
void loop ()
Definition at line 30 of file Cylon.ino.
            {
    static uint8_t hue = 0;
    Serial.print("x");
    // First slide the led in one direction
    for(int i = 0; i < NUM_LEDS; i++) {
        // Set the i'th led to red
        leds[i] = CHSV(hue++, 255, 255);
        // Show the leds
        FastLED.show();
        // now that we've shown the leds, reset the i'th led to black
        // leds[i] = CRGB::Black;
        fadeall();
        // Wait a little bit before we loop around and do it again
        delay(10);
    }
    Serial.print("x");
    // Now go in the other direction.
    for(int i = (NUM_LEDS)-1; i >= 0; i--) {
        // Set the i'th led to red
        leds[i] = CHSV(hue++, 255, 255);
        // Show the leds
        FastLED.show();
        // now that we've shown the leds, reset the i'th led to black
        // leds[i] = CRGB::Black;
        fadeall();
        // Wait a little bit before we loop around and do it again
        delay(10);
    }
}
References fadeall(), FastLED, leds, NUM_LEDS, and CFastLED::show().
setup()
void setup ()
Definition at line 21 of file Cylon.ino.
             {
    Serial.begin(57600);
    Serial.println("resetting");
    FastLED.addLeds<WS2812,DATA_PIN,RGB>(leds,NUM_LEDS);
    FastLED.setBrightness(84);
}
References CFastLED::addLeds(), DATA_PIN, FastLED, leds, NUM_LEDS, RGB, and CFastLED::setBrightness().
Variable Documentation
leds
CRGB leds[NUM_LEDS]
Definition at line 19 of file Cylon.ino.
Referenced by fadeall(), loop(), and setup().