FastLED: fl::DigitalPin Class Reference
fl::DigitalPin Class Reference
Detailed Description
Definition at line 19 of file digital_pin.h.
#include <digital_pin.h>
Public Types
enum Mode { kInput = 0 , kOutput }
Public Member Functions
DigitalPin (const DigitalPin &other)
DigitalPin (DigitalPin &&other)=delete
DigitalPin (int pin)
~DigitalPin ()
bool high () const
DigitalPin & operator= (const DigitalPin &other)
void setPinMode (Mode mode)
void write (bool is_high)
Private Attributes
DigitalPinImplPtr mImpl
Member Enumeration Documentation
Mode
enum fl::DigitalPin::Mode
Enumerator
kInput
kOutput
Definition at line 21 of file digital_pin.h.
              {
        kInput = 0,
        kOutput,
        // the fallback mechanism does not support pullups or pulldowns, so we don't either yet.
        // TODO: Add these for the fallback mechanism.
        // kInputPullup,
        // kInputPulldown,
    };
Constructor & Destructor Documentation
DigitalPin() [1/3]
fl::DigitalPin::DigitalPin (int pin)
Definition at line 80 of file digital_pin.cpp.
{
    mImpl = DigitalPinImplPtr::New(DigitalPin);
}
References mImpl.
~DigitalPin()
fl::DigitalPin::~DigitalPin () default
DigitalPin() [2/3]
fl::DigitalPin::DigitalPin (const DigitalPin & other) default
DigitalPin() [3/3]
fl::DigitalPin::DigitalPin (DigitalPin && other) delete
Member Function Documentation
high()
bool fl::DigitalPin::high () const
Definition at line 92 of file digital_pin.cpp.
{
    return mImpl->high();
}
References mImpl.
Referenced by fl::Pir::detect().
operator=()
DigitalPin & fl::DigitalPin::operator= (const DigitalPin & other) default
setPinMode()
void fl::DigitalPin::setPinMode (Mode mode)
Definition at line 88 of file digital_pin.cpp.
{
    mImpl->setPinMode(mode);
}
References mImpl, and setPinMode().
Referenced by fl::Pir::Pir(), and setPinMode().
write()
void fl::DigitalPin::write (bool is_high)
Definition at line 96 of file digital_pin.cpp.
{
    mImpl->write(is_high);
}
References mImpl.
Member Data Documentation
mImpl
DigitalPinImplPtr fl::DigitalPin::mImpl private
Definition at line 41 of file digital_pin.h.
Referenced by DigitalPin(), high(), setPinMode(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/sensors/digital_pin.h
/home/runner/work/FastLED/FastLED/src/sensors/digital_pin.cpp