FastLED: /home/runner/work/FastLED/FastLED/examples/ColorPalette/ColorPalette.ino File Reference
ColorPalette.ino File Reference
Detailed Description
Demonstrates how to use Color Palettes.
Definition in file ColorPalette.ino.
#include <FastLED.h>
Macros
#define BRIGHTNESS 64
#define COLOR_ORDER GRB
#define LED_PIN 5
#define LED_TYPE WS2811
#define NUM_LEDS 50
#define UPDATES_PER_SECOND 100
Functions
void ChangePalettePeriodically ()
void FillLEDsFromPaletteColors (uint8_t colorIndex)
void loop ()
void setup ()
void SetupBlackAndWhiteStripedPalette ()
void SetupPurpleAndGreenPalette ()
void SetupTotallyRandomPalette ()
Variables
TBlendType currentBlending
CRGBPalette16 currentPalette
CRGB leds [NUM_LEDS]
CRGBPalette16 myRedWhiteBluePalette
const TProgmemPalette16 myRedWhiteBluePalette_p
Macro Definition Documentation
BRIGHTNESS
#define BRIGHTNESS 64
Definition at line 9 of file ColorPalette.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Examples
ColorPalette.ino, ColorTemperature.ino, DemoReel100.ino, Fire2012.ino, Fire2012WithPalette.ino, FxEngine.ino, NoisePlusPalette.ino, Pacifica.ino, Pride2015.ino, TwinkleFox.ino, and XYMatrix.ino.
Definition at line 11 of file ColorPalette.ino.
Referenced by setup().
LED_PIN
#define LED_PIN 5
Examples
ColorPalette.ino, ColorTemperature.ino, Fire2012.ino, Fire2012WithPalette.ino, FxEngine.ino, NoisePlusPalette.ino, and XYMatrix.ino.
Definition at line 7 of file ColorPalette.ino.
Referenced by setup().
LED_TYPE
#define LED_TYPE WS2811
Examples
ColorPalette.ino, DemoReel100.ino, FxEngine.ino, NoisePlusPalette.ino, Pacifica.ino, Pride2015.ino, and TwinkleFox.ino.
Definition at line 10 of file ColorPalette.ino.
Referenced by setup().
NUM_LEDS
#define NUM_LEDS 50
Definition at line 8 of file ColorPalette.ino.
UPDATES_PER_SECOND
#define UPDATES_PER_SECOND 100
Examples
ColorPalette.ino.
Definition at line 14 of file ColorPalette.ino.
Referenced by loop().
Function Documentation
ChangePalettePeriodically()
void ChangePalettePeriodically ()
Examples
ColorPalette.ino.
Definition at line 95 of file ColorPalette.ino.
{
    uint8_t secondHand = (millis() / 1000) % 60;
    static uint8_t lastSecond = 99;
    if( lastSecond != secondHand) {
        lastSecond = secondHand;
        if( secondHand ==  0)  { currentPalette = RainbowColors_p;         currentBlending = LINEARBLEND; }
        if( secondHand == 10)  { currentPalette = RainbowStripeColors_p;   currentBlending = NOBLEND;  }
        if( secondHand == 15)  { currentPalette = RainbowStripeColors_p;   currentBlending = LINEARBLEND; }
        if( secondHand == 20)  { SetupPurpleAndGreenPalette();             currentBlending = LINEARBLEND; }
        if( secondHand == 25)  { SetupTotallyRandomPalette();              currentBlending = LINEARBLEND; }
        if( secondHand == 30)  { SetupBlackAndWhiteStripedPalette();       currentBlending = NOBLEND; }
        if( secondHand == 35)  { SetupBlackAndWhiteStripedPalette();       currentBlending = LINEARBLEND; }
        if( secondHand == 40)  { currentPalette = CloudColors_p;           currentBlending = LINEARBLEND; }
        if( secondHand == 45)  { currentPalette = PartyColors_p;           currentBlending = LINEARBLEND; }
        if( secondHand == 50)  { currentPalette = myRedWhiteBluePalette_p; currentBlending = NOBLEND;  }
        if( secondHand == 55)  { currentPalette = myRedWhiteBluePalette_p; currentBlending = LINEARBLEND; }
    }
}
References CloudColors_p, currentBlending, currentPalette, LINEARBLEND, myRedWhiteBluePalette_p, NOBLEND, PartyColors_p, RainbowColors_p, RainbowStripeColors_p, SetupBlackAndWhiteStripedPalette(), SetupPurpleAndGreenPalette(), and SetupTotallyRandomPalette().
Referenced by loop().
FillLEDsFromPaletteColors()
void FillLEDsFromPaletteColors (uint8_t colorIndex)
Examples
ColorPalette.ino.
Definition at line 76 of file ColorPalette.ino.
{
    uint8_t brightness = 255;
    for( int i = 0; i < NUM_LEDS; ++i) {
        leds[i] = ColorFromPalette( currentPalette, colorIndex, brightness, currentBlending);
        colorIndex += 3;
    }
}
References brightness, ColorFromPalette(), currentBlending, currentPalette, leds, and NUM_LEDS.
Referenced by loop().
loop()
void loop ()
Definition at line 63 of file ColorPalette.ino.
{
    ChangePalettePeriodically();
    static uint8_t startIndex = 0;
    startIndex = startIndex + 1; /* motion speed */
    FillLEDsFromPaletteColors( startIndex);
    FastLED.show();
    FastLED.delay(1000 / UPDATES_PER_SECOND);
}
References ChangePalettePeriodically(), CFastLED::delay(), FastLED, FillLEDsFromPaletteColors(), CFastLED::show(), and UPDATES_PER_SECOND.
setup()
void setup ()
Definition at line 53 of file ColorPalette.ino.
             {
    delay( 3000 ); // power-up safety delay
    FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection( TypicalLEDStrip );
    FastLED.setBrightness(  BRIGHTNESS );
    currentPalette = RainbowColors_p;
    currentBlending = LINEARBLEND;
}
References CFastLED::addLeds(), BRIGHTNESS, COLOR_ORDER, currentBlending, currentPalette, FastLED, LED_PIN, LED_TYPE, leds, LINEARBLEND, NUM_LEDS, RainbowColors_p, CFastLED::setBrightness(), and TypicalLEDStrip.
SetupBlackAndWhiteStripedPalette()
void SetupBlackAndWhiteStripedPalette ()
Examples
ColorPalette.ino, and NoisePlusPalette.ino.
Definition at line 128 of file ColorPalette.ino.
{
    // 'black out' all 16 palette entries...
    fill_solid( currentPalette, 16, CRGB::Black);
    // and set every fourth one to white.
    currentPalette[0] = CRGB::White;
    currentPalette[4] = CRGB::White;
    currentPalette[8] = CRGB::White;
    currentPalette[12] = CRGB::White;
}
References CRGB::Black, currentPalette, fill_solid(), and CRGB::White.
Referenced by ChangePaletteAndSettingsPeriodically(), and ChangePalettePeriodically().
SetupPurpleAndGreenPalette()
void SetupPurpleAndGreenPalette ()
Examples
ColorPalette.ino, and NoisePlusPalette.ino.
Definition at line 141 of file ColorPalette.ino.
{
    CRGB purple = CHSV( HUE_PURPLE, 255, 255);
    CRGB green  = CHSV( HUE_GREEN, 255, 255);
    CRGB black  = CRGB::Black;
    currentPalette = CRGBPalette16(
                                   green,  green,  black,  black,
                                   purple, purple, black,  black,
                                   green,  green,  black,  black,
                                   purple, purple, black,  black );
}
References CRGB::Black, currentPalette, HUE_GREEN, and HUE_PURPLE.
Referenced by ChangePaletteAndSettingsPeriodically(), and ChangePalettePeriodically().
SetupTotallyRandomPalette()
void SetupTotallyRandomPalette ()
Examples
ColorPalette.ino.
Definition at line 117 of file ColorPalette.ino.
{
    for( int i = 0; i < 16; ++i) {
        currentPalette[i] = CHSV( random8(), 255, random8());
    }
}
References currentPalette, and random8().
Referenced by ChangePalettePeriodically().
Variable Documentation
currentBlending
TBlendType currentBlending
Examples
ColorPalette.ino.
Definition at line 36 of file ColorPalette.ino.
Referenced by ChangePalettePeriodically(), FillLEDsFromPaletteColors(), and setup().
currentPalette
CRGBPalette16 currentPalette
Examples
ColorPalette.ino, and NoisePlusPalette.ino.
Definition at line 35 of file ColorPalette.ino.
Referenced by ChangePaletteAndSettingsPeriodically(), ChangePalettePeriodically(), FillLEDsFromPaletteColors(), mapNoiseToLEDsUsingPalette(), setup(), SetupBlackAndWhiteStripedPalette(), SetupPurpleAndGreenPalette(), SetupRandomPalette(), and SetupTotallyRandomPalette().
leds
CRGB leds[NUM_LEDS]
Definition at line 12 of file ColorPalette.ino.
myRedWhiteBluePalette
CRGBPalette16 myRedWhiteBluePalette extern
Examples
ColorPalette.ino.
myRedWhiteBluePalette_p
const TProgmemPalette16 myRedWhiteBluePalette_p
Initial value:
=
{
    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black,
    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black,
    CRGB::Red,
    CRGB::Red,
    CRGB::Gray,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Blue,
    CRGB::Black,
    CRGB::Black
}
Examples
ColorPalette.ino.
Definition at line 159 of file ColorPalette.ino.
{
    CRGB::Red,
    CRGB::Gray, // 'white' is too bright compared to red and blue
    CRGB::Blue,
    CRGB::Black,
    CRGB::Red,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Black,
    CRGB::Red,
    CRGB::Red,
    CRGB::Gray,
    CRGB::Gray,
    CRGB::Blue,
    CRGB::Blue,
    CRGB::Black,
    CRGB::Black
};
Referenced by ChangePalettePeriodically().