FastLED: fl::FileSystem Class Reference
fl::FileSystem Class Reference
Detailed Description
Definition at line 41 of file file_system.h.
#include <file_system.h>
Public Member Functions
FileSystem ()
bool begin (FsImplPtr platform_filesystem)
bool beginSd (int cs_pin)
void close (FileHandlePtr file)
void end ()
FileHandlePtr openRead (const char *path)
Video openVideo (const char *path, size_t pixelsPerFrame, float fps=30.0f, size_t nFrameHistory=0)
bool readJson (const char *path, JsonDocument *doc)
bool readScreenMap (const char *path, const char *name, ScreenMap *out, Str *error=nullptr)
bool readScreenMaps (const char *path, FixedMap< Str, ScreenMap, 16 > *out, Str *error=nullptr)
bool readText (const char *path, Str *out)
Private Attributes
FsImplPtr mFs
Constructor & Destructor Documentation
FileSystem()
fl::FileSystem::FileSystem ()
Definition at line 96 of file file_system.cpp.
: mFs() {}
Member Function Documentation
begin()
bool fl::FileSystem::begin (FsImplPtr platform_filesystem)
Definition at line 85 of file file_system.cpp.
{
    mFs = platform_filesystem;
    if (!mFs) {
        return false;
    }
    mFs->begin();
    return true;
}
References mFs.
beginSd()
bool fl::FileSystem::beginSd (int cs_pin)
Definition at line 76 of file file_system.cpp.
{
    mFs = make_sdcard_filesystem(cs_pin);
    if (!mFs) {
        return false;
    }
    mFs->begin();
    return true;
}
References fl::make_sdcard_filesystem(), and mFs.
Referenced by setup().
close()
void fl::FileSystem::close (FileHandlePtr file)
Definition at line 153 of file file_system.cpp.
{ mFs->close(file); }
References mFs.
end()
void fl::FileSystem::end ()
Definition at line 99 of file file_system.cpp.
                     {
    if (mFs) {
        mFs->end();
    }
}
References mFs.
openRead()
FileHandlePtr fl::FileSystem::openRead (const char * path)
Definition at line 155 of file file_system.cpp.
{ return mFs->openRead(path); }
References mFs.
Referenced by openVideo(), and readText().
openVideo()
Video fl::FileSystem::openVideo (const char * path, size_t pixelsPerFrame, float fps = 30.0f, size_t nFrameHistory = 0)
Definition at line 156 of file file_system.cpp.
{
    Video video(pixelsPerFrame, fps, nFrameHistory);
    FileHandlePtr file = openRead(path);
    if (!file) {
        video.setError(fl::Str("Could not open file: ").append(path));
        return video;
    }
    video.begin(file);
    return video;
}
References openRead(), and video.
Referenced by setup().
readJson()
bool fl::FileSystem::readJson (const char * path, JsonDocument * doc)
Definition at line 105 of file file_system.cpp.
{
    Str text;
    if (!readText(path, &text)) {
        return false;
    }
    return parseJson(text.c_str(), doc);
}
References fl::StrN< SIZE >::c_str(), fl::parseJson(), and readText().
readScreenMap()
bool fl::FileSystem::readScreenMap (const char * path, const char * name, ScreenMap * out, Str * error = nullptr)
Definition at line 133 of file file_system.cpp.
{
    Str text;
    if (!readText(path, &text)) {
        FASTLED_WARN("Failed to read file: " << path);
        if (error) {
            *error = "Failed to read file: ";
            error->append(path);
        }
        return false;
    }
    Str err;
    bool ok = ScreenMap::ParseJson(text.c_str(), name, out, &err);
    if (!ok) {
        FASTLED_WARN("Failed to parse screen map: " << err.c_str());
        *error = err;
        return false;
    }
    return true;
}
References fl::Str::append(), fl::StrN< SIZE >::c_str(), FASTLED_WARN, fl::ScreenMap::ParseJson(), and readText().
Referenced by setup().
readScreenMaps()
bool fl::FileSystem::readScreenMaps (const char * path, FixedMap< Str, ScreenMap, 16 > * out, Str * error = nullptr)
Definition at line 113 of file file_system.cpp.
{
    Str text;
    if (!readText(path, &text)) {
        FASTLED_WARN("Failed to read file: " << path);
        if (error) {
            *error = "Failed to read file: ";
            error->append(path);
        }
        return false;
    }
    Str err;
    bool ok = ScreenMap::ParseJson(text.c_str(), out, &err);
    if (!ok) {
        FASTLED_WARN("Failed to parse screen map: " << err.c_str());
        *error = err;
        return false;
    }
    return true;
}
References fl::Str::append(), fl::StrN< SIZE >::c_str(), FASTLED_WARN, fl::ScreenMap::ParseJson(), and readText().
readText()
bool fl::FileSystem::readText (const char * path, fl::Str * out)
Definition at line 167 of file file_system.cpp.
{
    FileHandlePtr file = openRead(path);
    if (!file) {
        FASTLED_WARN("Failed to open file: " << path);
        return false;
    }
    size_t size = file->size();
    out->reserve(size + out->size());
    bool wrote = false;
    while (file->available()) {
        uint8_t buf[64];
        size_t n = file->read(buf, sizeof(buf));
        // out->append(buf, n);
        out->append((const char*)buf, n);
        wrote = true;
    }
    file->close();
    FASTLED_DBG_IF(!wrote, "Failed to write any data to the output string.");
    return wrote;
}
References fl::Str::append(), FASTLED_DBG_IF, FASTLED_WARN, openRead(), fl::StrN< SIZE >::reserve(), and fl::StrN< SIZE >::size().
Referenced by readJson(), readScreenMap(), and readScreenMaps().
Member Data Documentation
mFs
FsImplPtr fl::FileSystem::mFs private
Definition at line 58 of file file_system.h.
Referenced by begin(), beginSd(), close(), end(), and openRead().
The documentation for this class was generated from the following files:
/home/runner/work/FastLED/FastLED/src/fl/file_system.h
/home/runner/work/FastLED/FastLED/src/fl/file_system.cpp