FastLED: Power Management Functions
Power Management Functions
Detailed Description
Functions to limit the amount of power used by FastLED
Power Control Setup Functions
Functions to initialize the power control system
void set_max_power_in_volts_and_milliamps (uint8_t volts, uint32_t milliamps)
Set the maximum power used in milliamps for a given voltage.
void set_max_power_in_milliwatts (uint32_t powerInmW)
Set the maximum power used in watts.
void set_max_power_indicator_LED (uint8_t pinNumber)
Select a pin with an LED that will be flashed to indicate that power management is pulling down the brightness.
Power Control 'show()' and 'delay()' Functions
Power-limiting replacements of show() and delay().
These are drop-in replacements for CFastLED::show() and CFastLED::delay(). In order to use these, you have to actually replace your calls to CFastLED::show() and CFastLED::delay() with these two functions.
Deprecated
These functions are deprecated as of 6ebcb64, circa 2015. Do not use them for new programs.
void show_at_max_brightness_for_power ()
Similar to CFastLED::show(), but pre-adjusts brightness to keep below the power threshold.
void delay_at_max_brightness_for_power (uint16_t ms)
Similar to CFastLED::delay(), but pre-adjusts brightness to keep below the power threshold.
Power Control Internal Helper Functions
Internal helper functions for power control.
uint32_t calculate_unscaled_power_mW (const CRGB *ledbuffer, uint16_t numLeds)
Determines how many milliwatts the current LED data would draw at max brightness (255)
uint8_t calculate_max_brightness_for_power_mW (const CRGB *ledbuffer, uint16_t numLeds, uint8_t target_brightness, uint32_t max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for a given set of LEDs.
uint8_t calculate_max_brightness_for_power_vmA (const CRGB *ledbuffer, uint16_t numLeds, uint8_t target_brightness, uint32_t max_power_V, uint32_t max_power_mA)
Determines the highest brightness level you can use and still stay under the specified power budget for a given set of LEDs.
uint8_t calculate_max_brightness_for_power_mW (uint8_t target_brightness, uint32_t max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for all sets of LEDs.
Function Documentation
calculate_max_brightness_for_power_mW() [1/2]
uint8_t calculate_max_brightness_for_power_mW (const CRGB * ledbuffer, uint16_t numLeds, uint8_t target_brightness, uint32_t max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for a given set of LEDs.
Parameters
ledbuffer the LED data to check
numLeds the number of LEDs in the data array
target_brightness the brightness you'd ideally like to use
max_power_mW the max power draw desired, in milliwatts
Returns
a limited brightness value. No higher than the target brightness, but may be lower depending on the power limit.
Definition at line 95 of file power_mgt.cpp.
{
    uint32_t total_mW = calculate_unscaled_power_mW( ledbuffer, numLeds);
    uint32_t requested_power_mW = ((uint32_t)total_mW * target_brightness) / 256;
    uint8_t recommended_brightness = target_brightness;
    if(requested_power_mW > max_power_mW) {
        recommended_brightness = (uint32_t)((uint8_t)(target_brightness) * (uint32_t)(max_power_mW)) / ((uint32_t)(requested_power_mW));
    }
    return recommended_brightness;
}
References calculate_unscaled_power_mW().
Referenced by calculate_max_brightness_for_power_vmA(), and CFastLED::setMaxPowerInMilliWatts().
calculate_max_brightness_for_power_mW() [2/2]
uint8_t calculate_max_brightness_for_power_mW (uint8_t target_brightness, uint32_t max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for all sets of LEDs.
Unlike the other internal power functions which use a pointer to a specific set of LED data, this function uses the CFastLED linked list of LED controllers and their attached data.
Parameters
target_brightness the brightness you'd ideally like to use
max_power_mW the max power draw desired, in milliwatts
Returns
a limited brightness value. No higher than the target brightness, but may be lower depending on the power limit.
Definition at line 111 of file power_mgt.cpp.
{
    uint32_t total_mW = gMCU_mW;
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        total_mW += calculate_unscaled_power_mW( pCur->leds(), pCur->size());
        pCur = pCur->next();
    }
#if POWER_DEBUG_PRINT == 1
    Serial.print("power demand at full brightness mW = ");
    Serial.println( total_mW);
#endif
    uint32_t requested_power_mW = ((uint32_t)total_mW * target_brightness) / 256;
#if POWER_DEBUG_PRINT == 1
    if( target_brightness != 255 ) {
        Serial.print("power demand at scaled brightness mW = ");
        Serial.println( requested_power_mW);
    }
    Serial.print("power limit mW = ");
    Serial.println( max_power_mW);
#endif
    if( requested_power_mW < max_power_mW) {
#if POWER_LED > 0
        if( gMaxPowerIndicatorLEDPinNumber ) {
            Pin(gMaxPowerIndicatorLEDPinNumber).lo(); // turn the LED off
        }
#endif
#if POWER_DEBUG_PRINT == 1
        Serial.print("demand is under the limit");
#endif
        return target_brightness;
    }
    uint8_t recommended_brightness = (uint32_t)((uint8_t)(target_brightness) * (uint32_t)(max_power_mW)) / ((uint32_t)(requested_power_mW));
#if POWER_DEBUG_PRINT == 1
    Serial.print("recommended brightness # = ");
    Serial.println( recommended_brightness);
    uint32_t resultant_power_mW = (total_mW * recommended_brightness) / 256;
    Serial.print("resultant power demand mW = ");
    Serial.println( resultant_power_mW);
    Serial.println();
#endif
#if POWER_LED > 0
    if( gMaxPowerIndicatorLEDPinNumber ) {
        Pin(gMaxPowerIndicatorLEDPinNumber).hi(); // turn the LED on
    }
#endif
    return recommended_brightness;
}
References calculate_unscaled_power_mW(), gMaxPowerIndicatorLEDPinNumber, gMCU_mW, CLEDController::head(), Pin::hi(), CLEDController::leds(), Pin::lo(), CLEDController::next(), and CLEDController::size().
calculate_max_brightness_for_power_vmA()
uint8_t calculate_max_brightness_for_power_vmA (const CRGB * ledbuffer, uint16_t numLeds, uint8_t target_brightness, uint32_t max_power_V, uint32_t max_power_mA)
Determines the highest brightness level you can use and still stay under the specified power budget for a given set of LEDs.
Parameters
ledbuffer the LED data to check
numLeds the number of LEDs in the data array
target_brightness the brightness you'd ideally like to use
max_power_V the max power in volts
max_power_mA the max power in milliamps
Returns
a limited brightness value. No higher than the target brightness, but may be lower depending on the power limit.
Definition at line 91 of file power_mgt.cpp.
{
    return calculate_max_brightness_for_power_mW(ledbuffer, numLeds, target_brightness, max_power_V * max_power_mA);
}
References calculate_max_brightness_for_power_mW().
calculate_unscaled_power_mW()
uint32_t calculate_unscaled_power_mW (const CRGB * ledbuffer, uint16_t numLeds)
Determines how many milliwatts the current LED data would draw at max brightness (255)
Parameters
ledbuffer the LED data to check
numLeds the number of LEDs in the data array
Returns
the number of milliwatts the LED data would consume at max brightness
Definition at line 61 of file power_mgt.cpp.
{
    uint32_t red32 = 0, green32 = 0, blue32 = 0;
    const CRGB* firstled = &(ledbuffer[0]);
    uint8_t* p = (uint8_t*)(firstled);
    uint16_t count = numLeds;
    // This loop might benefit from an AVR assembly version -MEK
    while( count) {
        red32   += *p++;
        green32 += *p++;
        blue32  += *p++;
        --count;
    }
    red32   *= gRed_mW;
    green32 *= gGreen_mW;
    blue32  *= gBlue_mW;
    red32   >>= 8;
    green32 >>= 8;
    blue32  >>= 8;
    uint32_t total = red32 + green32 + blue32 + (gDark_mW * numLeds);
    return total;
}
References gBlue_mW, gDark_mW, gGreen_mW, gRed_mW, and p.
Referenced by calculate_max_brightness_for_power_mW(), and calculate_max_brightness_for_power_mW().
delay_at_max_brightness_for_power()
void delay_at_max_brightness_for_power (uint16_t ms)
Similar to CFastLED::delay(), but pre-adjusts brightness to keep below the power threshold.
Deprecated
This is now a part of CFastLED::delay()
Definition at line 191 of file power_mgt.cpp.
{
    FastLED.delay(ms);
}
References CFastLED::delay(), and FastLED.
set_max_power_in_milliwatts()
void set_max_power_in_milliwatts (uint32_t powerInmW)
Set the maximum power used in watts.
Deprecated
Use CFastLED::setMaxPowerInMilliWatts
Definition at line 180 of file power_mgt.cpp.
{
    FastLED.setMaxPowerInMilliWatts(powerInmW);
}
References FastLED, and CFastLED::setMaxPowerInMilliWatts().
set_max_power_in_volts_and_milliamps()
void set_max_power_in_volts_and_milliamps (uint8_t volts, uint32_t milliamps)
Set the maximum power used in milliamps for a given voltage.
Deprecated
Use CFastLED::setMaxPowerInVoltsAndMilliamps()
Definition at line 175 of file power_mgt.cpp.
{
    FastLED.setMaxPowerInVoltsAndMilliamps(volts, milliamps);
}
References FastLED, and CFastLED::setMaxPowerInVoltsAndMilliamps().
set_max_power_indicator_LED()
void set_max_power_indicator_LED (uint8_t pinNumber)
Select a pin with an LED that will be flashed to indicate that power management is pulling down the brightness.
Parameters
pinNumber output pin. Zero is "no indicator LED".
Definition at line 170 of file power_mgt.cpp.
{
    gMaxPowerIndicatorLEDPinNumber = pinNumber;
}
References gMaxPowerIndicatorLEDPinNumber.
show_at_max_brightness_for_power()
void show_at_max_brightness_for_power ()
Similar to CFastLED::show(), but pre-adjusts brightness to keep below the power threshold.
Deprecated
This is now a part of CFastLED::show()
Definition at line 185 of file power_mgt.cpp.
{
    // power management usage is now in FastLED.show, no need for this function
    FastLED.show();
}
References FastLED, and CFastLED::show().