FastLED: /home/runner/work/FastLED/FastLED/examples/Ports/PJRCSpectrumAnalyzer/PJRCSpectrumAnalyzer.ino File Reference
PJRCSpectrumAnalyzer.ino File Reference
Detailed Description
Creates an impressive LED light show to music input on the Teensy.
Definition in file PJRCSpectrumAnalyzer.ino.
#include <OctoWS2811.h>
#include <FastLED.h>
#include <Audio.h>
#include <Wire.h>
#include <SD.h>
#include <SPI.h>
Macros
#define USE_OCTOWS2811
Functions
AudioInputAnalog adc1 (A3)
void computeVerticalLevels ()
void loop ()
AudioConnection patchCord1 (adc1, fft)
void setup ()
unsigned int xy (unsigned int x, unsigned int y)
Variables
const float dynamicRange = 40.0
AudioAnalyzeFFT1024 fft
int frequencyBinsHorizontal [matrix_width]
CRGB leds [matrix_width *matrix_height]
const float linearBlend = 0.3
const unsigned int matrix_height = 32
const unsigned int matrix_width = 60
const float maxLevel = 0.5
const unsigned int myColor = 0x400020
float thresholdVertical [matrix_height]
Macro Definition Documentation
USE_OCTOWS2811
#define USE_OCTOWS2811
Definition at line 18 of file PJRCSpectrumAnalyzer.ino.
Function Documentation
adc1()
AudioInputAnalog adc1 (A3)
Examples
PJRCSpectrumAnalyzer.ino.
computeVerticalLevels()
void computeVerticalLevels ()
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 128 of file PJRCSpectrumAnalyzer.ino.
{
  unsigned int y;
  float n, logLevel, linearLevel;
  for (y=0; y < matrix_height; y++) {
    n = (float)y / (float)(matrix_height - 1);
    logLevel = pow10f(n * -1.0 * (dynamicRange / 20.0));
    linearLevel = 1.0 - n;
    linearLevel = linearLevel * linearBlend;
    logLevel = logLevel * (1.0 - linearBlend);
    thresholdVertical[y] = (logLevel + linearLevel) * maxLevel;
  }
}
References dynamicRange, linearBlend, matrix_height, maxLevel, thresholdVertical, and y.
Referenced by setup().
loop()
void loop ()
Definition at line 90 of file PJRCSpectrumAnalyzer.ino.
            {
  unsigned int x, y, freqBin;
  float level;
  if (fft.available()) {
    // freqBin counts which FFT frequency data has been used,
    // starting at low frequency
    freqBin = 0;
    for (x=0; x < matrix_width; x++) {
      // get the volume for each horizontal pixel position
      level = fft.read(freqBin, freqBin + frequencyBinsHorizontal[x] - 1);
      // uncomment to see the spectrum in Arduino's Serial Monitor
      // Serial.print(level);
      // Serial.print("  ");
      for (y=0; y < matrix_height; y++) {
        // for each vertical pixel, check if above the threshold
        // and turn the LED on or off
        if (level >= thresholdVertical[y]) {
          leds[xy(x,y)] = CRGB(myColor);
        } else {
          leds[xy(x,y)] = CRGB::Black;
        }
      }
      // increment the frequency bin count, so we display
      // low to higher frequency from left to right
      freqBin = freqBin + frequencyBinsHorizontal[x];
    }
    // after all pixels set, show them all at the same instant
    FastLED.show();
    // Serial.println();
  }
}
References CRGB::Black, FastLED, fft, frequencyBinsHorizontal, leds, matrix_height, matrix_width, myColor, CFastLED::show(), thresholdVertical, x, xy(), and y.
patchCord1()
AudioConnection patchCord1 (adc1 , fft)
Examples
PJRCSpectrumAnalyzer.ino.
setup()
void setup ()
Definition at line 65 of file PJRCSpectrumAnalyzer.ino.
             {
  // the audio library needs to be given memory to start working
  AudioMemory(12);
  // compute the vertical thresholds before starting
  computeVerticalLevels();
  // turn on the display
  FastLED.addLeds<OCTOWS2811>(leds,(matrix_width * matrix_height) / 8);
}
References CFastLED::addLeds(), computeVerticalLevels(), FastLED, leds, matrix_height, matrix_width, and OCTOWS2811.
xy()
unsigned int xy (unsigned int x, unsigned int y)
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 79 of file PJRCSpectrumAnalyzer.ino.
{
  if ((y & 1) == 0) {
    // even numbered rows (0, 2, 4...) are left to right
    return y * matrix_width + x;
  } else {
    // odd numbered rows (1, 3, 5...) are right to left
    return y * matrix_width + matrix_width - 1 - x;
  }
}
References matrix_width, x, and y.
Referenced by blur2d(), anonymous_namespace{LedRopeTCL.cpp}::init_screenmap(), loop(), makeScreenMap(), fl::ScreenMap::toJson(), and wu_water().
Variable Documentation
dynamicRange
const float dynamicRange = 40.0
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 33 of file PJRCSpectrumAnalyzer.ino.
Referenced by computeVerticalLevels().
fft
AudioAnalyzeFFT1024 fft
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 40 of file PJRCSpectrumAnalyzer.ino.
Referenced by loop().
frequencyBinsHorizontal
int frequencyBinsHorizontal[matrix_width]
Initial value:
= {
   1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
   2,  2,  2,  2,  2,  2,  2,  2,  2,  3,
   3,  3,  3,  3,  4,  4,  4,  4,  4,  5,
   5,  5,  6,  6,  6,  7,  7,  7,  8,  8,
   9,  9, 10, 10, 11, 12, 12, 13, 14, 15,
  15, 16, 17, 18, 19, 20, 22, 23, 24, 25
}
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 53 of file PJRCSpectrumAnalyzer.ino.
{
   1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
   2,  2,  2,  2,  2,  2,  2,  2,  2,  3,
   3,  3,  3,  3,  4,  4,  4,  4,  4,  5,
   5,  5,  6,  6,  6,  7,  7,  7,  8,  8,
   9,  9, 10, 10, 11, 12, 12, 13, 14, 15,
  15, 16, 17, 18, 19, 20, 22, 23, 24, 25
};
Referenced by loop().
leds
CRGB leds[matrix_width *matrix_height]
Definition at line 36 of file PJRCSpectrumAnalyzer.ino.
linearBlend
const float linearBlend = 0.3
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 34 of file PJRCSpectrumAnalyzer.ino.
Referenced by computeVerticalLevels().
matrix_height
const unsigned int matrix_height = 32
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 28 of file PJRCSpectrumAnalyzer.ino.
Referenced by computeVerticalLevels(), loop(), and setup().
matrix_width
const unsigned int matrix_width = 60
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 27 of file PJRCSpectrumAnalyzer.ino.
Referenced by loop(), setup(), and xy().
maxLevel
const float maxLevel = 0.5
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 32 of file PJRCSpectrumAnalyzer.ino.
Referenced by computeVerticalLevels().
myColor
const unsigned int myColor = 0x400020
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 29 of file PJRCSpectrumAnalyzer.ino.
Referenced by loop().
thresholdVertical
float thresholdVertical[matrix_height]
Examples
PJRCSpectrumAnalyzer.ino.
Definition at line 47 of file PJRCSpectrumAnalyzer.ino.
Referenced by computeVerticalLevels(), and loop().