FastLED: ToggleButton Class Reference
ToggleButton Class Reference
Detailed Description
Definition at line 10 of file buttons.h.
#include <buttons.h>
Public Member Functions
ToggleButton (int pin)
bool Read ()
void Update (uint32_t time_now)
Private Member Functions
bool Read_Internal ()
Private Attributes
bool changed_
uint32_t debounce_timestamp_
bool on_
int pin_
Constructor & Destructor Documentation
ToggleButton()
ToggleButton::ToggleButton (int pin) inline
Definition at line 12 of file buttons.h.
                        : pin_(pin), on_(false), debounce_timestamp_(0), changed_(false) {
    pinMode(pin_, OUTPUT);
    digitalWrite(pin_, LOW);
    delay(1);
  }
References pin_.
Member Function Documentation
Read()
bool ToggleButton::Read () inline
Definition at line 19 of file buttons.h.
              {
    Update(millis());
    return changed_;
  }
References changed_, and Update().
Read_Internal()
bool ToggleButton::Read_Internal () inline private
Definition at line 45 of file buttons.h.
                       {
    // Toggle the pin back to INPUT and take a reading.
    pinMode(pin_, INPUT);
    bool on = (digitalRead(pin_) == HIGH);
    // Switch the pin back to output so that we can enable the
    // pulldown resister.
    pinMode(pin_, OUTPUT);
    digitalWrite(pin_, LOW);
    return on;
  }
References pin_.
Referenced by Update().
Update()
void ToggleButton::Update (uint32_t time_now) inline
Definition at line 24 of file buttons.h.
{
    if ((time_now - debounce_timestamp_) < 150) {
      changed_ = false;
      return;
    }
    int val = Read_Internal();
    changed_ = on_ != val;
    if (changed_) {  // Has the toggle switch changed?
      on_ = val;       // Set the new toggle switch value.
      // Protect against debouncing artifacts by putting a 200ms delay from the
      // last time the value changed.
      if ((time_now - debounce_timestamp_) > 150) {
        //++curr_val_;     // ... and increment the value.
        debounce_timestamp_ = time_now;
      }
    }
  }
References changed_, debounce_timestamp_, on_, and Read_Internal().
Referenced by Read().
Member Data Documentation
changed_
bool ToggleButton::changed_ private
Definition at line 60 of file buttons.h.
Referenced by Read(), and Update().
debounce_timestamp_
uint32_t ToggleButton::debounce_timestamp_ private
Definition at line 59 of file buttons.h.
Referenced by Update().
on_
bool ToggleButton::on_ private
Definition at line 58 of file buttons.h.
Referenced by Update().
pin_
int ToggleButton::pin_ private
Definition at line 57 of file buttons.h.
Referenced by ToggleButton(), and Read_Internal().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/examples/LuminescentGrand/arduino/buttons.h