FastLED: Color Blending Functions
Color Blending Functions
Color Utility Functions
Detailed Description
Functions for blending colors together
Functions
CHSV blend (const CHSV &p1, const CHSV &p2, fract8 amountOfP2, TGradientDirectionCode directionCode=SHORTEST_HUES)
Computes a new color blended some fraction of the way between two other colors.
CHSV * blend (const CHSV *src1, const CHSV *src2, CHSV *dest, uint16_t count, fract8 amountOfsrc2, TGradientDirectionCode directionCode=SHORTEST_HUES)
Computes a new blended array of colors, each some fraction of the way between corresponding elements of two source arrays of colors.
CRGB blend (const CRGB &p1, const CRGB &p2, fract8 amountOfP2)
Computes a new color blended some fraction of the way between two other colors.
CRGB * blend (const CRGB *src1, const CRGB *src2, CRGB *dest, uint16_t count, fract8 amountOfsrc2)
Computes a new blended array of colors, each some fraction of the way between corresponding elements of two source arrays of colors.
CHSV & nblend (CHSV &existing, const CHSV &overlay, fract8 amountOfOverlay, TGradientDirectionCode directionCode=SHORTEST_HUES)
Destructively modifies one color, blending in a given fraction of an overlay color.
void nblend (CHSV *existing, const CHSV *overlay, uint16_t count, fract8 amountOfOverlay, TGradientDirectionCode directionCode=SHORTEST_HUES)
Destructively blends a given fraction of a color array into an existing color array.
CRGB & nblend (CRGB &existing, const CRGB &overlay, fract8 amountOfOverlay)
Destructively modifies one color, blending in a given fraction of an overlay color.
void nblend (CRGB *existing, const CRGB *overlay, uint16_t count, fract8 amountOfOverlay)
Destructively blends a given fraction of a color array into an existing color array.
Function Documentation
blend() [1/4]
CHSV blend (const CHSV & p1, const CHSV & p2, fract8 amountOfP2, TGradientDirectionCode directionCode = SHORTEST_HUES)
Computes a new color blended some fraction of the way between two other colors.
Parameters
p1 the first color to blend
p2 the second color to blend
amountOfP2 the fraction of p2 to blend into p1
directionCode the direction to travel around the color wheel
Definition at line 424 of file colorutils.cpp.
{
    CHSV nu(p1);
    nblend( nu, p2, amountOfP2, directionCode);
    return nu;
}
References nblend().
blend() [2/4]
CHSV * blend (const CHSV * src1, const CHSV * src2, CHSV * dest, uint16_t count, fract8 amountOfsrc2, TGradientDirectionCode directionCode = SHORTEST_HUES)
Computes a new blended array of colors, each some fraction of the way between corresponding elements of two source arrays of colors.
Useful for blending palettes.
Parameters
src1 the first array of colors to blend
src2 the second array of colors to blend
dest the destination array for the colors
count the number of LEDs to blend
amountOfsrc2 the fraction of src2 to blend into src1
directionCode the direction to travel around the color wheel
Definition at line 431 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < count; ++i) {
        dest[i] = blend(src1[i], src2[i], amountOfsrc2, directionCode);
    }
    return dest;
}
References blend().
blend() [3/4]
CRGB blend (const CRGB & p1, const CRGB & p2, fract8 amountOfP2)
Computes a new color blended some fraction of the way between two other colors.
Parameters
p1 the first color to blend
p2 the second color to blend
amountOfP2 the fraction of p2 to blend into p1
Definition at line 347 of file colorutils.cpp.
{
    CRGB nu(p1);
    nblend( nu, p2, amountOfP2);
    return nu;
}
References nblend().
Referenced by blend(), blend(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), fl::TwinkleFox::drawTwinkleFox(), drawTwinkles(), fill_2dnoise16(), fill_2dnoise8(), and MyColorFromPaletteExtended().
blend() [4/4]
CRGB * blend (const CRGB * src1, const CRGB * src2, CRGB * dest, uint16_t count, fract8 amountOfsrc2)
Computes a new blended array of colors, each some fraction of the way between corresponding elements of two source arrays of colors.
Useful for blending palettes.
Parameters
src1 the first array of colors to blend
src2 the second array of colors to blend
dest the destination array for the colors
count the number of LEDs to blend
amountOfsrc2 the fraction of src2 to blend into src1
Definition at line 354 of file colorutils.cpp.
{
    for( uint16_t i = 0; i < count; ++i) {
        dest[i] = blend(src1[i], src2[i], amountOfsrc2);
    }
    return dest;
}
References blend().
nblend() [1/4]
CHSV & nblend (CHSV & existing, const CHSV & overlay, fract8 amountOfOverlay, TGradientDirectionCode directionCode = SHORTEST_HUES)
Destructively modifies one color, blending in a given fraction of an overlay color.
Parameters
existing the color to modify
overlay the color to blend into existing
amountOfOverlay the fraction of overlay to blend into existing
directionCode the direction to travel around the color wheel
Definition at line 364 of file colorutils.cpp.
{
    if( amountOfOverlay == 0) {
        return existing;
    }
    if( amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
    fract8 amountOfKeep = 255 - amountOfOverlay;
    uint8_t huedelta8 = overlay.hue - existing.hue;
    if( directionCode == SHORTEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 > 127) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == LONGEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 < 128) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == FORWARD_HUES) {
        existing.hue = existing.hue + scale8( huedelta8, amountOfOverlay);
    }
    else /* directionCode == BACKWARD_HUES */
    {
        huedelta8 = -huedelta8;
        existing.hue = existing.hue - scale8( huedelta8, amountOfOverlay);
    }
    existing.sat   = scale8_LEAVING_R1_DIRTY( existing.sat,   amountOfKeep)
    + scale8_LEAVING_R1_DIRTY( overlay.sat,    amountOfOverlay);
    existing.val = scale8_LEAVING_R1_DIRTY( existing.val, amountOfKeep)
    + scale8_LEAVING_R1_DIRTY( overlay.val,  amountOfOverlay);
    cleanup_R1();
    return existing;
}
References BACKWARD_HUES, cleanup_R1(), FORWARD_HUES, LONGEST_HUES, scale8(), scale8_LEAVING_R1_DIRTY(), and SHORTEST_HUES.
nblend() [2/4]
void nblend (CHSV * existing, const CHSV * overlay, uint16_t count, fract8 amountOfOverlay, TGradientDirectionCode directionCode = SHORTEST_HUES)
Destructively blends a given fraction of a color array into an existing color array.
Parameters
existing the color array to modify
overlay the color array to blend into existing
count the number of colors to process
amountOfOverlay the fraction of overlay to blend into existing
directionCode the direction to travel around the color wheel
Definition at line 414 of file colorutils.cpp.
{
    if(existing == overlay) return;
    for( uint16_t i = count; i; --i) {
        nblend( *existing, *overlay, amountOfOverlay, directionCode);
        ++existing;
        ++overlay;
    }
}
References nblend().
nblend() [3/4]
CRGB & nblend (CRGB & existing, const CRGB & overlay, fract8 amountOfOverlay)
Destructively modifies one color, blending in a given fraction of an overlay color.
Parameters
existing the color to modify
overlay the color to blend into existing
amountOfOverlay the fraction of overlay to blend into existing
Definition at line 303 of file colorutils.cpp.
{
    if( amountOfOverlay == 0) {
        return existing;
    }
    if( amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
#if 0
    // Old blend method which unfortunately had some rounding errors
    fract8 amountOfKeep = 255 - amountOfOverlay;
    existing.red   = scale8_LEAVING_R1_DIRTY( existing.red,   amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.red,    amountOfOverlay);
    existing.green = scale8_LEAVING_R1_DIRTY( existing.green, amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.green,  amountOfOverlay);
    existing.blue  = scale8_LEAVING_R1_DIRTY( existing.blue,  amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.blue,   amountOfOverlay);
    cleanup_R1();
#else
    // Corrected blend method, with no loss-of-precision rounding errors
    existing.red   = blend8( existing.red,   overlay.red,   amountOfOverlay);
    existing.green = blend8( existing.green, overlay.green, amountOfOverlay);
    existing.blue  = blend8( existing.blue,  overlay.blue,  amountOfOverlay);
#endif
    return existing;
}
References blend8(), cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
Referenced by blend(), blend(), fl::Pride2015::draw(), nblend(), nblend(), and pride().
nblend() [4/4]
void nblend (CRGB * existing, const CRGB * overlay, uint16_t count, fract8 amountOfOverlay)
Destructively blends a given fraction of a color array into an existing color array.
Parameters
existing the color array to modify
overlay the color array to blend into existing
count the number of colors to process
amountOfOverlay the fraction of overlay to blend into existing
Definition at line 338 of file colorutils.cpp.
{
    for( uint16_t i = count; i; --i) {
        nblend( *existing, *overlay, amountOfOverlay);
        ++existing;
        ++overlay;
    }
}
References nblend().