FastLED: /home/runner/work/FastLED/FastLED/examples/DemoReel100/DemoReel100.ino File Reference
DemoReel100.ino File Reference
Detailed Description
FastLED "100 lines of code" demo reel, showing off some effects.
Definition in file DemoReel100.ino.
#include <FastLED.h>
Macros
#define ARRAY_SIZE(A)
#define BRIGHTNESS 96
#define COLOR_ORDER GRB
#define DATA_PIN 3
#define FRAMES_PER_SECOND 120
#define LED_TYPE WS2811
#define NUM_LEDS 64
Typedefs
typedef void(* SimplePatternList[]) ()
Functions
void addGlitter (fract8 chanceOfGlitter)
void bpm ()
void confetti ()
void juggle ()
void loop ()
void nextPattern ()
void rainbow ()
void rainbowWithGlitter ()
void setup ()
void sinelon ()
Variables
uint8_t gCurrentPatternNumber = 0
uint8_t gHue = 0
SimplePatternList gPatterns = { rainbow, rainbowWithGlitter, confetti, sinelon, juggle, bpm }
CRGB leds [NUM_LEDS]
Macro Definition Documentation
ARRAY_SIZE
#define ARRAY_SIZE (A)
Value:
(sizeof(A) / sizeof((A)[0]))
Examples
DemoReel100.ino.
Definition at line 61 of file DemoReel100.ino.
Referenced by nextPattern().
BRIGHTNESS
#define BRIGHTNESS 96
Definition at line 24 of file DemoReel100.ino.
COLOR_ORDER
#define COLOR_ORDER GRB
Definition at line 20 of file DemoReel100.ino.
DATA_PIN
#define DATA_PIN 3
Definition at line 17 of file DemoReel100.ino.
FRAMES_PER_SECOND
#define FRAMES_PER_SECOND 120
Examples
DemoReel100.ino, Fire2012.ino, and Fire2012WithPalette.ino.
Definition at line 25 of file DemoReel100.ino.
Referenced by loop().
LED_TYPE
#define LED_TYPE WS2811
Definition at line 19 of file DemoReel100.ino.
NUM_LEDS
#define NUM_LEDS 64
Definition at line 21 of file DemoReel100.ino.
Typedef Documentation
SimplePatternList
typedef void(* SimplePatternList[])()
Examples
DemoReel100.ino.
Definition at line 40 of file DemoReel100.ino.
Function Documentation
addGlitter()
void addGlitter (fract8 chanceOfGlitter)
Examples
DemoReel100.ino.
Definition at line 82 of file DemoReel100.ino.
{
  if( random8() < chanceOfGlitter) {
    leds[ random16(NUM_LEDS) ] += CRGB::White;
  }
}
References leds, NUM_LEDS, random16(), random8(), and CRGB::White.
Referenced by rainbowWithGlitter().
bpm()
void bpm ()
Examples
DemoReel100.ino.
Definition at line 105 of file DemoReel100.ino.
{
  // colored stripes pulsing at a defined Beats-Per-Minute (BPM)
  uint8_t BeatsPerMinute = 62;
  CRGBPalette16 palette = PartyColors_p;
  uint8_t beat = beatsin8( BeatsPerMinute, 64, 255);
  for( int i = 0; i < NUM_LEDS; i++) { //9948
    leds[i] = ColorFromPalette(palette, gHue+(i*2), beat-gHue+(i*10));
  }
}
References beatsin8(), ColorFromPalette(), gHue, leds, NUM_LEDS, and PartyColors_p.
Referenced by fl::DemoReel100::runPattern().
confetti()
void confetti ()
Examples
DemoReel100.ino.
Definition at line 89 of file DemoReel100.ino.
{
  // random colored speckles that blink in and fade smoothly
  fadeToBlackBy( leds, NUM_LEDS, 10);
  int pos = random16(NUM_LEDS);
  leds[pos] += CHSV( gHue + random8(64), 200, 255);
}
References fadeToBlackBy(), gHue, leds, NUM_LEDS, pos, random16(), and random8().
Referenced by fl::DemoReel100::runPattern().
juggle()
void juggle ()
Examples
DemoReel100.ino.
Definition at line 116 of file DemoReel100.ino.
              {
  // eight colored dots, weaving in and out of sync with each other
  fadeToBlackBy( leds, NUM_LEDS, 20);
  uint8_t dothue = 0;
  for( int i = 0; i < 8; i++) {
    leds[beatsin16( i+7, 0, NUM_LEDS-1 )] |= CHSV(dothue, 200, 255);
    dothue += 32;
  }
}
References beatsin16(), fadeToBlackBy(), leds, and NUM_LEDS.
Referenced by fl::DemoReel100::runPattern().
loop()
void loop ()
Definition at line 46 of file DemoReel100.ino.
{
  // Call the current pattern function once, updating the 'leds' array
  gPatterns[gCurrentPatternNumber]();
  // send the 'leds' array out to the actual LED strip
  FastLED.show();
  // insert a delay to keep the framerate modest
  FastLED.delay(1000/FRAMES_PER_SECOND);
  // do some periodic updates
  EVERY_N_MILLISECONDS( 20 ) { gHue++; } // slowly cycle the "base color" through the rainbow
  EVERY_N_SECONDS( 10 ) { nextPattern(); } // change patterns periodically
}
References CFastLED::delay(), EVERY_N_MILLISECONDS, EVERY_N_SECONDS, FastLED, FRAMES_PER_SECOND, gCurrentPatternNumber, gHue, gPatterns, nextPattern(), and CFastLED::show().
nextPattern()
void nextPattern ()
Examples
DemoReel100.ino.
Definition at line 63 of file DemoReel100.ino.
{
  // add one to the current pattern number, and wrap around at the end
  gCurrentPatternNumber = (gCurrentPatternNumber + 1) % ARRAY_SIZE( gPatterns);
}
References ARRAY_SIZE, gCurrentPatternNumber, and gPatterns.
Referenced by loop().
rainbow()
void rainbow ()
Examples
DemoReel100.ino.
Definition at line 69 of file DemoReel100.ino.
{
  // FastLED's built-in rainbow generator
  fill_rainbow( leds, NUM_LEDS, gHue, 7);
}
References fill_rainbow(), gHue, leds, and NUM_LEDS.
Referenced by fl::DemoReel100::rainbowWithGlitter(), rainbowWithGlitter(), and fl::DemoReel100::runPattern().
rainbowWithGlitter()
void rainbowWithGlitter ()
Examples
DemoReel100.ino.
Definition at line 75 of file DemoReel100.ino.
{
  // built-in FastLED rainbow, plus some random sparkly glitter
  rainbow();
  addGlitter(80);
}
References addGlitter(), and rainbow().
Referenced by fl::DemoReel100::runPattern().
setup()
void setup ()
Definition at line 27 of file DemoReel100.ino.
             {
  delay(3000); // 3 second delay for recovery
  // tell FastLED about the LED strip configuration
  FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
  //FastLED.addLeds<LED_TYPE,DATA_PIN,CLK_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
  // set master brightness control
  FastLED.setBrightness(BRIGHTNESS);
}
References CFastLED::addLeds(), BRIGHTNESS, COLOR_ORDER, DATA_PIN, FastLED, LED_TYPE, leds, NUM_LEDS, CFastLED::setBrightness(), and TypicalLEDStrip.
sinelon()
void sinelon ()
Examples
DemoReel100.ino.
Definition at line 97 of file DemoReel100.ino.
{
  // a colored dot sweeping back and forth, with fading trails
  fadeToBlackBy( leds, NUM_LEDS, 20);
  int pos = beatsin16( 13, 0, NUM_LEDS-1 );
  leds[pos] += CHSV( gHue, 255, 192);
}
References beatsin16(), fadeToBlackBy(), gHue, leds, NUM_LEDS, and pos.
Referenced by fl::DemoReel100::runPattern().
Variable Documentation
gCurrentPatternNumber
uint8_t gCurrentPatternNumber = 0
Examples
DemoReel100.ino.
Definition at line 43 of file DemoReel100.ino.
Referenced by loop(), and nextPattern().
gHue
uint8_t gHue = 0
Examples
DemoReel100.ino.
Definition at line 44 of file DemoReel100.ino.
Referenced by bpm(), confetti(), loop(), rainbow(), and sinelon().
gPatterns
SimplePatternList gPatterns = { rainbow, rainbowWithGlitter, confetti, sinelon, juggle, bpm }
Examples
DemoReel100.ino.
Definition at line 41 of file DemoReel100.ino.
{ rainbow, rainbowWithGlitter, confetti, sinelon, juggle, bpm };
Referenced by loop(), and nextPattern().
leds
CRGB leds[NUM_LEDS]
Definition at line 22 of file DemoReel100.ino.