FastLED: fl::scoped_array< T, Deleter > Class Template Reference
fl::scoped_array< T, Deleter > Class Template Reference
Detailed Description
template<typename T, typename Deleter = ArrayDeleter<T>>
class fl::scoped_array< T, Deleter >
Definition at line 92 of file scoped_ptr.h.
#include <scoped_ptr.h>
Public Member Functions
scoped_array (const scoped_array &)=delete
scoped_array (scoped_array &&other) noexcept
scoped_array (T *arr, Deleter deleter)
scoped_array (T *arr=nullptr)
~scoped_array ()
void clear ()
T * get () const
operator bool () const noexcept
bool operator! () const noexcept
scoped_array & operator= (const scoped_array &)=delete
scoped_array & operator= (scoped_array &&other) noexcept
T & operator[] (size_t i) const
T * release ()
void reset (T *arr=nullptr)
Private Attributes
T * arr_
Deleter deleter_ = {}
Constructor & Destructor Documentation
scoped_array() [1/4]
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::scoped_array (T * arr = nullptr) inline explicit
Definition at line 95 of file scoped_ptr.h.
: arr_(arr) {}
scoped_array() [2/4]
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::scoped_array (T * arr, Deleter deleter) inline
Definition at line 96 of file scoped_ptr.h.
: arr_(arr), deleter_(deleter) {}
~scoped_array()
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::~scoped_array () inline
Definition at line 99 of file scoped_ptr.h.
{ deleter_(arr_); }
References fl::scoped_array< T, Deleter >::arr_, and fl::scoped_array< T, Deleter >::deleter_.
scoped_array() [3/4]
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::scoped_array (const scoped_array< T, Deleter > &) delete
scoped_array() [4/4]
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::scoped_array (scoped_array< T, Deleter > && other) inline noexcept
Definition at line 106 of file scoped_ptr.h.
                                                : arr_(other.arr_), deleter_(other.deleter_) {
        other.arr_ = nullptr;
        other.deleter_ = {};
    }
Member Function Documentation
clear()
template<typename T , typename Deleter = ArrayDeleter<T>> void fl::scoped_array< T, Deleter >::clear () inline
Definition at line 141 of file scoped_ptr.h.
                 {
        reset();
    }
References fl::scoped_array< T, Deleter >::reset().
get()
template<typename T , typename Deleter = ArrayDeleter<T>> T * fl::scoped_array< T, Deleter >::get () const inline
Definition at line 124 of file scoped_ptr.h.
{ return arr_; }
References fl::scoped_array< T, Deleter >::arr_.
Referenced by fl::Frame::Frame(), fl::Frame::copy(), fl::Frame::draw(), fl::ScaleUp::draw(), fl::NoisePalette::fillnoise8(), fl::Frame::interpolate(), fl::NoisePalette::mapNoiseToLEDsUsingPalette(), fl::RectangularDrawBuffer::onQueuingDone(), fl::RectangularDrawBuffer::onQueuingStart(), fl::Frame::rgb(), and fl::Frame::rgb().
operator bool()
template<typename T , typename Deleter = ArrayDeleter<T>> fl::scoped_array< T, Deleter >::operator bool () const inline explicit noexcept
Definition at line 127 of file scoped_ptr.h.
{ return arr_ != nullptr; }
References fl::scoped_array< T, Deleter >::arr_.
operator!()
template<typename T , typename Deleter = ArrayDeleter<T>> bool fl::scoped_array< T, Deleter >::operator! () const inline noexcept
Definition at line 130 of file scoped_ptr.h.
{ return arr_ == nullptr; }
References fl::scoped_array< T, Deleter >::arr_.
operator=() [1/2]
template<typename T , typename Deleter = ArrayDeleter<T>> scoped_array & fl::scoped_array< T, Deleter >::operator= (const scoped_array< T, Deleter > &) delete
operator=() [2/2]
template<typename T , typename Deleter = ArrayDeleter<T>> scoped_array & fl::scoped_array< T, Deleter >::operator= (scoped_array< T, Deleter > && other) inline noexcept
Definition at line 112 of file scoped_ptr.h.
{
        if (this != &other) {
            reset(other.arr_);
            other.arr_ = nullptr;
        }
        return *this;
    }
References fl::scoped_array< T, Deleter >::reset().
operator[]()
template<typename T , typename Deleter = ArrayDeleter<T>> T & fl::scoped_array< T, Deleter >::operator[] (size_t i) const inline
Definition at line 121 of file scoped_ptr.h.
{ return arr_[i]; }
References fl::scoped_array< T, Deleter >::arr_.
release()
template<typename T , typename Deleter = ArrayDeleter<T>> T * fl::scoped_array< T, Deleter >::release () inline
Definition at line 145 of file scoped_ptr.h.
                 {
        T* tmp = arr_;
        arr_ = nullptr;
        return tmp;
    }
References fl::scoped_array< T, Deleter >::arr_.
Referenced by fl::Frame::~Frame(), fl::HeapVector< T >::ensure_size(), and fl::RectangularDrawBuffer::onQueuingDone().
reset()
template<typename T , typename Deleter = ArrayDeleter<T>> void fl::scoped_array< T, Deleter >::reset (T * arr = nullptr) inline
Definition at line 133 of file scoped_ptr.h.
{
        if (arr_ == arr) {
            return;
        }
        deleter_(arr_);
        arr_ = arr;
    }
References fl::scoped_array< T, Deleter >::arr_, and fl::scoped_array< T, Deleter >::deleter_.
Referenced by fl::Fire2012::Fire2012(), fl::Frame::Frame(), fl::scoped_array< T, Deleter >::clear(), fl::ScaleUp::draw(), fl::RectangularDrawBuffer::onQueuingDone(), and fl::scoped_array< T, Deleter >::operator=().
Member Data Documentation
arr_
template<typename T , typename Deleter = ArrayDeleter<T>> T* fl::scoped_array< T, Deleter >::arr_ private
Definition at line 152 of file scoped_ptr.h.
Referenced by fl::scoped_array< T, Deleter >::~scoped_array(), fl::scoped_array< T, Deleter >::get(), fl::scoped_array< T, Deleter >::operator bool(), fl::scoped_array< T, Deleter >::operator!(), fl::scoped_array< T, Deleter >::operator[](), fl::scoped_array< T, Deleter >::release(), and fl::scoped_array< T, Deleter >::reset().
deleter_
template<typename T , typename Deleter = ArrayDeleter<T>> Deleter fl::scoped_array< T, Deleter >::deleter_ = {} private
Definition at line 153 of file scoped_ptr.h.
{};
Referenced by fl::scoped_array< T, Deleter >::~scoped_array(), and fl::scoped_array< T, Deleter >::reset().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/scoped_ptr.h