FastLED: fl::UICheckbox Class Reference
fl::UICheckbox Class Reference
Detailed Description
Examples
FxEngine.ino.
Definition at line 94 of file ui.h.
#include <ui.h>
Public Member Functions
UICheckbox (const char *name, bool value=false)
~UICheckbox ()
operator bool () const
operator int () const
UICheckbox & operator= (bool value)
UICheckbox & operator= (int value)
Private Member Functions
void setValue (bool value)
Private Attributes
bool mValue
Constructor & Destructor Documentation
UICheckbox()
fl::UICheckbox::UICheckbox (const char * name, bool value = false) inline
Definition at line 96 of file ui.h.
                                                     : mValue(value) {
      FASTLED_UNUSED(name);
    }
References FASTLED_UNUSED.
~UICheckbox()
fl::UICheckbox::~UICheckbox () inline
Definition at line 99 of file ui.h.
{}
Member Function Documentation
operator bool()
fl::UICheckbox::operator bool () const inline
Definition at line 100 of file ui.h.
{ return mValue; }
References mValue.
operator int()
fl::UICheckbox::operator int () const inline
Definition at line 101 of file ui.h.
{ return mValue ? 1 : 0; }
References mValue.
operator=() [1/2]
UICheckbox & fl::UICheckbox::operator= (bool value) inline
Definition at line 102 of file ui.h.
{ setValue(value); return *this; }
References setValue().
operator=() [2/2]
UICheckbox & fl::UICheckbox::operator= (int value) inline
Definition at line 103 of file ui.h.
{ setValue(value != 0); return *this; }
References setValue().
setValue()
void fl::UICheckbox::setValue (bool value) inline private
Definition at line 105 of file ui.h.
{ mValue = value; }
References mValue.
Referenced by operator=(), and operator=().
Member Data Documentation
mValue
bool fl::UICheckbox::mValue private
Definition at line 106 of file ui.h.
Referenced by operator bool(), operator int(), and setValue().
The documentation for this class was generated from the following file:
/home/runner/work/FastLED/FastLED/src/fl/ui.h